"""A Court of Thorns and Roses — high-fidelity WorldStateV1 test fixture.

Quality checklist (all five causality modalities, varied force/evidence,
trait_target/trait_delta, state_timeline, rich beliefs, info edges, constants).
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_MORTAL_LANDS": Location(name="Mortal Lands",
            description="Impoverished human village near the Wall where Feyre's family lives.",
            ambient_state={"hardship": AmbientVector(value=0.8, volatility=0.3),
                           "cold": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_SPRING_COURT": Location(name="Spring Court",
            description="Tamlin's faerie estate of eternal spring, masking a curse.",
            ambient_state={"beauty": AmbientVector(value=0.8, volatility=0.3),
                           "hidden_dread": AmbientVector(value=0.5, volatility=0.4)}),
        "LOC_UNDER_THE_MOUNTAIN": Location(name="Under the Mountain",
            description="Amarantha's subterranean court where the High Lords are enslaved.",
            ambient_state={"terror": AmbientVector(value=0.9, volatility=0.2),
                           "oppression": AmbientVector(value=0.9, volatility=0.2)}),
        "LOC_WALL": Location(name="The Wall",
            description="Magical barrier separating mortal and faerie lands.",
            ambient_state={"foreboding": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_CALANMAI_CLEARING": Location(name="Calanmai Clearing",
            description="Ritual ground where the Great Rite is performed.",
            ambient_state={"magic": AmbientVector(value=0.9, volatility=0.4)}),
        "LOC_PRISON_CELL": Location(name="Prison Cell",
            description="Feyre's cell Under the Mountain during her trials.",
            ambient_state={"despair": AmbientVector(value=0.8, volatility=0.3)}),
        "LOC_FOREST": Location(name="Mortal Forest",
            description="The bleak woods near Feyre's cottage where she hunts.",
            ambient_state={"danger": AmbientVector(value=0.6, volatility=0.4),
                           "cold": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_NIGHT_COURT": Location(name="Night Court",
            description="Rhysand's hidden domain beyond Under the Mountain.",
            ambient_state={"mystery": AmbientVector(value=0.7, volatility=0.3)}),
    },
    objects={
        "OBJ_ASH_ARROW": NarrativeObject(id="OBJ_ASH_ARROW", name="Ash Arrow",
            location_id=None, owner_id="ENT_FEYRE",
            properties={"state": "bloodied", "material": "faerie_killing_ash"},
            affordances=[Affordance(action="kill_faerie", target_type="Entity")]),
        "OBJ_MASK": NarrativeObject(id="OBJ_MASK", name="Spring Court Mask",
            location_id="LOC_SPRING_COURT", owner_id="ENT_TAMLIN",
            properties={"state": "permanent", "material": "enchanted"},
            affordances=[Affordance(action="conceal_identity", target_type="Entity")]),
        "OBJ_BONE_KNIFE": NarrativeObject(id="OBJ_BONE_KNIFE", name="Bone Knife",
            location_id="LOC_UNDER_THE_MOUNTAIN", owner_id=None,
            properties={"state": "enchanted"},
            affordances=[Affordance(action="kill", target_type="Entity")]),
        "OBJ_GLAMOUR": NarrativeObject(id="OBJ_GLAMOUR", name="Glamour Enchantment",
            location_id="LOC_MORTAL_LANDS", owner_id=None,
            properties={"state": "active", "effect": "false_memories"},
            affordances=[Affordance(action="deceive", target_type="Entity")]),
    },
    entities={
        "ENT_FEYRE": Entity(id="ENT_FEYRE", name="Feyre Archeron",
            location_id="LOC_MORTAL_LANDS", status="healthy",
            traits={
                "determination": TraitVector(value=0.8, inertia=0.5),
                "self_sacrifice": TraitVector(value=0.7, inertia=0.4),
                "fear": TraitVector(value=0.4, inertia=0.2),
                "love": TraitVector(value=0.3, inertia=0.2),
                "resilience": TraitVector(value=0.7, inertia=0.5),
                "literacy": TraitVector(value=0.1, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_TAMLIN", perceived_state="Tamlin is a beast who imprisoned me",
                       confidence=0.7, inertia=0.3),
                Belief(target_id="ENT_AMARANTHA", perceived_state="Amarantha is a distant faerie threat",
                       confidence=0.4, inertia=0.2),
            ],
            constants=["huntress", "mortal_born"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_FEYRE_TAKEN",
                    traits={"fear": TraitVector(value=0.7, inertia=0.2)},
                    location_id="LOC_SPRING_COURT"),
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_FEYRE_FALLS_FOR_TAMLIN",
                    traits={"love": TraitVector(value=0.7, inertia=0.3)},
                    beliefs_invalidated=["ENT_TAMLIN"],
                    beliefs_added=[Belief(target_id="ENT_TAMLIN",
                        perceived_state="Tamlin loves me and I love him",
                        confidence=0.8, inertia=0.4, established_at_fabula=500)]),
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_FEYRE_ENTERS_MOUNTAIN",
                    traits={"fear": TraitVector(value=0.9, inertia=0.2),
                            "determination": TraitVector(value=0.9, inertia=0.5)},
                    location_id="LOC_UNDER_THE_MOUNTAIN"),
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_FEYRE_DIES_REBORN",
                    traits={"resilience": TraitVector(value=0.95, inertia=0.5)}),
            ]),
        "ENT_TAMLIN": Entity(id="ENT_TAMLIN", name="Tamlin",
            location_id="LOC_SPRING_COURT", status="healthy",
            traits={
                "power": TraitVector(value=0.8, inertia=0.5),
                "protectiveness": TraitVector(value=0.8, inertia=0.5),
                "rage": TraitVector(value=0.5, inertia=0.3),
                "vulnerability": TraitVector(value=0.4, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_FEYRE", perceived_state="Feyre could break the curse if she loves me",
                       confidence=0.6, inertia=0.4),
                Belief(target_id="ENT_AMARANTHA", perceived_state="Amarantha will destroy everything I love",
                       confidence=0.95, inertia=0.7),
            ],
            constants=["high_lord", "shapeshifter"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_FEYRE_SENT_HOME",
                    traits={"vulnerability": TraitVector(value=0.6, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_TAMLIN_CAPTURED",
                    traits={"vulnerability": TraitVector(value=0.8, inertia=0.3)},
                    location_id="LOC_UNDER_THE_MOUNTAIN"),
            ]),
        "ENT_LUCIEN": Entity(id="ENT_LUCIEN", name="Lucien Vanserra",
            location_id="LOC_SPRING_COURT", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.7, inertia=0.5),
                "wit": TraitVector(value=0.7, inertia=0.5),
                "caution": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_TAMLIN", perceived_state="Tamlin is my High Lord and friend",
                       confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_FEYRE", perceived_state="Feyre may be the one to break the curse",
                       confidence=0.5, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_TAMLIN_CAPTURED",
                    location_id="LOC_UNDER_THE_MOUNTAIN"),
            ]),
        "ENT_AMARANTHA": Entity(id="ENT_AMARANTHA", name="Amarantha",
            location_id="LOC_UNDER_THE_MOUNTAIN", status="healthy",
            traits={
                "cruelty": TraitVector(value=0.95, inertia=0.7),
                "power": TraitVector(value=0.9, inertia=0.6),
                "obsession": TraitVector(value=0.8, inertia=0.5),
                "vanity": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_TAMLIN", perceived_state="Tamlin will eventually love me",
                       confidence=0.6, inertia=0.4),
                Belief(target_id="ENT_FEYRE", perceived_state="This mortal is no threat to me",
                       confidence=0.7, inertia=0.3),
            ],
            constants=["high_fae"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_FEYRE_DIES_REBORN",
                    status="dead"),
            ]),
        "ENT_RHYSAND": Entity(id="ENT_RHYSAND", name="Rhysand",
            location_id="LOC_UNDER_THE_MOUNTAIN", status="healthy",
            traits={
                "cunning": TraitVector(value=0.9, inertia=0.6),
                "compassion": TraitVector(value=0.6, inertia=0.4),
                "power": TraitVector(value=0.9, inertia=0.6),
                "secrecy": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_FEYRE", perceived_state="Feyre is extraordinary and must be protected",
                       confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_AMARANTHA", perceived_state="Amarantha must be destroyed from within",
                       confidence=0.9, inertia=0.6),
            ],
            constants=["high_lord", "daemati"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_RHYSAND_BARGAIN",
                    traits={"compassion": TraitVector(value=0.7, inertia=0.4)}),
            ]),
        "ENT_ALIS": Entity(id="ENT_ALIS", name="Alis",
            location_id="LOC_SPRING_COURT", status="healthy",
            traits={
                "kindness": TraitVector(value=0.7, inertia=0.5),
                "fear": TraitVector(value=0.6, inertia=0.4),
                "protectiveness": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_FEYRE", perceived_state="Feyre can save us all",
                       confidence=0.6, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_ALIS_REVEALS_TRUTH",
                    traits={"fear": TraitVector(value=0.4, inertia=0.4)}),
            ]),
        "ENT_NESTA": Entity(id="ENT_NESTA", name="Nesta Archeron",
            location_id="LOC_MORTAL_LANDS", status="healthy",
            traits={
                "coldness": TraitVector(value=0.8, inertia=0.5),
                "fierce_love": TraitVector(value=0.7, inertia=0.5),
                "rage": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_FEYRE", perceived_state="Feyre sacrifices too much for this family",
                       confidence=0.7, inertia=0.4),
            ],
            constants=["glamour_resistant"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_NESTA_REVEALS_GLAMOUR",
                    traits={"rage": TraitVector(value=0.8, inertia=0.4)}),
            ]),
    },
    events=[
        EventNode(id="EVT_WOLF_KILLED", fabula_time=100, syuzhet_index=1, event_type="choice",
                  actor_ids=["ENT_FEYRE"], target_ids=[],
                  description="Feyre kills a wolf in the forest that turns out to be the faerie Andras."),
        EventNode(id="EVT_FEYRE_TAKEN", fabula_time=200, syuzhet_index=2, event_type="outcome",
                  actor_ids=["ENT_TAMLIN"], target_ids=["ENT_FEYRE"],
                  description="Tamlin takes Feyre to the Spring Court as punishment under the Treaty."),
        EventNode(id="EVT_SPRING_COURT_LIFE", fabula_time=300, syuzhet_index=3, event_type="outcome",
                  actor_ids=["ENT_FEYRE"], target_ids=[],
                  description="Feyre settles into Spring Court life, learning faerie customs and painting."),
        EventNode(id="EVT_CALANMAI", fabula_time=400, syuzhet_index=4, event_type="outcome",
                  actor_ids=["ENT_TAMLIN"], target_ids=["ENT_FEYRE"],
                  description="The Great Rite at Calanmai; Rhysand first encounters Feyre."),
        EventNode(id="EVT_FEYRE_FALLS_FOR_TAMLIN", fabula_time=500, syuzhet_index=5, event_type="outcome",
                  actor_ids=["ENT_FEYRE", "ENT_TAMLIN"], target_ids=[],
                  description="Feyre falls in love with Tamlin; they make love the night before she must leave."),
        EventNode(id="EVT_FEYRE_SENT_HOME", fabula_time=600, syuzhet_index=6, event_type="choice",
                  actor_ids=["ENT_TAMLIN"], target_ids=["ENT_FEYRE"],
                  description="Tamlin sends Feyre home to the human realm for her safety."),
        EventNode(id="EVT_NESTA_REVEALS_GLAMOUR", fabula_time=700, syuzhet_index=7, event_type="revelation",
                  actor_ids=["ENT_NESTA"], target_ids=["ENT_FEYRE"],
                  description="Nesta reveals the glamour didn't work on her and inspires Feyre to return."),
        EventNode(id="EVT_TAMLIN_CAPTURED", fabula_time=700, syuzhet_index=8, event_type="outcome",
                  actor_ids=["ENT_AMARANTHA"], target_ids=["ENT_TAMLIN", "ENT_LUCIEN"],
                  description="Amarantha captures Tamlin and Lucien, taking them Under the Mountain."),
        EventNode(id="EVT_ALIS_REVEALS_TRUTH", fabula_time=800, syuzhet_index=9, event_type="revelation",
                  actor_ids=["ENT_ALIS"], target_ids=["ENT_FEYRE"],
                  description="Alis reveals the curse: a human who hated fae must declare love for Tamlin."),
        EventNode(id="EVT_FEYRE_ENTERS_MOUNTAIN", fabula_time=900, syuzhet_index=10, event_type="choice",
                  actor_ids=["ENT_FEYRE"], target_ids=["ENT_AMARANTHA"],
                  description="Feyre journeys Under the Mountain to save Tamlin and face Amarantha's trials."),
        EventNode(id="EVT_RHYSAND_BARGAIN", fabula_time=900, syuzhet_index=11, event_type="choice",
                  actor_ids=["ENT_RHYSAND"], target_ids=["ENT_FEYRE"],
                  description="Rhysand heals Feyre and strikes a bargain: a week per month at the Night Court."),
        EventNode(id="EVT_FIRST_TRIAL", fabula_time=1000, syuzhet_index=12, event_type="outcome",
                  actor_ids=["ENT_FEYRE"], target_ids=[],
                  description="Feyre survives the first trial against a giant worm in the labyrinth."),
        EventNode(id="EVT_SECOND_TRIAL", fabula_time=1050, syuzhet_index=13, event_type="choice",
                  actor_ids=["ENT_FEYRE"], target_ids=["ENT_LUCIEN"],
                  description="Feyre solves the puzzle to save herself and Lucien, aided by Rhysand's voice."),
        EventNode(id="EVT_FEYRE_KILLS_INNOCENTS", fabula_time=1100, syuzhet_index=14, event_type="choice",
                  actor_ids=["ENT_FEYRE"], target_ids=[],
                  description="Feyre is forced to kill two innocent faeries during the third trial."),
        EventNode(id="EVT_FEYRE_STABS_TAMLIN", fabula_time=1150, syuzhet_index=15, event_type="choice",
                  actor_ids=["ENT_FEYRE"], target_ids=["ENT_TAMLIN"],
                  description="Feyre stabs Tamlin with the ash dagger, trusting his heart is literally stone."),
        EventNode(id="EVT_FEYRE_SOLVES_RIDDLE", fabula_time=1200, syuzhet_index=16, event_type="revelation",
                  actor_ids=["ENT_FEYRE"], target_ids=["ENT_AMARANTHA"],
                  description="Feyre speaks the answer — love — as Amarantha beats her to death."),
        EventNode(id="EVT_FEYRE_DIES_REBORN", fabula_time=1300, syuzhet_index=17, event_type="outcome",
                  actor_ids=["ENT_RHYSAND"], target_ids=["ENT_FEYRE"],
                  description="Feyre dies and is resurrected by the seven High Lords as an immortal High Fae."),
    ],
    causal_topology=[
        # chain_reaction (12)
        CausalEdge(source_id="EVT_WOLF_KILLED", target_id="EVT_FEYRE_TAKEN",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=9.0, fabula_time=100),
        CausalEdge(source_id="EVT_FEYRE_TAKEN", target_id="EVT_SPRING_COURT_LIFE",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200),
        CausalEdge(source_id="EVT_SPRING_COURT_LIFE", target_id="EVT_FEYRE_FALLS_FOR_TAMLIN",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300),
        CausalEdge(source_id="EVT_FEYRE_FALLS_FOR_TAMLIN", target_id="EVT_FEYRE_SENT_HOME",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=500),
        CausalEdge(source_id="EVT_NESTA_REVEALS_GLAMOUR", target_id="EVT_FEYRE_ENTERS_MOUNTAIN",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700),
        CausalEdge(source_id="EVT_TAMLIN_CAPTURED", target_id="EVT_FEYRE_ENTERS_MOUNTAIN",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=700),
        CausalEdge(source_id="EVT_FEYRE_ENTERS_MOUNTAIN", target_id="EVT_FIRST_TRIAL",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900),
        CausalEdge(source_id="EVT_FIRST_TRIAL", target_id="EVT_SECOND_TRIAL",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1000),
        CausalEdge(source_id="EVT_SECOND_TRIAL", target_id="EVT_FEYRE_KILLS_INNOCENTS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1050),
        CausalEdge(source_id="EVT_FEYRE_KILLS_INNOCENTS", target_id="EVT_FEYRE_STABS_TAMLIN",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=1100),
        CausalEdge(source_id="EVT_FEYRE_STABS_TAMLIN", target_id="EVT_FEYRE_SOLVES_RIDDLE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1150),
        CausalEdge(source_id="EVT_FEYRE_SOLVES_RIDDLE", target_id="EVT_FEYRE_DIES_REBORN",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1200),
        # mutation (7)
        CausalEdge(source_id="EVT_FEYRE_TAKEN", target_id="ENT_FEYRE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200, trait_target="fear", trait_delta=0.3),
        CausalEdge(source_id="EVT_FEYRE_FALLS_FOR_TAMLIN", target_id="ENT_FEYRE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500, trait_target="love", trait_delta=0.4),
        CausalEdge(source_id="EVT_FEYRE_ENTERS_MOUNTAIN", target_id="ENT_FEYRE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900, trait_target="determination", trait_delta=0.1),
        CausalEdge(source_id="EVT_FEYRE_KILLS_INNOCENTS", target_id="ENT_FEYRE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1100, trait_target="resilience", trait_delta=-0.2),
        CausalEdge(source_id="EVT_TAMLIN_CAPTURED", target_id="ENT_TAMLIN",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700, trait_target="vulnerability", trait_delta=0.4),
        CausalEdge(source_id="EVT_ALIS_REVEALS_TRUTH", target_id="ENT_FEYRE",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=800, trait_target="determination", trait_delta=0.1),
        CausalEdge(source_id="EVT_FEYRE_DIES_REBORN", target_id="ENT_FEYRE",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1300, trait_target="resilience", trait_delta=0.25),
        # mutation_social (4)
        CausalEdge(source_id="EVT_FEYRE_FALLS_FOR_TAMLIN", target_id="ENT_FEYRE",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500,
                   trait_target="affinity", trait_delta=0.6, rel_counterpart_id="ENT_TAMLIN"),
        CausalEdge(source_id="EVT_RHYSAND_BARGAIN", target_id="ENT_FEYRE",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=900,
                   trait_target="affinity", trait_delta=0.2, rel_counterpart_id="ENT_RHYSAND"),
        CausalEdge(source_id="EVT_FEYRE_DIES_REBORN", target_id="ENT_FEYRE",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1300,
                   trait_target="power_dynamic", trait_delta=0.4, rel_counterpart_id="ENT_TAMLIN"),
        CausalEdge(source_id="EVT_TAMLIN_CAPTURED", target_id="ENT_LUCIEN",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=700,
                   trait_target="fear", trait_delta=0.3, rel_counterpart_id="ENT_AMARANTHA"),
        # affordance_gate (3)
        CausalEdge(source_id="OBJ_ASH_ARROW", target_id="EVT_WOLF_KILLED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="ENT_RHYSAND", target_id="EVT_RHYSAND_BARGAIN",
                   causality_type="affordance_gate", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900),
        CausalEdge(source_id="ENT_AMARANTHA", target_id="EVT_FIRST_TRIAL",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1000),
        # ambient_propagation (2)
        CausalEdge(source_id="LOC_UNDER_THE_MOUNTAIN", target_id="ENT_FEYRE",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=900),
        CausalEdge(source_id="LOC_SPRING_COURT", target_id="ENT_FEYRE",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=300),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_MORTAL_LANDS", target_id="LOC_WALL"),
        SpatialEdge(source_id="LOC_MORTAL_LANDS", target_id="LOC_FOREST"),
        SpatialEdge(source_id="LOC_WALL", target_id="LOC_SPRING_COURT"),
        SpatialEdge(source_id="LOC_SPRING_COURT", target_id="LOC_CALANMAI_CLEARING"),
        SpatialEdge(source_id="LOC_SPRING_COURT", target_id="LOC_UNDER_THE_MOUNTAIN"),
        SpatialEdge(source_id="LOC_UNDER_THE_MOUNTAIN", target_id="LOC_PRISON_CELL"),
        SpatialEdge(source_id="LOC_UNDER_THE_MOUNTAIN", target_id="LOC_NIGHT_COURT"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_ALIS", target_ids=["ENT_FEYRE"],
                        medium="whisper", established_at_fabula=300),
        InformationEdge(source_id="ENT_RHYSAND", target_ids=["ENT_FEYRE"],
                        medium="mind_link", established_at_fabula=900),
        InformationEdge(source_id="ENT_LUCIEN", target_ids=["ENT_FEYRE"],
                        medium="conversation", established_at_fabula=300),
        InformationEdge(source_id="ENT_NESTA", target_ids=["ENT_FEYRE"],
                        medium="confrontation", established_at_fabula=700),
        InformationEdge(source_id="ENT_ALIS", target_ids=["ENT_FEYRE"],
                        medium="curse_revelation", established_at_fabula=800),
    ],
    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_AMARANTHAS_CURSE": GlobalTrait(
            id="WORLD_AMARANTHAS_CURSE",
            name="Amarantha's Curse",
            description="Amarantha's curse strips the High Lords of their power and enslaves Prythian Under the Mountain, spreading blight and despair across the fae lands.",
            category="magic_system",
            magnitude=TraitVector(value=0.9, inertia=0.7),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=1200, triggered_by="EVT_FEYRE_BREAKS_CURSE",
                    magnitude=TraitVector(value=0.0, inertia=0.1),
                    description="Feyre's declaration of love breaks the curse, freeing all the courts."),
            ],
        ),
        "WORLD_FAE_MORTAL_WALL": GlobalTrait(
            id="WORLD_FAE_MORTAL_WALL",
            name="The Wall Between Fae and Mortal",
            description="An ancient magical barrier separating the human lands from Prythian. Crossing it transforms identity and allegiance.",
            category="magic_system",
            magnitude=TraitVector(value=0.8, inertia=0.8),
            affected_domains=["social", "epistemic"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=200, triggered_by="EVT_FEYRE_TAKEN",
                    magnitude=TraitVector(value=0.7, inertia=0.7),
                    description="Feyre crosses the Wall, beginning her transformation from mortal hunter to fae ally."),
            ],
        ),
    },
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_FEYRE", target_entity_id="ENT_TAMLIN",
                         affinity=0.7, fear=0.1, power_dynamic=-0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_TAMLIN", target_entity_id="ENT_FEYRE",
                         affinity=0.7, fear=0.2, power_dynamic=0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_FEYRE", target_entity_id="ENT_RHYSAND",
                         affinity=0.1, fear=0.3, power_dynamic=-0.4, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_RHYSAND", target_entity_id="ENT_FEYRE",
                         affinity=0.5, fear=0.0, power_dynamic=0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_AMARANTHA", target_entity_id="ENT_TAMLIN",
                         affinity=0.5, fear=0.0, power_dynamic=0.7, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_TAMLIN", target_entity_id="ENT_AMARANTHA",
                         affinity=-0.8, fear=0.6, power_dynamic=-0.7, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_FEYRE", target_entity_id="ENT_LUCIEN",
                         affinity=0.5, fear=0.0, power_dynamic=0.0, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_LUCIEN", target_entity_id="ENT_TAMLIN",
                         affinity=0.7, fear=0.1, power_dynamic=-0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_FEYRE", target_entity_id="ENT_NESTA",
                         affinity=0.5, fear=0.0, power_dynamic=0.0, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_AMARANTHA", target_entity_id="ENT_FEYRE",
                         affinity=-0.8, fear=0.0, power_dynamic=0.8, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_LUCIEN", target_entity_id="ENT_AMARANTHA",
                         affinity=-0.6, fear=0.5, power_dynamic=-0.6, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_RHYSAND", target_entity_id="ENT_AMARANTHA",
                         affinity=-0.7, fear=0.2, power_dynamic=-0.3, inertia=0.5),
    ],
)
"""A Court of Thorns and Roses — high-fidelity WorldStateV1 test fixture."""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait,
)

world_state = WorldStateV1(
    locations={
        "LOC_MORTAL_LANDS": Location(name="Mortal Lands", description="Impoverished human village near the Wall where Feyre's family lives.",
            ambient_state={"hardship": AmbientVector(value=0.8, volatility=0.3), "cold": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_SPRING_COURT": Location(name="Spring Court", description="Tamlin's faerie estate of eternal spring, masking a curse.",
            ambient_state={"beauty": AmbientVector(value=0.8, volatility=0.3), "hidden_dread": AmbientVector(value=0.5, volatility=0.4)}),
        "LOC_UNDER_THE_MOUNTAIN": Location(name="Under the Mountain", description="Amarantha's subterranean court where the High Lords are enslaved.",
            ambient_state={"terror": AmbientVector(value=0.9, volatility=0.2), "oppression": AmbientVector(value=0.9, volatility=0.2)}),
        "LOC_WALL": Location(name="The Wall", description="Magical barrier separating mortal and faerie lands.",
            ambient_state={"foreboding": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_CALANMAI_CLEARING": Location(name="Calanmai Clearing", description="Ritual ground where the Great Rite is performed.",
            ambient_state={"magic": AmbientVector(value=0.9, volatility=0.4)}),
        "LOC_PRISON_CELL": Location(name="Prison Cell", description="Feyre's cell Under the Mountain during her trials.",
            ambient_state={"despair": AmbientVector(value=0.8, volatility=0.3)}),
    },
    objects={
        "OBJ_ASH_ARROW": NarrativeObject(id="OBJ_ASH_ARROW", name="Ash Arrow",
            location_id=None, owner_id="ENT_FEYRE",
            properties={"state": "bloodied", "material": "faerie_killing_ash"},
            affordances=[Affordance(action="kill_faerie", target_type="Entity")]),
        "OBJ_MASK": NarrativeObject(id="OBJ_MASK", name="Spring Court Mask",
            location_id="LOC_SPRING_COURT", owner_id="ENT_TAMLIN",
            properties={"state": "permanent", "material": "enchanted"},
            affordances=[Affordance(action="conceal_identity", target_type="Entity")]),
        "OBJ_BONE_KNIFE": NarrativeObject(id="OBJ_BONE_KNIFE", name="Bone Knife",
            location_id="LOC_UNDER_THE_MOUNTAIN", owner_id=None,
            properties={"state": "enchanted"},
            affordances=[Affordance(action="kill", target_type="Entity")]),
    },
    entities={
        "ENT_FEYRE": Entity(id="ENT_FEYRE", name="Feyre Archeron",
            location_id="LOC_MORTAL_LANDS", status="healthy",
            traits={
                "determination": TraitVector(value=0.8, inertia=0.5),
                "self_sacrifice": TraitVector(value=0.7, inertia=0.4),
                "fear": TraitVector(value=0.4, inertia=0.2),
                "love": TraitVector(value=0.3, inertia=0.2),
                "resilience": TraitVector(value=0.7, inertia=0.5),
                "literacy": TraitVector(value=0.1, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_TAMLIN", perceived_state="Tamlin is a beast who imprisoned me", confidence=0.7, inertia=0.3),
                Belief(target_id="ENT_AMARANTHA", perceived_state="Amarantha is a distant faerie threat", confidence=0.4, inertia=0.2),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_FEYRE_TAKEN",
                    traits={"fear": TraitVector(value=0.7, inertia=0.2)},
                    location_id="LOC_SPRING_COURT"),
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_FEYRE_FALLS_FOR_TAMLIN",
                    traits={"love": TraitVector(value=0.7, inertia=0.3)},
                    beliefs_invalidated=["ENT_TAMLIN"]),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_FEYRE_UNDER_MOUNTAIN",
                    traits={"fear": TraitVector(value=0.9, inertia=0.2), "determination": TraitVector(value=0.9, inertia=0.5)},
                    location_id="LOC_UNDER_THE_MOUNTAIN"),
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_FEYRE_DIES_REBORN",
                    traits={"resilience": TraitVector(value=0.9, inertia=0.5)}, status="healthy"),
            ]),
        "ENT_TAMLIN": Entity(id="ENT_TAMLIN", name="Tamlin",
            location_id="LOC_SPRING_COURT", status="healthy",
            traits={
                "power": TraitVector(value=0.8, inertia=0.5),
                "protectiveness": TraitVector(value=0.8, inertia=0.5),
                "rage": TraitVector(value=0.5, inertia=0.3),
                "vulnerability": TraitVector(value=0.4, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_FEYRE", perceived_state="Feyre could break the curse if she loves me", confidence=0.6, inertia=0.4),
                Belief(target_id="ENT_AMARANTHA", perceived_state="Amarantha will destroy everything I love", confidence=0.95, inertia=0.7),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_TAMLIN_CAPTURED",
                    traits={"vulnerability": TraitVector(value=0.8, inertia=0.3)},
                    location_id="LOC_UNDER_THE_MOUNTAIN"),
            ]),
        "ENT_LUCIEN": Entity(id="ENT_LUCIEN", name="Lucien Vanserra",
            location_id="LOC_SPRING_COURT", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.7, inertia=0.5),
                "wit": TraitVector(value=0.7, inertia=0.5),
                "caution": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_TAMLIN", perceived_state="Tamlin is my High Lord and friend", confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_FEYRE", perceived_state="Feyre may be the one to break the curse", confidence=0.5, inertia=0.3),
            ]),
        "ENT_AMARANTHA": Entity(id="ENT_AMARANTHA", name="Amarantha",
            location_id="LOC_UNDER_THE_MOUNTAIN", status="healthy",
            traits={
                "cruelty": TraitVector(value=0.95, inertia=0.7),
                "power": TraitVector(value=0.9, inertia=0.6),
                "obsession": TraitVector(value=0.8, inertia=0.5),
                "vanity": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_TAMLIN", perceived_state="Tamlin will eventually love me", confidence=0.6, inertia=0.4),
                Belief(target_id="ENT_FEYRE", perceived_state="This mortal is no threat to me", confidence=0.7, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_FEYRE_DIES_REBORN", status="dead"),
            ]),
        "ENT_RHYSAND": Entity(id="ENT_RHYSAND", name="Rhysand",
            location_id="LOC_UNDER_THE_MOUNTAIN", status="healthy",
            traits={
                "cunning": TraitVector(value=0.9, inertia=0.6),
                "compassion": TraitVector(value=0.6, inertia=0.4),
                "power": TraitVector(value=0.9, inertia=0.6),
                "secrecy": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_FEYRE", perceived_state="Feyre is extraordinary and must be protected", confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_AMARANTHA", perceived_state="Amarantha must be destroyed from within", confidence=0.9, inertia=0.6),
            ]),
        "ENT_ALIS": Entity(id="ENT_ALIS", name="Alis",
            location_id="LOC_SPRING_COURT", status="healthy",
            traits={
                "kindness": TraitVector(value=0.7, inertia=0.5),
                "fear": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_FEYRE", perceived_state="Feyre can save us all", confidence=0.6, inertia=0.3),
            ]),
        "ENT_NESTA": Entity(id="ENT_NESTA", name="Nesta Archeron",
            location_id="LOC_MORTAL_LANDS", status="healthy",
            traits={
                "coldness": TraitVector(value=0.8, inertia=0.5),
                "fierce_love": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_FEYRE", perceived_state="Feyre sacrifices too much for this family", confidence=0.7, inertia=0.4),
            ]),
    },
    events=[
        EventNode(id="EVT_WOLF_KILLED", fabula_time=100, syuzhet_index=1, event_type="choice",
                  actor_ids=["ENT_FEYRE"], target_ids=[],
                  description="Feyre kills a wolf in the forest that turns out to be a faerie."),
        EventNode(id="EVT_FEYRE_TAKEN", fabula_time=200, syuzhet_index=2, event_type="outcome",
                  actor_ids=["ENT_TAMLIN"], target_ids=["ENT_FEYRE"],
                  description="Tamlin takes Feyre to the Spring Court as punishment for killing the faerie."),
        EventNode(id="EVT_SPRING_COURT_LIFE", fabula_time=300, syuzhet_index=3, event_type="outcome",
                  actor_ids=["ENT_FEYRE"], target_ids=[],
                  description="Feyre settles into Spring Court life, learning about the faerie world."),
        EventNode(id="EVT_CALANMAI", fabula_time=400, syuzhet_index=4, event_type="outcome",
                  actor_ids=["ENT_TAMLIN"], target_ids=["ENT_FEYRE"],
                  description="The Great Rite at Calanmai; Rhysand first encounters Feyre."),
        EventNode(id="EVT_FEYRE_FALLS_FOR_TAMLIN", fabula_time=500, syuzhet_index=5, event_type="outcome",
                  actor_ids=["ENT_FEYRE", "ENT_TAMLIN"], target_ids=[],
                  description="Feyre falls in love with Tamlin and nearly breaks the curse."),
        EventNode(id="EVT_TAMLIN_CAPTURED", fabula_time=600, syuzhet_index=6, event_type="outcome",
                  actor_ids=["ENT_AMARANTHA"], target_ids=["ENT_TAMLIN"],
                  description="Amarantha captures Tamlin and takes him Under the Mountain."),
        EventNode(id="EVT_FEYRE_UNDER_MOUNTAIN", fabula_time=700, syuzhet_index=7, event_type="choice",
                  actor_ids=["ENT_FEYRE"], target_ids=["ENT_AMARANTHA"],
                  description="Feyre goes Under the Mountain to save Tamlin and face Amarantha's trials."),
        EventNode(id="EVT_RHYSAND_BARGAIN", fabula_time=750, syuzhet_index=8, event_type="choice",
                  actor_ids=["ENT_RHYSAND"], target_ids=["ENT_FEYRE"],
                  description="Rhysand strikes a bargain with Feyre, secretly helping her survive."),
        EventNode(id="EVT_RIDDLE_TRIAL", fabula_time=800, syuzhet_index=9, event_type="choice",
                  actor_ids=["ENT_FEYRE"], target_ids=["ENT_AMARANTHA"],
                  description="Feyre faces Amarantha's trials and the final riddle."),
        EventNode(id="EVT_FEYRE_KILLS_INNOCENTS", fabula_time=850, syuzhet_index=10, event_type="choice",
                  actor_ids=["ENT_FEYRE"], target_ids=[],
                  description="Feyre is forced to kill two innocent faeries during the trials."),
        EventNode(id="EVT_FEYRE_SOLVES_RIDDLE", fabula_time=900, syuzhet_index=11, event_type="revelation",
                  actor_ids=["ENT_FEYRE"], target_ids=["ENT_AMARANTHA"],
                  description="Feyre solves the riddle — the answer is love."),
        EventNode(id="EVT_FEYRE_DIES_REBORN", fabula_time=1000, syuzhet_index=12, event_type="outcome",
                  actor_ids=["ENT_AMARANTHA", "ENT_RHYSAND"], target_ids=["ENT_FEYRE"],
                  description="Amarantha kills Feyre; the High Lords resurrect her as High Fae."),
    ],
    causal_topology=[
        # chain_reaction
        CausalEdge(source_id="EVT_WOLF_KILLED", target_id="EVT_FEYRE_TAKEN",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=9.0, fabula_time=100),
        CausalEdge(source_id="EVT_FEYRE_TAKEN", target_id="EVT_SPRING_COURT_LIFE",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200),
        CausalEdge(source_id="EVT_SPRING_COURT_LIFE", target_id="EVT_FEYRE_FALLS_FOR_TAMLIN",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300),
        CausalEdge(source_id="EVT_FEYRE_FALLS_FOR_TAMLIN", target_id="EVT_TAMLIN_CAPTURED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=500),
        CausalEdge(source_id="EVT_TAMLIN_CAPTURED", target_id="EVT_FEYRE_UNDER_MOUNTAIN",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=600),
        CausalEdge(source_id="EVT_FEYRE_UNDER_MOUNTAIN", target_id="EVT_RIDDLE_TRIAL",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700),
        CausalEdge(source_id="EVT_RIDDLE_TRIAL", target_id="EVT_FEYRE_KILLS_INNOCENTS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=800),
        CausalEdge(source_id="EVT_FEYRE_KILLS_INNOCENTS", target_id="EVT_FEYRE_SOLVES_RIDDLE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=850),
        CausalEdge(source_id="EVT_FEYRE_SOLVES_RIDDLE", target_id="EVT_FEYRE_DIES_REBORN",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=900),
        # mutation
        CausalEdge(source_id="EVT_FEYRE_TAKEN", target_id="ENT_FEYRE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200, trait_target="fear", trait_delta=0.3),
        CausalEdge(source_id="EVT_FEYRE_FALLS_FOR_TAMLIN", target_id="ENT_FEYRE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500, trait_target="love", trait_delta=0.4),
        CausalEdge(source_id="EVT_FEYRE_UNDER_MOUNTAIN", target_id="ENT_FEYRE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700, trait_target="determination", trait_delta=0.1),
        CausalEdge(source_id="EVT_FEYRE_KILLS_INNOCENTS", target_id="ENT_FEYRE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=850, trait_target="resilience", trait_delta=-0.2),
        CausalEdge(source_id="EVT_TAMLIN_CAPTURED", target_id="ENT_TAMLIN",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600, trait_target="vulnerability", trait_delta=0.4),
        # mutation_social
        CausalEdge(source_id="EVT_FEYRE_FALLS_FOR_TAMLIN", target_id="ENT_FEYRE",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500, trait_target="affinity", trait_delta=0.6, rel_counterpart_id="ENT_TAMLIN"),
        CausalEdge(source_id="EVT_RHYSAND_BARGAIN", target_id="ENT_FEYRE",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=750, trait_target="affinity", trait_delta=0.2, rel_counterpart_id="ENT_RHYSAND"),
        CausalEdge(source_id="EVT_FEYRE_DIES_REBORN", target_id="ENT_FEYRE",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1000, trait_target="power_dynamic", trait_delta=0.4, rel_counterpart_id="ENT_TAMLIN"),
        # affordance_gate
        CausalEdge(source_id="OBJ_ASH_ARROW", target_id="EVT_WOLF_KILLED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="ENT_RHYSAND", target_id="EVT_RHYSAND_BARGAIN",
                   causality_type="affordance_gate", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=750),
        CausalEdge(source_id="ENT_AMARANTHA", target_id="EVT_RIDDLE_TRIAL",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=800),
        # ambient_propagation
        CausalEdge(source_id="LOC_UNDER_THE_MOUNTAIN", target_id="ENT_FEYRE",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=700),
        CausalEdge(source_id="LOC_SPRING_COURT", target_id="ENT_FEYRE",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=300),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_MORTAL_LANDS", target_id="LOC_WALL"),
        SpatialEdge(source_id="LOC_WALL", target_id="LOC_SPRING_COURT"),
        SpatialEdge(source_id="LOC_SPRING_COURT", target_id="LOC_CALANMAI_CLEARING"),
        SpatialEdge(source_id="LOC_SPRING_COURT", target_id="LOC_UNDER_THE_MOUNTAIN"),
        SpatialEdge(source_id="LOC_UNDER_THE_MOUNTAIN", target_id="LOC_PRISON_CELL"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_ALIS", target_ids=["ENT_FEYRE"], medium="whisper", established_at_fabula=300),
        InformationEdge(source_id="ENT_RHYSAND", target_ids=["ENT_FEYRE"], medium="mind_link", established_at_fabula=750),
        InformationEdge(source_id="ENT_LUCIEN", target_ids=["ENT_FEYRE"], medium="conversation", established_at_fabula=300),
    ],
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_FEYRE", target_entity_id="ENT_TAMLIN", affinity=0.7, fear=0.1, power_dynamic=-0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_TAMLIN", target_entity_id="ENT_FEYRE", affinity=0.7, fear=0.2, power_dynamic=0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_FEYRE", target_entity_id="ENT_RHYSAND", affinity=0.1, fear=0.3, power_dynamic=-0.4, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_RHYSAND", target_entity_id="ENT_FEYRE", affinity=0.5, fear=0.0, power_dynamic=0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_AMARANTHA", target_entity_id="ENT_TAMLIN", affinity=0.5, fear=0.0, power_dynamic=0.7, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_TAMLIN", target_entity_id="ENT_AMARANTHA", affinity=-0.8, fear=0.6, power_dynamic=-0.7, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_FEYRE", target_entity_id="ENT_LUCIEN", affinity=0.5, fear=0.0, power_dynamic=0.0, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_LUCIEN", target_entity_id="ENT_TAMLIN", affinity=0.7, fear=0.1, power_dynamic=-0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_FEYRE", target_entity_id="ENT_NESTA", affinity=0.5, fear=0.0, power_dynamic=0.0, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_AMARANTHA", target_entity_id="ENT_FEYRE", affinity=-0.8, fear=0.0, power_dynamic=0.8, inertia=0.4),
    ],
)
