"""A Fish Called Wanda — high-fidelity WorldStateV1 test fixture."""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_HEATHROW": Location(name="Heathrow Safe-Deposit", description="Where the stolen diamonds are initially stored.",
            ambient_state={"tension": AmbientVector(value=0.7, volatility=0.4)}),
        "LOC_ARCHIE_FLAT": Location(name="Archie Leach's Chambers", description="Archie's barrister chambers and flat.",
            ambient_state={"respectability": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_GEORGE_FLAT": Location(name="George's Flat", description="George Thomason's flat where the gang meets.",
            ambient_state={"tension": AmbientVector(value=0.6, volatility=0.4)}),
        "LOC_WANDA_FLAT": Location(name="Wanda's Flat", description="Wanda's London flat where she keeps the locket.",
            ambient_state={"deception": AmbientVector(value=0.7, volatility=0.4)}),
        "LOC_OLD_BAILEY": Location(name="Old Bailey", description="Criminal court where George is tried.",
            ambient_state={"formality": AmbientVector(value=0.8, volatility=0.2)}),
        "LOC_HIDEOUT_GARAGE": Location(name="Hideout Garage", description="Garage where Ken keeps his fish tanks.",
            ambient_state={"tension": AmbientVector(value=0.5, volatility=0.4)}),
    },
    objects={
        "OBJ_DIAMONDS": NarrativeObject(id="OBJ_DIAMONDS", name="Stolen Diamonds",
            location_id="LOC_HEATHROW", owner_id=None,
            properties={"state": "hidden", "value": "thirteen_million"},
            affordances=[Affordance(action="retrieve", target_type="Entity"), Affordance(action="leverage", target_type="Entity")]),
        "OBJ_LOCKET": NarrativeObject(id="OBJ_LOCKET", name="Safe-Deposit Key in Locket",
            location_id=None, owner_id="ENT_WANDA",
            properties={"state": "worn", "content": "safe_deposit_key"},
            affordances=[Affordance(action="unlock_diamonds", target_type="Entity")]),
        "OBJ_STEAMROLLER": NarrativeObject(id="OBJ_STEAMROLLER", name="Steamroller",
            location_id=None, owner_id=None,
            properties={"state": "operational"},
            affordances=[Affordance(action="crush", target_type="Entity")]),
    },
    entities={
        "ENT_WANDA": Entity(id="ENT_WANDA", name="Wanda Gershwitz",
            location_id="LOC_WANDA_FLAT", status="healthy",
            traits={
                "cunning": TraitVector(value=0.9, inertia=0.5),
                "seductiveness": TraitVector(value=0.85, inertia=0.5),
                "greed": TraitVector(value=0.8, inertia=0.5),
                "linguistic_arousal": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_OTTO", perceived_state="Otto is useful but expendable", confidence=0.8, inertia=0.4),
                Belief(target_id="ENT_ARCHIE", perceived_state="Archie has information I need", confidence=0.7, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_WANDA_SEDUCES_ARCHIE",
                    traits={"cunning": TraitVector(value=0.9, inertia=0.5)},
                    beliefs_added=[Belief(target_id="ENT_ARCHIE", perceived_state="Archie is genuinely attractive", confidence=0.6, inertia=0.3)]),
            ]),
        "ENT_OTTO": Entity(id="ENT_OTTO", name="Otto West",
            location_id="LOC_GEORGE_FLAT", status="healthy",
            traits={
                "jealousy": TraitVector(value=0.8, inertia=0.4),
                "stupidity": TraitVector(value=0.7, inertia=0.6),
                "aggression": TraitVector(value=0.8, inertia=0.4),
                "pseudo_intellectualism": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_WANDA", perceived_state="Wanda is my girlfriend and loyal to me", confidence=0.7, inertia=0.3),
                Belief(target_id="ENT_KEN", perceived_state="Ken is an idiot I can bully", confidence=0.8, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_OTTO_DISCOVERS_BETRAYAL",
                    traits={"jealousy": TraitVector(value=0.95, inertia=0.4), "aggression": TraitVector(value=0.9, inertia=0.4)}),
            ]),
        "ENT_KEN": Entity(id="ENT_KEN", name="Ken Pile",
            location_id="LOC_HIDEOUT_GARAGE", status="healthy",
            traits={
                "kindness": TraitVector(value=0.8, inertia=0.5),
                "stutter": TraitVector(value=0.7, inertia=0.6),
                "devotion_to_animals": TraitVector(value=0.9, inertia=0.6),
                "determination": TraitVector(value=0.5, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_GEORGE", perceived_state="George is my boss and I am loyal to him", confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_OTTO", perceived_state="Otto is Wanda's brother", confidence=0.8, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_KEN_KILLS_DOGS",
                    traits={"devotion_to_animals": TraitVector(value=0.95, inertia=0.6), "determination": TraitVector(value=0.7, inertia=0.3)}),
            ]),
        "ENT_GEORGE": Entity(id="ENT_GEORGE", name="George Thomason",
            location_id="LOC_GEORGE_FLAT", status="healthy",
            traits={
                "professionalism": TraitVector(value=0.7, inertia=0.5),
                "calm": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_KEN", perceived_state="Ken is loyal and reliable", confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_OTTO", perceived_state="Otto and Wanda are siblings", confidence=0.9, inertia=0.5),
            ]),
        "ENT_ARCHIE": Entity(id="ENT_ARCHIE", name="Archie Leach",
            location_id="LOC_ARCHIE_FLAT", status="healthy",
            traits={
                "propriety": TraitVector(value=0.7, inertia=0.5),
                "repression": TraitVector(value=0.7, inertia=0.4),
                "charm": TraitVector(value=0.6, inertia=0.4),
                "passion": TraitVector(value=0.3, inertia=0.2),
            },
            beliefs=[
                Belief(target_id="ENT_WANDA", perceived_state="Wanda finds me irresistible", confidence=0.6, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_WANDA_SEDUCES_ARCHIE",
                    traits={"passion": TraitVector(value=0.7, inertia=0.3), "repression": TraitVector(value=0.4, inertia=0.4)}),
            ]),
        "ENT_MRS_COADY": Entity(id="ENT_MRS_COADY", name="Mrs Coady",
            location_id="LOC_ARCHIE_FLAT", status="healthy",
            traits={
                "frailty": TraitVector(value=0.7, inertia=0.5),
                "resilience": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[]),
    },
    events=[
        EventNode(id="EVT_HEIST", fabula_time=100, syuzhet_index=1, event_type="choice",
                  actor_ids=["ENT_GEORGE", "ENT_KEN", "ENT_WANDA", "ENT_OTTO"], target_ids=[],
                  description="The gang carries out the diamond heist at Heathrow."),
        EventNode(id="EVT_WANDA_BETRAYS_GEORGE", fabula_time=200, syuzhet_index=2, event_type="choice",
                  actor_ids=["ENT_WANDA", "ENT_OTTO"], target_ids=["ENT_GEORGE"],
                  description="Wanda and Otto tip off the police, getting George arrested."),
        EventNode(id="EVT_DIAMONDS_MOVED", fabula_time=300, syuzhet_index=3, event_type="choice",
                  actor_ids=["ENT_GEORGE"], target_ids=[],
                  description="George moves the diamonds to a new location before his arrest."),
        EventNode(id="EVT_ARCHIE_DEFENDS_GEORGE", fabula_time=400, syuzhet_index=4, event_type="outcome",
                  actor_ids=["ENT_ARCHIE"], target_ids=["ENT_GEORGE"],
                  description="Archie Leach is assigned as George's defence barrister."),
        EventNode(id="EVT_WANDA_SEDUCES_ARCHIE", fabula_time=500, syuzhet_index=5, event_type="choice",
                  actor_ids=["ENT_WANDA"], target_ids=["ENT_ARCHIE"],
                  description="Wanda seduces Archie to extract information about the diamond location."),
        EventNode(id="EVT_OTTO_DISCOVERS_BETRAYAL", fabula_time=600, syuzhet_index=6, event_type="revelation",
                  actor_ids=["ENT_OTTO"], target_ids=["ENT_WANDA", "ENT_ARCHIE"],
                  description="Otto discovers Wanda is sleeping with Archie and flies into a jealous rage."),
        EventNode(id="EVT_KEN_KILLS_DOGS", fabula_time=700, syuzhet_index=7, event_type="outcome",
                  actor_ids=["ENT_KEN"], target_ids=["ENT_MRS_COADY"],
                  description="Ken accidentally kills Mrs Coady's dogs while trying to silence her as a witness."),
        EventNode(id="EVT_OTTO_INTERROGATES_KEN", fabula_time=750, syuzhet_index=8, event_type="choice",
                  actor_ids=["ENT_OTTO"], target_ids=["ENT_KEN"],
                  description="Otto tortures Ken with his own fish to get the diamond location."),
        EventNode(id="EVT_GEORGE_CONVICTED", fabula_time=800, syuzhet_index=9, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_GEORGE"],
                  description="George is convicted; Archie's defence fails."),
        EventNode(id="EVT_AIRPORT_CHASE", fabula_time=900, syuzhet_index=10, event_type="outcome",
                  actor_ids=["ENT_WANDA", "ENT_ARCHIE", "ENT_OTTO"], target_ids=[],
                  description="Wanda, Archie, and Otto race to recover the diamonds and flee."),
        EventNode(id="EVT_OTTO_STEAMROLLED", fabula_time=1000, syuzhet_index=11, event_type="outcome",
                  actor_ids=["ENT_KEN"], target_ids=["ENT_OTTO"],
                  description="Ken runs over Otto with a steamroller in revenge."),
    ],
    causal_topology=[
        # chain_reaction
        CausalEdge(source_id="EVT_HEIST", target_id="EVT_WANDA_BETRAYS_GEORGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="EVT_WANDA_BETRAYS_GEORGE", target_id="EVT_DIAMONDS_MOVED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200),
        CausalEdge(source_id="EVT_WANDA_BETRAYS_GEORGE", target_id="EVT_ARCHIE_DEFENDS_GEORGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200),
        CausalEdge(source_id="EVT_ARCHIE_DEFENDS_GEORGE", target_id="EVT_WANDA_SEDUCES_ARCHIE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=400),
        CausalEdge(source_id="EVT_WANDA_SEDUCES_ARCHIE", target_id="EVT_OTTO_DISCOVERS_BETRAYAL",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500),
        CausalEdge(source_id="EVT_OTTO_DISCOVERS_BETRAYAL", target_id="EVT_OTTO_INTERROGATES_KEN",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=600),
        CausalEdge(source_id="EVT_GEORGE_CONVICTED", target_id="EVT_AIRPORT_CHASE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=800),
        CausalEdge(source_id="EVT_AIRPORT_CHASE", target_id="EVT_OTTO_STEAMROLLED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900),
        # mutation
        CausalEdge(source_id="EVT_WANDA_SEDUCES_ARCHIE", target_id="ENT_ARCHIE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500, trait_target="passion", trait_delta=0.4),
        CausalEdge(source_id="EVT_OTTO_DISCOVERS_BETRAYAL", target_id="ENT_OTTO",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600, trait_target="jealousy", trait_delta=0.15),
        CausalEdge(source_id="EVT_KEN_KILLS_DOGS", target_id="ENT_KEN",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=700, trait_target="determination", trait_delta=0.2),
        CausalEdge(source_id="EVT_OTTO_INTERROGATES_KEN", target_id="ENT_KEN",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=750, trait_target="determination", trait_delta=0.2),
        # mutation_social
        CausalEdge(source_id="EVT_WANDA_SEDUCES_ARCHIE", target_id="ENT_WANDA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=500, trait_target="affinity", trait_delta=0.3, rel_counterpart_id="ENT_ARCHIE"),
        CausalEdge(source_id="EVT_OTTO_DISCOVERS_BETRAYAL", target_id="ENT_OTTO",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600, trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_WANDA"),
        CausalEdge(source_id="EVT_OTTO_INTERROGATES_KEN", target_id="ENT_KEN",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=750, trait_target="affinity", trait_delta=-0.7, rel_counterpart_id="ENT_OTTO"),
        # affordance_gate
        CausalEdge(source_id="OBJ_DIAMONDS", target_id="EVT_HEIST",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="ENT_WANDA", target_id="EVT_WANDA_SEDUCES_ARCHIE",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500),
        CausalEdge(source_id="OBJ_STEAMROLLER", target_id="EVT_OTTO_STEAMROLLED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000),
        # ambient_propagation
        CausalEdge(source_id="LOC_OLD_BAILEY", target_id="ENT_ARCHIE",
                   causality_type="ambient_propagation", mechanism="social", evidence_strength="weak",
                   causal_force=2.0, fabula_time=400),
        CausalEdge(source_id="ENT_OTTO", target_id="ENT_KEN",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=600),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_HEATHROW", target_id="LOC_GEORGE_FLAT"),
        SpatialEdge(source_id="LOC_GEORGE_FLAT", target_id="LOC_WANDA_FLAT"),
        SpatialEdge(source_id="LOC_WANDA_FLAT", target_id="LOC_ARCHIE_FLAT"),
        SpatialEdge(source_id="LOC_GEORGE_FLAT", target_id="LOC_OLD_BAILEY"),
        SpatialEdge(source_id="LOC_GEORGE_FLAT", target_id="LOC_HIDEOUT_GARAGE"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_WANDA", target_ids=["ENT_ARCHIE"], medium="seduction", established_at_fabula=500),
        InformationEdge(source_id="ENT_KEN", target_ids=["ENT_OTTO"], medium="torture", established_at_fabula=750),
        InformationEdge(source_id="ENT_GEORGE", target_ids=["ENT_KEN"], medium="prison_visit", established_at_fabula=300),
    ],
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_WANDA", target_entity_id="ENT_OTTO", affinity=0.1, fear=0.1, power_dynamic=0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_OTTO", target_entity_id="ENT_WANDA", affinity=0.6, fear=0.0, power_dynamic=-0.2, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_WANDA", target_entity_id="ENT_ARCHIE", affinity=0.4, fear=0.0, power_dynamic=0.3, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_ARCHIE", target_entity_id="ENT_WANDA", affinity=0.6, fear=0.0, power_dynamic=-0.2, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_KEN", target_entity_id="ENT_GEORGE", affinity=0.7, fear=0.0, power_dynamic=-0.3, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_KEN", target_entity_id="ENT_OTTO", affinity=-0.3, fear=0.5, power_dynamic=-0.5, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_OTTO", target_entity_id="ENT_KEN", affinity=-0.2, fear=0.0, power_dynamic=0.5, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_OTTO", target_entity_id="ENT_ARCHIE", affinity=-0.6, fear=0.0, power_dynamic=0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_GEORGE", target_entity_id="ENT_KEN", affinity=0.5, fear=0.0, power_dynamic=0.3, inertia=0.4),
    ],
)
