"""Apocalypse Now — high-fidelity WorldStateV1 test fixture.

Quality checklist (all five causality modalities, varied force/evidence,
trait_target/trait_delta, state_timeline, rich beliefs, info edges, constants).
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_SAIGON_HOTEL": Location(name="Saigon Hotel Room",
            description="Willard's hotel room where he awaits his mission.",
            ambient_state={"despair": AmbientVector(value=0.7, volatility=0.4),
                           "heat": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_NHA_TRANG_HQ": Location(name="Nha Trang Intelligence HQ",
            description="Military intelligence briefing room.",
            ambient_state={"formality": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_PBR_BOAT": Location(name="PBR Street Gang Boat",
            description="Patrol boat travelling upriver into Cambodia.",
            ambient_state={"tension": AmbientVector(value=0.7, volatility=0.5),
                           "isolation": AmbientVector(value=0.6, volatility=0.4)}),
        "LOC_KILGORE_BEACH": Location(name="Vin Drin Dop Beach",
            description="Beach where Kilgore launches his helicopter assault.",
            ambient_state={"chaos": AmbientVector(value=0.9, volatility=0.3)}),
        "LOC_DO_LUNG_BRIDGE": Location(name="Do Lung Bridge",
            description="Last army outpost, leaderless and under nightly attack.",
            ambient_state={"chaos": AmbientVector(value=0.9, volatility=0.2),
                           "madness": AmbientVector(value=0.8, volatility=0.3)}),
        "LOC_KURTZ_COMPOUND": Location(name="Kurtz's Compound",
            description="Kurtz's temple compound deep in Cambodia.",
            ambient_state={"madness": AmbientVector(value=0.9, volatility=0.2),
                           "terror": AmbientVector(value=0.8, volatility=0.3)}),
        "LOC_JUNGLE": Location(name="Nung River Jungle",
            description="Dense jungle along the river where tigers and VC lurk.",
            ambient_state={"danger": AmbientVector(value=0.8, volatility=0.4),
                           "primeval": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_USO_DEPOT": Location(name="Supply Depot",
            description="US base supply depot with amphitheatre for USO shows.",
            ambient_state={"frenzy": AmbientVector(value=0.7, volatility=0.4)}),
    },
    objects={
        "OBJ_DOSSIER": NarrativeObject(id="OBJ_DOSSIER", name="Kurtz Dossier",
            location_id=None, owner_id="ENT_WILLARD",
            properties={"state": "classified", "content": "kurtz_history"},
            affordances=[Affordance(action="inform", target_type="Entity")]),
        "OBJ_SURFBOARD": NarrativeObject(id="OBJ_SURFBOARD", name="Lance's Surfboard",
            location_id="LOC_PBR_BOAT", owner_id="ENT_LANCE",
            properties={"state": "waxed"},
            affordances=[Affordance(action="surf", target_type="Entity")]),
        "OBJ_MACHETE": NarrativeObject(id="OBJ_MACHETE", name="Sacrificial Machete",
            location_id="LOC_KURTZ_COMPOUND", owner_id=None,
            properties={"state": "bloodied"},
            affordances=[Affordance(action="kill", target_type="Entity")]),
        "OBJ_PBR_RADIO": NarrativeObject(id="OBJ_PBR_RADIO", name="PBR Radio",
            location_id="LOC_PBR_BOAT", owner_id=None,
            properties={"state": "functional"},
            affordances=[Affordance(action="call_airstrike", target_type="Location")]),
    },
    entities={
        "ENT_WILLARD": Entity(id="ENT_WILLARD", name="Captain Benjamin Willard",
            location_id="LOC_SAIGON_HOTEL", status="healthy",
            traits={
                "discipline": TraitVector(value=0.6, inertia=0.4),
                "darkness": TraitVector(value=0.5, inertia=0.3),
                "resolve": TraitVector(value=0.7, inertia=0.5),
                "empathy": TraitVector(value=0.4, inertia=0.3),
                "madness": TraitVector(value=0.2, inertia=0.2),
            },
            beliefs=[
                Belief(target_id="ENT_KURTZ", perceived_state="Kurtz is a rogue officer who must be terminated",
                       confidence=0.7, inertia=0.4),
            ],
            constants=["special_forces", "assassin"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=100, triggered_by="EVT_MISSION_BRIEFING",
                    new_location_id="LOC_NHA_TRANG_HQ"),
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_SAMPAN_MASSACRE",
                    traits={"darkness": TraitVector(value=0.7, inertia=0.3),
                            "empathy": TraitVector(value=0.2, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_WILLARD_MEETS_KURTZ",
                    traits={"madness": TraitVector(value=0.5, inertia=0.2)},
                    beliefs_invalidated=["ENT_KURTZ"],
                    beliefs_added=[Belief(target_id="ENT_KURTZ",
                        perceived_state="Kurtz has seen the truth of war",
                        confidence=0.6, inertia=0.3, established_at_fabula=900)]),
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_WILLARD_KILLS_KURTZ",
                    traits={"darkness": TraitVector(value=0.8, inertia=0.3)}),
            ]),
        "ENT_KURTZ": Entity(id="ENT_KURTZ", name="Colonel Walter Kurtz",
            location_id="LOC_KURTZ_COMPOUND", status="healthy",
            traits={
                "intellect": TraitVector(value=0.9, inertia=0.6),
                "madness": TraitVector(value=0.8, inertia=0.5),
                "charisma": TraitVector(value=0.8, inertia=0.5),
                "horror": TraitVector(value=0.9, inertia=0.6),
                "will_to_die": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_WILLARD", perceived_state="Willard is a fellow soldier who can understand",
                       confidence=0.7, inertia=0.4),
            ],
            constants=["green_beret", "god_king"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_WILLARD_KILLS_KURTZ",
                    new_status="dead"),
            ]),
        "ENT_KILGORE": Entity(id="ENT_KILGORE", name="Lt Colonel Bill Kilgore",
            location_id="LOC_KILGORE_BEACH", status="healthy",
            traits={
                "bravado": TraitVector(value=0.9, inertia=0.6),
                "recklessness": TraitVector(value=0.8, inertia=0.5),
                "charisma": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_LANCE", perceived_state="Lance is a surfer worth risking lives for",
                       confidence=0.6, inertia=0.3),
            ],
            constants=["air_cavalry"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=300, triggered_by="EVT_KILGORE_ASSAULT",
                    traits={"bravado": TraitVector(value=0.95, inertia=0.6)}),
            ]),
        "ENT_CHEF": Entity(id="ENT_CHEF", name="Chef (Frederic Forrest)",
            location_id="LOC_PBR_BOAT", status="healthy",
            traits={
                "anxiety": TraitVector(value=0.7, inertia=0.4),
                "loyalty": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_WILLARD", perceived_state="Willard is leading us to our deaths",
                       confidence=0.6, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=400, triggered_by="EVT_TIGER_ATTACK",
                    traits={"anxiety": TraitVector(value=0.9, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_CHEF_BEHEADED",
                    new_status="dead"),
            ]),
        "ENT_CLEAN": Entity(id="ENT_CLEAN", name="Mr Clean (Laurence Fishburne)",
            location_id="LOC_PBR_BOAT", status="healthy",
            traits={
                "youth": TraitVector(value=0.8, inertia=0.5),
                "impulsiveness": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_CHIEF", perceived_state="Chief knows what he's doing",
                       confidence=0.6, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_CLEAN_KILLED",
                    new_status="dead"),
            ]),
        "ENT_CHIEF": Entity(id="ENT_CHIEF", name="Chief Phillips",
            location_id="LOC_PBR_BOAT", status="healthy",
            traits={
                "duty": TraitVector(value=0.8, inertia=0.6),
                "suspicion": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_WILLARD", perceived_state="Willard's mission is suspicious",
                       confidence=0.7, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_SAMPAN_MASSACRE",
                    traits={"suspicion": TraitVector(value=0.8, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_CHIEF_KILLED",
                    new_status="dead"),
            ]),
        "ENT_LANCE": Entity(id="ENT_LANCE", name="Lance B. Johnson",
            location_id="LOC_PBR_BOAT", status="healthy",
            traits={
                "detachment": TraitVector(value=0.6, inertia=0.3),
                "surfer_zen": TraitVector(value=0.7, inertia=0.4),
                "madness": TraitVector(value=0.2, inertia=0.2),
            },
            beliefs=[
                Belief(target_id="ENT_KILGORE", perceived_state="Kilgore is insane but respects surfing",
                       confidence=0.6, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_WILLARD_MEETS_KURTZ",
                    traits={"madness": TraitVector(value=0.6, inertia=0.3),
                            "detachment": TraitVector(value=0.8, inertia=0.3)}),
            ]),
    },
    events=[
        EventNode(id="EVT_MISSION_BRIEFING", fabula_time=100, syuzhet_index=1, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_WILLARD"],
                  description="Willard is briefed at Nha Trang: terminate Colonel Kurtz with extreme prejudice."),
        EventNode(id="EVT_PBR_DEPARTS", fabula_time=200, syuzhet_index=2, event_type="outcome",
                  actor_ids=["ENT_WILLARD", "ENT_CHEF", "ENT_CLEAN", "ENT_CHIEF", "ENT_LANCE"], target_ids=[],
                  description="Willard joins the PBR crew for the river journey to Cambodia."),
        EventNode(id="EVT_KILGORE_ASSAULT", fabula_time=300, syuzhet_index=3, event_type="choice",
                  actor_ids=["ENT_KILGORE"], target_ids=["ENT_WILLARD"],
                  description="Kilgore's helicopter squadron attacks a village blasting Wagner so Lance can surf."),
        EventNode(id="EVT_TIGER_ATTACK", fabula_time=400, syuzhet_index=4, event_type="outcome",
                  actor_ids=["ENT_CHEF", "ENT_WILLARD"], target_ids=[],
                  description="Chef and Willard are attacked by a tiger in the jungle; Chef has a breakdown."),
        EventNode(id="EVT_SAMPAN_MASSACRE", fabula_time=500, syuzhet_index=5, event_type="outcome",
                  actor_ids=["ENT_CLEAN", "ENT_CHIEF"], target_ids=[],
                  description="The crew massacres civilians on a sampan; Willard executes the sole survivor."),
        EventNode(id="EVT_DO_LUNG_BRIDGE", fabula_time=600, syuzhet_index=6, event_type="outcome",
                  actor_ids=["ENT_WILLARD"], target_ids=[],
                  description="The PBR reaches the leaderless Do Lung Bridge outpost under nightly siege."),
        EventNode(id="EVT_CLEAN_KILLED", fabula_time=700, syuzhet_index=7, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_CLEAN"],
                  description="Mr Clean is fatally shot while listening to a tape from his mother."),
        EventNode(id="EVT_CHIEF_KILLED", fabula_time=800, syuzhet_index=8, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_CHIEF"],
                  description="Chief is killed by a spear during a native ambush near Kurtz's territory."),
        EventNode(id="EVT_WILLARD_MEETS_KURTZ", fabula_time=900, syuzhet_index=9, event_type="revelation",
                  actor_ids=["ENT_WILLARD"], target_ids=["ENT_KURTZ"],
                  description="Willard arrives at Kurtz's compound and encounters the colonel."),
        EventNode(id="EVT_WILLARD_IMPRISONED", fabula_time=950, syuzhet_index=10, event_type="outcome",
                  actor_ids=["ENT_KURTZ"], target_ids=["ENT_WILLARD"],
                  description="Kurtz imprisons Willard in a tiger cage; throws Chef's severed head in his lap."),
        EventNode(id="EVT_CHEF_BEHEADED", fabula_time=1000, syuzhet_index=11, event_type="outcome",
                  actor_ids=["ENT_KURTZ"], target_ids=["ENT_CHEF"],
                  description="Chef is beheaded by Kurtz's followers when he tries to call in an airstrike."),
        EventNode(id="EVT_KURTZ_PHILOSOPHISES", fabula_time=1100, syuzhet_index=12, event_type="revelation",
                  actor_ids=["ENT_KURTZ"], target_ids=["ENT_WILLARD"],
                  description="Freed from the cage, Willard listens to Kurtz's monologues about the horror."),
        EventNode(id="EVT_WILLARD_KILLS_KURTZ", fabula_time=1200, syuzhet_index=13, event_type="choice",
                  actor_ids=["ENT_WILLARD"], target_ids=["ENT_KURTZ"],
                  description="Willard assassinates Kurtz with a machete during a ritual caribou sacrifice."),
        EventNode(id="EVT_WILLARD_DEPARTS", fabula_time=1300, syuzhet_index=14, event_type="outcome",
                  actor_ids=["ENT_WILLARD", "ENT_LANCE"], target_ids=[],
                  description="Willard and Lance depart the compound as the natives lay down their weapons."),
    ],
    causal_topology=[
        # chain_reaction (11)
        CausalEdge(source_id="EVT_MISSION_BRIEFING", target_id="EVT_PBR_DEPARTS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="EVT_PBR_DEPARTS", target_id="EVT_KILGORE_ASSAULT",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200),
        CausalEdge(source_id="EVT_KILGORE_ASSAULT", target_id="EVT_TIGER_ATTACK",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=300),
        CausalEdge(source_id="EVT_TIGER_ATTACK", target_id="EVT_SAMPAN_MASSACRE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=400),
        CausalEdge(source_id="EVT_SAMPAN_MASSACRE", target_id="EVT_DO_LUNG_BRIDGE",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=500),
        CausalEdge(source_id="EVT_DO_LUNG_BRIDGE", target_id="EVT_CLEAN_KILLED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=600),
        CausalEdge(source_id="EVT_CLEAN_KILLED", target_id="EVT_CHIEF_KILLED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=700),
        CausalEdge(source_id="EVT_CHIEF_KILLED", target_id="EVT_WILLARD_MEETS_KURTZ",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=800),
        CausalEdge(source_id="EVT_WILLARD_MEETS_KURTZ", target_id="EVT_WILLARD_IMPRISONED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900),
        CausalEdge(source_id="EVT_KURTZ_PHILOSOPHISES", target_id="EVT_WILLARD_KILLS_KURTZ",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1100),
        CausalEdge(source_id="EVT_WILLARD_KILLS_KURTZ", target_id="EVT_WILLARD_DEPARTS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1200),
        # mutation (6)
        CausalEdge(source_id="EVT_SAMPAN_MASSACRE", target_id="ENT_WILLARD",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500, trait_target="darkness", trait_delta=0.2),
        CausalEdge(source_id="EVT_TIGER_ATTACK", target_id="ENT_CHEF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=400, trait_target="anxiety", trait_delta=0.2),
        CausalEdge(source_id="EVT_WILLARD_MEETS_KURTZ", target_id="ENT_WILLARD",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900, trait_target="madness", trait_delta=0.3),
        CausalEdge(source_id="EVT_WILLARD_KILLS_KURTZ", target_id="ENT_WILLARD",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1200, trait_target="darkness", trait_delta=0.1),
        CausalEdge(source_id="EVT_KILGORE_ASSAULT", target_id="ENT_LANCE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=300, trait_target="detachment", trait_delta=0.2),
        CausalEdge(source_id="EVT_DO_LUNG_BRIDGE", target_id="ENT_LANCE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=600, trait_target="madness", trait_delta=0.2),
        # mutation_social (3)
        CausalEdge(source_id="EVT_WILLARD_MEETS_KURTZ", target_id="ENT_WILLARD",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900,
                   trait_target="affinity", trait_delta=0.3, rel_counterpart_id="ENT_KURTZ"),
        CausalEdge(source_id="EVT_SAMPAN_MASSACRE", target_id="ENT_CHIEF",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500,
                   trait_target="affinity", trait_delta=-0.4, rel_counterpart_id="ENT_WILLARD"),
        CausalEdge(source_id="EVT_WILLARD_KILLS_KURTZ", target_id="ENT_KURTZ",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1200,
                   trait_target="affinity", trait_delta=0.2, rel_counterpart_id="ENT_WILLARD"),
        # affordance_gate (3)
        CausalEdge(source_id="OBJ_DOSSIER", target_id="EVT_MISSION_BRIEFING",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=100),
        CausalEdge(source_id="OBJ_MACHETE", target_id="EVT_WILLARD_KILLS_KURTZ",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1200),
        CausalEdge(source_id="ENT_KILGORE", target_id="EVT_KILGORE_ASSAULT",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300),
        # ambient_propagation (2)
        CausalEdge(source_id="LOC_KURTZ_COMPOUND", target_id="ENT_WILLARD",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=900),
        CausalEdge(source_id="LOC_DO_LUNG_BRIDGE", target_id="ENT_LANCE",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=600),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_SAIGON_HOTEL", target_id="LOC_NHA_TRANG_HQ"),
        SpatialEdge(source_id="LOC_NHA_TRANG_HQ", target_id="LOC_PBR_BOAT"),
        SpatialEdge(source_id="LOC_PBR_BOAT", target_id="LOC_KILGORE_BEACH"),
        SpatialEdge(source_id="LOC_PBR_BOAT", target_id="LOC_JUNGLE"),
        SpatialEdge(source_id="LOC_PBR_BOAT", target_id="LOC_USO_DEPOT"),
        SpatialEdge(source_id="LOC_PBR_BOAT", target_id="LOC_DO_LUNG_BRIDGE"),
        SpatialEdge(source_id="LOC_DO_LUNG_BRIDGE", target_id="LOC_KURTZ_COMPOUND"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_KURTZ", target_ids=["ENT_WILLARD"],
                        medium="monologue", established_at_fabula=1100),
        InformationEdge(source_id="ENT_WILLARD", target_ids=["ENT_CHEF"],
                        medium="conversation", established_at_fabula=200, terminated_at_fabula=1000),
        InformationEdge(source_id="OBJ_DOSSIER", target_ids=["ENT_WILLARD"],
                        medium="classified_briefing", established_at_fabula=100),
        InformationEdge(source_id="ENT_CHIEF", target_ids=["ENT_WILLARD"],
                        medium="argument", established_at_fabula=500),
    ],
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_WILLARD", target_entity_id="ENT_KURTZ",
                         affinity=-0.2, fear=0.3, power_dynamic=-0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_KURTZ", target_entity_id="ENT_WILLARD",
                         affinity=0.3, fear=0.0, power_dynamic=0.4, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_WILLARD", target_entity_id="ENT_CHIEF",
                         affinity=0.2, fear=0.0, power_dynamic=0.2, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_CHIEF", target_entity_id="ENT_WILLARD",
                         affinity=-0.1, fear=0.1, power_dynamic=-0.2, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_WILLARD", target_entity_id="ENT_CHEF",
                         affinity=0.2, fear=0.0, power_dynamic=0.2, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_WILLARD", target_entity_id="ENT_LANCE",
                         affinity=0.2, fear=0.0, power_dynamic=0.2, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_KILGORE", target_entity_id="ENT_LANCE",
                         affinity=0.4, fear=0.0, power_dynamic=0.5, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_WILLARD", target_entity_id="ENT_CLEAN",
                         affinity=0.2, fear=0.0, power_dynamic=0.3, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_CHEF", target_entity_id="ENT_CHIEF",
                         affinity=0.3, fear=0.0, power_dynamic=-0.2, inertia=0.3),
    ],
)
