"""Dad's Army — high-fidelity WorldStateV1 test fixture."""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_CHURCH_HALL": Location(name="Church Hall", description="The Walmington-on-Sea Home Guard's HQ and drill hall.",
            ambient_state={"camaraderie": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_MAINWARING_OFFICE": Location(name="Mainwaring's Office", description="Captain Mainwaring's bank office doubling as command post.",
            ambient_state={"formality": AmbientVector(value=0.6, volatility=0.3)}),
        "LOC_JONES_SHOP": Location(name="Jones's Butcher Shop", description="Corporal Jones's butcher shop, hub of village gossip.",
            ambient_state={"warmth": AmbientVector(value=0.6, volatility=0.2)}),
        "LOC_BEACH": Location(name="Walmington Beach", description="Coastal defence position along the English Channel.",
            ambient_state={"danger": AmbientVector(value=0.4, volatility=0.5)}),
        "LOC_PIER": Location(name="Walmington Pier", description="The pier where the platoon captures the U-boat crew.",
            ambient_state={"tension": AmbientVector(value=0.6, volatility=0.5)}),
        "LOC_VICARAGE": Location(name="Vicarage", description="The Vicar's residence adjacent to the church hall.",
            ambient_state={"peace": AmbientVector(value=0.7, volatility=0.2)}),
    },
    objects={
        "OBJ_RIFLES": NarrativeObject(id="OBJ_RIFLES", name="Vintage Rifles",
            location_id="LOC_CHURCH_HALL", owner_id=None,
            properties={"state": "antiquated", "quantity": "few"},
            affordances=[Affordance(action="defend", target_type="Entity")]),
        "OBJ_SAUSAGES": NarrativeObject(id="OBJ_SAUSAGES", name="Jones's Sausages",
            location_id="LOC_JONES_SHOP", owner_id="ENT_JONES",
            properties={"state": "fresh", "use": "rations"},
            affordances=[Affordance(action="bribe", target_type="Entity"), Affordance(action="feed", target_type="Entity")]),
        "OBJ_UBOAT_DINGHY": NarrativeObject(id="OBJ_UBOAT_DINGHY", name="U-Boat Dinghy",
            location_id="LOC_PIER", owner_id=None,
            properties={"state": "beached"},
            affordances=[Affordance(action="transport", target_type="Entity")]),
    },
    entities={
        "ENT_MAINWARING": Entity(id="ENT_MAINWARING", name="Captain Mainwaring",
            location_id="LOC_MAINWARING_OFFICE", status="healthy",
            traits={
                "pomposity": TraitVector(value=0.8, inertia=0.6),
                "courage": TraitVector(value=0.6, inertia=0.4),
                "patriotism": TraitVector(value=0.9, inertia=0.7),
                "insecurity": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_WILSON", perceived_state="Wilson undermines my authority with his casual manner", confidence=0.7, inertia=0.5),
                Belief(target_id="ENT_JONES", perceived_state="Jones is enthusiastic but needs reining in", confidence=0.7, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_UBOAT_SPOTTED",
                    traits={"courage": TraitVector(value=0.7, inertia=0.4)}),
            ]),
        "ENT_WILSON": Entity(id="ENT_WILSON", name="Sergeant Wilson",
            location_id="LOC_CHURCH_HALL", status="healthy",
            traits={
                "charm": TraitVector(value=0.8, inertia=0.5),
                "languor": TraitVector(value=0.7, inertia=0.5),
                "class_superiority": TraitVector(value=0.7, inertia=0.5),
                "tact": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_MAINWARING", perceived_state="Mainwaring tries too hard but means well", confidence=0.8, inertia=0.5),
            ]),
        "ENT_JONES": Entity(id="ENT_JONES", name="Corporal Jones",
            location_id="LOC_JONES_SHOP", status="healthy",
            traits={
                "enthusiasm": TraitVector(value=0.9, inertia=0.6),
                "rambling": TraitVector(value=0.8, inertia=0.5),
                "bravery": TraitVector(value=0.7, inertia=0.5),
                "panic": TraitVector(value=0.6, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_MAINWARING", perceived_state="Mr Mainwaring is a great leader", confidence=0.9, inertia=0.6),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_UBOAT_SPOTTED",
                    traits={"panic": TraitVector(value=0.8, inertia=0.3)}),
            ]),
        "ENT_PIKE": Entity(id="ENT_PIKE", name="Private Pike",
            location_id="LOC_CHURCH_HALL", status="healthy",
            traits={
                "naivete": TraitVector(value=0.8, inertia=0.5),
                "cowardice": TraitVector(value=0.6, inertia=0.3),
                "youth": TraitVector(value=0.9, inertia=0.7),
            },
            beliefs=[
                Belief(target_id="ENT_MAINWARING", perceived_state="Uncle Arthur is in charge", confidence=0.7, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_PIKE_HOSTAGE",
                    traits={"cowardice": TraitVector(value=0.8, inertia=0.3)}),
            ]),
        "ENT_FRAZER": Entity(id="ENT_FRAZER", name="Private Frazer",
            location_id="LOC_CHURCH_HALL", status="healthy",
            traits={
                "doom": TraitVector(value=0.8, inertia=0.6),
                "miserliness": TraitVector(value=0.7, inertia=0.5),
                "highland_toughness": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_MAINWARING", perceived_state="We're all doomed under Mainwaring's command", confidence=0.8, inertia=0.5),
            ]),
        "ENT_GODFREY": Entity(id="ENT_GODFREY", name="Private Godfrey",
            location_id="LOC_CHURCH_HALL", status="healthy",
            traits={
                "gentleness": TraitVector(value=0.9, inertia=0.7),
                "frailty": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_MAINWARING", perceived_state="Mainwaring is a fine chap doing his best", confidence=0.7, inertia=0.5),
            ]),
        "ENT_UBOAT_CAPTAIN": Entity(id="ENT_UBOAT_CAPTAIN", name="German U-Boat Captain",
            location_id="LOC_PIER", status="healthy",
            traits={
                "arrogance": TraitVector(value=0.7, inertia=0.5),
                "discipline": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_MAINWARING", perceived_state="These amateur soldiers are beneath contempt", confidence=0.8, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_UBOAT_CAPTURED",
                    traits={"arrogance": TraitVector(value=0.5, inertia=0.5)}),
            ]),
    },
    events=[
        EventNode(id="EVT_PLATOON_FORMED", fabula_time=100, syuzhet_index=1, event_type="outcome",
                  actor_ids=["ENT_MAINWARING"], target_ids=["ENT_WILSON", "ENT_JONES"],
                  description="Mainwaring forms the Home Guard platoon from local volunteers."),
        EventNode(id="EVT_DRILL_DISASTER", fabula_time=200, syuzhet_index=2, event_type="outcome",
                  actor_ids=["ENT_JONES", "ENT_PIKE"], target_ids=[],
                  description="The platoon's first drill exercise descends into comic chaos."),
        EventNode(id="EVT_WEAPONS_ISSUED", fabula_time=300, syuzhet_index=3, event_type="outcome",
                  actor_ids=["ENT_MAINWARING"], target_ids=[],
                  description="The platoon receives antiquated rifles and minimal ammunition."),
        EventNode(id="EVT_BEACH_PATROL", fabula_time=400, syuzhet_index=4, event_type="choice",
                  actor_ids=["ENT_MAINWARING", "ENT_WILSON"], target_ids=[],
                  description="The platoon begins coastal defence patrols along Walmington beach."),
        EventNode(id="EVT_UBOAT_SPOTTED", fabula_time=500, syuzhet_index=5, event_type="revelation",
                  actor_ids=["ENT_PIKE"], target_ids=["ENT_MAINWARING"],
                  description="Pike spots a German U-boat dinghy approaching the pier."),
        EventNode(id="EVT_JONES_PANICS", fabula_time=550, syuzhet_index=6, event_type="outcome",
                  actor_ids=["ENT_JONES"], target_ids=[],
                  description="Jones runs about shouting 'Don't panic!' causing the platoon to panic."),
        EventNode(id="EVT_MAINWARING_RALLIES", fabula_time=600, syuzhet_index=7, event_type="choice",
                  actor_ids=["ENT_MAINWARING"], target_ids=["ENT_JONES", "ENT_PIKE", "ENT_FRAZER"],
                  description="Mainwaring rallies the platoon and formulates a plan to capture the Germans."),
        EventNode(id="EVT_PIKE_HOSTAGE", fabula_time=700, syuzhet_index=8, event_type="outcome",
                  actor_ids=["ENT_UBOAT_CAPTAIN"], target_ids=["ENT_PIKE"],
                  description="The U-boat captain takes Pike hostage and demands to be taken to his submarine."),
        EventNode(id="EVT_UBOAT_CAPTURED", fabula_time=800, syuzhet_index=9, event_type="outcome",
                  actor_ids=["ENT_MAINWARING", "ENT_JONES"], target_ids=["ENT_UBOAT_CAPTAIN"],
                  description="The platoon outwits the Germans and captures the U-boat crew."),
        EventNode(id="EVT_HEROES_CELEBRATED", fabula_time=900, syuzhet_index=10, event_type="outcome",
                  actor_ids=["ENT_MAINWARING"], target_ids=[],
                  description="The platoon is celebrated as local heroes; Mainwaring takes full credit."),
    ],
    causal_topology=[
        # chain_reaction
        CausalEdge(source_id="EVT_PLATOON_FORMED", target_id="EVT_DRILL_DISASTER",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=100),
        CausalEdge(source_id="EVT_DRILL_DISASTER", target_id="EVT_WEAPONS_ISSUED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=200),
        CausalEdge(source_id="EVT_WEAPONS_ISSUED", target_id="EVT_BEACH_PATROL",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=6.0, fabula_time=300),
        CausalEdge(source_id="EVT_BEACH_PATROL", target_id="EVT_UBOAT_SPOTTED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=400),
        CausalEdge(source_id="EVT_UBOAT_SPOTTED", target_id="EVT_JONES_PANICS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500),
        CausalEdge(source_id="EVT_JONES_PANICS", target_id="EVT_MAINWARING_RALLIES",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=550),
        CausalEdge(source_id="EVT_MAINWARING_RALLIES", target_id="EVT_PIKE_HOSTAGE",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=600),
        CausalEdge(source_id="EVT_PIKE_HOSTAGE", target_id="EVT_UBOAT_CAPTURED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700),
        CausalEdge(source_id="EVT_UBOAT_CAPTURED", target_id="EVT_HEROES_CELEBRATED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=800),
        # mutation
        CausalEdge(source_id="EVT_UBOAT_SPOTTED", target_id="ENT_MAINWARING",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=500, trait_target="courage", trait_delta=0.1),
        CausalEdge(source_id="EVT_UBOAT_SPOTTED", target_id="ENT_JONES",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500, trait_target="panic", trait_delta=0.2),
        CausalEdge(source_id="EVT_PIKE_HOSTAGE", target_id="ENT_PIKE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=700, trait_target="cowardice", trait_delta=0.2),
        CausalEdge(source_id="EVT_UBOAT_CAPTURED", target_id="ENT_UBOAT_CAPTAIN",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=800, trait_target="arrogance", trait_delta=-0.2),
        # mutation_social
        CausalEdge(source_id="EVT_UBOAT_CAPTURED", target_id="ENT_UBOAT_CAPTAIN",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=800, trait_target="fear", trait_delta=0.4, rel_counterpart_id="ENT_MAINWARING"),
        CausalEdge(source_id="EVT_MAINWARING_RALLIES", target_id="ENT_JONES",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=600, trait_target="affinity", trait_delta=0.2, rel_counterpart_id="ENT_MAINWARING"),
        CausalEdge(source_id="EVT_HEROES_CELEBRATED", target_id="ENT_WILSON",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=900, trait_target="affinity", trait_delta=0.1, rel_counterpart_id="ENT_MAINWARING"),
        # affordance_gate
        CausalEdge(source_id="OBJ_RIFLES", target_id="EVT_BEACH_PATROL",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=6.0, fabula_time=300),
        CausalEdge(source_id="ENT_MAINWARING", target_id="EVT_MAINWARING_RALLIES",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=600),
        CausalEdge(source_id="OBJ_UBOAT_DINGHY", target_id="EVT_UBOAT_SPOTTED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500),
        # ambient_propagation
        CausalEdge(source_id="LOC_CHURCH_HALL", target_id="ENT_PIKE",
                   causality_type="ambient_propagation", mechanism="social", evidence_strength="weak",
                   causal_force=2.0, fabula_time=100),
        CausalEdge(source_id="LOC_BEACH", target_id="ENT_FRAZER",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=400),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_CHURCH_HALL", target_id="LOC_MAINWARING_OFFICE"),
        SpatialEdge(source_id="LOC_CHURCH_HALL", target_id="LOC_VICARAGE"),
        SpatialEdge(source_id="LOC_CHURCH_HALL", target_id="LOC_JONES_SHOP"),
        SpatialEdge(source_id="LOC_CHURCH_HALL", target_id="LOC_BEACH"),
        SpatialEdge(source_id="LOC_BEACH", target_id="LOC_PIER"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_PIKE", target_ids=["ENT_MAINWARING"], medium="shout", established_at_fabula=500),
        InformationEdge(source_id="ENT_MAINWARING", target_ids=["ENT_WILSON", "ENT_JONES"], medium="briefing", established_at_fabula=600),
    ],
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_MAINWARING", target_entity_id="ENT_WILSON", affinity=0.4, fear=0.0, power_dynamic=0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_WILSON", target_entity_id="ENT_MAINWARING", affinity=0.5, fear=0.0, power_dynamic=-0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_JONES", target_entity_id="ENT_MAINWARING", affinity=0.8, fear=0.0, power_dynamic=-0.4, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_MAINWARING", target_entity_id="ENT_JONES", affinity=0.5, fear=0.0, power_dynamic=0.4, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_PIKE", target_entity_id="ENT_WILSON", affinity=0.6, fear=0.0, power_dynamic=-0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_FRAZER", target_entity_id="ENT_MAINWARING", affinity=0.1, fear=0.0, power_dynamic=-0.2, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_MAINWARING", target_entity_id="ENT_UBOAT_CAPTAIN", affinity=-0.5, fear=0.1, power_dynamic=0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_UBOAT_CAPTAIN", target_entity_id="ENT_MAINWARING", affinity=-0.6, fear=0.0, power_dynamic=0.2, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_GODFREY", target_entity_id="ENT_MAINWARING", affinity=0.6, fear=0.0, power_dynamic=-0.3, inertia=0.5),
    ],
)
