"""Dad's Army — high-fidelity WorldStateV1 test fixture.

Quality checklist (all five causality modalities, varied force/evidence,
trait_target/trait_delta, state_timeline, rich beliefs, info edges, constants).
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_CHURCH_HALL": Location(name="Church Hall",
            description="HQ of the Walmington-on-Sea Home Guard platoon.",
            ambient_state={"bumbling": AmbientVector(value=0.6, volatility=0.4),
                           "patriotism": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_HIGH_STREET": Location(name="High Street",
            description="Walmington-on-Sea main street with Jones's butcher shop.",
            ambient_state={"normality": AmbientVector(value=0.6, volatility=0.3)}),
        "LOC_JONES_SHOP": Location(name="Jones's Butcher Shop",
            description="Corporal Jones's butcher shop doubling as an armoury.",
            ambient_state={"warmth": AmbientVector(value=0.5, volatility=0.2)}),
        "LOC_BEACH": Location(name="Walmington Beach",
            description="The local beach where invasion drills occur.",
            ambient_state={"wind": AmbientVector(value=0.6, volatility=0.3),
                           "tension": AmbientVector(value=0.3, volatility=0.4)}),
        "LOC_VICARAGE": Location(name="Vicarage",
            description="Residence of the Vicar, adjacent to the church hall.",
            ambient_state={"calm": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_AIRFIELD": Location(name="Local Airfield",
            description="Small airfield near Walmington used for exercises.",
            ambient_state={"danger": AmbientVector(value=0.4, volatility=0.4),
                           "formality": AmbientVector(value=0.5, volatility=0.3)}),
        "LOC_TOWN_SQUARE": Location(name="Town Square",
            description="Central square for parades and public addresses.",
            ambient_state={"community": AmbientVector(value=0.6, volatility=0.3)}),
    },
    objects={
        "OBJ_RIFLES": NarrativeObject(id="OBJ_RIFLES", name="Ancient Rifles",
            location_id="LOC_CHURCH_HALL", owner_id=None,
            properties={"state": "antiquated", "calibre": "mixed"},
            affordances=[Affordance(action="shoot", target_type="Entity")]),
        "OBJ_JONES_VAN": NarrativeObject(id="OBJ_JONES_VAN", name="Jones's Butcher Van",
            location_id="LOC_JONES_SHOP", owner_id="ENT_JONES",
            properties={"state": "running", "purpose": "transport"},
            affordances=[Affordance(action="transport", target_type="Entity")]),
        "OBJ_WHISTLE": NarrativeObject(id="OBJ_WHISTLE", name="Parade Whistle",
            location_id="LOC_CHURCH_HALL", owner_id="ENT_MAINWARING",
            properties={"state": "polished"},
            affordances=[Affordance(action="command", target_type="Entity")]),
        "OBJ_SWASTIKA_FLAG": NarrativeObject(id="OBJ_SWASTIKA_FLAG", name="Captured Swastika Flag",
            location_id=None, owner_id=None,
            properties={"state": "captured"},
            affordances=[Affordance(action="display_as_trophy", target_type="Location")]),
    },
    entities={
        "ENT_MAINWARING": Entity(id="ENT_MAINWARING", name="Captain Mainwaring",
            location_id="LOC_CHURCH_HALL", status="healthy",
            traits={
                "pomposity": TraitVector(value=0.8, inertia=0.6),
                "bravery": TraitVector(value=0.6, inertia=0.4),
                "insecurity": TraitVector(value=0.6, inertia=0.4),
                "patriotism": TraitVector(value=0.9, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_WILSON", perceived_state="Wilson undermines my authority",
                       confidence=0.7, inertia=0.5),
                Belief(target_id="ENT_HODGES", perceived_state="Hodges is a petty rival",
                       confidence=0.8, inertia=0.5),
            ],
            constants=["bank_manager", "platoon_commander"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=300, triggered_by="EVT_DRILL_FIASCO",
                    traits={"insecurity": TraitVector(value=0.7, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_MAINWARING_STANDS_FIRM",
                    traits={"bravery": TraitVector(value=0.8, inertia=0.4)}),
            ]),
        "ENT_WILSON": Entity(id="ENT_WILSON", name="Sergeant Wilson",
            location_id="LOC_CHURCH_HALL", status="healthy",
            traits={
                "languid_charm": TraitVector(value=0.8, inertia=0.5),
                "diffidence": TraitVector(value=0.7, inertia=0.5),
                "wit": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_MAINWARING", perceived_state="Mainwaring means well but is absurd",
                       confidence=0.8, inertia=0.5),
            ],
            constants=["public_school_educated"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_WILSON_OUTRANKS_REVELATION",
                    traits={"diffidence": TraitVector(value=0.5, inertia=0.5)}),
            ]),
        "ENT_JONES": Entity(id="ENT_JONES", name="Corporal Jones",
            location_id="LOC_JONES_SHOP", status="healthy",
            traits={
                "excitability": TraitVector(value=0.9, inertia=0.5),
                "loyalty": TraitVector(value=0.9, inertia=0.6),
                "bravery": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_MAINWARING", perceived_state="Captain Mainwaring is a great leader",
                       confidence=0.9, inertia=0.6),
            ],
            constants=["sudan_veteran"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_JONES_BAYONET_CHARGE",
                    traits={"excitability": TraitVector(value=0.95, inertia=0.5)}),
            ]),
        "ENT_FRAZER": Entity(id="ENT_FRAZER", name="Private Frazer",
            location_id="LOC_CHURCH_HALL", status="healthy",
            traits={
                "doom": TraitVector(value=0.9, inertia=0.6),
                "cunning": TraitVector(value=0.7, inertia=0.5),
                "stubbornness": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_MAINWARING", perceived_state="Mainwaring is doomed to fail",
                       confidence=0.7, inertia=0.5),
            ],
            constants=["undertaker"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_PARACHUTIST_CAPTURED",
                    traits={"doom": TraitVector(value=0.7, inertia=0.6)}),
            ]),
        "ENT_GODFREY": Entity(id="ENT_GODFREY", name="Private Godfrey",
            location_id="LOC_CHURCH_HALL", status="healthy",
            traits={
                "gentleness": TraitVector(value=0.9, inertia=0.6),
                "frailty": TraitVector(value=0.7, inertia=0.5),
                "courage": TraitVector(value=0.5, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_MAINWARING", perceived_state="Mainwaring is doing his best",
                       confidence=0.7, inertia=0.4),
            ],
            constants=["conscientious_objector_medal"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_GODFREY_HERO",
                    traits={"courage": TraitVector(value=0.7, inertia=0.4)}),
            ]),
        "ENT_PIKE": Entity(id="ENT_PIKE", name="Private Pike",
            location_id="LOC_CHURCH_HALL", status="healthy",
            traits={
                "naivety": TraitVector(value=0.8, inertia=0.4),
                "enthusiasm": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_WILSON", perceived_state="Uncle Arthur looks after me",
                       confidence=0.9, inertia=0.5),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_PIKE_REFUSES_NAME",
                    traits={"naivety": TraitVector(value=0.6, inertia=0.4)}),
            ]),
        "ENT_HODGES": Entity(id="ENT_HODGES", name="ARP Warden Hodges",
            location_id="LOC_HIGH_STREET", status="healthy",
            traits={
                "belligerence": TraitVector(value=0.8, inertia=0.5),
                "pettiness": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_MAINWARING", perceived_state="Mainwaring's platoon is a joke",
                       confidence=0.8, inertia=0.5),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_HODGES_GRUDGING_RESPECT",
                    traits={"belligerence": TraitVector(value=0.6, inertia=0.5)}),
            ]),
    },
    events=[
        EventNode(id="EVT_PLATOON_FORMED", fabula_time=100, syuzhet_index=1, event_type="outcome",
                  actor_ids=["ENT_MAINWARING"], target_ids=["ENT_WILSON", "ENT_JONES"],
                  description="Mainwaring forms the Walmington-on-Sea Home Guard platoon at the church hall."),
        EventNode(id="EVT_WEAPONS_DISTRIBUTED", fabula_time=200, syuzhet_index=2, event_type="outcome",
                  actor_ids=["ENT_MAINWARING"], target_ids=[],
                  description="The platoon receives ancient rifles and begins improvised drill."),
        EventNode(id="EVT_DRILL_FIASCO", fabula_time=300, syuzhet_index=3, event_type="outcome",
                  actor_ids=["ENT_JONES"], target_ids=["ENT_MAINWARING"],
                  description="Jones panics during drill, causing a comedic chain-reaction of accidents."),
        EventNode(id="EVT_HODGES_CONFRONTATION", fabula_time=400, syuzhet_index=4, event_type="outcome",
                  actor_ids=["ENT_HODGES"], target_ids=["ENT_MAINWARING"],
                  description="ARP Warden Hodges challenges Mainwaring's authority during a blackout inspection."),
        EventNode(id="EVT_WILSON_OUTRANKS_REVELATION", fabula_time=500, syuzhet_index=5, event_type="revelation",
                  actor_ids=["ENT_WILSON"], target_ids=["ENT_MAINWARING"],
                  description="Wilson casually reveals his higher social standing, humiliating Mainwaring."),
        EventNode(id="EVT_JONES_BAYONET_CHARGE", fabula_time=600, syuzhet_index=6, event_type="choice",
                  actor_ids=["ENT_JONES"], target_ids=[],
                  description="Jones leads a bayonet charge during an exercise, shouting 'Don't panic!'"),
        EventNode(id="EVT_PARACHUTIST_CAPTURED", fabula_time=700, syuzhet_index=7, event_type="outcome",
                  actor_ids=["ENT_FRAZER", "ENT_GODFREY", "ENT_PIKE"], target_ids=[],
                  description="The platoon accidentally captures a downed German parachutist on the beach."),
        EventNode(id="EVT_MAINWARING_STANDS_FIRM", fabula_time=800, syuzhet_index=8, event_type="choice",
                  actor_ids=["ENT_MAINWARING"], target_ids=[],
                  description="Mainwaring stands up to a superior officer threatening to disband the platoon."),
        EventNode(id="EVT_GODFREY_HERO", fabula_time=900, syuzhet_index=9, event_type="outcome",
                  actor_ids=["ENT_GODFREY"], target_ids=["ENT_MAINWARING"],
                  description="Godfrey reveals his WW1 medal for bravery, earning the platoon's respect."),
        EventNode(id="EVT_PIKE_REFUSES_NAME", fabula_time=1000, syuzhet_index=10, event_type="choice",
                  actor_ids=["ENT_PIKE"], target_ids=[],
                  description="Pike refuses to give his name to a captured German officer: 'Don't tell him, Pike!'"),
        EventNode(id="EVT_HODGES_GRUDGING_RESPECT", fabula_time=1100, syuzhet_index=11, event_type="outcome",
                  actor_ids=["ENT_HODGES"], target_ids=["ENT_MAINWARING"],
                  description="Hodges grudgingly admits the platoon did well during a real air-raid scare."),
        EventNode(id="EVT_PLATOON_MARCHES", fabula_time=1200, syuzhet_index=12, event_type="outcome",
                  actor_ids=["ENT_MAINWARING", "ENT_WILSON", "ENT_JONES", "ENT_FRAZER", "ENT_GODFREY", "ENT_PIKE"],
                  target_ids=[],
                  description="The platoon marches through town to cheers, finally respected by the community."),
        EventNode(id="EVT_VICAR_COMPLAINS", fabula_time=350, syuzhet_index=13, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_MAINWARING"],
                  description="The Vicar complains about the platoon's use of the church hall for drilling."),
        EventNode(id="EVT_BEACH_PATROL", fabula_time=650, syuzhet_index=14, event_type="outcome",
                  actor_ids=["ENT_MAINWARING", "ENT_JONES"], target_ids=[],
                  description="Mainwaring and Jones patrol the beach, mistaking a buoy for a mine."),
        EventNode(id="EVT_PIKE_SCARF_INCIDENT", fabula_time=450, syuzhet_index=15, event_type="outcome",
                  actor_ids=["ENT_PIKE"], target_ids=["ENT_MAINWARING"],
                  description="Pike insists on wearing his scarf during drill, testing Mainwaring's patience."),
    ],
    causal_topology=[
        # chain_reaction (10)
        CausalEdge(source_id="EVT_PLATOON_FORMED", target_id="EVT_WEAPONS_DISTRIBUTED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="EVT_WEAPONS_DISTRIBUTED", target_id="EVT_DRILL_FIASCO",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200),
        CausalEdge(source_id="EVT_DRILL_FIASCO", target_id="EVT_HODGES_CONFRONTATION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=300),
        CausalEdge(source_id="EVT_HODGES_CONFRONTATION", target_id="EVT_WILSON_OUTRANKS_REVELATION",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=400),
        CausalEdge(source_id="EVT_JONES_BAYONET_CHARGE", target_id="EVT_BEACH_PATROL",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=600),
        CausalEdge(source_id="EVT_BEACH_PATROL", target_id="EVT_PARACHUTIST_CAPTURED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=650),
        CausalEdge(source_id="EVT_PARACHUTIST_CAPTURED", target_id="EVT_MAINWARING_STANDS_FIRM",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700),
        CausalEdge(source_id="EVT_MAINWARING_STANDS_FIRM", target_id="EVT_GODFREY_HERO",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=800),
        CausalEdge(source_id="EVT_GODFREY_HERO", target_id="EVT_PIKE_REFUSES_NAME",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=900),
        CausalEdge(source_id="EVT_HODGES_GRUDGING_RESPECT", target_id="EVT_PLATOON_MARCHES",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1100),
        # mutation (6)
        CausalEdge(source_id="EVT_DRILL_FIASCO", target_id="ENT_MAINWARING",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=300, trait_target="insecurity", trait_delta=0.1),
        CausalEdge(source_id="EVT_WILSON_OUTRANKS_REVELATION", target_id="ENT_MAINWARING",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=500, trait_target="insecurity", trait_delta=0.1),
        CausalEdge(source_id="EVT_MAINWARING_STANDS_FIRM", target_id="ENT_MAINWARING",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=800, trait_target="bravery", trait_delta=0.2),
        CausalEdge(source_id="EVT_GODFREY_HERO", target_id="ENT_GODFREY",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=900, trait_target="courage", trait_delta=0.2),
        CausalEdge(source_id="EVT_PIKE_REFUSES_NAME", target_id="ENT_PIKE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1000, trait_target="naivety", trait_delta=-0.2),
        CausalEdge(source_id="EVT_JONES_BAYONET_CHARGE", target_id="ENT_JONES",
                   causality_type="mutation", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=600, trait_target="excitability", trait_delta=0.05),
        # mutation_social (3)
        CausalEdge(source_id="EVT_HODGES_CONFRONTATION", target_id="ENT_MAINWARING",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=400,
                   trait_target="affinity", trait_delta=-0.2, rel_counterpart_id="ENT_HODGES"),
        CausalEdge(source_id="EVT_WILSON_OUTRANKS_REVELATION", target_id="ENT_MAINWARING",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=500,
                   trait_target="power_dynamic", trait_delta=-0.2, rel_counterpart_id="ENT_WILSON"),
        CausalEdge(source_id="EVT_HODGES_GRUDGING_RESPECT", target_id="ENT_HODGES",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1100,
                   trait_target="affinity", trait_delta=0.2, rel_counterpart_id="ENT_MAINWARING"),
        # affordance_gate (3)
        CausalEdge(source_id="OBJ_RIFLES", target_id="EVT_WEAPONS_DISTRIBUTED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200),
        CausalEdge(source_id="OBJ_JONES_VAN", target_id="EVT_BEACH_PATROL",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=650),
        CausalEdge(source_id="ENT_MAINWARING", target_id="EVT_PLATOON_FORMED",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        # ambient_propagation (2)
        CausalEdge(source_id="LOC_CHURCH_HALL", target_id="ENT_MAINWARING",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=100),
        CausalEdge(source_id="LOC_BEACH", target_id="ENT_JONES",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=650),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_CHURCH_HALL", target_id="LOC_VICARAGE"),
        SpatialEdge(source_id="LOC_CHURCH_HALL", target_id="LOC_HIGH_STREET"),
        SpatialEdge(source_id="LOC_HIGH_STREET", target_id="LOC_JONES_SHOP"),
        SpatialEdge(source_id="LOC_HIGH_STREET", target_id="LOC_TOWN_SQUARE"),
        SpatialEdge(source_id="LOC_HIGH_STREET", target_id="LOC_BEACH"),
        SpatialEdge(source_id="LOC_TOWN_SQUARE", target_id="LOC_AIRFIELD"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_WILSON", target_ids=["ENT_MAINWARING"],
                        medium="understated_remark", established_at_fabula=500),
        InformationEdge(source_id="ENT_HODGES", target_ids=["ENT_MAINWARING"],
                        medium="shouting", established_at_fabula=400),
        InformationEdge(source_id="ENT_GODFREY", target_ids=["ENT_MAINWARING", "ENT_JONES"],
                        medium="quiet_revelation", established_at_fabula=900),
        InformationEdge(source_id="ENT_JONES", target_ids=["ENT_MAINWARING", "ENT_FRAZER"],
                        medium="war_anecdote", established_at_fabula=100),
        InformationEdge(source_id="ENT_MAINWARING", target_ids=["ENT_WILSON", "ENT_JONES", "ENT_PIKE"],
                        medium="parade_order", established_at_fabula=100),
    ],
    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_HOME_FRONT": GlobalTrait(
            id="WORLD_HOME_FRONT",
            name="Home Front Spirit",
            description="The Blitz-era civilian determination to defend Britain despite inadequate training, equipment, and the absurdity of elderly volunteers facing a potential Nazi invasion.",
            category="social_structure",
            magnitude=TraitVector(value=0.7, inertia=0.6),
            affected_domains=["social", "psychological"],
        ),
        "WORLD_CLASS_COMEDY": GlobalTrait(
            id="WORLD_CLASS_COMEDY",
            name="British Class Comedy",
            description="The platoon is a microcosm of English class tensions — a pompous bank manager commands a spiv, a butcher, and a retired gentleman — all jostling for status.",
            category="social_structure",
            magnitude=TraitVector(value=0.8, inertia=0.7),
            affected_domains=["social"],
        ),
    },
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_MAINWARING", target_entity_id="ENT_WILSON",
                         affinity=0.4, fear=0.1, power_dynamic=0.3, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_WILSON", target_entity_id="ENT_MAINWARING",
                         affinity=0.5, fear=0.0, power_dynamic=-0.1, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_MAINWARING", target_entity_id="ENT_JONES",
                         affinity=0.5, fear=0.0, power_dynamic=0.4, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_JONES", target_entity_id="ENT_MAINWARING",
                         affinity=0.8, fear=0.0, power_dynamic=-0.4, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_MAINWARING", target_entity_id="ENT_HODGES",
                         affinity=-0.5, fear=0.0, power_dynamic=0.0, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_HODGES", target_entity_id="ENT_MAINWARING",
                         affinity=-0.5, fear=0.0, power_dynamic=0.0, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_FRAZER", target_entity_id="ENT_MAINWARING",
                         affinity=0.2, fear=0.0, power_dynamic=-0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_GODFREY", target_entity_id="ENT_MAINWARING",
                         affinity=0.5, fear=0.0, power_dynamic=-0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_PIKE", target_entity_id="ENT_WILSON",
                         affinity=0.8, fear=0.0, power_dynamic=-0.3, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_WILSON", target_entity_id="ENT_PIKE",
                         affinity=0.7, fear=0.0, power_dynamic=0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_MAINWARING", target_entity_id="ENT_PIKE",
                         affinity=0.2, fear=0.0, power_dynamic=0.4, inertia=0.3),
    ],
)
