"""Death on the Nile — high-fidelity WorldStateV1 test fixture."""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_ASWAN": Location(
            name="Aswan", description="Where Poirot first encounters the Doyles and Jacqueline.",
            ambient_state={"heat": AmbientVector(value=0.7, volatility=0.1), "intrigue": AmbientVector(value=0.5, volatility=0.4)},
        ),
        "LOC_KARNAK_DECK": Location(
            name="Karnak Steamer Deck", description="The main deck of the steamer touring the Nile.",
            ambient_state={"luxury": AmbientVector(value=0.7, volatility=0.2), "tension": AmbientVector(value=0.6, volatility=0.4)},
        ),
        "LOC_KARNAK_LOUNGE": Location(
            name="Karnak Lounge", description="Where Jacqueline shoots Simon (staged).",
            ambient_state={"danger": AmbientVector(value=0.7, volatility=0.5)},
        ),
        "LOC_LINNET_CABIN": Location(
            name="Linnet\'s Cabin", description="Where Linnet is found murdered.",
            ambient_state={"danger": AmbientVector(value=0.9, volatility=0.2)},
        ),
        "LOC_BESSNER_CABIN": Location(
            name="Dr Bessner\'s Cabin", description="Where Simon is treated for his leg wound.",
            ambient_state={"safety": AmbientVector(value=0.6, volatility=0.3)},
        ),
        "LOC_ABU_SIMBEL": Location(
            name="Abu Simbel", description="Where a boulder nearly kills Linnet.",
            ambient_state={"danger": AmbientVector(value=0.7, volatility=0.5)},
        ),
        "LOC_SHELLAL": Location(
            name="Shellal", description="Where the steamer docks; final scene.",
            ambient_state={"finality": AmbientVector(value=0.8, volatility=0.2)},
        ),
    },
    objects={
        "OBJ_PISTOL": NarrativeObject(
            id="OBJ_PISTOL", name="Jacqueline\'s Pistol",
            location_id=None, owner_id="ENT_JACQUELINE",
            properties={"caliber": "small", "shots_fired": "2"},
            affordances=[Affordance(action="shoot", target_type="Entity")],
        ),
        "OBJ_PEARLS_REAL": NarrativeObject(
            id="OBJ_PEARLS_REAL", name="Linnet\'s Pearl Necklace (genuine)",
            location_id="LOC_LINNET_CABIN", owner_id="ENT_LINNET",
            properties={"value": "very_high"},
            affordances=[Affordance(action="steal", target_type="Entity")],
        ),
        "OBJ_PEARLS_FAKE": NarrativeObject(
            id="OBJ_PEARLS_FAKE", name="Imitation Pearl Necklace",
            location_id=None, owner_id="ENT_TIM",
            properties={"value": "low"},
            affordances=[Affordance(action="deceive", target_type="Entity")],
        ),
        "OBJ_RED_INK": NarrativeObject(
            id="OBJ_RED_INK", name="Red Ink (disguised as nail polish)",
            location_id=None, owner_id="ENT_SIMON",
            properties={"purpose": "fake_blood"},
            affordances=[Affordance(action="fake_injury", target_type="Entity")],
        ),
        "OBJ_VELVET_STOLE": NarrativeObject(
            id="OBJ_VELVET_STOLE", name="Miss Van Schuyler\'s Velvet Stole",
            location_id=None, owner_id=None,
            properties={"use": "silencer"},
            affordances=[Affordance(action="muffle_shot", target_type="Entity")],
        ),
        "OBJ_SECOND_PISTOL": NarrativeObject(
            id="OBJ_SECOND_PISTOL", name="Jacqueline\'s Second Pistol",
            location_id=None, owner_id="ENT_JACQUELINE",
            properties={"hidden": "true"},
            affordances=[Affordance(action="shoot", target_type="Entity")],
        ),
    },
    entities={
        "ENT_POIROT": Entity(
            id="ENT_POIROT", name="Hercule Poirot",
            location_id="LOC_ASWAN", status="healthy",
            traits={
                "intellect": TraitVector(value=0.95, inertia=0.8),
                "compassion": TraitVector(value=0.6, inertia=0.5),
                "orderliness": TraitVector(value=0.9, inertia=0.7),
            },
            beliefs=[
                Belief(target_id="ENT_JACQUELINE", perceived_state="Jacqueline is opening her heart to evil", confidence=0.7, inertia=0.5),
                Belief(target_id="ENT_JACQUELINE", perceived_state="She has a second pistol — I will allow mercy", confidence=0.8, inertia=0.6, established_at_fabula=1800),
            ],
        ),
        "ENT_LINNET": Entity(
            id="ENT_LINNET", name="Linnet Doyle (née Ridgeway)",
            location_id="LOC_KARNAK_DECK", status="healthy",
            traits={
                "wealth": TraitVector(value=0.95, inertia=0.8),
                "entitlement": TraitVector(value=0.7, inertia=0.5),
                "beauty": TraitVector(value=0.8, inertia=0.7),
            },
            beliefs=[
                Belief(target_id="ENT_SIMON", perceived_state="Simon loves me genuinely", confidence=0.8, inertia=0.6),
                Belief(target_id="ENT_JACQUELINE", perceived_state="Jacqueline is a nuisance but not dangerous", confidence=0.6, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_LINNET_MURDERED", new_status="dead"),
            ],
        ),
        "ENT_SIMON": Entity(
            id="ENT_SIMON", name="Simon Doyle",
            location_id="LOC_KARNAK_DECK", status="healthy",
            traits={
                "charm": TraitVector(value=0.7, inertia=0.5),
                "greed": TraitVector(value=0.7, inertia=0.4),
                "devotion": TraitVector(value=0.3, inertia=0.3),
                "cunning": TraitVector(value=0.5, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_LINNET", perceived_state="Linnet is my ticket to wealth — I\'ll murder her for the money", confidence=0.9, inertia=0.7),
                Belief(target_id="ENT_JACQUELINE", perceived_state="Jacqueline and I will be together once this is done", confidence=0.85, inertia=0.6),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1900, triggered_by="EVT_MURDER_SUICIDE", new_status="dead"),
            ],
        ),
        "ENT_JACQUELINE": Entity(
            id="ENT_JACQUELINE", name="Jacqueline de Bellefort",
            location_id="LOC_ASWAN", status="healthy",
            traits={
                "passion": TraitVector(value=0.9, inertia=0.5),
                "intelligence": TraitVector(value=0.8, inertia=0.6),
                "jealousy": TraitVector(value=0.8, inertia=0.4),
                "ruthlessness": TraitVector(value=0.6, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_LINNET", perceived_state="Linnet stole Simon from me deliberately", confidence=0.95, inertia=0.7),
                Belief(target_id="ENT_SIMON", perceived_state="I must protect Simon even if it means more killing", confidence=0.9, inertia=0.6),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_STAGED_SHOOTING",
                    traits={"ruthlessness": TraitVector(value=0.8, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=1900, triggered_by="EVT_MURDER_SUICIDE", new_status="dead"),
            ],
        ),
        "ENT_PENNINGTON": Entity(
            id="ENT_PENNINGTON", name="Andrew Pennington",
            location_id="LOC_KARNAK_DECK", status="healthy",
            traits={
                "greed": TraitVector(value=0.7, inertia=0.5),
                "cowardice": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_LINNET", perceived_state="If Linnet discovers I embezzled her inheritance, I\'m finished", confidence=0.8, inertia=0.6),
            ],
        ),
        "ENT_LOUISE": Entity(
            id="ENT_LOUISE", name="Louise Bourget",
            location_id="LOC_LINNET_CABIN", status="healthy",
            traits={
                "opportunism": TraitVector(value=0.7, inertia=0.4),
                "cowardice": TraitVector(value=0.5, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_SIMON", perceived_state="I saw Simon enter Linnet\'s cabin — he will pay to keep me quiet", confidence=0.9, inertia=0.6, established_at_fabula=1000),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_LOUISE_MURDERED", new_status="dead"),
            ],
        ),
        "ENT_MRS_OTTERBOURNE": Entity(
            id="ENT_MRS_OTTERBOURNE", name="Salome Otterbourne",
            location_id="LOC_KARNAK_DECK", status="healthy",
            traits={
                "perceptiveness": TraitVector(value=0.6, inertia=0.4),
                "impulsiveness": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_OTTERBOURNE_MURDERED", new_status="dead"),
            ],
        ),
        "ENT_TIM": Entity(
            id="ENT_TIM", name="Tim Allerton",
            location_id="LOC_KARNAK_DECK", status="healthy",
            traits={
                "cunning": TraitVector(value=0.6, inertia=0.4),
                "charm": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[],
        ),
        "ENT_RACE": Entity(
            id="ENT_RACE", name="Colonel Race",
            location_id="LOC_KARNAK_DECK", status="healthy",
            traits={
                "authority": TraitVector(value=0.8, inertia=0.6),
                "loyalty": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[],
        ),
    },
    events=[
        EventNode(id="EVT_LINNET_SEDUCES_SIMON", fabula_time=100, syuzhet_index=1,
                  event_type="choice", actor_ids=["ENT_LINNET"], target_ids=["ENT_SIMON"],
                  description="Linnet deliberately seduces Simon away from Jacqueline, her friend."),
        EventNode(id="EVT_DOYLES_MARRY", fabula_time=200, syuzhet_index=2,
                  event_type="outcome", actor_ids=["ENT_LINNET", "ENT_SIMON"], target_ids=[],
                  description="Linnet and Simon marry; Jacqueline begins stalking them on their honeymoon."),
        EventNode(id="EVT_JACQUELINE_STALKS", fabula_time=300, syuzhet_index=3,
                  event_type="choice", actor_ids=["ENT_JACQUELINE"], target_ids=["ENT_LINNET", "ENT_SIMON"],
                  description="Jacqueline follows the Doyles obsessively across their honeymoon."),
        EventNode(id="EVT_POIROT_WARNS_JACQUELINE", fabula_time=400, syuzhet_index=4,
                  event_type="choice", actor_ids=["ENT_POIROT"], target_ids=["ENT_JACQUELINE"],
                  description="Poirot attempts to dissuade Jacqueline from her course of vengeful obsession."),
        EventNode(id="EVT_BOARD_KARNAK", fabula_time=500, syuzhet_index=5,
                  event_type="outcome", actor_ids=[], target_ids=[],
                  description="All key passengers board the steamer Karnak for the Nile voyage."),
        EventNode(id="EVT_BOULDER_ATTEMPT", fabula_time=600, syuzhet_index=6,
                  event_type="outcome", actor_ids=["ENT_PENNINGTON"], target_ids=["ENT_LINNET"],
                  description="A boulder nearly crushes Linnet at Abu Simbel; Pennington pushed it to avoid discovery of his embezzlement."),
        EventNode(id="EVT_RACE_BOARDS", fabula_time=700, syuzhet_index=7,
                  event_type="outcome", actor_ids=["ENT_RACE"], target_ids=[],
                  description="Colonel Race boards the Karnak, informing Poirot of a possible political agitator."),
        EventNode(id="EVT_STAGED_SHOOTING", fabula_time=800, syuzhet_index=8,
                  event_type="choice", actor_ids=["ENT_JACQUELINE", "ENT_SIMON"], target_ids=[],
                  description="Jacqueline stages shooting Simon in the lounge; Simon fakes his injury with red ink."),
        EventNode(id="EVT_SIMON_KILLS_LINNET", fabula_time=900, syuzhet_index=9,
                  event_type="choice", actor_ids=["ENT_SIMON"], target_ids=["ENT_LINNET"],
                  description="While everyone tends to the staged scene, Simon takes the pistol and shoots Linnet in her cabin."),
        EventNode(id="EVT_LINNET_MURDERED", fabula_time=1000, syuzhet_index=10,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_LINNET"],
                  description="Linnet is found dead the next morning with a bullet in her brain; pearls missing."),
        EventNode(id="EVT_INVESTIGATION_BEGINS", fabula_time=1100, syuzhet_index=11,
                  event_type="outcome", actor_ids=["ENT_POIROT", "ENT_RACE"], target_ids=[],
                  description="Poirot and Race begin interviewing passengers; Louise hints she knows something."),
        EventNode(id="EVT_LOUISE_MURDERED", fabula_time=1200, syuzhet_index=12,
                  event_type="choice", actor_ids=["ENT_JACQUELINE"], target_ids=["ENT_LOUISE"],
                  description="Jacqueline stabs Louise to prevent her from blackmailing Simon."),
        EventNode(id="EVT_OTTERBOURNE_MURDERED", fabula_time=1300, syuzhet_index=13,
                  event_type="outcome", actor_ids=["ENT_JACQUELINE"], target_ids=["ENT_MRS_OTTERBOURNE"],
                  description="Mrs Otterbourne is shot by Jacqueline before she can reveal seeing Jacqueline enter Louise\'s cabin."),
        EventNode(id="EVT_PENNINGTON_EXPOSED", fabula_time=1400, syuzhet_index=14,
                  event_type="revelation", actor_ids=["ENT_POIROT"], target_ids=["ENT_PENNINGTON"],
                  description="Poirot confronts Pennington over the boulder murder attempt and embezzlement."),
        EventNode(id="EVT_TIM_EXPOSED", fabula_time=1500, syuzhet_index=15,
                  event_type="revelation", actor_ids=["ENT_POIROT"], target_ids=["ENT_TIM"],
                  description="Poirot recovers Linnet\'s genuine pearls from Tim, exposing him as a thief."),
        EventNode(id="EVT_POIROT_REVEALS_TRUTH", fabula_time=1600, syuzhet_index=16,
                  event_type="revelation", actor_ids=["ENT_POIROT"], target_ids=["ENT_SIMON", "ENT_JACQUELINE"],
                  description="Poirot reconstructs the entire murder plan: Simon and Jacqueline are still lovers who conspired to kill Linnet."),
        EventNode(id="EVT_SIMON_CONFESSES", fabula_time=1700, syuzhet_index=17,
                  event_type="outcome", actor_ids=["ENT_SIMON"], target_ids=[],
                  description="Simon confesses; he and Jacqueline are arrested."),
        EventNode(id="EVT_MURDER_SUICIDE", fabula_time=1900, syuzhet_index=18,
                  event_type="choice", actor_ids=["ENT_JACQUELINE"], target_ids=["ENT_SIMON"],
                  description="At Shellal, Jacqueline shoots Simon and then herself with her second pistol."),
    ],
    causal_topology=[
        # chain_reaction
        CausalEdge(source_id="EVT_LINNET_SEDUCES_SIMON", target_id="EVT_DOYLES_MARRY",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=100),
        CausalEdge(source_id="EVT_DOYLES_MARRY", target_id="EVT_JACQUELINE_STALKS",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200),
        CausalEdge(source_id="EVT_JACQUELINE_STALKS", target_id="EVT_STAGED_SHOOTING",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300, propagation_delay=500),
        CausalEdge(source_id="EVT_STAGED_SHOOTING", target_id="EVT_SIMON_KILLS_LINNET",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=800),
        CausalEdge(source_id="EVT_LINNET_MURDERED", target_id="EVT_INVESTIGATION_BEGINS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000),
        CausalEdge(source_id="EVT_INVESTIGATION_BEGINS", target_id="EVT_LOUISE_MURDERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1100),
        CausalEdge(source_id="EVT_LOUISE_MURDERED", target_id="EVT_OTTERBOURNE_MURDERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1200),
        CausalEdge(source_id="EVT_INVESTIGATION_BEGINS", target_id="EVT_PENNINGTON_EXPOSED",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1100),
        CausalEdge(source_id="EVT_POIROT_REVEALS_TRUTH", target_id="EVT_SIMON_CONFESSES",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1600),
        CausalEdge(source_id="EVT_SIMON_CONFESSES", target_id="EVT_MURDER_SUICIDE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1700),
        # mutation
        CausalEdge(source_id="EVT_LINNET_SEDUCES_SIMON", target_id="ENT_JACQUELINE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100,
                   trait_target="jealousy", trait_delta=0.2),
        CausalEdge(source_id="EVT_STAGED_SHOOTING", target_id="ENT_JACQUELINE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=800,
                   trait_target="ruthlessness", trait_delta=0.2),
        CausalEdge(source_id="EVT_LINNET_MURDERED", target_id="ENT_SIMON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1000,
                   trait_target="cunning", trait_delta=0.2),
        CausalEdge(source_id="EVT_POIROT_REVEALS_TRUTH", target_id="ENT_SIMON",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1600,
                   trait_target="greed", trait_delta=-0.3),
        CausalEdge(source_id="EVT_BOULDER_ATTEMPT", target_id="ENT_LINNET",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=600,
                   trait_target="entitlement", trait_delta=-0.1),
        # mutation_social
        CausalEdge(source_id="EVT_LINNET_SEDUCES_SIMON", target_id="ENT_JACQUELINE",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=100,
                   trait_target="affinity", trait_delta=-0.9, rel_counterpart_id="ENT_LINNET"),
        CausalEdge(source_id="EVT_DOYLES_MARRY", target_id="ENT_SIMON",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=200,
                   trait_target="affinity", trait_delta=-0.3, rel_counterpart_id="ENT_JACQUELINE"),
        CausalEdge(source_id="EVT_POIROT_REVEALS_TRUTH", target_id="ENT_JACQUELINE",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1600,
                   trait_target="fear", trait_delta=0.5, rel_counterpart_id="ENT_SIMON"),
        # affordance_gate
        CausalEdge(source_id="OBJ_PISTOL", target_id="EVT_STAGED_SHOOTING",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=800),
        CausalEdge(source_id="OBJ_RED_INK", target_id="EVT_STAGED_SHOOTING",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=800),
        CausalEdge(source_id="OBJ_VELVET_STOLE", target_id="EVT_SIMON_KILLS_LINNET",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=6.0, fabula_time=900),
        CausalEdge(source_id="OBJ_SECOND_PISTOL", target_id="EVT_MURDER_SUICIDE",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1900),
        # ambient_propagation
        CausalEdge(source_id="LOC_KARNAK_DECK", target_id="ENT_LINNET",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=500),
        CausalEdge(source_id="ENT_JACQUELINE", target_id="ENT_LINNET",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=300),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_ASWAN", target_id="LOC_KARNAK_DECK"),
        SpatialEdge(source_id="LOC_KARNAK_DECK", target_id="LOC_KARNAK_LOUNGE"),
        SpatialEdge(source_id="LOC_KARNAK_DECK", target_id="LOC_LINNET_CABIN"),
        SpatialEdge(source_id="LOC_KARNAK_DECK", target_id="LOC_BESSNER_CABIN"),
        SpatialEdge(source_id="LOC_KARNAK_DECK", target_id="LOC_ABU_SIMBEL"),
        SpatialEdge(source_id="LOC_KARNAK_DECK", target_id="LOC_SHELLAL"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_POIROT", target_ids=["ENT_JACQUELINE"],
                        medium="private_warning", established_at_fabula=400),
        InformationEdge(source_id="ENT_RACE", target_ids=["ENT_POIROT"],
                        medium="intelligence_briefing", is_encrypted=True, established_at_fabula=700),
        InformationEdge(source_id="ENT_LOUISE", target_ids=["ENT_SIMON"],
                        medium="whispered_blackmail", is_encrypted=True, established_at_fabula=1100),
        InformationEdge(source_id="ENT_MRS_OTTERBOURNE", target_ids=["ENT_POIROT"],
                        medium="eyewitness_testimony", established_at_fabula=1300, terminated_at_fabula=1300),
        InformationEdge(source_id="ENT_POIROT", target_ids=["ENT_RACE"],
                        medium="deductive_reconstruction", established_at_fabula=1600),
    ],
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_LINNET", target_entity_id="ENT_SIMON",
                         affinity=0.8, fear=0.1, power_dynamic=0.4, inertia=0.5, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_SIMON", target_entity_id="ENT_LINNET",
                         affinity=-0.3, fear=0.0, power_dynamic=-0.3, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_SIMON", target_entity_id="ENT_JACQUELINE",
                         affinity=0.8, fear=0.1, power_dynamic=0.1, inertia=0.5, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_JACQUELINE", target_entity_id="ENT_SIMON",
                         affinity=0.9, fear=0.2, power_dynamic=-0.1, inertia=0.6, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_JACQUELINE", target_entity_id="ENT_LINNET",
                         affinity=-0.9, fear=0.1, power_dynamic=-0.3, inertia=0.4, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_POIROT", target_entity_id="ENT_JACQUELINE",
                         affinity=0.3, fear=0.0, power_dynamic=0.2, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_PENNINGTON", target_entity_id="ENT_LINNET",
                         affinity=-0.3, fear=0.6, power_dynamic=-0.2, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_LOUISE", target_entity_id="ENT_SIMON",
                         affinity=-0.2, fear=0.3, power_dynamic=-0.2, inertia=0.3, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_POIROT", target_entity_id="ENT_RACE",
                         affinity=0.7, fear=0.0, power_dynamic=0.0, inertia=0.5, evidence_strength="strong"),
    ],
)
