"""Frankenstein — high-fidelity WorldStateV1 test fixture."""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_INGOLSTADT_LAB": Location(name="Ingolstadt Laboratory", description="Victor's secret laboratory where he creates the Creature.",
            ambient_state={"obsession": AmbientVector(value=0.8, volatility=0.3), "dread": AmbientVector(value=0.6, volatility=0.4)}),
        "LOC_GENEVA": Location(name="Geneva", description="The Frankenstein family estate on Lake Geneva.",
            ambient_state={"serenity": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_MONT_BLANC": Location(name="Mer de Glace", description="Alpine glacier where Victor confronts the Creature.",
            ambient_state={"sublime": AmbientVector(value=0.8, volatility=0.2), "isolation": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_DELACEY_COTTAGE": Location(name="De Lacey Cottage", description="The cottage where the Creature secretly observes a family.",
            ambient_state={"warmth": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_ORKNEY": Location(name="Orkney Islands", description="Remote island where Victor begins and destroys the female creature.",
            ambient_state={"isolation": AmbientVector(value=0.9, volatility=0.2), "dread": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_ARCTIC": Location(name="Arctic Ice", description="The frozen wastes where Walton finds Victor and the pursuit ends.",
            ambient_state={"desolation": AmbientVector(value=0.9, volatility=0.2)}),
    },
    objects={
        "OBJ_LABORATORY_EQUIPMENT": NarrativeObject(id="OBJ_LABORATORY_EQUIPMENT", name="Laboratory Equipment",
            location_id="LOC_INGOLSTADT_LAB", owner_id="ENT_VICTOR",
            properties={"state": "assembled", "purpose": "reanimation"},
            affordances=[Affordance(action="create_life", target_type="Entity")]),
        "OBJ_JOURNAL": NarrativeObject(id="OBJ_JOURNAL", name="Victor's Journal",
            location_id=None, owner_id="ENT_VICTOR",
            properties={"state": "detailed", "content": "creation_notes"},
            affordances=[Affordance(action="inform", target_type="Entity")]),
        "OBJ_PARADISE_LOST": NarrativeObject(id="OBJ_PARADISE_LOST", name="Paradise Lost",
            location_id="LOC_DELACEY_COTTAGE", owner_id=None,
            properties={"state": "worn"},
            affordances=[Affordance(action="educate", target_type="Entity")]),
    },
    entities={
        "ENT_VICTOR": Entity(id="ENT_VICTOR", name="Victor Frankenstein",
            location_id="LOC_INGOLSTADT_LAB", status="healthy",
            traits={
                "ambition": TraitVector(value=0.9, inertia=0.5),
                "guilt": TraitVector(value=0.2, inertia=0.2),
                "obsession": TraitVector(value=0.8, inertia=0.4),
                "cowardice": TraitVector(value=0.4, inertia=0.3),
                "intellect": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_CREATURE", perceived_state="The Creature is a monster I must destroy", confidence=0.8, inertia=0.4),
                Belief(target_id="ENT_ELIZABETH", perceived_state="Elizabeth is my anchor to normality", confidence=0.8, inertia=0.5),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_CREATURE_ANIMATED",
                    traits={"guilt": TraitVector(value=0.6, inertia=0.2), "obsession": TraitVector(value=0.3, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_WILLIAM_MURDERED",
                    traits={"guilt": TraitVector(value=0.8, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_ELIZABETH_MURDERED",
                    traits={"guilt": TraitVector(value=0.9, inertia=0.3), "ambition": TraitVector(value=0.2, inertia=0.5)}),
            ]),
        "ENT_CREATURE": Entity(id="ENT_CREATURE", name="The Creature",
            location_id="LOC_INGOLSTADT_LAB", status="healthy",
            traits={
                "loneliness": TraitVector(value=0.9, inertia=0.4),
                "eloquence": TraitVector(value=0.7, inertia=0.5),
                "rage": TraitVector(value=0.3, inertia=0.2),
                "compassion": TraitVector(value=0.6, inertia=0.3),
                "intellect": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR", perceived_state="My creator owes me love and companionship", confidence=0.9, inertia=0.5),
                Belief(target_id="ENT_DELACEYS", perceived_state="The De Laceys will accept me if they know my heart", confidence=0.7, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=400, triggered_by="EVT_DELACEY_REJECTION",
                    traits={"rage": TraitVector(value=0.7, inertia=0.3), "compassion": TraitVector(value=0.3, inertia=0.3)},
                    beliefs_invalidated=["ENT_DELACEYS"]),
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_VICTOR_DESTROYS_MATE",
                    traits={"rage": TraitVector(value=0.95, inertia=0.4), "compassion": TraitVector(value=0.1, inertia=0.3)},
                    beliefs_invalidated=["ENT_VICTOR"]),
            ]),
        "ENT_ELIZABETH": Entity(id="ENT_ELIZABETH", name="Elizabeth Lavenza",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "devotion": TraitVector(value=0.8, inertia=0.6),
                "gentleness": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR", perceived_state="Victor is troubled but will recover", confidence=0.7, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_ELIZABETH_MURDERED", new_status="dead"),
            ]),
        "ENT_DELACEYS": Entity(id="ENT_DELACEYS", name="The De Lacey Family",
            location_id="LOC_DELACEY_COTTAGE", status="healthy",
            traits={
                "kindness": TraitVector(value=0.7, inertia=0.5),
                "fear": TraitVector(value=0.3, inertia=0.2),
            },
            beliefs=[]),
        "ENT_HENRY": Entity(id="ENT_HENRY", name="Henry Clerval",
            location_id="LOC_INGOLSTADT_LAB", status="healthy",
            traits={
                "warmth": TraitVector(value=0.8, inertia=0.5),
                "loyalty": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR", perceived_state="Victor needs my support through his illness", confidence=0.8, inertia=0.5),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=850, triggered_by="EVT_HENRY_MURDERED", new_status="dead"),
            ]),
        "ENT_WALTON": Entity(id="ENT_WALTON", name="Robert Walton",
            location_id="LOC_ARCTIC", status="healthy",
            traits={
                "ambition": TraitVector(value=0.7, inertia=0.4),
                "curiosity": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR", perceived_state="Victor is a tragic genius", confidence=0.8, inertia=0.4),
            ]),
        "ENT_JUSTINE": Entity(id="ENT_JUSTINE", name="Justine Moritz",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "innocence": TraitVector(value=0.9, inertia=0.6),
                "loyalty": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_JUSTINE_EXECUTED", new_status="dead"),
            ]),
    },
    events=[
        EventNode(id="EVT_CREATION_OBSESSION", fabula_time=100, syuzhet_index=1, event_type="choice",
                  actor_ids=["ENT_VICTOR"], target_ids=[],
                  description="Victor becomes obsessed with creating life, isolating himself from family."),
        EventNode(id="EVT_CREATURE_ANIMATED", fabula_time=200, syuzhet_index=2, event_type="outcome",
                  actor_ids=["ENT_VICTOR"], target_ids=["ENT_CREATURE"],
                  description="Victor animates the Creature and immediately flees in horror."),
        EventNode(id="EVT_CREATURE_LEARNS", fabula_time=300, syuzhet_index=3, event_type="outcome",
                  actor_ids=["ENT_CREATURE"], target_ids=[],
                  description="The Creature secretly observes the De Lacey family, learning language and morality."),
        EventNode(id="EVT_DELACEY_REJECTION", fabula_time=400, syuzhet_index=4, event_type="outcome",
                  actor_ids=["ENT_CREATURE"], target_ids=["ENT_DELACEYS"],
                  description="The Creature reveals himself to the De Laceys and is violently rejected."),
        EventNode(id="EVT_WILLIAM_MURDERED", fabula_time=500, syuzhet_index=5, event_type="choice",
                  actor_ids=["ENT_CREATURE"], target_ids=["ENT_VICTOR"],
                  description="The Creature murders Victor's younger brother William."),
        EventNode(id="EVT_JUSTINE_EXECUTED", fabula_time=600, syuzhet_index=6, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_JUSTINE"],
                  description="Justine is wrongly convicted and executed for William's murder."),
        EventNode(id="EVT_GLACIER_CONFRONTATION", fabula_time=650, syuzhet_index=7, event_type="revelation",
                  actor_ids=["ENT_CREATURE"], target_ids=["ENT_VICTOR"],
                  description="The Creature tells his tale on the glacier and demands a female companion."),
        EventNode(id="EVT_VICTOR_BEGINS_MATE", fabula_time=700, syuzhet_index=8, event_type="choice",
                  actor_ids=["ENT_VICTOR"], target_ids=[],
                  description="Victor reluctantly begins creating a female creature in the Orkneys."),
        EventNode(id="EVT_VICTOR_DESTROYS_MATE", fabula_time=800, syuzhet_index=9, event_type="choice",
                  actor_ids=["ENT_VICTOR"], target_ids=["ENT_CREATURE"],
                  description="Victor destroys the half-finished female creature as the Creature watches."),
        EventNode(id="EVT_HENRY_MURDERED", fabula_time=850, syuzhet_index=10, event_type="choice",
                  actor_ids=["ENT_CREATURE"], target_ids=["ENT_HENRY"],
                  description="The Creature murders Henry Clerval in revenge."),
        EventNode(id="EVT_ELIZABETH_MURDERED", fabula_time=900, syuzhet_index=11, event_type="choice",
                  actor_ids=["ENT_CREATURE"], target_ids=["ENT_ELIZABETH"],
                  description="The Creature kills Elizabeth on her wedding night."),
        EventNode(id="EVT_ARCTIC_PURSUIT", fabula_time=1000, syuzhet_index=12, event_type="outcome",
                  actor_ids=["ENT_VICTOR"], target_ids=["ENT_CREATURE"],
                  description="Victor pursues the Creature to the Arctic, where he dies; the Creature mourns and departs."),
    ],
    causal_topology=[
        # chain_reaction
        CausalEdge(source_id="EVT_CREATION_OBSESSION", target_id="EVT_CREATURE_ANIMATED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=100),
        CausalEdge(source_id="EVT_CREATURE_ANIMATED", target_id="EVT_CREATURE_LEARNS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200),
        CausalEdge(source_id="EVT_CREATURE_LEARNS", target_id="EVT_DELACEY_REJECTION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300),
        CausalEdge(source_id="EVT_DELACEY_REJECTION", target_id="EVT_WILLIAM_MURDERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=400),
        CausalEdge(source_id="EVT_WILLIAM_MURDERED", target_id="EVT_JUSTINE_EXECUTED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500),
        CausalEdge(source_id="EVT_GLACIER_CONFRONTATION", target_id="EVT_VICTOR_BEGINS_MATE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=650),
        CausalEdge(source_id="EVT_VICTOR_BEGINS_MATE", target_id="EVT_VICTOR_DESTROYS_MATE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700),
        CausalEdge(source_id="EVT_VICTOR_DESTROYS_MATE", target_id="EVT_HENRY_MURDERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=800),
        CausalEdge(source_id="EVT_HENRY_MURDERED", target_id="EVT_ELIZABETH_MURDERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=850),
        CausalEdge(source_id="EVT_ELIZABETH_MURDERED", target_id="EVT_ARCTIC_PURSUIT",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=900),
        # mutation
        CausalEdge(source_id="EVT_CREATURE_ANIMATED", target_id="ENT_VICTOR",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200, trait_target="guilt", trait_delta=0.4),
        CausalEdge(source_id="EVT_DELACEY_REJECTION", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=400, trait_target="rage", trait_delta=0.4),
        CausalEdge(source_id="EVT_WILLIAM_MURDERED", target_id="ENT_VICTOR",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500, trait_target="guilt", trait_delta=0.2),
        CausalEdge(source_id="EVT_VICTOR_DESTROYS_MATE", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=800, trait_target="rage", trait_delta=0.25),
        CausalEdge(source_id="EVT_ELIZABETH_MURDERED", target_id="ENT_VICTOR",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=900, trait_target="ambition", trait_delta=-0.7),
        # mutation_social
        CausalEdge(source_id="EVT_CREATURE_ANIMATED", target_id="ENT_CREATURE",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200, trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_VICTOR"),
        CausalEdge(source_id="EVT_VICTOR_DESTROYS_MATE", target_id="ENT_CREATURE",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=800, trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_VICTOR"),
        CausalEdge(source_id="EVT_GLACIER_CONFRONTATION", target_id="ENT_VICTOR",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=650, trait_target="fear", trait_delta=0.3, rel_counterpart_id="ENT_CREATURE"),
        # affordance_gate
        CausalEdge(source_id="OBJ_LABORATORY_EQUIPMENT", target_id="EVT_CREATURE_ANIMATED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=200),
        CausalEdge(source_id="OBJ_PARADISE_LOST", target_id="EVT_CREATURE_LEARNS",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=300),
        CausalEdge(source_id="ENT_VICTOR", target_id="EVT_VICTOR_BEGINS_MATE",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=700),
        # ambient_propagation
        CausalEdge(source_id="LOC_INGOLSTADT_LAB", target_id="ENT_VICTOR",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=100),
        CausalEdge(source_id="LOC_DELACEY_COTTAGE", target_id="ENT_CREATURE",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=300),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_INGOLSTADT_LAB", target_id="LOC_GENEVA"),
        SpatialEdge(source_id="LOC_GENEVA", target_id="LOC_MONT_BLANC"),
        SpatialEdge(source_id="LOC_INGOLSTADT_LAB", target_id="LOC_DELACEY_COTTAGE"),
        SpatialEdge(source_id="LOC_GENEVA", target_id="LOC_ORKNEY"),
        SpatialEdge(source_id="LOC_ORKNEY", target_id="LOC_ARCTIC"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_CREATURE", target_ids=["ENT_VICTOR"], medium="monologue", established_at_fabula=650),
        InformationEdge(source_id="ENT_VICTOR", target_ids=["ENT_WALTON"], medium="narration", established_at_fabula=1000),
        InformationEdge(source_id="ENT_DELACEYS", target_ids=["ENT_CREATURE"], medium="overheard_conversation", established_at_fabula=300),
    ],
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_VICTOR", target_entity_id="ENT_CREATURE", affinity=-0.7, fear=0.6, power_dynamic=0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_CREATURE", target_entity_id="ENT_VICTOR", affinity=-0.3, fear=0.0, power_dynamic=-0.2, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_VICTOR", target_entity_id="ENT_ELIZABETH", affinity=0.8, fear=0.1, power_dynamic=0.1, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_ELIZABETH", target_entity_id="ENT_VICTOR", affinity=0.8, fear=0.0, power_dynamic=-0.1, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_VICTOR", target_entity_id="ENT_HENRY", affinity=0.8, fear=0.0, power_dynamic=0.0, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_HENRY", target_entity_id="ENT_VICTOR", affinity=0.8, fear=0.0, power_dynamic=0.0, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_CREATURE", target_entity_id="ENT_DELACEYS", affinity=0.6, fear=0.3, power_dynamic=-0.5, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_WALTON", target_entity_id="ENT_VICTOR", affinity=0.5, fear=0.0, power_dynamic=-0.2, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_WALTON", target_entity_id="ENT_CREATURE", affinity=-0.1, fear=0.4, power_dynamic=-0.3, inertia=0.2),
    ],
)
