"""Frankenstein — high-fidelity WorldStateV1 test fixture.

Quality checklist (all five causality modalities, varied force/evidence,
trait_target/trait_delta, state_timeline, rich beliefs, info edges, constants).
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_GENEVA": Location(name="Geneva",
            description="The Frankenstein family home in Switzerland.",
            ambient_state={"comfort": AmbientVector(value=0.7, volatility=0.3),
                           "respectability": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_INGOLSTADT": Location(name="University of Ingolstadt",
            description="Where Victor studies natural philosophy and creates the Creature.",
            ambient_state={"obsession": AmbientVector(value=0.7, volatility=0.4),
                           "ambition": AmbientVector(value=0.8, volatility=0.3)}),
        "LOC_LABORATORY": Location(name="Victor's Laboratory",
            description="Attic laboratory where the Creature is assembled and animated.",
            ambient_state={"horror": AmbientVector(value=0.8, volatility=0.3),
                           "frenzy": AmbientVector(value=0.7, volatility=0.4)}),
        "LOC_ALPINE_WILDERNESS": Location(name="Alpine Wilderness",
            description="Mont Blanc glaciers where the Creature confronts Victor.",
            ambient_state={"sublime": AmbientVector(value=0.8, volatility=0.2),
                           "isolation": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_DELACEY_COTTAGE": Location(name="De Lacey Cottage",
            description="The cottage where the Creature secretly learns language and compassion.",
            ambient_state={"warmth": AmbientVector(value=0.6, volatility=0.3),
                           "poverty": AmbientVector(value=0.5, volatility=0.2)}),
        "LOC_ORKNEY": Location(name="Orkney Islands",
            description="Remote hut where Victor begins then destroys the female creature.",
            ambient_state={"desolation": AmbientVector(value=0.8, volatility=0.2),
                           "dread": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_ARCTIC": Location(name="Arctic Ice",
            description="The frozen sea where Victor pursues the Creature to his death.",
            ambient_state={"death": AmbientVector(value=0.9, volatility=0.2),
                           "vastness": AmbientVector(value=0.8, volatility=0.2)}),
        "LOC_PRISON": Location(name="Irish Prison",
            description="Where Victor is imprisoned after Clerval's murder.",
            ambient_state={"despair": AmbientVector(value=0.8, volatility=0.3)}),
    },
    objects={
        "OBJ_JOURNAL": NarrativeObject(id="OBJ_JOURNAL", name="Victor's Journal",
            location_id=None, owner_id="ENT_VICTOR",
            properties={"state": "written", "content": "creation_notes"},
            affordances=[Affordance(action="inform", target_type="Entity")]),
        "OBJ_GALVANIC_APPARATUS": NarrativeObject(id="OBJ_GALVANIC_APPARATUS",
            name="Galvanic Apparatus", location_id="LOC_LABORATORY", owner_id="ENT_VICTOR",
            properties={"state": "functional", "power": "electrical"},
            affordances=[Affordance(action="animate", target_type="Entity")]),
        "OBJ_DELACEY_BOOKS": NarrativeObject(id="OBJ_DELACEY_BOOKS",
            name="De Lacey Books", location_id="LOC_DELACEY_COTTAGE", owner_id=None,
            properties={"state": "worn", "titles": "Paradise Lost, Plutarch, Werther"},
            affordances=[Affordance(action="educate", target_type="Entity")]),
        "OBJ_FEMALE_CREATURE": NarrativeObject(id="OBJ_FEMALE_CREATURE",
            name="Half-Built Female Creature", location_id="LOC_ORKNEY", owner_id="ENT_VICTOR",
            properties={"state": "destroyed"},
            affordances=[Affordance(action="companion", target_type="Entity")]),
    },
    entities={
        "ENT_VICTOR": Entity(id="ENT_VICTOR", name="Victor Frankenstein",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "ambition": TraitVector(value=0.9, inertia=0.5),
                "guilt": TraitVector(value=0.2, inertia=0.2),
                "fear": TraitVector(value=0.2, inertia=0.2),
                "obsession": TraitVector(value=0.8, inertia=0.4),
                "isolation": TraitVector(value=0.3, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_CREATURE", perceived_state="My creation is an abomination",
                       confidence=0.8, inertia=0.5),
            ],
            constants=["intellect", "social_privilege"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=300, triggered_by="EVT_CREATION",
                    traits={"guilt": TraitVector(value=0.6, inertia=0.3),
                            "fear": TraitVector(value=0.7, inertia=0.3)},
                    new_location_id="LOC_LABORATORY"),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_CREATURE_DEMANDS_MATE",
                    traits={"guilt": TraitVector(value=0.8, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_ELIZABETH_MURDERED",
                    traits={"obsession": TraitVector(value=0.9, inertia=0.5),
                            "isolation": TraitVector(value=0.8, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_VICTOR_DIES",
                    new_status="dead"),
            ]),
        "ENT_CREATURE": Entity(id="ENT_CREATURE", name="The Creature",
            location_id="LOC_LABORATORY", status="healthy",
            traits={
                "loneliness": TraitVector(value=0.3, inertia=0.2),
                "rage": TraitVector(value=0.1, inertia=0.2),
                "eloquence": TraitVector(value=0.2, inertia=0.2),
                "compassion": TraitVector(value=0.7, inertia=0.3),
                "intelligence": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR", perceived_state="My creator abandoned me",
                       confidence=0.9, inertia=0.6),
                Belief(target_id="ENT_DELACEY", perceived_state="The De Laceys could be my family",
                       confidence=0.6, inertia=0.3),
            ],
            constants=["unnatural_origin", "superhuman_strength"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_CREATURE_LEARNS",
                    traits={"eloquence": TraitVector(value=0.7, inertia=0.3),
                            "intelligence": TraitVector(value=0.8, inertia=0.4)},
                    new_location_id="LOC_DELACEY_COTTAGE"),
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_CREATURE_REJECTED",
                    traits={"rage": TraitVector(value=0.6, inertia=0.3),
                            "loneliness": TraitVector(value=0.8, inertia=0.3),
                            "compassion": TraitVector(value=0.4, inertia=0.3)},
                    beliefs_invalidated=["ENT_DELACEY"],
                    beliefs_added=[Belief(target_id="ENT_DELACEY",
                        perceived_state="Humanity will never accept me",
                        confidence=0.9, inertia=0.5, established_at_fabula=600)]),
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_MATE_DESTROYED",
                    traits={"rage": TraitVector(value=0.9, inertia=0.4),
                            "compassion": TraitVector(value=0.1, inertia=0.3)}),
            ]),
        "ENT_ELIZABETH": Entity(id="ENT_ELIZABETH", name="Elizabeth Lavenza",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "devotion": TraitVector(value=0.8, inertia=0.5),
                "patience": TraitVector(value=0.7, inertia=0.5),
                "kindness": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR", perceived_state="Victor loves me but suffers a secret torment",
                       confidence=0.7, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_ELIZABETH_MURDERED",
                    new_status="dead"),
            ]),
        "ENT_CLERVAL": Entity(id="ENT_CLERVAL", name="Henry Clerval",
            location_id="LOC_INGOLSTADT", status="healthy",
            traits={
                "warmth": TraitVector(value=0.8, inertia=0.5),
                "optimism": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR", perceived_state="Victor is brilliant but needs grounding",
                       confidence=0.8, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_CLERVAL_MURDERED",
                    new_status="dead"),
            ]),
        "ENT_WILLIAM": Entity(id="ENT_WILLIAM", name="William Frankenstein",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "innocence": TraitVector(value=0.9, inertia=0.5),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=400, triggered_by="EVT_WILLIAM_MURDERED",
                    new_status="dead"),
            ]),
        "ENT_JUSTINE": Entity(id="ENT_JUSTINE", name="Justine Moritz",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "devotion": TraitVector(value=0.7, inertia=0.5),
                "innocence": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR", perceived_state="The Frankensteins are my benefactors",
                       confidence=0.8, inertia=0.5),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=450, triggered_by="EVT_JUSTINE_EXECUTED",
                    new_status="dead"),
            ]),
        "ENT_DELACEY": Entity(id="ENT_DELACEY", name="Old De Lacey",
            location_id="LOC_DELACEY_COTTAGE", status="healthy",
            traits={
                "blindness": TraitVector(value=1.0, inertia=1.0),
                "compassion": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_CREATURE", perceived_state="A gentle stranger in need",
                       confidence=0.5, inertia=0.3),
            ]),
        "ENT_WALTON": Entity(id="ENT_WALTON", name="Robert Walton",
            location_id="LOC_ARCTIC", status="healthy",
            traits={
                "ambition": TraitVector(value=0.8, inertia=0.4),
                "compassion": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR", perceived_state="Victor is a tragic genius",
                       confidence=0.7, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_VICTOR_DIES",
                    traits={"ambition": TraitVector(value=0.5, inertia=0.4)}),
            ]),
    },
    events=[
        EventNode(id="EVT_VICTOR_STUDIES", fabula_time=100, syuzhet_index=1, event_type="outcome",
                  actor_ids=["ENT_VICTOR"], target_ids=[],
                  description="Victor arrives at Ingolstadt and becomes obsessed with natural philosophy."),
        EventNode(id="EVT_CHARNEL_GATHERING", fabula_time=200, syuzhet_index=2, event_type="choice",
                  actor_ids=["ENT_VICTOR"], target_ids=[],
                  description="Victor secretly gathers body parts from charnel houses and dissecting rooms."),
        EventNode(id="EVT_CREATION", fabula_time=300, syuzhet_index=3, event_type="outcome",
                  actor_ids=["ENT_VICTOR"], target_ids=["ENT_CREATURE"],
                  description="Victor animates the Creature using galvanic apparatus, then flees in horror."),
        EventNode(id="EVT_WILLIAM_MURDERED", fabula_time=400, syuzhet_index=4, event_type="outcome",
                  actor_ids=["ENT_CREATURE"], target_ids=["ENT_WILLIAM"],
                  description="The Creature murders young William Frankenstein near Geneva."),
        EventNode(id="EVT_JUSTINE_EXECUTED", fabula_time=450, syuzhet_index=5, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_JUSTINE"],
                  description="Justine is falsely convicted of William's murder and executed."),
        EventNode(id="EVT_CREATURE_LEARNS", fabula_time=500, syuzhet_index=6, event_type="outcome",
                  actor_ids=["ENT_CREATURE"], target_ids=[],
                  description="The Creature learns language, reading, and empathy by observing the De Laceys."),
        EventNode(id="EVT_CREATURE_REJECTED", fabula_time=600, syuzhet_index=7, event_type="outcome",
                  actor_ids=["ENT_DELACEY"], target_ids=["ENT_CREATURE"],
                  description="The De Laceys' children drive the Creature away; the Creature's hopes shatter."),
        EventNode(id="EVT_CREATURE_DEMANDS_MATE", fabula_time=700, syuzhet_index=8, event_type="choice",
                  actor_ids=["ENT_CREATURE"], target_ids=["ENT_VICTOR"],
                  description="The Creature confronts Victor on Mont Blanc and demands a female companion."),
        EventNode(id="EVT_VICTOR_BEGINS_MATE", fabula_time=800, syuzhet_index=9, event_type="choice",
                  actor_ids=["ENT_VICTOR"], target_ids=[],
                  description="Victor reluctantly begins constructing a female creature on Orkney."),
        EventNode(id="EVT_MATE_DESTROYED", fabula_time=900, syuzhet_index=10, event_type="choice",
                  actor_ids=["ENT_VICTOR"], target_ids=["ENT_CREATURE"],
                  description="Victor destroys the half-finished female creature as the Creature watches."),
        EventNode(id="EVT_CLERVAL_MURDERED", fabula_time=1000, syuzhet_index=11, event_type="outcome",
                  actor_ids=["ENT_CREATURE"], target_ids=["ENT_CLERVAL"],
                  description="The Creature murders Henry Clerval in revenge; Victor is briefly imprisoned."),
        EventNode(id="EVT_ELIZABETH_MURDERED", fabula_time=1100, syuzhet_index=12, event_type="outcome",
                  actor_ids=["ENT_CREATURE"], target_ids=["ENT_ELIZABETH"],
                  description="The Creature kills Elizabeth on her wedding night fulfilling its vow."),
        EventNode(id="EVT_ARCTIC_CHASE", fabula_time=1200, syuzhet_index=13, event_type="outcome",
                  actor_ids=["ENT_VICTOR"], target_ids=["ENT_CREATURE"],
                  description="Victor pursues the Creature across the Arctic wastes, nearing exhaustion."),
        EventNode(id="EVT_VICTOR_DIES", fabula_time=1300, syuzhet_index=14, event_type="outcome",
                  actor_ids=["ENT_VICTOR"], target_ids=["ENT_WALTON"],
                  description="Victor dies aboard Walton's ship; the Creature mourns and vanishes into the ice."),
        EventNode(id="EVT_CREATURE_FINDS_JOURNAL", fabula_time=550, syuzhet_index=15, event_type="revelation",
                  actor_ids=["ENT_CREATURE"], target_ids=[],
                  description="The Creature finds Victor's journal in a coat pocket and learns the horror of its creation."),
    ],
    causal_topology=[
        # chain_reaction (11)
        CausalEdge(source_id="EVT_VICTOR_STUDIES", target_id="EVT_CHARNEL_GATHERING",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="EVT_CHARNEL_GATHERING", target_id="EVT_CREATION",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=200),
        CausalEdge(source_id="EVT_CREATION", target_id="EVT_WILLIAM_MURDERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300),
        CausalEdge(source_id="EVT_WILLIAM_MURDERED", target_id="EVT_JUSTINE_EXECUTED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=400),
        CausalEdge(source_id="EVT_CREATURE_LEARNS", target_id="EVT_CREATURE_REJECTED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500),
        CausalEdge(source_id="EVT_CREATURE_REJECTED", target_id="EVT_CREATURE_DEMANDS_MATE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=600),
        CausalEdge(source_id="EVT_CREATURE_DEMANDS_MATE", target_id="EVT_VICTOR_BEGINS_MATE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700),
        CausalEdge(source_id="EVT_VICTOR_BEGINS_MATE", target_id="EVT_MATE_DESTROYED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=800),
        CausalEdge(source_id="EVT_MATE_DESTROYED", target_id="EVT_CLERVAL_MURDERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=900),
        CausalEdge(source_id="EVT_CLERVAL_MURDERED", target_id="EVT_ELIZABETH_MURDERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000),
        CausalEdge(source_id="EVT_ELIZABETH_MURDERED", target_id="EVT_ARCTIC_CHASE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1100),
        # mutation (8)
        CausalEdge(source_id="EVT_CREATION", target_id="ENT_VICTOR",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300, trait_target="guilt", trait_delta=0.4),
        CausalEdge(source_id="EVT_JUSTINE_EXECUTED", target_id="ENT_VICTOR",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=450, trait_target="guilt", trait_delta=0.2),
        CausalEdge(source_id="EVT_CREATURE_LEARNS", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500, trait_target="eloquence", trait_delta=0.5),
        CausalEdge(source_id="EVT_CREATURE_REJECTED", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600, trait_target="rage", trait_delta=0.5),
        CausalEdge(source_id="EVT_MATE_DESTROYED", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=900, trait_target="compassion", trait_delta=-0.3),
        CausalEdge(source_id="EVT_ELIZABETH_MURDERED", target_id="ENT_VICTOR",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1100, trait_target="isolation", trait_delta=0.5),
        CausalEdge(source_id="EVT_CREATURE_FINDS_JOURNAL", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=550, trait_target="loneliness", trait_delta=0.3),
        CausalEdge(source_id="EVT_VICTOR_DIES", target_id="ENT_WALTON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=1300, trait_target="ambition", trait_delta=-0.3),
        # mutation_social (3)
        CausalEdge(source_id="EVT_CREATURE_REJECTED", target_id="ENT_CREATURE",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600,
                   trait_target="affinity", trait_delta=-0.6, rel_counterpart_id="ENT_DELACEY"),
        CausalEdge(source_id="EVT_MATE_DESTROYED", target_id="ENT_CREATURE",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=900,
                   trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_VICTOR"),
        CausalEdge(source_id="EVT_CREATURE_DEMANDS_MATE", target_id="ENT_VICTOR",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=700,
                   trait_target="fear", trait_delta=0.3, rel_counterpart_id="ENT_CREATURE"),
        # affordance_gate (3)
        CausalEdge(source_id="OBJ_GALVANIC_APPARATUS", target_id="EVT_CREATION",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=300),
        CausalEdge(source_id="OBJ_DELACEY_BOOKS", target_id="EVT_CREATURE_LEARNS",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500),
        CausalEdge(source_id="OBJ_JOURNAL", target_id="EVT_CREATURE_FINDS_JOURNAL",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=550),
        # ambient_propagation (2)
        CausalEdge(source_id="LOC_LABORATORY", target_id="ENT_VICTOR",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=200),
        CausalEdge(source_id="LOC_ARCTIC", target_id="ENT_VICTOR",
                   causality_type="ambient_propagation", mechanism="physical", evidence_strength="weak",
                   causal_force=3.0, fabula_time=1200),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_GENEVA", target_id="LOC_INGOLSTADT"),
        SpatialEdge(source_id="LOC_INGOLSTADT", target_id="LOC_LABORATORY"),
        SpatialEdge(source_id="LOC_GENEVA", target_id="LOC_ALPINE_WILDERNESS"),
        SpatialEdge(source_id="LOC_ALPINE_WILDERNESS", target_id="LOC_DELACEY_COTTAGE"),
        SpatialEdge(source_id="LOC_INGOLSTADT", target_id="LOC_ORKNEY"),
        SpatialEdge(source_id="LOC_ORKNEY", target_id="LOC_PRISON"),
        SpatialEdge(source_id="LOC_GENEVA", target_id="LOC_ARCTIC"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_CREATURE", target_ids=["ENT_VICTOR"],
                        medium="monologue", established_at_fabula=700),
        InformationEdge(source_id="OBJ_JOURNAL", target_ids=["ENT_CREATURE"],
                        medium="journal", established_at_fabula=550),
        InformationEdge(source_id="ENT_VICTOR", target_ids=["ENT_WALTON"],
                        medium="deathbed_narrative", established_at_fabula=1200),
        InformationEdge(source_id="ENT_DELACEY", target_ids=["ENT_CREATURE"],
                        medium="overheard_conversation", established_at_fabula=500),
        InformationEdge(source_id="ENT_ELIZABETH", target_ids=["ENT_VICTOR"],
                        medium="letter", established_at_fabula=400),
    ],
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_VICTOR", target_entity_id="ENT_CREATURE",
                         affinity=-0.7, fear=0.6, power_dynamic=0.2, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_CREATURE", target_entity_id="ENT_VICTOR",
                         affinity=-0.5, fear=0.0, power_dynamic=-0.2, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_VICTOR", target_entity_id="ENT_ELIZABETH",
                         affinity=0.8, fear=0.0, power_dynamic=0.1, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_ELIZABETH", target_entity_id="ENT_VICTOR",
                         affinity=0.8, fear=0.1, power_dynamic=-0.1, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_VICTOR", target_entity_id="ENT_CLERVAL",
                         affinity=0.8, fear=0.0, power_dynamic=0.0, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_CREATURE", target_entity_id="ENT_DELACEY",
                         affinity=0.5, fear=0.3, power_dynamic=-0.4, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_VICTOR", target_entity_id="ENT_WALTON",
                         affinity=0.4, fear=0.0, power_dynamic=0.1, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_WALTON", target_entity_id="ENT_VICTOR",
                         affinity=0.6, fear=0.0, power_dynamic=-0.1, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_CREATURE", target_entity_id="ENT_ELIZABETH",
                         affinity=-0.3, fear=0.0, power_dynamic=0.5, inertia=0.3),
    ],
)
