"""Gone Girl — high-fidelity WorldStateV1 test fixture.

Quality checklist (all five causality modalities, varied force/evidence,
trait_target/trait_delta, state_timeline, rich beliefs, info edges, constants).
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_DUNNE_HOUSE": Location(name="Dunne House",
            description="Nick and Amy's house in North Carthage, Missouri.",
            ambient_state={"tension": AmbientVector(value=0.7, volatility=0.4),
                           "stagnation": AmbientVector(value=0.6, volatility=0.3)}),
        "LOC_BAR": Location(name="The Bar",
            description="Nick and Margo's bar, purchased with Amy's trust fund.",
            ambient_state={"refuge": AmbientVector(value=0.5, volatility=0.3)}),
        "LOC_HIDEOUT_OZARKS": Location(name="Ozarks Hideout",
            description="Amy's pre-planned hideout cabin in the Ozarks.",
            ambient_state={"isolation": AmbientVector(value=0.8, volatility=0.2),
                           "control": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_DESI_LAKE_HOUSE": Location(name="Desi's Lake House",
            description="Desi Collings's luxurious lake house where Amy takes refuge.",
            ambient_state={"luxury": AmbientVector(value=0.7, volatility=0.2),
                           "entrapment": AmbientVector(value=0.6, volatility=0.4)}),
        "LOC_POLICE_STATION": Location(name="Police Station",
            description="North Carthage PD where the investigation unfolds.",
            ambient_state={"suspicion": AmbientVector(value=0.7, volatility=0.4)}),
        "LOC_MEDIA_CIRCUS": Location(name="Media Spotlight",
            description="The national media circus around Amy's disappearance.",
            ambient_state={"hysteria": AmbientVector(value=0.8, volatility=0.4)}),
        "LOC_NEW_YORK": Location(name="New York City",
            description="Where Nick and Amy originally met and lived.",
            ambient_state={"nostalgia": AmbientVector(value=0.5, volatility=0.3)}),
        "LOC_WOODLAWN": Location(name="Woodlawn",
            description="Missouri suburb where Amy stages treasure hunt clues.",
            ambient_state={"suburban_dread": AmbientVector(value=0.6, volatility=0.3)}),
    },
    objects={
        "OBJ_DIARY": NarrativeObject(id="OBJ_DIARY", name="Amy's Fake Diary",
            location_id="LOC_DUNNE_HOUSE", owner_id="ENT_AMY",
            properties={"state": "planted", "purpose": "frame_nick"},
            affordances=[Affordance(action="incriminate", target_type="Entity")]),
        "OBJ_TREASURE_HUNT": NarrativeObject(id="OBJ_TREASURE_HUNT",
            name="Anniversary Treasure Hunt Clues",
            location_id=None, owner_id="ENT_AMY",
            properties={"state": "staged", "purpose": "implicate_nick"},
            affordances=[Affordance(action="mislead", target_type="Entity")]),
        "OBJ_BOX_CUTTER": NarrativeObject(id="OBJ_BOX_CUTTER", name="Box Cutter",
            location_id="LOC_DESI_LAKE_HOUSE", owner_id=None,
            properties={"state": "concealed"},
            affordances=[Affordance(action="kill", target_type="Entity")]),
        "OBJ_PUPPET_STRINGS": NarrativeObject(id="OBJ_PUPPET_STRINGS",
            name="Vomit-Inducing Antifreeze",
            location_id="LOC_DUNNE_HOUSE", owner_id="ENT_AMY",
            properties={"state": "hidden", "purpose": "evidence"},
            affordances=[Affordance(action="poison_evidence", target_type="Entity")]),
    },
    entities={
        "ENT_NICK": Entity(id="ENT_NICK", name="Nick Dunne",
            location_id="LOC_DUNNE_HOUSE", status="healthy",
            traits={
                "charm": TraitVector(value=0.7, inertia=0.4),
                "cowardice": TraitVector(value=0.6, inertia=0.4),
                "deception": TraitVector(value=0.5, inertia=0.3),
                "resentment": TraitVector(value=0.6, inertia=0.4),
                "adaptability": TraitVector(value=0.5, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_AMY", perceived_state="Amy is controlling and impossible to please",
                       confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_MARGO", perceived_state="Margo is the only person who truly knows me",
                       confidence=0.9, inertia=0.6),
            ],
            constants=["writer", "twin_bond"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_AMY_DISAPPEARS",
                    traits={"deception": TraitVector(value=0.7, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_NICK_TV_CONFESSION",
                    traits={"adaptability": TraitVector(value=0.7, inertia=0.3)},
                    beliefs_invalidated=["ENT_AMY"],
                    beliefs_added=[Belief(target_id="ENT_AMY",
                        perceived_state="Amy framed me and I must out-manipulate her",
                        confidence=0.9, inertia=0.5, established_at_fabula=700)]),
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_AMY_RETURNS",
                    traits={"cowardice": TraitVector(value=0.7, inertia=0.4)}),
            ]),
        "ENT_AMY": Entity(id="ENT_AMY", name="Amy Elliott Dunne",
            location_id="LOC_DUNNE_HOUSE", status="healthy",
            traits={
                "intelligence": TraitVector(value=0.95, inertia=0.6),
                "narcissism": TraitVector(value=0.8, inertia=0.5),
                "manipulation": TraitVector(value=0.9, inertia=0.5),
                "vindictiveness": TraitVector(value=0.8, inertia=0.5),
                "control": TraitVector(value=0.9, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_NICK", perceived_state="Nick has betrayed everything I gave him",
                       confidence=0.95, inertia=0.6),
                Belief(target_id="ENT_DESI", perceived_state="Desi is a useful pawn",
                       confidence=0.8, inertia=0.4),
            ],
            constants=["amazing_amy", "trust_fund"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_AMY_DISAPPEARS",
                    location_id="LOC_HIDEOUT_OZARKS"),
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_AMY_ROBBED",
                    traits={"control": TraitVector(value=0.7, inertia=0.5)},
                    location_id="LOC_DESI_LAKE_HOUSE"),
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_AMY_KILLS_DESI",
                    traits={"vindictiveness": TraitVector(value=0.9, inertia=0.5)}),
            ]),
        "ENT_MARGO": Entity(id="ENT_MARGO", name="Margo Dunne",
            location_id="LOC_BAR", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.9, inertia=0.6),
                "perceptiveness": TraitVector(value=0.7, inertia=0.5),
                "directness": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_NICK", perceived_state="Nick is flawed but not a killer",
                       confidence=0.8, inertia=0.5),
            ],
            constants=["twin_bond"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_NICK_AFFAIR_REVEALED",
                    traits={"loyalty": TraitVector(value=0.7, inertia=0.6)},
                    beliefs_invalidated=["ENT_NICK"],
                    beliefs_added=[Belief(target_id="ENT_NICK",
                        perceived_state="Nick lied to me — but he may still be innocent",
                        confidence=0.6, inertia=0.4, established_at_fabula=500)]),
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_AMY_RETURNS",
                    traits={"perceptiveness": TraitVector(value=0.8, inertia=0.5)}),
            ]),
        "ENT_BONEY": Entity(id="ENT_BONEY", name="Detective Rhonda Boney",
            location_id="LOC_POLICE_STATION", status="healthy",
            traits={
                "thoroughness": TraitVector(value=0.8, inertia=0.5),
                "skepticism": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_NICK", perceived_state="Nick is the prime suspect",
                       confidence=0.7, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_AMY_RETURNS",
                    beliefs_invalidated=["ENT_NICK"],
                    beliefs_added=[Belief(target_id="ENT_NICK",
                        perceived_state="Nick may be innocent but something is very wrong",
                        confidence=0.6, inertia=0.4, established_at_fabula=1100)]),
            ]),
        "ENT_DESI": Entity(id="ENT_DESI", name="Desi Collings",
            location_id="LOC_DESI_LAKE_HOUSE", status="healthy",
            traits={
                "obsession": TraitVector(value=0.8, inertia=0.5),
                "possessiveness": TraitVector(value=0.7, inertia=0.5),
                "wealth": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_AMY", perceived_state="Amy finally needs me",
                       confidence=0.8, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_AMY_KILLS_DESI",
                    status="dead"),
            ]),
        "ENT_TANNER": Entity(id="ENT_TANNER", name="Tanner Bolt",
            location_id="LOC_POLICE_STATION", status="healthy",
            traits={
                "cunning": TraitVector(value=0.8, inertia=0.5),
                "showmanship": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_NICK", perceived_state="Nick is innocent but terrible at looking innocent",
                       confidence=0.7, inertia=0.4),
            ]),
        "ENT_ANDIE": Entity(id="ENT_ANDIE", name="Andie Hardy",
            location_id="LOC_WOODLAWN", status="healthy",
            traits={
                "naivety": TraitVector(value=0.7, inertia=0.4),
                "impulsiveness": TraitVector(value=0.6, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_NICK", perceived_state="Nick loves me and will leave Amy",
                       confidence=0.7, inertia=0.3),
            ]),
    },
    events=[
        EventNode(id="EVT_MARRIAGE_CRUMBLES", fabula_time=100, syuzhet_index=1, event_type="outcome",
                  actor_ids=["ENT_NICK", "ENT_AMY"], target_ids=[],
                  description="Nick and Amy's marriage deteriorates after moving to Missouri."),
        EventNode(id="EVT_AMY_DISAPPEARS", fabula_time=200, syuzhet_index=2, event_type="choice",
                  actor_ids=["ENT_AMY"], target_ids=["ENT_NICK"],
                  description="Amy stages her own disappearance on their fifth anniversary."),
        EventNode(id="EVT_DIARY_FOUND", fabula_time=300, syuzhet_index=3, event_type="outcome",
                  actor_ids=["ENT_BONEY"], target_ids=["ENT_NICK"],
                  description="Police find Amy's fabricated diary painting Nick as abusive."),
        EventNode(id="EVT_TREASURE_HUNT_CLUES", fabula_time=400, syuzhet_index=4, event_type="outcome",
                  actor_ids=["ENT_NICK"], target_ids=[],
                  description="Nick follows Amy's treasure hunt; each clue points to damning evidence."),
        EventNode(id="EVT_NICK_AFFAIR_REVEALED", fabula_time=500, syuzhet_index=5, event_type="revelation",
                  actor_ids=["ENT_ANDIE"], target_ids=["ENT_NICK"],
                  description="Nick's affair with Andie becomes public, destroying his credibility."),
        EventNode(id="EVT_NICK_HIRES_TANNER", fabula_time=600, syuzhet_index=6, event_type="choice",
                  actor_ids=["ENT_NICK"], target_ids=["ENT_TANNER"],
                  description="Nick hires celebrity lawyer Tanner Bolt to fight back."),
        EventNode(id="EVT_NICK_TV_CONFESSION", fabula_time=700, syuzhet_index=7, event_type="choice",
                  actor_ids=["ENT_NICK"], target_ids=["ENT_AMY"],
                  description="Nick goes on TV to apologise and beg Amy to return, playing her game."),
        EventNode(id="EVT_AMY_ROBBED", fabula_time=800, syuzhet_index=8, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_AMY"],
                  description="Amy is robbed at her Ozarks hideout, losing her cash reserve."),
        EventNode(id="EVT_AMY_GOES_TO_DESI", fabula_time=850, syuzhet_index=9, event_type="choice",
                  actor_ids=["ENT_AMY"], target_ids=["ENT_DESI"],
                  description="Desperate, Amy contacts Desi and moves into his lake house."),
        EventNode(id="EVT_NICK_FIGURES_OUT", fabula_time=900, syuzhet_index=10, event_type="revelation",
                  actor_ids=["ENT_NICK"], target_ids=[],
                  description="Nick deduces that Amy is alive and framed him; he plans a public counter-move."),
        EventNode(id="EVT_AMY_KILLS_DESI", fabula_time=1000, syuzhet_index=11, event_type="choice",
                  actor_ids=["ENT_AMY"], target_ids=["ENT_DESI"],
                  description="Amy murders Desi, staging it as an escape from a kidnapper."),
        EventNode(id="EVT_AMY_RETURNS", fabula_time=1100, syuzhet_index=12, event_type="outcome",
                  actor_ids=["ENT_AMY"], target_ids=["ENT_NICK"],
                  description="Amy returns home bloodied, cast as a survivor; Nick is trapped."),
        EventNode(id="EVT_NICK_STAYS", fabula_time=1200, syuzhet_index=13, event_type="choice",
                  actor_ids=["ENT_NICK"], target_ids=["ENT_AMY"],
                  description="Nick decides to stay with Amy after she reveals she's pregnant with his child."),
        EventNode(id="EVT_INTERROGATION", fabula_time=350, syuzhet_index=14, event_type="outcome",
                  actor_ids=["ENT_BONEY"], target_ids=["ENT_NICK"],
                  description="Detective Boney interrogates Nick, probing inconsistencies in his alibi."),
        EventNode(id="EVT_MEDIA_TURNS", fabula_time=550, syuzhet_index=15, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_NICK"],
                  description="National media turns against Nick after the affair revelation."),
        EventNode(id="EVT_AMY_PREGNANCY_TRAP", fabula_time=1150, syuzhet_index=16, event_type="revelation",
                  actor_ids=["ENT_AMY"], target_ids=["ENT_NICK"],
                  description="Amy reveals she used Nick's stored sperm to become pregnant, binding him."),
    ],
    causal_topology=[
        # chain_reaction (12)
        CausalEdge(source_id="EVT_MARRIAGE_CRUMBLES", target_id="EVT_AMY_DISAPPEARS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=100),
        CausalEdge(source_id="EVT_AMY_DISAPPEARS", target_id="EVT_DIARY_FOUND",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200),
        CausalEdge(source_id="EVT_DIARY_FOUND", target_id="EVT_INTERROGATION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300),
        CausalEdge(source_id="EVT_DIARY_FOUND", target_id="EVT_TREASURE_HUNT_CLUES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300),
        CausalEdge(source_id="EVT_NICK_AFFAIR_REVEALED", target_id="EVT_MEDIA_TURNS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500),
        CausalEdge(source_id="EVT_MEDIA_TURNS", target_id="EVT_NICK_HIRES_TANNER",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=550),
        CausalEdge(source_id="EVT_NICK_HIRES_TANNER", target_id="EVT_NICK_TV_CONFESSION",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600),
        CausalEdge(source_id="EVT_AMY_ROBBED", target_id="EVT_AMY_GOES_TO_DESI",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=800),
        CausalEdge(source_id="EVT_AMY_GOES_TO_DESI", target_id="EVT_AMY_KILLS_DESI",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=850),
        CausalEdge(source_id="EVT_AMY_KILLS_DESI", target_id="EVT_AMY_RETURNS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1000),
        CausalEdge(source_id="EVT_AMY_RETURNS", target_id="EVT_AMY_PREGNANCY_TRAP",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1100),
        CausalEdge(source_id="EVT_AMY_PREGNANCY_TRAP", target_id="EVT_NICK_STAYS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1150),
        # mutation (7)
        CausalEdge(source_id="EVT_AMY_DISAPPEARS", target_id="ENT_NICK",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200, trait_target="deception", trait_delta=0.2),
        CausalEdge(source_id="EVT_NICK_AFFAIR_REVEALED", target_id="ENT_NICK",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=500, trait_target="charm", trait_delta=-0.2),
        CausalEdge(source_id="EVT_NICK_TV_CONFESSION", target_id="ENT_NICK",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=700, trait_target="adaptability", trait_delta=0.2),
        CausalEdge(source_id="EVT_AMY_ROBBED", target_id="ENT_AMY",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=800, trait_target="control", trait_delta=-0.2),
        CausalEdge(source_id="EVT_AMY_KILLS_DESI", target_id="ENT_AMY",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000, trait_target="vindictiveness", trait_delta=0.1),
        CausalEdge(source_id="EVT_AMY_RETURNS", target_id="ENT_NICK",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1100, trait_target="cowardice", trait_delta=0.1),
        CausalEdge(source_id="EVT_NICK_AFFAIR_REVEALED", target_id="ENT_MARGO",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=500, trait_target="loyalty", trait_delta=-0.2),
        # mutation_social (4)
        CausalEdge(source_id="EVT_NICK_TV_CONFESSION", target_id="ENT_AMY",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=700,
                   trait_target="affinity", trait_delta=0.3, rel_counterpart_id="ENT_NICK"),
        CausalEdge(source_id="EVT_AMY_GOES_TO_DESI", target_id="ENT_DESI",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=850,
                   trait_target="affinity", trait_delta=0.3, rel_counterpart_id="ENT_AMY"),
        CausalEdge(source_id="EVT_AMY_RETURNS", target_id="ENT_NICK",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1100,
                   trait_target="fear", trait_delta=0.5, rel_counterpart_id="ENT_AMY"),
        CausalEdge(source_id="EVT_NICK_AFFAIR_REVEALED", target_id="ENT_MARGO",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=500,
                   trait_target="affinity", trait_delta=-0.2, rel_counterpart_id="ENT_NICK"),
        # affordance_gate (3)
        CausalEdge(source_id="OBJ_DIARY", target_id="EVT_DIARY_FOUND",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=9.0, fabula_time=300),
        CausalEdge(source_id="OBJ_BOX_CUTTER", target_id="EVT_AMY_KILLS_DESI",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000),
        CausalEdge(source_id="OBJ_TREASURE_HUNT", target_id="EVT_TREASURE_HUNT_CLUES",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=400),
        # ambient_propagation (2)
        CausalEdge(source_id="LOC_MEDIA_CIRCUS", target_id="ENT_NICK",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=500),
        CausalEdge(source_id="LOC_DESI_LAKE_HOUSE", target_id="ENT_AMY",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=850),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_DUNNE_HOUSE", target_id="LOC_BAR"),
        SpatialEdge(source_id="LOC_DUNNE_HOUSE", target_id="LOC_WOODLAWN"),
        SpatialEdge(source_id="LOC_DUNNE_HOUSE", target_id="LOC_POLICE_STATION"),
        SpatialEdge(source_id="LOC_HIDEOUT_OZARKS", target_id="LOC_DESI_LAKE_HOUSE"),
        SpatialEdge(source_id="LOC_NEW_YORK", target_id="LOC_DUNNE_HOUSE"),
        SpatialEdge(source_id="LOC_POLICE_STATION", target_id="LOC_MEDIA_CIRCUS"),
        SpatialEdge(source_id="LOC_DESI_LAKE_HOUSE", target_id="LOC_DUNNE_HOUSE"),
    ],
    information_topology=[
        InformationEdge(source_id="OBJ_DIARY", target_ids=["ENT_BONEY"],
                        medium="evidence", established_at_fabula=300),
        InformationEdge(source_id="ENT_ANDIE", target_ids=["ENT_BONEY"],
                        medium="media_leak", established_at_fabula=500),
        InformationEdge(source_id="ENT_NICK", target_ids=["ENT_MARGO"],
                        medium="confession", established_at_fabula=200),
        InformationEdge(source_id="ENT_TANNER", target_ids=["ENT_NICK"],
                        medium="legal_strategy", established_at_fabula=600),
        InformationEdge(source_id="ENT_AMY", target_ids=["ENT_NICK"],
                        medium="staged_return", established_at_fabula=1100),
    ],
    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_MEDIA_TRIAL": GlobalTrait(
            id="WORLD_MEDIA_TRIAL",
            name="Trial by Media",
            description="The 24-hour news cycle and social media create a parallel justice system where public opinion is weaponised and truth is irrelevant.",
            category="social_structure",
            magnitude=TraitVector(value=0.7, inertia=0.5),
            affected_domains=["social", "psychological", "epistemic"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=500, triggered_by="EVT_MEDIA_FRENZY",
                    magnitude=TraitVector(value=0.9, inertia=0.6),
                    description="Amy's disappearance becomes a national media spectacle that traps Nick."),
                WorldTraitSnapshot(fabula_time=1100, triggered_by="EVT_AMY_RETURNS",
                    magnitude=TraitVector(value=1.0, inertia=0.7),
                    description="Amy's return transforms the media narrative — she controls the story completely."),
            ],
        ),
        "WORLD_SUBURBAN_PERFORMANCE": GlobalTrait(
            id="WORLD_SUBURBAN_PERFORMANCE",
            name="Marriage as Performance",
            description="The expectation that couples perform happiness for neighbours, family, and cameras. Authenticity is sacrificed for appearances.",
            category="social_structure",
            magnitude=TraitVector(value=0.8, inertia=0.7),
            affected_domains=["psychological", "social"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=1200, triggered_by="EVT_NICK_CAPITULATES",
                    magnitude=TraitVector(value=1.0, inertia=0.9),
                    description="Nick agrees to stay married and perform the perfect-couple charade indefinitely."),
            ],
        ),
    },
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_AMY", target_entity_id="ENT_NICK",
                         affinity=-0.3, fear=0.0, power_dynamic=0.6, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_NICK", target_entity_id="ENT_MARGO",
                         affinity=0.9, fear=0.0, power_dynamic=0.0, inertia=0.6),
        RelationshipEdge(source_entity_id="ENT_MARGO", target_entity_id="ENT_NICK",
                         affinity=0.8, fear=0.0, power_dynamic=0.0, inertia=0.6),
        RelationshipEdge(source_entity_id="ENT_AMY", target_entity_id="ENT_DESI",
                         affinity=-0.2, fear=0.0, power_dynamic=0.5, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_DESI", target_entity_id="ENT_AMY",
                         affinity=0.7, fear=0.0, power_dynamic=-0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_BONEY", target_entity_id="ENT_NICK",
                         affinity=-0.2, fear=0.0, power_dynamic=0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_NICK", target_entity_id="ENT_ANDIE",
                         affinity=0.3, fear=0.1, power_dynamic=0.2, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_NICK", target_entity_id="ENT_TANNER",
                         affinity=0.4, fear=0.0, power_dynamic=-0.2, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_MARGO", target_entity_id="ENT_AMY",
                         affinity=-0.5, fear=0.1, power_dynamic=-0.2, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_AMY", target_entity_id="ENT_MARGO",
                         affinity=-0.4, fear=0.0, power_dynamic=0.3, inertia=0.3),
    ],
)
