"""Gone Girl — high-fidelity WorldStateV1 test fixture.

Quality checklist (all five causality modalities, varied force/evidence,
trait_target/trait_delta, state_timeline, rich beliefs, info edges).
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_DUNNE_HOUSE": Location(
            name="Dunne House", description="Nick and Amy's home in North Carthage where Amy stages her disappearance.",
            ambient_state={"tension": AmbientVector(value=0.8, volatility=0.5)},
        ),
        "LOC_BAR": Location(
            name="The Bar", description="Bar co-owned by Nick and Margo, funded by Amy's trust fund.",
            ambient_state={"familiarity": AmbientVector(value=0.6, volatility=0.3)},
        ),
        "LOC_MOTEL": Location(
            name="Hideaway Motel", description="Seedy motel where Amy hides after faking her disappearance.",
            ambient_state={"danger": AmbientVector(value=0.6, volatility=0.5)},
        ),
        "LOC_DESI_LAKE_HOUSE": Location(
            name="Desi's Lake House", description="Luxurious lakeside property where Desi shelters Amy.",
            ambient_state={"tension": AmbientVector(value=0.7, volatility=0.4), "concealment": AmbientVector(value=0.8, volatility=0.3)},
        ),
        "LOC_POLICE_STATION": Location(
            name="Police Station", description="North Carthage police station where the investigation is run.",
            ambient_state={"tension": AmbientVector(value=0.7, volatility=0.4)},
        ),
        "LOC_TV_STUDIO": Location(
            name="TV Studio", description="Studio where Nick gives his public apology interview.",
            ambient_state={"exposure": AmbientVector(value=0.9, volatility=0.3)},
        ),
        "LOC_WOODSHED": Location(
            name="Go's Woodshed", description="Storage shed where Amy planted incriminating evidence.",
            ambient_state={"concealment": AmbientVector(value=0.7, volatility=0.4)},
        ),
    },

    objects={
        "OBJ_DIARY": NarrativeObject(
            id="OBJ_DIARY", name="Amy's Fabricated Diary",
            location_id=None, owner_id="ENT_AMY",
            properties={"state": "planted", "content": "fabricated_abuse_narrative"},
            affordances=[Affordance(action="incriminate", target_type="Entity"), Affordance(action="deceive", target_type="Entity")],
        ),
        "OBJ_PUPPETS": NarrativeObject(
            id="OBJ_PUPPETS", name="Punch and Judy Puppets",
            location_id="LOC_WOODSHED", owner_id=None,
            properties={"state": "one_missing_handle"},
            affordances=[Affordance(action="implicate", target_type="Entity")],
        ),
        "OBJ_CREDIT_CARDS": NarrativeObject(
            id="OBJ_CREDIT_CARDS", name="Credit Cards in Nick's Name",
            location_id="LOC_WOODSHED", owner_id=None,
            properties={"state": "maxed_out", "holder": "nick_dunne"},
            affordances=[Affordance(action="incriminate", target_type="Entity")],
        ),
        "OBJ_LIFE_INSURANCE": NarrativeObject(
            id="OBJ_LIFE_INSURANCE", name="Amy's Life Insurance Policy",
            location_id=None, owner_id="ENT_NICK",
            properties={"state": "recently_increased"},
            affordances=[Affordance(action="implicate", target_type="Entity")],
        ),
    },

    entities={
        "ENT_NICK": Entity(
            id="ENT_NICK", name="Nick Dunne",
            location_id="LOC_DUNNE_HOUSE", status="healthy",
            traits={
                "charm": TraitVector(value=0.7, inertia=0.4),
                "passivity": TraitVector(value=0.6, inertia=0.4),
                "dishonesty": TraitVector(value=0.5, inertia=0.3),
                "guilt": TraitVector(value=0.3, inertia=0.2),
                "fear": TraitVector(value=0.2, inertia=0.2),
                "resolve": TraitVector(value=0.3, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_AMY", perceived_state="Amy is controlling and impossible to please", confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_ANDIE", perceived_state="Andie is my escape from a failing marriage", confidence=0.7, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=100, triggered_by="EVT_AMY_DISAPPEARS",
                    traits={"fear": TraitVector(value=0.6, inertia=0.2), "guilt": TraitVector(value=0.5, inertia=0.2)}),
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_NICK_DISCOVERS_CLUES",
                    traits={"fear": TraitVector(value=0.8, inertia=0.2), "resolve": TraitVector(value=0.6, inertia=0.3)},
                    beliefs_invalidated=["ENT_AMY"]),
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_NICK_ARRESTED",
                    traits={"fear": TraitVector(value=0.9, inertia=0.2)}),
            ],
        ),
        "ENT_AMY": Entity(
            id="ENT_AMY", name="Amy Elliott Dunne",
            location_id="LOC_DUNNE_HOUSE", status="healthy",
            traits={
                "intelligence": TraitVector(value=0.95, inertia=0.7),
                "manipulation": TraitVector(value=0.9, inertia=0.6),
                "narcissism": TraitVector(value=0.8, inertia=0.6),
                "vindictiveness": TraitVector(value=0.8, inertia=0.5),
                "control": TraitVector(value=0.9, inertia=0.6),
                "desperation": TraitVector(value=0.2, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_NICK", perceived_state="Nick has betrayed me and must pay", confidence=0.95, inertia=0.7),
                Belief(target_id="ENT_DESI", perceived_state="Desi is a useful tool who can be manipulated", confidence=0.8, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=100, triggered_by="EVT_AMY_DISAPPEARS",
                    new_location_id="LOC_MOTEL"),
                EntityStateSnapshot(fabula_time=400, triggered_by="EVT_AMY_ROBBED",
                    traits={"desperation": TraitVector(value=0.7, inertia=0.3)},
                    new_location_id="LOC_DESI_LAKE_HOUSE"),
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_AMY_KILLS_DESI",
                    traits={"control": TraitVector(value=0.95, inertia=0.6)},
                    new_location_id="LOC_DUNNE_HOUSE"),
            ],
        ),
        "ENT_MARGO": Entity(
            id="ENT_MARGO", name="Margo 'Go' Dunne",
            location_id="LOC_BAR", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.9, inertia=0.6),
                "suspicion": TraitVector(value=0.5, inertia=0.3),
                "protectiveness": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_NICK", perceived_state="Nick is flawed but not a murderer", confidence=0.8, inertia=0.5),
            ],
        ),
        "ENT_DETECTIVE_BONEY": Entity(
            id="ENT_DETECTIVE_BONEY", name="Detective Rhonda Boney",
            location_id="LOC_POLICE_STATION", status="healthy",
            traits={
                "diligence": TraitVector(value=0.8, inertia=0.6),
                "suspicion": TraitVector(value=0.7, inertia=0.4),
                "integrity": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_NICK", perceived_state="Nick is the primary suspect", confidence=0.7, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_AMY_RETURNS",
                    beliefs_invalidated=["ENT_NICK"],
                    beliefs_added=[Belief(target_id="ENT_AMY", perceived_state="Amy is lying about the kidnapping", confidence=0.8, inertia=0.3)]),
            ],
        ),
        "ENT_DESI": Entity(
            id="ENT_DESI", name="Desi Collings",
            location_id="LOC_DESI_LAKE_HOUSE", status="healthy",
            traits={
                "obsessiveness": TraitVector(value=0.8, inertia=0.5),
                "possessiveness": TraitVector(value=0.7, inertia=0.5),
                "wealth": TraitVector(value=0.9, inertia=0.8),
            },
            beliefs=[
                Belief(target_id="ENT_AMY", perceived_state="Amy needs my protection and loves me", confidence=0.8, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_AMY_KILLS_DESI", new_status="dead"),
            ],
        ),
        "ENT_ANDIE": Entity(
            id="ENT_ANDIE", name="Andie Hardy",
            location_id="LOC_BAR", status="healthy",
            traits={
                "naivete": TraitVector(value=0.7, inertia=0.4),
                "affection": TraitVector(value=0.6, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_NICK", perceived_state="Nick will leave Amy for me", confidence=0.7, inertia=0.3),
            ],
        ),
        "ENT_TANNER_BOLT": Entity(
            id="ENT_TANNER_BOLT", name="Tanner Bolt",
            location_id="LOC_DUNNE_HOUSE", status="healthy",
            traits={
                "cunning": TraitVector(value=0.85, inertia=0.5),
                "pragmatism": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_NICK", perceived_state="Nick is innocent but looks guilty", confidence=0.7, inertia=0.4),
            ],
        ),
    },

    events=[
        EventNode(id="EVT_MARRIAGE_DETERIORATES", fabula_time=50, syuzhet_index=1,
                  event_type="outcome", actor_ids=["ENT_NICK", "ENT_AMY"], target_ids=[],
                  description="Nick and Amy's marriage deteriorates after moving to Missouri; Nick begins affair with Andie."),
        EventNode(id="EVT_AMY_DISAPPEARS", fabula_time=100, syuzhet_index=2,
                  event_type="choice", actor_ids=["ENT_AMY"], target_ids=["ENT_NICK"],
                  description="Amy stages her disappearance on their fifth wedding anniversary, framing Nick."),
        EventNode(id="EVT_INVESTIGATION_BEGINS", fabula_time=200, syuzhet_index=3,
                  event_type="outcome", actor_ids=["ENT_DETECTIVE_BONEY"], target_ids=["ENT_NICK"],
                  description="Police investigation begins with Nick as primary suspect."),
        EventNode(id="EVT_PREGNANCY_REVEALED", fabula_time=300, syuzhet_index=4,
                  event_type="revelation", actor_ids=[], target_ids=["ENT_NICK"],
                  description="Noelle reveals Amy was pregnant, turning public opinion against Nick."),
        EventNode(id="EVT_AMY_ROBBED", fabula_time=400, syuzhet_index=5,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_AMY"],
                  description="Amy is robbed at the motel, losing her cash reserves."),
        EventNode(id="EVT_AMY_SEEKS_DESI", fabula_time=500, syuzhet_index=6,
                  event_type="choice", actor_ids=["ENT_AMY"], target_ids=["ENT_DESI"],
                  description="Desperate Amy contacts Desi and moves into his lake house."),
        EventNode(id="EVT_NICK_DISCOVERS_CLUES", fabula_time=600, syuzhet_index=7,
                  event_type="revelation", actor_ids=["ENT_NICK"], target_ids=[],
                  description="Nick follows the anniversary treasure hunt and discovers the woodshed full of incriminating evidence."),
        EventNode(id="EVT_AFFAIR_EXPOSED", fabula_time=700, syuzhet_index=8,
                  event_type="revelation", actor_ids=[], target_ids=["ENT_NICK"],
                  description="Nick's affair with Andie is exposed publicly."),
        EventNode(id="EVT_NICK_TV_INTERVIEW", fabula_time=800, syuzhet_index=9,
                  event_type="choice", actor_ids=["ENT_NICK", "ENT_TANNER_BOLT"], target_ids=[],
                  description="Nick gives a calculated public apology interview to shift media perception."),
        EventNode(id="EVT_DIARY_FOUND", fabula_time=900, syuzhet_index=10,
                  event_type="revelation", actor_ids=["ENT_DETECTIVE_BONEY"], target_ids=["ENT_NICK"],
                  description="Police discover Amy's fabricated diary chronicling abuse."),
        EventNode(id="EVT_WOODSHED_DISCOVERED", fabula_time=1000, syuzhet_index=11,
                  event_type="revelation", actor_ids=["ENT_DETECTIVE_BONEY"], target_ids=["ENT_NICK"],
                  description="Police discover the woodshed with violent materials and bloody puppet handle."),
        EventNode(id="EVT_NICK_ARRESTED", fabula_time=1100, syuzhet_index=12,
                  event_type="outcome", actor_ids=["ENT_DETECTIVE_BONEY"], target_ids=["ENT_NICK"],
                  description="Nick is arrested for Amy's murder."),
        EventNode(id="EVT_AMY_KILLS_DESI", fabula_time=1200, syuzhet_index=13,
                  event_type="choice", actor_ids=["ENT_AMY"], target_ids=["ENT_DESI"],
                  description="Amy seduces and murders Desi, staging it as self-defense after captivity."),
        EventNode(id="EVT_AMY_RETURNS", fabula_time=1300, syuzhet_index=14,
                  event_type="outcome", actor_ids=["ENT_AMY"], target_ids=["ENT_NICK"],
                  description="Amy returns to North Carthage with a fabricated kidnapping story."),
        EventNode(id="EVT_FORCED_RECONCILIATION", fabula_time=1400, syuzhet_index=15,
                  event_type="outcome", actor_ids=["ENT_AMY", "ENT_NICK"], target_ids=[],
                  description="Nick is forced back into married life with Amy, unable to prove her deception."),
        EventNode(id="EVT_AMY_INSEMINATES", fabula_time=1500, syuzhet_index=16,
                  event_type="choice", actor_ids=["ENT_AMY"], target_ids=["ENT_NICK"],
                  description="Amy uses preserved semen to inseminate herself, trapping Nick permanently."),
    ],

    causal_topology=[
        # chain_reaction
        CausalEdge(source_id="EVT_MARRIAGE_DETERIORATES", target_id="EVT_AMY_DISAPPEARS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=50),
        CausalEdge(source_id="EVT_AMY_DISAPPEARS", target_id="EVT_INVESTIGATION_BEGINS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="EVT_INVESTIGATION_BEGINS", target_id="EVT_PREGNANCY_REVEALED",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=200),
        CausalEdge(source_id="EVT_AMY_ROBBED", target_id="EVT_AMY_SEEKS_DESI",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=400),
        CausalEdge(source_id="EVT_AFFAIR_EXPOSED", target_id="EVT_NICK_TV_INTERVIEW",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=700),
        CausalEdge(source_id="EVT_DIARY_FOUND", target_id="EVT_NICK_ARRESTED",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900),
        CausalEdge(source_id="EVT_WOODSHED_DISCOVERED", target_id="EVT_NICK_ARRESTED",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000),
        CausalEdge(source_id="EVT_NICK_TV_INTERVIEW", target_id="EVT_AMY_KILLS_DESI",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=800),
        CausalEdge(source_id="EVT_AMY_KILLS_DESI", target_id="EVT_AMY_RETURNS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1200),
        CausalEdge(source_id="EVT_AMY_RETURNS", target_id="EVT_FORCED_RECONCILIATION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1300),
        CausalEdge(source_id="EVT_FORCED_RECONCILIATION", target_id="EVT_AMY_INSEMINATES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1400),

        # mutation
        CausalEdge(source_id="EVT_AMY_DISAPPEARS", target_id="ENT_NICK",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100,
                   trait_target="fear", trait_delta=0.4),
        CausalEdge(source_id="EVT_NICK_DISCOVERS_CLUES", target_id="ENT_NICK",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600,
                   trait_target="resolve", trait_delta=0.3),
        CausalEdge(source_id="EVT_AMY_ROBBED", target_id="ENT_AMY",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=400,
                   trait_target="desperation", trait_delta=0.5),
        CausalEdge(source_id="EVT_NICK_TV_INTERVIEW", target_id="ENT_AMY",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=800,
                   trait_target="control", trait_delta=0.1),
        CausalEdge(source_id="EVT_AMY_KILLS_DESI", target_id="ENT_AMY",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1200,
                   trait_target="control", trait_delta=0.15),
        CausalEdge(source_id="EVT_NICK_ARRESTED", target_id="ENT_NICK",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1100,
                   trait_target="fear", trait_delta=0.3),
        CausalEdge(source_id="EVT_AMY_INSEMINATES", target_id="ENT_NICK",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1500,
                   trait_target="passivity", trait_delta=0.3),

        # mutation_social
        CausalEdge(source_id="EVT_MARRIAGE_DETERIORATES", target_id="ENT_AMY",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=50,
                   trait_target="affinity", trait_delta=-0.8, rel_counterpart_id="ENT_NICK"),
        CausalEdge(source_id="EVT_AMY_RETURNS", target_id="ENT_NICK",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1300,
                   trait_target="fear", trait_delta=0.5, rel_counterpart_id="ENT_AMY"),
        CausalEdge(source_id="EVT_AMY_SEEKS_DESI", target_id="ENT_DESI",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=500,
                   trait_target="affinity", trait_delta=0.4, rel_counterpart_id="ENT_AMY"),
        CausalEdge(source_id="EVT_AMY_KILLS_DESI", target_id="ENT_AMY",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1200,
                   trait_target="power_dynamic", trait_delta=0.5, rel_counterpart_id="ENT_NICK"),

        # affordance_gate
        CausalEdge(source_id="OBJ_DIARY", target_id="EVT_NICK_ARRESTED",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900),
        CausalEdge(source_id="ENT_AMY", target_id="EVT_AMY_DISAPPEARS",
                   causality_type="affordance_gate", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=100),
        CausalEdge(source_id="ENT_TANNER_BOLT", target_id="EVT_NICK_TV_INTERVIEW",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=800),

        # ambient_propagation
        CausalEdge(source_id="LOC_DESI_LAKE_HOUSE", target_id="ENT_AMY",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=500),
        CausalEdge(source_id="ENT_AMY", target_id="ENT_NICK",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=1400),
    ],

    spatial_topology=[
        SpatialEdge(source_id="LOC_DUNNE_HOUSE", target_id="LOC_BAR"),
        SpatialEdge(source_id="LOC_DUNNE_HOUSE", target_id="LOC_POLICE_STATION"),
        SpatialEdge(source_id="LOC_DUNNE_HOUSE", target_id="LOC_WOODSHED"),
        SpatialEdge(source_id="LOC_POLICE_STATION", target_id="LOC_TV_STUDIO"),
        SpatialEdge(source_id="LOC_MOTEL", target_id="LOC_DESI_LAKE_HOUSE"),
        SpatialEdge(source_id="LOC_DESI_LAKE_HOUSE", target_id="LOC_DUNNE_HOUSE"),
    ],

    information_topology=[
        InformationEdge(source_id="ENT_AMY", target_ids=["ENT_NICK"],
                        medium="treasure_hunt_clues", established_at_fabula=100),
        InformationEdge(source_id="ENT_NICK", target_ids=["ENT_TANNER_BOLT"],
                        medium="consultation", established_at_fabula=600),
        InformationEdge(source_id="ENT_NICK", target_ids=["ENT_MARGO"],
                        medium="conversation", established_at_fabula=100),
        InformationEdge(source_id="ENT_AMY", target_ids=["ENT_DESI"],
                        medium="telephone", established_at_fabula=500, terminated_at_fabula=1200),
    ],

    social_topology=[
        RelationshipEdge(source_entity_id="ENT_NICK", target_entity_id="ENT_AMY", affinity=-0.3, fear=0.2, power_dynamic=-0.4, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_AMY", target_entity_id="ENT_NICK", affinity=-0.6, fear=0.0, power_dynamic=0.5, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_NICK", target_entity_id="ENT_MARGO", affinity=0.9, fear=0.0, power_dynamic=0.0, inertia=0.6),
        RelationshipEdge(source_entity_id="ENT_NICK", target_entity_id="ENT_ANDIE", affinity=0.5, fear=0.1, power_dynamic=0.3, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_AMY", target_entity_id="ENT_DESI", affinity=-0.2, fear=0.1, power_dynamic=0.4, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_DESI", target_entity_id="ENT_AMY", affinity=0.8, fear=0.0, power_dynamic=-0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_DETECTIVE_BONEY", target_entity_id="ENT_NICK", affinity=-0.3, fear=0.0, power_dynamic=0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_NICK", target_entity_id="ENT_TANNER_BOLT", affinity=0.4, fear=0.0, power_dynamic=-0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_MARGO", target_entity_id="ENT_AMY", affinity=-0.5, fear=0.1, power_dynamic=-0.2, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_AMY", target_entity_id="ENT_DETECTIVE_BONEY", affinity=-0.2, fear=0.3, power_dynamic=-0.2, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_AMY", target_entity_id="ENT_ANDIE", affinity=-0.9, fear=0.0, power_dynamic=0.3, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_ANDIE", target_entity_id="ENT_NICK", affinity=0.6, fear=0.0, power_dynamic=-0.3, inertia=0.2),
    ],
)
