"""Great Expectations — high-fidelity WorldStateV1 test fixture."""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_KENT_MARSHES": Location(
            name="Kent Marshes", description="Bleak coastal marshland with the churchyard where Pip meets the convict.",
            ambient_state={"desolation": AmbientVector(value=0.8, volatility=0.3), "danger": AmbientVector(value=0.6, volatility=0.5)},
        ),
        "LOC_FORGE": Location(
            name="Joe\'s Forge", description="The warm blacksmith shop where Pip apprentices.",
            ambient_state={"warmth": AmbientVector(value=0.8, volatility=0.2), "simplicity": AmbientVector(value=0.9, volatility=0.1)},
        ),
        "LOC_SATIS_HOUSE": Location(
            name="Satis House", description="Miss Havisham\'s decaying mansion frozen in time.",
            ambient_state={"decay": AmbientVector(value=0.9, volatility=0.1), "manipulation": AmbientVector(value=0.8, volatility=0.2)},
        ),
        "LOC_LONDON": Location(
            name="London", description="The city where Pip lives as a gentleman, far from its imagined glamour.",
            ambient_state={"sophistication": AmbientVector(value=0.6, volatility=0.3), "corruption": AmbientVector(value=0.5, volatility=0.4)},
        ),
        "LOC_BARNARDS_INN": Location(
            name="Barnard\'s Inn", description="Pip and Herbert\'s cramped London lodgings.",
            ambient_state={"modesty": AmbientVector(value=0.6, volatility=0.2)},
        ),
        "LOC_RIVER_THAMES": Location(
            name="River Thames", description="The river where Magwitch\'s escape attempt fails.",
            ambient_state={"danger": AmbientVector(value=0.7, volatility=0.5)},
        ),
        "LOC_CAIRO": Location(
            name="Cairo", description="Where Pip eventually works with Herbert at Clarriker\'s.",
            ambient_state={"renewal": AmbientVector(value=0.6, volatility=0.3)},
        ),
    },
    objects={
        "OBJ_FILE": NarrativeObject(
            id="OBJ_FILE", name="Joe\'s File",
            location_id="LOC_FORGE", owner_id="ENT_JOE",
            properties={"stolen_by": "Pip"},
            affordances=[Affordance(action="free_shackles", target_type="Entity")],
        ),
        "OBJ_LEG_IRON": NarrativeObject(
            id="OBJ_LEG_IRON", name="Convict\'s Leg Iron",
            location_id=None, owner_id=None,
            properties={"state": "used_as_weapon"},
            affordances=[Affordance(action="bludgeon", target_type="Entity")],
        ),
        "OBJ_WEDDING_DRESS": NarrativeObject(
            id="OBJ_WEDDING_DRESS", name="Miss Havisham\'s Wedding Dress",
            location_id="LOC_SATIS_HOUSE", owner_id="ENT_MISS_HAVISHAM",
            properties={"state": "decaying", "symbolism": "frozen_grief"},
            affordances=[],
        ),
        "OBJ_MONEY": NarrativeObject(
            id="OBJ_MONEY", name="Magwitch\'s Fortune",
            location_id=None, owner_id="ENT_MAGWITCH",
            properties={"annual_income": "500_pounds"},
            affordances=[Affordance(action="fund_gentleman", target_type="Entity")],
        ),
    },
    entities={
        "ENT_PIP": Entity(
            id="ENT_PIP", name="Pip (Philip Pirrip)",
            location_id="LOC_KENT_MARSHES", status="healthy",
            traits={
                "ambition": TraitVector(value=0.5, inertia=0.3),
                "shame": TraitVector(value=0.3, inertia=0.2),
                "gratitude": TraitVector(value=0.7, inertia=0.4),
                "snobbery": TraitVector(value=0.1, inertia=0.2),
                "compassion": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_MISS_HAVISHAM", perceived_state="Miss Havisham is my secret benefactress (FALSE)", confidence=0.9, inertia=0.7),
                Belief(target_id="ENT_ESTELLA", perceived_state="Estella is destined for me if I become a gentleman", confidence=0.7, inertia=0.5),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=400, triggered_by="EVT_PIP_MEETS_ESTELLA",
                    traits={"ambition": TraitVector(value=0.7, inertia=0.3), "shame": TraitVector(value=0.6, inertia=0.2)}),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_GREAT_EXPECTATIONS",
                    traits={"snobbery": TraitVector(value=0.5, inertia=0.2)},
                    new_location_id="LOC_LONDON"),
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_MAGWITCH_REVEALED",
                    traits={"shame": TraitVector(value=0.8, inertia=0.2), "snobbery": TraitVector(value=0.2, inertia=0.2)}),
                EntityStateSnapshot(fabula_time=1800, triggered_by="EVT_JOE_NURSES_PIP",
                    traits={"compassion": TraitVector(value=0.9, inertia=0.4), "shame": TraitVector(value=0.4, inertia=0.3)}),
            ],
        ),
        "ENT_JOE": Entity(
            id="ENT_JOE", name="Joe Gargery",
            location_id="LOC_FORGE", status="healthy",
            traits={
                "kindness": TraitVector(value=0.95, inertia=0.8),
                "humility": TraitVector(value=0.9, inertia=0.7),
                "loyalty": TraitVector(value=0.9, inertia=0.7),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip is like a son to me no matter how he acts", confidence=0.95, inertia=0.9),
            ],
        ),
        "ENT_MISS_HAVISHAM": Entity(
            id="ENT_MISS_HAVISHAM", name="Miss Havisham",
            location_id="LOC_SATIS_HOUSE", status="healthy",
            traits={
                "bitterness": TraitVector(value=0.9, inertia=0.7),
                "manipulation": TraitVector(value=0.8, inertia=0.6),
                "remorse": TraitVector(value=0.1, inertia=0.2),
            },
            beliefs=[
                Belief(target_id="ENT_ESTELLA", perceived_state="Estella is my weapon of revenge against men", confidence=0.8, inertia=0.6),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1500, triggered_by="EVT_HAVISHAM_REMORSE",
                    traits={"remorse": TraitVector(value=0.8, inertia=0.2), "manipulation": TraitVector(value=0.3, inertia=0.6)}),
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_HAVISHAM_FIRE",
                    new_status="dead"),
            ],
        ),
        "ENT_ESTELLA": Entity(
            id="ENT_ESTELLA", name="Estella",
            location_id="LOC_SATIS_HOUSE", status="healthy",
            traits={
                "coldness": TraitVector(value=0.8, inertia=0.6),
                "beauty": TraitVector(value=0.9, inertia=0.8),
                "obedience": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip is beneath me — a common labouring boy", confidence=0.7, inertia=0.5),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=2000, triggered_by="EVT_PIP_MEETS_ESTELLA_AGAIN",
                    traits={"coldness": TraitVector(value=0.3, inertia=0.6)}),
            ],
        ),
        "ENT_MAGWITCH": Entity(
            id="ENT_MAGWITCH", name="Abel Magwitch",
            location_id="LOC_KENT_MARSHES", status="healthy",
            traits={
                "gratitude": TraitVector(value=0.9, inertia=0.6),
                "determination": TraitVector(value=0.8, inertia=0.5),
                "roughness": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip showed me kindness — I will make him a gentleman", confidence=0.95, inertia=0.8),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1700, triggered_by="EVT_MAGWITCH_CAPTURED",
                    new_status="imprisoned"),
                EntityStateSnapshot(fabula_time=1750, triggered_by="EVT_MAGWITCH_DIES",
                    new_status="dead"),
            ],
        ),
        "ENT_HERBERT": Entity(
            id="ENT_HERBERT", name="Herbert Pocket",
            location_id="LOC_BARNARDS_INN", status="healthy",
            traits={
                "cheerfulness": TraitVector(value=0.8, inertia=0.6),
                "loyalty": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[],
        ),
        "ENT_JAGGERS": Entity(
            id="ENT_JAGGERS", name="Mr Jaggers",
            location_id="LOC_LONDON", status="healthy",
            traits={
                "power": TraitVector(value=0.9, inertia=0.7),
                "secrecy": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[],
        ),
        "ENT_COMPEYSON": Entity(
            id="ENT_COMPEYSON", name="Compeyson",
            location_id="LOC_LONDON", status="healthy",
            traits={
                "cunning": TraitVector(value=0.9, inertia=0.6),
                "malice": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1700, triggered_by="EVT_MAGWITCH_CAPTURED",
                    new_status="dead"),
            ],
        ),
        "ENT_ORLICK": Entity(
            id="ENT_ORLICK", name="Dolge Orlick",
            location_id="LOC_FORGE", status="healthy",
            traits={
                "malice": TraitVector(value=0.8, inertia=0.5),
                "jealousy": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[],
        ),
        "ENT_BIDDY": Entity(
            id="ENT_BIDDY", name="Biddy",
            location_id="LOC_FORGE", status="healthy",
            traits={
                "intelligence": TraitVector(value=0.7, inertia=0.5),
                "kindness": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[],
        ),
    },
    events=[
        EventNode(id="EVT_PIP_MEETS_CONVICT", fabula_time=100, syuzhet_index=1,
                  event_type="revelation", actor_ids=["ENT_MAGWITCH"], target_ids=["ENT_PIP"],
                  description="Pip encounters the escaped convict Magwitch in the churchyard and is threatened into bringing food and a file."),
        EventNode(id="EVT_PIP_HELPS_CONVICT", fabula_time=200, syuzhet_index=2,
                  event_type="choice", actor_ids=["ENT_PIP"], target_ids=["ENT_MAGWITCH"],
                  description="Pip steals food and a file to help the convict."),
        EventNode(id="EVT_CONVICT_RECAPTURED", fabula_time=300, syuzhet_index=3,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MAGWITCH"],
                  description="The convict is recaptured but confesses to stealing the food, protecting Pip."),
        EventNode(id="EVT_PIP_MEETS_ESTELLA", fabula_time=400, syuzhet_index=4,
                  event_type="revelation", actor_ids=["ENT_PIP"], target_ids=["ENT_ESTELLA"],
                  description="Pip visits Satis House and falls in love with the beautiful but contemptuous Estella."),
        EventNode(id="EVT_APPRENTICESHIP", fabula_time=500, syuzhet_index=5,
                  event_type="outcome", actor_ids=["ENT_PIP"], target_ids=["ENT_JOE"],
                  description="Pip becomes Joe\'s apprentice blacksmith with money from Miss Havisham."),
        EventNode(id="EVT_MRS_JOE_ATTACKED", fabula_time=600, syuzhet_index=6,
                  event_type="outcome", actor_ids=["ENT_ORLICK"], target_ids=[],
                  description="Pip\'s sister is brutally attacked with a leg iron, leaving her an invalid."),
        EventNode(id="EVT_GREAT_EXPECTATIONS", fabula_time=700, syuzhet_index=7,
                  event_type="revelation", actor_ids=["ENT_JAGGERS"], target_ids=["ENT_PIP"],
                  description="Jaggers informs Pip of an anonymous benefactor funding his life as a London gentleman."),
        EventNode(id="EVT_PIP_ARRIVES_LONDON", fabula_time=800, syuzhet_index=8,
                  event_type="outcome", actor_ids=["ENT_PIP"], target_ids=[],
                  description="Pip arrives in London and moves into Barnard\'s Inn with Herbert Pocket."),
        EventNode(id="EVT_JOE_VISITS_PIP", fabula_time=900, syuzhet_index=9,
                  event_type="outcome", actor_ids=["ENT_JOE"], target_ids=["ENT_PIP"],
                  description="Joe visits Pip in London; Pip is ashamed to be seen with him."),
        EventNode(id="EVT_ESTELLA_IN_SOCIETY", fabula_time=1000, syuzhet_index=10,
                  event_type="outcome", actor_ids=["ENT_ESTELLA"], target_ids=[],
                  description="Estella is introduced into London society; Pip pursues her devotedly."),
        EventNode(id="EVT_MAGWITCH_REVEALED", fabula_time=1200, syuzhet_index=11,
                  event_type="revelation", actor_ids=["ENT_MAGWITCH"], target_ids=["ENT_PIP"],
                  description="Magwitch returns to reveal himself as Pip\'s true benefactor, shattering Pip\'s assumptions."),
        EventNode(id="EVT_ESTELLA_MARRIES_DRUMMLE", fabula_time=1400, syuzhet_index=12,
                  event_type="outcome", actor_ids=["ENT_ESTELLA"], target_ids=["ENT_PIP"],
                  description="Estella coldly tells Pip she plans to marry Drummle, breaking his heart."),
        EventNode(id="EVT_HAVISHAM_REMORSE", fabula_time=1500, syuzhet_index=13,
                  event_type="revelation", actor_ids=["ENT_MISS_HAVISHAM"], target_ids=["ENT_PIP"],
                  description="A remorseful Miss Havisham begs Pip\'s forgiveness for raising Estella to be heartless."),
        EventNode(id="EVT_HAVISHAM_FIRE", fabula_time=1600, syuzhet_index=14,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MISS_HAVISHAM"],
                  description="Miss Havisham\'s wedding dress catches fire; she dies despite Pip\'s rescue attempt."),
        EventNode(id="EVT_ORLICK_TRAPS_PIP", fabula_time=1650, syuzhet_index=15,
                  event_type="outcome", actor_ids=["ENT_ORLICK"], target_ids=["ENT_PIP"],
                  description="Orlick lures Pip to a sluice-house and attempts to murder him; Herbert rescues Pip."),
        EventNode(id="EVT_MAGWITCH_CAPTURED", fabula_time=1700, syuzhet_index=16,
                  event_type="outcome", actor_ids=["ENT_COMPEYSON"], target_ids=["ENT_MAGWITCH"],
                  description="During the escape attempt on the Thames, Compeyson identifies Magwitch; they fight. Compeyson drowns; Magwitch is captured."),
        EventNode(id="EVT_MAGWITCH_DIES", fabula_time=1750, syuzhet_index=17,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MAGWITCH"],
                  description="Magwitch dies in prison; Pip tells him Estella is alive."),
        EventNode(id="EVT_JOE_NURSES_PIP", fabula_time=1800, syuzhet_index=18,
                  event_type="outcome", actor_ids=["ENT_JOE"], target_ids=["ENT_PIP"],
                  description="Joe nurses the ill Pip back to health and pays his debts."),
        EventNode(id="EVT_PIP_RETURNS", fabula_time=1900, syuzhet_index=19,
                  event_type="choice", actor_ids=["ENT_PIP"], target_ids=[],
                  description="Pip returns to propose to Biddy but finds she has married Joe. He leaves for Cairo."),
        EventNode(id="EVT_PIP_MEETS_ESTELLA_AGAIN", fabula_time=2000, syuzhet_index=20,
                  event_type="outcome", actor_ids=["ENT_PIP"], target_ids=["ENT_ESTELLA"],
                  description="After eleven years, Pip meets the widowed Estella in the ruins of Satis House; her suffering has opened her heart."),
    ],
    causal_topology=[
        # chain_reaction
        CausalEdge(source_id="EVT_PIP_MEETS_CONVICT", target_id="EVT_PIP_HELPS_CONVICT",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=100),
        CausalEdge(source_id="EVT_PIP_HELPS_CONVICT", target_id="EVT_GREAT_EXPECTATIONS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200, propagation_delay=500),
        CausalEdge(source_id="EVT_PIP_MEETS_ESTELLA", target_id="EVT_APPRENTICESHIP",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=400),
        CausalEdge(source_id="EVT_GREAT_EXPECTATIONS", target_id="EVT_PIP_ARRIVES_LONDON",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700),
        CausalEdge(source_id="EVT_PIP_ARRIVES_LONDON", target_id="EVT_JOE_VISITS_PIP",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=800),
        CausalEdge(source_id="EVT_MAGWITCH_REVEALED", target_id="EVT_ESTELLA_MARRIES_DRUMMLE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1200),
        CausalEdge(source_id="EVT_MAGWITCH_REVEALED", target_id="EVT_HAVISHAM_REMORSE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1200, propagation_delay=300),
        CausalEdge(source_id="EVT_HAVISHAM_REMORSE", target_id="EVT_HAVISHAM_FIRE",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1500),
        CausalEdge(source_id="EVT_MAGWITCH_CAPTURED", target_id="EVT_MAGWITCH_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1700),
        CausalEdge(source_id="EVT_MAGWITCH_DIES", target_id="EVT_JOE_NURSES_PIP",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1750),
        CausalEdge(source_id="EVT_JOE_NURSES_PIP", target_id="EVT_PIP_RETURNS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1800),
        # mutation
        CausalEdge(source_id="EVT_PIP_MEETS_ESTELLA", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=400,
                   trait_target="ambition", trait_delta=0.2),
        CausalEdge(source_id="EVT_PIP_MEETS_ESTELLA", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=400,
                   trait_target="shame", trait_delta=0.3),
        CausalEdge(source_id="EVT_GREAT_EXPECTATIONS", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700,
                   trait_target="snobbery", trait_delta=0.4),
        CausalEdge(source_id="EVT_MAGWITCH_REVEALED", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1200,
                   trait_target="shame", trait_delta=0.4),
        CausalEdge(source_id="EVT_MAGWITCH_REVEALED", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1200,
                   trait_target="snobbery", trait_delta=-0.3),
        CausalEdge(source_id="EVT_JOE_NURSES_PIP", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1800,
                   trait_target="compassion", trait_delta=0.3),
        CausalEdge(source_id="EVT_HAVISHAM_REMORSE", target_id="ENT_MISS_HAVISHAM",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1500,
                   trait_target="remorse", trait_delta=0.7),
        # mutation_social
        CausalEdge(source_id="EVT_JOE_VISITS_PIP", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=900,
                   trait_target="affinity", trait_delta=-0.3, rel_counterpart_id="ENT_JOE"),
        CausalEdge(source_id="EVT_MAGWITCH_REVEALED", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1200,
                   trait_target="affinity", trait_delta=0.4, rel_counterpart_id="ENT_MAGWITCH"),
        CausalEdge(source_id="EVT_ESTELLA_MARRIES_DRUMMLE", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1400,
                   trait_target="affinity", trait_delta=-0.3, rel_counterpart_id="ENT_ESTELLA"),
        CausalEdge(source_id="EVT_JOE_NURSES_PIP", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1800,
                   trait_target="affinity", trait_delta=0.5, rel_counterpart_id="ENT_JOE"),
        # affordance_gate
        CausalEdge(source_id="OBJ_FILE", target_id="EVT_PIP_HELPS_CONVICT",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200),
        CausalEdge(source_id="OBJ_MONEY", target_id="EVT_PIP_ARRIVES_LONDON",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=800),
        CausalEdge(source_id="OBJ_LEG_IRON", target_id="EVT_MRS_JOE_ATTACKED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=600),
        # ambient_propagation
        CausalEdge(source_id="LOC_SATIS_HOUSE", target_id="ENT_ESTELLA",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=400),
        CausalEdge(source_id="LOC_SATIS_HOUSE", target_id="ENT_PIP",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=400),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_KENT_MARSHES", target_id="LOC_FORGE"),
        SpatialEdge(source_id="LOC_FORGE", target_id="LOC_SATIS_HOUSE"),
        SpatialEdge(source_id="LOC_KENT_MARSHES", target_id="LOC_LONDON"),
        SpatialEdge(source_id="LOC_LONDON", target_id="LOC_BARNARDS_INN"),
        SpatialEdge(source_id="LOC_LONDON", target_id="LOC_RIVER_THAMES"),
        SpatialEdge(source_id="LOC_LONDON", target_id="LOC_CAIRO"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_JAGGERS", target_ids=["ENT_PIP"],
                        medium="legal_notice", established_at_fabula=700),
        InformationEdge(source_id="ENT_MAGWITCH", target_ids=["ENT_PIP"],
                        medium="confession", is_encrypted=True, established_at_fabula=1200),
        InformationEdge(source_id="ENT_HERBERT", target_ids=["ENT_PIP"],
                        medium="private_conversation", established_at_fabula=800),
        InformationEdge(source_id="ENT_MISS_HAVISHAM", target_ids=["ENT_PIP"],
                        medium="deathbed_confession", established_at_fabula=1500),
        InformationEdge(source_id="ENT_ORLICK", target_ids=["ENT_PIP"],
                        medium="anonymous_letter", is_encrypted=True, established_at_fabula=1650),
    ],
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_PIP", target_entity_id="ENT_JOE",
                         affinity=0.6, fear=0.0, power_dynamic=0.1, inertia=0.5, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_JOE", target_entity_id="ENT_PIP",
                         affinity=0.9, fear=0.0, power_dynamic=-0.1, inertia=0.7, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_PIP", target_entity_id="ENT_ESTELLA",
                         affinity=0.9, fear=0.2, power_dynamic=-0.5, inertia=0.5, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_ESTELLA", target_entity_id="ENT_PIP",
                         affinity=-0.2, fear=0.0, power_dynamic=0.5, inertia=0.5, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_PIP", target_entity_id="ENT_MAGWITCH",
                         affinity=0.3, fear=0.3, power_dynamic=-0.3, inertia=0.3, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_MAGWITCH", target_entity_id="ENT_PIP",
                         affinity=0.9, fear=0.0, power_dynamic=0.2, inertia=0.6, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_MISS_HAVISHAM", target_entity_id="ENT_ESTELLA",
                         affinity=0.6, fear=0.0, power_dynamic=0.7, inertia=0.5, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_ESTELLA", target_entity_id="ENT_MISS_HAVISHAM",
                         affinity=0.3, fear=0.2, power_dynamic=-0.6, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_PIP", target_entity_id="ENT_HERBERT",
                         affinity=0.8, fear=0.0, power_dynamic=0.0, inertia=0.5, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_PIP", target_entity_id="ENT_MISS_HAVISHAM",
                         affinity=0.3, fear=0.3, power_dynamic=-0.5, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_MAGWITCH", target_entity_id="ENT_COMPEYSON",
                         affinity=-0.9, fear=0.3, power_dynamic=-0.3, inertia=0.4, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_ORLICK", target_entity_id="ENT_PIP",
                         affinity=-0.8, fear=0.0, power_dynamic=0.2, inertia=0.4, evidence_strength="moderate"),
    ],
)
