"""Great Gatsby — high-fidelity WorldStateV1 test fixture."""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_WEST_EGG": Location(
            name="West Egg", description="Nouveau-riche Long Island village where Gatsby and Nick live.",
            ambient_state={"opulence": AmbientVector(value=0.8, volatility=0.3), "artifice": AmbientVector(value=0.7, volatility=0.3)},
        ),
        "LOC_EAST_EGG": Location(
            name="East Egg", description="Old-money enclave across the bay; home of the Buchanans.",
            ambient_state={"privilege": AmbientVector(value=0.9, volatility=0.1), "complacency": AmbientVector(value=0.7, volatility=0.2)},
        ),
        "LOC_VALLEY_OF_ASHES": Location(
            name="Valley of Ashes", description="Industrial wasteland between the Eggs and New York.",
            ambient_state={"desolation": AmbientVector(value=0.9, volatility=0.1), "danger": AmbientVector(value=0.5, volatility=0.5)},
        ),
        "LOC_WILSON_GARAGE": Location(
            name="Wilson's Garage", description="George Wilson's auto-repair shop in the valley of ashes.",
            ambient_state={"despair": AmbientVector(value=0.7, volatility=0.4)},
        ),
        "LOC_GATSBY_MANSION": Location(
            name="Gatsby's Mansion", description="Lavish estate where Gatsby hosts extravagant parties.",
            ambient_state={"opulence": AmbientVector(value=0.95, volatility=0.2), "loneliness": AmbientVector(value=0.6, volatility=0.3)},
        ),
        "LOC_PLAZA_HOTEL": Location(
            name="Plaza Hotel Suite", description="Hotel room where the confrontation between Gatsby and Tom takes place.",
            ambient_state={"tension": AmbientVector(value=0.9, volatility=0.3)},
        ),
        "LOC_NEW_YORK_APARTMENT": Location(
            name="Tom's New York Apartment", description="Small apartment Tom rents for his affair with Myrtle.",
            ambient_state={"secrecy": AmbientVector(value=0.7, volatility=0.4)},
        ),
    },
    objects={
        "OBJ_GREEN_LIGHT": NarrativeObject(
            id="OBJ_GREEN_LIGHT", name="Green Light",
            location_id="LOC_EAST_EGG", owner_id=None,
            properties={"symbolism": "unattainable_dream"},
            affordances=[Affordance(action="inspire_longing", target_type="Entity")],
        ),
        "OBJ_YELLOW_CAR": NarrativeObject(
            id="OBJ_YELLOW_CAR", name="Gatsby's Yellow Car",
            location_id=None, owner_id="ENT_GATSBY",
            properties={"color": "yellow", "visibility": "conspicuous"},
            affordances=[Affordance(action="drive", target_type="Entity"), Affordance(action="kill", target_type="Entity")],
        ),
        "OBJ_GUN": NarrativeObject(
            id="OBJ_GUN", name="George Wilson's Gun",
            location_id="LOC_WILSON_GARAGE", owner_id="ENT_GEORGE",
            properties={},
            affordances=[Affordance(action="shoot", target_type="Entity")],
        ),
    },
    entities={
        "ENT_GATSBY": Entity(
            id="ENT_GATSBY", name="Jay Gatsby",
            location_id="LOC_GATSBY_MANSION", status="healthy",
            traits={
                "romanticism": TraitVector(value=0.95, inertia=0.7),
                "ambition": TraitVector(value=0.9, inertia=0.6),
                "self_deception": TraitVector(value=0.7, inertia=0.5),
                "generosity": TraitVector(value=0.7, inertia=0.4),
                "obsession": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_DAISY", perceived_state="Daisy still loves me and will leave Tom", confidence=0.8, inertia=0.7),
                Belief(target_id="OBJ_GREEN_LIGHT", perceived_state="The dream is within reach — I can repeat the past", confidence=0.9, inertia=0.8),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_REUNION_WITH_DAISY",
                    traits={"obsession": TraitVector(value=0.95, inertia=0.6)}),
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_PLAZA_CONFRONTATION",
                    traits={"self_deception": TraitVector(value=0.5, inertia=0.5), "romanticism": TraitVector(value=0.7, inertia=0.7)}),
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_GATSBY_SHOT",
                    status="dead"),
            ],
        ),
        "ENT_NICK": Entity(
            id="ENT_NICK", name="Nick Carraway",
            location_id="LOC_WEST_EGG", status="healthy",
            traits={
                "moral_compass": TraitVector(value=0.7, inertia=0.5),
                "reserve": TraitVector(value=0.6, inertia=0.5),
                "disillusionment": TraitVector(value=0.2, inertia=0.2),
            },
            beliefs=[
                Belief(target_id="ENT_GATSBY", perceived_state="Gatsby is worth more than the whole lot of them put together", confidence=0.7, inertia=0.5, established_at_fabula=1600),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_GATSBY_SHOT",
                    traits={"disillusionment": TraitVector(value=0.9, inertia=0.2)}),
            ],
        ),
        "ENT_DAISY": Entity(
            id="ENT_DAISY", name="Daisy Buchanan",
            location_id="LOC_EAST_EGG", status="healthy",
            traits={
                "charm": TraitVector(value=0.9, inertia=0.6),
                "carelessness": TraitVector(value=0.7, inertia=0.6),
                "indecision": TraitVector(value=0.7, inertia=0.5),
                "self_preservation": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_GATSBY", perceived_state="Gatsby represents an exciting escape from my hollow marriage", confidence=0.6, inertia=0.3),
                Belief(target_id="ENT_TOM", perceived_state="Tom provides security I cannot abandon", confidence=0.7, inertia=0.6),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_PLAZA_CONFRONTATION",
                    traits={"indecision": TraitVector(value=0.9, inertia=0.5)}),
            ],
        ),
        "ENT_TOM": Entity(
            id="ENT_TOM", name="Tom Buchanan",
            location_id="LOC_EAST_EGG", status="healthy",
            traits={
                "arrogance": TraitVector(value=0.9, inertia=0.7),
                "brutality": TraitVector(value=0.7, inertia=0.5),
                "entitlement": TraitVector(value=0.9, inertia=0.7),
                "possessiveness": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_GATSBY", perceived_state="Gatsby is a common criminal and bootlegger", confidence=0.8, inertia=0.6),
                Belief(target_id="ENT_DAISY", perceived_state="Daisy belongs to me and will never truly leave", confidence=0.9, inertia=0.7),
            ],
        ),
        "ENT_JORDAN": Entity(
            id="ENT_JORDAN", name="Jordan Baker",
            location_id="LOC_EAST_EGG", status="healthy",
            traits={
                "dishonesty": TraitVector(value=0.6, inertia=0.5),
                "independence": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[],
        ),
        "ENT_MYRTLE": Entity(
            id="ENT_MYRTLE", name="Myrtle Wilson",
            location_id="LOC_WILSON_GARAGE", status="healthy",
            traits={
                "desire_for_status": TraitVector(value=0.9, inertia=0.5),
                "recklessness": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_TOM", perceived_state="Tom will eventually leave Daisy for me", confidence=0.5, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1400, triggered_by="EVT_MYRTLE_KILLED",
                    status="dead"),
            ],
        ),
        "ENT_GEORGE": Entity(
            id="ENT_GEORGE", name="George Wilson",
            location_id="LOC_WILSON_GARAGE", status="healthy",
            traits={
                "despair": TraitVector(value=0.5, inertia=0.3),
                "meekness": TraitVector(value=0.7, inertia=0.5),
                "devotion": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_MYRTLE", perceived_state="Myrtle is faithful to me", confidence=0.4, inertia=0.3),
                Belief(target_id="ENT_GATSBY", perceived_state="Gatsby is Myrtle's lover and killer", confidence=0.9, inertia=0.5, established_at_fabula=1500),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1400, triggered_by="EVT_MYRTLE_KILLED",
                    traits={"despair": TraitVector(value=0.95, inertia=0.1), "meekness": TraitVector(value=0.2, inertia=0.5)}),
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_GATSBY_SHOT",
                    status="dead"),
            ],
        ),
    },
    events=[
        EventNode(id="EVT_NICK_ARRIVES", fabula_time=100, syuzhet_index=1,
                  event_type="outcome", actor_ids=["ENT_NICK"], target_ids=[],
                  description="Nick Carraway rents a bungalow in West Egg next to Gatsby\'s mansion."),
        EventNode(id="EVT_DINNER_AT_BUCHANANS", fabula_time=200, syuzhet_index=2,
                  event_type="revelation", actor_ids=["ENT_NICK"], target_ids=["ENT_DAISY", "ENT_TOM"],
                  description="Nick dines with the Buchanans; learns of Tom\'s affair and sees Gatsby staring at the green light."),
        EventNode(id="EVT_TOM_HITS_MYRTLE", fabula_time=300, syuzhet_index=3,
                  event_type="outcome", actor_ids=["ENT_TOM"], target_ids=["ENT_MYRTLE"],
                  description="Tom breaks Myrtle\'s nose at the New York apartment after she mentions Daisy."),
        EventNode(id="EVT_GATSBY_PARTY", fabula_time=400, syuzhet_index=4,
                  event_type="outcome", actor_ids=["ENT_GATSBY"], target_ids=["ENT_NICK"],
                  description="Nick attends Gatsby\'s lavish party and meets Gatsby for the first time."),
        EventNode(id="EVT_JORDAN_REVEALS_PAST", fabula_time=500, syuzhet_index=5,
                  event_type="revelation", actor_ids=["ENT_JORDAN"], target_ids=["ENT_NICK"],
                  description="Jordan reveals Gatsby and Daisy\'s romantic history and Gatsby\'s plan to reunite with Daisy."),
        EventNode(id="EVT_GATSBY_LUNCH", fabula_time=600, syuzhet_index=6,
                  event_type="outcome", actor_ids=["ENT_GATSBY"], target_ids=["ENT_NICK"],
                  description="Gatsby has lunch with Nick, boasting of war heroism and Oxford education."),
        EventNode(id="EVT_GATSBY_ASKS_NICK", fabula_time=700, syuzhet_index=7,
                  event_type="choice", actor_ids=["ENT_GATSBY"], target_ids=["ENT_NICK"],
                  description="Gatsby asks Nick to arrange a reunion with Daisy at Nick\'s bungalow."),
        EventNode(id="EVT_REUNION_WITH_DAISY", fabula_time=800, syuzhet_index=8,
                  event_type="outcome", actor_ids=["ENT_GATSBY"], target_ids=["ENT_DAISY"],
                  description="Gatsby and Daisy are reunited and begin an affair."),
        EventNode(id="EVT_TOM_DISCOVERS_AFFAIR", fabula_time=1100, syuzhet_index=9,
                  event_type="revelation", actor_ids=[], target_ids=["ENT_TOM"],
                  description="Tom notices Daisy\'s unguarded intimacy with Gatsby and realizes the affair."),
        EventNode(id="EVT_PLAZA_CONFRONTATION", fabula_time=1300, syuzhet_index=10,
                  event_type="choice", actor_ids=["ENT_TOM", "ENT_GATSBY"], target_ids=["ENT_DAISY"],
                  description="Tom and Gatsby confront each other at the Plaza. Gatsby demands Daisy say she never loved Tom. Tom exposes Gatsby\'s bootlegging. Daisy chooses Tom."),
        EventNode(id="EVT_MYRTLE_KILLED", fabula_time=1400, syuzhet_index=11,
                  event_type="outcome", actor_ids=["ENT_DAISY"], target_ids=["ENT_MYRTLE"],
                  description="Daisy, driving Gatsby\'s car, strikes and kills Myrtle Wilson."),
        EventNode(id="EVT_GATSBY_TAKES_BLAME", fabula_time=1450, syuzhet_index=12,
                  event_type="choice", actor_ids=["ENT_GATSBY"], target_ids=["ENT_DAISY"],
                  description="Gatsby tells Nick he will take the blame for Myrtle\'s death to protect Daisy."),
        EventNode(id="EVT_TOM_TELLS_GEORGE", fabula_time=1500, syuzhet_index=13,
                  event_type="choice", actor_ids=["ENT_TOM"], target_ids=["ENT_GEORGE"],
                  description="Tom tells George that Gatsby owns the yellow car that killed Myrtle."),
        EventNode(id="EVT_GATSBY_SHOT", fabula_time=1600, syuzhet_index=14,
                  event_type="outcome", actor_ids=["ENT_GEORGE"], target_ids=["ENT_GATSBY"],
                  description="George shoots Gatsby dead in his swimming pool, then kills himself."),
        EventNode(id="EVT_GATSBY_FUNERAL", fabula_time=1700, syuzhet_index=15,
                  event_type="outcome", actor_ids=["ENT_NICK"], target_ids=[],
                  description="Gatsby\'s funeral is sparsely attended; Daisy and Tom have left town without a word."),
        EventNode(id="EVT_NICK_LEAVES", fabula_time=1800, syuzhet_index=16,
                  event_type="choice", actor_ids=["ENT_NICK"], target_ids=[],
                  description="Nick, disillusioned, returns to the Midwest."),
    ],
    causal_topology=[
        # chain_reaction
        CausalEdge(source_id="EVT_DINNER_AT_BUCHANANS", target_id="EVT_JORDAN_REVEALS_PAST",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=200),
        CausalEdge(source_id="EVT_JORDAN_REVEALS_PAST", target_id="EVT_GATSBY_ASKS_NICK",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500),
        CausalEdge(source_id="EVT_GATSBY_ASKS_NICK", target_id="EVT_REUNION_WITH_DAISY",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700),
        CausalEdge(source_id="EVT_REUNION_WITH_DAISY", target_id="EVT_TOM_DISCOVERS_AFFAIR",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=800, propagation_delay=300),
        CausalEdge(source_id="EVT_TOM_DISCOVERS_AFFAIR", target_id="EVT_PLAZA_CONFRONTATION",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1100),
        CausalEdge(source_id="EVT_PLAZA_CONFRONTATION", target_id="EVT_MYRTLE_KILLED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1300),
        CausalEdge(source_id="EVT_MYRTLE_KILLED", target_id="EVT_GATSBY_TAKES_BLAME",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1400),
        CausalEdge(source_id="EVT_TOM_TELLS_GEORGE", target_id="EVT_GATSBY_SHOT",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1500),
        CausalEdge(source_id="EVT_GATSBY_SHOT", target_id="EVT_GATSBY_FUNERAL",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1600),
        CausalEdge(source_id="EVT_GATSBY_FUNERAL", target_id="EVT_NICK_LEAVES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1700),
        # mutation
        CausalEdge(source_id="EVT_REUNION_WITH_DAISY", target_id="ENT_GATSBY",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=800,
                   trait_target="obsession", trait_delta=0.15),
        CausalEdge(source_id="EVT_PLAZA_CONFRONTATION", target_id="ENT_GATSBY",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1300,
                   trait_target="self_deception", trait_delta=-0.2),
        CausalEdge(source_id="EVT_PLAZA_CONFRONTATION", target_id="ENT_DAISY",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=1300,
                   trait_target="indecision", trait_delta=0.2),
        CausalEdge(source_id="EVT_MYRTLE_KILLED", target_id="ENT_GEORGE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1400,
                   trait_target="despair", trait_delta=0.45),
        CausalEdge(source_id="EVT_GATSBY_SHOT", target_id="ENT_NICK",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1600,
                   trait_target="disillusionment", trait_delta=0.7),
        CausalEdge(source_id="EVT_TOM_HITS_MYRTLE", target_id="ENT_MYRTLE",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=6.0, fabula_time=300,
                   trait_target="desire_for_status", trait_delta=-0.1),
        # mutation_social
        CausalEdge(source_id="EVT_REUNION_WITH_DAISY", target_id="ENT_GATSBY",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=800,
                   trait_target="affinity", trait_delta=0.3, rel_counterpart_id="ENT_DAISY"),
        CausalEdge(source_id="EVT_PLAZA_CONFRONTATION", target_id="ENT_DAISY",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1300,
                   trait_target="affinity", trait_delta=-0.4, rel_counterpart_id="ENT_GATSBY"),
        CausalEdge(source_id="EVT_TOM_TELLS_GEORGE", target_id="ENT_GEORGE",
                   causality_type="mutation_social", mechanism="informational", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1500,
                   trait_target="affinity", trait_delta=-0.9, rel_counterpart_id="ENT_GATSBY"),
        CausalEdge(source_id="EVT_GATSBY_SHOT", target_id="ENT_NICK",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1600,
                   trait_target="affinity", trait_delta=-0.6, rel_counterpart_id="ENT_TOM"),
        # affordance_gate
        CausalEdge(source_id="OBJ_YELLOW_CAR", target_id="EVT_MYRTLE_KILLED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1400),
        CausalEdge(source_id="OBJ_GUN", target_id="EVT_GATSBY_SHOT",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1600),
        CausalEdge(source_id="OBJ_GREEN_LIGHT", target_id="EVT_GATSBY_ASKS_NICK",
                   causality_type="affordance_gate", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=700),
        # ambient_propagation
        CausalEdge(source_id="LOC_VALLEY_OF_ASHES", target_id="ENT_GEORGE",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=100),
        CausalEdge(source_id="LOC_GATSBY_MANSION", target_id="ENT_GATSBY",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=400),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_WEST_EGG", target_id="LOC_EAST_EGG"),
        SpatialEdge(source_id="LOC_WEST_EGG", target_id="LOC_VALLEY_OF_ASHES"),
        SpatialEdge(source_id="LOC_VALLEY_OF_ASHES", target_id="LOC_NEW_YORK_APARTMENT"),
        SpatialEdge(source_id="LOC_VALLEY_OF_ASHES", target_id="LOC_WILSON_GARAGE"),
        SpatialEdge(source_id="LOC_WEST_EGG", target_id="LOC_GATSBY_MANSION"),
        SpatialEdge(source_id="LOC_EAST_EGG", target_id="LOC_PLAZA_HOTEL"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_JORDAN", target_ids=["ENT_NICK"],
                        medium="private_conversation", established_at_fabula=500),
        InformationEdge(source_id="ENT_GATSBY", target_ids=["ENT_NICK"],
                        medium="self_mythologising", established_at_fabula=600),
        InformationEdge(source_id="ENT_TOM", target_ids=["ENT_GEORGE"],
                        medium="accusation", established_at_fabula=1500),
        InformationEdge(source_id="ENT_GATSBY", target_ids=["ENT_NICK"],
                        medium="whispered_confession", is_encrypted=True, established_at_fabula=1450),
        InformationEdge(source_id="ENT_TOM", target_ids=["ENT_DAISY", "ENT_NICK", "ENT_JORDAN"],
                        medium="public_revelation", established_at_fabula=1300),
    ],
    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_JAZZ_AGE_EXCESS": GlobalTrait(
            id="WORLD_JAZZ_AGE_EXCESS",
            name="Jazz Age Excess",
            description="The Roaring Twenties culture of conspicuous wealth, bootlegging, and decadent parties that masks spiritual emptiness.",
            category="social_structure",
            magnitude=TraitVector(value=0.85, inertia=0.6),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=1500, triggered_by="EVT_GATSBY_SHOT",
                    magnitude=TraitVector(value=0.4, inertia=0.3),
                    description="Gatsby's death exposes the hollowness behind the glamour — the dream collapses."),
            ],
        ),
        "WORLD_CLASS_BARRIER": GlobalTrait(
            id="WORLD_CLASS_BARRIER",
            name="Old Money vs New Money",
            description="The invisible but impenetrable barrier between established East Egg aristocracy and self-made West Egg wealth. No amount of money can buy social legitimacy.",
            category="social_structure",
            magnitude=TraitVector(value=0.8, inertia=0.8),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=1300, triggered_by="EVT_PLAZA_CONFRONTATION",
                    magnitude=TraitVector(value=0.95, inertia=0.9),
                    description="Tom brutally exposes Gatsby's origins, proving class boundaries cannot be crossed."),
            ],
        ),
    },
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_DAISY", target_entity_id="ENT_GATSBY",
                         affinity=0.5, fear=0.15, power_dynamic=0.2, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_TOM", target_entity_id="ENT_DAISY",
                         affinity=0.5, fear=0.0, power_dynamic=0.5, inertia=0.6, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_DAISY", target_entity_id="ENT_TOM",
                         affinity=0.4, fear=0.3, power_dynamic=-0.4, inertia=0.5, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_TOM", target_entity_id="ENT_GATSBY",
                         affinity=-0.8, fear=0.2, power_dynamic=0.3, inertia=0.4, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_GATSBY", target_entity_id="ENT_TOM",
                         affinity=-0.7, fear=0.1, power_dynamic=-0.2, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_NICK", target_entity_id="ENT_GATSBY",
                         affinity=0.6, fear=0.05, power_dynamic=-0.2, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_GATSBY", target_entity_id="ENT_NICK",
                         affinity=0.5, fear=0.0, power_dynamic=0.1, inertia=0.3, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_TOM", target_entity_id="ENT_MYRTLE",
                         affinity=0.4, fear=0.0, power_dynamic=0.6, inertia=0.3, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_MYRTLE", target_entity_id="ENT_TOM",
                         affinity=0.6, fear=0.2, power_dynamic=-0.5, inertia=0.3, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_GEORGE", target_entity_id="ENT_MYRTLE",
                         affinity=0.8, fear=0.1, power_dynamic=-0.3, inertia=0.5, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_GEORGE", target_entity_id="ENT_GATSBY",
                         affinity=-0.9, fear=0.0, power_dynamic=-0.1, inertia=0.2, evidence_strength="weak",
                         last_updated_fabula=1500),
        RelationshipEdge(source_entity_id="ENT_NICK", target_entity_id="ENT_TOM",
                         affinity=-0.3, fear=0.1, power_dynamic=-0.3, inertia=0.3, evidence_strength="moderate"),
    ],
)
