"""Macbeth — high-fidelity WorldStateV1 test fixture.

Quality checklist (all five causality modalities, varied force/evidence,
trait_target/trait_delta, state_timeline, rich beliefs, info edges).
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait,
)

world_state = WorldStateV1(
    # ── LOCATIONS ──────────────────────────────────────────────────────
    locations={
        "LOC_BATTLEFIELD": Location(
            name="Battlefield", description="Blood-soaked field near Forres where rebellion was quashed.",
            ambient_state={"danger": AmbientVector(value=0.9, volatility=0.4), "tension": AmbientVector(value=0.8, volatility=0.3)},
        ),
        "LOC_HEATH": Location(
            name="The Heath", description="Desolate moor shrouded in fog where the witches appear.",
            ambient_state={"supernatural": AmbientVector(value=0.9, volatility=0.2), "danger": AmbientVector(value=0.5, volatility=0.6)},
        ),
        "LOC_INVERNESS_CASTLE": Location(
            name="Inverness Castle", description="Macbeth's stronghold where Duncan is murdered.",
            ambient_state={"tension": AmbientVector(value=0.7, volatility=0.5), "concealment": AmbientVector(value=0.6, volatility=0.4)},
        ),
        "LOC_DUNSINANE_CASTLE": Location(
            name="Dunsinane Castle", description="Royal seat where Macbeth reigns as tyrant.",
            ambient_state={"danger": AmbientVector(value=0.8, volatility=0.3), "tension": AmbientVector(value=0.9, volatility=0.2)},
        ),
        "LOC_WITCHES_CAVERN": Location(
            name="Witches' Cavern", description="Subterranean lair where the second set of prophecies is delivered.",
            ambient_state={"supernatural": AmbientVector(value=1.0, volatility=0.1)},
        ),
        "LOC_ENGLAND": Location(
            name="England", description="Refuge of Malcolm and Macduff, seat of King Edward.",
            ambient_state={"safety": AmbientVector(value=0.8, volatility=0.2)},
        ),
        "LOC_MACDUFF_CASTLE": Location(
            name="Macduff's Castle", description="Home of Macduff's family, site of the massacre.",
            ambient_state={"safety": AmbientVector(value=0.6, volatility=0.7)},
        ),
        "LOC_BIRNAM_WOOD": Location(
            name="Birnam Wood", description="Forest used as camouflage by Malcolm's advancing army.",
            ambient_state={"concealment": AmbientVector(value=0.7, volatility=0.3)},
        ),
    },

    # ── OBJECTS ─────────────────────────────────────────────────────────
    objects={
        "OBJ_BLOODY_DAGGERS": NarrativeObject(
            id="OBJ_BLOODY_DAGGERS", name="Bloody Daggers",
            location_id=None, owner_id="ENT_MACBETH",
            properties={"state": "blood-smeared"},
            affordances=[Affordance(action="kill", target_type="Entity"), Affordance(action="frame", target_type="Entity")],
        ),
        "OBJ_CROWN": NarrativeObject(
            id="OBJ_CROWN", name="Crown of Scotland",
            location_id=None, owner_id="ENT_MACBETH",
            properties={"state": "contested"},
            affordances=[Affordance(action="legitimize", target_type="Entity")],
        ),
        "OBJ_LETTER": NarrativeObject(
            id="OBJ_LETTER", name="Macbeth's Letter to Lady Macbeth",
            location_id=None, owner_id="ENT_LADY_MACBETH",
            properties={"content": "witches_prophecy"},
            affordances=[Affordance(action="inform", target_type="Entity")],
        ),
        "OBJ_CAULDRON": NarrativeObject(
            id="OBJ_CAULDRON", name="Witches' Cauldron",
            location_id="LOC_WITCHES_CAVERN", owner_id=None,
            properties={"state": "bubbling"},
            affordances=[Affordance(action="prophesy", target_type="Entity")],
        ),
    },

    # ── ENTITIES ────────────────────────────────────────────────────────
    entities={
        "ENT_MACBETH": Entity(
            id="ENT_MACBETH", name="Macbeth (Thane of Glamis)",
            location_id="LOC_DUNSINANE_CASTLE", status="healthy",
            traits={
                "ambition": TraitVector(value=0.95, inertia=0.8),
                "courage": TraitVector(value=0.8, inertia=0.5),
                "guilt": TraitVector(value=0.1, inertia=0.2),
                "paranoia": TraitVector(value=0.2, inertia=0.2),
                "loyalty": TraitVector(value=0.6, inertia=0.4),
                "ruthlessness": TraitVector(value=0.3, inertia=0.3),
                "despair": TraitVector(value=0.1, inertia=0.2),
            },
            beliefs=[
                Belief(target_id="ENT_DUNCAN", perceived_state="Duncan is my kinsman and king whom I serve loyally", confidence=0.9, inertia=0.6),
                Belief(target_id="ENT_BANQUO", perceived_state="Banquo is a trusted comrade", confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_WITCHES", perceived_state="The witches' prophecies may be true", confidence=0.5, inertia=0.3),
            ],
            constants=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_WITCHES_PROPHECY_1",
                    traits={"ambition": TraitVector(value=0.8, inertia=0.3), "paranoia": TraitVector(value=0.4, inertia=0.2)}),
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_DUNCAN_MURDER",
                    traits={"guilt": TraitVector(value=0.7, inertia=0.2), "paranoia": TraitVector(value=0.6, inertia=0.3), "ruthlessness": TraitVector(value=0.6, inertia=0.3)},
                    new_location_id="LOC_INVERNESS_CASTLE"),
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_BANQUO_MURDERED",
                    traits={"paranoia": TraitVector(value=0.8, inertia=0.3), "guilt": TraitVector(value=0.8, inertia=0.2)}),
                EntityStateSnapshot(fabula_time=1900, triggered_by="EVT_MACBETH_KILLED",
                    new_status="dead"),
            ],
        ),
        "ENT_LADY_MACBETH": Entity(
            id="ENT_LADY_MACBETH", name="Lady Macbeth",
            location_id="LOC_DUNSINANE_CASTLE", status="healthy",
            traits={
                "ambition": TraitVector(value=0.9, inertia=0.4),
                "ruthlessness": TraitVector(value=0.8, inertia=0.4),
                "guilt": TraitVector(value=0.05, inertia=0.1),
                "resolve": TraitVector(value=0.9, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_MACBETH", perceived_state="Macbeth is too full of the milk of human kindness to seize power alone", confidence=0.8, inertia=0.5),
                Belief(target_id="OBJ_CROWN", perceived_state="The crown is within our grasp if we act tonight", confidence=0.9, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_DUNCAN_MURDER",
                    traits={"guilt": TraitVector(value=0.3, inertia=0.1), "resolve": TraitVector(value=0.8, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_LADY_MACBETH_SLEEPWALKING",
                    traits={"guilt": TraitVector(value=0.95, inertia=0.1), "resolve": TraitVector(value=0.2, inertia=0.3)},
                    new_status="ill"),
                EntityStateSnapshot(fabula_time=1700, triggered_by="EVT_LADY_MACBETH_DEATH",
                    new_status="dead"),
            ],
        ),
        "ENT_DUNCAN": Entity(
            id="ENT_DUNCAN", name="King Duncan",
            location_id="LOC_INVERNESS_CASTLE", status="healthy",
            traits={
                "benevolence": TraitVector(value=0.9, inertia=0.7),
                "trust": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_MACBETH", perceived_state="Macbeth is my loyal and valiant kinsman", confidence=0.95, inertia=0.7),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_DUNCAN_MURDER", new_status="dead"),
            ],
        ),
        "ENT_BANQUO": Entity(
            id="ENT_BANQUO", name="Banquo",
            location_id="LOC_BATTLEFIELD", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.7, inertia=0.6),
                "suspicion": TraitVector(value=0.3, inertia=0.3),
                "courage": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_WITCHES", perceived_state="The prophecies may hold truth — my line shall be kings", confidence=0.5, inertia=0.4),
                Belief(target_id="ENT_MACBETH", perceived_state="Macbeth may have played foully for the crown", confidence=0.6, inertia=0.3, established_at_fabula=900),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_BANQUO_MURDERED", new_status="dead"),
            ],
        ),
        "ENT_MACDUFF": Entity(
            id="ENT_MACDUFF", name="Macduff (Thane of Fife)",
            location_id="LOC_INVERNESS_CASTLE", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.8, inertia=0.6),
                "courage": TraitVector(value=0.8, inertia=0.5),
                "vengefulness": TraitVector(value=0.2, inertia=0.2),
                "grief": TraitVector(value=0.1, inertia=0.2),
            },
            beliefs=[
                Belief(target_id="ENT_MACBETH", perceived_state="Macbeth is a tyrant who murdered Duncan", confidence=0.7, inertia=0.4, established_at_fabula=700),
            ],
            constants=["caesarean_birth"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1400, triggered_by="EVT_MACDUFF_FAMILY_SLAUGHTERED",
                    traits={"grief": TraitVector(value=0.95, inertia=0.2), "vengefulness": TraitVector(value=0.9, inertia=0.3)},
                    new_location_id="LOC_ENGLAND"),
            ],
        ),
        "ENT_MALCOLM": Entity(
            id="ENT_MALCOLM", name="Prince Malcolm",
            location_id="LOC_INVERNESS_CASTLE", status="healthy",
            traits={
                "caution": TraitVector(value=0.7, inertia=0.5),
                "leadership": TraitVector(value=0.5, inertia=0.3),
                "trust": TraitVector(value=0.4, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_MACBETH", perceived_state="Macbeth may have killed my father", confidence=0.6, inertia=0.4, established_at_fabula=700),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_SONS_FLEE", new_location_id="LOC_ENGLAND"),
            ],
        ),
        "ENT_WITCHES": Entity(
            id="ENT_WITCHES", name="The Three Witches",
            location_id="LOC_HEATH", status="healthy",
            traits={
                "malice": TraitVector(value=0.8, inertia=0.9),
                "deception": TraitVector(value=0.7, inertia=0.8),
            },
            beliefs=[],
            constants=["supernatural"],
        ),
        "ENT_FLEANCE": Entity(
            id="ENT_FLEANCE", name="Fleance (son of Banquo)",
            location_id="LOC_ENGLAND", status="healthy",
            traits={
                "innocence": TraitVector(value=0.9, inertia=0.5),
            },
            beliefs=[],
        ),
        "ENT_LENNOX": Entity(
            id="ENT_LENNOX", name="Lennox",
            location_id="LOC_INVERNESS_CASTLE", status="healthy",
            traits={
                "suspicion": TraitVector(value=0.4, inertia=0.3),
                "loyalty": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_MACBETH", perceived_state="Macbeth is a murderous tyrant", confidence=0.7, inertia=0.3, established_at_fabula=1200),
            ],
        ),
    },

    # ── EVENTS ──────────────────────────────────────────────────────────
    events=[
        EventNode(id="EVT_REBELLION_DEFEATED", fabula_time=100, syuzhet_index=1,
                  event_type="outcome", actor_ids=["ENT_MACBETH", "ENT_BANQUO"], target_ids=[],
                  description="Macbeth and Banquo defeat the rebellion of the Thane of Cawdor."),
        EventNode(id="EVT_WITCHES_PROPHECY_1", fabula_time=200, syuzhet_index=2,
                  event_type="revelation", actor_ids=["ENT_WITCHES"], target_ids=["ENT_MACBETH", "ENT_BANQUO"],
                  description="The witches prophesy Macbeth will be king and Banquo's line will inherit the throne."),
        EventNode(id="EVT_CAWDOR_TITLE", fabula_time=300, syuzhet_index=3,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MACBETH"],
                  description="Macbeth is granted the title Thane of Cawdor, fulfilling the first prophecy."),
        EventNode(id="EVT_LETTER_SENT", fabula_time=400, syuzhet_index=4,
                  event_type="choice", actor_ids=["ENT_MACBETH"], target_ids=["ENT_LADY_MACBETH"],
                  description="Macbeth sends a letter to Lady Macbeth about the witches' prophecy."),
        EventNode(id="EVT_LADY_MACBETH_PERSUADES", fabula_time=500, syuzhet_index=5,
                  event_type="choice", actor_ids=["ENT_LADY_MACBETH"], target_ids=["ENT_MACBETH"],
                  description="Lady Macbeth persuades Macbeth to murder Duncan that night."),
        EventNode(id="EVT_DUNCAN_MURDER", fabula_time=600, syuzhet_index=6,
                  event_type="choice", actor_ids=["ENT_MACBETH"], target_ids=["ENT_DUNCAN"],
                  description="Macbeth stabs the sleeping King Duncan to death."),
        EventNode(id="EVT_SERVANTS_FRAMED", fabula_time=650, syuzhet_index=7,
                  event_type="choice", actor_ids=["ENT_LADY_MACBETH"], target_ids=[],
                  description="Lady Macbeth plants the bloody daggers on Duncan's sleeping servants."),
        EventNode(id="EVT_MACBETH_KILLS_SERVANTS", fabula_time=700, syuzhet_index=8,
                  event_type="choice", actor_ids=["ENT_MACBETH"], target_ids=[],
                  description="Macbeth impulsively kills Duncan's servants to silence them."),
        EventNode(id="EVT_SONS_FLEE", fabula_time=750, syuzhet_index=9,
                  event_type="choice", actor_ids=["ENT_MALCOLM"], target_ids=[],
                  description="Duncan's sons flee Scotland, fearing for their lives."),
        EventNode(id="EVT_MACBETH_CROWNED", fabula_time=900, syuzhet_index=10,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MACBETH"],
                  description="Macbeth assumes the throne as King of Scotland."),
        EventNode(id="EVT_BANQUO_MURDERED", fabula_time=1100, syuzhet_index=11,
                  event_type="choice", actor_ids=["ENT_MACBETH"], target_ids=["ENT_BANQUO"],
                  description="Macbeth's hired assassins kill Banquo, but Fleance escapes."),
        EventNode(id="EVT_BANQUO_GHOST", fabula_time=1150, syuzhet_index=12,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MACBETH"],
                  description="Banquo's ghost appears at the banquet, visible only to Macbeth."),
        EventNode(id="EVT_WITCHES_PROPHECY_2", fabula_time=1300, syuzhet_index=13,
                  event_type="revelation", actor_ids=["ENT_WITCHES"], target_ids=["ENT_MACBETH"],
                  description="The witches deliver three new prophecies: beware Macduff, none of woman born, Birnam Wood."),
        EventNode(id="EVT_MACDUFF_FAMILY_SLAUGHTERED", fabula_time=1400, syuzhet_index=14,
                  event_type="choice", actor_ids=["ENT_MACBETH"], target_ids=["ENT_MACDUFF"],
                  description="Macbeth orders the slaughter of Macduff's wife and children."),
        EventNode(id="EVT_MALCOLM_MACDUFF_ALLIANCE", fabula_time=1500, syuzhet_index=15,
                  event_type="choice", actor_ids=["ENT_MALCOLM", "ENT_MACDUFF"], target_ids=[],
                  description="Malcolm and Macduff form an alliance to retake Scotland."),
        EventNode(id="EVT_LADY_MACBETH_SLEEPWALKING", fabula_time=1600, syuzhet_index=16,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_LADY_MACBETH"],
                  description="Lady Macbeth sleepwalks, compulsively washing imaginary bloodstains from her hands."),
        EventNode(id="EVT_LADY_MACBETH_DEATH", fabula_time=1700, syuzhet_index=17,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_LADY_MACBETH"],
                  description="Lady Macbeth dies, implied suicide."),
        EventNode(id="EVT_BIRNAM_WOOD_MOVES", fabula_time=1800, syuzhet_index=18,
                  event_type="outcome", actor_ids=["ENT_MALCOLM"], target_ids=[],
                  description="Malcolm's soldiers carry tree boughs from Birnam Wood, fulfilling the prophecy."),
        EventNode(id="EVT_MACBETH_KILLED", fabula_time=1900, syuzhet_index=19,
                  event_type="outcome", actor_ids=["ENT_MACDUFF"], target_ids=["ENT_MACBETH"],
                  description="Macduff, born by caesarean section, kills Macbeth in single combat."),
        EventNode(id="EVT_MALCOLM_CROWNED", fabula_time=2000, syuzhet_index=20,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MALCOLM"],
                  description="Malcolm is crowned King of Scotland; order is restored."),
    ],

    # ── CAUSAL TOPOLOGY ─────────────────────────────────────────────────
    causal_topology=[
        # ── chain_reaction (Event → Event) ──
        CausalEdge(source_id="EVT_REBELLION_DEFEATED", target_id="EVT_CAWDOR_TITLE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=100),
        CausalEdge(source_id="EVT_WITCHES_PROPHECY_1", target_id="EVT_LETTER_SENT",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200),
        CausalEdge(source_id="EVT_LADY_MACBETH_PERSUADES", target_id="EVT_DUNCAN_MURDER",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500),
        CausalEdge(source_id="EVT_DUNCAN_MURDER", target_id="EVT_SERVANTS_FRAMED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=600),
        CausalEdge(source_id="EVT_DUNCAN_MURDER", target_id="EVT_SONS_FLEE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=600),
        CausalEdge(source_id="EVT_SONS_FLEE", target_id="EVT_MACBETH_CROWNED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=750),
        CausalEdge(source_id="EVT_WITCHES_PROPHECY_1", target_id="EVT_BANQUO_MURDERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=200, propagation_delay=900),
        CausalEdge(source_id="EVT_BANQUO_MURDERED", target_id="EVT_BANQUO_GHOST",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1100),
        CausalEdge(source_id="EVT_WITCHES_PROPHECY_2", target_id="EVT_MACDUFF_FAMILY_SLAUGHTERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1300),
        CausalEdge(source_id="EVT_MACDUFF_FAMILY_SLAUGHTERED", target_id="EVT_MALCOLM_MACDUFF_ALLIANCE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1400),
        CausalEdge(source_id="EVT_MALCOLM_MACDUFF_ALLIANCE", target_id="EVT_BIRNAM_WOOD_MOVES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1500),
        CausalEdge(source_id="EVT_BIRNAM_WOOD_MOVES", target_id="EVT_MACBETH_KILLED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1800),
        CausalEdge(source_id="EVT_MACBETH_KILLED", target_id="EVT_MALCOLM_CROWNED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1900),

        # ── mutation (Event → Entity trait/status) ──
        CausalEdge(source_id="EVT_WITCHES_PROPHECY_1", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200,
                   trait_target="ambition", trait_delta=0.3),
        CausalEdge(source_id="EVT_DUNCAN_MURDER", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=600,
                   trait_target="guilt", trait_delta=0.6),
        CausalEdge(source_id="EVT_DUNCAN_MURDER", target_id="ENT_LADY_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=600,
                   trait_target="guilt", trait_delta=0.25, propagation_delay=1000),
        CausalEdge(source_id="EVT_BANQUO_MURDERED", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1100,
                   trait_target="paranoia", trait_delta=0.3),
        CausalEdge(source_id="EVT_MACDUFF_FAMILY_SLAUGHTERED", target_id="ENT_MACDUFF",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1400,
                   trait_target="vengefulness", trait_delta=0.7),
        CausalEdge(source_id="EVT_MACDUFF_FAMILY_SLAUGHTERED", target_id="ENT_MACDUFF",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1400,
                   trait_target="grief", trait_delta=0.85),
        CausalEdge(source_id="EVT_LADY_MACBETH_SLEEPWALKING", target_id="ENT_LADY_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1600,
                   trait_target="guilt", trait_delta=0.65),
        CausalEdge(source_id="EVT_WITCHES_PROPHECY_2", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=1300,
                   trait_target="paranoia", trait_delta=-0.3),

        # ── mutation_social (Event → Relationship) ──
        CausalEdge(source_id="EVT_DUNCAN_MURDER", target_id="ENT_MACBETH",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=600,
                   trait_target="fear", trait_delta=0.4, rel_counterpart_id="ENT_BANQUO"),
        CausalEdge(source_id="EVT_BANQUO_MURDERED", target_id="ENT_MALCOLM",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=1100,
                   trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_MACBETH"),
        CausalEdge(source_id="EVT_MACDUFF_FAMILY_SLAUGHTERED", target_id="ENT_MACDUFF",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1400,
                   trait_target="affinity", trait_delta=-0.9, rel_counterpart_id="ENT_MACBETH"),

        # ── affordance_gate (State → Event) ──
        CausalEdge(source_id="ENT_MACBETH", target_id="EVT_LADY_MACBETH_PERSUADES",
                   causality_type="affordance_gate", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=500),
        CausalEdge(source_id="ENT_MACDUFF", target_id="EVT_MACBETH_KILLED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1900),
        CausalEdge(source_id="ENT_WITCHES", target_id="EVT_WITCHES_PROPHECY_1",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200),

        # ── ambient_propagation (State → State) ──
        CausalEdge(source_id="LOC_DUNSINANE_CASTLE", target_id="ENT_MACBETH",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=1300),
        CausalEdge(source_id="ENT_MACBETH", target_id="ENT_LADY_MACBETH",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=1200),
    ],

    # ── SPATIAL TOPOLOGY ────────────────────────────────────────────────
    spatial_topology=[
        SpatialEdge(source_id="LOC_BATTLEFIELD", target_id="LOC_HEATH"),
        SpatialEdge(source_id="LOC_BATTLEFIELD", target_id="LOC_INVERNESS_CASTLE"),
        SpatialEdge(source_id="LOC_HEATH", target_id="LOC_INVERNESS_CASTLE"),
        SpatialEdge(source_id="LOC_HEATH", target_id="LOC_WITCHES_CAVERN"),
        SpatialEdge(source_id="LOC_INVERNESS_CASTLE", target_id="LOC_DUNSINANE_CASTLE"),
        SpatialEdge(source_id="LOC_DUNSINANE_CASTLE", target_id="LOC_INVERNESS_CASTLE"),
        SpatialEdge(source_id="LOC_DUNSINANE_CASTLE", target_id="LOC_MACDUFF_CASTLE"),
        SpatialEdge(source_id="LOC_DUNSINANE_CASTLE", target_id="LOC_BIRNAM_WOOD"),
        SpatialEdge(source_id="LOC_BIRNAM_WOOD", target_id="LOC_ENGLAND"),
        SpatialEdge(source_id="LOC_ENGLAND", target_id="LOC_MACDUFF_CASTLE"),
    ],

    # ── INFORMATION TOPOLOGY ────────────────────────────────────────────
    information_topology=[
        InformationEdge(source_id="ENT_WITCHES", target_ids=["ENT_MACBETH", "ENT_BANQUO"],
                        medium="prophecy", established_at_fabula=200),
        InformationEdge(source_id="ENT_MACBETH", target_ids=["ENT_LADY_MACBETH"],
                        medium="letter", is_encrypted=True,
                        established_at_fabula=400, terminated_at_fabula=500),
        InformationEdge(source_id="ENT_WITCHES", target_ids=["ENT_MACBETH"],
                        medium="prophecy", established_at_fabula=1300),
        InformationEdge(source_id="ENT_LADY_MACBETH", target_ids=["ENT_LENNOX"],
                        medium="overheard_confession", is_encrypted=False,
                        established_at_fabula=1600, terminated_at_fabula=1600),
        InformationEdge(source_id="ENT_LENNOX", target_ids=["ENT_MACDUFF"],
                        medium="whisper", is_encrypted=True,
                        established_at_fabula=1200),
    ],

    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_FEUDAL_HIERARCHY": GlobalTrait(
            id="WORLD_FEUDAL_HIERARCHY",
            name="Feudal Power Structure",
            description="Scotland's feudal hierarchy where thanes compete for royal favor through violence and loyalty. Kingship is earned through bloodshed.",
            category="governance",
            magnitude=TraitVector(value=0.8, inertia=0.6),
            affected_domains=["social", "psychological"],
        ),
        "WORLD_SUPERNATURAL_PROPHECY": GlobalTrait(
            id="WORLD_SUPERNATURAL_PROPHECY",
            name="Supernatural Prophecy",
            description="The witches' prophecies create an ambiguous supernatural backdrop that blurs the line between fate and free will.",
            category="cosmology",
            magnitude=TraitVector(value=0.5, inertia=0.8),
            affected_domains=["psychological", "epistemic"],
        ),
    },

    # ── SOCIAL TOPOLOGY ─────────────────────────────────────────────────
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_MACBETH", target_entity_id="ENT_LADY_MACBETH",
                         affinity=0.8, fear=0.3, power_dynamic=-0.3, inertia=0.3, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_LADY_MACBETH", target_entity_id="ENT_MACBETH",
                         affinity=0.8, fear=0.2, power_dynamic=0.4, inertia=0.5, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_MACBETH", target_entity_id="ENT_DUNCAN",
                         affinity=0.3, fear=0.35, power_dynamic=-0.6, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_MACBETH", target_entity_id="ENT_BANQUO",
                         affinity=0.4, fear=0.3, power_dynamic=0.2, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_BANQUO", target_entity_id="ENT_MACBETH",
                         affinity=0.2, fear=0.35, power_dynamic=-0.4, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_MACBETH", target_entity_id="ENT_MACDUFF",
                         affinity=-0.8, fear=0.45, power_dynamic=0.3, inertia=0.3, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_MACDUFF", target_entity_id="ENT_MACBETH",
                         affinity=-0.9, fear=0.3, power_dynamic=-0.5, inertia=0.3, evidence_strength="strong",
                         last_updated_fabula=1400),
        RelationshipEdge(source_entity_id="ENT_MACDUFF", target_entity_id="ENT_MALCOLM",
                         affinity=0.8, fear=0.1, power_dynamic=-0.3, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_MALCOLM", target_entity_id="ENT_MACBETH",
                         affinity=-0.9, fear=0.45, power_dynamic=-0.5, inertia=0.3, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_LADY_MACBETH", target_entity_id="ENT_DUNCAN",
                         affinity=-0.5, fear=0.4, power_dynamic=-0.4, inertia=0.3, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_MACBETH", target_entity_id="ENT_WITCHES",
                         affinity=0.3, fear=0.3, power_dynamic=-0.5, inertia=0.3, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_MACBETH", target_entity_id="ENT_FLEANCE",
                         affinity=-0.6, fear=0.35, power_dynamic=0.5, inertia=0.2, evidence_strength="weak"),
        RelationshipEdge(source_entity_id="ENT_LENNOX", target_entity_id="ENT_MACBETH",
                         affinity=-0.5, fear=0.3, power_dynamic=-0.4, inertia=0.3, evidence_strength="moderate"),
    ],
)