"""1984 — high-fidelity WorldStateV1 test fixture."""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait,
)

world_state = WorldStateV1(
    locations={
        "LOC_VICTORY_MANSIONS": Location(name="Victory Mansions", description="Winston's dilapidated flat with ever-present telescreen.",
            ambient_state={"surveillance": AmbientVector(value=0.9, volatility=0.2), "decay": AmbientVector(value=0.7, volatility=0.1)}),
        "LOC_MINISTRY_TRUTH": Location(name="Ministry of Truth", description="Propaganda ministry where Winston rewrites history.",
            ambient_state={"surveillance": AmbientVector(value=0.95, volatility=0.1), "oppression": AmbientVector(value=0.8, volatility=0.2)}),
        "LOC_ROOM_101": Location(name="Room 101", description="Torture chamber containing each prisoner's worst fear.",
            ambient_state={"terror": AmbientVector(value=1.0, volatility=0.1), "oppression": AmbientVector(value=1.0, volatility=0.1)}),
        "LOC_CHARRINGTON_ROOM": Location(name="Charrington's Room", description="Room above the antique shop where Winston and Julia meet secretly.",
            ambient_state={"false_safety": AmbientVector(value=0.8, volatility=0.6), "intimacy": AmbientVector(value=0.7, volatility=0.4)}),
        "LOC_MINISTRY_LOVE": Location(name="Ministry of Love", description="Secret police headquarters where prisoners are broken.",
            ambient_state={"terror": AmbientVector(value=0.9, volatility=0.2), "surveillance": AmbientVector(value=1.0, volatility=0.1)}),
        "LOC_GOLDEN_COUNTRY": Location(name="Golden Country", description="Rural clearing where Winston and Julia first make love.",
            ambient_state={"freedom": AmbientVector(value=0.7, volatility=0.5)}),
        "LOC_CHESTNUT_TREE_CAFE": Location(name="Chestnut Tree Cafe", description="Cafe where broken dissidents drink Victory Gin.",
            ambient_state={"despair": AmbientVector(value=0.8, volatility=0.2)}),
    },
    objects={
        "OBJ_DIARY": NarrativeObject(id="OBJ_DIARY", name="Winston's Diary",
            location_id="LOC_VICTORY_MANSIONS", owner_id="ENT_WINSTON",
            properties={"state": "hidden", "content": "thoughtcrime"},
            affordances=[Affordance(action="record_thoughts", target_type="Entity"), Affordance(action="incriminate", target_type="Entity")]),
        "OBJ_PAPERWEIGHT": NarrativeObject(id="OBJ_PAPERWEIGHT", name="Glass Paperweight",
            location_id="LOC_CHARRINGTON_ROOM", owner_id="ENT_WINSTON",
            properties={"state": "intact", "symbolism": "fragile_beauty"},
            affordances=[Affordance(action="symbolize_hope", target_type="Entity")]),
        "OBJ_TELESCREEN": NarrativeObject(id="OBJ_TELESCREEN", name="Telescreen",
            location_id="LOC_VICTORY_MANSIONS", owner_id=None,
            properties={"state": "always_on", "coverage": "omnipresent"},
            affordances=[Affordance(action="surveil", target_type="Entity")]),
        "OBJ_GOLDSTEIN_BOOK": NarrativeObject(id="OBJ_GOLDSTEIN_BOOK", name="Goldstein's Book",
            location_id=None, owner_id="ENT_OBRIEN",
            properties={"state": "forbidden", "content": "theory_of_oligarchical_collectivism"},
            affordances=[Affordance(action="enlighten", target_type="Entity"), Affordance(action="entrap", target_type="Entity")]),
    },
    entities={
        "ENT_WINSTON": Entity(id="ENT_WINSTON", name="Winston Smith",
            location_id="LOC_VICTORY_MANSIONS", status="healthy",
            traits={
                "rebellion": TraitVector(value=0.6, inertia=0.3),
                "fear": TraitVector(value=0.5, inertia=0.3),
                "intellect": TraitVector(value=0.7, inertia=0.5),
                "hope": TraitVector(value=0.4, inertia=0.2),
                "fatalism": TraitVector(value=0.6, inertia=0.4),
                "integrity": TraitVector(value=0.5, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_OBRIEN", perceived_state="O'Brien is a Brotherhood ally who shares my rebellion", confidence=0.7, inertia=0.3, established_at_fabula=600),
                Belief(target_id="ENT_BIG_BROTHER", perceived_state="Big Brother's regime can be overthrown", confidence=0.4, inertia=0.2),
                Belief(target_id="ENT_CHARRINGTON", perceived_state="Charrington is a harmless old shopkeeper", confidence=0.8, inertia=0.4, established_at_fabula=300),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=300, triggered_by="EVT_JULIA_NOTE",
                    traits={"hope": TraitVector(value=0.7, inertia=0.2), "rebellion": TraitVector(value=0.7, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_OBRIEN_RECRUITS",
                    traits={"hope": TraitVector(value=0.8, inertia=0.2)},
                    beliefs_invalidated=["ENT_OBRIEN"]),
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_ARRESTED",
                    traits={"fear": TraitVector(value=0.9, inertia=0.2), "hope": TraitVector(value=0.2, inertia=0.2)},
                    new_location_id="LOC_MINISTRY_LOVE"),
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_ROOM_101",
                    traits={"integrity": TraitVector(value=0.0, inertia=0.1), "rebellion": TraitVector(value=0.0, inertia=0.1)}),
            ]),
        "ENT_JULIA": Entity(id="ENT_JULIA", name="Julia",
            location_id="LOC_MINISTRY_TRUTH", status="healthy",
            traits={
                "sensuality": TraitVector(value=0.8, inertia=0.5),
                "pragmatism": TraitVector(value=0.7, inertia=0.5),
                "rebellion": TraitVector(value=0.6, inertia=0.3),
                "survival_instinct": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_WINSTON", perceived_state="Winston is someone I can trust and love", confidence=0.8, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_ARRESTED",
                    new_location_id="LOC_MINISTRY_LOVE"),
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_JULIA_BROKEN",
                    traits={"rebellion": TraitVector(value=0.0, inertia=0.1)},
                    beliefs_invalidated=["ENT_WINSTON"]),
            ]),
        "ENT_OBRIEN": Entity(id="ENT_OBRIEN", name="O'Brien",
            location_id="LOC_MINISTRY_LOVE", status="healthy",
            traits={
                "intellect": TraitVector(value=0.9, inertia=0.7),
                "cruelty": TraitVector(value=0.8, inertia=0.6),
                "fanaticism": TraitVector(value=0.9, inertia=0.7),
                "manipulation": TraitVector(value=0.9, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_WINSTON", perceived_state="Winston is a thoughtcriminal who must be broken", confidence=0.95, inertia=0.7),
                Belief(target_id="ENT_BIG_BROTHER", perceived_state="The Party is eternal and infallible", confidence=1.0, inertia=0.9),
            ]),
        "ENT_CHARRINGTON": Entity(id="ENT_CHARRINGTON", name="Mr Charrington",
            location_id="LOC_CHARRINGTON_ROOM", status="healthy",
            traits={
                "deceit": TraitVector(value=0.9, inertia=0.7),
                "patience": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[]),
        "ENT_SYME": Entity(id="ENT_SYME", name="Syme",
            location_id="LOC_MINISTRY_TRUTH", status="healthy",
            traits={
                "intellect": TraitVector(value=0.8, inertia=0.5),
                "orthodoxy": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_BIG_BROTHER", perceived_state="Newspeak will perfect Ingsoc ideology", confidence=0.9, inertia=0.5),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_SYME_VANISHES", new_status="dead"),
            ]),
        "ENT_PARSONS": Entity(id="ENT_PARSONS", name="Tom Parsons",
            location_id="LOC_VICTORY_MANSIONS", status="healthy",
            traits={
                "orthodoxy": TraitVector(value=0.6, inertia=0.4),
                "naivete": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_BIG_BROTHER", perceived_state="The Party is always right", confidence=0.8, inertia=0.5),
            ]),
        "ENT_BIG_BROTHER": Entity(id="ENT_BIG_BROTHER", name="Big Brother",
            location_id="LOC_MINISTRY_TRUTH", status="healthy",
            traits={
                "omnipresence": TraitVector(value=1.0, inertia=0.9),
                "authority": TraitVector(value=1.0, inertia=0.9),
            },
            beliefs=[]),
    },
    events=[
        EventNode(id="EVT_DIARY_BEGUN", fabula_time=100, syuzhet_index=1, event_type="choice",
                  actor_ids=["ENT_WINSTON"], target_ids=[],
                  description="Winston begins writing his secret diary, committing thoughtcrime."),
        EventNode(id="EVT_TWO_MINUTES_HATE", fabula_time=200, syuzhet_index=2, event_type="outcome",
                  actor_ids=["ENT_WINSTON"], target_ids=["ENT_OBRIEN"],
                  description="Winston notices O'Brien during Two Minutes Hate and believes he shares his rebellion."),
        EventNode(id="EVT_JULIA_NOTE", fabula_time=300, syuzhet_index=3, event_type="revelation",
                  actor_ids=["ENT_JULIA"], target_ids=["ENT_WINSTON"],
                  description="Julia passes Winston a note reading 'I love you'."),
        EventNode(id="EVT_GOLDEN_COUNTRY_MEETING", fabula_time=400, syuzhet_index=4, event_type="choice",
                  actor_ids=["ENT_WINSTON", "ENT_JULIA"], target_ids=[],
                  description="Winston and Julia meet secretly in the Golden Country and begin their affair."),
        EventNode(id="EVT_SYME_VANISHES", fabula_time=500, syuzhet_index=5, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_SYME"],
                  description="Syme is vaporized by the Party for being too intelligent."),
        EventNode(id="EVT_OBRIEN_RECRUITS", fabula_time=600, syuzhet_index=6, event_type="choice",
                  actor_ids=["ENT_OBRIEN"], target_ids=["ENT_WINSTON", "ENT_JULIA"],
                  description="O'Brien pretends to recruit Winston and Julia into the Brotherhood."),
        EventNode(id="EVT_GOLDSTEIN_BOOK_READ", fabula_time=700, syuzhet_index=7, event_type="revelation",
                  actor_ids=["ENT_WINSTON"], target_ids=[],
                  description="Winston reads Goldstein's book in Charrington's room, understanding the Party's mechanics."),
        EventNode(id="EVT_ARRESTED", fabula_time=800, syuzhet_index=8, event_type="outcome",
                  actor_ids=["ENT_CHARRINGTON"], target_ids=["ENT_WINSTON", "ENT_JULIA"],
                  description="Thought Police arrest Winston and Julia; Charrington is revealed as an agent."),
        EventNode(id="EVT_OBRIEN_TORTURES", fabula_time=900, syuzhet_index=9, event_type="choice",
                  actor_ids=["ENT_OBRIEN"], target_ids=["ENT_WINSTON"],
                  description="O'Brien tortures Winston in the Ministry of Love to destroy his mind."),
        EventNode(id="EVT_ROOM_101", fabula_time=1000, syuzhet_index=10, event_type="choice",
                  actor_ids=["ENT_OBRIEN"], target_ids=["ENT_WINSTON"],
                  description="Winston is sent to Room 101, where he betrays Julia to escape the rats."),
        EventNode(id="EVT_JULIA_BROKEN", fabula_time=1100, syuzhet_index=11, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_JULIA"],
                  description="Julia is also broken by the Party; she and Winston meet as hollow shells."),
        EventNode(id="EVT_WINSTON_LOVES_BB", fabula_time=1200, syuzhet_index=12, event_type="outcome",
                  actor_ids=["ENT_WINSTON"], target_ids=["ENT_BIG_BROTHER"],
                  description="Winston, sitting in the Chestnut Tree Cafe, finally loves Big Brother."),
    ],
    causal_topology=[
        # chain_reaction
        CausalEdge(source_id="EVT_DIARY_BEGUN", target_id="EVT_TWO_MINUTES_HATE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=100),
        CausalEdge(source_id="EVT_TWO_MINUTES_HATE", target_id="EVT_JULIA_NOTE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=200),
        CausalEdge(source_id="EVT_JULIA_NOTE", target_id="EVT_GOLDEN_COUNTRY_MEETING",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300),
        CausalEdge(source_id="EVT_GOLDEN_COUNTRY_MEETING", target_id="EVT_OBRIEN_RECRUITS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=400),
        CausalEdge(source_id="EVT_OBRIEN_RECRUITS", target_id="EVT_GOLDSTEIN_BOOK_READ",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=600),
        CausalEdge(source_id="EVT_GOLDSTEIN_BOOK_READ", target_id="EVT_ARRESTED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700),
        CausalEdge(source_id="EVT_ARRESTED", target_id="EVT_OBRIEN_TORTURES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=800),
        CausalEdge(source_id="EVT_OBRIEN_TORTURES", target_id="EVT_ROOM_101",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=900),
        CausalEdge(source_id="EVT_ROOM_101", target_id="EVT_WINSTON_LOVES_BB",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1000),
        CausalEdge(source_id="EVT_ROOM_101", target_id="EVT_JULIA_BROKEN",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000),
        # mutation
        CausalEdge(source_id="EVT_JULIA_NOTE", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300, trait_target="hope", trait_delta=0.3),
        CausalEdge(source_id="EVT_OBRIEN_RECRUITS", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=600, trait_target="hope", trait_delta=0.1),
        CausalEdge(source_id="EVT_ARRESTED", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=800, trait_target="fear", trait_delta=0.4),
        CausalEdge(source_id="EVT_ROOM_101", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1000, trait_target="integrity", trait_delta=-0.5),
        CausalEdge(source_id="EVT_OBRIEN_TORTURES", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=900, trait_target="rebellion", trait_delta=-0.4),
        CausalEdge(source_id="EVT_SYME_VANISHES", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=500, trait_target="fatalism", trait_delta=0.2),
        # mutation_social
        CausalEdge(source_id="EVT_ROOM_101", target_id="ENT_WINSTON",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1000, trait_target="affinity", trait_delta=-1.0, rel_counterpart_id="ENT_JULIA"),
        CausalEdge(source_id="EVT_JULIA_BROKEN", target_id="ENT_JULIA",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1100, trait_target="affinity", trait_delta=-1.0, rel_counterpart_id="ENT_WINSTON"),
        CausalEdge(source_id="EVT_ARRESTED", target_id="ENT_WINSTON",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=8.0, fabula_time=800, trait_target="affinity", trait_delta=-0.6, rel_counterpart_id="ENT_OBRIEN"),
        CausalEdge(source_id="EVT_GOLDEN_COUNTRY_MEETING", target_id="ENT_JULIA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=400, trait_target="affinity", trait_delta=0.5, rel_counterpart_id="ENT_WINSTON"),
        # affordance_gate
        CausalEdge(source_id="OBJ_DIARY", target_id="EVT_DIARY_BEGUN",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=100),
        CausalEdge(source_id="ENT_CHARRINGTON", target_id="EVT_ARRESTED",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=9.0, fabula_time=800),
        CausalEdge(source_id="OBJ_GOLDSTEIN_BOOK", target_id="EVT_GOLDSTEIN_BOOK_READ",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=700),
        CausalEdge(source_id="LOC_ROOM_101", target_id="EVT_ROOM_101",
                   causality_type="affordance_gate", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1000),
        # ambient_propagation
        CausalEdge(source_id="LOC_MINISTRY_TRUTH", target_id="ENT_WINSTON",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=100),
        CausalEdge(source_id="LOC_CHARRINGTON_ROOM", target_id="ENT_WINSTON",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=400),
        CausalEdge(source_id="ENT_OBRIEN", target_id="ENT_WINSTON",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=900),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_VICTORY_MANSIONS", target_id="LOC_MINISTRY_TRUTH"),
        SpatialEdge(source_id="LOC_VICTORY_MANSIONS", target_id="LOC_CHARRINGTON_ROOM"),
        SpatialEdge(source_id="LOC_MINISTRY_TRUTH", target_id="LOC_MINISTRY_LOVE"),
        SpatialEdge(source_id="LOC_MINISTRY_LOVE", target_id="LOC_ROOM_101"),
        SpatialEdge(source_id="LOC_CHARRINGTON_ROOM", target_id="LOC_GOLDEN_COUNTRY"),
        SpatialEdge(source_id="LOC_MINISTRY_LOVE", target_id="LOC_CHESTNUT_TREE_CAFE"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_JULIA", target_ids=["ENT_WINSTON"], medium="handwritten_note", is_encrypted=True, established_at_fabula=300),
        InformationEdge(source_id="ENT_OBRIEN", target_ids=["ENT_WINSTON", "ENT_JULIA"], medium="meeting", established_at_fabula=600, terminated_at_fabula=800),
        InformationEdge(source_id="ENT_CHARRINGTON", target_ids=["ENT_OBRIEN"], medium="surveillance", established_at_fabula=400),
        InformationEdge(source_id="ENT_OBRIEN", target_ids=["ENT_WINSTON"], medium="torture_interrogation", established_at_fabula=900),
    ],
    world_traits={
        "WORLD_SURVEILLANCE_STATE": GlobalTrait(
            id="WORLD_SURVEILLANCE_STATE",
            name="Totalitarian Surveillance",
            description="The Party monitors all citizens through telescreens, microphones, informants, and the Thought Police. Privacy is functionally impossible.",
            category="governance",
            magnitude=TraitVector(value=0.95, inertia=0.9),
            affected_domains=["psychological", "epistemic", "social"],
        ),
        "WORLD_THOUGHT_CONTROL": GlobalTrait(
            id="WORLD_THOUGHT_CONTROL",
            name="Newspeak and Doublethink",
            description="Systematic reduction of language and cognitive freedom through Newspeak and doublethink. Limits what citizens can think and express.",
            category="governance",
            magnitude=TraitVector(value=0.85, inertia=0.85),
            affected_domains=["epistemic", "psychological"],
        ),
        "WORLD_PERPETUAL_WAR": GlobalTrait(
            id="WORLD_PERPETUAL_WAR",
            name="Perpetual War Economy",
            description="Oceania is perpetually at war (with Eurasia or Eastasia). War justifies scarcity, nationalism, and the Party's absolute authority.",
            category="economy",
            magnitude=TraitVector(value=0.7, inertia=0.8),
            affected_domains=["social", "psychological"],
        ),
    },
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_WINSTON", target_entity_id="ENT_JULIA", affinity=0.8, fear=0.1, power_dynamic=0.0, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_JULIA", target_entity_id="ENT_WINSTON", affinity=0.7, fear=0.1, power_dynamic=0.0, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_WINSTON", target_entity_id="ENT_OBRIEN", affinity=0.3, fear=0.2, power_dynamic=-0.5, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_OBRIEN", target_entity_id="ENT_WINSTON", affinity=-0.3, fear=0.0, power_dynamic=0.8, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_WINSTON", target_entity_id="ENT_BIG_BROTHER", affinity=-0.7, fear=0.8, power_dynamic=-1.0, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_WINSTON", target_entity_id="ENT_CHARRINGTON", affinity=0.4, fear=0.0, power_dynamic=0.0, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_CHARRINGTON", target_entity_id="ENT_WINSTON", affinity=-0.5, fear=0.0, power_dynamic=0.6, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_WINSTON", target_entity_id="ENT_SYME", affinity=0.3, fear=0.0, power_dynamic=0.0, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_WINSTON", target_entity_id="ENT_PARSONS", affinity=0.1, fear=0.0, power_dynamic=0.1, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_JULIA", target_entity_id="ENT_OBRIEN", affinity=-0.2, fear=0.3, power_dynamic=-0.5, inertia=0.3),
    ],
)
