"""Persuasion — high-fidelity WorldStateV1 test fixture."""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait,
)

world_state = WorldStateV1(
    locations={
        "LOC_KELLYNCH_HALL": Location(name="Kellynch Hall", description="The Elliot family estate, being let due to financial troubles.",
            ambient_state={"decline": AmbientVector(value=0.7, volatility=0.3), "nostalgia": AmbientVector(value=0.6, volatility=0.3)}),
        "LOC_UPPERCROSS": Location(name="Uppercross", description="The Musgrove family estate where Anne visits Mary.",
            ambient_state={"warmth": AmbientVector(value=0.6, volatility=0.3)}),
        "LOC_LYME_REGIS": Location(name="Lyme Regis", description="Coastal town where Louisa's accident occurs.",
            ambient_state={"danger": AmbientVector(value=0.4, volatility=0.6)}),
        "LOC_BATH": Location(name="Bath", description="Fashionable city where the Elliots relocate.",
            ambient_state={"society": AmbientVector(value=0.7, volatility=0.3), "tension": AmbientVector(value=0.5, volatility=0.4)}),
        "LOC_CAMDEN_PLACE": Location(name="Camden Place", description="Sir Walter's rented lodgings in Bath.",
            ambient_state={"vanity": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_CONCERT_HALL": Location(name="Bath Concert Hall", description="Where Anne and Wentworth reconnect.",
            ambient_state={"tension": AmbientVector(value=0.6, volatility=0.4)}),
    },
    objects={
        "OBJ_LETTER": NarrativeObject(id="OBJ_LETTER", name="Wentworth's Letter",
            location_id="LOC_BATH", owner_id="ENT_WENTWORTH",
            properties={"state": "sealed", "content": "declaration_of_love"},
            affordances=[Affordance(action="declare_love", target_type="Entity"), Affordance(action="resolve_misunderstanding", target_type="Entity")]),
        "OBJ_NAVY_LIST": NarrativeObject(id="OBJ_NAVY_LIST", name="Navy List",
            location_id="LOC_KELLYNCH_HALL", owner_id="ENT_ANNE",
            properties={"state": "worn", "content": "wentworth_entry"},
            affordances=[Affordance(action="remind", target_type="Entity")]),
        "OBJ_COBB_WALL": NarrativeObject(id="OBJ_COBB_WALL", name="Lyme Cobb Wall",
            location_id="LOC_LYME_REGIS", owner_id=None,
            properties={"state": "slippery", "height": "dangerous"},
            affordances=[Affordance(action="injure", target_type="Entity")]),
    },
    entities={
        "ENT_ANNE": Entity(id="ENT_ANNE", name="Anne Elliot",
            location_id="LOC_KELLYNCH_HALL", status="healthy",
            traits={
                "constancy": TraitVector(value=0.9, inertia=0.7),
                "self_effacement": TraitVector(value=0.7, inertia=0.4),
                "intelligence": TraitVector(value=0.8, inertia=0.6),
                "regret": TraitVector(value=0.7, inertia=0.4),
                "hope": TraitVector(value=0.3, inertia=0.2),
            },
            beliefs=[
                Belief(target_id="ENT_WENTWORTH", perceived_state="Wentworth resents me for rejecting him", confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_LADY_RUSSELL", perceived_state="Lady Russell acted from genuine concern", confidence=0.7, inertia=0.5),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=300, triggered_by="EVT_WENTWORTH_ARRIVES",
                    traits={"regret": TraitVector(value=0.8, inertia=0.4), "hope": TraitVector(value=0.4, inertia=0.2)}),
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_LOUISA_FALLS",
                    traits={"self_effacement": TraitVector(value=0.5, inertia=0.4)},
                    beliefs_added=[Belief(target_id="ENT_WENTWORTH", perceived_state="Wentworth values my composure", confidence=0.6, inertia=0.3)]),
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_LETTER_RECEIVED",
                    traits={"hope": TraitVector(value=0.9, inertia=0.3), "regret": TraitVector(value=0.2, inertia=0.3)},
                    beliefs_invalidated=["ENT_WENTWORTH"]),
            ]),
        "ENT_WENTWORTH": Entity(id="ENT_WENTWORTH", name="Captain Frederick Wentworth",
            location_id="LOC_UPPERCROSS", status="healthy",
            traits={
                "pride": TraitVector(value=0.7, inertia=0.4),
                "resentment": TraitVector(value=0.6, inertia=0.3),
                "honour": TraitVector(value=0.8, inertia=0.6),
                "passion": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_ANNE", perceived_state="Anne was too weak to resist Lady Russell's persuasion", confidence=0.7, inertia=0.4),
                Belief(target_id="ENT_LOUISA", perceived_state="Louisa has the firmness Anne lacked", confidence=0.5, inertia=0.2),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_LOUISA_FALLS",
                    traits={"pride": TraitVector(value=0.5, inertia=0.4)},
                    beliefs_invalidated=["ENT_LOUISA", "ENT_ANNE"]),
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_WENTWORTH_JEALOUS",
                    traits={"resentment": TraitVector(value=0.3, inertia=0.3), "passion": TraitVector(value=0.8, inertia=0.4)}),
            ]),
        "ENT_LADY_RUSSELL": Entity(id="ENT_LADY_RUSSELL", name="Lady Russell",
            location_id="LOC_KELLYNCH_HALL", status="healthy",
            traits={
                "prudence": TraitVector(value=0.8, inertia=0.6),
                "class_consciousness": TraitVector(value=0.7, inertia=0.5),
                "protectiveness": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_WENTWORTH", perceived_state="Wentworth was unworthy of Anne's station", confidence=0.6, inertia=0.4),
                Belief(target_id="ENT_ELLIOT", perceived_state="Mr Elliot would be a fine match for Anne", confidence=0.7, inertia=0.3),
            ]),
        "ENT_LOUISA": Entity(id="ENT_LOUISA", name="Louisa Musgrove",
            location_id="LOC_UPPERCROSS", status="healthy",
            traits={
                "impetuosity": TraitVector(value=0.8, inertia=0.4),
                "cheerfulness": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_WENTWORTH", perceived_state="Wentworth admires my spirit", confidence=0.7, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_LOUISA_FALLS",
                    traits={"impetuosity": TraitVector(value=0.3, inertia=0.4)}, new_status="injured"),
            ]),
        "ENT_ELLIOT": Entity(id="ENT_ELLIOT", name="William Elliot",
            location_id="LOC_BATH", status="healthy",
            traits={
                "charm": TraitVector(value=0.8, inertia=0.5),
                "duplicity": TraitVector(value=0.8, inertia=0.5),
                "ambition": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_ANNE", perceived_state="Marrying Anne secures my inheritance", confidence=0.8, inertia=0.4),
            ]),
        "ENT_SIR_WALTER": Entity(id="ENT_SIR_WALTER", name="Sir Walter Elliot",
            location_id="LOC_CAMDEN_PLACE", status="healthy",
            traits={
                "vanity": TraitVector(value=0.9, inertia=0.7),
                "extravagance": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_ELLIOT", perceived_state="Mr Elliot is a worthy heir and connection", confidence=0.7, inertia=0.4),
            ]),
        "ENT_MRS_SMITH": Entity(id="ENT_MRS_SMITH", name="Mrs Smith",
            location_id="LOC_BATH", status="healthy",
            traits={
                "candour": TraitVector(value=0.7, inertia=0.5),
                "resilience": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_ELLIOT", perceived_state="Mr Elliot is a scheming deceiver", confidence=0.9, inertia=0.6),
            ]),
    },
    events=[
        EventNode(id="EVT_KELLYNCH_LET", fabula_time=100, syuzhet_index=1, event_type="outcome",
                  actor_ids=["ENT_SIR_WALTER"], target_ids=["ENT_ANNE"],
                  description="Sir Walter is forced to let Kellynch Hall due to debts."),
        EventNode(id="EVT_CROFTS_ARRIVE", fabula_time=200, syuzhet_index=2, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_ANNE"],
                  description="Admiral and Mrs Croft take Kellynch, bringing news of Wentworth."),
        EventNode(id="EVT_WENTWORTH_ARRIVES", fabula_time=300, syuzhet_index=3, event_type="outcome",
                  actor_ids=["ENT_WENTWORTH"], target_ids=["ENT_ANNE"],
                  description="Wentworth arrives at Uppercross, reuniting with Anne after eight years."),
        EventNode(id="EVT_WENTWORTH_FLIRTS_LOUISA", fabula_time=400, syuzhet_index=4, event_type="choice",
                  actor_ids=["ENT_WENTWORTH"], target_ids=["ENT_LOUISA"],
                  description="Wentworth pays marked attention to Louisa, praising her firmness."),
        EventNode(id="EVT_LYME_EXCURSION", fabula_time=500, syuzhet_index=5, event_type="outcome",
                  actor_ids=["ENT_WENTWORTH", "ENT_LOUISA", "ENT_ANNE"], target_ids=[],
                  description="The party travels to Lyme Regis for a seaside excursion."),
        EventNode(id="EVT_LOUISA_FALLS", fabula_time=600, syuzhet_index=6, event_type="outcome",
                  actor_ids=["ENT_LOUISA"], target_ids=["ENT_WENTWORTH"],
                  description="Louisa jumps from the Cobb wall and suffers a serious head injury."),
        EventNode(id="EVT_ANNE_TAKES_CHARGE", fabula_time=650, syuzhet_index=7, event_type="choice",
                  actor_ids=["ENT_ANNE"], target_ids=["ENT_WENTWORTH"],
                  description="Anne takes command during the crisis while others panic."),
        EventNode(id="EVT_MOVE_TO_BATH", fabula_time=700, syuzhet_index=8, event_type="outcome",
                  actor_ids=["ENT_ANNE"], target_ids=[],
                  description="Anne joins her father and sister at Camden Place in Bath."),
        EventNode(id="EVT_ELLIOT_COURTS_ANNE", fabula_time=800, syuzhet_index=9, event_type="choice",
                  actor_ids=["ENT_ELLIOT"], target_ids=["ENT_ANNE"],
                  description="Mr Elliot begins courting Anne with Lady Russell's encouragement."),
        EventNode(id="EVT_WENTWORTH_JEALOUS", fabula_time=900, syuzhet_index=10, event_type="outcome",
                  actor_ids=["ENT_WENTWORTH"], target_ids=["ENT_ELLIOT"],
                  description="Wentworth sees Elliot's attentions to Anne and feels jealousy."),
        EventNode(id="EVT_MRS_SMITH_REVEALS", fabula_time=950, syuzhet_index=11, event_type="revelation",
                  actor_ids=["ENT_MRS_SMITH"], target_ids=["ENT_ANNE"],
                  description="Mrs Smith reveals Mr Elliot's true mercenary character."),
        EventNode(id="EVT_LETTER_RECEIVED", fabula_time=1000, syuzhet_index=12, event_type="revelation",
                  actor_ids=["ENT_WENTWORTH"], target_ids=["ENT_ANNE"],
                  description="Wentworth writes his letter declaring he is half agony, half hope."),
        EventNode(id="EVT_REUNION", fabula_time=1100, syuzhet_index=13, event_type="outcome",
                  actor_ids=["ENT_ANNE", "ENT_WENTWORTH"], target_ids=[],
                  description="Anne and Wentworth reunite and become engaged."),
    ],
    causal_topology=[
        # chain_reaction
        CausalEdge(source_id="EVT_KELLYNCH_LET", target_id="EVT_CROFTS_ARRIVE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=100),
        CausalEdge(source_id="EVT_CROFTS_ARRIVE", target_id="EVT_WENTWORTH_ARRIVES",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200),
        CausalEdge(source_id="EVT_WENTWORTH_ARRIVES", target_id="EVT_WENTWORTH_FLIRTS_LOUISA",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=300),
        CausalEdge(source_id="EVT_WENTWORTH_FLIRTS_LOUISA", target_id="EVT_LYME_EXCURSION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=400),
        CausalEdge(source_id="EVT_LYME_EXCURSION", target_id="EVT_LOUISA_FALLS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500),
        CausalEdge(source_id="EVT_LOUISA_FALLS", target_id="EVT_ANNE_TAKES_CHARGE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600),
        CausalEdge(source_id="EVT_MOVE_TO_BATH", target_id="EVT_ELLIOT_COURTS_ANNE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=700),
        CausalEdge(source_id="EVT_ELLIOT_COURTS_ANNE", target_id="EVT_WENTWORTH_JEALOUS",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=800),
        CausalEdge(source_id="EVT_MRS_SMITH_REVEALS", target_id="EVT_LETTER_RECEIVED",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=950),
        CausalEdge(source_id="EVT_LETTER_RECEIVED", target_id="EVT_REUNION",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1000),
        # mutation
        CausalEdge(source_id="EVT_WENTWORTH_ARRIVES", target_id="ENT_ANNE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300, trait_target="regret", trait_delta=0.1),
        CausalEdge(source_id="EVT_LOUISA_FALLS", target_id="ENT_WENTWORTH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600, trait_target="pride", trait_delta=-0.2),
        CausalEdge(source_id="EVT_ANNE_TAKES_CHARGE", target_id="ENT_ANNE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=650, trait_target="self_effacement", trait_delta=-0.2),
        CausalEdge(source_id="EVT_LETTER_RECEIVED", target_id="ENT_ANNE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1000, trait_target="hope", trait_delta=0.6),
        CausalEdge(source_id="EVT_WENTWORTH_JEALOUS", target_id="ENT_WENTWORTH",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900, trait_target="resentment", trait_delta=-0.3),
        # mutation_social
        CausalEdge(source_id="EVT_LOUISA_FALLS", target_id="ENT_WENTWORTH",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600, trait_target="affinity", trait_delta=0.4, rel_counterpart_id="ENT_ANNE"),
        CausalEdge(source_id="EVT_ANNE_TAKES_CHARGE", target_id="ENT_WENTWORTH",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=650, trait_target="affinity", trait_delta=0.3, rel_counterpart_id="ENT_ANNE"),
        CausalEdge(source_id="EVT_MRS_SMITH_REVEALS", target_id="ENT_ANNE",
                   causality_type="mutation_social", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=950, trait_target="affinity", trait_delta=-0.6, rel_counterpart_id="ENT_ELLIOT"),
        # affordance_gate
        CausalEdge(source_id="OBJ_LETTER", target_id="EVT_LETTER_RECEIVED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1000),
        CausalEdge(source_id="ENT_LADY_RUSSELL", target_id="EVT_ELLIOT_COURTS_ANNE",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=800),
        CausalEdge(source_id="OBJ_COBB_WALL", target_id="EVT_LOUISA_FALLS",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=600),
        # ambient_propagation
        CausalEdge(source_id="LOC_BATH", target_id="ENT_ANNE",
                   causality_type="ambient_propagation", mechanism="social", evidence_strength="weak",
                   causal_force=3.0, fabula_time=700),
        CausalEdge(source_id="LOC_KELLYNCH_HALL", target_id="ENT_ANNE",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=100),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_KELLYNCH_HALL", target_id="LOC_UPPERCROSS"),
        SpatialEdge(source_id="LOC_UPPERCROSS", target_id="LOC_LYME_REGIS"),
        SpatialEdge(source_id="LOC_KELLYNCH_HALL", target_id="LOC_BATH"),
        SpatialEdge(source_id="LOC_BATH", target_id="LOC_CAMDEN_PLACE"),
        SpatialEdge(source_id="LOC_BATH", target_id="LOC_CONCERT_HALL"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_WENTWORTH", target_ids=["ENT_ANNE"], medium="letter", established_at_fabula=1000),
        InformationEdge(source_id="ENT_MRS_SMITH", target_ids=["ENT_ANNE"], medium="conversation", established_at_fabula=950),
        InformationEdge(source_id="ENT_LADY_RUSSELL", target_ids=["ENT_ANNE"], medium="conversation", established_at_fabula=100),
        InformationEdge(source_id="ENT_ANNE", target_ids=["ENT_WENTWORTH"], medium="overheard_conversation", established_at_fabula=900),
    ],
    world_traits={
        "WORLD_SOCIAL_RIGIDITY": GlobalTrait(
            id="WORLD_SOCIAL_RIGIDITY",
            name="Regency Social Class Rigidity",
            description="Regency-era class expectations constrain marriage, social interaction, and personal autonomy. Rank and connections determine life prospects.",
            category="social_structure",
            magnitude=TraitVector(value=0.7, inertia=0.75),
            affected_domains=["social", "emotional"],
        ),
        "WORLD_NAVAL_MERITOCRACY": GlobalTrait(
            id="WORLD_NAVAL_MERITOCRACY",
            name="Naval Meritocracy",
            description="The Navy offers an alternative social ladder based on merit and service rather than birth. Self-made men like Wentworth can rise.",
            category="social_structure",
            magnitude=TraitVector(value=0.5, inertia=0.6),
            affected_domains=["social", "psychological"],
        ),
    },
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_ANNE", target_entity_id="ENT_WENTWORTH", affinity=0.8, fear=0.1, power_dynamic=-0.2, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_WENTWORTH", target_entity_id="ENT_ANNE", affinity=0.3, fear=0.0, power_dynamic=0.2, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_ANNE", target_entity_id="ENT_LADY_RUSSELL", affinity=0.6, fear=0.0, power_dynamic=-0.3, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_LADY_RUSSELL", target_entity_id="ENT_WENTWORTH", affinity=-0.4, fear=0.0, power_dynamic=0.2, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_ELLIOT", target_entity_id="ENT_ANNE", affinity=0.3, fear=0.0, power_dynamic=0.2, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_ANNE", target_entity_id="ENT_ELLIOT", affinity=0.1, fear=0.1, power_dynamic=-0.1, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_WENTWORTH", target_entity_id="ENT_LOUISA", affinity=0.4, fear=0.0, power_dynamic=0.2, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_LOUISA", target_entity_id="ENT_WENTWORTH", affinity=0.7, fear=0.0, power_dynamic=-0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_SIR_WALTER", target_entity_id="ENT_ANNE", affinity=0.2, fear=0.0, power_dynamic=0.4, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_MRS_SMITH", target_entity_id="ENT_ANNE", affinity=0.7, fear=0.0, power_dynamic=-0.1, inertia=0.4),
    ],
)
