"""Reservoir Dogs — high-fidelity WorldStateV1 test fixture."""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_DINER": Location(name="Uncle Bob's Diner", description="Diner where the crew has breakfast before the heist.",
            ambient_state={"camaraderie": AmbientVector(value=0.6, volatility=0.3)}),
        "LOC_WAREHOUSE": Location(name="Rendezvous Warehouse", description="Abandoned warehouse where the crew regroups after the botched heist.",
            ambient_state={"tension": AmbientVector(value=0.8, volatility=0.4), "danger": AmbientVector(value=0.7, volatility=0.4)}),
        "LOC_DIAMOND_STORE": Location(name="Karina's Diamond Store", description="The jewelry store targeted for the heist.",
            ambient_state={"danger": AmbientVector(value=0.9, volatility=0.3)}),
        "LOC_JOE_OFFICE": Location(name="Joe Cabot's Office", description="Crime boss Joe Cabot's office where the heist is planned.",
            ambient_state={"authority": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_ORANGE_CAR": Location(name="Getaway Car", description="Car where Mr Orange is bleeding out after being shot.",
            ambient_state={"desperation": AmbientVector(value=0.8, volatility=0.4)}),
        "LOC_ORANGE_APARTMENT": Location(name="Mr Orange's Apartment", description="Undercover cop Freddy Newandyke's apartment.",
            ambient_state={"deception": AmbientVector(value=0.7, volatility=0.4)}),
    },
    objects={
        "OBJ_DIAMONDS": NarrativeObject(id="OBJ_DIAMONDS", name="Stolen Diamonds",
            location_id="LOC_DIAMOND_STORE", owner_id=None,
            properties={"state": "in_display_cases", "value": "high"},
            affordances=[Affordance(action="steal", target_type="Entity")]),
        "OBJ_GUNS": NarrativeObject(id="OBJ_GUNS", name="Crew's Weapons",
            location_id="LOC_WAREHOUSE", owner_id=None,
            properties={"state": "loaded"},
            affordances=[Affordance(action="threaten", target_type="Entity"), Affordance(action="kill", target_type="Entity")]),
        "OBJ_POLICE_BADGE": NarrativeObject(id="OBJ_POLICE_BADGE", name="Mr Orange's Police Badge",
            location_id="LOC_ORANGE_APARTMENT", owner_id="ENT_ORANGE",
            properties={"state": "hidden"},
            affordances=[Affordance(action="identify", target_type="Entity")]),
    },
    entities={
        "ENT_WHITE": Entity(id="ENT_WHITE", name="Mr White (Larry Dimmick)",
            location_id="LOC_WAREHOUSE", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.8, inertia=0.5),
                "professionalism": TraitVector(value=0.7, inertia=0.5),
                "compassion": TraitVector(value=0.6, inertia=0.3),
                "temper": TraitVector(value=0.5, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_ORANGE", perceived_state="Orange is a good kid who needs my protection", confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_BLONDE", perceived_state="Blonde is a psychopath who blew the heist", confidence=0.8, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_ORANGE_REVEALED",
                    traits={"loyalty": TraitVector(value=0.3, inertia=0.5)},
                    beliefs_invalidated=["ENT_ORANGE"]),
            ]),
        "ENT_ORANGE": Entity(id="ENT_ORANGE", name="Mr Orange (Freddy Newandyke)",
            location_id="LOC_WAREHOUSE", status="injured",
            traits={
                "deceit": TraitVector(value=0.6, inertia=0.3),
                "guilt": TraitVector(value=0.5, inertia=0.3),
                "courage": TraitVector(value=0.6, inertia=0.4),
                "pain": TraitVector(value=0.8, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_WHITE", perceived_state="White genuinely cares about me, making my betrayal worse", confidence=0.8, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=300, triggered_by="EVT_HEIST_GOES_WRONG",
                    traits={"pain": TraitVector(value=0.9, inertia=0.3)}, new_status="injured"),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_ORANGE_REVEALED",
                    traits={"guilt": TraitVector(value=0.9, inertia=0.3)}),
            ]),
        "ENT_BLONDE": Entity(id="ENT_BLONDE", name="Mr Blonde (Vic Vega)",
            location_id="LOC_WAREHOUSE", status="healthy",
            traits={
                "sadism": TraitVector(value=0.9, inertia=0.6),
                "loyalty_to_joe": TraitVector(value=0.8, inertia=0.5),
                "calm": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_JOE", perceived_state="Joe took care of me; I owe him everything", confidence=0.9, inertia=0.6),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_ORANGE_KILLS_BLONDE", new_status="dead"),
            ]),
        "ENT_PINK": Entity(id="ENT_PINK", name="Mr Pink",
            location_id="LOC_WAREHOUSE", status="healthy",
            traits={
                "self_preservation": TraitVector(value=0.9, inertia=0.6),
                "professionalism": TraitVector(value=0.8, inertia=0.5),
                "paranoia": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_JOE", perceived_state="Someone set us up, possibly from the inside", confidence=0.8, inertia=0.4),
            ]),
        "ENT_JOE": Entity(id="ENT_JOE", name="Joe Cabot",
            location_id="LOC_JOE_OFFICE", status="healthy",
            traits={
                "authority": TraitVector(value=0.9, inertia=0.6),
                "suspicion": TraitVector(value=0.7, inertia=0.5),
                "ruthlessness": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_ORANGE", perceived_state="Orange is the rat", confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_BLONDE", perceived_state="Blonde is loyal and proved it doing time", confidence=0.8, inertia=0.5),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_MEXICAN_STANDOFF", new_status="dead"),
            ]),
        "ENT_EDDIE": Entity(id="ENT_EDDIE", name="Nice Guy Eddie",
            location_id="LOC_JOE_OFFICE", status="healthy",
            traits={
                "loyalty_to_father": TraitVector(value=0.9, inertia=0.6),
                "volatility": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_JOE", perceived_state="Dad is always right", confidence=0.9, inertia=0.6),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_MEXICAN_STANDOFF", new_status="dead"),
            ]),
        "ENT_MARVIN": Entity(id="ENT_MARVIN", name="Officer Marvin Nash",
            location_id="LOC_WAREHOUSE", status="healthy",
            traits={
                "courage": TraitVector(value=0.5, inertia=0.3),
                "fear": TraitVector(value=0.7, inertia=0.3),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_BLONDE_TORTURES_COP",
                    traits={"fear": TraitVector(value=0.95, inertia=0.3)}, new_status="injured"),
            ]),
    },
    events=[
        EventNode(id="EVT_HEIST_PLANNED", fabula_time=100, syuzhet_index=1, event_type="choice",
                  actor_ids=["ENT_JOE"], target_ids=["ENT_WHITE", "ENT_ORANGE", "ENT_BLONDE", "ENT_PINK"],
                  description="Joe Cabot assembles the crew and plans the diamond heist."),
        EventNode(id="EVT_DINER_BREAKFAST", fabula_time=200, syuzhet_index=2, event_type="outcome",
                  actor_ids=["ENT_WHITE", "ENT_ORANGE", "ENT_BLONDE", "ENT_PINK"], target_ids=[],
                  description="The crew has breakfast at the diner; tipping debate reveals personalities."),
        EventNode(id="EVT_HEIST_GOES_WRONG", fabula_time=300, syuzhet_index=3, event_type="outcome",
                  actor_ids=["ENT_BLONDE"], target_ids=["ENT_WHITE", "ENT_ORANGE", "ENT_PINK"],
                  description="The heist goes wrong when Mr Blonde starts killing civilians; police arrive immediately."),
        EventNode(id="EVT_ORANGE_SHOT", fabula_time=350, syuzhet_index=4, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_ORANGE"],
                  description="Mr Orange is shot in the gut during the getaway."),
        EventNode(id="EVT_WAREHOUSE_REGROUP", fabula_time=400, syuzhet_index=5, event_type="outcome",
                  actor_ids=["ENT_WHITE", "ENT_PINK"], target_ids=[],
                  description="White and Pink regroup at the warehouse; Pink suspects a setup."),
        EventNode(id="EVT_BLONDE_TORTURES_COP", fabula_time=500, syuzhet_index=6, event_type="choice",
                  actor_ids=["ENT_BLONDE"], target_ids=["ENT_MARVIN"],
                  description="Mr Blonde tortures Officer Marvin Nash, cutting off his ear."),
        EventNode(id="EVT_ORANGE_KILLS_BLONDE", fabula_time=600, syuzhet_index=7, event_type="choice",
                  actor_ids=["ENT_ORANGE"], target_ids=["ENT_BLONDE"],
                  description="Mr Orange shoots and kills Mr Blonde to save the cop, revealing his loyalties."),
        EventNode(id="EVT_MEXICAN_STANDOFF", fabula_time=700, syuzhet_index=8, event_type="outcome",
                  actor_ids=["ENT_JOE", "ENT_EDDIE", "ENT_WHITE"], target_ids=["ENT_ORANGE"],
                  description="Joe accuses Orange of being the rat; three-way standoff ends with Joe, Eddie, and White all shot."),
        EventNode(id="EVT_ORANGE_REVEALED", fabula_time=750, syuzhet_index=9, event_type="revelation",
                  actor_ids=["ENT_ORANGE"], target_ids=["ENT_WHITE"],
                  description="Dying Orange confesses to White that he is an undercover cop."),
        EventNode(id="EVT_WHITE_KILLS_ORANGE", fabula_time=800, syuzhet_index=10, event_type="choice",
                  actor_ids=["ENT_WHITE"], target_ids=["ENT_ORANGE"],
                  description="White shoots Orange as police storm the warehouse."),
    ],
    causal_topology=[
        # chain_reaction
        CausalEdge(source_id="EVT_HEIST_PLANNED", target_id="EVT_DINER_BREAKFAST",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=100),
        CausalEdge(source_id="EVT_DINER_BREAKFAST", target_id="EVT_HEIST_GOES_WRONG",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200),
        CausalEdge(source_id="EVT_HEIST_GOES_WRONG", target_id="EVT_ORANGE_SHOT",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300),
        CausalEdge(source_id="EVT_ORANGE_SHOT", target_id="EVT_WAREHOUSE_REGROUP",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=350),
        CausalEdge(source_id="EVT_WAREHOUSE_REGROUP", target_id="EVT_BLONDE_TORTURES_COP",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=400),
        CausalEdge(source_id="EVT_BLONDE_TORTURES_COP", target_id="EVT_ORANGE_KILLS_BLONDE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500),
        CausalEdge(source_id="EVT_ORANGE_KILLS_BLONDE", target_id="EVT_MEXICAN_STANDOFF",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600),
        CausalEdge(source_id="EVT_MEXICAN_STANDOFF", target_id="EVT_ORANGE_REVEALED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=700),
        CausalEdge(source_id="EVT_ORANGE_REVEALED", target_id="EVT_WHITE_KILLS_ORANGE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=750),
        # mutation
        CausalEdge(source_id="EVT_ORANGE_SHOT", target_id="ENT_ORANGE",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=350, trait_target="pain", trait_delta=0.1),
        CausalEdge(source_id="EVT_BLONDE_TORTURES_COP", target_id="ENT_MARVIN",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=500, trait_target="fear", trait_delta=0.25),
        CausalEdge(source_id="EVT_ORANGE_REVEALED", target_id="ENT_WHITE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=750, trait_target="loyalty", trait_delta=-0.5),
        CausalEdge(source_id="EVT_ORANGE_REVEALED", target_id="ENT_ORANGE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=750, trait_target="guilt", trait_delta=0.4),
        # mutation_social
        CausalEdge(source_id="EVT_ORANGE_REVEALED", target_id="ENT_WHITE",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=10.0, fabula_time=750, trait_target="affinity", trait_delta=-0.9, rel_counterpart_id="ENT_ORANGE"),
        CausalEdge(source_id="EVT_HEIST_GOES_WRONG", target_id="ENT_WHITE",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300, trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_BLONDE"),
        CausalEdge(source_id="EVT_ORANGE_KILLS_BLONDE", target_id="ENT_ORANGE",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=600, trait_target="affinity", trait_delta=0.2, rel_counterpart_id="ENT_WHITE"),
        # affordance_gate
        CausalEdge(source_id="ENT_JOE", target_id="EVT_HEIST_PLANNED",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="ENT_BLONDE", target_id="EVT_HEIST_GOES_WRONG",
                   causality_type="affordance_gate", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300),
        CausalEdge(source_id="OBJ_GUNS", target_id="EVT_MEXICAN_STANDOFF",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700),
        # ambient_propagation
        CausalEdge(source_id="LOC_WAREHOUSE", target_id="ENT_PINK",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=400),
        CausalEdge(source_id="ENT_ORANGE", target_id="ENT_WHITE",
                   causality_type="ambient_propagation", mechanism="emotional", evidence_strength="weak",
                   causal_force=3.0, fabula_time=400),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_JOE_OFFICE", target_id="LOC_DINER"),
        SpatialEdge(source_id="LOC_DINER", target_id="LOC_DIAMOND_STORE"),
        SpatialEdge(source_id="LOC_DIAMOND_STORE", target_id="LOC_ORANGE_CAR"),
        SpatialEdge(source_id="LOC_ORANGE_CAR", target_id="LOC_WAREHOUSE"),
        SpatialEdge(source_id="LOC_ORANGE_APARTMENT", target_id="LOC_JOE_OFFICE"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_ORANGE", target_ids=["ENT_WHITE"], medium="confession", established_at_fabula=750),
        InformationEdge(source_id="ENT_JOE", target_ids=["ENT_EDDIE"], medium="conversation", established_at_fabula=100),
        InformationEdge(source_id="ENT_PINK", target_ids=["ENT_WHITE"], medium="argument", established_at_fabula=400),
    ],
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_WHITE", target_entity_id="ENT_ORANGE", affinity=0.7, fear=0.0, power_dynamic=0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_ORANGE", target_entity_id="ENT_WHITE", affinity=0.5, fear=0.1, power_dynamic=-0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_WHITE", target_entity_id="ENT_BLONDE", affinity=-0.5, fear=0.2, power_dynamic=0.0, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_WHITE", target_entity_id="ENT_PINK", affinity=0.2, fear=0.0, power_dynamic=0.0, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_BLONDE", target_entity_id="ENT_JOE", affinity=0.7, fear=0.1, power_dynamic=-0.4, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_JOE", target_entity_id="ENT_BLONDE", affinity=0.5, fear=0.0, power_dynamic=0.4, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_JOE", target_entity_id="ENT_ORANGE", affinity=-0.3, fear=0.0, power_dynamic=0.5, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_EDDIE", target_entity_id="ENT_JOE", affinity=0.8, fear=0.1, power_dynamic=-0.5, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_PINK", target_entity_id="ENT_JOE", affinity=0.1, fear=0.2, power_dynamic=-0.4, inertia=0.3),
    ],
)
