"""Wuthering Heights — high-fidelity WorldStateV1 test fixture.

Quality checklist (all five causality modalities, varied force/evidence,
trait_target/trait_delta, state_timeline, rich beliefs, info edges, constants).
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_WUTHERING_HEIGHTS": Location(name="Wuthering Heights",
            description="The Earnshaw farmhouse on the wild Yorkshire moors.",
            ambient_state={"wildness": AmbientVector(value=0.9, volatility=0.3),
                           "cruelty": AmbientVector(value=0.6, volatility=0.4)}),
        "LOC_THRUSHCROSS_GRANGE": Location(name="Thrushcross Grange",
            description="The Linton family's refined manor across the moors.",
            ambient_state={"refinement": AmbientVector(value=0.8, volatility=0.2),
                           "fragility": AmbientVector(value=0.5, volatility=0.3)}),
        "LOC_MOORS": Location(name="The Moors",
            description="Vast Yorkshire moorland connecting the two houses.",
            ambient_state={"freedom": AmbientVector(value=0.8, volatility=0.3),
                           "harshness": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_LIVERPOOL": Location(name="Liverpool Streets",
            description="Where Mr Earnshaw finds the orphan Heathcliff.",
            ambient_state={"poverty": AmbientVector(value=0.8, volatility=0.3)}),
        "LOC_UNKNOWN_CITY": Location(name="Unknown City",
            description="Where Heathcliff disappears for three years and returns wealthy.",
            ambient_state={"mystery": AmbientVector(value=0.7, volatility=0.4)}),
        "LOC_KIRKYARD": Location(name="Gimmerton Kirkyard",
            description="The churchyard where Catherine and Heathcliff are eventually buried.",
            ambient_state={"peace": AmbientVector(value=0.5, volatility=0.2),
                           "haunting": AmbientVector(value=0.6, volatility=0.4)}),
        "LOC_GARDEN": Location(name="Thrushcross Garden",
            description="The garden of Thrushcross Grange where young Cathy plays.",
            ambient_state={"warmth": AmbientVector(value=0.6, volatility=0.3)}),
    },
    objects={
        "OBJ_DIARY": NarrativeObject(id="OBJ_DIARY", name="Catherine's Diary",
            location_id="LOC_WUTHERING_HEIGHTS", owner_id="ENT_CATHERINE",
            properties={"state": "marginalia", "content": "childhood_confessions"},
            affordances=[Affordance(action="inform", target_type="Entity")]),
        "OBJ_RIDING_CROP": NarrativeObject(id="OBJ_RIDING_CROP", name="Hindley's Riding Crop",
            location_id="LOC_WUTHERING_HEIGHTS", owner_id="ENT_HINDLEY",
            properties={"state": "worn"},
            affordances=[Affordance(action="beat", target_type="Entity")]),
        "OBJ_KEY": NarrativeObject(id="OBJ_KEY", name="Nelly's Household Keys",
            location_id="LOC_THRUSHCROSS_GRANGE", owner_id="ENT_NELLY",
            properties={"state": "iron"},
            affordances=[Affordance(action="lock_unlock", target_type="Location")]),
        "OBJ_LOCKET": NarrativeObject(id="OBJ_LOCKET", name="Catherine's Locket",
            location_id=None, owner_id="ENT_CATHERINE",
            properties={"state": "contains_hair", "significance": "divided_love"},
            affordances=[Affordance(action="symbolise", target_type="Entity")]),
    },
    entities={
        "ENT_HEATHCLIFF": Entity(id="ENT_HEATHCLIFF", name="Heathcliff",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "passion": TraitVector(value=0.9, inertia=0.6),
                "cruelty": TraitVector(value=0.3, inertia=0.2),
                "obsession": TraitVector(value=0.7, inertia=0.4),
                "resilience": TraitVector(value=0.8, inertia=0.5),
                "vindictiveness": TraitVector(value=0.3, inertia=0.2),
            },
            beliefs=[
                Belief(target_id="ENT_CATHERINE", perceived_state="Catherine is my soul",
                       confidence=0.95, inertia=0.7),
                Belief(target_id="ENT_HINDLEY", perceived_state="Hindley destroyed my childhood",
                       confidence=0.9, inertia=0.6),
            ],
            constants=["foundling", "dark_outsider"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_HEATHCLIFF_DEGRADED",
                    traits={"cruelty": TraitVector(value=0.4, inertia=0.3),
                            "vindictiveness": TraitVector(value=0.5, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_CATHERINE_MARRIES_EDGAR",
                    traits={"obsession": TraitVector(value=0.9, inertia=0.5),
                            "vindictiveness": TraitVector(value=0.7, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_CATHERINE_DIES",
                    traits={"cruelty": TraitVector(value=0.8, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_HEATHCLIFF_DIES",
                    status="dead"),
            ]),
        "ENT_CATHERINE": Entity(id="ENT_CATHERINE", name="Catherine Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "wildness": TraitVector(value=0.9, inertia=0.5),
                "passion": TraitVector(value=0.9, inertia=0.5),
                "vanity": TraitVector(value=0.5, inertia=0.3),
                "self_destruction": TraitVector(value=0.4, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF", perceived_state="Heathcliff is more myself than I am",
                       confidence=0.95, inertia=0.7),
                Belief(target_id="ENT_EDGAR", perceived_state="Edgar offers respectability and comfort",
                       confidence=0.7, inertia=0.4),
            ],
            constants=["earnshaw_heir"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_CATHERINE_CHOOSES_EDGAR",
                    traits={"vanity": TraitVector(value=0.7, inertia=0.3)},
                    location_id="LOC_THRUSHCROSS_GRANGE"),
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_CONFRONTATION",
                    traits={"self_destruction": TraitVector(value=0.8, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_CATHERINE_DIES",
                    status="dead"),
            ]),
        "ENT_EDGAR": Entity(id="ENT_EDGAR", name="Edgar Linton",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "gentleness": TraitVector(value=0.8, inertia=0.5),
                "jealousy": TraitVector(value=0.4, inertia=0.3),
                "devotion": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_CATHERINE", perceived_state="Catherine chose me over Heathcliff",
                       confidence=0.7, inertia=0.4),
                Belief(target_id="ENT_HEATHCLIFF", perceived_state="Heathcliff is a dangerous brute",
                       confidence=0.8, inertia=0.5),
            ],
            constants=["linton_heir"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_CONFRONTATION",
                    traits={"jealousy": TraitVector(value=0.7, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_CATHERINE_DIES",
                    traits={"devotion": TraitVector(value=0.9, inertia=0.5)}),
            ]),
        "ENT_HINDLEY": Entity(id="ENT_HINDLEY", name="Hindley Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "jealousy": TraitVector(value=0.8, inertia=0.5),
                "cruelty": TraitVector(value=0.6, inertia=0.4),
                "alcoholism": TraitVector(value=0.4, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF", perceived_state="Heathcliff stole my father's love",
                       confidence=0.9, inertia=0.6),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_HEATHCLIFF_DEGRADED",
                    traits={"alcoholism": TraitVector(value=0.7, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_HINDLEY_DIES",
                    status="dead"),
            ]),
        "ENT_NELLY": Entity(id="ENT_NELLY", name="Nelly Dean",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "pragmatism": TraitVector(value=0.8, inertia=0.5),
                "loyalty": TraitVector(value=0.7, inertia=0.5),
                "judgement": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_CATHERINE", perceived_state="Catherine is self-destructive but I love her",
                       confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_HEATHCLIFF", perceived_state="Heathcliff brings ruin on everyone",
                       confidence=0.8, inertia=0.5),
            ],
            constants=["servant", "narrator"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_CATHERINE_DIES",
                    traits={"loyalty": TraitVector(value=0.8, inertia=0.5)}),
            ]),
        "ENT_ISABELLA": Entity(id="ENT_ISABELLA", name="Isabella Linton",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "naivety": TraitVector(value=0.7, inertia=0.4),
                "romanticism": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF", perceived_state="Heathcliff is a romantic hero",
                       confidence=0.6, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_ISABELLA_ELOPES",
                    traits={"naivety": TraitVector(value=0.3, inertia=0.4)},
                    location_id="LOC_WUTHERING_HEIGHTS",
                    beliefs_invalidated=["ENT_HEATHCLIFF"],
                    beliefs_added=[Belief(target_id="ENT_HEATHCLIFF",
                        perceived_state="Heathcliff is a monster who trapped me",
                        confidence=0.9, inertia=0.5, established_at_fabula=900)]),
            ]),
        "ENT_HARETON": Entity(id="ENT_HARETON", name="Hareton Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "roughness": TraitVector(value=0.7, inertia=0.4),
                "goodness": TraitVector(value=0.6, inertia=0.4),
                "loyalty": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF", perceived_state="Heathcliff is my master and tormentor",
                       confidence=0.7, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1500, triggered_by="EVT_CATHY_HARETON_LOVE",
                    traits={"roughness": TraitVector(value=0.4, inertia=0.4),
                            "goodness": TraitVector(value=0.8, inertia=0.4)}),
            ]),
        "ENT_CATHY_LINTON": Entity(id="ENT_CATHY_LINTON", name="Cathy Linton",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "spirit": TraitVector(value=0.8, inertia=0.4),
                "compassion": TraitVector(value=0.7, inertia=0.4),
                "stubbornness": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_HARETON", perceived_state="Hareton is rough but has a good heart",
                       confidence=0.6, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1400, triggered_by="EVT_LINTON_DIES",
                    traits={"spirit": TraitVector(value=0.6, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=1500, triggered_by="EVT_CATHY_HARETON_LOVE",
                    traits={"spirit": TraitVector(value=0.8, inertia=0.4),
                            "compassion": TraitVector(value=0.8, inertia=0.4)}),
            ]),
        "ENT_LOCKWOOD": Entity(id="ENT_LOCKWOOD", name="Mr Lockwood",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "curiosity": TraitVector(value=0.7, inertia=0.4),
                "naivety": TraitVector(value=0.6, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF", perceived_state="My landlord is a strange recluse",
                       confidence=0.6, inertia=0.3),
            ]),
        "ENT_LINTON": Entity(id="ENT_LINTON", name="Linton Heathcliff",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "frailty": TraitVector(value=0.95, inertia=0.6),
                "petulance": TraitVector(value=0.85, inertia=0.5),
                "cowardice": TraitVector(value=0.8, inertia=0.5),
                "self_pity": TraitVector(value=0.85, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF", perceived_state="My father terrifies me but I must obey",
                       confidence=0.9, inertia=0.6),
                Belief(target_id="ENT_CATHY_LINTON", perceived_state="Cathy will pity me into marrying me",
                       confidence=0.7, inertia=0.4),
            ],
            constants=["heathcliff_son", "linton_heir"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_CATHY_FORCED_MARRIAGE",
                    traits={"frailty": TraitVector(value=1.0, inertia=0.7)},
                    location_id="LOC_WUTHERING_HEIGHTS"),
                EntityStateSnapshot(fabula_time=1400, triggered_by="EVT_LINTON_DIES",
                    status="dead"),
            ]),
    },
    events=[
        EventNode(id="EVT_HEATHCLIFF_ARRIVES", fabula_time=100, syuzhet_index=1, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_HEATHCLIFF"],
                  description="Mr Earnshaw brings the orphan Heathcliff home from Liverpool."),
        EventNode(id="EVT_CHILDHOOD_BOND", fabula_time=200, syuzhet_index=2, event_type="outcome",
                  actor_ids=["ENT_HEATHCLIFF", "ENT_CATHERINE"], target_ids=[],
                  description="Heathcliff and Catherine grow up inseparable on the moors."),
        EventNode(id="EVT_EARNSHAW_DIES", fabula_time=300, syuzhet_index=3, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_HINDLEY"],
                  description="Mr Earnshaw dies; Hindley becomes master and degrades Heathcliff."),
        EventNode(id="EVT_CATHY_INJURED_AT_GRANGE", fabula_time=400, syuzhet_index=4, event_type="outcome",
                  actor_ids=["ENT_CATHERINE", "ENT_HEATHCLIFF"], target_ids=["ENT_EDGAR"],
                  description="Catherine is bitten by the Lintons' dog and stays at the Grange for weeks."),
        EventNode(id="EVT_HEATHCLIFF_DEGRADED", fabula_time=500, syuzhet_index=5, event_type="outcome",
                  actor_ids=["ENT_HINDLEY"], target_ids=["ENT_HEATHCLIFF"],
                  description="Hindley degrades Heathcliff to a servant; Heathcliff vows revenge."),
        EventNode(id="EVT_CATHERINE_CHOOSES_EDGAR", fabula_time=600, syuzhet_index=6, event_type="choice",
                  actor_ids=["ENT_CATHERINE"], target_ids=["ENT_EDGAR"],
                  description="Catherine tells Nelly she will marry Edgar, though her soul is Heathcliff's."),
        EventNode(id="EVT_HEATHCLIFF_DISAPPEARS", fabula_time=650, syuzhet_index=7, event_type="outcome",
                  actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Heathcliff overhears Catherine's remark and disappears for three years."),
        EventNode(id="EVT_CATHERINE_MARRIES_EDGAR", fabula_time=700, syuzhet_index=8, event_type="outcome",
                  actor_ids=["ENT_CATHERINE", "ENT_EDGAR"], target_ids=[],
                  description="Catherine marries Edgar Linton and moves to Thrushcross Grange."),
        EventNode(id="EVT_HEATHCLIFF_RETURNS", fabula_time=800, syuzhet_index=9, event_type="outcome",
                  actor_ids=["ENT_HEATHCLIFF"], target_ids=["ENT_CATHERINE"],
                  description="Heathcliff returns wealthy and begins his campaign of revenge."),
        EventNode(id="EVT_ISABELLA_ELOPES", fabula_time=900, syuzhet_index=10, event_type="choice",
                  actor_ids=["ENT_ISABELLA"], target_ids=["ENT_HEATHCLIFF"],
                  description="Isabella elopes with Heathcliff; he marries her to torment Edgar."),
        EventNode(id="EVT_CONFRONTATION", fabula_time=1000, syuzhet_index=11, event_type="outcome",
                  actor_ids=["ENT_HEATHCLIFF", "ENT_EDGAR"], target_ids=["ENT_CATHERINE"],
                  description="Heathcliff and Edgar confront each other; Catherine's mental health shatters."),
        EventNode(id="EVT_CATHERINE_DIES", fabula_time=1100, syuzhet_index=12, event_type="outcome",
                  actor_ids=["ENT_CATHERINE"], target_ids=["ENT_HEATHCLIFF", "ENT_EDGAR"],
                  description="Catherine dies giving birth to Cathy; Heathcliff howls for her ghost to haunt him."),
        EventNode(id="EVT_HINDLEY_DIES", fabula_time=1200, syuzhet_index=13, event_type="outcome",
                  actor_ids=["ENT_HINDLEY"], target_ids=["ENT_HEATHCLIFF"],
                  description="Hindley dies; Heathcliff takes possession of Wuthering Heights."),
        EventNode(id="EVT_HEATHCLIFF_ENSLAVES_HARETON", fabula_time=1250, syuzhet_index=14,
                  event_type="outcome",
                  actor_ids=["ENT_HEATHCLIFF"], target_ids=["ENT_HARETON"],
                  description="Heathcliff raises Hareton as a degraded servant, mirroring his own youth."),
        EventNode(id="EVT_CATHY_FORCED_MARRIAGE", fabula_time=1300, syuzhet_index=15, event_type="choice",
                  actor_ids=["ENT_HEATHCLIFF"], target_ids=["ENT_CATHY_LINTON"],
                  description="Heathcliff forces young Cathy to marry his sickly son Linton."),
        EventNode(id="EVT_LINTON_DIES", fabula_time=1400, syuzhet_index=16, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_CATHY_LINTON"],
                  description="Linton Heathcliff dies; Cathy is trapped at Wuthering Heights."),
        EventNode(id="EVT_CATHY_HARETON_LOVE", fabula_time=1500, syuzhet_index=17, event_type="outcome",
                  actor_ids=["ENT_CATHY_LINTON", "ENT_HARETON"], target_ids=[],
                  description="Cathy teaches Hareton to read; they fall in love, echoing the first generation."),
        EventNode(id="EVT_HEATHCLIFF_DIES", fabula_time=1600, syuzhet_index=18, event_type="outcome",
                  actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Heathcliff starves himself to death, claiming he sees Catherine's ghost."),
    ],
    causal_topology=[
        # chain_reaction (13)
        CausalEdge(source_id="EVT_HEATHCLIFF_ARRIVES", target_id="EVT_CHILDHOOD_BOND",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="EVT_CHILDHOOD_BOND", target_id="EVT_EARNSHAW_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=200),
        CausalEdge(source_id="EVT_EARNSHAW_DIES", target_id="EVT_HEATHCLIFF_DEGRADED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300),
        CausalEdge(source_id="EVT_CATHY_INJURED_AT_GRANGE", target_id="EVT_CATHERINE_CHOOSES_EDGAR",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=400),
        CausalEdge(source_id="EVT_HEATHCLIFF_DEGRADED", target_id="EVT_CATHERINE_CHOOSES_EDGAR",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500),
        CausalEdge(source_id="EVT_CATHERINE_CHOOSES_EDGAR", target_id="EVT_HEATHCLIFF_DISAPPEARS",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=600),
        CausalEdge(source_id="EVT_HEATHCLIFF_DISAPPEARS", target_id="EVT_CATHERINE_MARRIES_EDGAR",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=650),
        CausalEdge(source_id="EVT_CATHERINE_MARRIES_EDGAR", target_id="EVT_HEATHCLIFF_RETURNS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700),
        CausalEdge(source_id="EVT_HEATHCLIFF_RETURNS", target_id="EVT_ISABELLA_ELOPES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=800),
        CausalEdge(source_id="EVT_ISABELLA_ELOPES", target_id="EVT_CONFRONTATION",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900),
        CausalEdge(source_id="EVT_CONFRONTATION", target_id="EVT_CATHERINE_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1000),
        CausalEdge(source_id="EVT_CATHERINE_DIES", target_id="EVT_HINDLEY_DIES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1100),
        CausalEdge(source_id="EVT_CATHY_HARETON_LOVE", target_id="EVT_HEATHCLIFF_DIES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500),
        # mutation (7)
        CausalEdge(source_id="EVT_HEATHCLIFF_DEGRADED", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500, trait_target="vindictiveness", trait_delta=0.2),
        CausalEdge(source_id="EVT_CATHERINE_MARRIES_EDGAR", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=700, trait_target="obsession", trait_delta=0.2),
        CausalEdge(source_id="EVT_CATHERINE_DIES", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1100, trait_target="cruelty", trait_delta=0.5),
        CausalEdge(source_id="EVT_CATHERINE_CHOOSES_EDGAR", target_id="ENT_CATHERINE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=600, trait_target="vanity", trait_delta=0.2),
        CausalEdge(source_id="EVT_CONFRONTATION", target_id="ENT_CATHERINE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000, trait_target="self_destruction", trait_delta=0.4),
        CausalEdge(source_id="EVT_ISABELLA_ELOPES", target_id="ENT_ISABELLA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900, trait_target="naivety", trait_delta=-0.4),
        CausalEdge(source_id="EVT_CATHY_HARETON_LOVE", target_id="ENT_HARETON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1500, trait_target="roughness", trait_delta=-0.3),
        # mutation_social (4)
        CausalEdge(source_id="EVT_CATHERINE_MARRIES_EDGAR", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=700,
                   trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_EDGAR"),
        CausalEdge(source_id="EVT_ISABELLA_ELOPES", target_id="ENT_EDGAR",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900,
                   trait_target="affinity", trait_delta=-0.4, rel_counterpart_id="ENT_HEATHCLIFF"),
        CausalEdge(source_id="EVT_CATHY_HARETON_LOVE", target_id="ENT_CATHY_LINTON",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500,
                   trait_target="affinity", trait_delta=0.6, rel_counterpart_id="ENT_HARETON"),
        CausalEdge(source_id="EVT_HEATHCLIFF_DEGRADED", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500,
                   trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_HINDLEY"),
        # affordance_gate (3)
        CausalEdge(source_id="OBJ_RIDING_CROP", target_id="EVT_HEATHCLIFF_DEGRADED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=6.0, fabula_time=500),
        CausalEdge(source_id="OBJ_DIARY", target_id="EVT_CHILDHOOD_BOND",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=200),
        CausalEdge(source_id="ENT_NELLY", target_id="EVT_CATHERINE_CHOOSES_EDGAR",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=600),
        # ambient_propagation (2)
        CausalEdge(source_id="LOC_MOORS", target_id="ENT_HEATHCLIFF",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=200),
        CausalEdge(source_id="LOC_WUTHERING_HEIGHTS", target_id="ENT_HARETON",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=1250),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_WUTHERING_HEIGHTS", target_id="LOC_MOORS"),
        SpatialEdge(source_id="LOC_MOORS", target_id="LOC_THRUSHCROSS_GRANGE"),
        SpatialEdge(source_id="LOC_THRUSHCROSS_GRANGE", target_id="LOC_GARDEN"),
        SpatialEdge(source_id="LOC_WUTHERING_HEIGHTS", target_id="LOC_KIRKYARD"),
        SpatialEdge(source_id="LOC_THRUSHCROSS_GRANGE", target_id="LOC_KIRKYARD"),
        SpatialEdge(source_id="LOC_LIVERPOOL", target_id="LOC_WUTHERING_HEIGHTS"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_NELLY", target_ids=["ENT_LOCKWOOD"],
                        medium="narration", established_at_fabula=100),
        InformationEdge(source_id="ENT_CATHERINE", target_ids=["ENT_NELLY"],
                        medium="confession", established_at_fabula=600),
        InformationEdge(source_id="ENT_ISABELLA", target_ids=["ENT_NELLY"],
                        medium="letter", established_at_fabula=900),
        InformationEdge(source_id="ENT_NELLY", target_ids=["ENT_EDGAR"],
                        medium="report", established_at_fabula=800),
        InformationEdge(source_id="OBJ_DIARY", target_ids=["ENT_LOCKWOOD"],
                        medium="reading", established_at_fabula=100),
        InformationEdge(source_id="ENT_LINTON", target_ids=["ENT_CATHY_LINTON"],
                        medium="smuggled_letters", is_encrypted=True,
                        established_at_fabula=1250, terminated_at_fabula=1400),
        InformationEdge(source_id="ENT_HEATHCLIFF", target_ids=["ENT_LINTON"],
                        medium="coercive_dictation", established_at_fabula=1280),
        InformationEdge(source_id="ENT_CATHY_LINTON", target_ids=["ENT_NELLY"],
                        medium="smuggled_note", is_encrypted=True,
                        established_at_fabula=1350),
        InformationEdge(source_id="ENT_HEATHCLIFF", target_ids=["ENT_NELLY"],
                        medium="deathbed_confession", established_at_fabula=1600),
    ],
    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_MOOR_ISOLATION": GlobalTrait(
            id="WORLD_MOOR_ISOLATION",
            name="Yorkshire Moor Isolation",
            description="The remote, wind-blasted moorland traps characters in claustrophobic proximity, intensifying passions and grudges across generations.",
            category="environment",
            magnitude=TraitVector(value=0.85, inertia=0.8),
            affected_domains=["psychological", "social"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=600, triggered_by="EVT_HEATHCLIFF_RETURNS",
                    magnitude=TraitVector(value=0.9, inertia=0.85),
                    description="Heathcliff's return to the moor reactivates old obsessions in the confined landscape."),
            ],
        ),
        "WORLD_CLASS_BRUTALITY": GlobalTrait(
            id="WORLD_CLASS_BRUTALITY",
            name="Class-Based Cruelty",
            description="The rigid class system of Georgian-Victorian England enables the systematic degradation of those without property or name.",
            category="social_structure",
            magnitude=TraitVector(value=0.8, inertia=0.7),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=500, triggered_by="EVT_HEATHCLIFF_DEGRADED",
                    magnitude=TraitVector(value=0.9, inertia=0.8),
                    description="Hindley strips Heathcliff of education and status, planting the seeds of revenge."),
            ],
        ),
    },
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_CATHERINE",
                         affinity=0.95, fear=0.0, power_dynamic=0.0, inertia=0.7),
        RelationshipEdge(source_entity_id="ENT_CATHERINE", target_entity_id="ENT_HEATHCLIFF",
                         affinity=0.9, fear=0.1, power_dynamic=0.0, inertia=0.7),
        RelationshipEdge(source_entity_id="ENT_CATHERINE", target_entity_id="ENT_EDGAR",
                         affinity=0.6, fear=0.0, power_dynamic=0.1, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_EDGAR", target_entity_id="ENT_CATHERINE",
                         affinity=0.8, fear=0.0, power_dynamic=-0.1, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_EDGAR",
                         affinity=-0.8, fear=0.0, power_dynamic=0.2, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_EDGAR", target_entity_id="ENT_HEATHCLIFF",
                         affinity=-0.7, fear=0.3, power_dynamic=-0.2, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_HINDLEY",
                         affinity=-0.8, fear=0.0, power_dynamic=0.3, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_HINDLEY", target_entity_id="ENT_HEATHCLIFF",
                         affinity=-0.8, fear=0.2, power_dynamic=-0.3, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_ISABELLA", target_entity_id="ENT_HEATHCLIFF",
                         affinity=0.3, fear=0.4, power_dynamic=-0.5, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_ISABELLA",
                         affinity=-0.5, fear=0.0, power_dynamic=0.5, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_CATHY_LINTON", target_entity_id="ENT_HARETON",
                         affinity=0.5, fear=0.0, power_dynamic=0.1, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_HARETON", target_entity_id="ENT_CATHY_LINTON",
                         affinity=0.5, fear=0.1, power_dynamic=-0.1, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_HARETON",
                         affinity=-0.3, fear=0.0, power_dynamic=0.6, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_LINTON",
                         affinity=-0.6, fear=0.0, power_dynamic=0.8, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_LINTON", target_entity_id="ENT_HEATHCLIFF",
                         affinity=-0.4, fear=0.85, power_dynamic=-0.8, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_LINTON", target_entity_id="ENT_CATHY_LINTON",
                         affinity=0.4, fear=0.2, power_dynamic=-0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_CATHY_LINTON", target_entity_id="ENT_LINTON",
                         affinity=0.3, fear=0.0, power_dynamic=0.2, inertia=0.3,
                         last_updated_fabula=1300),
        RelationshipEdge(source_entity_id="ENT_CATHY_LINTON", target_entity_id="ENT_HEATHCLIFF",
                         affinity=-0.7, fear=0.6, power_dynamic=-0.6, inertia=0.4,
                         last_updated_fabula=1300),
        RelationshipEdge(source_entity_id="ENT_NELLY", target_entity_id="ENT_LOCKWOOD",
                         affinity=0.5, fear=0.0, power_dynamic=-0.1, inertia=0.3),
    ],
)
