"""
Step 10 — LLM Rendering (The Generation Step).

The Large Language Model operates strictly as a **renderer**.  It takes the
Semantic Prompt Injection (the mathematical guardrails and constraints
generated by the DirectiveAssembler in Step 9) and translates them into
natural-language prose.

The generation step is conditioned on query type:
  - Observation  → neutral scene rendering from ego-graph state
  - Intervention → describe the physical mechanism of a do-operator state change
  - Counterfactual → weave the "what-if" into character monologue / narration
  - Directive     → maximise a specific narrative/emotional effect per CreativeBrief

For Directive queries, the 10 target effects each trigger distinct rendering
strategies (pacing, sensory focus, tonal arc, POV lock, etc.) that are
encoded in the ``RenderingDirective`` attached to the ``CreativeBrief``.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field
from pydantic_ai import Agent, NativeOutput, RunContext

from shadow_loom.directive_assembly import (
    AbductionTruth,
    CausalAttribution,
    ConstraintBlock,
    CounterfactualBranch,
    CreativeBrief,
    EntanglementPair,
    InterventionMechanism,
    RenderingDirective,
    ThreatProximity,
)
from shadow_loom.models import WorldStateV1
from shadow_loom.query_models import (
    CounterfactualQuery,
    DirectiveQuery,
    InterventionQuery,
    ObservationQuery,
    UserRequest,
)

logger = logging.getLogger(__name__)

_PROMPTS_DIR = Path(__file__).resolve().parent / "prompts"
_OLLAMA_BASE_URL = "http://localhost:11434/v1/"


# =====================================================================
# Configuration
# =====================================================================

class GenerationConfig(BaseModel):
    """Runtime configuration for the generation step."""
    model: str = Field(
        default="ollama:qwen3.6:27b",
        description="PydanticAI model string.",
    )
    output_retries: int = Field(
        default=3,
        description="Max retries for output validation.",
    )
    max_tokens: int = Field(
        default=4096,
        description="Maximum tokens in the generated prose.",
    )
    temperature: float = Field(
        default=0.7,
        description="Sampling temperature for creative prose.",
    )


# =====================================================================
# Output Models
# =====================================================================

class GeneratedScene(BaseModel):
    """The structured output of the generation step."""
    prose: str = Field(
        description="The rendered prose passage.",
    )
    pov_entity: Optional[str] = Field(
        default=None,
        description="The entity whose perspective anchors the prose.",
    )
    rendering_mode: str = Field(
        default="observation",
        description="The rendering strategy that was applied.",
    )
    constraints_honoured: List[str] = Field(
        default_factory=list,
        description=(
            "IDs or summaries of hard constraints that were satisfied. "
            "Used by the NarrativeAuditor for structural validation."
        ),
    )
    constraints_violated: List[str] = Field(
        default_factory=list,
        description="Any hard constraints that could not be fully satisfied.",
    )


# =====================================================================
# Dependencies
# =====================================================================

class _GenerationDeps(BaseModel):
    """Injected context for the generation agent."""
    model_config = {"protected_namespaces": ()}
    rendering_prompt: str = Field(
        description="The fully assembled semantic prompt injection.",
    )


# =====================================================================
# Prompt Assembly — translates CreativeBrief → text prompt
# =====================================================================

def _load_prompt(filename: str) -> str:
    path = _PROMPTS_DIR / filename
    if not path.exists():
        raise FileNotFoundError(f"Prompt file not found: {path}")
    return path.read_text(encoding="utf-8")


def _resolve_model(model_str: str):
    if model_str.startswith("ollama:"):
        base_url = os.environ.get("OLLAMA_BASE_URL", _OLLAMA_BASE_URL)
        model_name = model_str.split(":", 1)[1]
        from pydantic_ai.models.ollama import OllamaModel
        from pydantic_ai.providers.ollama import OllamaProvider
        return OllamaModel(model_name, provider=OllamaProvider(base_url=base_url))
    return model_str


def _format_constraints(constraints: List[ConstraintBlock]) -> str:
    """Format ConstraintBlocks into a numbered constraint list."""
    if not constraints:
        return "(No constraints.)"
    lines: List[str] = []
    for i, c in enumerate(constraints, 1):
        priority_tag = "HARD" if c.priority == "hard" else "SOFT"
        lines.append(f"  {i}. [{priority_tag} | {c.constraint_type.upper()}] {c.instruction}")
    return "\n".join(lines)


def _format_rendering_directive(r: RenderingDirective) -> str:
    """Format a RenderingDirective into prose instructions."""
    parts = [
        f"RENDERING MODE: {r.rendering_mode}",
        f"PACING: {r.pacing}",
        f"SENSORY FOCUS: {r.sensory_focus}",
    ]
    if r.pov_lock:
        parts.append(f"POV LOCKED TO: {r.pov_lock}")
    if r.tone_arc:
        parts.append(f"TONAL ARC: {r.tone_arc}")
    if r.stylistic_instructions:
        parts.append("STYLISTIC ACTIONS:")
        for j, si in enumerate(r.stylistic_instructions, 1):
            parts.append(f"  {j}. {si}")
    return "\n".join(parts)


def _format_threat_proximity(tp: ThreatProximity) -> str:
    lines = ["THREAT PROXIMITY:"]
    if tp.threat_event_id:
        lines.append(f"  Threat event: {tp.threat_event_id}")
    lines.append(f"  Description: {tp.threat_description}")
    lines.append(f"  P(threat): {tp.threat_probability:.2f}")
    lines.append(f"  P(hope): {tp.hope_probability:.2f}")
    lines.append(f"  Damage potential: {tp.damage_potential:.1f}/10")
    if tp.spatial_distance is not None:
        lines.append(f"  Spatial distance: {tp.spatial_distance} hops")
    return "\n".join(lines)


def _format_counterfactual(cf: CounterfactualBranch) -> str:
    lines = [
        "COUNTERFACTUAL BRANCH:",
        f"  ACTUAL OUTCOME: {cf.actual_outcome}",
        f"  SIMULATED (better) OUTCOME: {cf.simulated_outcome}",
    ]
    if cf.divergence_event_id:
        lines.append(f"  POINT OF DIVERGENCE: {cf.divergence_event_id}")
    if cf.divergence_description:
        lines.append(f"    → {cf.divergence_description}")
    return "\n".join(lines)


def _format_causal_attribution(ca: CausalAttribution) -> str:
    lines = [
        "CAUSAL ATTRIBUTION:",
        f"  PERPETRATOR: {ca.perpetrator_id}" + (f" ({ca.perpetrator_name})" if ca.perpetrator_name else ""),
        f"  LOSS EVENT: {ca.loss_event_id} — {ca.loss_description}",
    ]
    if ca.causal_chain:
        lines.append(f"  CAUSAL CHAIN: {' → '.join(ca.causal_chain)}")
    return "\n".join(lines)


def _format_entanglement(pairs: List[EntanglementPair]) -> str:
    if not pairs:
        return ""
    lines = ["ENTANGLEMENT PAIRS:"]
    for p in pairs:
        co = " (co-located)" if p.shared_location else " (separated)"
        lines.append(f"  {p.entity_a} ↔ {p.entity_b}: coupling={p.coupling_strength:.2f}{co}")
    return "\n".join(lines)


def _format_interventions(mechs: List[InterventionMechanism]) -> str:
    if not mechs:
        return ""
    lines = ["INTERVENTION PHYSICS (do-operator state changes you MUST render):"]
    for m in mechs:
        lines.append(
            f"  {m.node_id}: {m.old_state} → {m.new_state} "
            f"via {m.mechanism_hint} (inertia={m.inertia:.2f})"
        )
    return "\n".join(lines)


def _format_abduction(truths: List[AbductionTruth]) -> str:
    if not truths:
        return ""
    lines = ["ABDUCTION BACKGROUND TRUTHS (weave into subtext — do NOT use clunky exposition):"]
    for t in truths:
        hint = f" Hint: {t.weave_hint}" if t.weave_hint else ""
        lines.append(f"  {t.entity_id}: {t.hidden_variable}.{hint}")
    return "\n".join(lines)


def _format_scene_context(ctx: Dict[str, Any]) -> str:
    """Build a concise scene context from the ego-graph payload."""
    lines: List[str] = []

    # Focus entities
    for ent in ctx.get("focus_entities", []):
        eid = ent.get("id", "?")
        name = ent.get("name", eid)
        loc = ent.get("location_id", "unknown")
        status = ent.get("status", "unknown")
        traits = ent.get("traits", {})
        trait_parts = []
        for tn, td in traits.items():
            if isinstance(td, dict):
                val = td.get("value", 0.5)
                if abs(val - 0.5) >= 0.15:
                    trait_parts.append(f"{tn}={val:.2f}")
        trait_str = ", ".join(trait_parts) if trait_parts else "baseline"
        lines.append(f"  {name} ({eid}) — {status}, at {loc} [{trait_str}]")

    # Present entities
    for ent in ctx.get("present_entities", []):
        eid = ent.get("id", "?")
        name = ent.get("name", eid)
        loc = ent.get("location_id", "unknown")
        lines.append(f"  {name} ({eid}) — present at {loc}")

    # Locations (ego-graph uses "current_locations")
    for loc in ctx.get("current_locations", ctx.get("relevant_locations", [])):
        lid = loc.get("id", "?")
        lname = loc.get("name", lid)
        lines.append(f"  Location: {lname} ({lid})")

    # Recent events (from memory)
    for evt in ctx.get("recent_memory", []):
        eid = evt.get("id", "?")
        desc = evt.get("description", "")
        lines.append(f"  Recent: {eid} — {desc}")

    if not lines:
        return "(No scene context available.)"
    return "\n".join(lines)


def assemble_rendering_prompt(
    brief: CreativeBrief,
    query_type: str = "directive",
    physics_state: Optional[Dict[str, Any]] = None,
) -> str:
    """Assemble the full semantic prompt injection from a CreativeBrief.

    This is the "Step 9 → Step 10" bridge: all mathematical constraints,
    rendering directives, and scene context are flattened into a single
    text block that the LLM can consume as a user message.
    """
    sections: List[str] = []

    # === Header ===
    sections.append(f"=== GENERATION TASK: {brief.target_effect.upper()} ===")
    sections.append(f"Target entities: {', '.join(brief.target_entities)}")
    sections.append("")

    # === Scene Context ===
    sections.append("=== SCENE CONTEXT ===")
    sections.append(_format_scene_context(brief.scene_context))
    sections.append("")

    # === Mathematical Constraints (the guardrails) ===
    sections.append("=== CONSTRAINTS (Step 9 — Semantic Prompt Injection) ===")
    sections.append(_format_constraints(brief.constraints))
    sections.append("")

    # === Rendering Directive (the stylistic control layer) ===
    if brief.rendering:
        sections.append("=== RENDERING DIRECTIVE (Step 10 — How to write) ===")
        sections.append(_format_rendering_directive(brief.rendering))
        sections.append("")

    # === Effect-specific payloads ===
    if brief.threat_proximity:
        sections.append(_format_threat_proximity(brief.threat_proximity))
        sections.append("")

    if brief.counterfactual_branch:
        sections.append(_format_counterfactual(brief.counterfactual_branch))
        sections.append("")

    if brief.causal_attribution:
        sections.append(_format_causal_attribution(brief.causal_attribution))
        sections.append("")

    if brief.entanglement_pairs:
        sections.append(_format_entanglement(brief.entanglement_pairs))
        sections.append("")

    if brief.intervention_mechanisms:
        sections.append(_format_interventions(brief.intervention_mechanisms))
        sections.append("")

    if brief.abduction_truths:
        sections.append(_format_abduction(brief.abduction_truths))
        sections.append("")

    # === Physics Override ===
    if brief.physics_override:
        sections.append(f"=== PHYSICS OVERRIDE ===\n{brief.physics_override}")
        sections.append("")

    # === Epistemic Gaps (reference data) ===
    if brief.epistemic_gaps:
        sections.append("=== EPISTEMIC STATE (character beliefs vs reality) ===")
        for g in brief.epistemic_gaps:
            sections.append(
                f"  {g.entity_id} re {g.belief_target_id}: "
                f"believes='{g.believed_state}' actual='{g.actual_state}' "
                f"({g.gap_type}, mag={g.gap_magnitude:.2f})"
            )
        sections.append("")

    # === Trait Trajectories (reference data) ===
    if brief.trait_trajectories:
        extreme = [t for t in brief.trait_trajectories if abs(t.current_value - 0.5) >= 0.15]
        if extreme:
            sections.append("=== KEY TRAIT STATES ===")
            for t in extreme:
                sections.append(
                    f"  {t.entity_id}.{t.trait_name} = {t.current_value:.2f} "
                    f"(inertia={t.inertia:.2f}, headroom↑={t.headroom_up:.2f}, headroom↓={t.headroom_down:.2f})"
                )
            sections.append("")

    # === Relationship Tensions (reference data) ===
    if brief.relationship_tensions:
        tense = [r for r in brief.relationship_tensions if r.asymmetry_score > 0.1]
        if tense:
            sections.append("=== RELATIONSHIP TENSIONS ===")
            for r in tense:
                sections.append(
                    f"  {r.source_id}→{r.target_id}: affinity={r.affinity:.2f}, "
                    f"fear={r.fear:.2f}, power={r.power_dynamic:.2f} "
                    f"(asymmetry={r.asymmetry_score:.2f})"
                )
            sections.append("")

    sections.append(
        "=== TASK ===\n"
        "Write the prose passage now. Honour ALL hard constraints. "
        "The prose must structurally validate against the mathematical "
        "state described above. The NarrativeAuditor will check that "
        "the rendered text is consistent with the physics."
    )

    return "\n".join(sections)


# =====================================================================
# Brief builders for non-directive query types
# =====================================================================

def build_observation_brief(
    query: ObservationQuery,
    physics_state: Dict[str, Any],
    world_state: WorldStateV1,
) -> CreativeBrief:
    """Build a lightweight CreativeBrief for observation queries."""
    pov = query.focus_entity_ids[0] if query.focus_entity_ids else None
    return CreativeBrief(
        target_effect="observation",
        target_entities=query.focus_entity_ids,
        rendering=RenderingDirective(
            rendering_mode="observation",
            pov_lock=pov,
            pacing="normal",
            sensory_focus="wide",
            stylistic_instructions=[
                "Render the scene from the focal character's perspective.",
                "Describe what they see, hear, and feel in this moment.",
                "Include environmental details that set the tone.",
                "Ground the prose in the character's current emotional state (use trait values).",
                "Do NOT reveal information the focal character cannot perceive.",
            ],
        ),
        scene_context=physics_state,
    )


def build_intervention_brief(
    query: InterventionQuery,
    physics_state: Dict[str, Any],
    world_state: WorldStateV1,
    mutations: Optional[List[Dict[str, Any]]] = None,
    blocked: Optional[List[Dict[str, Any]]] = None,
) -> CreativeBrief:
    """Build a CreativeBrief for intervention (do-calculus) queries."""
    # Build InterventionMechanism entries from the interventions dict
    mechanisms: List[InterventionMechanism] = []
    for target_path, new_value in query.interventions.items():
        parts = target_path.split(".", 1)
        node_id = parts[0]
        prop = parts[1] if len(parts) > 1 else "state"

        # Try to find the old state
        old_state = "unknown"
        if node_id in world_state.entities:
            if prop == "status":
                old_state = world_state.entities[node_id].status
            elif prop.startswith("traits."):
                trait_name = prop.split(".", 1)[1]
                tv = world_state.entities[node_id].traits.get(trait_name)
                old_state = f"{tv.value:.2f}" if tv else "unknown"
        elif node_id in world_state.objects:
            old_state = world_state.objects[node_id].properties.get(prop, "unknown")

        # Determine mechanism from the property type
        mechanism = "physical"
        if prop.startswith("traits."):
            mechanism = "psychological force overcoming inertia"
        elif prop == "status":
            mechanism = "physical force or environmental change"
        elif prop == "location_id":
            mechanism = "physical movement"

        # Find inertia if applicable
        inertia = 0.5
        if node_id in world_state.entities and prop.startswith("traits."):
            trait_name = prop.split(".", 1)[1]
            tv = world_state.entities[node_id].traits.get(trait_name)
            if tv:
                inertia = tv.inertia

        mechanisms.append(InterventionMechanism(
            node_id=node_id,
            old_state=old_state,
            new_state=str(new_value),
            mechanism_hint=mechanism,
            inertia=inertia,
        ))

    constraints: List[ConstraintBlock] = []
    # Blocked propagations become constraints
    if blocked:
        for b in blocked:
            constraints.append(ConstraintBlock(
                constraint_type="spatial",
                priority="hard",
                instruction=(
                    f"BLOCKED: The propagation to {b.get('node_id', '?')}.{b.get('trait', '?')} "
                    f"was blocked by {b.get('reason', 'unknown')}. "
                    f"The state change did NOT propagate — render the resistance."
                ),
                evidence=b,
            ))

    constraints.append(ConstraintBlock(
        constraint_type="mathematical",
        priority="hard",
        instruction=(
            "You MUST describe the exact physical mechanism that caused each "
            "state change. Do NOT just say 'the door opened' — render the "
            "physical struggle or action that forced the Impact to overcome "
            "the Inertia. The reader must feel the force required."
        ),
        evidence={},
    ))

    return CreativeBrief(
        target_effect="intervention",
        target_entities=list({
            p.split(".")[0] for p in query.interventions
            if p.split(".")[0].startswith("ENT_")
        }),
        constraints=constraints,
        rendering=RenderingDirective(
            rendering_mode="intervention",
            pacing="normal",
            sensory_focus="normal",
            stylistic_instructions=[
                "Describe the exact physical mechanism for each state change (do-operator).",
                "Render the struggle between Impact and Inertia as physical prose.",
                "Show the cause producing the effect through a specific mechanism "
                "(kinetic, chemical, social, psychological).",
                "If a propagation was blocked, describe the resistance — the force "
                "that stopped the change from taking hold.",
            ],
        ),
        intervention_mechanisms=mechanisms,
        scene_context=physics_state,
    )


def build_counterfactual_brief(
    query: CounterfactualQuery,
    physics_state: Dict[str, Any],
    world_state: WorldStateV1,
    hidden_deltas: Optional[Dict[str, Dict[str, float]]] = None,
) -> CreativeBrief:
    """Build a CreativeBrief for counterfactual (Rung 3) queries."""
    # Build AbductionTruth entries from hidden_deltas
    abduction: List[AbductionTruth] = []
    if hidden_deltas:
        for entity_id, deltas in hidden_deltas.items():
            for trait, delta_val in deltas.items():
                direction = "increased" if delta_val > 0 else "decreased"
                abduction.append(AbductionTruth(
                    entity_id=entity_id,
                    hidden_variable=(
                        f"{trait} {direction} by {abs(delta_val):.2f} "
                        f"(inferred from present-day evidence)"
                    ),
                    weave_hint=(
                        f"Show this through subtle behavioral cues — {entity_id}'s "
                        f"body language, word choice, or micro-reactions should "
                        f"reveal the hidden {trait} shift without exposition."
                    ),
                ))

    # Build a counterfactual branch from the intervention keys
    hist_keys = list(query.historical_interventions.keys())
    cf_branch = CounterfactualBranch(
        actual_outcome="The factual timeline as it occurred.",
        simulated_outcome=(
            f"The alternate timeline where {', '.join(hist_keys)} "
            f"were changed to: {query.historical_interventions}"
        ),
        divergence_event_id=hist_keys[0].split(".")[0] if hist_keys else None,
    )

    constraints = [
        ConstraintBlock(
            constraint_type="narrative",
            priority="hard",
            instruction=(
                "This is a COUNTERFACTUAL scene — an alternate reality. "
                "The prose must feel like a 'what-if' branch, subtly different "
                "from the factual timeline. Use conditional/subjunctive mood "
                "where appropriate."
            ),
            evidence={},
        ),
    ]

    if abduction:
        constraints.append(ConstraintBlock(
            constraint_type="mathematical",
            priority="hard",
            instruction=(
                "Abduction background truths have been inferred by the physics "
                "engine. You MUST weave these into the subtext smoothly — through "
                "casual actions, body language, or environmental details. "
                "Do NOT use clunky exposition. The NarrativeAuditor will check "
                "that these hidden variables are structurally present."
            ),
            evidence={},
        ))

    return CreativeBrief(
        target_effect="counterfactual",
        target_entities=list({
            p.split(".")[0] for p in query.historical_interventions
            if p.split(".")[0].startswith("ENT_")
        }),
        constraints=constraints,
        rendering=RenderingDirective(
            rendering_mode="counterfactual",
            pacing="normal",
            sensory_focus="normal",
            stylistic_instructions=[
                "This is an alternate timeline. Ground the prose in physical "
                "reality but mark the divergence subtly.",
                "If the counterfactual is better than reality, let the prose "
                "feel cautiously hopeful — but fragile.",
                "If the counterfactual is worse, let the prose feel eerily wrong.",
                "Weave abduction background truths into character behavior naturally.",
                "The reader should feel they are peering into a possible world.",
            ],
        ),
        counterfactual_branch=cf_branch,
        abduction_truths=abduction,
        scene_context=physics_state,
    )


# =====================================================================
# Agent Builder
# =====================================================================

def _build_generation_agent(config: GenerationConfig) -> Agent[_GenerationDeps, GeneratedScene]:
    """Construct the Step 10 rendering LLM agent."""
    agent: Agent[_GenerationDeps, GeneratedScene] = Agent(
        _resolve_model(config.model),
        deps_type=_GenerationDeps,
        output_type=NativeOutput(GeneratedScene),
        system_prompt=_load_prompt("generation.md"),
        retries=config.output_retries,
    )

    @agent.system_prompt
    def inject_rendering_prompt(ctx: RunContext[_GenerationDeps]) -> str:
        return ctx.deps.rendering_prompt

    return agent


# =====================================================================
# Public API
# =====================================================================

def render_scene(
    brief: CreativeBrief,
    config: GenerationConfig | None = None,
    query_type: str = "directive",
    physics_state: Optional[Dict[str, Any]] = None,
) -> GeneratedScene:
    """Render a prose scene from a CreativeBrief.

    This is the main entry point for Step 10.

    Parameters
    ----------
    brief : CreativeBrief
        The assembled brief from directive_assembly (or a brief builder).
    config : GenerationConfig or None
        Model and retry configuration.
    query_type : str
        The originating query type for prompt framing.
    physics_state : dict or None
        Raw physics state for additional context.

    Returns
    -------
    GeneratedScene
        The rendered prose with audit metadata.
    """
    config = config or GenerationConfig()

    rendering_prompt = assemble_rendering_prompt(brief, query_type, physics_state)
    logger.info(
        "[Generation] Rendering scene: effect=%s entities=%s mode=%s",
        brief.target_effect,
        brief.target_entities,
        brief.rendering.rendering_mode if brief.rendering else "default",
    )
    logger.debug("[Generation] Prompt length: %d chars", len(rendering_prompt))

    agent = _build_generation_agent(config)
    deps = _GenerationDeps(rendering_prompt=rendering_prompt)

    model_settings: Dict[str, Any] = {}
    if config.temperature != 0.7:
        model_settings["temperature"] = config.temperature
    if config.max_tokens != 4096:
        model_settings["max_tokens"] = config.max_tokens

    try:
        result = agent.run_sync(
            f"Render the scene now. Target effect: {brief.target_effect}.",
            deps=deps,
            model_settings=model_settings if model_settings else None,
        )
        scene = result.output
    except Exception as exc:
        logger.error("[Generation] LLM call failed: %s. Returning fallback scene.", exc)
        return GeneratedScene(
            prose=f"[Generation failed: {exc}]",
            pov_entity=None,
            rendering_mode="fallback",
            constraints_honoured=[],
            constraints_violated=["generation_failure"],
        )

    logger.info(
        "[Generation] Scene rendered: %d chars, mode=%s, %d constraints honoured, %d violated",
        len(scene.prose),
        scene.rendering_mode,
        len(scene.constraints_honoured),
        len(scene.constraints_violated),
    )
    return scene


def render_from_query(
    request: UserRequest,
    physics_result: Dict[str, Any],
    world_state: WorldStateV1,
    config: GenerationConfig | None = None,
) -> GeneratedScene:
    """High-level convenience: build a brief from any query type and render.

    This routes from the raw ``calculate_narrative_physics()`` output
    directly to prose generation.

    Parameters
    ----------
    request : UserRequest
        The original user query.
    physics_result : dict
        The output of ``calculate_narrative_physics()``.
    world_state : WorldStateV1
        The global world state for context.
    config : GenerationConfig or None
        Generation configuration.

    Returns
    -------
    GeneratedScene
    """
    config = config or GenerationConfig()
    physics_state = physics_result.get("physics_state", {})

    if request.query_type == "observation":
        brief = build_observation_brief(request, physics_state, world_state)
        return render_scene(brief, config, "observation", physics_state)

    elif request.query_type == "intervention":
        brief = build_intervention_brief(
            request,
            physics_state,
            world_state,
            mutations=physics_result.get("mutations"),
            blocked=physics_result.get("blocked"),
        )
        return render_scene(brief, config, "intervention", physics_state)

    elif request.query_type == "counterfactual":
        brief = build_counterfactual_brief(
            request,
            physics_state,
            world_state,
            hidden_deltas=physics_result.get("hidden_deltas"),
        )
        return render_scene(brief, config, "counterfactual", physics_state)

    elif request.query_type == "directive":
        # Directive queries should already have a creative_brief in physics_result
        brief_data = physics_result.get("creative_brief")
        if brief_data:
            brief = CreativeBrief(**brief_data) if isinstance(brief_data, dict) else brief_data
        else:
            # Fallback: build a minimal brief
            brief = CreativeBrief(
                target_effect=physics_result.get("target_effect", "observation"),
                target_entities=getattr(request, "target_entity_ids", []),
                scene_context=physics_state,
            )
        return render_scene(brief, config, "directive", physics_state)

    elif request.query_type == "interrogate":
        raise ValueError(
            "Interrogation queries return graph analysis, not prose. "
            "Do not call render_from_query for interrogation."
        )

    else:
        raise ValueError(f"Unknown query type: {request.query_type}")
