"""A Fish Called Wanda — high-fidelity WorldStateV1 test fixture.

Authored against the current ingestion prompts. Demonstrates all five
CausalEdge modalities, per-axis ``RelationshipMetric``, explicit
``evidence_strength`` everywhere, and named-latent WORLD_ traits wired
as common-cause parents over the events they jointly drive.

This story's WORLD_ latents are: Thieves' Honour (the brittle code
among heist crews), Anglo-American Cultural Clash (brash Yanks vs.
stiff English propriety), Double-Cross Economy (every alliance is a
temporary contract), and English Respectability Pressure (marriage,
the Bar, and the courtroom as moral cages).
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, RelationshipMetric, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_HEATHROW": Location(name="Heathrow Safe-Deposit", description="Where the stolen diamonds are initially stored.",
            ambient_state={
                "tension": AmbientVector(value=0.7, volatility=0.4, evidence_strength="strong"),
                "institutional_security": AmbientVector(value=0.8, volatility=0.1, evidence_strength="moderate"),
            }),
        "LOC_ARCHIE_FLAT": Location(name="Archie Leach's Chambers", description="Archie's barrister chambers and flat — wood-panelled English propriety made architectural.",
            ambient_state={
                "respectability": AmbientVector(value=0.7, volatility=0.3, evidence_strength="strong"),
                "marital_chill": AmbientVector(value=0.75, volatility=0.2, evidence_strength="moderate"),
            }),
        "LOC_GEORGE_FLAT": Location(name="George's Flat", description="George Thomason's flat where the gang meets to plan the heist.",
            ambient_state={
                "tension": AmbientVector(value=0.6, volatility=0.4, evidence_strength="strong"),
                "criminal_intimacy": AmbientVector(value=0.7, volatility=0.3, evidence_strength="moderate"),
            }),
        "LOC_WANDA_FLAT": Location(name="Wanda's Flat", description="Wanda's London flat where she keeps the locket and stages her seductions.",
            ambient_state={
                "deception": AmbientVector(value=0.7, volatility=0.4, evidence_strength="strong"),
                "erotic_charge": AmbientVector(value=0.8, volatility=0.5, evidence_strength="strong"),
            }),
        "LOC_OLD_BAILEY": Location(name="Old Bailey", description="Criminal court where George is tried — the cathedral of English legal decorum.",
            ambient_state={
                "formality": AmbientVector(value=0.85, volatility=0.15, evidence_strength="strong"),
                "public_scrutiny": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
            }),
        "LOC_HIDEOUT_GARAGE": Location(name="Hideout Garage", description="Garage where Ken keeps his fish tanks and the stash before the move.",
            ambient_state={
                "tension": AmbientVector(value=0.5, volatility=0.4, evidence_strength="moderate"),
                "animal_warmth": AmbientVector(value=0.7, volatility=0.2, evidence_strength="strong"),
            }),
        "LOC_OLD_WORKSHOP": Location(name="Old Workshop", description="Disused workshop where the gang stash the diamonds in a safe immediately after the heist.",
            ambient_state={
                "secrecy": AmbientVector(value=0.85, volatility=0.3, evidence_strength="strong"),
                "abandonment": AmbientVector(value=0.8, volatility=0.1, evidence_strength="moderate"),
            }),
        "LOC_HEATHROW_HOTEL": Location(name="Hotel near Heathrow", description="Hotel near Heathrow Airport where George later stashes the diamonds in a safe-deposit box.",
            ambient_state={
                "tension": AmbientVector(value=0.75, volatility=0.4, evidence_strength="strong"),
                "transient_anonymity": AmbientVector(value=0.85, volatility=0.2, evidence_strength="moderate"),
            }),
        "LOC_AIRPORT_RUNWAY": Location(name="Heathrow Runway", description="Tarmac where the Rio-bound jet boards in the closing slapstick.",
            ambient_state={
                "chaos": AmbientVector(value=0.85, volatility=0.6, evidence_strength="strong"),
                "escape_velocity": AmbientVector(value=0.9, volatility=0.5, evidence_strength="strong"),
            }),
    },
    objects={
        "OBJ_DIAMONDS": NarrativeObject(id="OBJ_DIAMONDS", name="Stolen Diamonds",
            location_id="LOC_OLD_WORKSHOP", owner_id=None,
            properties={"state": "hidden", "value": "thirteen_million", "initial_stash": "old_workshop_safe", "final_stash": "heathrow_hotel_safe_deposit_box"},
            affordances=[Affordance(action="retrieve", target_type="Entity"), Affordance(action="leverage", target_type="Entity")]),
        "OBJ_LOCKET": NarrativeObject(id="OBJ_LOCKET", name="Safe-Deposit Key in Locket",
            location_id=None, owner_id="ENT_WANDA",
            properties={"state": "worn", "content": "safe_deposit_key"},
            affordances=[Affordance(action="unlock_diamonds", target_type="Entity")]),
        "OBJ_STEAMROLLER": NarrativeObject(id="OBJ_STEAMROLLER", name="Steamroller",
            location_id=None, owner_id=None,
            properties={"state": "operational"},
            affordances=[Affordance(action="crush", target_type="Entity")]),
    },
    entities={
        "ENT_WANDA": Entity(id="ENT_WANDA", name="Wanda Gershwitz",
            location_id="LOC_WANDA_FLAT", status="healthy",
            traits={
                "cunning":            TraitVector(value=0.9,  inertia=0.5,  evidence_strength="strong"),
                "seductiveness":      TraitVector(value=0.85, inertia=0.5,  evidence_strength="strong"),
                "greed":              TraitVector(value=0.8,  inertia=0.5,  evidence_strength="strong"),
                "linguistic_arousal": TraitVector(value=0.7,  inertia=0.4,  evidence_strength="moderate"),
                "opportunism":        TraitVector(value=0.85, inertia=0.55, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_OTTO",   perceived_state="Otto is useful but expendable",            confidence=0.8, inertia=0.4, established_at_fabula=0,   evidence_strength="moderate"),
                Belief(target_id="ENT_ARCHIE", perceived_state="Archie has information I need",            confidence=0.7, inertia=0.3, established_at_fabula=600, evidence_strength="moderate"),
                Belief(target_id="ENT_GEORGE", perceived_state="George is a useful patsy and obstacle",   confidence=0.8, inertia=0.4, established_at_fabula=100, evidence_strength="strong"),
            ],
            constants=["american_grifter", "bilingual_italian"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_WANDA_SEDUCES_ARCHIE",
                    traits={"cunning": TraitVector(value=0.9, inertia=0.5, evidence_strength="strong")},
                    beliefs_added=[Belief(target_id="ENT_ARCHIE", perceived_state="Archie is genuinely attractive",
                                          confidence=0.6, inertia=0.3, established_at_fabula=700, evidence_strength="moderate")]),
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_ARCHIE_ENDS_AFFAIR",
                    traits={"opportunism": TraitVector(value=0.95, inertia=0.55, evidence_strength="strong")},
                    beliefs_added=[Belief(target_id="ENT_ARCHIE",
                        perceived_state="Archie has gone soft — he can still be played but is no longer reliable",
                        confidence=0.7, inertia=0.4, established_at_fabula=1200, evidence_strength="moderate")]),
                EntityStateSnapshot(fabula_time=2200, triggered_by="EVT_WANDA_DOUBLECROSSES_OTTO",
                    traits={"greed": TraitVector(value=0.95, inertia=0.55, evidence_strength="strong")}),
                EntityStateSnapshot(fabula_time=2600, triggered_by="EVT_ARCHIE_WANDA_FLY_AWAY",
                    traits={"seductiveness": TraitVector(value=0.85, inertia=0.55, evidence_strength="strong")},
                    beliefs_invalidated=["ENT_OTTO"],
                    beliefs_added=[Belief(target_id="ENT_ARCHIE", perceived_state="Archie is a trusted partner",
                                          confidence=0.75, inertia=0.4, established_at_fabula=2600, evidence_strength="moderate")]),
            ]),
        "ENT_OTTO": Entity(id="ENT_OTTO", name="Otto West",
            location_id="LOC_GEORGE_FLAT", status="healthy",
            traits={
                "jealousy":              TraitVector(value=0.8,  inertia=0.4, evidence_strength="strong"),
                "stupidity":             TraitVector(value=0.45, inertia=0.5, evidence_strength="moderate"),
                "aggression":            TraitVector(value=0.8,  inertia=0.4, evidence_strength="strong"),
                "pseudo_intellectualism":TraitVector(value=0.85, inertia=0.55, evidence_strength="strong"),
                "vengeance":             TraitVector(value=0.4,  inertia=0.4, evidence_strength="moderate"),
                "stability":             TraitVector(value=0.5,  inertia=0.4, evidence_strength="moderate"),
                "anglophobia":           TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_WANDA", perceived_state="Wanda is my girlfriend and loyal to me", confidence=0.7, inertia=0.3, established_at_fabula=0,   evidence_strength="moderate"),
                Belief(target_id="ENT_KEN",   perceived_state="Ken is an idiot I can bully",            confidence=0.85, inertia=0.5, established_at_fabula=0,  evidence_strength="strong"),
                Belief(target_id="ENT_ARCHIE",perceived_state="Archie is a stuck-up English wanker",     confidence=0.9, inertia=0.6, established_at_fabula=700, evidence_strength="strong"),
            ],
            constants=["american_grifter", "weapons_expert", "vietnam_obsessed"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_OTTO_DISCOVERS_BETRAYAL",
                    traits={"jealousy":   TraitVector(value=0.95, inertia=0.5, evidence_strength="strong"),
                            "aggression": TraitVector(value=0.9,  inertia=0.5, evidence_strength="strong")},
                    beliefs_invalidated=["ENT_WANDA"],
                    beliefs_added=[Belief(target_id="ENT_WANDA",
                        perceived_state="Wanda is sleeping with Archie — she will pay",
                        confidence=0.95, inertia=0.6, established_at_fabula=1100, evidence_strength="strong")]),
                EntityStateSnapshot(fabula_time=2200, triggered_by="EVT_WANDA_DOUBLECROSSES_OTTO",
                    traits={"aggression": TraitVector(value=1.0, inertia=0.5, evidence_strength="strong"),
                            "stability":  TraitVector(value=0.1, inertia=0.45, evidence_strength="strong"),
                            "vengeance":  TraitVector(value=0.9, inertia=0.5, evidence_strength="strong")}),
                EntityStateSnapshot(fabula_time=2500, triggered_by="EVT_OTTO_STEAMROLLED",
                    status="injured",
                    traits={"aggression": TraitVector(value=1.0, inertia=0.5, evidence_strength="strong"),
                            "stability":  TraitVector(value=0.05, inertia=0.5, evidence_strength="strong"),
                            "vengeance":  TraitVector(value=1.0, inertia=0.55, evidence_strength="strong")}),
                EntityStateSnapshot(fabula_time=2800, triggered_by="EVT_OTTO_BLOWN_OFF_DURING_TAKEOFF",
                    status="injured", location_id="LOC_AIRPORT_RUNWAY"),
            ]),
        "ENT_KEN": Entity(id="ENT_KEN", name="Ken Pile",
            location_id="LOC_HIDEOUT_GARAGE", status="healthy",
            traits={
                "kindness":            TraitVector(value=0.8,  inertia=0.55, evidence_strength="strong"),
                "stutter":             TraitVector(value=0.7,  inertia=0.7,  evidence_strength="strong"),
                "devotion_to_animals": TraitVector(value=0.95, inertia=0.9,  evidence_strength="strong"),
                "determination":       TraitVector(value=0.65, inertia=0.3,  evidence_strength="moderate"),
                "guilt":               TraitVector(value=0.2,  inertia=0.4,  evidence_strength="moderate"),
                "loyalty_to_george":   TraitVector(value=0.85, inertia=0.6,  evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_GEORGE", perceived_state="George is my boss and I am loyal to him", confidence=0.85, inertia=0.55, established_at_fabula=0,   evidence_strength="strong"),
                Belief(target_id="ENT_OTTO",   perceived_state="Otto is Wanda's brother",                  confidence=0.8, inertia=0.4, established_at_fabula=0,    evidence_strength="moderate"),
                Belief(target_id="ENT_WANDA",  perceived_state="Wanda is Otto's sister and trustworthy",   confidence=0.7, inertia=0.4, established_at_fabula=0,    evidence_strength="moderate"),
            ],
            constants=["animal_lover", "stutterer", "safe_cracker"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_KEN_KILLS_DOGS",
                    traits={"devotion_to_animals": TraitVector(value=0.95, inertia=0.9, evidence_strength="strong"),
                            "determination":       TraitVector(value=0.6,  inertia=0.35, evidence_strength="strong"),
                            "guilt":               TraitVector(value=0.75, inertia=0.45, evidence_strength="strong")}),
                EntityStateSnapshot(fabula_time=1900, triggered_by="EVT_OTTO_INTERROGATES_KEN",
                    traits={"determination": TraitVector(value=0.9, inertia=0.4, evidence_strength="strong"),
                            "guilt":         TraitVector(value=0.85, inertia=0.5, evidence_strength="strong")},
                    beliefs_invalidated=["ENT_OTTO"],
                    beliefs_added=[Belief(target_id="ENT_OTTO",
                        perceived_state="Otto is a fish-murdering monster who must be crushed",
                        confidence=0.95, inertia=0.7, established_at_fabula=1900, evidence_strength="strong")]),
                EntityStateSnapshot(fabula_time=2500, triggered_by="EVT_OTTO_STEAMROLLED",
                    traits={"determination": TraitVector(value=1.0, inertia=0.5, evidence_strength="strong")}),
            ]),
        "ENT_GEORGE": Entity(id="ENT_GEORGE", name="George Thomason",
            location_id="LOC_GEORGE_FLAT", status="healthy",
            traits={
                "professionalism":  TraitVector(value=0.75, inertia=0.55, evidence_strength="strong"),
                "calm":             TraitVector(value=0.65, inertia=0.45, evidence_strength="moderate"),
                "paranoia":         TraitVector(value=0.55, inertia=0.4,  evidence_strength="moderate"),
                "vindictiveness":   TraitVector(value=0.4,  inertia=0.4,  evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_KEN",   perceived_state="Ken is loyal and reliable",       confidence=0.85, inertia=0.55, established_at_fabula=0, evidence_strength="strong"),
                Belief(target_id="ENT_OTTO",  perceived_state="Otto and Wanda are siblings",     confidence=0.9, inertia=0.5, established_at_fabula=0, evidence_strength="moderate"),
                Belief(target_id="ENT_WANDA", perceived_state="Wanda is Otto's sister and a useful asset", confidence=0.85, inertia=0.5, established_at_fabula=0, evidence_strength="moderate"),
            ],
            constants=["london_gangster", "crew_boss"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_DIAMONDS_MOVED",
                    traits={"paranoia": TraitVector(value=0.8, inertia=0.45, evidence_strength="strong")},
                    location_id="LOC_HEATHROW_HOTEL"),
                EntityStateSnapshot(fabula_time=300, triggered_by="EVT_WANDA_BETRAYS_GEORGE",
                    status="injured",
                    traits={"vindictiveness": TraitVector(value=0.85, inertia=0.55, evidence_strength="strong")},
                    beliefs_invalidated=["ENT_WANDA", "ENT_OTTO"],
                    beliefs_added=[Belief(target_id="ENT_WANDA",
                        perceived_state="Wanda and Otto sold me out — they will not see a penny",
                        confidence=0.95, inertia=0.7, established_at_fabula=300, evidence_strength="strong")],
                    location_id="LOC_OLD_BAILEY"),
                EntityStateSnapshot(fabula_time=2000, triggered_by="EVT_GEORGE_INFORMS_ARCHIE_ABOUT_KEN",
                    traits={"professionalism": TraitVector(value=0.5, inertia=0.55, evidence_strength="strong")}),
            ]),
        "ENT_ARCHIE": Entity(id="ENT_ARCHIE", name="Archie Leach",
            location_id="LOC_ARCHIE_FLAT", status="healthy",
            traits={
                "propriety":   TraitVector(value=0.75, inertia=0.55, evidence_strength="strong"),
                "repression":  TraitVector(value=0.7,  inertia=0.45, evidence_strength="strong"),
                "charm":       TraitVector(value=0.6,  inertia=0.4,  evidence_strength="moderate"),
                "passion":     TraitVector(value=0.3,  inertia=0.25, evidence_strength="moderate"),
                "guilt":       TraitVector(value=0.2,  inertia=0.35, evidence_strength="moderate"),
                "risk_taking": TraitVector(value=0.2,  inertia=0.3,  evidence_strength="moderate"),
                "awakening":   TraitVector(value=0.1,  inertia=0.2,  evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_WANDA",  perceived_state="Wanda finds me irresistible",            confidence=0.6, inertia=0.3, established_at_fabula=700, evidence_strength="moderate"),
                Belief(target_id="ENT_WENDY",  perceived_state="Wendy is my respectable but loveless wife", confidence=0.85, inertia=0.6, established_at_fabula=0, evidence_strength="strong"),
            ],
            constants=["barrister", "english_gentleman"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_WANDA_SEDUCES_ARCHIE",
                    traits={"passion":    TraitVector(value=0.7, inertia=0.35, evidence_strength="strong"),
                            "repression": TraitVector(value=0.4, inertia=0.45, evidence_strength="strong"),
                            "awakening":  TraitVector(value=0.5, inertia=0.3,  evidence_strength="moderate")}),
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_ARCHIE_ENDS_AFFAIR",
                    traits={"passion": TraitVector(value=0.5, inertia=0.35, evidence_strength="moderate"),
                            "guilt":   TraitVector(value=0.7, inertia=0.45, evidence_strength="strong")}),
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_ARCHIE_CALLS_WANDA_DARLING",
                    traits={"propriety":  TraitVector(value=0.45, inertia=0.55, evidence_strength="strong"),
                            "awakening":  TraitVector(value=0.7,  inertia=0.4,  evidence_strength="strong")},
                    beliefs_invalidated=["ENT_WANDA"],
                    beliefs_added=[Belief(target_id="ENT_WANDA",
                        perceived_state="Wanda has played me — yet I cannot stop wanting her",
                        confidence=0.85, inertia=0.5, established_at_fabula=1600, evidence_strength="strong")]),
                EntityStateSnapshot(fabula_time=2100, triggered_by="EVT_AIRPORT_CHASE",
                    traits={"propriety":   TraitVector(value=0.3,  inertia=0.55, evidence_strength="strong"),
                            "repression":  TraitVector(value=0.15, inertia=0.4,  evidence_strength="strong"),
                            "passion":     TraitVector(value=0.85, inertia=0.4,  evidence_strength="strong"),
                            "risk_taking": TraitVector(value=0.75, inertia=0.4,  evidence_strength="strong"),
                            "awakening":   TraitVector(value=0.9,  inertia=0.5,  evidence_strength="strong")}),
                EntityStateSnapshot(fabula_time=2600, triggered_by="EVT_ARCHIE_WANDA_FLY_AWAY",
                    location_id="LOC_AIRPORT_RUNWAY",
                    traits={"propriety": TraitVector(value=0.2, inertia=0.6, evidence_strength="strong")},
                    beliefs_invalidated=["ENT_WENDY"]),
            ]),
        "ENT_MRS_COADY": Entity(id="ENT_MRS_COADY", name="Mrs Coady",
            location_id="LOC_ARCHIE_FLAT", status="healthy",
            traits={
                "frailty":    TraitVector(value=0.75, inertia=0.55, evidence_strength="strong"),
                "resilience": TraitVector(value=0.55, inertia=0.45, evidence_strength="moderate"),
                "devotion_to_dogs": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
            },
            beliefs=[],
            constants=["crown_eyewitness", "dog_owner", "elderly"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_KEN_KILLS_DOGS",
                    traits={"frailty": TraitVector(value=0.95, inertia=0.6, evidence_strength="strong")}),
                EntityStateSnapshot(fabula_time=1400, triggered_by="EVT_MRS_COADY_DIES_HEART_ATTACK", status="dead"),
            ]),
        "ENT_WENDY": Entity(id="ENT_WENDY", name="Wendy Leach",
            location_id="LOC_ARCHIE_FLAT", status="healthy",
            traits={
                "snobbery":   TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                "coldness":   TraitVector(value=0.7,  inertia=0.6,  evidence_strength="strong"),
                "shrewdness": TraitVector(value=0.65, inertia=0.55, evidence_strength="moderate"),
                "propriety":  TraitVector(value=0.9,  inertia=0.75, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_ARCHIE", perceived_state="Archie is a respectable but dull husband",
                       confidence=0.8, inertia=0.55, established_at_fabula=0, evidence_strength="moderate"),
            ],
            constants=["middle_class_wife", "social_climber"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_WENDY_MISREADS_PENDANT",
                    beliefs_added=[Belief(target_id="ENT_ARCHIE",
                        perceived_state="Archie has bought me a tasteful pendant — he can be taught",
                        confidence=0.7, inertia=0.4, established_at_fabula=900, evidence_strength="moderate")]),
                EntityStateSnapshot(fabula_time=1700, triggered_by="EVT_WENDY_DECIDES_DIVORCE",
                    traits={"coldness": TraitVector(value=0.95, inertia=0.7, evidence_strength="strong")},
                    beliefs_invalidated=["ENT_ARCHIE"],
                    beliefs_added=[Belief(target_id="ENT_ARCHIE",
                        perceived_state="Archie is having an affair — I will divorce him",
                        confidence=0.95, inertia=0.7, established_at_fabula=1700, evidence_strength="strong")]),
            ]),
    },
    events=[
        EventNode(id="EVT_HEIST", fabula_time=100, syuzhet_index=1, event_type="choice",
                  actor_ids=["ENT_GEORGE", "ENT_KEN", "ENT_WANDA", "ENT_OTTO"], target_ids=[],
                  description="The gang carries out the diamond heist at Heathrow."),
        EventNode(id="EVT_WANDA_BETRAYS_GEORGE", fabula_time=300, syuzhet_index=3, event_type="choice",
                  actor_ids=["ENT_WANDA", "ENT_OTTO"], target_ids=["ENT_GEORGE"],
                  description="Wanda and Otto tip off the police, getting George arrested."),
        EventNode(id="EVT_DIAMONDS_MOVED", fabula_time=200, syuzhet_index=2, event_type="choice",
                  actor_ids=["ENT_GEORGE"], target_ids=[],
                  description="George moves the diamonds to a new location before his arrest."),
        EventNode(id="EVT_WANDA_FINDS_KEY_IN_TANK", fabula_time=400, syuzhet_index=4, event_type="revelation",
                  actor_ids=["ENT_WANDA"], target_ids=["OBJ_LOCKET"],
                  description="In Ken's fish tank, Wanda discovers the key to the safe-deposit box containing the diamonds."),
        EventNode(id="EVT_WANDA_HIDES_KEY_IN_PENDANT", fabula_time=500, syuzhet_index=5, event_type="choice",
                  actor_ids=["ENT_WANDA"], target_ids=["OBJ_LOCKET"],
                  description="Wanda hides the safe-deposit key in her pendant locket."),
        EventNode(id="EVT_ARCHIE_DEFENDS_GEORGE", fabula_time=600, syuzhet_index=6, event_type="outcome",
                  actor_ids=["ENT_ARCHIE"], target_ids=["ENT_GEORGE"],
                  description="Archie Leach is assigned as George's defence barrister."),
        EventNode(id="EVT_WANDA_SEDUCES_ARCHIE", fabula_time=700, syuzhet_index=7, event_type="choice",
                  actor_ids=["ENT_WANDA"], target_ids=["ENT_ARCHIE"],
                  description="Wanda seduces Archie to extract information about the diamond location."),
        EventNode(id="EVT_OTTO_DISCOVERS_BETRAYAL", fabula_time=1100, syuzhet_index=11, event_type="revelation",
                  actor_ids=["ENT_OTTO"], target_ids=["ENT_WANDA", "ENT_ARCHIE"],
                  description="Otto discovers Wanda is sleeping with Archie and flies into a jealous rage."),
        EventNode(id="EVT_PENDANT_LEFT_AT_ARCHIE_HOME", fabula_time=800, syuzhet_index=8, event_type="outcome",
                  actor_ids=["ENT_WANDA"], target_ids=["OBJ_LOCKET"],
                  description="Wanda accidentally leaves her pendant at Archie's house."),
        EventNode(id="EVT_WENDY_MISREADS_PENDANT", fabula_time=900, syuzhet_index=9, event_type="revelation",
                  actor_ids=["ENT_WENDY"], target_ids=["OBJ_LOCKET"],
                  description="Wendy finds the pendant and mistakes it as a gift for her from Archie."),
        EventNode(id="EVT_ARCHIE_STAGES_BURGLARY", fabula_time=1000, syuzhet_index=10, event_type="choice",
                  actor_ids=["ENT_ARCHIE"], target_ids=["OBJ_LOCKET"],
                  description="At Wanda's insistence, Archie recovers the pendant by staging a burglary at his own home."),
        EventNode(id="EVT_ARCHIE_ENDS_AFFAIR", fabula_time=1200, syuzhet_index=12, event_type="choice",
                  actor_ids=["ENT_ARCHIE"], target_ids=["ENT_WANDA"],
                  description="Feeling guilty, Archie ends the affair with Wanda."),
        EventNode(id="EVT_KEN_KILLS_DOGS", fabula_time=1300, syuzhet_index=13, event_type="outcome",
                  actor_ids=["ENT_KEN"], target_ids=["ENT_MRS_COADY"],
                  description="Ken accidentally kills Mrs Coady's dogs while trying to silence her as a witness."),
        EventNode(id="EVT_MRS_COADY_DIES_HEART_ATTACK", fabula_time=1400, syuzhet_index=14, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_MRS_COADY"],
                  description="Mrs Coady dies of a heart attack triggered by the shock of the staged dog killings."),
        EventNode(id="EVT_WANDA_TESTIFIES_AGAINST_GEORGE", fabula_time=1500, syuzhet_index=15, event_type="choice",
                  actor_ids=["ENT_WANDA"], target_ids=["ENT_GEORGE"],
                  description="At George's trial, defence witness Wanda unexpectedly gives evidence against him."),
        EventNode(id="EVT_ARCHIE_CALLS_WANDA_DARLING", fabula_time=1600, syuzhet_index=16, event_type="outcome",
                  actor_ids=["ENT_ARCHIE"], target_ids=["ENT_WANDA"],
                  description="Stunned, Archie flubs his cross-examination and calls Wanda 'darling' in open court."),
        EventNode(id="EVT_WENDY_DECIDES_DIVORCE", fabula_time=1700, syuzhet_index=17, event_type="choice",
                  actor_ids=["ENT_WENDY"], target_ids=["ENT_ARCHIE"],
                  description="Wendy realises Archie has had an affair and decides to divorce him."),
        EventNode(id="EVT_OTTO_INTERROGATES_KEN", fabula_time=1900, syuzhet_index=19, event_type="choice",
                  actor_ids=["ENT_OTTO"], target_ids=["ENT_KEN"],
                  description="Otto tortures Ken with his own fish to get the diamond location, leaving Ken's favourite (named Wanda) until last."),
        EventNode(id="EVT_GEORGE_CONVICTED", fabula_time=1800, syuzhet_index=18, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_GEORGE"],
                  description="George is convicted; Archie's defence fails."),
        EventNode(id="EVT_GEORGE_INFORMS_ARCHIE_ABOUT_KEN", fabula_time=2000, syuzhet_index=20, event_type="revelation",
                  actor_ids=["ENT_GEORGE"], target_ids=["ENT_ARCHIE"],
                  description="Promised less jail time, George tells Archie that Ken knows where the diamonds are."),
        EventNode(id="EVT_AIRPORT_CHASE", fabula_time=2100, syuzhet_index=21, event_type="outcome",
                  actor_ids=["ENT_WANDA", "ENT_ARCHIE", "ENT_OTTO", "ENT_KEN"], target_ids=[],
                  description="Archie pulls Wanda into his car and races to Ken's flat; Otto steals the car with Wanda inside; Ken and Archie give chase."),
        EventNode(id="EVT_WANDA_DOUBLECROSSES_OTTO", fabula_time=2200, syuzhet_index=22, event_type="choice",
                  actor_ids=["ENT_WANDA"], target_ids=["ENT_OTTO"],
                  description="After recovering the diamonds, Wanda double-crosses Otto and leaves him unconscious in a broom cupboard."),
        EventNode(id="EVT_OTTO_SHOOTS_OUT_CUPBOARD", fabula_time=2300, syuzhet_index=23, event_type="outcome",
                  actor_ids=["ENT_OTTO"], target_ids=[],
                  description="Otto recovers and shoots his way out of the broom cupboard, then confronts Archie."),
        EventNode(id="EVT_ARCHIE_TAUNTS_OTTO_VIETNAM", fabula_time=2400, syuzhet_index=24, event_type="choice",
                  actor_ids=["ENT_ARCHIE"], target_ids=["ENT_OTTO"],
                  description="Archie stalls Otto by taunting him about American failures such as the Vietnam War."),
        EventNode(id="EVT_OTTO_STEAMROLLED", fabula_time=2500, syuzhet_index=25, event_type="outcome",
                  actor_ids=["ENT_KEN"], target_ids=["ENT_OTTO"],
                  description="Ken arrives driving a steamroller seeking vengeance for the fish; Otto, stuck in wet concrete, is run over but survives."),
        EventNode(id="EVT_ARCHIE_WANDA_FLY_AWAY", fabula_time=2600, syuzhet_index=26, event_type="outcome",
                  actor_ids=["ENT_ARCHIE", "ENT_WANDA"], target_ids=[],
                  description="Archie leaps aboard the Rio-bound jet at the last moment; he and Wanda fly off together with the diamonds, leaving Wendy and English respectability behind."),
        EventNode(id="EVT_OTTO_CLINGS_TO_PLANE", fabula_time=2700, syuzhet_index=27, event_type="outcome",
                  actor_ids=["ENT_OTTO"], target_ids=[],
                  description="Otto, having pursued them onto the runway, clings to the plane's window from outside and curses Archie and Wanda."),
        EventNode(id="EVT_OTTO_BLOWN_OFF_DURING_TAKEOFF", fabula_time=2800, syuzhet_index=28, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_OTTO"],
                  description="Otto is blown off the plane during takeoff."),
    ],
    causal_topology=[
        # chain_reaction
        CausalEdge(source_id="EVT_HEIST", target_id="EVT_WANDA_BETRAYS_GEORGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100, propagation_delay=200),
        CausalEdge(source_id="EVT_DIAMONDS_MOVED", target_id="EVT_WANDA_BETRAYS_GEORGE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200, propagation_delay=100),
        CausalEdge(source_id="EVT_DIAMONDS_MOVED", target_id="EVT_WANDA_FINDS_KEY_IN_TANK",
                   causality_type="chain_reaction", mechanism="epistemic_revelation", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200, propagation_delay=140),
        CausalEdge(source_id="EVT_WANDA_FINDS_KEY_IN_TANK", target_id="EVT_WANDA_HIDES_KEY_IN_PENDANT",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=400, propagation_delay=80),
        CausalEdge(source_id="EVT_WANDA_BETRAYS_GEORGE", target_id="EVT_ARCHIE_DEFENDS_GEORGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300, propagation_delay=300),
        CausalEdge(source_id="EVT_ARCHIE_DEFENDS_GEORGE", target_id="EVT_WANDA_SEDUCES_ARCHIE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=600, propagation_delay=100),
        CausalEdge(source_id="EVT_WANDA_SEDUCES_ARCHIE", target_id="EVT_OTTO_DISCOVERS_BETRAYAL",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=700, propagation_delay=100),
        CausalEdge(source_id="EVT_OTTO_DISCOVERS_BETRAYAL", target_id="EVT_OTTO_INTERROGATES_KEN",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1100, propagation_delay=220),
        CausalEdge(source_id="EVT_WANDA_SEDUCES_ARCHIE", target_id="EVT_PENDANT_LEFT_AT_ARCHIE_HOME",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=700, propagation_delay=60),
        CausalEdge(source_id="EVT_PENDANT_LEFT_AT_ARCHIE_HOME", target_id="EVT_WENDY_MISREADS_PENDANT",
                   causality_type="chain_reaction", mechanism="epistemic_revelation", evidence_strength="strong",
                   causal_force=7.0, fabula_time=800, propagation_delay=100),
        CausalEdge(source_id="EVT_WENDY_MISREADS_PENDANT", target_id="EVT_ARCHIE_STAGES_BURGLARY",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900, propagation_delay=15),
        CausalEdge(source_id="EVT_OTTO_DISCOVERS_BETRAYAL", target_id="EVT_ARCHIE_ENDS_AFFAIR",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1100, propagation_delay=20),
        CausalEdge(source_id="EVT_KEN_KILLS_DOGS", target_id="EVT_MRS_COADY_DIES_HEART_ATTACK",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=1300, propagation_delay=40),
        CausalEdge(source_id="EVT_MRS_COADY_DIES_HEART_ATTACK", target_id="EVT_WANDA_TESTIFIES_AGAINST_GEORGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1400, propagation_delay=20),
        CausalEdge(source_id="EVT_WANDA_TESTIFIES_AGAINST_GEORGE", target_id="EVT_ARCHIE_CALLS_WANDA_DARLING",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1500, propagation_delay=10),
        CausalEdge(source_id="EVT_ARCHIE_CALLS_WANDA_DARLING", target_id="EVT_WENDY_DECIDES_DIVORCE",
                   causality_type="chain_reaction", mechanism="epistemic_revelation", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1600, propagation_delay=5),
        CausalEdge(source_id="EVT_WANDA_TESTIFIES_AGAINST_GEORGE", target_id="EVT_GEORGE_CONVICTED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500, propagation_delay=40),
        CausalEdge(source_id="EVT_GEORGE_CONVICTED", target_id="EVT_GEORGE_INFORMS_ARCHIE_ABOUT_KEN",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1800, propagation_delay=40),
        CausalEdge(source_id="EVT_GEORGE_INFORMS_ARCHIE_ABOUT_KEN", target_id="EVT_AIRPORT_CHASE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=2000, propagation_delay=60),
        CausalEdge(source_id="EVT_AIRPORT_CHASE", target_id="EVT_WANDA_DOUBLECROSSES_OTTO",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2100, propagation_delay=20),
        CausalEdge(source_id="EVT_WANDA_DOUBLECROSSES_OTTO", target_id="EVT_OTTO_SHOOTS_OUT_CUPBOARD",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=2200, propagation_delay=20),
        CausalEdge(source_id="EVT_OTTO_SHOOTS_OUT_CUPBOARD", target_id="EVT_ARCHIE_TAUNTS_OTTO_VIETNAM",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2300, propagation_delay=10),
        CausalEdge(source_id="EVT_OTTO_INTERROGATES_KEN", target_id="EVT_OTTO_STEAMROLLED",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.5, fabula_time=1900, propagation_delay=180),
        CausalEdge(source_id="EVT_ARCHIE_TAUNTS_OTTO_VIETNAM", target_id="EVT_OTTO_STEAMROLLED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=2400, propagation_delay=50),
        CausalEdge(source_id="EVT_OTTO_STEAMROLLED", target_id="EVT_ARCHIE_WANDA_FLY_AWAY",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="weak",
                   causal_force=3.0, fabula_time=2500, propagation_delay=20),
        CausalEdge(source_id="EVT_ARCHIE_WANDA_FLY_AWAY", target_id="EVT_OTTO_CLINGS_TO_PLANE",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2600, propagation_delay=10),
        CausalEdge(source_id="EVT_OTTO_CLINGS_TO_PLANE", target_id="EVT_OTTO_BLOWN_OFF_DURING_TAKEOFF",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=2700, propagation_delay=10),
        CausalEdge(source_id="EVT_ARCHIE_WANDA_FLY_AWAY", target_id="ENT_ARCHIE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=2600, trait_target="passion", trait_delta=0.2),
        CausalEdge(source_id="EVT_ARCHIE_WANDA_FLY_AWAY", target_id="ENT_ARCHIE",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=2600,
                   trait_target="affinity", trait_delta=0.5, rel_counterpart_id="ENT_WANDA"),
        CausalEdge(source_id="EVT_ARCHIE_WANDA_FLY_AWAY", target_id="ENT_ARCHIE",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=2600,
                   trait_target="affinity", trait_delta=-0.8, rel_counterpart_id="ENT_WENDY"),
        CausalEdge(source_id="EVT_ARCHIE_STAGES_BURGLARY", target_id="ENT_ARCHIE",
                   causality_type="mutation", mechanism="betrayal", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1000, trait_target="propriety", trait_delta=-0.25),
        CausalEdge(source_id="EVT_ARCHIE_ENDS_AFFAIR", target_id="ENT_ARCHIE",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=1200,
                   trait_target="affinity", trait_delta=-0.35, rel_counterpart_id="ENT_WANDA"),
        CausalEdge(source_id="EVT_WANDA_DOUBLECROSSES_OTTO", target_id="ENT_OTTO",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=2200,
                   trait_target="affinity", trait_delta=-0.8, rel_counterpart_id="ENT_WANDA"),
        # mutation
        CausalEdge(source_id="EVT_WANDA_SEDUCES_ARCHIE", target_id="ENT_ARCHIE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=700, trait_target="passion", trait_delta=0.4),
        CausalEdge(source_id="EVT_OTTO_DISCOVERS_BETRAYAL", target_id="ENT_OTTO",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1100, trait_target="jealousy", trait_delta=0.15),
        CausalEdge(source_id="EVT_KEN_KILLS_DOGS", target_id="ENT_KEN",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1300, trait_target="determination", trait_delta=0.2),
        CausalEdge(source_id="EVT_OTTO_INTERROGATES_KEN", target_id="ENT_KEN",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1900, trait_target="determination", trait_delta=0.2),
        # mutation_social
        CausalEdge(source_id="EVT_WANDA_SEDUCES_ARCHIE", target_id="ENT_WANDA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=700, propagation_delay=40, trait_target="affinity", trait_delta=0.3, rel_counterpart_id="ENT_ARCHIE"),
        CausalEdge(source_id="EVT_OTTO_DISCOVERS_BETRAYAL", target_id="ENT_OTTO",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1100, trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_WANDA"),
        CausalEdge(source_id="EVT_OTTO_INTERROGATES_KEN", target_id="ENT_KEN",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1900, trait_target="affinity", trait_delta=-0.7, rel_counterpart_id="ENT_OTTO"),
        # ── additional mutations to cover canon-significant events ──
        # Wanda+Otto's tip-off: George's affinity toward Wanda craters and his betrayal-awareness spikes.
        CausalEdge(source_id="EVT_WANDA_BETRAYS_GEORGE", target_id="ENT_GEORGE",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300,
                   trait_target="affinity", trait_delta=-0.9, rel_counterpart_id="ENT_WANDA"),
        CausalEdge(source_id="EVT_WANDA_BETRAYS_GEORGE", target_id="ENT_GEORGE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300, trait_target="paranoia", trait_delta=0.25),
        # Hiding the key in the locket — Wanda's secrecy crystallises around the diamonds.
        CausalEdge(source_id="EVT_WANDA_HIDES_KEY_IN_PENDANT", target_id="ENT_WANDA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=500, trait_target="cunning", trait_delta=0.05),
        # Archie defending George — a professional tie of barrister to client.
        CausalEdge(source_id="EVT_ARCHIE_DEFENDS_GEORGE", target_id="ENT_ARCHIE",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=600,
                   trait_target="affinity", trait_delta=0.2, rel_counterpart_id="ENT_GEORGE"),
        CausalEdge(source_id="EVT_ARCHIE_DEFENDS_GEORGE", target_id="ENT_ARCHIE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=600, trait_target="propriety", trait_delta=0.05),
        # Pendant left at Archie's — Wanda's normally-flawless tradecraft slips.
        CausalEdge(source_id="EVT_PENDANT_LEFT_AT_ARCHIE_HOME", target_id="ENT_WANDA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=800, trait_target="opportunism", trait_delta=-0.05),
        # Mrs Coady's heart attack — Ken's guilt deepens for a botched intimidation that killed an innocent.
        CausalEdge(source_id="EVT_MRS_COADY_DIES_HEART_ATTACK", target_id="ENT_KEN",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1400, trait_target="guilt", trait_delta=0.15),
        # Wendy misreads the pendant — her affinity (briefly) softens toward Archie.
        CausalEdge(source_id="EVT_WENDY_MISREADS_PENDANT", target_id="ENT_WENDY",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=900,
                   trait_target="affinity", trait_delta=0.15, rel_counterpart_id="ENT_ARCHIE"),
        # Archie stages the burglary at his own home — propriety already fractured, his power-balance with Wanda shifts.
        CausalEdge(source_id="EVT_ARCHIE_STAGES_BURGLARY", target_id="ENT_ARCHIE",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1000,
                   trait_target="power_dynamic", trait_delta=-0.2, rel_counterpart_id="ENT_WANDA"),
        # Wanda testifies against George in court — courtroom betrayal cements George's hatred.
        CausalEdge(source_id="EVT_WANDA_TESTIFIES_AGAINST_GEORGE", target_id="ENT_GEORGE",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500,
                   trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_WANDA"),
        CausalEdge(source_id="EVT_WANDA_TESTIFIES_AGAINST_GEORGE", target_id="ENT_GEORGE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1500, trait_target="vindictiveness", trait_delta=0.3),
        # Archie's 'darling' slip — propriety craters; awakening rises.
        CausalEdge(source_id="EVT_ARCHIE_CALLS_WANDA_DARLING", target_id="ENT_ARCHIE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1600, trait_target="propriety", trait_delta=-0.3),
        # Wendy decides to divorce Archie — affinity collapses toward him.
        CausalEdge(source_id="EVT_WENDY_DECIDES_DIVORCE", target_id="ENT_WENDY",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1700,
                   trait_target="affinity", trait_delta=-0.7, rel_counterpart_id="ENT_ARCHIE"),
        # George's plea-deal disclosure — professionalism slips as he sells out Ken.
        CausalEdge(source_id="EVT_GEORGE_INFORMS_ARCHIE_ABOUT_KEN", target_id="ENT_GEORGE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=2000, trait_target="professionalism", trait_delta=-0.2),
        # George conviction — the verdict crystallises his vindictiveness.
        CausalEdge(source_id="EVT_GEORGE_CONVICTED", target_id="ENT_GEORGE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1800, trait_target="vindictiveness", trait_delta=0.2),
        # Otto steamrolled & blown off plane — his stability nosedives as physical injury compounds rage.
        CausalEdge(source_id="EVT_OTTO_STEAMROLLED", target_id="ENT_OTTO",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=2500, trait_target="stability", trait_delta=-0.4),
        CausalEdge(source_id="EVT_OTTO_BLOWN_OFF_DURING_TAKEOFF", target_id="ENT_OTTO",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2800, trait_target="vengeance", trait_delta=0.05),
        # affordance_gate
        CausalEdge(source_id="OBJ_DIAMONDS", target_id="EVT_HEIST",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="ENT_WANDA", target_id="EVT_WANDA_SEDUCES_ARCHIE",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=700),
        CausalEdge(source_id="OBJ_STEAMROLLER", target_id="EVT_OTTO_STEAMROLLED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=2500),
        CausalEdge(source_id="OBJ_LOCKET", target_id="EVT_WANDA_HIDES_KEY_IN_PENDANT",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500),
        CausalEdge(source_id="OBJ_LOCKET", target_id="EVT_WENDY_MISREADS_PENDANT",
                   causality_type="affordance_gate", mechanism="epistemic_revelation", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900),
        CausalEdge(source_id="ENT_KEN", target_id="EVT_OTTO_STEAMROLLED",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2500),
        # ambient_propagation
        CausalEdge(source_id="LOC_OLD_BAILEY", target_id="ENT_ARCHIE",
                   causality_type="ambient_propagation", mechanism="social", evidence_strength="weak",
                   causal_force=2.0, fabula_time=600),
        CausalEdge(source_id="ENT_OTTO", target_id="ENT_KEN",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=1100),
        CausalEdge(source_id="LOC_ARCHIE_FLAT", target_id="ENT_WENDY",
                   causality_type="ambient_propagation", mechanism="social", evidence_strength="moderate",
                   causal_force=3.0, fabula_time=900),
        CausalEdge(source_id="LOC_WANDA_FLAT", target_id="ENT_ARCHIE",
                   causality_type="ambient_propagation", mechanism="emotional", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=700),
        CausalEdge(source_id="LOC_AIRPORT_RUNWAY", target_id="ENT_OTTO",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=2700),
    
        # ── WORLD_ → Event (named-latent common-cause wiring) ──
        CausalEdge(source_id="WORLD_HEIST_HONOUR", target_id="EVT_WANDA_BETRAYS_GEORGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=300),
        CausalEdge(source_id="WORLD_HEIST_HONOUR", target_id="EVT_OTTO_DISCOVERS_BETRAYAL",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="weak",
                   causal_force=3.0, fabula_time=1100),
        CausalEdge(source_id="WORLD_ANGLO_AMERICAN_CLASH", target_id="EVT_WANDA_SEDUCES_ARCHIE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=700),
        CausalEdge(source_id="WORLD_ANGLO_AMERICAN_CLASH", target_id="EVT_OTTO_INTERROGATES_KEN",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="weak",
                   causal_force=3.0, fabula_time=1900),
        # WORLD_DOUBLE_CROSS_ECONOMY edges
        CausalEdge(source_id="WORLD_DOUBLE_CROSS_ECONOMY", target_id="EVT_WANDA_BETRAYS_GEORGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.5, fabula_time=300),
        CausalEdge(source_id="WORLD_DOUBLE_CROSS_ECONOMY", target_id="EVT_WANDA_TESTIFIES_AGAINST_GEORGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.5, fabula_time=1500),
        CausalEdge(source_id="WORLD_DOUBLE_CROSS_ECONOMY", target_id="EVT_WANDA_DOUBLECROSSES_OTTO",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=2200),
        # WORLD_RESPECTABILITY_PRESSURE edges
        CausalEdge(source_id="WORLD_RESPECTABILITY_PRESSURE", target_id="EVT_ARCHIE_ENDS_AFFAIR",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1200),
        CausalEdge(source_id="WORLD_RESPECTABILITY_PRESSURE", target_id="EVT_WENDY_DECIDES_DIVORCE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1700),
        CausalEdge(source_id="WORLD_RESPECTABILITY_PRESSURE", target_id="EVT_ARCHIE_WANDA_FLY_AWAY",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="weak",
                   causal_force=3.0, fabula_time=2600),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_HEATHROW", target_id="LOC_GEORGE_FLAT"),
        SpatialEdge(source_id="LOC_HEATHROW", target_id="LOC_HEATHROW_HOTEL"),
        SpatialEdge(source_id="LOC_HEATHROW", target_id="LOC_AIRPORT_RUNWAY"),
        SpatialEdge(source_id="LOC_GEORGE_FLAT", target_id="LOC_OLD_WORKSHOP"),
        SpatialEdge(source_id="LOC_GEORGE_FLAT", target_id="LOC_WANDA_FLAT"),
        SpatialEdge(source_id="LOC_WANDA_FLAT", target_id="LOC_ARCHIE_FLAT"),
        SpatialEdge(source_id="LOC_GEORGE_FLAT", target_id="LOC_OLD_BAILEY"),
        SpatialEdge(source_id="LOC_GEORGE_FLAT", target_id="LOC_HIDEOUT_GARAGE"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_WANDA", target_ids=["ENT_ARCHIE"], medium="seduction", established_at_fabula=700, discovered_at_syuzhet=5, evidence_strength='moderate'),
        InformationEdge(source_id="ENT_KEN", target_ids=["ENT_OTTO"], medium="torture", established_at_fabula=1900, discovered_at_syuzhet=10, evidence_strength='moderate'),
        InformationEdge(source_id="ENT_WANDA", target_ids=["ENT_GEORGE", "ENT_KEN", "ENT_ARCHIE"],
                        medium="court_testimony", is_encrypted=False,
                        established_at_fabula=1500, discovered_at_syuzhet=9, evidence_strength='strong'),
        InformationEdge(source_id="ENT_ARCHIE", target_ids=["ENT_WENDY"],
                        medium="accidental_endearment", is_encrypted=False,
                        established_at_fabula=1600, terminated_at_fabula=1600, discovered_at_syuzhet=9, evidence_strength='moderate'),
        InformationEdge(source_id="ENT_OTTO", target_ids=["ENT_WANDA"],
                        medium="surveillance", is_encrypted=False, established_at_fabula=800, discovered_at_syuzhet=6, evidence_strength='weak'),
        InformationEdge(source_id="ENT_KEN", target_ids=["ENT_GEORGE"],
                        medium="prison_correspondence", is_encrypted=True, established_at_fabula=1200, discovered_at_syuzhet=7, evidence_strength='moderate'),
        InformationEdge(source_id="ENT_OTTO", target_ids=["ENT_KEN"],
                        medium="torture_interrogation", established_at_fabula=1900, discovered_at_syuzhet=10, evidence_strength='moderate'),
        InformationEdge(source_id="ENT_WENDY", target_ids=["ENT_ARCHIE"],
                        medium="possession_of_pendant", is_encrypted=False,
                        established_at_fabula=900, discovered_at_syuzhet=6, evidence_strength='moderate'),
        InformationEdge(source_id="ENT_GEORGE", target_ids=["ENT_ARCHIE"],
                        medium="plea_deal_disclosure", is_encrypted=False,
                        established_at_fabula=2000, discovered_at_syuzhet=10, evidence_strength='moderate'),
    ],
    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_HEIST_HONOUR": GlobalTrait(
            id="WORLD_HEIST_HONOUR",
            name="Thieves' Honour",
            description="The fragile code of loyalty among diamond thieves — easily broken when greed, lust, or self-preservation intervene.",
            category="social_structure",
            magnitude=TraitVector(value=0.6, inertia=0.4, evidence_strength="moderate"),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=200, triggered_by="EVT_DIAMONDS_MOVED",
                    magnitude=TraitVector(value=0.3, inertia=0.3, evidence_strength="strong"),
                    description="Everyone begins scheming to keep the diamonds for themselves — honour disintegrates."),
                WorldTraitSnapshot(fabula_time=2200, triggered_by="EVT_WANDA_DOUBLECROSSES_OTTO",
                    magnitude=TraitVector(value=0.05, inertia=0.3, evidence_strength="strong"),
                    description="With Wanda crossing Otto in the broom cupboard, the code is dead."),
            ],
        ),
        "WORLD_ANGLO_AMERICAN_CLASH": GlobalTrait(
            id="WORLD_ANGLO_AMERICAN_CLASH",
            name="Anglo-American Cultural Clash",
            description="The collision between brash American confidence (Wanda, Otto) and stiff English propriety (Archie, the legal world) drives the comedy.",
            category="social_structure",
            magnitude=TraitVector(value=0.7, inertia=0.6, evidence_strength="strong"),
            affected_domains=["social"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=2400, triggered_by="EVT_ARCHIE_TAUNTS_OTTO_VIETNAM",
                    magnitude=TraitVector(value=0.95, inertia=0.6, evidence_strength="strong"),
                    description="Archie weaponises English condescension about Vietnam against an armed American — the clash boils over."),
            ],
        ),
        "WORLD_DOUBLE_CROSS_ECONOMY": GlobalTrait(
            id="WORLD_DOUBLE_CROSS_ECONOMY",
            name="Double-Cross Economy",
            description="In this gangland milieu, every alliance is a temporary contract: Wanda double-crosses George, then Otto, then arguably Archie. Betrayal is the default settlement currency.",
            category="economy",
            magnitude=TraitVector(value=0.85, inertia=0.55, evidence_strength="strong"),
            affected_domains=["social", "betrayal"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=1500, triggered_by="EVT_WANDA_TESTIFIES_AGAINST_GEORGE",
                    magnitude=TraitVector(value=0.9, inertia=0.55, evidence_strength="strong"),
                    description="Wanda's courtroom turn confirms: any partner is a future witness."),
                WorldTraitSnapshot(fabula_time=2200, triggered_by="EVT_WANDA_DOUBLECROSSES_OTTO",
                    magnitude=TraitVector(value=0.95, inertia=0.55, evidence_strength="strong"),
                    description="Wanda's serial betrayals — George, then Otto — saturate the economy."),
            ],
        ),
        "WORLD_RESPECTABILITY_PRESSURE": GlobalTrait(
            id="WORLD_RESPECTABILITY_PRESSURE",
            name="English Respectability Pressure",
            description="English middle-class respectability — marriage, propriety, courtroom decorum — exerts a constant constraint on Archie and Wendy that the affair, the courtroom slip, and the final flight all transgress.",
            category="social_structure",
            magnitude=TraitVector(value=0.8, inertia=0.7, evidence_strength="strong"),
            affected_domains=["social", "emotional"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=1600, triggered_by="EVT_ARCHIE_CALLS_WANDA_DARLING",
                    magnitude=TraitVector(value=0.6, inertia=0.65, evidence_strength="strong"),
                    description="Archie's slip in open court fractures the decorum that has held him in place."),
                WorldTraitSnapshot(fabula_time=2600, triggered_by="EVT_ARCHIE_WANDA_FLY_AWAY",
                    magnitude=TraitVector(value=0.2, inertia=0.6, evidence_strength="strong"),
                    description="With Archie literally airborne to Rio, the pressure has been thrown off entirely."),
            ],
        ),
    },
    social_topology=[
        RelationshipEdge(
            source_entity_id='ENT_WANDA', target_entity_id='ENT_OTTO',
            metrics={
                    "affinity":      RelationshipMetric(value=0.75, inertia=0.46, evidence_strength='moderate'),
                    "fear":          RelationshipMetric(value=0.1, inertia=0.17, evidence_strength='weak'),
                    "power_dynamic": RelationshipMetric(value=0.3, inertia=0.57, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_OTTO', target_entity_id='ENT_WANDA',
            metrics={
                    "affinity":      RelationshipMetric(value=0.85, inertia=0.52, evidence_strength='strong', last_updated_fabula=2200),
                    "fear":          RelationshipMetric(value=0.0, inertia=0.17, evidence_strength='weak', observed=False),
                    "power_dynamic": RelationshipMetric(value=-0.2, inertia=0.57, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_WANDA', target_entity_id='ENT_ARCHIE',
            metrics={
                    "affinity":      RelationshipMetric(value=0.6, inertia=0.45, evidence_strength='moderate', last_updated_fabula=700),
                    "fear":          RelationshipMetric(value=0.0, inertia=0.17, evidence_strength='weak', observed=False),
                    "power_dynamic": RelationshipMetric(value=0.2, inertia=0.57, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_ARCHIE', target_entity_id='ENT_WANDA',
            metrics={
                    "affinity":      RelationshipMetric(value=0.85, inertia=0.52, evidence_strength='strong', last_updated_fabula=2600),
                    "fear":          RelationshipMetric(value=0.0, inertia=0.17, evidence_strength='weak', observed=False),
                    "power_dynamic": RelationshipMetric(value=-0.2, inertia=0.57, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_KEN', target_entity_id='ENT_GEORGE',
            metrics={
                    "affinity":      RelationshipMetric(value=0.7, inertia=0.46, evidence_strength='moderate'),
                    "fear":          RelationshipMetric(value=0.0, inertia=0.17, evidence_strength='weak', observed=False),
                    "power_dynamic": RelationshipMetric(value=-0.3, inertia=0.57, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_KEN', target_entity_id='ENT_OTTO',
            metrics={
                    "affinity":      RelationshipMetric(value=-0.3, inertia=0.47, evidence_strength='strong', last_updated_fabula=1900),
                    "fear":          RelationshipMetric(value=0.5, inertia=0.15, evidence_strength='weak'),
                    "power_dynamic": RelationshipMetric(value=-0.5, inertia=0.59, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_OTTO', target_entity_id='ENT_KEN',
            metrics={
                    "affinity":      RelationshipMetric(value=-0.2, inertia=0.37, evidence_strength='weak'),
                    "fear":          RelationshipMetric(value=0.0, inertia=0.17, evidence_strength='weak', observed=False),
                    "power_dynamic": RelationshipMetric(value=0.5, inertia=0.59, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_OTTO', target_entity_id='ENT_ARCHIE',
            metrics={
                    "affinity":      RelationshipMetric(value=-0.6, inertia=0.4, evidence_strength='weak'),
                    "fear":          RelationshipMetric(value=0.0, inertia=0.17, evidence_strength='weak', observed=False),
                    "power_dynamic": RelationshipMetric(value=0.3, inertia=0.57, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_GEORGE', target_entity_id='ENT_KEN',
            metrics={
                    "affinity":      RelationshipMetric(value=0.5, inertia=0.39, evidence_strength='weak'),
                    "fear":          RelationshipMetric(value=0.0, inertia=0.17, evidence_strength='weak', observed=False),
                    "power_dynamic": RelationshipMetric(value=0.3, inertia=0.57, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_WENDY', target_entity_id='ENT_ARCHIE',
            metrics={
                    "affinity":      RelationshipMetric(value=0.2, inertia=0.37, evidence_strength='weak'),
                    "fear":          RelationshipMetric(value=0.0, inertia=0.17, evidence_strength='weak', observed=False),
                    "power_dynamic": RelationshipMetric(value=0.4, inertia=0.58, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_ARCHIE', target_entity_id='ENT_WENDY',
            metrics={
                    "affinity":      RelationshipMetric(value=0.2, inertia=0.47, evidence_strength='strong', last_updated_fabula=2600),
                    "fear":          RelationshipMetric(value=0.3, inertia=0.16, evidence_strength='weak'),
                    "power_dynamic": RelationshipMetric(value=-0.4, inertia=0.58, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_WANDA', target_entity_id='ENT_KEN',
            metrics={
                    "affinity":      RelationshipMetric(value=0.3, inertia=0.37, evidence_strength='weak'),
                    "fear":          RelationshipMetric(value=0.0, inertia=0.17, evidence_strength='weak', observed=False),
                    "power_dynamic": RelationshipMetric(value=0.4, inertia=0.58, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_GEORGE', target_entity_id='ENT_WANDA',
            metrics={
                    "affinity":      RelationshipMetric(value=-0.6, inertia=0.4, evidence_strength='weak'),
                    "fear":          RelationshipMetric(value=0.0, inertia=0.17, evidence_strength='weak', observed=False),
                    "power_dynamic": RelationshipMetric(value=-0.2, inertia=0.57, evidence_strength='weak'),
                },
        ),
        RelationshipEdge(
            source_entity_id='ENT_GEORGE', target_entity_id='ENT_OTTO',
            metrics={
                    "affinity":      RelationshipMetric(value=-0.5, inertia=0.39, evidence_strength='weak'),
                    "fear":          RelationshipMetric(value=0.0, inertia=0.17, evidence_strength='weak', observed=False),
                    "power_dynamic": RelationshipMetric(value=-0.2, inertia=0.57, evidence_strength='weak'),
                },
        ),
    ],
)
