"""Apocalypse Now — high-fidelity WorldStateV1 test fixture.

Quality checklist (all five causality modalities, varied force/evidence,
trait_target/trait_delta, state_timeline, rich beliefs, info edges, constants).
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_SAIGON_HOTEL": Location(name="Saigon Hotel Room",
            description="Willard's hotel room where he awaits his mission.",
            ambient_state={"despair": AmbientVector(value=0.7, volatility=0.4),
                           "heat": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_NHA_TRANG_HQ": Location(name="Nha Trang Intelligence HQ",
            description="Military intelligence briefing room.",
            ambient_state={"formality": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_PBR_BOAT": Location(name="PBR Street Gang Boat",
            description="Patrol boat travelling upriver into Cambodia.",
            ambient_state={"tension": AmbientVector(value=0.7, volatility=0.5),
                           "isolation": AmbientVector(value=0.6, volatility=0.4)}),
        "LOC_KILGORE_BEACH": Location(name="Vin Drin Dop Beach",
            description="Beach where Kilgore launches his helicopter assault.",
            ambient_state={"chaos": AmbientVector(value=0.9, volatility=0.3)}),
        "LOC_DO_LUNG_BRIDGE": Location(name="Do Lung Bridge",
            description="Last army outpost, leaderless and under nightly attack.",
            ambient_state={"chaos": AmbientVector(value=0.9, volatility=0.2),
                           "madness": AmbientVector(value=0.8, volatility=0.3)}),
        "LOC_KURTZ_COMPOUND": Location(name="Kurtz's Compound",
            description="Kurtz's temple compound deep in Cambodia.",
            ambient_state={"madness": AmbientVector(value=0.9, volatility=0.2),
                           "terror": AmbientVector(value=0.8, volatility=0.3)}),
        "LOC_JUNGLE": Location(name="Nung River Jungle",
            description="Dense jungle along the river where tigers and VC lurk.",
            ambient_state={"danger": AmbientVector(value=0.8, volatility=0.4),
                           "primeval": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_USO_DEPOT": Location(name="Supply Depot",
            description="US base supply depot with amphitheatre for USO shows.",
            ambient_state={"frenzy": AmbientVector(value=0.7, volatility=0.4)}),
    },
    objects={
        "OBJ_DOSSIER": NarrativeObject(id="OBJ_DOSSIER", name="Kurtz Dossier",
            location_id=None, owner_id="ENT_WILLARD",
            properties={"state": "classified", "content": "kurtz_history"},
            affordances=[Affordance(action="inform", target_type="Entity")]),
        "OBJ_SURFBOARD": NarrativeObject(id="OBJ_SURFBOARD", name="Lance's Surfboard",
            location_id="LOC_PBR_BOAT", owner_id="ENT_LANCE",
            properties={"state": "waxed"},
            affordances=[Affordance(action="surf", target_type="Entity")]),
        "OBJ_MACHETE": NarrativeObject(id="OBJ_MACHETE", name="Sacrificial Machete",
            location_id="LOC_KURTZ_COMPOUND", owner_id=None,
            properties={"state": "bloodied"},
            affordances=[Affordance(action="kill", target_type="Entity")]),
        "OBJ_PBR_RADIO": NarrativeObject(id="OBJ_PBR_RADIO", name="PBR Radio",
            location_id="LOC_PBR_BOAT", owner_id=None,
            properties={"state": "functional"},
            affordances=[Affordance(action="call_airstrike", target_type="Location")]),
        "OBJ_MAIL_PACKET": NarrativeObject(id="OBJ_MAIL_PACKET", name="Do Lung Mail Packet",
            location_id="LOC_DO_LUNG_BRIDGE", owner_id=None,
            properties={"state": "sealed", "content": "prior_operative_letter"},
            affordances=[Affordance(action="inform", target_type="Entity")]),
    },
    entities={
        "ENT_WILLARD": Entity(id="ENT_WILLARD", name="Captain Benjamin Willard",
            location_id="LOC_SAIGON_HOTEL", status="healthy",
            traits={
                "discipline": TraitVector(value=0.6, inertia=0.4),
                "darkness": TraitVector(value=0.5, inertia=0.3),
                "resolve": TraitVector(value=0.7, inertia=0.5),
                "empathy": TraitVector(value=0.3, inertia=0.4),
                "madness": TraitVector(value=0.2, inertia=0.2),
                "despair": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_KURTZ", perceived_state="Kurtz is a rogue officer who must be terminated",
                       confidence=0.7, inertia=0.4),
            ],
            constants=["special_forces", "assassin"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=100, triggered_by="EVT_MISSION_BRIEFING",
                    location_id="LOC_NHA_TRANG_HQ"),
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_PBR_DEPARTS",
                    location_id="LOC_PBR_BOAT"),
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_SAMPAN_MASSACRE",
                    traits={"darkness": TraitVector(value=0.75, inertia=0.35),
                            "empathy": TraitVector(value=0.15, inertia=0.4),
                            "remorse": TraitVector(value=0.4, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=1500, triggered_by="EVT_WILLARD_MEETS_KURTZ",
                    location_id="LOC_KURTZ_COMPOUND",
                    traits={"madness": TraitVector(value=0.5, inertia=0.2)},
                    beliefs_invalidated=["ENT_KURTZ"],
                    beliefs_added=[Belief(target_id="ENT_KURTZ",
                        perceived_state="Kurtz has seen the truth of war",
                        confidence=0.6, inertia=0.3, established_at_fabula=1500)]),
                EntityStateSnapshot(fabula_time=1900, triggered_by="EVT_WILLARD_KILLS_KURTZ",
                    traits={"darkness": TraitVector(value=0.85, inertia=0.4),
                            "remorse": TraitVector(value=0.6, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=2200, triggered_by="EVT_WILLARD_DEPARTS",
                    location_id="LOC_PBR_BOAT",
                    beliefs_added=[Belief(target_id="ENT_KURTZ",
                        perceived_state="The mission was the horror; the radio is silence",
                        confidence=0.8, inertia=0.6, established_at_fabula=2200)]),
            ]),
        "ENT_KURTZ": Entity(id="ENT_KURTZ", name="Colonel Walter Kurtz",
            location_id="LOC_KURTZ_COMPOUND", status="healthy",
            traits={
                "intellect": TraitVector(value=0.9, inertia=0.6),
                "madness": TraitVector(value=0.8, inertia=0.5),
                "charisma": TraitVector(value=0.8, inertia=0.5),
                "horror": TraitVector(value=0.9, inertia=0.6),
                "will_to_die": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_WILLARD", perceived_state="Willard is a fellow soldier who can understand",
                       confidence=0.7, inertia=0.4),
            ],
            constants=["green_beret", "god_king"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1900, triggered_by="EVT_WILLARD_KILLS_KURTZ",
                    status="dead"),
            ]),
        "ENT_KILGORE": Entity(id="ENT_KILGORE", name="Lt Colonel Bill Kilgore",
            location_id="LOC_KILGORE_BEACH", status="healthy",
            traits={
                "bravado": TraitVector(value=0.9, inertia=0.6),
                "recklessness": TraitVector(value=0.8, inertia=0.5),
                "charisma": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_LANCE", perceived_state="Lance is a surfer worth risking lives for",
                       confidence=0.6, inertia=0.3),
            ],
            constants=["air_cavalry"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=400, triggered_by="EVT_KILGORE_ASSAULT",
                    traits={"bravado": TraitVector(value=0.95, inertia=0.6)}),
            ]),
        "ENT_CHEF": Entity(id="ENT_CHEF", name="Chef (Frederic Forrest)",
            location_id="LOC_PBR_BOAT", status="healthy",
            traits={
                "anxiety": TraitVector(value=0.7, inertia=0.4),
                "loyalty": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_WILLARD", perceived_state="Willard is leading us to our deaths",
                       confidence=0.6, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_TIGER_ATTACK",
                    traits={"anxiety": TraitVector(value=0.9, inertia=0.55)}),
                EntityStateSnapshot(fabula_time=1700, triggered_by="EVT_CHEF_BEHEADED",
                    status="dead"),
            ]),
        "ENT_CLEAN": Entity(id="ENT_CLEAN", name="Mr Clean (Laurence Fishburne)",
            location_id="LOC_PBR_BOAT", status="healthy",
            traits={
                "youth": TraitVector(value=0.8, inertia=0.5),
                "impulsiveness": TraitVector(value=0.7, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_CHIEF", perceived_state="Chief knows what he's doing",
                       confidence=0.6, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_CLEAN_KILLED",
                    status="dead"),
            ]),
        "ENT_CHIEF": Entity(id="ENT_CHIEF", name="Chief Phillips",
            location_id="LOC_PBR_BOAT", status="healthy",
            traits={
                "duty": TraitVector(value=0.8, inertia=0.6),
                "suspicion": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_WILLARD", perceived_state="Willard's mission is suspicious",
                       confidence=0.7, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_SAMPAN_MASSACRE",
                    traits={"suspicion": TraitVector(value=0.9, inertia=0.5)}),
                EntityStateSnapshot(fabula_time=1400, triggered_by="EVT_CHIEF_KILLED",
                    status="dead"),
            ]),
        "ENT_LANCE": Entity(id="ENT_LANCE", name="Lance B. Johnson",
            location_id="LOC_PBR_BOAT", status="healthy",
            traits={
                "detachment": TraitVector(value=0.6, inertia=0.3),
                "surfer_zen": TraitVector(value=0.7, inertia=0.4),
                "madness": TraitVector(value=0.2, inertia=0.2),
            },
            beliefs=[
                Belief(target_id="ENT_KILGORE", perceived_state="Kilgore is insane but respects surfing",
                       confidence=0.6, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_CREW_DRUG_DISSOCIATION",
                    traits={"madness": TraitVector(value=0.35, inertia=0.3),
                            "detachment": TraitVector(value=0.75, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=1500, triggered_by="EVT_WILLARD_MEETS_KURTZ",
                    location_id="LOC_KURTZ_COMPOUND",
                    traits={"madness": TraitVector(value=0.55, inertia=0.4),
                            "detachment": TraitVector(value=0.85, inertia=0.4)}),
            ]),
        "ENT_PHOTOJOURNALIST": Entity(id="ENT_PHOTOJOURNALIST",
            name="American Photojournalist",
            location_id="LOC_KURTZ_COMPOUND", status="healthy",
            traits={
                "manic_devotion": TraitVector(value=0.95, inertia=0.5),
                "incoherence": TraitVector(value=0.85, inertia=0.5),
                "reverence": TraitVector(value=0.9, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_KURTZ", perceived_state="Kurtz is a poet-warrior god",
                       confidence=0.95, inertia=0.7),
                Belief(target_id="ENT_WILLARD", perceived_state="Willard has been chosen to receive Kurtz's truth",
                       confidence=0.7, inertia=0.4),
            ],
            constants=["freelance_photographer", "kurtz_acolyte"]),
    },
    events=[
        EventNode(id="EVT_MISSION_BRIEFING", fabula_time=100, syuzhet_index=1, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_WILLARD"],
                  description="Willard is briefed at Nha Trang: terminate Colonel Kurtz with extreme prejudice."),
        EventNode(id="EVT_PBR_DEPARTS", fabula_time=200, syuzhet_index=2, event_type="outcome",
                  actor_ids=["ENT_WILLARD", "ENT_CHEF", "ENT_CLEAN", "ENT_CHIEF", "ENT_LANCE"], target_ids=[],
                  description="Willard joins the PBR crew for the river journey to Cambodia."),
        EventNode(id="EVT_B52_STRIKE", fabula_time=300, syuzhet_index=3, event_type="outcome",
                  actor_ids=["ENT_WILLARD", "ENT_CHEF", "ENT_CLEAN", "ENT_CHIEF", "ENT_LANCE"], target_ids=[],
                  description="En route to the Air Cavalry rendezvous, the PBR crew is caught in the middle of a B-52 bomber strike."),
        EventNode(id="EVT_KILGORE_ASSAULT", fabula_time=400, syuzhet_index=4, event_type="choice",
                  actor_ids=["ENT_KILGORE"], target_ids=["ENT_WILLARD"],
                  description="Kilgore's helicopter squadron attacks a village blasting Wagner so Lance can surf."),
        EventNode(id="EVT_TIGER_ATTACK", fabula_time=500, syuzhet_index=5, event_type="outcome",
                  actor_ids=["ENT_CHEF", "ENT_WILLARD"], target_ids=[],
                  description="Chef and Willard are attacked by a tiger in the jungle; Chef has a breakdown."),
        EventNode(id="EVT_USO_SHOW", fabula_time=600, syuzhet_index=6, event_type="outcome",
                  actor_ids=["ENT_WILLARD", "ENT_CHEF", "ENT_CLEAN", "ENT_CHIEF", "ENT_LANCE"], target_ids=[],
                  description="At the supply depot a USO show with Playboy Playmates whips the troops into a frenzy and is cut short."),
        EventNode(id="EVT_MOCK_WARFARE", fabula_time=700, syuzhet_index=7, event_type="outcome",
                  actor_ids=["ENT_CHIEF", "ENT_LANCE", "ENT_CHEF", "ENT_CLEAN"], target_ids=[],
                  description="The PBR crew engages other patrol boats in mock warfare on the river."),
        EventNode(id="EVT_DOSSIER_OBSESSION", fabula_time=800, syuzhet_index=8, event_type="choice",
                  actor_ids=["ENT_WILLARD"], target_ids=["ENT_WILLARD"],
                  description="Willard withdraws into Kurtz's dossier, obsessively re-reading it as tempers fray."),
        EventNode(id="EVT_CREW_DRUG_DISSOCIATION", fabula_time=900, syuzhet_index=9, event_type="outcome",
                  actor_ids=["ENT_LANCE", "ENT_CHEF"], target_ids=[],
                  description="Lance and Chef are continually under the influence of drugs; Lance smears camouflage paint and withdraws into silence."),
        EventNode(id="EVT_SAMPAN_MASSACRE", fabula_time=1000, syuzhet_index=10, event_type="outcome",
                  actor_ids=["ENT_CLEAN", "ENT_CHIEF", "ENT_WILLARD", "ENT_CHEF"], target_ids=[],
                  description="At Chief's stop-and-search order a peasant woman moves; Clean panic-fires; Willard executes the wounded survivor."),
        EventNode(id="EVT_DO_LUNG_BRIDGE", fabula_time=1100, syuzhet_index=11, event_type="outcome",
                  actor_ids=["ENT_WILLARD"], target_ids=[],
                  description="The PBR reaches the leaderless Do Lung Bridge outpost under nightly siege."),
        EventNode(id="EVT_PRIOR_OPERATIVE_REVEAL", fabula_time=1200, syuzhet_index=12, event_type="revelation",
                  actor_ids=["ENT_WILLARD"], target_ids=["ENT_WILLARD"],
                  description="In a packet of mail Willard reads that a prior operative sent to retrieve Kurtz is now operating with him."),
        EventNode(id="EVT_CLEAN_KILLED", fabula_time=1300, syuzhet_index=13, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_CLEAN"],
                  description="Mr Clean is fatally shot while listening to a tape from his mother."),
        EventNode(id="EVT_CHIEF_KILLED", fabula_time=1400, syuzhet_index=14, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_CHIEF"],
                  description="Chief is killed by a spear during a native ambush near Kurtz's territory."),
        EventNode(id="EVT_WILLARD_MEETS_KURTZ", fabula_time=1500, syuzhet_index=15, event_type="revelation",
                  actor_ids=["ENT_WILLARD"], target_ids=["ENT_KURTZ"],
                  description="Willard arrives at Kurtz's compound and encounters the colonel."),
        EventNode(id="EVT_WILLARD_IMPRISONED", fabula_time=1600, syuzhet_index=16, event_type="outcome",
                  actor_ids=["ENT_KURTZ"], target_ids=["ENT_WILLARD"],
                  description="Kurtz imprisons Willard in a tiger cage; throws Chef's severed head in his lap."),
        EventNode(id="EVT_CHEF_BEHEADED", fabula_time=1700, syuzhet_index=17, event_type="outcome",
                  actor_ids=["ENT_KURTZ"], target_ids=["ENT_CHEF"],
                  description="Chef is beheaded by Kurtz's followers when he tries to call in an airstrike."),
        EventNode(id="EVT_KURTZ_PHILOSOPHISES", fabula_time=1800, syuzhet_index=18, event_type="revelation",
                  actor_ids=["ENT_KURTZ"], target_ids=["ENT_WILLARD"],
                  description="Freed from the cage, Willard listens to Kurtz's monologues about the horror."),
        EventNode(id="EVT_WILLARD_KILLS_KURTZ", fabula_time=1900, syuzhet_index=19, event_type="choice",
                  actor_ids=["ENT_WILLARD"], target_ids=["ENT_KURTZ"],
                  description="Willard assassinates Kurtz with a machete during a ritual caribou sacrifice."),
        EventNode(id="EVT_NATIVES_ACCLAIM_WILLARD", fabula_time=2000, syuzhet_index=20, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_WILLARD"],
                  description="Emerging from Kurtz's quarters, the Montagnard natives lay down their weapons and acclaim Willard as their new leader and god."),
        EventNode(id="EVT_WILLARD_REJECTS_GODHOOD", fabula_time=2100, syuzhet_index=21, event_type="choice",
                  actor_ids=["ENT_WILLARD"], target_ids=["ENT_WILLARD"],
                  description="Willard throws down his machete, refusing the role of god-king, and finds Lance to lead him back to the boat."),
        EventNode(id="EVT_WILLARD_DEPARTS", fabula_time=2200, syuzhet_index=22, event_type="outcome",
                  actor_ids=["ENT_WILLARD", "ENT_LANCE"], target_ids=[],
                  description="Willard shuts off the radio and pulls away from shore with Lance as rain begins to fall; Kurtz's words echo."),
    ],
    causal_topology=[
        # ── chain_reaction ──
        CausalEdge(source_id="EVT_MISSION_BRIEFING", target_id="EVT_PBR_DEPARTS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100, propagation_delay=100),
        CausalEdge(source_id="EVT_PBR_DEPARTS", target_id="EVT_B52_STRIKE",
                   causality_type="chain_reaction", mechanism="physical_force", evidence_strength="strong",
                   causal_force=7.5, fabula_time=200, propagation_delay=50),
        CausalEdge(source_id="EVT_B52_STRIKE", target_id="EVT_KILGORE_ASSAULT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.5, fabula_time=300, propagation_delay=50),
        CausalEdge(source_id="EVT_KILGORE_ASSAULT", target_id="EVT_TIGER_ATTACK",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="weak",
                   causal_force=1.5, fabula_time=400, propagation_delay=100),
        CausalEdge(source_id="EVT_TIGER_ATTACK", target_id="EVT_USO_SHOW",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="weak",
                   causal_force=1.5, fabula_time=500, propagation_delay=50),
        CausalEdge(source_id="EVT_USO_SHOW", target_id="EVT_MOCK_WARFARE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="weak",
                   causal_force=2.0, fabula_time=600, propagation_delay=25),
        CausalEdge(source_id="EVT_MOCK_WARFARE", target_id="EVT_DOSSIER_OBSESSION",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=700, propagation_delay=5),
        CausalEdge(source_id="EVT_DOSSIER_OBSESSION", target_id="EVT_CREW_DRUG_DISSOCIATION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="weak",
                   causal_force=2.0, fabula_time=800, propagation_delay=5),
        CausalEdge(source_id="EVT_CREW_DRUG_DISSOCIATION", target_id="EVT_SAMPAN_MASSACRE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=900, propagation_delay=15),
        CausalEdge(source_id="EVT_TIGER_ATTACK", target_id="EVT_SAMPAN_MASSACRE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=3.5, fabula_time=500, propagation_delay=100),
        CausalEdge(source_id="EVT_SAMPAN_MASSACRE", target_id="EVT_DO_LUNG_BRIDGE",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="weak",
                   causal_force=2.0, fabula_time=1000, propagation_delay=100),
        CausalEdge(source_id="EVT_DO_LUNG_BRIDGE", target_id="EVT_PRIOR_OPERATIVE_REVEAL",
                   causality_type="chain_reaction", mechanism="epistemic_revelation", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1100, propagation_delay=50),
        CausalEdge(source_id="EVT_DO_LUNG_BRIDGE", target_id="EVT_CLEAN_KILLED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1100, propagation_delay=100),
        CausalEdge(source_id="EVT_CLEAN_KILLED", target_id="EVT_CHIEF_KILLED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="weak",
                   causal_force=2.5, fabula_time=1300, propagation_delay=100),
        CausalEdge(source_id="EVT_CHIEF_KILLED", target_id="EVT_WILLARD_MEETS_KURTZ",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1400, propagation_delay=100),
        CausalEdge(source_id="EVT_WILLARD_MEETS_KURTZ", target_id="EVT_WILLARD_IMPRISONED",
                   causality_type="chain_reaction", mechanism="social_coercion", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500, propagation_delay=50),
        CausalEdge(source_id="EVT_WILLARD_IMPRISONED", target_id="EVT_CHEF_BEHEADED",
                   causality_type="chain_reaction", mechanism="social_coercion", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1600, propagation_delay=50),
        CausalEdge(source_id="EVT_CHEF_BEHEADED", target_id="EVT_KURTZ_PHILOSOPHISES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1700, propagation_delay=100),
        CausalEdge(source_id="EVT_KURTZ_PHILOSOPHISES", target_id="EVT_WILLARD_KILLS_KURTZ",
                   causality_type="chain_reaction", mechanism="epistemic_revelation", evidence_strength="strong",
                   causal_force=8.5, fabula_time=1800, propagation_delay=100),
        CausalEdge(source_id="EVT_WILLARD_KILLS_KURTZ", target_id="EVT_NATIVES_ACCLAIM_WILLARD",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.5, fabula_time=1900, propagation_delay=50),
        CausalEdge(source_id="EVT_NATIVES_ACCLAIM_WILLARD", target_id="EVT_WILLARD_REJECTS_GODHOOD",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2000, propagation_delay=25),
        CausalEdge(source_id="EVT_WILLARD_REJECTS_GODHOOD", target_id="EVT_WILLARD_DEPARTS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.5, fabula_time=2100, propagation_delay=25),
        CausalEdge(source_id="EVT_PRIOR_OPERATIVE_REVEAL", target_id="EVT_WILLARD_MEETS_KURTZ",
                   causality_type="chain_reaction", mechanism="epistemic_revelation", evidence_strength="moderate",
                   causal_force=4.5, fabula_time=1200, propagation_delay=250),
        # ── mutation ──
        CausalEdge(source_id="EVT_SAMPAN_MASSACRE", target_id="ENT_WILLARD",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.5, fabula_time=1000, propagation_delay=0,
                   trait_target="remorse", trait_delta=0.25),
        CausalEdge(source_id="EVT_SAMPAN_MASSACRE", target_id="ENT_WILLARD",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1000, propagation_delay=0,
                   trait_target="despair", trait_delta=0.2),
        CausalEdge(source_id="EVT_TIGER_ATTACK", target_id="ENT_CHEF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500, propagation_delay=0,
                   trait_target="anxiety", trait_delta=0.2),
        CausalEdge(source_id="EVT_WILLARD_MEETS_KURTZ", target_id="ENT_WILLARD",
                   causality_type="mutation", mechanism="epistemic_revelation", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500, propagation_delay=0,
                   trait_target="paranoia", trait_delta=0.3),
        CausalEdge(source_id="EVT_WILLARD_KILLS_KURTZ", target_id="ENT_WILLARD",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1900, propagation_delay=0,
                   trait_target="remorse", trait_delta=0.3),
        CausalEdge(source_id="EVT_KILGORE_ASSAULT", target_id="ENT_LANCE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=400, propagation_delay=0,
                   trait_target="anxiety", trait_delta=0.2),
        CausalEdge(source_id="EVT_CREW_DRUG_DISSOCIATION", target_id="ENT_LANCE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=900, propagation_delay=115,
                   trait_target="despair", trait_delta=0.2),
        CausalEdge(source_id="EVT_DO_LUNG_BRIDGE", target_id="ENT_LANCE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1100, propagation_delay=300,
                   trait_target="despair", trait_delta=0.15),
        CausalEdge(source_id="EVT_USO_SHOW", target_id="ENT_CHEF",
                   causality_type="mutation", mechanism="emotional", evidence_strength="weak",
                   causal_force=2.0, fabula_time=600, propagation_delay=0,
                   trait_target="affection", trait_delta=0.1),
        # ── mutation_social ──
        CausalEdge(source_id="EVT_WILLARD_MEETS_KURTZ", target_id="ENT_WILLARD",
                   causality_type="mutation_social", mechanism="epistemic_revelation", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500, propagation_delay=0,
                   trait_target="affinity", trait_delta=0.3, rel_counterpart_id="ENT_KURTZ"),
        CausalEdge(source_id="EVT_SAMPAN_MASSACRE", target_id="ENT_CHIEF",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=7.5, fabula_time=1000, propagation_delay=0,
                   trait_target="affinity", trait_delta=-0.45, rel_counterpart_id="ENT_WILLARD"),
        CausalEdge(source_id="EVT_SAMPAN_MASSACRE", target_id="ENT_CHIEF",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=6.5, fabula_time=1000, propagation_delay=0,
                   trait_target="fear", trait_delta=0.25, rel_counterpart_id="ENT_WILLARD"),
        CausalEdge(source_id="EVT_WILLARD_KILLS_KURTZ", target_id="ENT_WILLARD",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1900, propagation_delay=0,
                   trait_target="affinity", trait_delta=-0.3, rel_counterpart_id="ENT_KURTZ"),
        CausalEdge(source_id="EVT_NATIVES_ACCLAIM_WILLARD", target_id="ENT_LANCE",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=2000, propagation_delay=0,
                   trait_target="loyalty", trait_delta=0.2, rel_counterpart_id="ENT_WILLARD"),
        # ── affordance_gate ──
        CausalEdge(source_id="OBJ_DOSSIER", target_id="EVT_MISSION_BRIEFING",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=100, propagation_delay=0),
        CausalEdge(source_id="OBJ_DOSSIER", target_id="EVT_DOSSIER_OBSESSION",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=6.0, fabula_time=800, propagation_delay=0),
        CausalEdge(source_id="OBJ_MAIL_PACKET", target_id="EVT_PRIOR_OPERATIVE_REVEAL",
                   causality_type="affordance_gate", mechanism="epistemic_revelation", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1200, propagation_delay=0),
        CausalEdge(source_id="OBJ_MACHETE", target_id="EVT_WILLARD_KILLS_KURTZ",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1900, propagation_delay=0),
        CausalEdge(source_id="OBJ_PBR_RADIO", target_id="EVT_WILLARD_DEPARTS",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=2200, propagation_delay=0),
        CausalEdge(source_id="ENT_KILGORE", target_id="EVT_KILGORE_ASSAULT",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=400, propagation_delay=0),
        # ── ambient_propagation ──
        CausalEdge(source_id="LOC_KURTZ_COMPOUND", target_id="ENT_WILLARD",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=1500, propagation_delay=0),
        CausalEdge(source_id="LOC_DO_LUNG_BRIDGE", target_id="ENT_LANCE",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=1100, propagation_delay=0),
        CausalEdge(source_id="LOC_PBR_BOAT", target_id="ENT_WILLARD",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.5, fabula_time=800, propagation_delay=0),

        # ── WORLD_ → Event (named-latent common-cause wiring) ──
        CausalEdge(source_id="WORLD_AMERICAN_IMPERIALISM", target_id="EVT_MISSION_BRIEFING",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=100, propagation_delay=0),
        CausalEdge(source_id="WORLD_AMERICAN_IMPERIALISM", target_id="EVT_KILGORE_ASSAULT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=400, propagation_delay=0),
        CausalEdge(source_id="WORLD_AMERICAN_IMPERIALISM", target_id="EVT_SAMPAN_MASSACRE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1000, propagation_delay=0),
        CausalEdge(source_id="WORLD_JUNGLE_MADNESS", target_id="EVT_TIGER_ATTACK",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="weak",
                   causal_force=3.0, fabula_time=500, propagation_delay=0),
        CausalEdge(source_id="WORLD_JUNGLE_MADNESS", target_id="EVT_CHEF_BEHEADED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1700, propagation_delay=0),
        CausalEdge(source_id="WORLD_JUNGLE_MADNESS", target_id="EVT_KURTZ_PHILOSOPHISES",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1800, propagation_delay=0),
        CausalEdge(source_id="WORLD_VIETNAM_WAR_ATTRITION", target_id="EVT_B52_STRIKE",
                   causality_type="chain_reaction", mechanism="physical_force", evidence_strength="strong",
                   causal_force=6.0, fabula_time=300, propagation_delay=0),
        CausalEdge(source_id="WORLD_VIETNAM_WAR_ATTRITION", target_id="EVT_CLEAN_KILLED",
                   causality_type="chain_reaction", mechanism="physical_force", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1300, propagation_delay=0),
        CausalEdge(source_id="WORLD_VIETNAM_WAR_ATTRITION", target_id="EVT_CHIEF_KILLED",
                   causality_type="chain_reaction", mechanism="physical_force", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1400, propagation_delay=0),
        CausalEdge(source_id="WORLD_MILITARY_HIERARCHY_BREAKDOWN", target_id="EVT_DO_LUNG_BRIDGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.5, fabula_time=1100, propagation_delay=0),
        CausalEdge(source_id="WORLD_MILITARY_HIERARCHY_BREAKDOWN", target_id="EVT_WILLARD_MEETS_KURTZ",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1500, propagation_delay=0),
        CausalEdge(source_id="WORLD_US_MILITARY_SPECTACLE", target_id="EVT_KILGORE_ASSAULT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=400, propagation_delay=0),
        CausalEdge(source_id="WORLD_US_MILITARY_SPECTACLE", target_id="EVT_USO_SHOW",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=600, propagation_delay=0),
        CausalEdge(source_id="WORLD_CAMBODIAN_INCURSION", target_id="EVT_MISSION_BRIEFING",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=100, propagation_delay=0),
        CausalEdge(source_id="WORLD_CAMBODIAN_INCURSION", target_id="EVT_WILLARD_MEETS_KURTZ",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1500, propagation_delay=0),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_SAIGON_HOTEL", target_id="LOC_NHA_TRANG_HQ"),
        SpatialEdge(source_id="LOC_NHA_TRANG_HQ", target_id="LOC_PBR_BOAT"),
        SpatialEdge(source_id="LOC_PBR_BOAT", target_id="LOC_KILGORE_BEACH"),
        SpatialEdge(source_id="LOC_PBR_BOAT", target_id="LOC_JUNGLE"),
        SpatialEdge(source_id="LOC_PBR_BOAT", target_id="LOC_USO_DEPOT"),
        SpatialEdge(source_id="LOC_PBR_BOAT", target_id="LOC_DO_LUNG_BRIDGE"),
        SpatialEdge(source_id="LOC_DO_LUNG_BRIDGE", target_id="LOC_KURTZ_COMPOUND"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_KURTZ", target_ids=["ENT_WILLARD"],
                        medium="monologue", established_at_fabula=1800, discovered_at_syuzhet=18),
        InformationEdge(source_id="ENT_WILLARD", target_ids=["ENT_CHEF"],
                        medium="conversation", established_at_fabula=200, terminated_at_fabula=1700, discovered_at_syuzhet=2),
        InformationEdge(source_id="OBJ_DOSSIER", target_ids=["ENT_WILLARD"],
                        medium="classified_briefing", established_at_fabula=100, discovered_at_syuzhet=1),
        InformationEdge(source_id="ENT_CHIEF", target_ids=["ENT_WILLARD"],
                        medium="argument", established_at_fabula=1000, discovered_at_syuzhet=10),
        InformationEdge(source_id="ENT_PHOTOJOURNALIST", target_ids=["ENT_WILLARD", "ENT_LANCE"],
                        medium="manic_proselytising", established_at_fabula=1500, discovered_at_syuzhet=15),
        InformationEdge(source_id="ENT_KURTZ", target_ids=["ENT_PHOTOJOURNALIST"],
                        medium="poetry_recitation", established_at_fabula=1800, discovered_at_syuzhet=18),
        InformationEdge(source_id="ENT_KILGORE", target_ids=["ENT_WILLARD", "ENT_LANCE"],
                        medium="radio_broadcast", established_at_fabula=400, discovered_at_syuzhet=4),
        InformationEdge(source_id="ENT_WILLARD", target_ids=["ENT_CHIEF", "ENT_LANCE"],
                        medium="mission_disclosure", is_encrypted=True,
                        established_at_fabula=1100, discovered_at_syuzhet=11),
        InformationEdge(source_id="OBJ_MAIL_PACKET", target_ids=["ENT_WILLARD"],
                        medium="letter", established_at_fabula=1200, discovered_at_syuzhet=12),
        InformationEdge(source_id="OBJ_PBR_RADIO", target_ids=["ENT_WILLARD", "ENT_LANCE"],
                        medium="radio_silence", established_at_fabula=2200, discovered_at_syuzhet=22),
    ],
    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_JUNGLE_MADNESS": GlobalTrait(
            id="WORLD_JUNGLE_MADNESS",
            name="Jungle Madness",
            description="The deeper the patrol boat travels upriver, the more the veneer of civilisation dissolves — replaced by primal violence and moral disintegration.",
            category="environment",
            magnitude=TraitVector(value=0.5, inertia=0.4),
            affected_domains=["psychological", "social"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=1100, triggered_by="EVT_DO_LUNG_BRIDGE",
                    magnitude=TraitVector(value=0.8, inertia=0.6),
                    description="Do Lung Bridge — last Army outpost — is leaderless chaos, signalling total institutional collapse."),
                WorldTraitSnapshot(fabula_time=1500, triggered_by="EVT_WILLARD_MEETS_KURTZ",
                    magnitude=TraitVector(value=1.0, inertia=0.9),
                    description="Kurtz's compound is civilisation's endpoint — severed heads, ritual worship, absolute madness."),
                WorldTraitSnapshot(fabula_time=1900, triggered_by="EVT_WILLARD_KILLS_KURTZ",
                    magnitude=TraitVector(value=1.0, inertia=0.95),
                    description="Peak ritual violence as Kurtz is slaughtered alongside the caribou sacrifice."),
                WorldTraitSnapshot(fabula_time=2200, triggered_by="EVT_WILLARD_DEPARTS",
                    magnitude=TraitVector(value=0.85, inertia=0.7),
                    description="Slight recession as Willard departs and the natives lay down their weapons; the madness lingers in the rain."),
            ],
        ),
        "WORLD_AMERICAN_IMPERIALISM": GlobalTrait(
            id="WORLD_AMERICAN_IMPERIALISM",
            name="American Military Imperialism",
            description="The US military machine projects overwhelming firepower with no coherent moral framework, creating destruction that consumes its own soldiers.",
            category="governance",
            magnitude=TraitVector(value=0.8, inertia=0.7),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=400, triggered_by="EVT_KILGORE_ASSAULT",
                    magnitude=TraitVector(value=0.95, inertia=0.8),
                    description="Kilgore's surfing-while-napalming epitomises the obscene detachment of imperial violence."),
                WorldTraitSnapshot(fabula_time=1000, triggered_by="EVT_SAMPAN_MASSACRE",
                    magnitude=TraitVector(value=0.95, inertia=0.85),
                    description="Civilians on the sampan are slaughtered in service of mission-priority imperial logic."),
                WorldTraitSnapshot(fabula_time=1100, triggered_by="EVT_DO_LUNG_BRIDGE",
                    magnitude=TraitVector(value=0.9, inertia=0.85),
                    description="Imperial command collapses on its own frontier: no commanding officer can be found at Do Lung."),
            ],
        ),
        "WORLD_VIETNAM_WAR_ATTRITION": GlobalTrait(
            id="WORLD_VIETNAM_WAR_ATTRITION",
            name="Vietnam War Attrition",
            description="Persistent combat entropy: random ambushes, surprise attacks, and unending small-arms loss that grinds down crews regardless of plan.",
            category="environment",
            magnitude=TraitVector(value=0.85, inertia=0.8),
            affected_domains=["physical", "psychological"],
        ),
        "WORLD_MILITARY_HIERARCHY_BREAKDOWN": GlobalTrait(
            id="WORLD_MILITARY_HIERARCHY_BREAKDOWN",
            name="Military Hierarchy Breakdown",
            description="The chain of command dissolves at the war's edge: officers absent, orders contradictory, outposts leaderless, sanctioning a private mission against a private army.",
            category="governance",
            magnitude=TraitVector(value=0.7, inertia=0.6),
            affected_domains=["social", "psychological"],
        ),
        "WORLD_US_MILITARY_SPECTACLE": GlobalTrait(
            id="WORLD_US_MILITARY_SPECTACLE",
            name="US Military Spectacle",
            description="War as theatre: Wagner over loudspeakers, USO Playmate shows, mock warfare on the river — morale-as-spectacle that masks and amplifies the violence.",
            category="social_structure",
            magnitude=TraitVector(value=0.75, inertia=0.6),
            affected_domains=["social", "emotional"],
        ),
        "WORLD_CAMBODIAN_INCURSION": GlobalTrait(
            id="WORLD_CAMBODIAN_INCURSION",
            name="Cambodian Border Incursion",
            description="The mission crosses a forbidden border into Cambodia under deniable orders — illegality that frames every act upriver.",
            category="governance",
            magnitude=TraitVector(value=0.7, inertia=0.7),
            affected_domains=["social"],
        ),
    },
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_WILLARD", target_entity_id="ENT_KURTZ",
                         affinity=-0.05, fear=0.3, power_dynamic=-0.3, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_KURTZ", target_entity_id="ENT_WILLARD",
                         affinity=0.3, fear=0.0, power_dynamic=0.4, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_WILLARD", target_entity_id="ENT_CHIEF",
                         affinity=0.2, fear=0.0, power_dynamic=0.2, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_CHIEF", target_entity_id="ENT_WILLARD",
                         affinity=-0.1, fear=0.1, power_dynamic=-0.2, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_WILLARD", target_entity_id="ENT_CHEF",
                         affinity=0.2, fear=0.0, power_dynamic=0.2, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_WILLARD", target_entity_id="ENT_LANCE",
                         affinity=0.2, fear=0.0, power_dynamic=0.2, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_KILGORE", target_entity_id="ENT_LANCE",
                         affinity=0.4, fear=0.0, power_dynamic=0.5, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_WILLARD", target_entity_id="ENT_CLEAN",
                         affinity=0.2, fear=0.0, power_dynamic=0.3, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_CHEF", target_entity_id="ENT_CHIEF",
                         affinity=0.3, fear=0.0, power_dynamic=-0.2, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_CHIEF", target_entity_id="ENT_CLEAN",
                         affinity=0.3, fear=0.0, power_dynamic=0.5, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_CLEAN", target_entity_id="ENT_CHIEF",
                         affinity=0.4, fear=0.1, power_dynamic=-0.4, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_CLEAN", target_entity_id="ENT_WILLARD",
                         affinity=0.1, fear=0.2, power_dynamic=-0.3, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_LANCE", target_entity_id="ENT_WILLARD",
                         affinity=0.3, fear=0.1, power_dynamic=-0.3, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_PHOTOJOURNALIST", target_entity_id="ENT_KURTZ",
                         affinity=0.95, fear=0.4, power_dynamic=-0.7, inertia=0.6),
        RelationshipEdge(source_entity_id="ENT_KURTZ", target_entity_id="ENT_PHOTOJOURNALIST",
                         affinity=0.2, fear=0.0, power_dynamic=0.7, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_PHOTOJOURNALIST", target_entity_id="ENT_WILLARD",
                         affinity=0.5, fear=0.2, power_dynamic=-0.2, inertia=0.2),
        RelationshipEdge(source_entity_id="ENT_WILLARD", target_entity_id="ENT_PHOTOJOURNALIST",
                         affinity=-0.1, fear=0.0, power_dynamic=0.3, inertia=0.2),
    ],
)
