"""Brief Encounter — high-fidelity WorldStateV1 test fixture."""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_MILFORD_JUNCTION": Location(name="Milford Junction Station", description="Railway station where Laura and Alec meet weekly.",
            ambient_state={"transience": AmbientVector(value=0.8, volatility=0.3), "routine": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_TEA_ROOM": Location(name="Station Tea Room", description="Refreshment room run by Myrtle Bagot.",
            ambient_state={"warmth": AmbientVector(value=0.6, volatility=0.3)}),
        "LOC_CHEMIST": Location(name="Milford Chemist", description="The chemist's shop where Laura and Alec re-encounter each other the week after the grit incident.",
            ambient_state={"chance": AmbientVector(value=0.7, volatility=0.4)}),
        "LOC_CINEMA": Location(name="Cinema", description="Local picture house where Laura and Alec go on dates.",
            ambient_state={"intimacy": AmbientVector(value=0.6, volatility=0.4)}),
        "LOC_BOTANICAL_GARDENS": Location(name="Botanical Gardens", description="Public gardens where they walk together.",
            ambient_state={"serenity": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_STEPHENS_FLAT": Location(name="Stephen's Flat", description="Borrowed flat where Laura and Alec are almost caught.",
            ambient_state={"danger": AmbientVector(value=0.7, volatility=0.5), "guilt": AmbientVector(value=0.6, volatility=0.4)}),
        "LOC_MILFORD_STREETS": Location(name="Milford Streets at Night", description="The streets Laura wanders for three hours after fleeing Stephen's flat.",
            ambient_state={"desolation": AmbientVector(value=0.8, volatility=0.4), "guilt": AmbientVector(value=0.7, volatility=0.3)}),
        "LOC_LAURA_HOME": Location(name="Laura's Home", description="Laura's comfortable suburban home with Fred.",
            ambient_state={"security": AmbientVector(value=0.7, volatility=0.2), "guilt": AmbientVector(value=0.4, volatility=0.4)}),
    },
    objects={
        "OBJ_GRIT": NarrativeObject(id="OBJ_GRIT", name="Piece of Grit",
            location_id="LOC_MILFORD_JUNCTION", owner_id=None,
            properties={"state": "lodged_in_eye"},
            affordances=[Affordance(action="create_encounter", target_type="Entity")]),
        "OBJ_EXPRESS_TRAIN": NarrativeObject(id="OBJ_EXPRESS_TRAIN", name="Express Train",
            location_id="LOC_MILFORD_JUNCTION", owner_id=None,
            properties={"state": "thundering_through"},
            affordances=[Affordance(action="tempt_death", target_type="Entity")]),
    },
    entities={
        "ENT_LAURA": Entity(id="ENT_LAURA", name="Laura Jesson",
            location_id="LOC_LAURA_HOME", status="healthy",
            traits={
                "duty": TraitVector(value=0.8, inertia=0.6),
                "passion": TraitVector(value=0.3, inertia=0.2),
                "guilt": TraitVector(value=0.30, inertia=0.45),
                "longing": TraitVector(value=0.3, inertia=0.2),
                "propriety": TraitVector(value=0.8, inertia=0.6),
                "grief": TraitVector(value=0.1, inertia=0.25),
                "love": TraitVector(value=0.2, inertia=0.3),
                "anxiety": TraitVector(value=0.25, inertia=0.4),
                "despair": TraitVector(value=0.05, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_FRED", perceived_state="Fred is a good husband but we lack passion", confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_ALEC", perceived_state="Alec is exciting but forbidden", confidence=0.7, inertia=0.3),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_GRIT_IN_EYE",
                    traits={"longing": TraitVector(value=0.5, inertia=0.25)}),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_FRIENDS_ENCOUNTER_DECEPTION",
                    traits={"guilt": TraitVector(value=0.55, inertia=0.45),
                            "anxiety": TraitVector(value=0.55, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_FLAT_INTERRUPTED",
                    traits={"guilt": TraitVector(value=0.75, inertia=0.4), "passion": TraitVector(value=0.7, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_POLICE_ADVISES_HOME",
                    traits={"guilt": TraitVector(value=0.90, inertia=0.45),
                            "despair": TraitVector(value=0.55, inertia=0.4),
                            "anxiety": TraitVector(value=0.7, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_FINAL_MEETING",
                    traits={"longing": TraitVector(value=0.9, inertia=0.3),
                            "duty": TraitVector(value=0.9, inertia=0.6),
                            "grief": TraitVector(value=0.85, inertia=0.4),
                            "despair": TraitVector(value=0.8, inertia=0.45)}),
                EntityStateSnapshot(fabula_time=1500, triggered_by="EVT_FRED_UNDERSTANDS",
                    traits={"guilt": TraitVector(value=0.65, inertia=0.5),
                            "despair": TraitVector(value=0.45, inertia=0.4)}),
            ]),
        "ENT_ALEC": Entity(id="ENT_ALEC", name="Dr Alec Harvey",
            location_id="LOC_MILFORD_JUNCTION", status="healthy",
            traits={
                "compassion": TraitVector(value=0.7, inertia=0.5),
                "passion": TraitVector(value=0.6, inertia=0.3),
                "honour": TraitVector(value=0.82, inertia=0.70),
                "restraint": TraitVector(value=0.78, inertia=0.75),
                "resignation": TraitVector(value=0.35, inertia=0.50),
                "love": TraitVector(value=0.4, inertia=0.4),
                "despair": TraitVector(value=0.1, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_LAURA", perceived_state="Laura is the love of my life", confidence=0.8, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_ALEC_ACCEPTS_POST",
                    traits={"resignation": TraitVector(value=0.78, inertia=0.6),
                            "despair": TraitVector(value=0.5, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_ALEC_DEPARTS",
                    location_id="LOC_MILFORD_JUNCTION",
                    traits={"resignation": TraitVector(value=0.85, inertia=0.7),
                            "grief": TraitVector(value=0.7, inertia=0.5)}),
            ]),
        "ENT_FRED": Entity(id="ENT_FRED", name="Fred Jesson",
            location_id="LOC_LAURA_HOME", status="healthy",
            traits={
                "steadiness": TraitVector(value=0.9, inertia=0.7),
                "kindness": TraitVector(value=0.7, inertia=0.5),
                "obliviousness": TraitVector(value=0.78, inertia=0.65),
                "attunement": TraitVector(value=0.25, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_LAURA", perceived_state="Laura is a devoted wife", confidence=0.9, inertia=0.6),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1500, triggered_by="EVT_FRED_UNDERSTANDS",
                    traits={"obliviousness": TraitVector(value=0.40, inertia=0.70),
                            "attunement": TraitVector(value=0.75, inertia=0.6),
                            "kindness": TraitVector(value=0.85, inertia=0.55)}),
            ]),
        "ENT_DOLLY": Entity(id="ENT_DOLLY", name="Dolly Messiter",
            location_id="LOC_TEA_ROOM", status="healthy",
            traits={
                "garrulousness": TraitVector(value=0.8, inertia=0.5),
                "nosiness": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_LAURA", perceived_state="Laura is a perfectly ordinary friend", confidence=0.8, inertia=0.5),
            ]),
        "ENT_MYRTLE": Entity(id="ENT_MYRTLE", name="Myrtle Bagot",
            location_id="LOC_TEA_ROOM", status="healthy",
            traits={
                "primness": TraitVector(value=0.7, inertia=0.5),
                "authority": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[]),
        "ENT_ALBERT": Entity(id="ENT_ALBERT", name="Albert Godby",
            location_id="LOC_MILFORD_JUNCTION", status="healthy",
            traits={
                "flirtatiousness": TraitVector(value=0.7, inertia=0.4),
                "work_propriety": TraitVector(value=0.6, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_MYRTLE", perceived_state="Myrtle returns the affection but maintains workplace decorum", confidence=0.7, inertia=0.4),
            ]),
        "ENT_STEPHEN": Entity(id="ENT_STEPHEN", name="Stephen Lynn",
            location_id="LOC_STEPHENS_FLAT", status="healthy",
            traits={
                "perceptiveness": TraitVector(value=0.8, inertia=0.6),
                "disapproval": TraitVector(value=0.7, inertia=0.5),
                "discretion": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_ALEC", perceived_state="Alec is risking his marriage and his reputation",
                       confidence=0.85, inertia=0.5, established_at_fabula=800),
            ]),
    },
    events=[
        EventNode(id="EVT_FINAL_MEETING", fabula_time=1200, syuzhet_index=1, event_type="outcome",
                  actor_ids=["ENT_LAURA", "ENT_ALEC"], target_ids=[],
                  description="Their final meeting is interrupted by Dolly, who chatters obliviously while Laura and Alec sit anguished, unable to say goodbye properly."),
        EventNode(id="EVT_ALEC_DEPARTS", fabula_time=1300, syuzhet_index=2, event_type="outcome",
                  actor_ids=["ENT_ALEC"], target_ids=[],
                  description="Alec's train arrives at the final meeting; he discreetly squeezes Laura's shoulder and departs forever — shown in the opening before context is revealed."),
        EventNode(id="EVT_ROUTINE_THURSDAYS", fabula_time=100, syuzhet_index=3, event_type="outcome",
                  actor_ids=["ENT_LAURA"], target_ids=[],
                  description="Laura's routine Thursday shopping trips to Milford Junction."),
        EventNode(id="EVT_GRIT_IN_EYE", fabula_time=200, syuzhet_index=4, event_type="outcome",
                  actor_ids=["ENT_ALEC"], target_ids=["ENT_LAURA"],
                  description="Alec removes a piece of grit from Laura's eye in the tea room."),
        EventNode(id="EVT_CHEMIST_REUNION", fabula_time=300, syuzhet_index=5, event_type="outcome",
                  actor_ids=["ENT_LAURA", "ENT_ALEC"], target_ids=[],
                  description="The following week, Laura runs into Alec at the chemist — a chance re-encounter that revives the connection."),
        EventNode(id="EVT_CINEMA_DATE", fabula_time=400, syuzhet_index=6, event_type="choice",
                  actor_ids=["ENT_LAURA", "ENT_ALEC"], target_ids=[],
                  description="The week after the chemist, Laura and Alec eat lunch and watch a film together."),
        EventNode(id="EVT_BOATING_GARDENS", fabula_time=500, syuzhet_index=7, event_type="choice",
                  actor_ids=["ENT_LAURA", "ENT_ALEC"], target_ids=[],
                  description="They go boating in the botanical gardens, deepening their bond."),
        EventNode(id="EVT_STAFF_FLIRTATION", fabula_time=500, syuzhet_index=8, event_type="outcome",
                  actor_ids=["ENT_ALBERT", "ENT_MYRTLE"], target_ids=[],
                  description="Albert and Myrtle flirt at the refreshment counter but cannot openly express affection during work hours — a contrast to Laura and Alec."),
        EventNode(id="EVT_DECLARATION", fabula_time=600, syuzhet_index=9, event_type="revelation",
                  actor_ids=["ENT_ALEC"], target_ids=["ENT_LAURA"],
                  description="Alec declares his love; Laura reciprocates despite her turmoil."),
        EventNode(id="EVT_FRIENDS_ENCOUNTER_DECEPTION", fabula_time=700, syuzhet_index=10, event_type="outcome",
                  actor_ids=["ENT_LAURA", "ENT_ALEC"], target_ids=[],
                  description="They unexpectedly run into some of Laura's friends, forcing the first of many deceptions."),
        EventNode(id="EVT_FLAT_INTERRUPTED", fabula_time=800, syuzhet_index=11, event_type="outcome",
                  actor_ids=["ENT_LAURA", "ENT_ALEC"], target_ids=[],
                  description="Laura and Alec go to Stephen's flat but are interrupted by his return."),
        EventNode(id="EVT_LAURA_WANDERS_STREETS", fabula_time=900, syuzhet_index=12, event_type="outcome",
                  actor_ids=["ENT_LAURA"], target_ids=[],
                  description="A distraught Laura wanders the streets of Milford for three hours after fleeing Stephen's flat."),
        EventNode(id="EVT_POLICE_ADVISES_HOME", fabula_time=1000, syuzhet_index=13, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_LAURA"],
                  description="A concerned police officer urges Laura to go home."),
        EventNode(id="EVT_ALEC_ACCEPTS_POST", fabula_time=1100, syuzhet_index=14, event_type="choice",
                  actor_ids=["ENT_ALEC"], target_ids=["ENT_LAURA"],
                  description="Alec accepts a medical post in Johannesburg, ending the affair for the sake of his family."),
        EventNode(id="EVT_LAURA_SUICIDAL_IMPULSE", fabula_time=1400, syuzhet_index=15, event_type="outcome",
                  actor_ids=["ENT_LAURA"], target_ids=[],
                  description="Laura runs toward the express train platform, tempted to end her life, but gathers herself."),
        EventNode(id="EVT_FRED_UNDERSTANDS", fabula_time=1500, syuzhet_index=16, event_type="revelation",
                  actor_ids=["ENT_FRED"], target_ids=["ENT_LAURA"],
                  description="At home, Fred acknowledges Laura's emotional distance and thanks her for coming back to him."),
    ],
    causal_topology=[
        CausalEdge(source_id="EVT_ROUTINE_THURSDAYS", target_id="EVT_GRIT_IN_EYE",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=100, propagation_delay=50),
        CausalEdge(source_id="EVT_GRIT_IN_EYE", target_id="EVT_CHEMIST_REUNION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.5, fabula_time=200, propagation_delay=100),
        CausalEdge(source_id="EVT_CHEMIST_REUNION", target_id="EVT_CINEMA_DATE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300, propagation_delay=100),
        CausalEdge(source_id="EVT_CINEMA_DATE", target_id="EVT_BOATING_GARDENS",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=400, propagation_delay=100),
        CausalEdge(source_id="EVT_BOATING_GARDENS", target_id="EVT_DECLARATION",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500, propagation_delay=100),
        CausalEdge(source_id="EVT_DECLARATION", target_id="EVT_FRIENDS_ENCOUNTER_DECEPTION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.5, fabula_time=600, propagation_delay=20),
        CausalEdge(source_id="EVT_FRIENDS_ENCOUNTER_DECEPTION", target_id="EVT_FLAT_INTERRUPTED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=700, propagation_delay=80),
        CausalEdge(source_id="EVT_DECLARATION", target_id="EVT_FLAT_INTERRUPTED",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=600, propagation_delay=100),
        CausalEdge(source_id="EVT_FLAT_INTERRUPTED", target_id="EVT_LAURA_WANDERS_STREETS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.5, fabula_time=800, propagation_delay=20),
        CausalEdge(source_id="EVT_LAURA_WANDERS_STREETS", target_id="EVT_POLICE_ADVISES_HOME",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=900, propagation_delay=20),
        CausalEdge(source_id="EVT_FLAT_INTERRUPTED", target_id="EVT_ALEC_ACCEPTS_POST",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=800, propagation_delay=100),
        CausalEdge(source_id="EVT_ALEC_ACCEPTS_POST", target_id="EVT_ALEC_DEPARTS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.5, fabula_time=1100, propagation_delay=100),
        CausalEdge(source_id="EVT_ALEC_ACCEPTS_POST", target_id="EVT_FINAL_MEETING",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1100, propagation_delay=100),
        CausalEdge(source_id="EVT_FINAL_MEETING", target_id="EVT_LAURA_SUICIDAL_IMPULSE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1200, propagation_delay=20),
        CausalEdge(source_id="EVT_ALEC_DEPARTS", target_id="EVT_LAURA_SUICIDAL_IMPULSE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.5, fabula_time=1300, propagation_delay=10),
        CausalEdge(source_id="EVT_LAURA_SUICIDAL_IMPULSE", target_id="EVT_FRED_UNDERSTANDS",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=1400, propagation_delay=100),
        CausalEdge(source_id="EVT_FINAL_MEETING", target_id="EVT_FRED_UNDERSTANDS",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=1200, propagation_delay=100),
        CausalEdge(source_id="EVT_GRIT_IN_EYE", target_id="ENT_LAURA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=200, trait_target="love", trait_delta=0.15),
        CausalEdge(source_id="EVT_DECLARATION", target_id="ENT_LAURA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600, trait_target="love", trait_delta=0.4),
        CausalEdge(source_id="EVT_FRIENDS_ENCOUNTER_DECEPTION", target_id="ENT_LAURA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.5, fabula_time=700, trait_target="anxiety", trait_delta=0.3),
        CausalEdge(source_id="EVT_FLAT_INTERRUPTED", target_id="ENT_LAURA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=800, trait_target="guilt", trait_delta=0.45),
        CausalEdge(source_id="EVT_LAURA_WANDERS_STREETS", target_id="ENT_LAURA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900, trait_target="despair", trait_delta=0.4),
        CausalEdge(source_id="EVT_POLICE_ADVISES_HOME", target_id="ENT_LAURA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=1000, trait_target="guilt", trait_delta=0.25),
        CausalEdge(source_id="EVT_ALEC_ACCEPTS_POST", target_id="ENT_ALEC",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1100, trait_target="despair", trait_delta=0.4),
        CausalEdge(source_id="EVT_ALEC_DEPARTS", target_id="ENT_LAURA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1300, trait_target="grief", trait_delta=0.4),
        CausalEdge(source_id="EVT_FINAL_MEETING", target_id="ENT_LAURA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.5, fabula_time=1200, trait_target="grief", trait_delta=0.35),
        CausalEdge(source_id="EVT_FRED_UNDERSTANDS", target_id="ENT_LAURA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1500, trait_target="guilt", trait_delta=-0.25),
        CausalEdge(source_id="EVT_DECLARATION", target_id="ENT_LAURA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600, trait_target="affinity", trait_delta=0.5, rel_counterpart_id="ENT_ALEC"),
        CausalEdge(source_id="EVT_FRIENDS_ENCOUNTER_DECEPTION", target_id="ENT_LAURA",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=700, trait_target="fear", trait_delta=0.25, rel_counterpart_id="ENT_ALEC"),
        CausalEdge(source_id="EVT_FRIENDS_ENCOUNTER_DECEPTION", target_id="ENT_ALEC",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=700, trait_target="fear", trait_delta=0.25, rel_counterpart_id="ENT_LAURA"),
        CausalEdge(source_id="EVT_FINAL_MEETING", target_id="ENT_LAURA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1200, trait_target="affinity", trait_delta=-0.3, rel_counterpart_id="ENT_ALEC"),
        CausalEdge(source_id="EVT_FRED_UNDERSTANDS", target_id="ENT_LAURA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1500, trait_target="affinity", trait_delta=0.3, rel_counterpart_id="ENT_FRED"),
        CausalEdge(source_id="OBJ_GRIT", target_id="EVT_GRIT_IN_EYE",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200),
        CausalEdge(source_id="ENT_DOLLY", target_id="EVT_FINAL_MEETING",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1200),
        CausalEdge(source_id="OBJ_EXPRESS_TRAIN", target_id="EVT_LAURA_SUICIDAL_IMPULSE",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1400),
        CausalEdge(source_id="LOC_MILFORD_JUNCTION", target_id="ENT_LAURA",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=200),
        CausalEdge(source_id="LOC_LAURA_HOME", target_id="ENT_LAURA",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=800),
        CausalEdge(source_id="LOC_MILFORD_STREETS", target_id="ENT_LAURA",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=900),
        CausalEdge(source_id="WORLD_SOCIAL_PROPRIETY", target_id="EVT_ALEC_ACCEPTS_POST",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1100),
        CausalEdge(source_id="WORLD_SOCIAL_PROPRIETY", target_id="EVT_ALEC_DEPARTS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.5, fabula_time=1300),
        CausalEdge(source_id="WORLD_SOCIAL_PROPRIETY", target_id="EVT_LAURA_SUICIDAL_IMPULSE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1400),
        CausalEdge(source_id="WORLD_SOCIAL_PROPRIETY", target_id="EVT_FRED_UNDERSTANDS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1500),
        CausalEdge(source_id="WORLD_SOCIAL_PROPRIETY", target_id="EVT_FRIENDS_ENCOUNTER_DECEPTION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.5, fabula_time=700),
        CausalEdge(source_id="WORLD_SOCIAL_PROPRIETY", target_id="EVT_STAFF_FLIRTATION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=500),
        CausalEdge(source_id="WORLD_MARRIAGE_SACRED_INSTITUTION", target_id="EVT_DECLARATION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.5, fabula_time=600),
        CausalEdge(source_id="WORLD_MARRIAGE_SACRED_INSTITUTION", target_id="EVT_FLAT_INTERRUPTED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.5, fabula_time=800),
        CausalEdge(source_id="WORLD_MARRIAGE_SACRED_INSTITUTION", target_id="EVT_ALEC_ACCEPTS_POST",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.5, fabula_time=1100),
        CausalEdge(source_id="WORLD_MARRIAGE_SACRED_INSTITUTION", target_id="EVT_FINAL_MEETING",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1200),
        CausalEdge(source_id="WORLD_MARRIAGE_SACRED_INSTITUTION", target_id="EVT_FRED_UNDERSTANDS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.5, fabula_time=1500),
        CausalEdge(source_id="WORLD_RAILWAY_LIMINAL", target_id="EVT_GRIT_IN_EYE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=200),
        CausalEdge(source_id="WORLD_RAILWAY_LIMINAL", target_id="EVT_FINAL_MEETING",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.5, fabula_time=1200),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_MILFORD_JUNCTION", target_id="LOC_TEA_ROOM"),
        SpatialEdge(source_id="LOC_MILFORD_JUNCTION", target_id="LOC_CHEMIST"),
        SpatialEdge(source_id="LOC_MILFORD_JUNCTION", target_id="LOC_CINEMA"),
        SpatialEdge(source_id="LOC_MILFORD_JUNCTION", target_id="LOC_BOTANICAL_GARDENS"),
        SpatialEdge(source_id="LOC_MILFORD_JUNCTION", target_id="LOC_STEPHENS_FLAT"),
        SpatialEdge(source_id="LOC_MILFORD_JUNCTION", target_id="LOC_MILFORD_STREETS"),
        SpatialEdge(source_id="LOC_MILFORD_JUNCTION", target_id="LOC_LAURA_HOME"),
        SpatialEdge(source_id="LOC_STEPHENS_FLAT", target_id="LOC_MILFORD_STREETS"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_ALEC", target_ids=["ENT_LAURA"], medium="conversation", established_at_fabula=300, discovered_at_syuzhet=4),
        InformationEdge(source_id="ENT_LAURA", target_ids=["ENT_FRED"], medium="confession", established_at_fabula=1500, discovered_at_syuzhet=16),
        InformationEdge(source_id="ENT_STEPHEN", target_ids=["ENT_ALEC"],
                        medium="overheard_intrusion", is_encrypted=False,
                        established_at_fabula=800, terminated_at_fabula=800, discovered_at_syuzhet=10),
        InformationEdge(source_id="ENT_DOLLY", target_ids=["ENT_LAURA", "ENT_ALEC"],
                        medium="chatter", is_encrypted=False,
                        established_at_fabula=1200, terminated_at_fabula=1200, discovered_at_syuzhet=1),
        InformationEdge(source_id="ENT_MYRTLE", target_ids=["ENT_LAURA"],
                        medium="prim_observation", established_at_fabula=500, discovered_at_syuzhet=6),
        InformationEdge(source_id="ENT_FRED", target_ids=["ENT_LAURA"],
                        medium="quiet_acknowledgement", established_at_fabula=1500, discovered_at_syuzhet=16),
        InformationEdge(source_id="ENT_ALBERT", target_ids=["ENT_MYRTLE"],
                        medium="workplace_flirtation", established_at_fabula=500, discovered_at_syuzhet=7),
    ],
    world_traits={
        "WORLD_SOCIAL_PROPRIETY": GlobalTrait(
            id="WORLD_SOCIAL_PROPRIETY",
            name="Post-War Social Propriety",
            description="1940s English middle-class respectability constrains desire. Adultery is unthinkable; duty to marriage and children overrides personal happiness.",
            category="social_structure",
            magnitude=TraitVector(value=0.85, inertia=0.8),
            affected_domains=["social", "psychological", "emotional"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=400, triggered_by="EVT_CINEMA_DATE",
                    magnitude=TraitVector(value=0.7, inertia=0.7),
                    description="Laura begins to bend the rules by going to the cinema alone with a man — propriety loosens."),
                WorldTraitSnapshot(fabula_time=700, triggered_by="EVT_FRIENDS_ENCOUNTER_DECEPTION",
                    magnitude=TraitVector(value=0.85, inertia=0.8),
                    description="Being seen by Laura's friends snaps propriety back into force, requiring deception."),
                WorldTraitSnapshot(fabula_time=1200, triggered_by="EVT_FINAL_MEETING",
                    magnitude=TraitVector(value=0.95, inertia=0.9),
                    description="Propriety wins — Laura chooses duty over desire, ending the affair."),
            ],
        ),
        "WORLD_MARRIAGE_SACRED_INSTITUTION": GlobalTrait(
            id="WORLD_MARRIAGE_SACRED_INSTITUTION",
            name="Marriage as Sacred Institution / Family Duty",
            description="Both Laura and Alec are married with children. Marriage and the duty owed to spouse and children form a near-inviolable axis that ultimately overrides romantic love.",
            category="social_structure",
            magnitude=TraitVector(value=0.90, inertia=0.85),
            affected_domains=["social", "psychological", "emotional"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=1100, triggered_by="EVT_ALEC_ACCEPTS_POST",
                    magnitude=TraitVector(value=0.95, inertia=0.9),
                    description="For the sake of his family Alec ends the affair — family duty becomes the decisive force."),
            ],
        ),
        "WORLD_RAILWAY_LIMINAL": GlobalTrait(
            id="WORLD_RAILWAY_LIMINAL",
            name="Railway Station as Liminal Space",
            description="The Milford Junction refreshment room exists between destinations and identities — a threshold space where forbidden connections form.",
            category="environment",
            magnitude=TraitVector(value=0.6, inertia=0.5),
            affected_domains=["psychological", "emotional"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=200, triggered_by="EVT_GRIT_IN_EYE",
                    magnitude=TraitVector(value=0.75, inertia=0.55),
                    description="The threshold-space charge intensifies as a chance encounter ignites a forbidden bond."),
                WorldTraitSnapshot(fabula_time=1200, triggered_by="EVT_FINAL_MEETING",
                    magnitude=TraitVector(value=0.9, inertia=0.6),
                    description="The liminal space reaches peak intensity at the final parting — neither home nor destination."),
            ],
        ),
    },
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_LAURA", target_entity_id="ENT_ALEC", affinity=0.7, fear=0.4, power_dynamic=0.0, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_ALEC", target_entity_id="ENT_LAURA", affinity=0.8, fear=0.35, power_dynamic=0.0, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_LAURA", target_entity_id="ENT_FRED", affinity=0.62, fear=0.0, power_dynamic=-0.05, inertia=0.6),
        RelationshipEdge(source_entity_id="ENT_FRED", target_entity_id="ENT_LAURA", affinity=0.75, fear=0.0, power_dynamic=0.0, inertia=0.6),
        RelationshipEdge(source_entity_id="ENT_LAURA", target_entity_id="ENT_DOLLY", affinity=0.2, fear=0.0, power_dynamic=0.0, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_DOLLY", target_entity_id="ENT_LAURA", affinity=0.5, fear=0.0, power_dynamic=0.0, inertia=0.3),
        RelationshipEdge(source_entity_id="ENT_STEPHEN", target_entity_id="ENT_ALEC",
                         affinity=0.4, fear=0.0, power_dynamic=0.2, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_ALEC", target_entity_id="ENT_STEPHEN",
                         affinity=0.5, fear=0.1, power_dynamic=-0.1, inertia=0.5,
                         last_updated_fabula=800),
        RelationshipEdge(source_entity_id="ENT_MYRTLE", target_entity_id="ENT_DOLLY",
                         affinity=0.3, fear=0.0, power_dynamic=0.1, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_ALBERT", target_entity_id="ENT_MYRTLE",
                         affinity=0.6, fear=0.0, power_dynamic=-0.1, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_MYRTLE", target_entity_id="ENT_ALBERT",
                         affinity=0.5, fear=0.0, power_dynamic=0.1, inertia=0.4),
    ],
)
