# SPDX-FileCopyrightText: 2025-2026 David Rae Wilmot
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Frankenstein — high-fidelity WorldStateV1 test fixture.

Authored against the current ingestion prompts. Demonstrates all five
CausalEdge modalities, per-axis ``RelationshipMetric`` (only observed
axes populated), explicit ``evidence_strength`` everywhere, named-latent
WORLD_ traits (Promethean hubris, monstrous otherness, paternal duty)
wired as common-cause parents, ``state_timeline`` snapshots whose
inertia bumps under shock, and initial entity locations matching each
character's first appearance in the fabula.
"""
from shadow_loom.models import (
    Channel,
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, RelationshipMetric, TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
    NarrativeStyle,
)

world_state = WorldStateV1(
    narrative_style=NarrativeStyle(
        format='scene',
        target_word_min=600,
        target_word_max=1800,
        prose_density='moderate',
        voice='scene-level prose with some dialogue and sensory detail; first-person POV; past tense',
        style_exemplar='Victor Frankenstein, born in Naples to an upper-class Genevese family, spends his youth obsessed with alchemy. As he grows older, he develops an interest in modern sciences such as chemistry and electricity. After his mother Caroline dies of scarlet fever, Victor leaves home to attend the University of Ingolstadt. Through his studies, Victor discovers a new way to create life, assembling human body parts stolen from charnel houses and fresh graves, which he uses to create a large and grotesque humanoid creature.',
        source_word_count=677,
    ),
    # ── LOCATIONS ──────────────────────────────────────────────────────
    locations={
        "LOC_GENEVA": Location(
            name="Geneva",
            description="The Frankenstein family estate on Lake Geneva — Victor's birthplace and site of William's and Elizabeth's deaths.",
            ambient_state={
                "comfort": AmbientVector(value=0.7, volatility=0.3, evidence_strength="strong"),
                "respectability": AmbientVector(value=0.8, volatility=0.2, evidence_strength="strong"),
                "grief": AmbientVector(value=0.2, volatility=0.6, evidence_strength="moderate"),
            },
        ),
        "LOC_INGOLSTADT": Location(
            name="University of Ingolstadt",
            description="German university where Victor studies natural philosophy and chemistry under Waldman and Krempe.",
            ambient_state={
                "ambition": AmbientVector(value=0.8, volatility=0.3, evidence_strength="strong"),
                "isolation": AmbientVector(value=0.6, volatility=0.4, evidence_strength="moderate"),
            },
        ),
        "LOC_LABORATORY": Location(
            name="Victor's Attic Laboratory",
            description="Squalid attic in Ingolstadt where the Creature is assembled from charnel-house parts and animated.",
            ambient_state={
                "horror": AmbientVector(value=0.85, volatility=0.3, evidence_strength="strong"),
                "obsession": AmbientVector(value=0.9, volatility=0.4, evidence_strength="strong"),
            },
        ),
        "LOC_DELACEY_COTTAGE": Location(
            name="De Lacey Cottage",
            description="Rural French-exiled cottage where the Creature secretly observes the De Lacey family and learns language and morality.",
            ambient_state={
                "warmth": AmbientVector(value=0.7, volatility=0.3, evidence_strength="strong"),
                "poverty": AmbientVector(value=0.6, volatility=0.2, evidence_strength="strong"),
                "concealment": AmbientVector(value=0.7, volatility=0.3, evidence_strength="strong"),
            },
        ),
        "LOC_MER_DE_GLACE": Location(
            name="Mer de Glace",
            description="Alpine glacier above Chamonix where the Creature confronts Victor and tells his story.",
            ambient_state={
                "sublime": AmbientVector(value=0.9, volatility=0.2, evidence_strength="strong"),
                "isolation": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_ORKNEY": Location(
            name="Orkney Hut",
            description="Remote Scottish island shed where Victor begins, then destroys, the female creature.",
            ambient_state={
                "desolation": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
                "dread": AmbientVector(value=0.75, volatility=0.4, evidence_strength="strong"),
            },
        ),
        "LOC_IRISH_COAST": Location(
            name="Irish Coast",
            description="Shore where Victor lands after dumping the destroyed female creature and is arrested for Clerval's murder.",
            ambient_state={
                "dread": AmbientVector(value=0.7, volatility=0.5, evidence_strength="moderate"),
            },
        ),
        "LOC_ARCTIC": Location(
            name="Arctic Ice",
            description="Frozen sea where Victor pursues the Creature and is rescued by Walton's expedition.",
            ambient_state={
                "death": AmbientVector(value=0.9, volatility=0.2, evidence_strength="strong"),
                "vastness": AmbientVector(value=0.95, volatility=0.1, evidence_strength="strong"),
            },
        ),
        "LOC_WALTONS_SHIP": Location(
            name="Walton's Ship",
            description="Vessel of the North Pole expedition where Victor recounts his story and dies.",
            ambient_state={
                "isolation": AmbientVector(value=0.8, volatility=0.3, evidence_strength="strong"),
            },
        ),
    },

    # ── OBJECTS ─────────────────────────────────────────────────────────
    objects={
        "OBJ_GALVANIC_APPARATUS": NarrativeObject(
            id="OBJ_GALVANIC_APPARATUS", name="Galvanic Apparatus",
            location_id="LOC_LABORATORY", owner_id="ENT_VICTOR",
            properties={"state": "functional", "power_source": "electrical"},
            affordances=[Affordance(action="animate", target_type="Entity")],
        ),
        "OBJ_VICTOR_NOTES": NarrativeObject(
            id="OBJ_VICTOR_NOTES", name="Victor's Creation Notes",
            location_id=None, owner_id="ENT_CREATURE",
            properties={"state": "found_in_coat_pocket", "content": "step-by-step record of the creation"},
            affordances=[Affordance(action="inform", target_type="Entity")],
        ),
        "OBJ_DELACEY_BOOKS": NarrativeObject(
            id="OBJ_DELACEY_BOOKS", name="Paradise Lost / Plutarch / Werther",
            location_id="LOC_DELACEY_COTTAGE", owner_id=None,
            properties={"state": "intact", "content": "moral and emotional education"},
            affordances=[Affordance(action="educate", target_type="Entity")],
        ),
        "OBJ_FEMALE_CREATURE": NarrativeObject(
            id="OBJ_FEMALE_CREATURE", name="Half-Built Female Creature",
            location_id="LOC_ORKNEY", owner_id="ENT_VICTOR",
            properties={"state": "destroyed", "completion": "partial"},
            affordances=[Affordance(action="companion", target_type="Entity")],
        ),
    },

    # ── ENTITIES ────────────────────────────────────────────────────────
    entities={
        "ENT_VICTOR": Entity(
            id="ENT_VICTOR", name="Victor Frankenstein",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "ambition": TraitVector(value=0.9, inertia=0.55, evidence_strength="strong"),
                "obsession": TraitVector(value=0.8, inertia=0.5, evidence_strength="strong"),
                "intellect": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "guilt": TraitVector(value=0.1, inertia=0.25, evidence_strength="weak"),
                "fear": TraitVector(value=0.2, inertia=0.3, evidence_strength="weak"),
                "isolation": TraitVector(value=0.3, inertia=0.4, evidence_strength="moderate"),
                "vengeance": TraitVector(value=0.1, inertia=0.3, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="WORLD_SCIENTIFIC_HUBRIS",
                       perceived_state="The boundaries between life and death may be broken by science",
                       confidence=0.9, inertia=0.6, evidence_strength="strong"),
            ],
            constants=["intellect", "social_privilege"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_CAROLINE_DIES",
                    traits={
                        "obsession": TraitVector(value=1.00, inertia=0.50, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_VICTOR_LEAVES_GENEVA",
                    location_id="LOC_INGOLSTADT"),
                EntityStateSnapshot(fabula_time=3000, triggered_by="EVT_CREATION",
                    location_id="LOC_LABORATORY",
                    traits={
                        "fear": TraitVector(value=0.85, inertia=0.45, evidence_strength="strong"),
                        "guilt": TraitVector(value=0.5, inertia=0.4, evidence_strength="strong"),
                        "obsession": TraitVector(value=0.4, inertia=0.55, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_CREATURE",
                               perceived_state="My creation is a hideous wretch that I must hide from the world",
                               confidence=0.95, inertia=0.65, established_at_fabula=3000, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=5000, triggered_by="EVT_JUSTINE_EXECUTED",
                    traits={
                        "guilt": TraitVector(value=0.8, inertia=0.55, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=9000, triggered_by="EVT_CREATURE_DEMANDS_MATE",
                    location_id="LOC_MER_DE_GLACE",
                    beliefs_added=[
                        Belief(target_id="ENT_CREATURE",
                               perceived_state="The Creature has reason and feeling; I owe it a companion",
                               confidence=0.6, inertia=0.45, established_at_fabula=9000, evidence_strength="moderate"),
                    ]),
                EntityStateSnapshot(fabula_time=11000, triggered_by="EVT_MATE_DESTROYED",
                    location_id="LOC_ORKNEY",
                    traits={
                        "fear": TraitVector(value=0.9, inertia=0.5, evidence_strength="strong"),
                    },
                    beliefs_invalidated=["ENT_CREATURE"]),
                EntityStateSnapshot(fabula_time=13000, triggered_by="EVT_ELIZABETH_MURDERED",
                    location_id="LOC_GENEVA",
                    traits={
                        "vengeance": TraitVector(value=1.0, inertia=0.6, evidence_strength="strong"),
                        "isolation": TraitVector(value=0.95, inertia=0.55, evidence_strength="strong"),
                        "obsession": TraitVector(value=1.0, inertia=0.6, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=14000, triggered_by="EVT_ARCTIC_CHASE",
                    location_id="LOC_ARCTIC"),
                EntityStateSnapshot(fabula_time=15000, triggered_by="EVT_VICTOR_DIES",
                    location_id="LOC_WALTONS_SHIP", status="dead"),
                
            ],
        ),
        "ENT_CREATURE": Entity(
            id="ENT_CREATURE", name="The Creature",
            location_id="LOC_LABORATORY", status="healthy",
            traits={
                "loneliness": TraitVector(value=0.4, inertia=0.3, evidence_strength="moderate"),
                "rage": TraitVector(value=0.1, inertia=0.25, evidence_strength="weak"),
                "compassion": TraitVector(value=0.7, inertia=0.4, evidence_strength="strong"),
                "intelligence": TraitVector(value=0.5, inertia=0.4, evidence_strength="moderate"),
                "eloquence": TraitVector(value=0.2, inertia=0.3, evidence_strength="weak"),
                "vengefulness": TraitVector(value=0.1, inertia=0.3, evidence_strength="weak"),
            },
            beliefs=[],
            constants=["unnatural_origin", "superhuman_strength", "grotesque_appearance"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=3500, triggered_by="EVT_CREATURE_FLEES",
                    location_id="LOC_DELACEY_COTTAGE"),
                EntityStateSnapshot(fabula_time=4000, triggered_by="EVT_WILLIAM_MURDERED",
                    location_id="LOC_GENEVA"),
                EntityStateSnapshot(fabula_time=6000, triggered_by="EVT_CREATURE_LEARNS",
                    traits={
                        "intelligence": TraitVector(value=0.85, inertia=0.55, evidence_strength="strong"),
                        "eloquence": TraitVector(value=0.8, inertia=0.5, evidence_strength="strong"),
                        "compassion": TraitVector(value=0.85, inertia=0.5, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_DELACEY",
                               perceived_state="The De Laceys may accept me if I approach the blind father first",
                               confidence=0.7, inertia=0.4, established_at_fabula=6000, evidence_strength="moderate"),
                    ]),
                EntityStateSnapshot(fabula_time=7000, triggered_by="EVT_CREATURE_FINDS_NOTES",
                    beliefs_added=[
                        Belief(target_id="ENT_VICTOR",
                               perceived_state="My creator regarded me with horror from the moment I drew breath",
                               confidence=0.95, inertia=0.7, established_at_fabula=7000, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=8000, triggered_by="EVT_CREATURE_REJECTED",
                    traits={
                        "rage": TraitVector(value=0.7, inertia=0.45, evidence_strength="strong"),
                        "loneliness": TraitVector(value=0.95, inertia=0.5, evidence_strength="strong"),
                        "compassion": TraitVector(value=0.45, inertia=0.5, evidence_strength="strong"),
                        "vengefulness": TraitVector(value=0.6, inertia=0.4, evidence_strength="strong"),
                    },
                    beliefs_invalidated=["ENT_DELACEY"]),
                EntityStateSnapshot(fabula_time=9000, triggered_by="EVT_CREATURE_DEMANDS_MATE",
                    location_id="LOC_MER_DE_GLACE"),
                EntityStateSnapshot(fabula_time=11000, triggered_by="EVT_MATE_DESTROYED",
                    location_id="LOC_ORKNEY",
                    traits={
                        "rage": TraitVector(value=1.0, inertia=0.55, evidence_strength="strong"),
                        "compassion": TraitVector(value=0.05, inertia=0.6, evidence_strength="strong"),
                        "vengefulness": TraitVector(value=1.0, inertia=0.55, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=15000, triggered_by="EVT_VICTOR_DIES",
                    location_id="LOC_WALTONS_SHIP",
                    traits={
                        "rage": TraitVector(value=0.2, inertia=0.4, evidence_strength="strong"),
                        "loneliness": TraitVector(value=1.0, inertia=0.6, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_ELIZABETH": Entity(
            id="ENT_ELIZABETH", name="Elizabeth Lavenza",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "devotion": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                "patience": TraitVector(value=0.75, inertia=0.55, evidence_strength="moderate"),
                "kindness": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR",
                       perceived_state="Victor loves me but is consumed by a secret torment",
                       confidence=0.7, inertia=0.45, evidence_strength="moderate"),
                Belief(target_id="ENT_JUSTINE",
                       perceived_state="Justine is innocent of William's murder",
                       confidence=0.95, inertia=0.65, established_at_fabula=4500, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=13000, triggered_by="EVT_ELIZABETH_MURDERED",
                    status="dead"),
            ],
        ),
        "ENT_CLERVAL": Entity(
            id="ENT_CLERVAL", name="Henry Clerval",
            location_id="LOC_INGOLSTADT", status="healthy",
            traits={
                "warmth": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                "optimism": TraitVector(value=0.75, inertia=0.55, evidence_strength="strong"),
                "loyalty": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR",
                       perceived_state="Victor is a brilliant friend who needs grounding and care",
                       confidence=0.8, inertia=0.55, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=12000, triggered_by="EVT_CLERVAL_MURDERED",
                    location_id="LOC_IRISH_COAST", status="dead"),
            ],
        ),
        "ENT_WILLIAM": Entity(
            id="ENT_WILLIAM", name="William Frankenstein",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "innocence": TraitVector(value=0.95, inertia=0.6, evidence_strength="strong"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=4000, triggered_by="EVT_WILLIAM_MURDERED",
                    status="dead"),
            ],
        ),
        "ENT_JUSTINE": Entity(
            id="ENT_JUSTINE", name="Justine Moritz",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "devotion": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
                "innocence": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                "piety": TraitVector(value=0.7, inertia=0.55, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR",
                       perceived_state="The Frankensteins are my benefactors and I owe them everything",
                       confidence=0.85, inertia=0.6, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=5000, triggered_by="EVT_JUSTINE_EXECUTED",
                    status="dead"),
            ],
        ),
        "ENT_DELACEY": Entity(
            id="ENT_DELACEY", name="Old De Lacey",
            location_id="LOC_DELACEY_COTTAGE", status="healthy",
            traits={
                "compassion": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                "wisdom": TraitVector(value=0.7, inertia=0.6, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_CREATURE",
                       perceived_state="A gentle stranger in distress deserves my help",
                       confidence=0.6, inertia=0.4, established_at_fabula=8000, evidence_strength="moderate"),
            ],
            constants=["blind"],
        ),
        "ENT_FELIX": Entity(
            id="ENT_FELIX", name="Felix De Lacey",
            location_id="LOC_DELACEY_COTTAGE", status="healthy",
            traits={
                "protectiveness": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                "fear": TraitVector(value=0.4, inertia=0.4, evidence_strength="moderate"),
            },
            beliefs=[],
        ),
        "ENT_WALTON": Entity(
            id="ENT_WALTON", name="Captain Robert Walton",
            location_id="LOC_ARCTIC", status="healthy",
            traits={
                "ambition": TraitVector(value=0.85, inertia=0.5, evidence_strength="strong"),
                "compassion": TraitVector(value=0.65, inertia=0.45, evidence_strength="moderate"),
                "loneliness": TraitVector(value=0.6, inertia=0.45, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="WORLD_SCIENTIFIC_HUBRIS",
                       perceived_state="Glory at the Pole is worth any sacrifice",
                       confidence=0.85, inertia=0.5, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=14500, triggered_by="EVT_VICTOR_RESCUED",
                    location_id="LOC_WALTONS_SHIP",
                    beliefs_added=[
                        Belief(target_id="ENT_VICTOR",
                               perceived_state="Victor is a tragic genius and a brother in spirit",
                               confidence=0.8, inertia=0.5, established_at_fabula=14500, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=15000, triggered_by="EVT_VICTOR_DIES",
                    traits={
                        "ambition": TraitVector(value=0.4, inertia=0.55, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_ALPHONSE": Entity(
            id="ENT_ALPHONSE", name="Alphonse Frankenstein",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "paternal_devotion": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "propriety": TraitVector(value=0.8, inertia=0.7, evidence_strength="strong"),
                "frailty": TraitVector(value=0.4, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_VICTOR",
                       perceived_state="My son's melancholy is a passing affliction of youth",
                       confidence=0.6, inertia=0.5, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=13000, triggered_by="EVT_ELIZABETH_MURDERED",
                    traits={
                        "frailty": TraitVector(value=1.00, inertia=0.50, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=13200, triggered_by="EVT_ALPHONSE_DIES",
                    traits={"frailty": TraitVector(value=1.0, inertia=0.65, evidence_strength="strong")},
                    status="dead"),
                
            ],
            constants=["frankenstein_patriarch"],
        ),
        "ENT_ERNEST": Entity(
            id="ENT_ERNEST", name="Ernest Frankenstein",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "steadiness": TraitVector(value=0.7, inertia=0.55, evidence_strength="moderate"),
                "naivety": TraitVector(value=0.6, inertia=0.45, evidence_strength="moderate"),
            },
            beliefs=[],
        ),
        "ENT_CAROLINE": Entity(
            id="ENT_CAROLINE", name="Caroline Frankenstein",
            location_id="LOC_GENEVA", status="healthy",
            traits={
                "tenderness": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_CAROLINE_DIES",
                    status="dead"),
            ],
        ),
    },

    # ── EVENTS ──────────────────────────────────────────────────────────
    events=[
        EventNode(id="EVT_CAROLINE_DIES", fabula_time=500, syuzhet_index=1,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_CAROLINE"],
                  description="Victor's mother Caroline dies of scarlet fever caught nursing Elizabeth, propelling Victor toward Ingolstadt and the conquest of death."),
        EventNode(id="EVT_VICTOR_LEAVES_GENEVA", fabula_time=1000, syuzhet_index=2,
                  event_type="choice", actor_ids=["ENT_VICTOR"], target_ids=[],
                  description="Victor leaves Geneva to study natural philosophy at the University of Ingolstadt."),
        EventNode(id="EVT_VICTOR_DISCOVERS_PRINCIPLE", fabula_time=2000, syuzhet_index=3,
                  event_type="revelation", actor_ids=["ENT_VICTOR"], target_ids=[],
                  description="Victor discovers a means of imparting life to inanimate matter and resolves to build a man."),
        EventNode(id="EVT_CHARNEL_GATHERING", fabula_time=2500, syuzhet_index=4,
                  event_type="choice", actor_ids=["ENT_VICTOR"], target_ids=[],
                  description="Victor gathers body parts from charnel houses, dissecting rooms, and slaughterhouses to assemble the Creature."),
        EventNode(id="EVT_CREATION", fabula_time=3000, syuzhet_index=5,
                  event_type="outcome", actor_ids=["ENT_VICTOR"], target_ids=["ENT_CREATURE"],
                  description="Victor animates the Creature with the galvanic apparatus; recoiling in horror at the result, he flees."),
        EventNode(id="EVT_CREATURE_FLEES", fabula_time=3500, syuzhet_index=6,
                  event_type="choice", actor_ids=["ENT_CREATURE"], target_ids=[],
                  description="The newly conscious Creature wanders out of the laboratory, takes Victor's coat (with notes inside), and learns to avoid villagers who flee or stone him."),
        EventNode(id="EVT_WILLIAM_MURDERED", fabula_time=4000, syuzhet_index=8,
                  event_type="outcome", actor_ids=["ENT_CREATURE"], target_ids=["ENT_WILLIAM"],
                  description="The Creature, learning William is a Frankenstein, strangles the boy and plants a locket on the sleeping Justine."),
        EventNode(id="EVT_JUSTINE_EXECUTED", fabula_time=5000, syuzhet_index=9,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_JUSTINE"],
                  description="Justine is convicted of William's murder on the planted evidence and hanged; Victor stays silent."),
        EventNode(id="EVT_CREATURE_LEARNS", fabula_time=6000, syuzhet_index=7,
                  event_type="outcome", actor_ids=["ENT_CREATURE"], target_ids=[],
                  description="Hidden in a hovel beside the De Lacey cottage, the Creature learns French, reads Paradise Lost, and develops a moral imagination."),
        EventNode(id="EVT_CREATURE_FINDS_NOTES", fabula_time=7000, syuzhet_index=10,
                  event_type="revelation", actor_ids=["ENT_CREATURE"], target_ids=[],
                  description="The Creature reads Victor's notes from the coat pocket and learns the full story of his repulsive birth."),
        EventNode(id="EVT_CREATURE_APPROACHES_DELACEY", fabula_time=7800, syuzhet_index=11,
                  event_type="choice", actor_ids=["ENT_CREATURE"], target_ids=["ENT_DELACEY"],
                  description="The Creature reveals himself to the blind De Lacey, who treats him kindly."),
        EventNode(id="EVT_CREATURE_REJECTED", fabula_time=8000, syuzhet_index=12,
                  event_type="outcome", actor_ids=["ENT_FELIX"], target_ids=["ENT_CREATURE"],
                  description="Felix and the rest of the De Lacey family return, are horrified, and beat the Creature out of the cottage."),
        EventNode(id="EVT_CREATURE_DEMANDS_MATE", fabula_time=9000, syuzhet_index=13,
                  event_type="choice", actor_ids=["ENT_CREATURE"], target_ids=["ENT_VICTOR"],
                  description="On Mer de Glace the Creature confronts Victor, recounts his sufferings, and demands a female companion."),
        EventNode(id="EVT_VICTOR_BEGINS_MATE", fabula_time=10000, syuzhet_index=14,
                  event_type="choice", actor_ids=["ENT_VICTOR"], target_ids=[],
                  description="Victor sets up a hut on the Orkneys with Clerval nearby and reluctantly begins building the female creature."),
        EventNode(id="EVT_MATE_DESTROYED", fabula_time=11000, syuzhet_index=15,
                  event_type="choice", actor_ids=["ENT_VICTOR"], target_ids=["ENT_CREATURE"],
                  description="Imagining a race of monsters, Victor tears the half-built female apart while the Creature watches through the window; the Creature vows 'I shall be with you on your wedding night'."),
        EventNode(id="EVT_CLERVAL_MURDERED", fabula_time=12000, syuzhet_index=16,
                  event_type="outcome", actor_ids=["ENT_CREATURE"], target_ids=["ENT_CLERVAL"],
                  description="Victor lands on the Irish coast after dumping the female remains; the Creature has murdered Clerval, and Victor is briefly imprisoned for the killing."),
        EventNode(id="EVT_VICTOR_MARRIES_ELIZABETH", fabula_time=12800, syuzhet_index=17,
                  event_type="choice", actor_ids=["ENT_VICTOR", "ENT_ELIZABETH"], target_ids=[],
                  description="Released, Victor returns to Geneva and marries Elizabeth, hoping the Creature meant to kill him on the wedding night."),
        EventNode(id="EVT_ELIZABETH_MURDERED", fabula_time=13000, syuzhet_index=18,
                  event_type="outcome", actor_ids=["ENT_CREATURE"], target_ids=["ENT_ELIZABETH"],
                  description="The Creature strangles Elizabeth in the bridal chamber while Victor patrols outside."),
        EventNode(id="EVT_ALPHONSE_DIES", fabula_time=13200, syuzhet_index=19,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_ALPHONSE"],
                  description="Alphonse Frankenstein dies of grief days after Elizabeth's murder."),
        EventNode(id="EVT_ARCTIC_CHASE", fabula_time=14000, syuzhet_index=20,
                  event_type="choice", actor_ids=["ENT_VICTOR"], target_ids=["ENT_CREATURE"],
                  description="Victor pursues the Creature across Russia and onto the Arctic ice."),
        EventNode(id="EVT_VICTOR_RESCUED", fabula_time=14500, syuzhet_index=21,
                  event_type="outcome", actor_ids=["ENT_WALTON"], target_ids=["ENT_VICTOR"],
                  description="Walton's expedition rescues a near-dead Victor from a drifting ice floe; Victor recounts his story."),
        EventNode(id="EVT_VICTOR_DIES", fabula_time=15000, syuzhet_index=22,
                  event_type="outcome", actor_ids=["ENT_VICTOR"], target_ids=["ENT_WALTON"],
                  description="Victor dies aboard Walton's ship after urging the crew to glory; the crew instead vote to turn back."),
        EventNode(id="EVT_CREATURE_DEPARTS", fabula_time=15500, syuzhet_index=23,
                  event_type="choice", actor_ids=["ENT_CREATURE"], target_ids=["ENT_WALTON"],
                  description="The Creature boards the ship, mourns over Victor's body, declares his intent to immolate himself at the Pole, and vanishes into the ice."),

        # ── UTTERANCES (on-page speech-acts and written messages) ──
        EventNode(id="EVT_UTT_ELIZABETH_LETTER_NEWS_FROM_HOME", fabula_time=1800, syuzhet_index=24,
                  event_type="utterance",
                  description="Elizabeth writes to Victor at Ingolstadt with affectionate news of the Geneva household.",
                  content="My dear cousin, write — one line, one word will be a blessing to us. Henry... is well; William grows daily; do not forget us.",
                  speaker_id="ENT_ELIZABETH",
                  addressee_ids=["ENT_VICTOR"],
                  actor_ids=["ENT_ELIZABETH"],
                  target_ids=["ENT_WILLIAM", "ENT_CLERVAL"],
                  via_channel_id="CHN_FAMILY_CORRESPONDENCE", truth_value="true"),
        EventNode(id="EVT_UTT_ALPHONSE_LETTER_WILLIAM_DEAD", fabula_time=4200, syuzhet_index=25,
                  event_type="utterance",
                  description="Alphonse writes to summon Victor home, telling him William has been murdered.",
                  content="William is dead! — that sweet child... has been murdered. Come home, Victor; we need you.",
                  speaker_id="ENT_ALPHONSE",
                  addressee_ids=["ENT_VICTOR"],
                  actor_ids=["ENT_ALPHONSE"],
                  target_ids=["EVT_WILLIAM_MURDERED"],
                  via_channel_id="CHN_FAMILY_CORRESPONDENCE", truth_value="true"),
        EventNode(id="EVT_UTT_VICTOR_NOTES_REVEAL_ORIGIN", fabula_time=7000, syuzhet_index=26,
                  event_type="utterance",
                  description="The Creature reads Victor's lab notebook found in the clothes he carried from Ingolstadt and learns the truth of his own creation.",
                  content="Notebook entries describing the assembly and animation of the Creature from charnel-house parts.",
                  speaker_id="OBJ_VICTOR_NOTES",
                  addressee_ids=["ENT_CREATURE"],
                  actor_ids=["ENT_CREATURE", "OBJ_VICTOR_NOTES"],
                  target_ids=["EVT_CREATION", "EVT_CHARNEL_GATHERING", "ENT_VICTOR"],
                  via_channel_id=None, truth_value="true"),
        EventNode(id="EVT_UTT_CREATURE_NARRATES_LIFE", fabula_time=9000, syuzhet_index=27,
                  event_type="utterance",
                  description="On the Mer de Glace the Creature recounts his entire life since animation — flight, the De Laceys, the murder of William — to Victor.",
                  content="All men hate the wretched; how then must I be hated, who am miserable beyond all living things! ... Listen to my tale.",
                  speaker_id="ENT_CREATURE",
                  addressee_ids=["ENT_VICTOR"],
                  actor_ids=["ENT_CREATURE"],
                  target_ids=["EVT_CREATURE_FLEES", "EVT_CREATURE_LEARNS", "EVT_CREATURE_FINDS_NOTES", "EVT_CREATURE_APPROACHES_DELACEY", "EVT_CREATURE_REJECTED", "EVT_WILLIAM_MURDERED"],
                  via_channel_id="CHN_CREATURE_NARRATION_TO_VICTOR", truth_value="true"),
        EventNode(id="EVT_UTT_CREATURE_DEMANDS_FEMALE_MATE", fabula_time=9100, syuzhet_index=28,
                  event_type="utterance",
                  description="At the close of his narration the Creature demands that Victor build him a female companion as the price of his withdrawal from humanity.",
                  content="You must create a female for me, with whom I can live in the interchange of those sympathies necessary for my being. This you alone can do.",
                  speaker_id="ENT_CREATURE",
                  addressee_ids=["ENT_VICTOR"],
                  actor_ids=["ENT_CREATURE"],
                  target_ids=["OBJ_FEMALE_CREATURE", "EVT_VICTOR_BEGINS_MATE"],
                  via_channel_id="CHN_CREATURE_NARRATION_TO_VICTOR", truth_value="performative"),
        EventNode(id="EVT_UTT_CREATURE_WEDDING_NIGHT_THREAT", fabula_time=11100, syuzhet_index=29,
                  event_type="utterance",
                  description="Enraged by the destruction of the female creature, the Creature swears he will be with Victor on his wedding night.",
                  content="It is well. I go; but remember, I shall be with you on your wedding-night.",
                  speaker_id="ENT_CREATURE",
                  addressee_ids=["ENT_VICTOR"],
                  actor_ids=["ENT_CREATURE"],
                  target_ids=["EVT_MATE_DESTROYED", "EVT_VICTOR_MARRIES_ELIZABETH", "EVT_ELIZABETH_MURDERED"],
                  via_channel_id=None, truth_value="performative"),
        EventNode(id="EVT_UTT_VICTOR_DEATHBED_NARRATIVE", fabula_time=14700, syuzhet_index=30,
                  event_type="utterance",
                  description="Aboard Walton's ship Victor recounts his entire history — creation, the Creature, the murders — to Walton as a confession and warning.",
                  content="Learn from me, if not by my precepts, at least by my example, how dangerous is the acquirement of knowledge...",
                  speaker_id="ENT_VICTOR",
                  addressee_ids=["ENT_WALTON"],
                  actor_ids=["ENT_VICTOR"],
                  target_ids=["EVT_CREATION", "EVT_CREATURE_FLEES", "EVT_WILLIAM_MURDERED", "EVT_JUSTINE_EXECUTED", "EVT_CREATURE_DEMANDS_MATE", "EVT_MATE_DESTROYED", "EVT_CLERVAL_MURDERED", "EVT_ELIZABETH_MURDERED"],
                  via_channel_id="CHN_VICTOR_CONFESSION_TO_WALTON", truth_value="true"),
        EventNode(id="EVT_UTT_WALTON_LETTER_REPORTS_VICTORS_DEATH", fabula_time=15600, syuzhet_index=31,
                  event_type="utterance",
                  description="After Victor's death Walton writes to Ernest in Geneva to report that the last surviving Frankenstein brother has died at the Pole.",
                  content="Your brother Victor is dead. He died upon my ship in the Arctic, having recounted to me a most extraordinary and terrible history.",
                  speaker_id="ENT_WALTON",
                  addressee_ids=["ENT_ERNEST"],
                  actor_ids=["ENT_WALTON"],
                  target_ids=["EVT_VICTOR_DIES"],
                  via_channel_id=None, truth_value="true"),
        EventNode(id="EVT_UTT_CREATURE_FAREWELL_TO_WALTON", fabula_time=15650, syuzhet_index=32,
                  event_type="utterance",
                  description="Standing over Victor's corpse on the ship, the Creature mourns his creator and announces to Walton his intent to immolate himself at the Pole.",
                  content="I shall ascend my funeral pile triumphantly, and exult in the agony of the torturing flames. Farewell.",
                  speaker_id="ENT_CREATURE",
                  addressee_ids=["ENT_WALTON"],
                  actor_ids=["ENT_CREATURE"],
                  target_ids=["ENT_VICTOR", "EVT_VICTOR_DIES", "EVT_CREATURE_DEPARTS"],
                  via_channel_id=None, truth_value="performative"),
    ],

    # ── CAUSAL TOPOLOGY ────────────────────────────────────────────────
    causal_topology=[
        # ── chain_reaction ──
        CausalEdge(source_id="EVT_CAROLINE_DIES", target_id="EVT_VICTOR_LEAVES_GENEVA",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500, propagation_delay=500),
        CausalEdge(source_id="EVT_VICTOR_LEAVES_GENEVA", target_id="EVT_VICTOR_DISCOVERS_PRINCIPLE",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1000, propagation_delay=1000),
        CausalEdge(source_id="EVT_VICTOR_DISCOVERS_PRINCIPLE", target_id="EVT_CHARNEL_GATHERING",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=2000, propagation_delay=500),
        CausalEdge(source_id="EVT_CHARNEL_GATHERING", target_id="EVT_CREATION",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=2500, propagation_delay=500),
        CausalEdge(source_id="EVT_CREATION", target_id="EVT_CREATURE_FLEES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=3000, propagation_delay=500),
        CausalEdge(source_id="EVT_CREATURE_FLEES", target_id="EVT_CREATURE_LEARNS",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=6.0, fabula_time=3500, propagation_delay=2500),
        CausalEdge(source_id="EVT_CREATURE_LEARNS", target_id="EVT_CREATURE_FINDS_NOTES",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=6.0, fabula_time=6000, propagation_delay=1000),
        # NOTE: this fixture artistically compresses William's murder (f=4000) to occur
        # before the creature reads Victor's notes (f=7000). In the novel the notes-
        # reading motivates the murder; here the on-loose creature kills William out of
        # post-creation bitterness, with the notes-reading retrospectively explaining
        # the framing of Justine. We therefore wire CREATURE_FLEES → WILLIAM_MURDERED
        # directly (positive delay) and drop the impossible negative-delay edge.
        CausalEdge(source_id="EVT_CREATURE_FLEES", target_id="EVT_WILLIAM_MURDERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=7.0, fabula_time=3500, propagation_delay=500),
        CausalEdge(source_id="EVT_CREATURE_LEARNS", target_id="EVT_CREATURE_APPROACHES_DELACEY",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=6000, propagation_delay=1800),
        CausalEdge(source_id="EVT_CREATURE_APPROACHES_DELACEY", target_id="EVT_CREATURE_REJECTED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=7800, propagation_delay=200),
        CausalEdge(source_id="EVT_CREATURE_REJECTED", target_id="EVT_CREATURE_DEMANDS_MATE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8000, propagation_delay=1000),
        CausalEdge(source_id="EVT_WILLIAM_MURDERED", target_id="EVT_JUSTINE_EXECUTED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=4000, propagation_delay=1000),
        CausalEdge(source_id="EVT_CREATURE_DEMANDS_MATE", target_id="EVT_VICTOR_BEGINS_MATE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=9000, propagation_delay=1000),
        CausalEdge(source_id="EVT_VICTOR_BEGINS_MATE", target_id="EVT_MATE_DESTROYED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=10000, propagation_delay=1000),
        CausalEdge(source_id="EVT_MATE_DESTROYED", target_id="EVT_CLERVAL_MURDERED",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=11000, propagation_delay=1000),
        CausalEdge(source_id="EVT_CLERVAL_MURDERED", target_id="EVT_VICTOR_MARRIES_ELIZABETH",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=12000, propagation_delay=800),
        CausalEdge(source_id="EVT_MATE_DESTROYED", target_id="EVT_ELIZABETH_MURDERED",
                   causality_type="chain_reaction", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=11000, propagation_delay=2000),
        CausalEdge(source_id="EVT_VICTOR_MARRIES_ELIZABETH", target_id="EVT_ELIZABETH_MURDERED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=12800, propagation_delay=200),
        CausalEdge(source_id="EVT_ELIZABETH_MURDERED", target_id="EVT_ALPHONSE_DIES",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=13000, propagation_delay=200),
        CausalEdge(source_id="EVT_ELIZABETH_MURDERED", target_id="EVT_ARCTIC_CHASE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=13000, propagation_delay=1000),
        CausalEdge(source_id="EVT_ARCTIC_CHASE", target_id="EVT_VICTOR_RESCUED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=14000, propagation_delay=500),
        CausalEdge(source_id="EVT_VICTOR_RESCUED", target_id="EVT_VICTOR_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=14500, propagation_delay=500),
        CausalEdge(source_id="EVT_VICTOR_DIES", target_id="EVT_CREATURE_DEPARTS",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=15000, propagation_delay=500),

        # ── mutation (Event → Entity trait) ──
        CausalEdge(source_id="EVT_CAROLINE_DIES", target_id="ENT_VICTOR",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500,
                   trait_target="obsession", trait_delta=0.3),
        CausalEdge(source_id="EVT_CREATION", target_id="ENT_VICTOR",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=3000,
                   trait_target="fear", trait_delta=0.7),
        CausalEdge(source_id="EVT_CREATION", target_id="ENT_VICTOR",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=3000,
                   trait_target="guilt", trait_delta=0.5),
        CausalEdge(source_id="EVT_JUSTINE_EXECUTED", target_id="ENT_VICTOR",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=5000,
                   trait_target="guilt", trait_delta=0.3),
        CausalEdge(source_id="EVT_CREATURE_LEARNS", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=6000,
                   trait_target="eloquence", trait_delta=0.6),
        CausalEdge(source_id="EVT_CREATURE_LEARNS", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=6000,
                   trait_target="intelligence", trait_delta=0.35),
        CausalEdge(source_id="EVT_CREATURE_FINDS_NOTES", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=7000,
                   trait_target="loneliness", trait_delta=0.3),
        CausalEdge(source_id="EVT_CREATURE_REJECTED", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=8000,
                   trait_target="rage", trait_delta=0.6),
        CausalEdge(source_id="EVT_CREATURE_REJECTED", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=8000,
                   trait_target="vengefulness", trait_delta=0.5),
        CausalEdge(source_id="EVT_CREATURE_REJECTED", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8000,
                   trait_target="compassion", trait_delta=-0.4),
        CausalEdge(source_id="EVT_MATE_DESTROYED", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=11000,
                   trait_target="vengefulness", trait_delta=0.4),
        CausalEdge(source_id="EVT_MATE_DESTROYED", target_id="ENT_CREATURE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=11000,
                   trait_target="compassion", trait_delta=-0.4),
        CausalEdge(source_id="EVT_ELIZABETH_MURDERED", target_id="ENT_VICTOR",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=13000,
                   trait_target="vengeance", trait_delta=0.9),
        CausalEdge(source_id="EVT_ELIZABETH_MURDERED", target_id="ENT_VICTOR",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=13000,
                   trait_target="isolation", trait_delta=0.65),
        CausalEdge(source_id="EVT_ELIZABETH_MURDERED", target_id="ENT_ALPHONSE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=13000,
                   trait_target="frailty", trait_delta=0.6),
        CausalEdge(source_id="EVT_VICTOR_DIES", target_id="ENT_WALTON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=15000,
                   trait_target="ambition", trait_delta=-0.45),

        # ── mutation_social ──
        CausalEdge(source_id="EVT_CREATION", target_id="ENT_VICTOR",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=8.0, fabula_time=3000,
                   trait_target="affinity", trait_delta=-0.7, rel_counterpart_id="ENT_CREATURE"),
        CausalEdge(source_id="EVT_CREATION", target_id="ENT_VICTOR",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=3000,
                   trait_target="fear", trait_delta=0.85, rel_counterpart_id="ENT_CREATURE"),
        CausalEdge(source_id="EVT_CREATURE_FINDS_NOTES", target_id="ENT_CREATURE",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=8.0, fabula_time=7000,
                   trait_target="affinity", trait_delta=-0.7, rel_counterpart_id="ENT_VICTOR"),
        CausalEdge(source_id="EVT_CREATURE_REJECTED", target_id="ENT_CREATURE",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8000,
                   trait_target="affinity", trait_delta=-0.7, rel_counterpart_id="ENT_DELACEY"),
        CausalEdge(source_id="EVT_MATE_DESTROYED", target_id="ENT_CREATURE",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=10.0, fabula_time=11000,
                   trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_VICTOR"),
        CausalEdge(source_id="EVT_CREATURE_DEMANDS_MATE", target_id="ENT_VICTOR",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=9000,
                   trait_target="fear", trait_delta=0.4, rel_counterpart_id="ENT_CREATURE"),
        CausalEdge(source_id="EVT_ELIZABETH_MURDERED", target_id="ENT_VICTOR",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=10.0, fabula_time=13000,
                   trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_CREATURE"),

        # ── affordance_gate ──
        CausalEdge(source_id="OBJ_GALVANIC_APPARATUS", target_id="EVT_CREATION",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=3000),
        CausalEdge(source_id="OBJ_DELACEY_BOOKS", target_id="EVT_CREATURE_LEARNS",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=6000),
        CausalEdge(source_id="OBJ_VICTOR_NOTES", target_id="EVT_CREATURE_FINDS_NOTES",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="strong",
                   causal_force=8.0, fabula_time=7000),
        CausalEdge(source_id="ENT_DELACEY", target_id="EVT_CREATURE_LEARNS",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=6000),

        # ── ambient_propagation ──
        CausalEdge(source_id="LOC_LABORATORY", target_id="ENT_VICTOR",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=2500),
        CausalEdge(source_id="LOC_ARCTIC", target_id="ENT_VICTOR",
                   causality_type="ambient_propagation", mechanism="physical", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=14000),
        CausalEdge(source_id="LOC_DELACEY_COTTAGE", target_id="ENT_CREATURE",
                   causality_type="ambient_propagation", mechanism="emotional", evidence_strength="weak",
                   causal_force=3.0, fabula_time=6000),

        # ── WORLD_ → Event (named-latent common-cause wiring) ──
        CausalEdge(source_id="WORLD_SCIENTIFIC_HUBRIS", target_id="EVT_VICTOR_LEAVES_GENEVA",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1000),
        CausalEdge(source_id="WORLD_SCIENTIFIC_HUBRIS", target_id="EVT_VICTOR_DISCOVERS_PRINCIPLE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=2000),
        CausalEdge(source_id="WORLD_SCIENTIFIC_HUBRIS", target_id="EVT_CREATION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=3000),
        CausalEdge(source_id="WORLD_SCIENTIFIC_HUBRIS", target_id="EVT_ARCTIC_CHASE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=14000),
        CausalEdge(source_id="WORLD_MONSTROUS_OTHERNESS", target_id="EVT_CREATURE_FLEES",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=3500),
        CausalEdge(source_id="WORLD_MONSTROUS_OTHERNESS", target_id="EVT_CREATURE_REJECTED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=8000),
        CausalEdge(source_id="WORLD_MONSTROUS_OTHERNESS", target_id="EVT_WILLIAM_MURDERED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=4000),
        CausalEdge(source_id="WORLD_MONSTROUS_OTHERNESS", target_id="EVT_MATE_DESTROYED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=11000),
        CausalEdge(source_id="WORLD_PATERNAL_DUTY", target_id="EVT_CREATURE_DEMANDS_MATE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=9000),
        CausalEdge(source_id="WORLD_PATERNAL_DUTY", target_id="EVT_VICTOR_BEGINS_MATE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=10000),
        CausalEdge(source_id="WORLD_PATERNAL_DUTY", target_id="EVT_MATE_DESTROYED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=11000),

        # ── orphan utterance wirings ──
        CausalEdge(source_id="EVT_UTT_ELIZABETH_LETTER_NEWS_FROM_HOME", target_id="EVT_VICTOR_DISCOVERS_PRINCIPLE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="weak",
                   causal_force=2.0, fabula_time=1800, propagation_delay=200),
        CausalEdge(source_id="EVT_WILLIAM_MURDERED", target_id="EVT_UTT_ALPHONSE_LETTER_WILLIAM_DEAD",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=8.0, fabula_time=4000, propagation_delay=200),
        CausalEdge(source_id="EVT_UTT_ALPHONSE_LETTER_WILLIAM_DEAD", target_id="EVT_JUSTINE_EXECUTED",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=4200, propagation_delay=800),
        CausalEdge(source_id="EVT_UTT_VICTOR_NOTES_REVEAL_ORIGIN", target_id="EVT_CREATURE_FINDS_NOTES",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_CREATURE_NARRATES_LIFE", target_id="EVT_UTT_CREATURE_DEMANDS_FEMALE_MATE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=5.0, fabula_time=9000, propagation_delay=100),
        CausalEdge(source_id="EVT_UTT_CREATURE_DEMANDS_FEMALE_MATE", target_id="EVT_VICTOR_BEGINS_MATE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=9100, propagation_delay=900),
        CausalEdge(source_id="EVT_UTT_CREATURE_WEDDING_NIGHT_THREAT", target_id="EVT_ELIZABETH_MURDERED",
                   causality_type="chain_reaction", mechanism="performative", evidence_strength="strong",
                   causal_force=9.0, fabula_time=11100, propagation_delay=1900),
        CausalEdge(source_id="EVT_UTT_VICTOR_DEATHBED_NARRATIVE", target_id="EVT_VICTOR_DIES",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=4.0, fabula_time=14700, propagation_delay=300),
        CausalEdge(source_id="EVT_VICTOR_DIES", target_id="EVT_UTT_WALTON_LETTER_REPORTS_VICTORS_DEATH",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=4.0, fabula_time=15000, propagation_delay=600),
        CausalEdge(source_id="EVT_CREATURE_DEPARTS", target_id="EVT_UTT_CREATURE_FAREWELL_TO_WALTON",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=4.0, fabula_time=15500, propagation_delay=150),
    ],

    # ── SPATIAL TOPOLOGY ────────────────────────────────────────────────
    spatial_topology=[
        SpatialEdge(source_id="LOC_GENEVA", target_id="LOC_INGOLSTADT"),
        SpatialEdge(source_id="LOC_INGOLSTADT", target_id="LOC_LABORATORY"),
        SpatialEdge(source_id="LOC_INGOLSTADT", target_id="LOC_DELACEY_COTTAGE"),
        SpatialEdge(source_id="LOC_GENEVA", target_id="LOC_MER_DE_GLACE"),
        SpatialEdge(source_id="LOC_INGOLSTADT", target_id="LOC_ORKNEY"),
        SpatialEdge(source_id="LOC_ORKNEY", target_id="LOC_IRISH_COAST"),
        SpatialEdge(source_id="LOC_IRISH_COAST", target_id="LOC_GENEVA"),
        SpatialEdge(source_id="LOC_GENEVA", target_id="LOC_ARCTIC"),
        SpatialEdge(source_id="LOC_ARCTIC", target_id="LOC_WALTONS_SHIP"),
    ],

    # ── INFORMATION TOPOLOGY ────────────────────────────────────────────
    # Only standing communication capabilities live here. One-shot speech-acts
    # (the Creature's wedding-night threat, the Creature reading Victor's
    # notebook, Walton's posthumous letter to Ernest, the Creature's farewell)
    # are modelled as utterance events with via_channel_id=None — they do not
    # establish persistent channels. The framing Walton↔Margaret epistolary
    # frame is omitted because Margaret Saville is not modelled as an entity
    # in this fixture.
    channels={
        "CHN_FAMILY_CORRESPONDENCE": Channel(
            id="CHN_FAMILY_CORRESPONDENCE",
            name="Geneva family ↔ Victor at Ingolstadt correspondence",
            medium="correspondence",
            participant_ids=["ENT_VICTOR", "ENT_ELIZABETH", "ENT_ALPHONSE"],
            directionality="duplex",
            intelligibility={},
            established_at_fabula=1000, terminated_at_fabula=13000,
            evidence_strength="strong",
        ),
        "CHN_CREATURE_NARRATION_TO_VICTOR": Channel(
            id="CHN_CREATURE_NARRATION_TO_VICTOR",
            name="The Creature's autobiographical narration to Victor on the Mer de Glace",
            medium="autobiographical_narration",
            participant_ids=["ENT_CREATURE", "ENT_VICTOR"],
            directionality="simplex",
            intelligibility={},
            established_at_fabula=9000, terminated_at_fabula=9200,
            evidence_strength="strong",
        ),
        "CHN_VICTOR_CONFESSION_TO_WALTON": Channel(
            id="CHN_VICTOR_CONFESSION_TO_WALTON",
            name="Victor's deathbed confession-narrative to Walton aboard ship",
            medium="autobiographical_narration",
            participant_ids=["ENT_VICTOR", "ENT_WALTON"],
            directionality="simplex",
            intelligibility={},
            established_at_fabula=14500, terminated_at_fabula=15000,
            evidence_strength="strong",
        ),
    },

    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_SCIENTIFIC_HUBRIS": GlobalTrait(
            id="WORLD_SCIENTIFIC_HUBRIS",
            name="Promethean Scientific Hubris",
            description="The Enlightenment conviction that the natural laws governing life and death may be transgressed by sufficiently bold inquiry, with no necessary moral consequence — the climate of thought that produces both Victor and Walton.",
            category="social_structure",
            magnitude=TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
            affected_domains=["psychological", "epistemic", "social"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=3000, triggered_by="EVT_CREATION",
                    magnitude=TraitVector(value=1.0, inertia=0.8, evidence_strength="strong"),
                    description="Animation of the Creature is the high-water mark of unchecked ambition."),
                WorldTraitSnapshot(fabula_time=15000, triggered_by="EVT_VICTOR_DIES",
                    magnitude=TraitVector(value=0.4, inertia=0.55, evidence_strength="strong"),
                    description="Victor's death and Walton's crew turning back together discredit the Promethean impulse within this story-world, but the cultural climate persists."),
            ],
        ),
        "WORLD_MONSTROUS_OTHERNESS": GlobalTrait(
            id="WORLD_MONSTROUS_OTHERNESS",
            name="Monstrous Otherness",
            description="Society's reflexive, near-universal rejection of the physically grotesque regardless of inner virtue. Drives every human encounter with the Creature and provides moral cover for his crimes.",
            category="social_structure",
            magnitude=TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
            affected_domains=["social", "psychological", "betrayal"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=8000, triggered_by="EVT_CREATURE_REJECTED",
                    magnitude=TraitVector(value=1.0, inertia=0.9, evidence_strength="strong"),
                    description="Even the kindly De Lacey family beats the Creature out of their cottage; the rejection is total."),
            ],
        ),
        "WORLD_PATERNAL_DUTY": GlobalTrait(
            id="WORLD_PATERNAL_DUTY",
            name="Paternal Duty to the Created",
            description="The named-latent ethical claim — pressed by the Creature in Miltonic terms ('I ought to be thy Adam') — that a creator owes its creation companionship and care. Operates as common-cause parent over the female-creature subplot.",
            category="social_structure",
            magnitude=TraitVector(value=0.55, inertia=0.6, evidence_strength="moderate"),
            affected_domains=["psychological", "emotional"],
        ),
    },

    # ── SOCIAL TOPOLOGY ────────────────────────────────────────────────
    social_topology=[
        # Victor ↔ Creature — the central bond, asymmetric: hatred outward, demanding need inward.
        RelationshipEdge(
            source_entity_id="ENT_VICTOR", target_entity_id="ENT_CREATURE",
            metrics={
                "affinity":      RelationshipMetric(value=-0.85, inertia=0.5, evidence_strength="strong", last_updated_fabula=13000),
                "fear":          RelationshipMetric(value=0.85, inertia=0.25, evidence_strength="strong", last_updated_fabula=11000),
                "power_dynamic": RelationshipMetric(value=0.4, inertia=0.65, evidence_strength="moderate", last_updated_fabula=3000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_CREATURE", target_entity_id="ENT_VICTOR",
            metrics={
                "affinity":      RelationshipMetric(value=-0.6, inertia=0.5, evidence_strength="strong", last_updated_fabula=11000),
                "power_dynamic": RelationshipMetric(value=-0.4, inertia=0.7, evidence_strength="strong", last_updated_fabula=7000),
            },
        ),
        # Victor ↔ Elizabeth — devoted but blocked by Victor's secret.
        RelationshipEdge(
            source_entity_id="ENT_VICTOR", target_entity_id="ENT_ELIZABETH",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.55, evidence_strength="strong", last_updated_fabula=12800),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_ELIZABETH", target_entity_id="ENT_VICTOR",
            metrics={
                "affinity": RelationshipMetric(value=0.9, inertia=0.6, evidence_strength="strong", last_updated_fabula=12800),
            },
        ),
        # Victor ↔ Clerval — devoted friendship.
        RelationshipEdge(
            source_entity_id="ENT_VICTOR", target_entity_id="ENT_CLERVAL",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.55, evidence_strength="strong", last_updated_fabula=11000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_CLERVAL", target_entity_id="ENT_VICTOR",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.55, evidence_strength="strong", last_updated_fabula=11000),
            },
        ),
        # Alphonse → Victor — paternal authority and care.
        RelationshipEdge(
            source_entity_id="ENT_ALPHONSE", target_entity_id="ENT_VICTOR",
            metrics={
                "affinity":      RelationshipMetric(value=0.85, inertia=0.6, evidence_strength="strong", last_updated_fabula=13000),
                "power_dynamic": RelationshipMetric(value=0.6, inertia=0.75, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_VICTOR", target_entity_id="ENT_ALPHONSE",
            metrics={
                "affinity":      RelationshipMetric(value=0.7, inertia=0.55, evidence_strength="strong", last_updated_fabula=13000),
                "power_dynamic": RelationshipMetric(value=-0.5, inertia=0.7, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        # Creature → De Lacey — fragile hope, then bitter loss.
        RelationshipEdge(
            source_entity_id="ENT_CREATURE", target_entity_id="ENT_DELACEY",
            metrics={
                "affinity":      RelationshipMetric(value=0.4, inertia=0.5, evidence_strength="strong", last_updated_fabula=8000),
                "power_dynamic": RelationshipMetric(value=-0.3, inertia=0.65, evidence_strength="moderate", last_updated_fabula=7800),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_DELACEY", target_entity_id="ENT_CREATURE",
            metrics={
                "affinity": RelationshipMetric(value=0.4, inertia=0.4, evidence_strength="moderate", last_updated_fabula=7800),
            },
        ),
        # Felix → Creature — pure terror and protection of family.
        RelationshipEdge(
            source_entity_id="ENT_FELIX", target_entity_id="ENT_CREATURE",
            metrics={
                "affinity": RelationshipMetric(value=-0.9, inertia=0.45, evidence_strength="strong", last_updated_fabula=8000),
                "fear":     RelationshipMetric(value=0.9, inertia=0.2, evidence_strength="strong", last_updated_fabula=8000),
            },
        ),
        # Creature → Elizabeth/William — instrumental hatred mediated by Victor.
        RelationshipEdge(
            source_entity_id="ENT_CREATURE", target_entity_id="ENT_WILLIAM",
            metrics={
                "affinity": RelationshipMetric(value=-0.6, inertia=0.4, evidence_strength="strong", last_updated_fabula=4000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_CREATURE", target_entity_id="ENT_ELIZABETH",
            metrics={
                "affinity": RelationshipMetric(value=-0.5, inertia=0.4, evidence_strength="strong", last_updated_fabula=13000),
            },
        ),
        # Walton ↔ Victor — late-blooming brotherhood / cautionary tale.
        RelationshipEdge(
            source_entity_id="ENT_WALTON", target_entity_id="ENT_VICTOR",
            metrics={
                "affinity": RelationshipMetric(value=0.75, inertia=0.5, evidence_strength="strong", last_updated_fabula=15000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_VICTOR", target_entity_id="ENT_WALTON",
            metrics={
                "affinity": RelationshipMetric(value=0.6, inertia=0.45, evidence_strength="strong", last_updated_fabula=15000),
            },
        ),
        # Justine → Frankensteins — devoted servant.
        RelationshipEdge(
            source_entity_id="ENT_JUSTINE", target_entity_id="ENT_ELIZABETH",
            metrics={
                "affinity":      RelationshipMetric(value=0.85, inertia=0.6, evidence_strength="strong", last_updated_fabula=4000),
                "power_dynamic": RelationshipMetric(value=-0.5, inertia=0.7, evidence_strength="strong", last_updated_fabula=4000),
            },
        ),
    ],
)
