"""Great Expectations — high-fidelity WorldStateV1 test fixture.

Quality checklist (all five causality modalities, varied force/evidence,
trait_target/trait_delta, state_timeline, rich beliefs, info edges, constants).
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    locations={
        "LOC_MARSHES": Location(name="Kent Marshes",
            description="The bleak graveyard marshes where Pip meets Magwitch.",
            ambient_state={"desolation": AmbientVector(value=0.8, volatility=0.3),
                           "fog": AmbientVector(value=0.7, volatility=0.4)}),
        "LOC_FORGE": Location(name="Joe's Forge",
            description="The blacksmith forge where Pip is raised by Joe and Mrs Joe.",
            ambient_state={"warmth": AmbientVector(value=0.7, volatility=0.2),
                           "simplicity": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_SATIS_HOUSE": Location(name="Satis House",
            description="Miss Havisham's decaying mansion frozen in time.",
            ambient_state={"decay": AmbientVector(value=0.9, volatility=0.2),
                           "bitterness": AmbientVector(value=0.8, volatility=0.3)}),
        "LOC_LONDON": Location(name="London",
            description="The city where Pip pursues his great expectations.",
            ambient_state={"ambition": AmbientVector(value=0.7, volatility=0.3),
                           "corruption": AmbientVector(value=0.5, volatility=0.3)}),
        "LOC_JAGGERS_OFFICE": Location(name="Jaggers's Office",
            description="The lawyer's office in Little Britain.",
            ambient_state={"authority": AmbientVector(value=0.8, volatility=0.2),
                           "menace": AmbientVector(value=0.5, volatility=0.3)}),
        "LOC_WEMMICK_CASTLE": Location(name="Wemmick's Castle",
            description="Wemmick's eccentric miniature castle in Walworth.",
            ambient_state={"warmth": AmbientVector(value=0.7, volatility=0.2)}),
        "LOC_TEMPLE": Location(name="Temple Chambers",
            description="Pip and Herbert's lodgings in London.",
            ambient_state={"aspiration": AmbientVector(value=0.6, volatility=0.3)}),
        "LOC_RIVER_THAMES": Location(name="River Thames",
            description="Where the escape attempt for Magwitch takes place.",
            ambient_state={"danger": AmbientVector(value=0.7, volatility=0.4),
                           "murk": AmbientVector(value=0.6, volatility=0.3)}),
    },
    objects={
        "OBJ_FILE": NarrativeObject(id="OBJ_FILE", name="File and Vittles",
            location_id=None, owner_id="ENT_PIP",
            properties={"state": "stolen", "purpose": "aid_convict"},
            affordances=[Affordance(action="free_shackles", target_type="Entity")]),
        "OBJ_WEDDING_DRESS": NarrativeObject(id="OBJ_WEDDING_DRESS",
            name="Miss Havisham's Wedding Dress",
            location_id="LOC_SATIS_HOUSE", owner_id="ENT_MISS_HAVISHAM",
            properties={"state": "rotting", "age": "decades"},
            affordances=[Affordance(action="symbolise_betrayal", target_type="Entity")]),
        "OBJ_CONVICT_MONEY": NarrativeObject(id="OBJ_CONVICT_MONEY",
            name="Magwitch's Fortune",
            location_id=None, owner_id="ENT_MAGWITCH",
            properties={"state": "accumulated", "source": "australian_sheep_farming"},
            affordances=[Affordance(action="fund_expectations", target_type="Entity")]),
        "OBJ_PLAYING_CARDS": NarrativeObject(id="OBJ_PLAYING_CARDS",
            name="Playing Cards",
            location_id="LOC_SATIS_HOUSE", owner_id="ENT_ESTELLA",
            properties={"state": "worn"},
            affordances=[Affordance(action="humiliate", target_type="Entity")]),
    },
    entities={
        "ENT_PIP": Entity(id="ENT_PIP", name="Pip",
            location_id="LOC_MARSHES", status="healthy",
            traits={
                "ambition": TraitVector(value=0.5, inertia=0.3),
                "shame": TraitVector(value=0.4, inertia=0.3),
                "kindness": TraitVector(value=0.7, inertia=0.4),
                "snobbery": TraitVector(value=0.2, inertia=0.2),
                "guilt": TraitVector(value=0.3, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_MISS_HAVISHAM", perceived_state="Miss Havisham is my secret benefactress",
                       confidence=0.8, inertia=0.5),
                Belief(target_id="ENT_ESTELLA", perceived_state="Estella is my destined love",
                       confidence=0.7, inertia=0.4),
            ],
            constants=["orphan", "blacksmith_origin"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=300, triggered_by="EVT_PIP_VISITS_SATIS",
                    traits={"shame": TraitVector(value=0.6, inertia=0.3),
                            "ambition": TraitVector(value=0.7, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=500, triggered_by="EVT_PIP_TO_LONDON",
                    traits={"snobbery": TraitVector(value=0.5, inertia=0.3)},
                    location_id="LOC_LONDON"),
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_MAGWITCH_RETURNS",
                    traits={"shame": TraitVector(value=0.8, inertia=0.3),
                            "snobbery": TraitVector(value=0.3, inertia=0.3)},
                    beliefs_invalidated=["ENT_MISS_HAVISHAM"],
                    beliefs_added=[Belief(target_id="ENT_MAGWITCH",
                        perceived_state="The convict is my true benefactor",
                        confidence=0.95, inertia=0.5, established_at_fabula=900)]),
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_PIP_FORGIVEN",
                    traits={"kindness": TraitVector(value=0.9, inertia=0.5),
                            "snobbery": TraitVector(value=0.1, inertia=0.2)}),
            ]),
        "ENT_ESTELLA": Entity(id="ENT_ESTELLA", name="Estella Havisham",
            location_id="LOC_SATIS_HOUSE", status="healthy",
            traits={
                "coldness": TraitVector(value=0.8, inertia=0.5),
                "beauty": TraitVector(value=0.9, inertia=0.6),
                "cruelty": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip is common and beneath me",
                       confidence=0.7, inertia=0.4),
                Belief(target_id="ENT_MISS_HAVISHAM", perceived_state="Miss Havisham controls my destiny",
                       confidence=0.8, inertia=0.5),
            ],
            constants=["adopted"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_ESTELLA_MARRIES_DRUMMLE",
                    traits={"coldness": TraitVector(value=0.6, inertia=0.5)}),
                EntityStateSnapshot(fabula_time=1700, triggered_by="EVT_REUNION",
                    traits={"cruelty": TraitVector(value=0.2, inertia=0.4)}),
            ]),
        "ENT_MISS_HAVISHAM": Entity(id="ENT_MISS_HAVISHAM", name="Miss Havisham",
            location_id="LOC_SATIS_HOUSE", status="healthy",
            traits={
                "bitterness": TraitVector(value=0.9, inertia=0.6),
                "manipulation": TraitVector(value=0.8, inertia=0.5),
                "grief": TraitVector(value=0.9, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_ESTELLA", perceived_state="Estella is my instrument of revenge on men",
                       confidence=0.9, inertia=0.6),
                Belief(target_id="ENT_PIP", perceived_state="Pip is another heart for Estella to break",
                       confidence=0.7, inertia=0.4),
            ],
            constants=["jilted_bride"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_HAVISHAM_REPENTS",
                    traits={"bitterness": TraitVector(value=0.5, inertia=0.6),
                            "grief": TraitVector(value=0.95, inertia=0.6)}),
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_HAVISHAM_FIRE",
                    status="dead"),
            ]),
        "ENT_MAGWITCH": Entity(id="ENT_MAGWITCH", name="Abel Magwitch",
            location_id="LOC_MARSHES", status="healthy",
            traits={
                "gratitude": TraitVector(value=0.8, inertia=0.5),
                "ferocity": TraitVector(value=0.6, inertia=0.4),
                "devotion": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip is the boy who saved me and I will make him a gentleman",
                       confidence=0.9, inertia=0.6),
                Belief(target_id="ENT_COMPEYSON", perceived_state="Compeyson ruined my life",
                       confidence=0.95, inertia=0.6),
            ],
            constants=["convict", "transported"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_MAGWITCH_RETURNS",
                    location_id="LOC_TEMPLE"),
                EntityStateSnapshot(fabula_time=1400, triggered_by="EVT_ESCAPE_FAILS",
                    status="injured",
                    traits={"ferocity": TraitVector(value=0.3, inertia=0.4)}),
            ]),
        "ENT_JOE": Entity(id="ENT_JOE", name="Joe Gargery",
            location_id="LOC_FORGE", status="healthy",
            traits={
                "goodness": TraitVector(value=0.95, inertia=0.7),
                "humility": TraitVector(value=0.9, inertia=0.6),
                "devotion": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip is the dear boy I raised",
                       confidence=0.9, inertia=0.6),
            ],
            constants=["blacksmith"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_PIP_SNUBS_JOE",
                    traits={"humility": TraitVector(value=0.95, inertia=0.6)}),
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_PIP_FORGIVEN",
                    traits={"devotion": TraitVector(value=0.9, inertia=0.6)}),
            ]),
        "ENT_HERBERT": Entity(id="ENT_HERBERT", name="Herbert Pocket",
            location_id="LOC_LONDON", status="healthy",
            traits={
                "cheerfulness": TraitVector(value=0.8, inertia=0.5),
                "loyalty": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip is my dear friend and companion",
                       confidence=0.8, inertia=0.5),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1400, triggered_by="EVT_ESCAPE_FAILS",
                    traits={"loyalty": TraitVector(value=0.8, inertia=0.5)}),
            ]),
        "ENT_JAGGERS": Entity(id="ENT_JAGGERS", name="Mr Jaggers",
            location_id="LOC_JAGGERS_OFFICE", status="healthy",
            traits={
                "authority": TraitVector(value=0.9, inertia=0.6),
                "inscrutability": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip is my client, nothing more",
                       confidence=0.7, inertia=0.5),
            ],
            constants=["criminal_lawyer"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_MAGWITCH_RETURNS",
                    traits={"inscrutability": TraitVector(value=0.9, inertia=0.5)}),
            ]),
        "ENT_COMPEYSON": Entity(id="ENT_COMPEYSON", name="Compeyson",
            location_id="LOC_LONDON", status="healthy",
            traits={
                "villainy": TraitVector(value=0.9, inertia=0.6),
                "cunning": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_MAGWITCH", perceived_state="Magwitch is a brute I can exploit",
                       confidence=0.8, inertia=0.5),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1400, triggered_by="EVT_ESCAPE_FAILS",
                    status="dead"),
            ]),
        "ENT_BIDDY": Entity(id="ENT_BIDDY", name="Biddy",
            location_id="LOC_FORGE", status="healthy",
            traits={
                "intelligence": TraitVector(value=0.7, inertia=0.5),
                "patience": TraitVector(value=0.8, inertia=0.5),
                "goodness": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip has lost sight of what matters",
                       confidence=0.7, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_PIP_FORGIVEN",
                    traits={"patience": TraitVector(value=0.9, inertia=0.5)}),
            ]),
        "ENT_ORLICK": Entity(id="ENT_ORLICK", name="Dolge Orlick",
            location_id="LOC_FORGE", status="healthy",
            traits={
                "malice": TraitVector(value=0.8, inertia=0.5),
                "brute_strength": TraitVector(value=0.8, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip stole my rightful place",
                       confidence=0.7, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_MRS_JOE_ATTACKED",
                    traits={"malice": TraitVector(value=0.9, inertia=0.5)}),
            ]),
        "ENT_WEMMICK": Entity(id="ENT_WEMMICK", name="John Wemmick",
            location_id="LOC_JAGGERS_OFFICE", status="healthy",
            traits={
                "shrewdness": TraitVector(value=0.85, inertia=0.6),
                "warmth": TraitVector(value=0.7, inertia=0.5),
                "professional_reserve": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip is a friend at Walworth, a client in Little Britain",
                       confidence=0.85, inertia=0.6),
            ],
            constants=["jaggers_clerk", "walworth_sentiments"]),
        "ENT_MRS_JOE": Entity(id="ENT_MRS_JOE", name="Mrs Joe Gargery",
            location_id="LOC_FORGE", status="healthy",
            traits={
                "sharpness": TraitVector(value=0.85, inertia=0.6),
                "resentment": TraitVector(value=0.8, inertia=0.6),
                "pride": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip is an ungrateful burden I raised by hand",
                       confidence=0.85, inertia=0.6),
            ],
            constants=["pip_sister"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_MRS_JOE_ATTACKED",
                    traits={"sharpness": TraitVector(value=0.1, inertia=0.6),
                            "resentment": TraitVector(value=0.2, inertia=0.5)},
                    status="injured"),
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_PIP_COURTS_ESTELLA",
                    status="dead"),
            ]),
        "ENT_DRUMMLE": Entity(id="ENT_DRUMMLE", name="Bentley Drummle",
            location_id="LOC_LONDON", status="healthy",
            traits={
                "brutishness": TraitVector(value=0.85, inertia=0.6),
                "arrogance": TraitVector(value=0.85, inertia=0.6),
                "sullenness": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_ESTELLA", perceived_state="Estella is a prize to dominate",
                       confidence=0.7, inertia=0.5),
                Belief(target_id="ENT_PIP", perceived_state="Pip is a jumped-up apprentice",
                       confidence=0.8, inertia=0.5),
            ],
            constants=["baronet_heir"]),
    },
    events=[
        EventNode(id="EVT_CONVICT_ENCOUNTER", fabula_time=100, syuzhet_index=1, event_type="outcome",
                  actor_ids=["ENT_MAGWITCH"], target_ids=["ENT_PIP"],
                  description="Young Pip encounters the escaped convict Magwitch in the marshes graveyard."),
        EventNode(id="EVT_PIP_STEALS_FILE", fabula_time=200, syuzhet_index=2, event_type="choice",
                  actor_ids=["ENT_PIP"], target_ids=["ENT_MAGWITCH"],
                  description="Pip steals a file and food from the forge for the convict."),
        EventNode(id="EVT_PIP_VISITS_SATIS", fabula_time=300, syuzhet_index=3, event_type="outcome",
                  actor_ids=["ENT_PIP"], target_ids=["ENT_MISS_HAVISHAM", "ENT_ESTELLA"],
                  description="Pip visits Satis House, plays cards with Estella, and feels ashamed of his origins."),
        EventNode(id="EVT_PIP_APPRENTICED", fabula_time=400, syuzhet_index=4, event_type="outcome",
                  actor_ids=["ENT_PIP"], target_ids=["ENT_JOE"],
                  description="Pip is apprenticed to Joe at the forge, but dreams of being a gentleman."),
        EventNode(id="EVT_PIP_TO_LONDON", fabula_time=500, syuzhet_index=5, event_type="outcome",
                  actor_ids=["ENT_PIP", "ENT_JAGGERS"], target_ids=[],
                  description="Jaggers informs Pip of his great expectations; Pip departs for London."),
        EventNode(id="EVT_MRS_JOE_ATTACKED", fabula_time=600, syuzhet_index=6, event_type="outcome",
                  actor_ids=["ENT_ORLICK"], target_ids=[],
                  description="Orlick attacks Mrs Joe with a leg-iron, leaving her brain-damaged."),
        EventNode(id="EVT_PIP_SNUBS_JOE", fabula_time=700, syuzhet_index=7, event_type="choice",
                  actor_ids=["ENT_PIP"], target_ids=["ENT_JOE"],
                  description="Pip is ashamed when Joe visits him in London; Joe leaves quietly."),
        EventNode(id="EVT_PIP_COURTS_ESTELLA", fabula_time=800, syuzhet_index=8, event_type="outcome",
                  actor_ids=["ENT_PIP"], target_ids=["ENT_ESTELLA"],
                  description="Pip pursues Estella in London society, who warns him she has no heart."),
        EventNode(id="EVT_MAGWITCH_RETURNS", fabula_time=900, syuzhet_index=9, event_type="revelation",
                  actor_ids=["ENT_MAGWITCH"], target_ids=["ENT_PIP"],
                  description="Magwitch returns from Australia, revealing himself as Pip's secret benefactor."),
        EventNode(id="EVT_PIP_LEARNS_ESTELLA_PARENTAGE", fabula_time=1000, syuzhet_index=10,
                  event_type="revelation",
                  actor_ids=["ENT_JAGGERS"], target_ids=["ENT_PIP"],
                  description="Pip discovers Estella is Magwitch's daughter and Molly's child."),
        EventNode(id="EVT_ESTELLA_MARRIES_DRUMMLE", fabula_time=1100, syuzhet_index=11, event_type="outcome",
                  actor_ids=["ENT_ESTELLA"], target_ids=["ENT_PIP"],
                  description="Estella marries the brutish Bentley Drummle, devastating Pip."),
        EventNode(id="EVT_HAVISHAM_REPENTS", fabula_time=1200, syuzhet_index=12, event_type="outcome",
                  actor_ids=["ENT_MISS_HAVISHAM"], target_ids=["ENT_PIP"],
                  description="Miss Havisham begs Pip's forgiveness; her dress catches fire."),
        EventNode(id="EVT_HAVISHAM_FIRE", fabula_time=1200, syuzhet_index=13, event_type="outcome",
                  actor_ids=[], target_ids=["ENT_MISS_HAVISHAM"],
                  description="Miss Havisham is fatally burned when her wedding dress catches fire."),
        EventNode(id="EVT_ESCAPE_FAILS", fabula_time=1400, syuzhet_index=14, event_type="outcome",
                  actor_ids=["ENT_PIP", "ENT_HERBERT"], target_ids=["ENT_MAGWITCH", "ENT_COMPEYSON"],
                  description="The escape down the Thames fails; Compeyson drowns, Magwitch is fatally injured."),
        EventNode(id="EVT_MAGWITCH_DIES", fabula_time=1500, syuzhet_index=15, event_type="outcome",
                  actor_ids=["ENT_MAGWITCH"], target_ids=["ENT_PIP"],
                  description="Magwitch dies in prison; Pip tells him his daughter is alive and beautiful."),
        EventNode(id="EVT_PIP_FORGIVEN", fabula_time=1600, syuzhet_index=16, event_type="outcome",
                  actor_ids=["ENT_JOE"], target_ids=["ENT_PIP"],
                  description="Joe nurses the ill Pip back to health and pays his debts; Pip is humbled."),
        EventNode(id="EVT_REUNION", fabula_time=1700, syuzhet_index=17, event_type="outcome",
                  actor_ids=["ENT_PIP", "ENT_ESTELLA"], target_ids=[],
                  description="Years later, Pip and a chastened Estella meet at the ruins of Satis House."),
        EventNode(id="EVT_ORLICK_TRAP", fabula_time=1300, syuzhet_index=18, event_type="outcome",
                  actor_ids=["ENT_ORLICK"], target_ids=["ENT_PIP"],
                  description="Orlick lures Pip to a lime-kiln and tries to murder him; Herbert rescues Pip."),
    ],
    causal_topology=[
        # chain_reaction (13)
        CausalEdge(source_id="EVT_CONVICT_ENCOUNTER", target_id="EVT_PIP_STEALS_FILE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="EVT_PIP_STEALS_FILE", target_id="EVT_PIP_VISITS_SATIS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=200),
        CausalEdge(source_id="EVT_PIP_VISITS_SATIS", target_id="EVT_PIP_APPRENTICED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300),
        CausalEdge(source_id="EVT_PIP_APPRENTICED", target_id="EVT_PIP_TO_LONDON",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=400),
        CausalEdge(source_id="EVT_PIP_TO_LONDON", target_id="EVT_PIP_SNUBS_JOE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500),
        CausalEdge(source_id="EVT_PIP_SNUBS_JOE", target_id="EVT_PIP_COURTS_ESTELLA",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=700),
        CausalEdge(source_id="EVT_PIP_COURTS_ESTELLA", target_id="EVT_MAGWITCH_RETURNS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=800),
        CausalEdge(source_id="EVT_MAGWITCH_RETURNS", target_id="EVT_PIP_LEARNS_ESTELLA_PARENTAGE",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900),
        CausalEdge(source_id="EVT_PIP_LEARNS_ESTELLA_PARENTAGE", target_id="EVT_ESTELLA_MARRIES_DRUMMLE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1000),
        CausalEdge(source_id="EVT_HAVISHAM_REPENTS", target_id="EVT_HAVISHAM_FIRE",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1200),
        CausalEdge(source_id="EVT_ESCAPE_FAILS", target_id="EVT_MAGWITCH_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1400),
        CausalEdge(source_id="EVT_MAGWITCH_DIES", target_id="EVT_PIP_FORGIVEN",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500),
        CausalEdge(source_id="EVT_ESTELLA_MARRIES_DRUMMLE", target_id="EVT_REUNION",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1100),
        # mutation (8)
        CausalEdge(source_id="EVT_PIP_VISITS_SATIS", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300, trait_target="shame", trait_delta=0.2),
        CausalEdge(source_id="EVT_PIP_TO_LONDON", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500, trait_target="snobbery", trait_delta=0.3),
        CausalEdge(source_id="EVT_MAGWITCH_RETURNS", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=900, trait_target="shame", trait_delta=0.2),
        CausalEdge(source_id="EVT_PIP_FORGIVEN", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1600, trait_target="kindness", trait_delta=0.2),
        CausalEdge(source_id="EVT_HAVISHAM_REPENTS", target_id="ENT_MISS_HAVISHAM",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1200, trait_target="bitterness", trait_delta=-0.4),
        CausalEdge(source_id="EVT_ESTELLA_MARRIES_DRUMMLE", target_id="ENT_ESTELLA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1100, trait_target="coldness", trait_delta=-0.2),
        CausalEdge(source_id="EVT_MRS_JOE_ATTACKED", target_id="ENT_ORLICK",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=600, trait_target="malice", trait_delta=0.1),
        CausalEdge(source_id="EVT_PIP_SNUBS_JOE", target_id="ENT_JOE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=700, trait_target="humility", trait_delta=0.05),
        # mutation_social (3)
        CausalEdge(source_id="EVT_PIP_VISITS_SATIS", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300,
                   trait_target="affinity", trait_delta=0.5, rel_counterpart_id="ENT_ESTELLA"),
        CausalEdge(source_id="EVT_PIP_SNUBS_JOE", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=700,
                   trait_target="affinity", trait_delta=-0.3, rel_counterpart_id="ENT_JOE"),
        CausalEdge(source_id="EVT_MAGWITCH_RETURNS", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900,
                   trait_target="affinity", trait_delta=0.3, rel_counterpart_id="ENT_MAGWITCH"),
        # affordance_gate (3)
        CausalEdge(source_id="OBJ_FILE", target_id="EVT_PIP_STEALS_FILE",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=200),
        CausalEdge(source_id="OBJ_CONVICT_MONEY", target_id="EVT_PIP_TO_LONDON",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=9.0, fabula_time=500),
        CausalEdge(source_id="OBJ_WEDDING_DRESS", target_id="EVT_HAVISHAM_FIRE",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1200),
        # ambient_propagation (2)
        CausalEdge(source_id="LOC_SATIS_HOUSE", target_id="ENT_PIP",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=300),
        CausalEdge(source_id="LOC_LONDON", target_id="ENT_PIP",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.0, fabula_time=500),
    
        # ── WORLD_ → Event (named-latent common-cause wiring) ──
        CausalEdge(source_id="WORLD_CLASS_MOBILITY", target_id="EVT_PIP_TO_LONDON",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=500),
        CausalEdge(source_id="WORLD_CLASS_MOBILITY", target_id="EVT_PIP_SNUBS_JOE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=700),
        CausalEdge(source_id="WORLD_CLASS_MOBILITY", target_id="EVT_PIP_COURTS_ESTELLA",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=800),
        CausalEdge(source_id="WORLD_CLASS_MOBILITY", target_id="EVT_MAGWITCH_RETURNS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=900),
        CausalEdge(source_id="WORLD_CRIMINAL_JUSTICE", target_id="EVT_CONVICT_ENCOUNTER",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=100),
        CausalEdge(source_id="WORLD_CRIMINAL_JUSTICE", target_id="EVT_PIP_STEALS_FILE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=200),
        CausalEdge(source_id="WORLD_CRIMINAL_JUSTICE", target_id="EVT_ESCAPE_FAILS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1400),
        CausalEdge(source_id="WORLD_CRIMINAL_JUSTICE", target_id="EVT_MAGWITCH_DIES",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1500),
    ],
    spatial_topology=[
        SpatialEdge(source_id="LOC_MARSHES", target_id="LOC_FORGE"),
        SpatialEdge(source_id="LOC_FORGE", target_id="LOC_SATIS_HOUSE"),
        SpatialEdge(source_id="LOC_FORGE", target_id="LOC_LONDON"),
        SpatialEdge(source_id="LOC_LONDON", target_id="LOC_JAGGERS_OFFICE"),
        SpatialEdge(source_id="LOC_LONDON", target_id="LOC_WEMMICK_CASTLE"),
        SpatialEdge(source_id="LOC_LONDON", target_id="LOC_TEMPLE"),
        SpatialEdge(source_id="LOC_TEMPLE", target_id="LOC_RIVER_THAMES"),
    ],
    information_topology=[
        InformationEdge(source_id="ENT_JAGGERS", target_ids=["ENT_PIP"],
                        medium="legal_letter", established_at_fabula=500, discovered_at_syuzhet=5),
        InformationEdge(source_id="ENT_MAGWITCH", target_ids=["ENT_PIP"],
                        medium="confession", established_at_fabula=900, discovered_at_syuzhet=9),
        InformationEdge(source_id="ENT_JAGGERS", target_ids=["ENT_PIP"],
                        medium="conversation", established_at_fabula=1000, discovered_at_syuzhet=10),
        InformationEdge(source_id="ENT_ESTELLA", target_ids=["ENT_PIP"],
                        medium="warning", established_at_fabula=800, discovered_at_syuzhet=8),
        InformationEdge(source_id="ENT_MISS_HAVISHAM", target_ids=["ENT_PIP"],
                        medium="deathbed_confession", established_at_fabula=1200, discovered_at_syuzhet=13),
        InformationEdge(source_id="ENT_WEMMICK", target_ids=["ENT_PIP", "ENT_HERBERT"],
                        medium="covert_warning", is_encrypted=True,
                        established_at_fabula=1300, discovered_at_syuzhet=18),
        InformationEdge(source_id="ENT_HERBERT", target_ids=["ENT_PIP"],
                        medium="recounted_history", established_at_fabula=600, discovered_at_syuzhet=6),
        InformationEdge(source_id="ENT_BIDDY", target_ids=["ENT_PIP"],
                        medium="letter_from_home", established_at_fabula=800, discovered_at_syuzhet=8),
        InformationEdge(source_id="ENT_DRUMMLE", target_ids=["ENT_PIP"],
                        medium="club_boasting", established_at_fabula=1000, discovered_at_syuzhet=10),
    ],
    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_CLASS_MOBILITY": GlobalTrait(
            id="WORLD_CLASS_MOBILITY",
            name="Victorian Class Mobility",
            description="The possibility — and illusion — of rising from poverty to gentility through wealth, connections, or a secret benefactor.",
            category="social_structure",
            magnitude=TraitVector(value=0.7, inertia=0.6),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=500, triggered_by="EVT_PIP_TO_LONDON",
                    magnitude=TraitVector(value=0.9, inertia=0.7),
                    description="Pip's great expectations embody the dream of transcending class through wealth."),
                WorldTraitSnapshot(fabula_time=900, triggered_by="EVT_MAGWITCH_RETURNS",
                    magnitude=TraitVector(value=0.4, inertia=0.5),
                    description="Learning Magwitch is his benefactor shatters Pip's genteel self-image."),
            ],
        ),
        "WORLD_CRIMINAL_JUSTICE": GlobalTrait(
            id="WORLD_CRIMINAL_JUSTICE",
            name="Transportation and Penal System",
            description="The brutal 19th-century justice system that transports convicts to Australia, branding them for life regardless of reformation.",
            category="governance",
            magnitude=TraitVector(value=0.6, inertia=0.7),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=900, triggered_by="EVT_MAGWITCH_RETURNS",
                    magnitude=TraitVector(value=0.8, inertia=0.8),
                    description="Magwitch's illegal return to England makes Pip's fortune a death-sentence liability."),
            ],
        ),
    },
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_PIP", target_entity_id="ENT_ESTELLA",
                         affinity=0.8, fear=0.1, power_dynamic=-0.4, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_ESTELLA", target_entity_id="ENT_PIP",
                         affinity=0.1, fear=0.0, power_dynamic=0.4, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_PIP", target_entity_id="ENT_JOE",
                         affinity=0.6, fear=0.0, power_dynamic=0.0, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_JOE", target_entity_id="ENT_PIP",
                         affinity=0.9, fear=0.0, power_dynamic=-0.1, inertia=0.6),
        RelationshipEdge(source_entity_id="ENT_PIP", target_entity_id="ENT_MISS_HAVISHAM",
                         affinity=0.3, fear=0.3, power_dynamic=-0.5, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_MISS_HAVISHAM", target_entity_id="ENT_ESTELLA",
                         affinity=0.6, fear=0.0, power_dynamic=0.6, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_PIP", target_entity_id="ENT_MAGWITCH",
                         affinity=0.4, fear=0.2, power_dynamic=-0.1, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_MAGWITCH", target_entity_id="ENT_PIP",
                         affinity=0.9, fear=0.0, power_dynamic=0.2, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_PIP", target_entity_id="ENT_HERBERT",
                         affinity=0.8, fear=0.0, power_dynamic=0.0, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_MAGWITCH", target_entity_id="ENT_COMPEYSON",
                         affinity=-0.9, fear=0.1, power_dynamic=-0.3, inertia=0.6),
        RelationshipEdge(source_entity_id="ENT_ORLICK", target_entity_id="ENT_PIP",
                         affinity=-0.7, fear=0.0, power_dynamic=0.2, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_PIP", target_entity_id="ENT_BIDDY",
                         affinity=0.5, fear=0.0, power_dynamic=0.1, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_PIP", target_entity_id="ENT_WEMMICK",
                         affinity=0.7, fear=0.0, power_dynamic=-0.2, inertia=0.5),
        RelationshipEdge(source_entity_id="ENT_WEMMICK", target_entity_id="ENT_JAGGERS",
                         affinity=0.4, fear=0.2, power_dynamic=-0.4, inertia=0.7),
        RelationshipEdge(source_entity_id="ENT_MRS_JOE", target_entity_id="ENT_PIP",
                         affinity=-0.4, fear=0.0, power_dynamic=0.7, inertia=0.6),
        RelationshipEdge(source_entity_id="ENT_MRS_JOE", target_entity_id="ENT_JOE",
                         affinity=0.3, fear=0.0, power_dynamic=0.5, inertia=0.7),
        RelationshipEdge(source_entity_id="ENT_DRUMMLE", target_entity_id="ENT_ESTELLA",
                         affinity=0.4, fear=0.0, power_dynamic=0.6, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_ESTELLA", target_entity_id="ENT_DRUMMLE",
                         affinity=-0.3, fear=0.4, power_dynamic=-0.5, inertia=0.4,
                         last_updated_fabula=1100),
        RelationshipEdge(source_entity_id="ENT_DRUMMLE", target_entity_id="ENT_PIP",
                         affinity=-0.6, fear=0.0, power_dynamic=0.3, inertia=0.4),
    ],
)
