# SPDX-FileCopyrightText: 2025-2026 David Rae Wilmot
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Great Expectations — high-fidelity WorldStateV1 test fixture.

Authored against the current ingestion prompts. Demonstrates all five
CausalEdge modalities, per-axis ``RelationshipMetric`` (only observed
axes populated), explicit ``evidence_strength`` everywhere, and named-
latent WORLD_ traits (Victorian class hierarchy, Miss Havisham's
revenge ethos, the law's reach over the criminal class) wired as
common-cause parents over the events they jointly drive.
"""
from shadow_loom.models import (
    Channel,
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, RelationshipMetric, TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
    NarrativeStyle,
)

world_state = WorldStateV1(
    narrative_style=NarrativeStyle(
        format='synopsis',
        target_word_min=479,
        target_word_max=600,
        prose_density='sparse',
        voice='synoptic narration; no dialogue; condensed scene description; third-person POV; past tense',
        style_exemplar='The book includes three "stages" of Pip\'s expectations.\n\nFirst stage\nPhilip "Pip" Pirrip is a seven-year-old orphan who lives with his hot-tempered older sister and her kindly blacksmith husband Joe Gargery on the coastal marshes of Kent. On Christmas Eve 1812,[14] Pip visits the graves of his parents and siblings. There, he unexpectedly encounters an escaped convict who threatens to kill him if he does not bring back food and tools. Pip steals a file from among Joe\'s tools and a pie and brandy meant for Christmas dinner, which he delivers to the convict.',
        source_word_count=1439,
    ),
    # ── LOCATIONS ──────────────────────────────────────────────────────
    locations={
        "LOC_KENT_MARSHES": Location(
            name="Kent Marshes",
            description="The bleak coastal marshes near the Gargery forge where Pip first meets the convict Magwitch.",
            ambient_state={
                "isolation": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
                "danger": AmbientVector(value=0.6, volatility=0.5, evidence_strength="moderate"),
            },
        ),
        "LOC_FORGE": Location(
            name="Joe Gargery's Forge",
            description="The blacksmith's forge and adjoining cottage where Pip is raised by his sister and Joe.",
            ambient_state={
                "warmth": AmbientVector(value=0.65, volatility=0.4, evidence_strength="strong"),
                "domestic_tension": AmbientVector(value=0.6, volatility=0.4, evidence_strength="moderate"),
            },
        ),
        "LOC_SATIS_HOUSE": Location(
            name="Satis House",
            description="Miss Havisham's decaying mansion, frozen at the hour of her jilting; site of Pip's romantic ruin.",
            ambient_state={
                "decay": AmbientVector(value=0.95, volatility=0.1, evidence_strength="strong"),
                "obsession": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
                "stagnation": AmbientVector(value=0.9, volatility=0.1, evidence_strength="strong"),
            },
        ),
        "LOC_LONDON": Location(
            name="London",
            description="Bustling, filthy capital where Pip pursues his expectations among gentlemen and lawyers.",
            ambient_state={
                "filth": AmbientVector(value=0.7, volatility=0.3, evidence_strength="strong"),
                "ambition": AmbientVector(value=0.8, volatility=0.4, evidence_strength="strong"),
            },
        ),
        "LOC_BARNARDS_INN": Location(
            name="Barnard's Inn",
            description="Pip and Herbert's cramped chambers in London — their bachelor apartment of debts and confidences.",
            ambient_state={
                "shabbiness": AmbientVector(value=0.6, volatility=0.3, evidence_strength="moderate"),
            },
        ),
        "LOC_JAGGERS_OFFICE": Location(
            name="Jaggers's Office at Little Britain",
            description="The lawyer's intimidating chambers where the law and Pip's expectations are administered.",
            ambient_state={
                "authority": AmbientVector(value=0.9, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_THAMES": Location(
            name="The Thames",
            description="Tidal river along which Pip and Herbert attempt Magwitch's escape; site of Compeyson's death.",
            ambient_state={
                "danger": AmbientVector(value=0.75, volatility=0.5, evidence_strength="strong"),
            },
        ),
        "LOC_SLUICE_HOUSE": Location(
            name="Marsh Sluice-House",
            description="Abandoned lime-kiln where Orlick lures Pip and nearly murders him.",
            ambient_state={
                "danger": AmbientVector(value=0.9, volatility=0.3, evidence_strength="strong"),
                "isolation": AmbientVector(value=0.95, volatility=0.1, evidence_strength="strong"),
            },
        ),
        "LOC_NEWGATE": Location(
            name="Newgate Prison Hospital",
            description="The prison infirmary where Magwitch dies under sentence of death.",
            ambient_state={
                "despair": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_CAIRO": Location(
            name="Cairo",
            description="Egyptian outpost where Pip works for Clarriker's for eleven years, working off his debts.",
            ambient_state={
                "isolation": AmbientVector(value=0.6, volatility=0.3, evidence_strength="moderate"),
            },
        ),
    },

    # ── OBJECTS ────────────────────────────────────────────────────────
    objects={
        "OBJ_FILE_AND_PIE": NarrativeObject(
            id="OBJ_FILE_AND_PIE", name="Stolen File, Pie and Brandy",
            location_id="LOC_KENT_MARSHES", owner_id="ENT_MAGWITCH",
            properties={"state": "delivered"},
            affordances=[Affordance(action="free_from_irons", target_type="Entity")],
        ),
        "OBJ_LEG_IRON": NarrativeObject(
            id="OBJ_LEG_IRON", name="Filed-Off Leg Iron",
            location_id="LOC_KENT_MARSHES", owner_id="ENT_ORLICK",
            properties={"state": "weapon", "history": "magwitch_iron"},
            affordances=[Affordance(action="bludgeon", target_type="Entity")],
        ),
        "OBJ_WEDDING_DRESS": NarrativeObject(
            id="OBJ_WEDDING_DRESS", name="Miss Havisham's Wedding Dress",
            location_id="LOC_SATIS_HOUSE", owner_id="ENT_HAVISHAM",
            properties={"state": "yellowed", "frozen_at": "twenty_minutes_to_nine"},
            affordances=[Affordance(action="symbolize_betrayal", target_type="Entity"),
                         Affordance(action="catch_fire", target_type="Entity")],
        ),
        "OBJ_BANKNOTES": NarrativeObject(
            id="OBJ_BANKNOTES", name="Magwitch's Banknotes",
            location_id=None, owner_id="ENT_PIP",
            properties={"state": "disbursed_via_jaggers"},
            affordances=[Affordance(action="grant_gentleman_status", target_type="Entity")],
        ),
        "OBJ_ANONYMOUS_LETTER": NarrativeObject(
            id="OBJ_ANONYMOUS_LETTER", name="Orlick's Anonymous Letter",
            location_id=None, owner_id="ENT_PIP",
            properties={"state": "received", "content": "summons_to_sluice_house"},
            affordances=[Affordance(action="lure", target_type="Entity")],
        ),
    },

    # ── ENTITIES ────────────────────────────────────────────────────────
    entities={
        "ENT_PIP": Entity(
            id="ENT_PIP", name="Philip 'Pip' Pirrip",
            location_id="LOC_KENT_MARSHES", status="healthy",
            traits={
                "naivety": TraitVector(value=0.85, inertia=0.4, evidence_strength="strong"),
                "guilt": TraitVector(value=0.3, inertia=0.35, evidence_strength="moderate"),
                "ambition": TraitVector(value=0.4, inertia=0.4, evidence_strength="moderate"),
                "snobbery": TraitVector(value=0.1, inertia=0.3, evidence_strength="weak"),
                "loyalty": TraitVector(value=0.7, inertia=0.5, evidence_strength="strong"),
                "shame": TraitVector(value=0.2, inertia=0.3, evidence_strength="weak"),
                "compassion": TraitVector(value=0.7, inertia=0.5, evidence_strength="moderate"),
                "fear": TraitVector(value=0.1, inertia=0.3, evidence_strength="weak"),
                "gratitude_to_havisham": TraitVector(value=0.05, inertia=0.4, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_HAVISHAM", perceived_state="Miss Havisham must be my secret benefactress",
                       confidence=0.8, inertia=0.55, established_at_fabula=6000, evidence_strength="moderate"),
                Belief(target_id="ENT_ESTELLA", perceived_state="Estella was raised for me",
                       confidence=0.6, inertia=0.5, established_at_fabula=6000, evidence_strength="moderate"),
            ],
            constants=["orphan"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_PIP_MEETS_CONVICT",
                    traits={
                        "fear": TraitVector(value=0.70, inertia=0.30, evidence_strength="moderate"),
                        "compassion": TraitVector(value=0.75, inertia=0.50, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=2000, triggered_by="EVT_CONVICTS_RECAPTURED",
                    traits={
                        "guilt": TraitVector(value=0.50, inertia=0.35, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=4000, triggered_by="EVT_PIP_VISITS_SATIS",
                    location_id="LOC_SATIS_HOUSE",
                    traits={
                        "shame": TraitVector(value=0.7, inertia=0.4, evidence_strength="strong"),
                        "ambition": TraitVector(value=0.7, inertia=0.5, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=4800, triggered_by="EVT_HAVISHAM_PAYS_PREMIUM",
                    traits={
                        "gratitude_to_havisham": TraitVector(value=0.75, inertia=0.40, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=8000, triggered_by="EVT_JAGGERS_REVEALS_FORTUNE",
                    location_id="LOC_LONDON",
                    traits={
                        "snobbery": TraitVector(value=0.7, inertia=0.5, evidence_strength="strong"),
                        "ambition": TraitVector(value=0.85, inertia=0.55, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=8500, triggered_by="EVT_MRS_JOE_DIES",
                    traits={
                        "guilt": TraitVector(value=0.55, inertia=0.35, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=9000, triggered_by="EVT_JOE_VISITS_LONDON",
                    traits={
                        "shame": TraitVector(value=0.85, inertia=0.45, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=12000, triggered_by="EVT_DRUMMLE_TOAST",
                    traits={
                        "shame": TraitVector(value=0.35, inertia=0.30, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=13000, triggered_by="EVT_MAGWITCH_REVEALS_HIMSELF",
                    traits={
                        "snobbery": TraitVector(value=0.4, inertia=0.5, evidence_strength="strong"),
                        "shame": TraitVector(value=0.95, inertia=0.55, evidence_strength="strong"),
                        "compassion": TraitVector(value=0.55, inertia=0.55, evidence_strength="strong"),
                    },
                    beliefs_invalidated=["ENT_HAVISHAM"]),
                EntityStateSnapshot(fabula_time=15000, triggered_by="EVT_ESTELLA_MARRIES_DRUMMLE",
                    beliefs_invalidated=["ENT_ESTELLA"]),
                EntityStateSnapshot(fabula_time=16000, triggered_by="EVT_ORLICK_LURES_PIP",
                    traits={
                        "naivety": TraitVector(value=0.45, inertia=0.40, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=16200, triggered_by="EVT_PIP_RESCUED",
                    traits={
                        "compassion": TraitVector(value=0.80, inertia=0.50, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=17000, triggered_by="EVT_MAGWITCH_DIES",
                    traits={
                        "compassion": TraitVector(value=0.95, inertia=0.6, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=18000, triggered_by="EVT_JOE_NURSES_PIP",
                    location_id="LOC_BARNARDS_INN", status="ill",
                    traits={
                        "snobbery": TraitVector(value=0.05, inertia=0.55, evidence_strength="strong"),
                        "shame": TraitVector(value=0.7, inertia=0.5, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=19000, triggered_by="EVT_PIP_LEAVES_FOR_CAIRO",
                    location_id="LOC_CAIRO", status="healthy"),
                EntityStateSnapshot(fabula_time=21000, triggered_by="EVT_PIP_MEETS_ESTELLA_AGAIN",
                    location_id="LOC_SATIS_HOUSE"),
                
            ],
        ),
        "ENT_JOE": Entity(
            id="ENT_JOE", name="Joe Gargery",
            location_id="LOC_FORGE", status="healthy",
            traits={
                "kindness": TraitVector(value=0.95, inertia=0.75, evidence_strength="strong"),
                "loyalty": TraitVector(value=0.95, inertia=0.75, evidence_strength="strong"),
                "humility": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "moral_courage": TraitVector(value=0.7, inertia=0.65, evidence_strength="strong"),
                "grief": TraitVector(value=0.05, inertia=0.4, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip is the closest thing I have to a son",
                       confidence=0.95, inertia=0.7, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=8500, triggered_by="EVT_MRS_JOE_DIES",
                    traits={
                        "grief": TraitVector(value=0.75, inertia=0.40, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=20000, triggered_by="EVT_JOE_MARRIES_BIDDY",
                    beliefs_added=[
                        Belief(target_id="ENT_BIDDY", perceived_state="Biddy is my wife and partner",
                               confidence=1.0, inertia=0.7, established_at_fabula=20000, evidence_strength="strong"),
                    ]),
                
            ],
        ),
        "ENT_MRS_JOE": Entity(
            id="ENT_MRS_JOE", name="Mrs Joe Gargery (Pip's Sister)",
            location_id="LOC_FORGE", status="healthy",
            traits={
                "irascibility": TraitVector(value=0.9, inertia=0.7, evidence_strength="strong"),
                "harshness": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=5000, triggered_by="EVT_MRS_JOE_ATTACKED",
                    status="ill",
                    traits={
                        "irascibility": TraitVector(value=0.2, inertia=0.75, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=8500, triggered_by="EVT_MRS_JOE_DIES",
                    status="dead"),
            ],
        ),
        "ENT_HAVISHAM": Entity(
            id="ENT_HAVISHAM", name="Miss Havisham",
            location_id="LOC_SATIS_HOUSE", status="ill",
            traits={
                "bitterness": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "vengefulness": TraitVector(value=0.85, inertia=0.8, evidence_strength="strong"),
                "manipulativeness": TraitVector(value=0.85, inertia=0.75, evidence_strength="strong"),
                "remorse": TraitVector(value=0.05, inertia=0.3, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="WORLD_HAVISHAM_REVENGE",
                       perceived_state="Men deserve to be broken as I was broken",
                       confidence=0.95, inertia=0.85, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=15000, triggered_by="EVT_HAVISHAM_REPENTS",
                    traits={
                        "remorse": TraitVector(value=0.95, inertia=0.55, evidence_strength="strong"),
                        "vengefulness": TraitVector(value=0.2, inertia=0.85, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=15500, triggered_by="EVT_HAVISHAM_BURNS",
                    status="dead"),
            ],
        ),
        "ENT_ESTELLA": Entity(
            id="ENT_ESTELLA", name="Estella",
            location_id="LOC_SATIS_HOUSE", status="healthy",
            traits={
                "coldness": TraitVector(value=0.9, inertia=0.7, evidence_strength="strong"),
                "beauty": TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
                "pride": TraitVector(value=0.8, inertia=0.65, evidence_strength="strong"),
                "self_awareness": TraitVector(value=0.5, inertia=0.45, evidence_strength="moderate"),
                "sorrow": TraitVector(value=0.1, inertia=0.3, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="I have no heart to give Pip or anyone",
                       confidence=0.85, inertia=0.65, established_at_fabula=4000, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=15000, triggered_by="EVT_ESTELLA_MARRIES_DRUMMLE",
                    location_id="LOC_LONDON"),
                EntityStateSnapshot(fabula_time=20500, triggered_by="EVT_DRUMMLE_DIES",
                    traits={
                        "coldness": TraitVector(value=0.4, inertia=0.7, evidence_strength="strong"),
                        "sorrow": TraitVector(value=0.85, inertia=0.45, evidence_strength="strong"),
                        "self_awareness": TraitVector(value=0.85, inertia=0.55, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_MAGWITCH": Entity(
            id="ENT_MAGWITCH", name="Abel Magwitch",
            location_id="LOC_KENT_MARSHES", status="healthy",
            traits={
                "ferocity": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                "gratitude": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
                "cunning": TraitVector(value=0.75, inertia=0.6, evidence_strength="strong"),
                "tenderness": TraitVector(value=0.4, inertia=0.45, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_PIP",
                       perceived_state="Pip's kindness to me on the marshes shall be repaid a thousandfold",
                       confidence=0.95, inertia=0.7, established_at_fabula=1000, evidence_strength="strong"),
                Belief(target_id="ENT_COMPEYSON",
                       perceived_state="Compeyson is the gentleman who corrupted and betrayed me",
                       confidence=1.0, inertia=0.85, evidence_strength="strong"),
            ],
            constants=["transported_for_life"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=2000, triggered_by="EVT_CONVICTS_RECAPTURED",
                    location_id="LOC_LONDON"),
                EntityStateSnapshot(fabula_time=13000, triggered_by="EVT_MAGWITCH_REVEALS_HIMSELF",
                    location_id="LOC_BARNARDS_INN",
                    traits={
                        "tenderness": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=14000, triggered_by="EVT_PIP_PLANS_ESCAPE",
                    traits={
                        "tenderness": TraitVector(value=0.60, inertia=0.45, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=16500, triggered_by="EVT_MAGWITCH_CAPTURED",
                    location_id="LOC_NEWGATE", status="ill"),
                EntityStateSnapshot(fabula_time=17000, triggered_by="EVT_MAGWITCH_DIES",
                    status="dead"),
                
            ],
        ),
        "ENT_HERBERT": Entity(
            id="ENT_HERBERT", name="Herbert Pocket",
            location_id="LOC_SATIS_HOUSE", status="healthy",
            traits={
                "cheerfulness": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                "loyalty": TraitVector(value=0.9, inertia=0.7, evidence_strength="strong"),
                "candour": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
                "gratitude": TraitVector(value=0.3, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip is my closest friend",
                       confidence=0.9, inertia=0.65, established_at_fabula=7500, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=7500, triggered_by="EVT_PIP_MOVES_TO_LONDON",
                    location_id="LOC_BARNARDS_INN"),
                EntityStateSnapshot(fabula_time=10000, triggered_by="EVT_PIP_HELPS_HERBERT",
                    traits={
                        "gratitude": TraitVector(value=0.80, inertia=0.50, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=17500, triggered_by="EVT_HERBERT_LEAVES_FOR_CAIRO",
                    location_id="LOC_CAIRO"),
                
            ],
        ),
        "ENT_JAGGERS": Entity(
            id="ENT_JAGGERS", name="Mr Jaggers",
            location_id="LOC_JAGGERS_OFFICE", status="healthy",
            traits={
                "shrewdness": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "discretion": TraitVector(value=0.9, inertia=0.8, evidence_strength="strong"),
                "intimidation": TraitVector(value=0.85, inertia=0.75, evidence_strength="strong"),
            },
            beliefs=[],
            constants=["legal_authority"],
        ),
        "ENT_WEMMICK": Entity(
            id="ENT_WEMMICK", name="John Wemmick",
            location_id="LOC_JAGGERS_OFFICE", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.7, inertia=0.55, evidence_strength="moderate"),
                "kindness": TraitVector(value=0.75, inertia=0.55, evidence_strength="strong"),
                "secretiveness": TraitVector(value=0.7, inertia=0.6, evidence_strength="moderate"),
            },
            beliefs=[],
        ),
        "ENT_ORLICK": Entity(
            id="ENT_ORLICK", name="Dolge Orlick",
            location_id="LOC_FORGE", status="healthy",
            traits={
                "envy": TraitVector(value=0.9, inertia=0.75, evidence_strength="strong"),
                "violence": TraitVector(value=0.9, inertia=0.7, evidence_strength="strong"),
                "resentment": TraitVector(value=0.95, inertia=0.75, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip is a favoured upstart who deserves to die",
                       confidence=0.9, inertia=0.7, evidence_strength="strong"),
            ],
        ),
        "ENT_COMPEYSON": Entity(
            id="ENT_COMPEYSON", name="Compeyson",
            location_id="LOC_KENT_MARSHES", status="healthy",
            traits={
                "duplicity": TraitVector(value=0.95, inertia=0.8, evidence_strength="strong"),
                "vengefulness": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[],
            constants=["scarred_face"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=16500, triggered_by="EVT_MAGWITCH_CAPTURED",
                    status="dead"),
            ],
        ),
        "ENT_DRUMMLE": Entity(
            id="ENT_DRUMMLE", name="Bentley Drummle",
            location_id="LOC_LONDON", status="healthy",
            traits={
                "brutishness": TraitVector(value=0.9, inertia=0.75, evidence_strength="strong"),
                "entitlement": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=20500, triggered_by="EVT_DRUMMLE_DIES",
                    status="dead"),
            ],
        ),
        "ENT_BIDDY": Entity(
            id="ENT_BIDDY", name="Biddy",
            location_id="LOC_FORGE", status="healthy",
            traits={
                "kindness": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                "wisdom": TraitVector(value=0.7, inertia=0.55, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_PIP", perceived_state="Pip looks down on us now that he is a gentleman",
                       confidence=0.7, inertia=0.5, established_at_fabula=9000, evidence_strength="moderate"),
            ],
        ),
    },

    # ── EVENTS ──────────────────────────────────────────────────────────
    events=[
        EventNode(id="EVT_PIP_MEETS_CONVICT", fabula_time=1000, syuzhet_index=1,
                  event_type="outcome", actor_ids=["ENT_MAGWITCH"], target_ids=["ENT_PIP"],
                  description="At his parents' graves on the marshes, Pip is seized by an escaped convict and threatened into stealing food and a file."),
        EventNode(id="EVT_PIP_BRINGS_FOOD", fabula_time=1500, syuzhet_index=2,
                  event_type="choice", actor_ids=["ENT_PIP"], target_ids=["ENT_MAGWITCH"],
                  description="Pip steals a pie, brandy and Joe's file and brings them to the convict at dawn."),
        EventNode(id="EVT_CONVICTS_RECAPTURED", fabula_time=2000, syuzhet_index=3,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MAGWITCH", "ENT_COMPEYSON"],
                  description="Soldiers recapture Magwitch and Compeyson fighting in the marshes; Magwitch confesses to the theft to clear Pip."),
        EventNode(id="EVT_PIP_VISITS_SATIS", fabula_time=4000, syuzhet_index=4,
                  event_type="outcome", actor_ids=["ENT_PIP", "ENT_HAVISHAM", "ENT_ESTELLA"], target_ids=[],
                  description="Pip is summoned to Satis House to amuse Miss Havisham; he falls hopelessly in love with the cold Estella."),
        EventNode(id="EVT_HAVISHAM_PAYS_PREMIUM", fabula_time=4800, syuzhet_index=5,
                  event_type="choice", actor_ids=["ENT_HAVISHAM"], target_ids=["ENT_JOE"],
                  description="Miss Havisham pays Pip's premium so he can be apprenticed to Joe at the forge — sealing his sense that she is his patron."),
        EventNode(id="EVT_MRS_JOE_ATTACKED", fabula_time=5000, syuzhet_index=6,
                  event_type="outcome", actor_ids=["ENT_ORLICK"], target_ids=["ENT_MRS_JOE"],
                  description="While Pip and Joe are away, Orlick attacks Mrs Joe with the convict's old leg-iron, leaving her unable to speak."),
        EventNode(id="EVT_JAGGERS_REVEALS_FORTUNE", fabula_time=7000, syuzhet_index=7,
                  event_type="revelation", actor_ids=["ENT_JAGGERS"], target_ids=["ENT_PIP"],
                  description="The lawyer Jaggers tells Pip that an anonymous benefactor has settled a fortune on him; he is to become a gentleman in London."),
        EventNode(id="EVT_PIP_MOVES_TO_LONDON", fabula_time=7500, syuzhet_index=8,
                  event_type="choice", actor_ids=["ENT_PIP"], target_ids=[],
                  description="Pip moves into Barnard's Inn with Herbert Pocket and begins the life of a gentleman in training."),
        EventNode(id="EVT_JOE_VISITS_LONDON", fabula_time=9000, syuzhet_index=9,
                  event_type="outcome", actor_ids=["ENT_JOE"], target_ids=["ENT_PIP"],
                  description="Joe visits Pip at Barnard's Inn; Pip is ashamed to be seen with him."),
        EventNode(id="EVT_MRS_JOE_DIES", fabula_time=8500, syuzhet_index=10,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MRS_JOE"],
                  description="Mrs Joe dies of her injuries; Pip returns to the village for the funeral."),
        EventNode(id="EVT_PIP_HELPS_HERBERT", fabula_time=10000, syuzhet_index=11,
                  event_type="choice", actor_ids=["ENT_PIP", "ENT_WEMMICK"], target_ids=["ENT_HERBERT"],
                  description="With Wemmick's discreet help, Pip secretly buys Herbert a position at Clarriker's shipping firm."),
        EventNode(id="EVT_DRUMMLE_TOAST", fabula_time=12000, syuzhet_index=12,
                  event_type="choice", actor_ids=["ENT_DRUMMLE"], target_ids=["ENT_PIP"],
                  description="At the Finches club Drummle proposes a toast to Estella, mortifying Pip; Pip warns Estella but she is undeterred."),
        EventNode(id="EVT_MAGWITCH_REVEALS_HIMSELF", fabula_time=13000, syuzhet_index=13,
                  event_type="revelation", actor_ids=["ENT_MAGWITCH"], target_ids=["ENT_PIP"],
                  description="A storm-soaked old convict arrives at Barnard's Inn and reveals himself as Magwitch — the true source of Pip's fortune."),
        EventNode(id="EVT_PIP_PLANS_ESCAPE", fabula_time=14000, syuzhet_index=14,
                  event_type="choice", actor_ids=["ENT_PIP", "ENT_HERBERT"], target_ids=["ENT_MAGWITCH"],
                  description="Pip and Herbert plan to row Magwitch downriver to a Hamburg-bound steamer."),
        EventNode(id="EVT_ESTELLA_MARRIES_DRUMMLE", fabula_time=15000, syuzhet_index=15,
                  event_type="choice", actor_ids=["ENT_ESTELLA"], target_ids=["ENT_DRUMMLE"],
                  description="Pip declares his love at Satis House; Estella tells him she is to marry Drummle and dismisses him."),
        EventNode(id="EVT_HAVISHAM_REPENTS", fabula_time=15200, syuzhet_index=16,
                  event_type="revelation", actor_ids=["ENT_HAVISHAM"], target_ids=["ENT_PIP"],
                  description="Miss Havisham, broken by Pip's anguish, confesses she raised Estella to break men's hearts and begs his forgiveness."),
        EventNode(id="EVT_HAVISHAM_BURNS", fabula_time=15500, syuzhet_index=17,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_HAVISHAM"],
                  description="Miss Havisham's wedding dress catches fire at Satis House; Pip is burned trying to save her, and she dies of her injuries."),
        EventNode(id="EVT_ORLICK_LURES_PIP", fabula_time=16000, syuzhet_index=18,
                  event_type="outcome", actor_ids=["ENT_ORLICK"], target_ids=["ENT_PIP"],
                  description="Lured by an anonymous letter to a marsh sluice-house, Pip is seized by Orlick, who confesses to the attack on Mrs Joe and prepares to murder him."),
        EventNode(id="EVT_PIP_RESCUED", fabula_time=16200, syuzhet_index=19,
                  event_type="outcome", actor_ids=["ENT_HERBERT"], target_ids=["ENT_PIP"],
                  description="Herbert and Startop arrive in time to save Pip; Orlick flees."),
        EventNode(id="EVT_MAGWITCH_CAPTURED", fabula_time=16500, syuzhet_index=20,
                  event_type="outcome", actor_ids=["ENT_COMPEYSON"], target_ids=["ENT_MAGWITCH"],
                  description="On the river escape, a police boat with Compeyson aboard intercepts them; Magwitch and Compeyson grapple in the Thames; Compeyson drowns and Magwitch is captured."),
        EventNode(id="EVT_MAGWITCH_DIES", fabula_time=17000, syuzhet_index=21,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MAGWITCH"],
                  description="Pip nurses the dying Magwitch in Newgate, telling him his daughter Estella lives and is loved; Magwitch dies in peace."),
        EventNode(id="EVT_HERBERT_LEAVES_FOR_CAIRO", fabula_time=17500, syuzhet_index=22,
                  event_type="choice", actor_ids=["ENT_HERBERT"], target_ids=[],
                  description="Herbert leaves for Cairo to manage Clarriker's office, offering Pip a future place."),
        EventNode(id="EVT_JOE_NURSES_PIP", fabula_time=18000, syuzhet_index=23,
                  event_type="choice", actor_ids=["ENT_JOE"], target_ids=["ENT_PIP"],
                  description="With Magwitch's fortune forfeit to the Crown and Pip prostrate from fever, Joe travels to London, nurses Pip back to health, and quietly pays his debts."),
        EventNode(id="EVT_JOE_MARRIES_BIDDY", fabula_time=18500, syuzhet_index=24,
                  event_type="outcome", actor_ids=["ENT_JOE", "ENT_BIDDY"], target_ids=[],
                  description="Pip returns home to propose to Biddy and finds she has just married Joe."),
        EventNode(id="EVT_PIP_LEAVES_FOR_CAIRO", fabula_time=19000, syuzhet_index=25,
                  event_type="choice", actor_ids=["ENT_PIP"], target_ids=[],
                  description="Pip joins Herbert in Cairo and works in the firm for eleven years to repay his debts."),
        EventNode(id="EVT_DRUMMLE_DIES", fabula_time=20500, syuzhet_index=26,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_DRUMMLE"],
                  description="Drummle dies after years of mistreating Estella."),
        EventNode(id="EVT_PIP_MEETS_ESTELLA_AGAIN", fabula_time=21000, syuzhet_index=27,
                  event_type="outcome", actor_ids=["ENT_PIP", "ENT_ESTELLA"], target_ids=[],
                  description="Pip returns to England and meets the widowed, gentled Estella in the moonlit ruins of Satis House; he sees no shadow of another parting from her."),

        # ── UTTERANCES (discrete on-page speech-acts) ──────────────────
        EventNode(
            id="EVT_UTT_MAGWITCH_THREATENS_PIP",
            event_type="utterance", fabula_time=1000, syuzhet_index=28,
            speaker_id="ENT_MAGWITCH", addressee_ids=["ENT_PIP"],
            actor_ids=["ENT_MAGWITCH"], target_ids=["ENT_PIP"],
            description="In the churchyard the escaped convict seizes Pip and threatens to cut out his heart if he does not bring food and a file by morning.",
            content="Bring me, to-morrow morning early, that file and them wittles — or I'll have your heart and liver out.",
            via_channel_id=None, truth_value="performative",
        ),
        EventNode(
            id="EVT_UTT_JAGGERS_ANNOUNCES_FORTUNE",
            event_type="utterance", fabula_time=7000, syuzhet_index=29,
            speaker_id="ENT_JAGGERS", addressee_ids=["ENT_PIP"],
            actor_ids=["ENT_JAGGERS"], target_ids=["ENT_PIP", "EVT_JAGGERS_REVEALS_FORTUNE"],
            description="Jaggers informs Pip he has come into great expectations from an anonymous benefactor and is to be raised as a gentleman in London — explicitly forbidding Pip from inquiring after the patron.",
            content="You will please consider me your guardian. You are not to inquire who has made you a gentleman — the name is held back at the patron's pleasure.",
            via_channel_id="CHN_PIP_BENEFACTOR_PIPELINE", truth_value="true",
        ),
        EventNode(
            id="EVT_UTT_MAGWITCH_REVEALS_PATRONAGE",
            event_type="utterance", fabula_time=13000, syuzhet_index=30,
            speaker_id="ENT_MAGWITCH", addressee_ids=["ENT_PIP"],
            actor_ids=["ENT_MAGWITCH"], target_ids=["ENT_PIP", "EVT_JAGGERS_REVEALS_FORTUNE", "EVT_PIP_BRINGS_FOOD"],
            description="The returned convict tells Pip face-to-face that he, Magwitch, is the source of every shilling — collapsing the anonymous-benefactor channel.",
            content="Yes, Pip, dear boy, I've made a gentleman on you! It's me wot has done it.",
            via_channel_id=None, truth_value="true",
        ),
        EventNode(
            id="EVT_UTT_WEMMICK_WARNS_PIP",
            event_type="utterance", fabula_time=13800, syuzhet_index=31,
            speaker_id="ENT_WEMMICK", addressee_ids=["ENT_PIP"],
            actor_ids=["ENT_WEMMICK"], target_ids=["ENT_COMPEYSON", "ENT_MAGWITCH", "ENT_PIP"],
            description="At Walworth, off the Little Britain clock, Wemmick quietly tells Pip that Compeyson is in London hunting Magwitch and that the chambers are watched.",
            content="You are watched. Don't go home. Lie by at Herbert's — Compeyson is in London, and he knows.",
            via_channel_id=None, truth_value="true",
        ),
        EventNode(
            id="EVT_UTT_HAVISHAM_REPENTS_TO_PIP",
            event_type="utterance", fabula_time=15200, syuzhet_index=32,
            speaker_id="ENT_HAVISHAM", addressee_ids=["ENT_PIP"],
            actor_ids=["ENT_HAVISHAM"], target_ids=["ENT_ESTELLA", "ENT_PIP"],
            description="Broken by Pip's anguish, Miss Havisham confesses she raised Estella to break men's hearts and begs Pip's forgiveness.",
            content="What have I done! What have I done! Oh, take the pencil and write under my name, 'I forgive her.'",
            via_channel_id=None, truth_value="true",
        ),
        EventNode(
            id="EVT_UTT_ANONYMOUS_LURE_LETTER",
            event_type="utterance", fabula_time=15900, syuzhet_index=33,
            speaker_id="ENT_ORLICK", addressee_ids=["ENT_PIP"],
            actor_ids=["ENT_ORLICK"], target_ids=["ENT_PIP"],
            description="Orlick — hidden behind an unsigned note delivered to Pip's chambers — lures Pip alone to the marsh sluice-house on a fabricated pretext concerning Magwitch.",
            content="If you would hear something concerning your uncle Provis, come at once and alone to the lime-kiln by the sluice-house.",
            via_channel_id=None, truth_value="false",
        ),
        EventNode(
            id="EVT_UTT_ORLICK_CONFESSES_TO_PIP",
            event_type="utterance", fabula_time=16100, syuzhet_index=34,
            speaker_id="ENT_ORLICK", addressee_ids=["ENT_PIP"],
            actor_ids=["ENT_ORLICK"], target_ids=["EVT_MRS_JOE_ATTACKED", "ENT_MRS_JOE", "ENT_PIP"],
            description="Bound at the sluice-house and about to be murdered, Pip hears Orlick boast that it was he who struck down Mrs Joe — done at Pip on her, because of Pip.",
            content="It was you as did for your shrew sister — I tell you it was your doing — I done it; but I done it through you.",
            via_channel_id=None, truth_value="true",
        ),
        EventNode(
            id="EVT_UTT_PIP_TELLS_MAGWITCH_OF_ESTELLA",
            event_type="utterance", fabula_time=17000, syuzhet_index=35,
            speaker_id="ENT_PIP", addressee_ids=["ENT_MAGWITCH"],
            actor_ids=["ENT_PIP"], target_ids=["ENT_ESTELLA", "ENT_MAGWITCH"],
            description="At Magwitch's bedside in the prison hospital, Pip tells the dying convict that his lost daughter Estella is alive, a lady, and beloved.",
            content="You had a child once, whom you loved and lost... She lived, and found powerful friends. She is living now. She is a lady and very beautiful. And I love her!",
            via_channel_id=None, truth_value="true",
        ),
    ],

    # ── CAUSAL TOPOLOGY ────────────────────────────────────────────────
    causal_topology=[
        # ── chain_reaction ──
        CausalEdge(source_id="EVT_PIP_MEETS_CONVICT", target_id="EVT_PIP_BRINGS_FOOD",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000, propagation_delay=500),
        CausalEdge(source_id="EVT_PIP_BRINGS_FOOD", target_id="EVT_CONVICTS_RECAPTURED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1500, propagation_delay=500),
        CausalEdge(source_id="EVT_PIP_VISITS_SATIS", target_id="EVT_HAVISHAM_PAYS_PREMIUM",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=4000, propagation_delay=800),
        CausalEdge(source_id="EVT_HAVISHAM_PAYS_PREMIUM", target_id="EVT_MRS_JOE_ATTACKED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=4800, propagation_delay=200),
        CausalEdge(source_id="EVT_PIP_VISITS_SATIS", target_id="EVT_JAGGERS_REVEALS_FORTUNE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=4000, propagation_delay=3000),
        CausalEdge(source_id="EVT_PIP_BRINGS_FOOD", target_id="EVT_JAGGERS_REVEALS_FORTUNE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500, propagation_delay=5500),
        CausalEdge(source_id="EVT_JAGGERS_REVEALS_FORTUNE", target_id="EVT_PIP_MOVES_TO_LONDON",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=7000, propagation_delay=500),
        CausalEdge(source_id="EVT_PIP_MOVES_TO_LONDON", target_id="EVT_JOE_VISITS_LONDON",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=7500, propagation_delay=1500),
        CausalEdge(source_id="EVT_MRS_JOE_ATTACKED", target_id="EVT_MRS_JOE_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=5000, propagation_delay=3500),
        CausalEdge(source_id="EVT_PIP_MOVES_TO_LONDON", target_id="EVT_PIP_HELPS_HERBERT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7500, propagation_delay=2500),
        CausalEdge(source_id="EVT_PIP_MOVES_TO_LONDON", target_id="EVT_DRUMMLE_TOAST",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=7500, propagation_delay=4500),
        CausalEdge(source_id="EVT_DRUMMLE_TOAST", target_id="EVT_ESTELLA_MARRIES_DRUMMLE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=12000, propagation_delay=3000),
        CausalEdge(source_id="EVT_MAGWITCH_REVEALS_HIMSELF", target_id="EVT_PIP_PLANS_ESCAPE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=13000, propagation_delay=1000),
        CausalEdge(source_id="EVT_ESTELLA_MARRIES_DRUMMLE", target_id="EVT_HAVISHAM_REPENTS",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=15000, propagation_delay=200),
        CausalEdge(source_id="EVT_HAVISHAM_REPENTS", target_id="EVT_HAVISHAM_BURNS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=15200, propagation_delay=300),
        CausalEdge(source_id="EVT_PIP_PLANS_ESCAPE", target_id="EVT_MAGWITCH_CAPTURED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=14000, propagation_delay=2500),
        CausalEdge(source_id="EVT_ORLICK_LURES_PIP", target_id="EVT_PIP_RESCUED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=16000, propagation_delay=200),
        CausalEdge(source_id="EVT_MAGWITCH_CAPTURED", target_id="EVT_MAGWITCH_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=16500, propagation_delay=500),
        CausalEdge(source_id="EVT_MAGWITCH_DIES", target_id="EVT_JOE_NURSES_PIP",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=17000, propagation_delay=1000),
        CausalEdge(source_id="EVT_JOE_NURSES_PIP", target_id="EVT_JOE_MARRIES_BIDDY",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=18000, propagation_delay=500),
        CausalEdge(source_id="EVT_JOE_MARRIES_BIDDY", target_id="EVT_PIP_LEAVES_FOR_CAIRO",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=18500, propagation_delay=500),
        CausalEdge(source_id="EVT_HERBERT_LEAVES_FOR_CAIRO", target_id="EVT_PIP_LEAVES_FOR_CAIRO",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=17500, propagation_delay=1500),
        CausalEdge(source_id="EVT_DRUMMLE_DIES", target_id="EVT_PIP_MEETS_ESTELLA_AGAIN",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=20500, propagation_delay=500),

        # ── mutation ──
        CausalEdge(source_id="EVT_PIP_VISITS_SATIS", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=4000,
                   trait_target="shame", trait_delta=0.5),
        CausalEdge(source_id="EVT_PIP_VISITS_SATIS", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=4000,
                   trait_target="ambition", trait_delta=0.3),
        CausalEdge(source_id="EVT_JAGGERS_REVEALS_FORTUNE", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=7000,
                   trait_target="snobbery", trait_delta=0.6),
        CausalEdge(source_id="EVT_JAGGERS_REVEALS_FORTUNE", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=7000,
                   trait_target="ambition", trait_delta=0.45),
        CausalEdge(source_id="EVT_JOE_VISITS_LONDON", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=9000,
                   trait_target="shame", trait_delta=0.15),
        CausalEdge(source_id="EVT_MAGWITCH_REVEALS_HIMSELF", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=10.0, fabula_time=13000,
                   trait_target="snobbery", trait_delta=-0.3),
        CausalEdge(source_id="EVT_MAGWITCH_REVEALS_HIMSELF", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=13000,
                   trait_target="shame", trait_delta=0.25),
        CausalEdge(source_id="EVT_MRS_JOE_ATTACKED", target_id="ENT_MRS_JOE",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=5000,
                   trait_target="irascibility", trait_delta=-0.7),
        CausalEdge(source_id="EVT_HAVISHAM_REPENTS", target_id="ENT_HAVISHAM",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=15200,
                   trait_target="remorse", trait_delta=0.9),
        CausalEdge(source_id="EVT_HAVISHAM_REPENTS", target_id="ENT_HAVISHAM",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=15200,
                   trait_target="vengefulness", trait_delta=-0.6),
        CausalEdge(source_id="EVT_MAGWITCH_REVEALS_HIMSELF", target_id="ENT_MAGWITCH",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=13000,
                   trait_target="tenderness", trait_delta=0.45),
        CausalEdge(source_id="EVT_MAGWITCH_DIES", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=17000,
                   trait_target="compassion", trait_delta=0.35),
        CausalEdge(source_id="EVT_JOE_NURSES_PIP", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=18000,
                   trait_target="snobbery", trait_delta=-0.4),
        CausalEdge(source_id="EVT_DRUMMLE_DIES", target_id="ENT_ESTELLA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=20500,
                   trait_target="coldness", trait_delta=-0.5),
        CausalEdge(source_id="EVT_DRUMMLE_DIES", target_id="ENT_ESTELLA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=20500,
                   trait_target="self_awareness", trait_delta=0.4),

        # ── mutation_social ──
        CausalEdge(source_id="EVT_PIP_BRINGS_FOOD", target_id="ENT_MAGWITCH",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1500,
                   trait_target="affinity", trait_delta=0.95, rel_counterpart_id="ENT_PIP"),
        CausalEdge(source_id="EVT_PIP_VISITS_SATIS", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=4000,
                   trait_target="affinity", trait_delta=0.9, rel_counterpart_id="ENT_ESTELLA"),
        CausalEdge(source_id="EVT_JOE_VISITS_LONDON", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=9000,
                   trait_target="affinity", trait_delta=-0.3, rel_counterpart_id="ENT_JOE"),
        CausalEdge(source_id="EVT_ESTELLA_MARRIES_DRUMMLE", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=15000,
                   trait_target="affinity", trait_delta=-0.3, rel_counterpart_id="ENT_ESTELLA"),
        CausalEdge(source_id="EVT_MAGWITCH_REVEALS_HIMSELF", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=13000,
                   trait_target="affinity", trait_delta=0.6, rel_counterpart_id="ENT_MAGWITCH"),
        CausalEdge(source_id="EVT_JOE_NURSES_PIP", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=18000,
                   trait_target="affinity", trait_delta=0.8, rel_counterpart_id="ENT_JOE"),
        CausalEdge(source_id="EVT_HAVISHAM_REPENTS", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=15200,
                   trait_target="affinity", trait_delta=0.4, rel_counterpart_id="ENT_HAVISHAM"),
        CausalEdge(source_id="EVT_PIP_MEETS_ESTELLA_AGAIN", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=21000,
                   trait_target="affinity", trait_delta=0.6, rel_counterpart_id="ENT_ESTELLA"),

        # ── mutation / mutation_social — coverage for remaining significant events ──
        # EVT_PIP_MEETS_CONVICT — terror on the marshes seeds Pip's lifelong fear and pity for Magwitch.
        CausalEdge(source_id="EVT_PIP_MEETS_CONVICT", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000,
                   trait_target="fear", trait_delta=0.6),
        CausalEdge(source_id="EVT_PIP_MEETS_CONVICT", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1000,
                   trait_target="compassion", trait_delta=0.05),
        # EVT_CONVICTS_RECAPTURED — Magwitch's confession to clear Pip plants long-term guilt in the boy.
        CausalEdge(source_id="EVT_CONVICTS_RECAPTURED", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=2000,
                   trait_target="guilt", trait_delta=0.2),
        # EVT_HAVISHAM_PAYS_PREMIUM — buying Pip's apprenticeship cements his (mistaken) gratitude to her.
        CausalEdge(source_id="EVT_HAVISHAM_PAYS_PREMIUM", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=4800,
                   trait_target="gratitude_to_havisham", trait_delta=0.7),
        CausalEdge(source_id="EVT_HAVISHAM_PAYS_PREMIUM", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=4800,
                   trait_target="affinity", trait_delta=0.4, rel_counterpart_id="ENT_HAVISHAM"),
        # EVT_MRS_JOE_DIES — Pip's secret guilt over the leg-iron, and Joe's mute grief.
        CausalEdge(source_id="EVT_MRS_JOE_DIES", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=8500,
                   trait_target="guilt", trait_delta=0.25),
        CausalEdge(source_id="EVT_MRS_JOE_DIES", target_id="ENT_JOE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=8500,
                   trait_target="grief", trait_delta=0.7),
        # EVT_PIP_HELPS_HERBERT — secret patronage produces Herbert's gratitude and deepens the friendship.
        CausalEdge(source_id="EVT_PIP_HELPS_HERBERT", target_id="ENT_HERBERT",
                   causality_type="mutation", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=10000,
                   trait_target="gratitude", trait_delta=0.5),
        CausalEdge(source_id="EVT_PIP_HELPS_HERBERT", target_id="ENT_HERBERT",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=10000,
                   trait_target="affinity", trait_delta=0.2, rel_counterpart_id="ENT_PIP"),
        # EVT_DRUMMLE_TOAST — public claim on Estella inflames Pip's shame and spikes hostility to Drummle.
        CausalEdge(source_id="EVT_DRUMMLE_TOAST", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=12000,
                   trait_target="shame", trait_delta=0.15),
        CausalEdge(source_id="EVT_DRUMMLE_TOAST", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=12000,
                   trait_target="affinity", trait_delta=-0.6, rel_counterpart_id="ENT_DRUMMLE"),
        # EVT_PIP_PLANS_ESCAPE — committing to Magwitch's escape softens Magwitch and binds Pip in loyalty.
        CausalEdge(source_id="EVT_PIP_PLANS_ESCAPE", target_id="ENT_MAGWITCH",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=14000,
                   trait_target="tenderness", trait_delta=0.2),
        CausalEdge(source_id="EVT_PIP_PLANS_ESCAPE", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=14000,
                   trait_target="affinity", trait_delta=0.2, rel_counterpart_id="ENT_MAGWITCH"),
        # EVT_HAVISHAM_BURNS — the burning extinguishes the bitterness she lived in.
        CausalEdge(source_id="EVT_HAVISHAM_BURNS", target_id="ENT_HAVISHAM",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=15500,
                   trait_target="bitterness", trait_delta=-0.95),
        # EVT_ORLICK_LURES_PIP — staring down a confessed murderer collapses Pip's remaining naivety.
        CausalEdge(source_id="EVT_ORLICK_LURES_PIP", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=16000,
                   trait_target="naivety", trait_delta=-0.4),
        CausalEdge(source_id="EVT_ORLICK_LURES_PIP", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=16000,
                   trait_target="fear", trait_delta=0.6, rel_counterpart_id="ENT_ORLICK"),
        # EVT_PIP_RESCUED — Herbert and Startop's arrival cements Pip's gratitude and bond.
        CausalEdge(source_id="EVT_PIP_RESCUED", target_id="ENT_PIP",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=5.0, fabula_time=16200,
                   trait_target="compassion", trait_delta=0.1),
        CausalEdge(source_id="EVT_PIP_RESCUED", target_id="ENT_PIP",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=16200,
                   trait_target="affinity", trait_delta=0.3, rel_counterpart_id="ENT_HERBERT"),
        # EVT_MAGWITCH_CAPTURED — wounded and doomed, Magwitch turns wholly tender toward Pip.
        CausalEdge(source_id="EVT_MAGWITCH_CAPTURED", target_id="ENT_MAGWITCH",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=16500,
                   trait_target="ferocity", trait_delta=-0.6),
        CausalEdge(source_id="EVT_MAGWITCH_CAPTURED", target_id="ENT_MAGWITCH",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=16500,
                   trait_target="tenderness", trait_delta=0.15),

        # ── affordance_gate ──
        CausalEdge(source_id="OBJ_FILE_AND_PIE", target_id="EVT_PIP_BRINGS_FOOD",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1500),
        CausalEdge(source_id="OBJ_LEG_IRON", target_id="EVT_MRS_JOE_ATTACKED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=5000),
        CausalEdge(source_id="OBJ_BANKNOTES", target_id="EVT_PIP_MOVES_TO_LONDON",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=7500),
        CausalEdge(source_id="OBJ_ANONYMOUS_LETTER", target_id="EVT_ORLICK_LURES_PIP",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="strong",
                   causal_force=8.0, fabula_time=16000),
        CausalEdge(source_id="OBJ_WEDDING_DRESS", target_id="EVT_HAVISHAM_BURNS",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=15500),
        CausalEdge(source_id="ENT_JAGGERS", target_id="EVT_JAGGERS_REVEALS_FORTUNE",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="strong",
                   causal_force=7.0, fabula_time=7000),

        # ── ambient_propagation ──
        CausalEdge(source_id="LOC_SATIS_HOUSE", target_id="ENT_ESTELLA",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=4000),
        CausalEdge(source_id="LOC_SATIS_HOUSE", target_id="ENT_PIP",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=4000),
        CausalEdge(source_id="LOC_LONDON", target_id="ENT_PIP",
                   causality_type="ambient_propagation", mechanism="social", evidence_strength="weak",
                   causal_force=3.0, fabula_time=7500),

        # ── WORLD_ → Event ──
        CausalEdge(source_id="WORLD_VICTORIAN_CLASS", target_id="EVT_PIP_VISITS_SATIS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=4000),
        CausalEdge(source_id="WORLD_VICTORIAN_CLASS", target_id="EVT_JAGGERS_REVEALS_FORTUNE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=7000),
        CausalEdge(source_id="WORLD_VICTORIAN_CLASS", target_id="EVT_JOE_VISITS_LONDON",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=9000),
        CausalEdge(source_id="WORLD_VICTORIAN_CLASS", target_id="EVT_MAGWITCH_REVEALS_HIMSELF",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=13000),
        CausalEdge(source_id="WORLD_VICTORIAN_CLASS", target_id="EVT_ESTELLA_MARRIES_DRUMMLE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=15000),
        CausalEdge(source_id="WORLD_HAVISHAM_REVENGE", target_id="EVT_PIP_VISITS_SATIS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=4000),
        CausalEdge(source_id="WORLD_HAVISHAM_REVENGE", target_id="EVT_HAVISHAM_PAYS_PREMIUM",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=5.0, fabula_time=4800),
        CausalEdge(source_id="WORLD_HAVISHAM_REVENGE", target_id="EVT_ESTELLA_MARRIES_DRUMMLE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=5.0, fabula_time=15000),
        CausalEdge(source_id="WORLD_LAW_AND_TRANSPORTATION", target_id="EVT_CONVICTS_RECAPTURED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=2000),
        CausalEdge(source_id="WORLD_LAW_AND_TRANSPORTATION", target_id="EVT_MAGWITCH_REVEALS_HIMSELF",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=13000),
        CausalEdge(source_id="WORLD_LAW_AND_TRANSPORTATION", target_id="EVT_MAGWITCH_CAPTURED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=16500),
        CausalEdge(source_id="WORLD_LAW_AND_TRANSPORTATION", target_id="EVT_MAGWITCH_DIES",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=17000),

        # ── orphan utterance wirings ──
        CausalEdge(source_id="EVT_PIP_MEETS_CONVICT", target_id="EVT_UTT_MAGWITCH_THREATENS_PIP",
                   causality_type="chain_reaction", mechanism="performative", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000, propagation_delay=0),
        CausalEdge(source_id="EVT_JAGGERS_REVEALS_FORTUNE", target_id="EVT_UTT_JAGGERS_ANNOUNCES_FORTUNE",
                   causality_type="chain_reaction", mechanism="performative", evidence_strength="strong",
                   causal_force=8.0, fabula_time=7000, propagation_delay=0),
        CausalEdge(source_id="EVT_MAGWITCH_REVEALS_HIMSELF", target_id="EVT_UTT_MAGWITCH_REVEALS_PATRONAGE",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=10.0, fabula_time=13000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_WEMMICK_WARNS_PIP", target_id="EVT_PIP_PLANS_ESCAPE",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=7.0, fabula_time=13800, propagation_delay=200),
        CausalEdge(source_id="EVT_HAVISHAM_REPENTS", target_id="EVT_UTT_HAVISHAM_REPENTS_TO_PIP",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=15200, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_ANONYMOUS_LURE_LETTER", target_id="EVT_ORLICK_LURES_PIP",
                   causality_type="chain_reaction", mechanism="performative", evidence_strength="strong",
                   causal_force=8.0, fabula_time=15900, propagation_delay=100),
        CausalEdge(source_id="EVT_ORLICK_LURES_PIP", target_id="EVT_UTT_ORLICK_CONFESSES_TO_PIP",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=16000, propagation_delay=100),
        CausalEdge(source_id="EVT_MAGWITCH_DIES", target_id="EVT_UTT_PIP_TELLS_MAGWITCH_OF_ESTELLA",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=4.0, fabula_time=17000, propagation_delay=0),
    ],

    # ── SPATIAL TOPOLOGY ────────────────────────────────────────────────
    spatial_topology=[
        SpatialEdge(source_id="LOC_KENT_MARSHES", target_id="LOC_FORGE"),
        SpatialEdge(source_id="LOC_FORGE", target_id="LOC_SATIS_HOUSE"),
        SpatialEdge(source_id="LOC_KENT_MARSHES", target_id="LOC_SLUICE_HOUSE"),
        SpatialEdge(source_id="LOC_FORGE", target_id="LOC_LONDON"),
        SpatialEdge(source_id="LOC_LONDON", target_id="LOC_BARNARDS_INN"),
        SpatialEdge(source_id="LOC_LONDON", target_id="LOC_JAGGERS_OFFICE"),
        SpatialEdge(source_id="LOC_LONDON", target_id="LOC_THAMES"),
        SpatialEdge(source_id="LOC_LONDON", target_id="LOC_NEWGATE"),
        SpatialEdge(source_id="LOC_LONDON", target_id="LOC_SATIS_HOUSE"),
        SpatialEdge(source_id="LOC_LONDON", target_id="LOC_CAIRO"),
    ],

    # ── INFORMATION TOPOLOGY ────────────────────────────────────────────
    channels={
        # The standing anonymous-benefactor pipeline: Magwitch funds Pip
        # via Jaggers as cut-out, with strict instructions to conceal the
        # patron's identity. Pip's intelligibility of the *source* is near
        # zero (he believes Miss Havisham); the channel collapses the
        # moment Magwitch reveals himself in person.
        "CHN_PIP_BENEFACTOR_PIPELINE": Channel(
            id="CHN_PIP_BENEFACTOR_PIPELINE",
            name="Anonymous benefactor pipeline (Magwitch → Jaggers → Pip)",
            medium="anonymous_pipeline",
            participant_ids=["ENT_MAGWITCH", "ENT_JAGGERS", "ENT_PIP"],
            directionality="simplex",
            intelligibility={"ENT_PIP": 0.1},
            established_at_fabula=7000,
            terminated_at_fabula=13000,
            evidence_strength="strong",
        ),
    },

    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_VICTORIAN_CLASS": GlobalTrait(
            id="WORLD_VICTORIAN_CLASS",
            name="Victorian Class Hierarchy",
            description="The rigid Regency-into-Victorian social order in which 'gentleman' is a coveted status conferred by money, education and accent — not work. Drives Pip's snobbery toward Joe, his shame at Magwitch's rough origins, and Estella's disdain.",
            category="social_structure",
            magnitude=TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=13000, triggered_by="EVT_MAGWITCH_REVEALS_HIMSELF",
                    magnitude=TraitVector(value=0.6, inertia=0.7, evidence_strength="strong"),
                    description="The revelation that Pip's gentility was funded by a transported convict undermines the supposed purity of the gentleman class for Pip personally."),
                WorldTraitSnapshot(fabula_time=18000, triggered_by="EVT_JOE_NURSES_PIP",
                    magnitude=TraitVector(value=0.4, inertia=0.6, evidence_strength="strong"),
                    description="Joe's quiet, total kindness in nursing the bankrupted Pip dissolves the class distinction in Pip's heart even though it persists in the wider world."),
            ],
        ),
        "WORLD_HAVISHAM_REVENGE": GlobalTrait(
            id="WORLD_HAVISHAM_REVENGE",
            name="Havisham's Revenge Against Men",
            description="The named-latent psychological project of raising Estella to break men's hearts — a private cosmology of vengeance that radiates from Satis House and shapes every character drawn into it.",
            category="social_structure",
            magnitude=TraitVector(value=0.8, inertia=0.75, evidence_strength="strong"),
            affected_domains=["psychological", "emotional", "social"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=15200, triggered_by="EVT_HAVISHAM_REPENTS",
                    magnitude=TraitVector(value=0.2, inertia=0.55, evidence_strength="strong"),
                    description="Havisham's repentance collapses the scheme; only its aftereffects on Estella remain."),
            ],
        ),
        "WORLD_LAW_AND_TRANSPORTATION": GlobalTrait(
            id="WORLD_LAW_AND_TRANSPORTATION",
            name="Penal Law and Transportation",
            description="The Regency-era legal apparatus that hangs forgers, transports thieves to New South Wales for life, and condemns returnees on sight. Operates as common-cause parent over Magwitch's history and ultimate fate.",
            category="governance",
            magnitude=TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
            affected_domains=["social"],
        ),
    },

    # ── SOCIAL TOPOLOGY ────────────────────────────────────────────────
    social_topology=[
        # Pip ↔ Joe — the moral spine of the novel.
        RelationshipEdge(
            source_entity_id="ENT_PIP", target_entity_id="ENT_JOE",
            metrics={
                "affinity": RelationshipMetric(value=0.9, inertia=0.55, evidence_strength="strong", last_updated_fabula=18000),
                "power_dynamic": RelationshipMetric(value=-0.3, inertia=0.6, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_JOE", target_entity_id="ENT_PIP",
            metrics={
                "affinity": RelationshipMetric(value=1.0, inertia=0.65, evidence_strength="strong", last_updated_fabula=18000),
                "power_dynamic": RelationshipMetric(value=0.3, inertia=0.6, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        # Pip ↔ Estella — devotion, contempt, late thaw.
        RelationshipEdge(
            source_entity_id="ENT_PIP", target_entity_id="ENT_ESTELLA",
            metrics={
                "affinity": RelationshipMetric(value=0.95, inertia=0.55, evidence_strength="strong", last_updated_fabula=21000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_ESTELLA", target_entity_id="ENT_PIP",
            metrics={
                "affinity": RelationshipMetric(value=0.4, inertia=0.45, evidence_strength="strong", last_updated_fabula=21000),
                "power_dynamic": RelationshipMetric(value=0.4, inertia=0.65, evidence_strength="strong", last_updated_fabula=4000),
            },
        ),
        # Pip ↔ Magwitch — terror to filial love.
        RelationshipEdge(
            source_entity_id="ENT_PIP", target_entity_id="ENT_MAGWITCH",
            metrics={
                "affinity": RelationshipMetric(value=0.7, inertia=0.5, evidence_strength="strong", last_updated_fabula=17000),
                "fear":     RelationshipMetric(value=0.3, inertia=0.2, evidence_strength="moderate", last_updated_fabula=1000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_MAGWITCH", target_entity_id="ENT_PIP",
            metrics={
                "affinity":      RelationshipMetric(value=1.0, inertia=0.6, evidence_strength="strong", last_updated_fabula=13000),
                "power_dynamic": RelationshipMetric(value=-0.2, inertia=0.65, evidence_strength="moderate", last_updated_fabula=13000),
            },
        ),
        # Havisham ↔ Estella — possessive maker / unwilling instrument.
        RelationshipEdge(
            source_entity_id="ENT_HAVISHAM", target_entity_id="ENT_ESTELLA",
            metrics={
                "affinity":      RelationshipMetric(value=0.5, inertia=0.5, evidence_strength="strong", last_updated_fabula=15000),
                "power_dynamic": RelationshipMetric(value=0.7, inertia=0.75, evidence_strength="strong", last_updated_fabula=4000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_ESTELLA", target_entity_id="ENT_HAVISHAM",
            metrics={
                "affinity":      RelationshipMetric(value=0.0, inertia=0.45, evidence_strength="moderate", last_updated_fabula=15000),
                "power_dynamic": RelationshipMetric(value=-0.7, inertia=0.75, evidence_strength="strong", last_updated_fabula=4000),
            },
        ),
        # Havisham → Pip — instrumental, then repentant.
        RelationshipEdge(
            source_entity_id="ENT_HAVISHAM", target_entity_id="ENT_PIP",
            metrics={
                "affinity":      RelationshipMetric(value=0.4, inertia=0.45, evidence_strength="strong", last_updated_fabula=15200),
                "power_dynamic": RelationshipMetric(value=0.7, inertia=0.7, evidence_strength="strong", last_updated_fabula=4000),
            },
        ),
        # Pip ↔ Herbert — easy friendship.
        RelationshipEdge(
            source_entity_id="ENT_PIP", target_entity_id="ENT_HERBERT",
            metrics={
                "affinity": RelationshipMetric(value=0.9, inertia=0.55, evidence_strength="strong", last_updated_fabula=7500),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_HERBERT", target_entity_id="ENT_PIP",
            metrics={
                "affinity": RelationshipMetric(value=0.9, inertia=0.55, evidence_strength="strong", last_updated_fabula=7500),
            },
        ),
        # Orlick → Pip — class envy and murderous resentment.
        RelationshipEdge(
            source_entity_id="ENT_ORLICK", target_entity_id="ENT_PIP",
            metrics={
                "affinity": RelationshipMetric(value=-1.0, inertia=0.55, evidence_strength="strong", last_updated_fabula=16000),
                "fear":     RelationshipMetric(value=0.0, inertia=0.15, evidence_strength="weak", observed=False),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_PIP", target_entity_id="ENT_ORLICK",
            metrics={
                "affinity": RelationshipMetric(value=-0.5, inertia=0.5, evidence_strength="moderate", last_updated_fabula=16000),
                "fear":     RelationshipMetric(value=0.7, inertia=0.25, evidence_strength="strong", last_updated_fabula=16000),
            },
        ),
        # Magwitch ↔ Compeyson — defining mutual hatred.
        RelationshipEdge(
            source_entity_id="ENT_MAGWITCH", target_entity_id="ENT_COMPEYSON",
            metrics={
                "affinity": RelationshipMetric(value=-1.0, inertia=0.7, evidence_strength="strong", last_updated_fabula=2000),
            },
        ),
        # Jaggers → Pip — paid intermediary.
        RelationshipEdge(
            source_entity_id="ENT_JAGGERS", target_entity_id="ENT_PIP",
            metrics={
                "power_dynamic": RelationshipMetric(value=0.7, inertia=0.75, evidence_strength="strong", last_updated_fabula=7000),
            },
        ),
        # Estella ↔ Drummle — entrapment.
        RelationshipEdge(
            source_entity_id="ENT_ESTELLA", target_entity_id="ENT_DRUMMLE",
            metrics={
                "affinity":      RelationshipMetric(value=-0.6, inertia=0.5, evidence_strength="strong", last_updated_fabula=15000),
                "fear":          RelationshipMetric(value=0.6, inertia=0.25, evidence_strength="strong", last_updated_fabula=20500),
                "power_dynamic": RelationshipMetric(value=-0.6, inertia=0.7, evidence_strength="strong", last_updated_fabula=15000),
            },
        ),
        # Joe ↔ Biddy — late marriage.
        RelationshipEdge(
            source_entity_id="ENT_JOE", target_entity_id="ENT_BIDDY",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.6, evidence_strength="strong", last_updated_fabula=18500),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_BIDDY", target_entity_id="ENT_JOE",
            metrics={
                "affinity": RelationshipMetric(value=0.9, inertia=0.6, evidence_strength="strong", last_updated_fabula=18500),
            },
        ),
    ],
)
