"""Macbeth — high-fidelity WorldStateV1 test fixture.

Authored against the current ingestion prompts (ontology_locations,
ontology_objects, ontology_entities, ontology_world_traits,
physics_extraction, social_extraction, consequences_extraction,
world_trait_timeline). Demonstrates:

* All five CausalEdge modalities (chain_reaction, mutation,
  mutation_social, affordance_gate, ambient_propagation).
* Per-axis ``RelationshipMetric`` (only observed axes populated, with
  per-axis inertia bands: fear ~0.1–0.3, affinity ~0.3–0.6,
  power_dynamic ~0.5–0.8).
* Explicit ``evidence_strength`` everywhere it is supported
  (TraitVector, AmbientVector, Belief, CausalEdge,
  RelationshipMetric, GlobalTrait magnitude).
* ``state_timeline`` snapshots whose inertia *bumps up* (not down) when
  a trait is shocked away from baseline.
* WORLD_ named-latent traits wired as common-cause parents to the
  events they jointly drive.
* Initial entity locations match each character's first appearance
  (not their final stronghold).
"""
from shadow_loom.models import (
    Channel,
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, RelationshipMetric, TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    # ── LOCATIONS ──────────────────────────────────────────────────────
    locations={
        "LOC_BATTLEFIELD": Location(
            name="Battlefield near Forres",
            description="Blood-soaked field where Macbeth and Banquo crush the Cawdor rebellion.",
            ambient_state={
                "danger": AmbientVector(value=0.9, volatility=0.4, evidence_strength="strong"),
                "tension": AmbientVector(value=0.8, volatility=0.3, evidence_strength="strong"),
            },
        ),
        "LOC_HEATH": Location(
            name="The Heath",
            description="Desolate fog-shrouded moor where Macbeth and Banquo first meet the witches.",
            ambient_state={
                "supernatural": AmbientVector(value=0.9, volatility=0.2, evidence_strength="strong"),
                "concealment": AmbientVector(value=0.7, volatility=0.3, evidence_strength="moderate"),
            },
        ),
        "LOC_FORRES_COURT": Location(
            name="Duncan's Court at Forres",
            description="Royal hall where Duncan praises his generals and names Malcolm his heir.",
            ambient_state={
                "formality": AmbientVector(value=0.8, volatility=0.2, evidence_strength="moderate"),
                "tension": AmbientVector(value=0.4, volatility=0.4, evidence_strength="weak"),
            },
        ),
        "LOC_INVERNESS_CASTLE": Location(
            name="Inverness Castle",
            description="Macbeth's ancestral keep; Duncan is murdered here in his sleep.",
            ambient_state={
                "tension": AmbientVector(value=0.7, volatility=0.5, evidence_strength="strong"),
                "concealment": AmbientVector(value=0.6, volatility=0.4, evidence_strength="moderate"),
            },
        ),
        "LOC_DUNSINANE_CASTLE": Location(
            name="Dunsinane Castle",
            description="Royal seat of the crowned Macbeth; site of his banquet, raving, and final stand.",
            ambient_state={
                "danger": AmbientVector(value=0.8, volatility=0.3, evidence_strength="strong"),
                "tension": AmbientVector(value=0.9, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_WITCHES_CAVERN": Location(
            name="Witches' Cavern",
            description="Subterranean lair where Macbeth returns for the apparitions and second prophecies.",
            ambient_state={
                "supernatural": AmbientVector(value=0.95, volatility=0.1, evidence_strength="strong"),
            },
        ),
        "LOC_MACDUFF_CASTLE": Location(
            name="Macduff's Castle at Fife",
            description="Macduff's family seat; site of the slaughter of his wife and children.",
            ambient_state={
                "safety": AmbientVector(value=0.6, volatility=0.7, evidence_strength="moderate"),
            },
        ),
        "LOC_ENGLAND": Location(
            name="English Court",
            description="Refuge of Malcolm and Macduff at King Edward's court; staging ground for the counter-invasion.",
            ambient_state={
                "safety": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_BIRNAM_WOOD": Location(
            name="Birnam Wood",
            description="Forest west of Dunsinane; Malcolm's army camouflages itself with cut boughs from here.",
            ambient_state={
                "concealment": AmbientVector(value=0.8, volatility=0.3, evidence_strength="strong"),
            },
        ),
    },

    # ── OBJECTS ─────────────────────────────────────────────────────────
    objects={
        "OBJ_BLOODY_DAGGERS": NarrativeObject(
            id="OBJ_BLOODY_DAGGERS", name="Bloody Daggers",
            location_id=None, owner_id="ENT_MACBETH",
            properties={"state": "blood-smeared", "stained_with": "duncan_blood"},
            affordances=[
                Affordance(action="kill", target_type="Entity"),
                Affordance(action="frame", target_type="Entity"),
            ],
        ),
        "OBJ_CROWN": NarrativeObject(
            id="OBJ_CROWN", name="Crown of Scotland",
            location_id="LOC_FORRES_COURT", owner_id="ENT_DUNCAN",
            properties={"state": "contested"},
            affordances=[Affordance(action="legitimize", target_type="Entity")],
        ),
        "OBJ_LETTER": NarrativeObject(
            id="OBJ_LETTER", name="Macbeth's Letter to Lady Macbeth",
            location_id="LOC_INVERNESS_CASTLE", owner_id="ENT_LADY_MACBETH",
            properties={"content": "witches_prophecy", "state": "delivered"},
            affordances=[Affordance(action="inform", target_type="Entity")],
        ),
        "OBJ_CAULDRON": NarrativeObject(
            id="OBJ_CAULDRON", name="Witches' Cauldron",
            location_id="LOC_WITCHES_CAVERN", owner_id=None,
            properties={"state": "bubbling"},
            affordances=[Affordance(action="prophesy", target_type="Entity")],
        ),
        "OBJ_APPARITIONS": NarrativeObject(
            id="OBJ_APPARITIONS", name="The Three Apparitions",
            location_id="LOC_WITCHES_CAVERN", owner_id=None,
            properties={"content": "armed_head_bloody_child_crowned_child"},
            affordances=[Affordance(action="prophesy", target_type="Entity"), Affordance(action="deceive", target_type="Entity")],
        ),
        "OBJ_BIRNAM_BOUGHS": NarrativeObject(
            id="OBJ_BIRNAM_BOUGHS", name="Birnam Wood Boughs",
            location_id="LOC_BIRNAM_WOOD", owner_id=None,
            properties={"state": "cut", "purpose": "camouflage"},
            affordances=[Affordance(action="conceal", target_type="Entity")],
        ),
    },

    # ── ENTITIES ────────────────────────────────────────────────────────
    # Initial location = where the entity FIRST appears (per ontology_entities rules).
    entities={
        "ENT_MACBETH": Entity(
            id="ENT_MACBETH", name="Macbeth (Thane of Glamis)",
            location_id="LOC_BATTLEFIELD", status="healthy",
            traits={
                "ambition": TraitVector(value=0.7, inertia=0.55, evidence_strength="strong"),
                "courage": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "loyalty": TraitVector(value=0.7, inertia=0.5, evidence_strength="moderate"),
                "guilt": TraitVector(value=0.1, inertia=0.25, evidence_strength="weak"),
                "paranoia": TraitVector(value=0.2, inertia=0.3, evidence_strength="weak"),
                "ruthlessness": TraitVector(value=0.4, inertia=0.45, evidence_strength="moderate"),
                "despair": TraitVector(value=0.1, inertia=0.25, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_DUNCAN", perceived_state="Duncan is my kinsman and rightful king",
                       confidence=0.9, inertia=0.55, evidence_strength="strong"),
                Belief(target_id="ENT_BANQUO", perceived_state="Banquo is my trusted comrade-in-arms",
                       confidence=0.85, inertia=0.5, evidence_strength="strong"),
                Belief(target_id="ENT_WITCHES", perceived_state="The witches' prophecies may yet prove true",
                       confidence=0.4, inertia=0.35, evidence_strength="moderate"),
            ],
            constants=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=2000, triggered_by="EVT_WITCHES_PROPHECY_1",
                    traits={
                        "ambition": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=6000, triggered_by="EVT_DUNCAN_MURDER",
                    traits={
                        "guilt": TraitVector(value=0.7, inertia=0.4, evidence_strength="strong"),
                        "paranoia": TraitVector(value=0.55, inertia=0.4, evidence_strength="strong"),
                        "ruthlessness": TraitVector(value=0.65, inertia=0.55, evidence_strength="strong"),
                    },
                    location_id="LOC_INVERNESS_CASTLE"),
                EntityStateSnapshot(fabula_time=10000, triggered_by="EVT_MACBETH_CROWNED",
                    traits={
                        "paranoia": TraitVector(value=0.7, inertia=0.45, evidence_strength="strong"),
                    },
                    location_id="LOC_DUNSINANE_CASTLE"),
                EntityStateSnapshot(fabula_time=11000, triggered_by="EVT_BANQUO_MURDERED",
                    traits={
                        "guilt": TraitVector(value=0.85, inertia=0.5, evidence_strength="strong"),
                        "paranoia": TraitVector(value=0.85, inertia=0.5, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=13000, triggered_by="EVT_WITCHES_PROPHECY_2",
                    traits={
                        "courage": TraitVector(value=0.95, inertia=0.75, evidence_strength="strong"),
                        "paranoia": TraitVector(value=0.55, inertia=0.45, evidence_strength="moderate"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_MACDUFF", perceived_state="Macduff threatens me but no man of woman born can harm me",
                               confidence=0.85, inertia=0.6, established_at_fabula=13000, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=17000, triggered_by="EVT_LADY_MACBETH_DEATH",
                    traits={
                        "despair": TraitVector(value=0.9, inertia=0.5, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=18500, triggered_by="EVT_BIRNAM_WOOD_MOVES",
                    traits={
                        "courage": TraitVector(value=0.7, inertia=0.7, evidence_strength="moderate"),
                        "despair": TraitVector(value=0.95, inertia=0.55, evidence_strength="strong"),
                    },
                    beliefs_invalidated=["ENT_MACDUFF"]),
                EntityStateSnapshot(fabula_time=19000, triggered_by="EVT_MACBETH_KILLED",
                    status="dead"),
            ],
        ),
        "ENT_LADY_MACBETH": Entity(
            id="ENT_LADY_MACBETH", name="Lady Macbeth",
            location_id="LOC_INVERNESS_CASTLE", status="healthy",
            traits={
                "ambition": TraitVector(value=0.9, inertia=0.6, evidence_strength="strong"),
                "ruthlessness": TraitVector(value=0.85, inertia=0.55, evidence_strength="strong"),
                "resolve": TraitVector(value=0.9, inertia=0.55, evidence_strength="strong"),
                "guilt": TraitVector(value=0.05, inertia=0.2, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_MACBETH", perceived_state="Macbeth is too full of the milk of human kindness to seize the crown alone",
                       confidence=0.85, inertia=0.55, evidence_strength="strong"),
                Belief(target_id="OBJ_CROWN", perceived_state="The crown is within our grasp tonight",
                       confidence=0.9, inertia=0.5, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=6000, triggered_by="EVT_DUNCAN_MURDER",
                    traits={
                        "guilt": TraitVector(value=0.3, inertia=0.3, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=16000, triggered_by="EVT_LADY_MACBETH_SLEEPWALKING",
                    traits={
                        "guilt": TraitVector(value=0.95, inertia=0.55, evidence_strength="strong"),
                        "resolve": TraitVector(value=0.2, inertia=0.6, evidence_strength="strong"),
                    },
                    status="ill"),
                EntityStateSnapshot(fabula_time=17000, triggered_by="EVT_LADY_MACBETH_DEATH",
                    status="dead"),
            ],
        ),
        "ENT_DUNCAN": Entity(
            id="ENT_DUNCAN", name="King Duncan of Scotland",
            location_id="LOC_FORRES_COURT", status="healthy",
            traits={
                "benevolence": TraitVector(value=0.9, inertia=0.7, evidence_strength="strong"),
                "trust": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                "leadership": TraitVector(value=0.7, inertia=0.6, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_MACBETH", perceived_state="Macbeth is my loyal and valiant kinsman",
                       confidence=0.95, inertia=0.65, evidence_strength="strong"),
                Belief(target_id="ENT_MALCOLM", perceived_state="Malcolm is fit to be my heir",
                       confidence=0.85, inertia=0.7, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=5500, triggered_by="EVT_DUNCAN_ARRIVES_INVERNESS",
                    location_id="LOC_INVERNESS_CASTLE"),
                EntityStateSnapshot(fabula_time=6000, triggered_by="EVT_DUNCAN_MURDER",
                    status="dead"),
            ],
        ),
        "ENT_BANQUO": Entity(
            id="ENT_BANQUO", name="Banquo",
            location_id="LOC_BATTLEFIELD", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.8, inertia=0.65, evidence_strength="strong"),
                "courage": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
                "suspicion": TraitVector(value=0.25, inertia=0.3, evidence_strength="weak"),
                "caution": TraitVector(value=0.6, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_WITCHES", perceived_state="The prophecies may hold truth — my line shall be kings",
                       confidence=0.5, inertia=0.4, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=10500, triggered_by="EVT_MACBETH_CROWNED",
                    traits={
                        "suspicion": TraitVector(value=0.75, inertia=0.45, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_MACBETH", perceived_state="Macbeth played most foully for the crown",
                               confidence=0.7, inertia=0.55, established_at_fabula=10500, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=11000, triggered_by="EVT_BANQUO_MURDERED",
                    status="dead"),
            ],
        ),
        "ENT_FLEANCE": Entity(
            id="ENT_FLEANCE", name="Fleance (son of Banquo)",
            location_id="LOC_DUNSINANE_CASTLE", status="healthy",
            traits={
                "innocence": TraitVector(value=0.9, inertia=0.6, evidence_strength="moderate"),
                "fear": TraitVector(value=0.4, inertia=0.25, evidence_strength="weak"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=11000, triggered_by="EVT_BANQUO_MURDERED",
                    traits={
                        "fear": TraitVector(value=0.85, inertia=0.35, evidence_strength="strong"),
                    },
                    location_id="LOC_ENGLAND"),
            ],
        ),
        "ENT_MACDUFF": Entity(
            id="ENT_MACDUFF", name="Macduff (Thane of Fife)",
            location_id="LOC_INVERNESS_CASTLE", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "courage": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                "vengefulness": TraitVector(value=0.2, inertia=0.3, evidence_strength="weak"),
                "grief": TraitVector(value=0.1, inertia=0.25, evidence_strength="weak"),
                "suspicion": TraitVector(value=0.4, inertia=0.35, evidence_strength="moderate"),
            },
            beliefs=[],
            constants=["caesarean_birth"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=7500, triggered_by="EVT_DUNCAN_DISCOVERED_MURDERED",
                    traits={
                        "suspicion": TraitVector(value=0.7, inertia=0.45, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_MACBETH", perceived_state="Macbeth's grief at Duncan's death rings false",
                               confidence=0.6, inertia=0.5, established_at_fabula=7500, evidence_strength="moderate"),
                    ]),
                EntityStateSnapshot(fabula_time=12500, triggered_by="EVT_MACDUFF_FLEES_TO_ENGLAND",
                    location_id="LOC_ENGLAND"),
                EntityStateSnapshot(fabula_time=14500, triggered_by="EVT_MACDUFF_LEARNS_OF_MASSACRE",
                    traits={
                        "grief": TraitVector(value=0.95, inertia=0.55, evidence_strength="strong"),
                        "vengefulness": TraitVector(value=0.95, inertia=0.6, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_LADY_MACDUFF": Entity(
            id="ENT_LADY_MACDUFF", name="Lady Macduff",
            location_id="LOC_MACDUFF_CASTLE", status="healthy",
            traits={
                "courage": TraitVector(value=0.5, inertia=0.4, evidence_strength="moderate"),
                "anger": TraitVector(value=0.5, inertia=0.3, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_MACDUFF", perceived_state="My husband has abandoned us by fleeing to England",
                       confidence=0.7, inertia=0.5, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=14000, triggered_by="EVT_MACDUFF_FAMILY_SLAUGHTERED",
                    status="dead"),
            ],
        ),
        "ENT_MALCOLM": Entity(
            id="ENT_MALCOLM", name="Prince Malcolm",
            location_id="LOC_FORRES_COURT", status="healthy",
            traits={
                "caution": TraitVector(value=0.75, inertia=0.6, evidence_strength="strong"),
                "leadership": TraitVector(value=0.55, inertia=0.45, evidence_strength="moderate"),
                "loyalty": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
                "courage": TraitVector(value=0.6, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_MACBETH", perceived_state="Macbeth or his agents may seek to kill us next",
                       confidence=0.8, inertia=0.55, established_at_fabula=7500, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=9000, triggered_by="EVT_SONS_FLEE",
                    location_id="LOC_ENGLAND",
                    traits={
                        "caution": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=15000, triggered_by="EVT_MALCOLM_MACDUFF_ALLIANCE",
                    traits={
                        "leadership": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_WITCHES": Entity(
            id="ENT_WITCHES", name="The Three Witches",
            location_id="LOC_HEATH", status="healthy",
            traits={
                "malice": TraitVector(value=0.8, inertia=0.85, evidence_strength="strong"),
                "deception": TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
            },
            beliefs=[],
            constants=["supernatural"],
        ),
        "ENT_LENNOX": Entity(
            id="ENT_LENNOX", name="Lennox",
            location_id="LOC_INVERNESS_CASTLE", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.6, inertia=0.5, evidence_strength="moderate"),
                "suspicion": TraitVector(value=0.4, inertia=0.35, evidence_strength="moderate"),
                "caution": TraitVector(value=0.7, inertia=0.55, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=12000, triggered_by="EVT_LENNOX_WHISPER",
                    traits={
                        "suspicion": TraitVector(value=0.8, inertia=0.5, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_MACBETH", perceived_state="Macbeth is a murdering tyrant",
                               confidence=0.8, inertia=0.55, established_at_fabula=12000, evidence_strength="strong"),
                    ]),
            ],
        ),
    },

    # ── EVENTS ──────────────────────────────────────────────────────────
    events=[
        EventNode(id="EVT_REBELLION_DEFEATED", fabula_time=1000, syuzhet_index=1,
                  event_type="outcome", actor_ids=["ENT_MACBETH", "ENT_BANQUO"], target_ids=[],
                  description="Macbeth and Banquo defeat the Cawdor rebellion on the battlefield."),
        EventNode(id="EVT_WITCHES_PROPHECY_1", fabula_time=2000, syuzhet_index=2,
                  event_type="revelation", actor_ids=["ENT_WITCHES"],
                  target_ids=["ENT_MACBETH", "ENT_BANQUO"],
                  description="On the heath the witches hail Macbeth Thane of Cawdor and king hereafter, and tell Banquo his line shall be kings."),
        EventNode(id="EVT_CAWDOR_TITLE", fabula_time=3000, syuzhet_index=4,
                  event_type="outcome", actor_ids=["ENT_DUNCAN"], target_ids=["ENT_MACBETH"],
                  description="The Thane of Ross informs Macbeth that Duncan has granted him the title Thane of Cawdor, fulfilling the first prophecy."),
        EventNode(id="EVT_MALCOLM_NAMED_HEIR", fabula_time=3500, syuzhet_index=6,
                  event_type="choice", actor_ids=["ENT_DUNCAN"], target_ids=["ENT_MALCOLM"],
                  description="Duncan declares Malcolm his official heir, forcing Macbeth to confront the prophecy's obstacle."),
        EventNode(id="EVT_LETTER_SENT", fabula_time=4000, syuzhet_index=7,
                  event_type="choice", actor_ids=["ENT_MACBETH"], target_ids=["ENT_LADY_MACBETH"],
                  description="Macbeth sends a letter to Lady Macbeth telling her of the witches' prophecies."),
        EventNode(id="EVT_LADY_MACBETH_PERSUADES", fabula_time=5000, syuzhet_index=8,
                  event_type="choice", actor_ids=["ENT_LADY_MACBETH"], target_ids=["ENT_MACBETH"],
                  description="Lady Macbeth persuades a wavering Macbeth to murder Duncan that very night."),
        EventNode(id="EVT_DUNCAN_ARRIVES_INVERNESS", fabula_time=5500, syuzhet_index=9,
                  event_type="outcome", actor_ids=["ENT_DUNCAN"], target_ids=[],
                  description="Duncan arrives at Inverness Castle as Macbeth's guest."),
        EventNode(id="EVT_DUNCAN_MURDER", fabula_time=6000, syuzhet_index=10,
                  event_type="choice", actor_ids=["ENT_MACBETH"], target_ids=["ENT_DUNCAN"],
                  description="Macbeth stabs the sleeping King Duncan to death."),
        EventNode(id="EVT_SERVANTS_FRAMED", fabula_time=6500, syuzhet_index=11,
                  event_type="choice", actor_ids=["ENT_LADY_MACBETH"], target_ids=[],
                  description="Lady Macbeth plants the bloody daggers on Duncan's drugged chamber attendants."),
        EventNode(id="EVT_DUNCAN_DISCOVERED_MURDERED", fabula_time=7000, syuzhet_index=12,
                  event_type="revelation", actor_ids=["ENT_MACDUFF"], target_ids=[],
                  description="Macduff discovers Duncan's body and raises the alarm at Inverness."),
        EventNode(id="EVT_MACBETH_KILLS_SERVANTS", fabula_time=7500, syuzhet_index=14,
                  event_type="choice", actor_ids=["ENT_MACBETH"], target_ids=[],
                  description="Macbeth impulsively kills the framed servants to silence them, claiming vengeance."),
        EventNode(id="EVT_SONS_FLEE", fabula_time=9000, syuzhet_index=15,
                  event_type="choice", actor_ids=["ENT_MALCOLM"], target_ids=[],
                  description="Duncan's sons Malcolm and Donalbain flee Scotland for England, fearing assassination."),
        EventNode(id="EVT_MACBETH_CROWNED", fabula_time=10000, syuzhet_index=16,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MACBETH"],
                  description="With Duncan's heirs in flight, Macbeth assumes the throne as King of Scotland."),
        EventNode(id="EVT_BANQUO_MURDERED", fabula_time=11000, syuzhet_index=17,
                  event_type="choice", actor_ids=["ENT_MACBETH"], target_ids=["ENT_BANQUO"],
                  description="Macbeth's hired murderers ambush Banquo and kill him; Fleance escapes into the night."),
        EventNode(id="EVT_BANQUO_GHOST", fabula_time=12000, syuzhet_index=18,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MACBETH"],
                  description="Banquo's ghost appears at Macbeth's banquet, visible only to him; he raves in front of his lords."),
        EventNode(id="EVT_LENNOX_WHISPER", fabula_time=12500, syuzhet_index=19,
                  event_type="revelation", actor_ids=["ENT_LENNOX"], target_ids=[],
                  description="Lennox confides to another lord his suspicion that Macbeth is a murdering tyrant."),
        EventNode(id="EVT_WITCHES_PROPHECY_2", fabula_time=13000, syuzhet_index=20,
                  event_type="revelation", actor_ids=["ENT_WITCHES"], target_ids=["ENT_MACBETH"],
                  description="In the cavern the witches summon apparitions: beware Macduff, none of woman born can harm Macbeth, safe until Birnam Wood comes to Dunsinane."),
        EventNode(id="EVT_MACDUFF_FLEES_TO_ENGLAND", fabula_time=13500, syuzhet_index=22,
                  event_type="choice", actor_ids=["ENT_MACDUFF"], target_ids=[],
                  description="Macduff travels to England to seek out Malcolm and raise an army."),
        EventNode(id="EVT_MACDUFF_FAMILY_SLAUGHTERED", fabula_time=14000, syuzhet_index=23,
                  event_type="choice", actor_ids=["ENT_MACBETH"], target_ids=["ENT_LADY_MACDUFF"],
                  description="Macbeth orders his hired men to seize Macduff's castle and slaughter his wife and children."),
        EventNode(id="EVT_MACDUFF_LEARNS_OF_MASSACRE", fabula_time=14500, syuzhet_index=24,
                  event_type="revelation", actor_ids=[], target_ids=["ENT_MACDUFF"],
                  description="The Thane of Ross arrives in England and tells Macduff that his family has been slaughtered."),
        EventNode(id="EVT_MALCOLM_MACDUFF_ALLIANCE", fabula_time=15000, syuzhet_index=25,
                  event_type="choice", actor_ids=["ENT_MALCOLM", "ENT_MACDUFF"], target_ids=[],
                  description="Provoked by grief, Macduff joins Malcolm's English-backed army to retake Scotland."),
        EventNode(id="EVT_LADY_MACBETH_SLEEPWALKING", fabula_time=16000, syuzhet_index=26,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_LADY_MACBETH"],
                  description="Lady Macbeth sleepwalks at Dunsinane, washing imaginary bloodstains from her hands while a doctor and gentlewoman watch."),
        EventNode(id="EVT_LADY_MACBETH_DEATH", fabula_time=17000, syuzhet_index=28,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_LADY_MACBETH"],
                  description="Lady Macbeth dies — implied suicide — prompting Macbeth's 'tomorrow' soliloquy."),
        EventNode(id="EVT_BIRNAM_WOOD_MOVES", fabula_time=18500, syuzhet_index=29,
                  event_type="outcome", actor_ids=["ENT_MALCOLM"], target_ids=[],
                  description="Malcolm's army cuts boughs from Birnam Wood and advances on Dunsinane camouflaged, fulfilling the prophecy."),
        EventNode(id="EVT_MACBETH_KILLED", fabula_time=19000, syuzhet_index=30,
                  event_type="outcome", actor_ids=["ENT_MACDUFF"], target_ids=["ENT_MACBETH"],
                  description="Macduff, born by caesarean section, kills Macbeth in single combat at Dunsinane."),
        EventNode(id="EVT_MALCOLM_CROWNED", fabula_time=20000, syuzhet_index=32,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_MALCOLM"],
                  description="Malcolm is crowned King of Scotland at Scone; legitimate feudal order is restored."),

        # ── UTTERANCES (discrete on-page speech-acts; woven into syuzhet at the
        #    point the reader actually encounters them) ────────────────────
        EventNode(id="EVT_UTT_PROPHECY_HEATH", event_type="utterance",
                  description="On the heath the witches deliver their first prophetic salutation to Macbeth and Banquo.",
                  speaker_id="ENT_WITCHES", addressee_ids=["ENT_MACBETH", "ENT_BANQUO"],
                  actor_ids=["ENT_WITCHES"], target_ids=["EVT_WITCHES_PROPHECY_1"],
                  content="All hail Macbeth — Thane of Glamis, Thane of Cawdor, king hereafter; and Banquo, lesser yet greater, shall father a line of kings though never wear the crown himself.",
                  via_channel_id="CHN_PROPHETIC_LINK", truth_value="performative",
                  fabula_time=2000, syuzhet_index=3),
        EventNode(id="EVT_UTT_DUNCAN_BESTOWS_CAWDOR", event_type="utterance",
                  description="At Forres, Duncan formally proclaims the title of Thane of Cawdor transferred to Macbeth, conveyed to him via Ross.",
                  speaker_id="ENT_DUNCAN", addressee_ids=["ENT_MACBETH"],
                  actor_ids=["ENT_DUNCAN"], target_ids=["EVT_CAWDOR_TITLE"],
                  content="What the traitor Cawdor hath lost, noble Macbeth hath won — his title and lands are bestowed upon Macbeth.",
                  via_channel_id=None, truth_value="performative",
                  fabula_time=3000, syuzhet_index=5),
        EventNode(id="EVT_UTT_MACDUFF_ALARM", event_type="utterance",
                  description="Bursting back from the murder chamber, Macduff raises the general alarm at Inverness.",
                  speaker_id="ENT_MACDUFF", addressee_ids=["ENT_LENNOX", "ENT_MALCOLM"],
                  actor_ids=["ENT_MACDUFF"], target_ids=["EVT_DUNCAN_DISCOVERED_MURDERED", "EVT_DUNCAN_MURDER"],
                  content="O horror, horror, horror — most sacrilegious murder hath broke ope the Lord's anointed temple; awake, awake, ring the alarum bell!",
                  via_channel_id=None, truth_value="true",
                  fabula_time=7000, syuzhet_index=13),
        EventNode(id="EVT_UTT_PROPHECY_CAVERN", event_type="utterance",
                  description="In the witches' cavern, the apparitions answer Macbeth's demand for further prophecy.",
                  speaker_id="ENT_WITCHES", addressee_ids=["ENT_MACBETH"],
                  actor_ids=["ENT_WITCHES"], target_ids=["EVT_WITCHES_PROPHECY_2"],
                  content="Beware Macduff; none of woman born shall harm Macbeth; he is safe until Great Birnam Wood comes against him to Dunsinane Hill.",
                  via_channel_id="CHN_PROPHETIC_LINK", truth_value="performative",
                  fabula_time=13000, syuzhet_index=21),
        EventNode(id="EVT_UTT_LADY_MACBETH_SLEEPWALK_CONFESSION", event_type="utterance",
                  description="In a guilt-trance at Dunsinane, Lady Macbeth confesses the regicide and the slaughter of Macduff's wife while a doctor and gentlewoman watch unseen.",
                  speaker_id="ENT_LADY_MACBETH", addressee_ids=[],
                  actor_ids=["ENT_LADY_MACBETH"], target_ids=["EVT_DUNCAN_MURDER", "EVT_BANQUO_MURDERED", "EVT_MACDUFF_FAMILY_SLAUGHTERED"],
                  content="Out, damned spot — yet who would have thought the old man to have had so much blood in him? The Thane of Fife had a wife: where is she now?",
                  via_channel_id=None, truth_value="true",
                  fabula_time=16000, syuzhet_index=27),
        EventNode(id="EVT_UTT_MACBETH_INVINCIBILITY_TAUNT", event_type="utterance",
                  description="At Dunsinane, Macbeth taunts the closing Macduff with the witches' second prophecy, certain he cannot be killed by any man of woman born.",
                  speaker_id="ENT_MACBETH", addressee_ids=["ENT_MACDUFF"],
                  actor_ids=["ENT_MACBETH"], target_ids=["EVT_MACBETH_KILLED", "EVT_WITCHES_PROPHECY_2"],
                  content="Thou losest labour — I bear a charmèd life which must not yield to one of woman born.",
                  via_channel_id=None, truth_value="false",
                  fabula_time=19000, syuzhet_index=31),
    ],

    # ── CAUSAL TOPOLOGY ─────────────────────────────────────────────────
    causal_topology=[
        # ── chain_reaction (Event → Event) ──
        CausalEdge(source_id="EVT_REBELLION_DEFEATED", target_id="EVT_CAWDOR_TITLE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1000, propagation_delay=2000),
        CausalEdge(source_id="EVT_WITCHES_PROPHECY_1", target_id="EVT_LETTER_SENT",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2000, propagation_delay=2000),
        CausalEdge(source_id="EVT_MALCOLM_NAMED_HEIR", target_id="EVT_LADY_MACBETH_PERSUADES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=3500, propagation_delay=1500),
        CausalEdge(source_id="EVT_LETTER_SENT", target_id="EVT_LADY_MACBETH_PERSUADES",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=7.0, fabula_time=4000, propagation_delay=1000),
        CausalEdge(source_id="EVT_LADY_MACBETH_PERSUADES", target_id="EVT_DUNCAN_MURDER",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=5000, propagation_delay=1000),
        CausalEdge(source_id="EVT_DUNCAN_ARRIVES_INVERNESS", target_id="EVT_DUNCAN_MURDER",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=5500, propagation_delay=500),
        CausalEdge(source_id="EVT_DUNCAN_MURDER", target_id="EVT_SERVANTS_FRAMED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=6000, propagation_delay=500),
        CausalEdge(source_id="EVT_DUNCAN_MURDER", target_id="EVT_DUNCAN_DISCOVERED_MURDERED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=6000, propagation_delay=1000),
        CausalEdge(source_id="EVT_DUNCAN_DISCOVERED_MURDERED", target_id="EVT_MACBETH_KILLS_SERVANTS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7000, propagation_delay=500),
        CausalEdge(source_id="EVT_DUNCAN_DISCOVERED_MURDERED", target_id="EVT_SONS_FLEE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=7000, propagation_delay=2000),
        CausalEdge(source_id="EVT_SONS_FLEE", target_id="EVT_MACBETH_CROWNED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=9000, propagation_delay=1000),
        CausalEdge(source_id="EVT_WITCHES_PROPHECY_1", target_id="EVT_BANQUO_MURDERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=2000, propagation_delay=9000),
        CausalEdge(source_id="EVT_BANQUO_MURDERED", target_id="EVT_BANQUO_GHOST",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=11000, propagation_delay=1000),
        CausalEdge(source_id="EVT_BANQUO_GHOST", target_id="EVT_LENNOX_WHISPER",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=12000, propagation_delay=500),
        CausalEdge(source_id="EVT_BANQUO_GHOST", target_id="EVT_WITCHES_PROPHECY_2",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=12000, propagation_delay=1000),
        CausalEdge(source_id="EVT_WITCHES_PROPHECY_2", target_id="EVT_MACDUFF_FAMILY_SLAUGHTERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=13000, propagation_delay=1000),
        CausalEdge(source_id="EVT_LENNOX_WHISPER", target_id="EVT_MACDUFF_FLEES_TO_ENGLAND",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=12500, propagation_delay=1000),
        CausalEdge(source_id="EVT_MACDUFF_FLEES_TO_ENGLAND", target_id="EVT_MACDUFF_FAMILY_SLAUGHTERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=13500, propagation_delay=500),
        CausalEdge(source_id="EVT_MACDUFF_FAMILY_SLAUGHTERED", target_id="EVT_MACDUFF_LEARNS_OF_MASSACRE",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=7.0, fabula_time=14000, propagation_delay=500),
        CausalEdge(source_id="EVT_MACDUFF_LEARNS_OF_MASSACRE", target_id="EVT_MALCOLM_MACDUFF_ALLIANCE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=14500, propagation_delay=500),
        CausalEdge(source_id="EVT_LADY_MACBETH_SLEEPWALKING", target_id="EVT_LADY_MACBETH_DEATH",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=16000, propagation_delay=1000),
        CausalEdge(source_id="EVT_MALCOLM_MACDUFF_ALLIANCE", target_id="EVT_BIRNAM_WOOD_MOVES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=15000, propagation_delay=3500),
        CausalEdge(source_id="EVT_BIRNAM_WOOD_MOVES", target_id="EVT_MACBETH_KILLED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=18500, propagation_delay=500),
        CausalEdge(source_id="EVT_MACBETH_KILLED", target_id="EVT_MALCOLM_CROWNED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=19000, propagation_delay=1000),

        # ── mutation (Event → Entity trait/status) ──
        # Each one has a matching state_timeline snapshot above.
        CausalEdge(source_id="EVT_WITCHES_PROPHECY_1", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2000,
                   trait_target="ambition", trait_delta=0.4),
        CausalEdge(source_id="EVT_LADY_MACBETH_PERSUADES", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=5000,
                   trait_target="ruthlessness", trait_delta=0.4),
        CausalEdge(source_id="EVT_DUNCAN_MURDER", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=6000,
                   trait_target="guilt", trait_delta=0.7),
        CausalEdge(source_id="EVT_DUNCAN_MURDER", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=6000,
                   trait_target="paranoia", trait_delta=0.5),
        CausalEdge(source_id="EVT_DUNCAN_MURDER", target_id="ENT_LADY_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=6000,
                   trait_target="guilt", trait_delta=0.4),
        CausalEdge(source_id="EVT_MACBETH_CROWNED", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=10000,
                   trait_target="paranoia", trait_delta=0.3),
        CausalEdge(source_id="EVT_MACBETH_CROWNED", target_id="ENT_BANQUO",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=10000,
                   trait_target="suspicion", trait_delta=0.6, propagation_delay=500),
        CausalEdge(source_id="EVT_BANQUO_MURDERED", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=11000,
                   trait_target="paranoia", trait_delta=0.4),
        CausalEdge(source_id="EVT_BANQUO_MURDERED", target_id="ENT_FLEANCE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=11000,
                   trait_target="fear", trait_delta=0.7),
        CausalEdge(source_id="EVT_LENNOX_WHISPER", target_id="ENT_LENNOX",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=5.0, fabula_time=12500,
                   trait_target="suspicion", trait_delta=0.5),
        CausalEdge(source_id="EVT_WITCHES_PROPHECY_2", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=13000,
                   trait_target="courage", trait_delta=0.3),
        CausalEdge(source_id="EVT_DUNCAN_DISCOVERED_MURDERED", target_id="ENT_MACDUFF",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7500,
                   trait_target="suspicion", trait_delta=0.5),
        CausalEdge(source_id="EVT_MACDUFF_LEARNS_OF_MASSACRE", target_id="ENT_MACDUFF",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=14500,
                   trait_target="grief", trait_delta=1.0),
        CausalEdge(source_id="EVT_MACDUFF_LEARNS_OF_MASSACRE", target_id="ENT_MACDUFF",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=14500,
                   trait_target="vengefulness", trait_delta=1.0),
        CausalEdge(source_id="EVT_LADY_MACBETH_SLEEPWALKING", target_id="ENT_LADY_MACBETH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=16000,
                   trait_target="guilt", trait_delta=0.7),
        CausalEdge(source_id="EVT_LADY_MACBETH_DEATH", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=17000,
                   trait_target="despair", trait_delta=0.8),
        CausalEdge(source_id="EVT_MACBETH_KILLED", target_id="ENT_MACBETH",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=19000,
                   trait_target="courage", trait_delta=-1.0),
        CausalEdge(source_id="EVT_MACDUFF_FAMILY_SLAUGHTERED", target_id="ENT_LADY_MACDUFF",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=14000,
                   trait_target="courage", trait_delta=-1.0),

        # ── mutation_social (Event → Relationship metric) ──
        CausalEdge(source_id="EVT_WITCHES_PROPHECY_1", target_id="ENT_MACBETH",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=2000,
                   trait_target="fear", trait_delta=0.4, rel_counterpart_id="ENT_BANQUO"),
        CausalEdge(source_id="EVT_DUNCAN_MURDER", target_id="ENT_MACBETH",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=6000,
                   trait_target="fear", trait_delta=0.5, rel_counterpart_id="ENT_BANQUO"),
        CausalEdge(source_id="EVT_BANQUO_MURDERED", target_id="ENT_MALCOLM",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=11000,
                   trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_MACBETH"),
        CausalEdge(source_id="EVT_MACDUFF_FAMILY_SLAUGHTERED", target_id="ENT_MACDUFF",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=10.0, fabula_time=14000,
                   trait_target="affinity", trait_delta=-1.0, rel_counterpart_id="ENT_MACBETH"),
        CausalEdge(source_id="EVT_MACDUFF_LEARNS_OF_MASSACRE", target_id="ENT_MACDUFF",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=14500,
                   trait_target="affinity", trait_delta=0.4, rel_counterpart_id="ENT_MALCOLM"),
        CausalEdge(source_id="EVT_LADY_MACBETH_PERSUADES", target_id="ENT_MACBETH",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=5000,
                   trait_target="power_dynamic", trait_delta=-0.3, rel_counterpart_id="ENT_LADY_MACBETH"),
        CausalEdge(source_id="EVT_BANQUO_GHOST", target_id="ENT_MACBETH",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=12000,
                   trait_target="fear", trait_delta=0.5, rel_counterpart_id="ENT_BANQUO"),

        # ── affordance_gate (State → Event) ──
        CausalEdge(source_id="ENT_LADY_MACBETH", target_id="EVT_LADY_MACBETH_PERSUADES",
                   causality_type="affordance_gate", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=5000),
        CausalEdge(source_id="OBJ_BLOODY_DAGGERS", target_id="EVT_DUNCAN_MURDER",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=6000),
        CausalEdge(source_id="ENT_WITCHES", target_id="EVT_WITCHES_PROPHECY_1",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=2000),
        CausalEdge(source_id="OBJ_APPARITIONS", target_id="EVT_WITCHES_PROPHECY_2",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=13000),
        CausalEdge(source_id="OBJ_BIRNAM_BOUGHS", target_id="EVT_BIRNAM_WOOD_MOVES",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=18500),
        CausalEdge(source_id="ENT_MACDUFF", target_id="EVT_MACBETH_KILLED",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=19000),

        # ── ambient_propagation (State → State) ──
        CausalEdge(source_id="LOC_DUNSINANE_CASTLE", target_id="ENT_MACBETH",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=13000),
        CausalEdge(source_id="LOC_HEATH", target_id="ENT_MACBETH",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=2000),
        CausalEdge(source_id="ENT_MACBETH", target_id="ENT_LADY_MACBETH",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=2.5, fabula_time=12000),

        # ── WORLD_ → Event (named-latent common-cause wiring) ──
        CausalEdge(source_id="WORLD_FEUDAL_HIERARCHY", target_id="EVT_REBELLION_DEFEATED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1000),
        CausalEdge(source_id="WORLD_FEUDAL_HIERARCHY", target_id="EVT_CAWDOR_TITLE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=3000),
        CausalEdge(source_id="WORLD_FEUDAL_HIERARCHY", target_id="EVT_MALCOLM_NAMED_HEIR",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=3500),
        CausalEdge(source_id="WORLD_FEUDAL_HIERARCHY", target_id="EVT_MACBETH_CROWNED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=10000),
        CausalEdge(source_id="WORLD_FEUDAL_HIERARCHY", target_id="EVT_MALCOLM_CROWNED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=20000),
        CausalEdge(source_id="WORLD_SUPERNATURAL_PROPHECY", target_id="EVT_DUNCAN_MURDER",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=6000),
        CausalEdge(source_id="WORLD_SUPERNATURAL_PROPHECY", target_id="EVT_BANQUO_MURDERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=11000),
        CausalEdge(source_id="WORLD_SUPERNATURAL_PROPHECY", target_id="EVT_MACDUFF_FAMILY_SLAUGHTERED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=14000),
        CausalEdge(source_id="WORLD_SUPERNATURAL_PROPHECY", target_id="EVT_BIRNAM_WOOD_MOVES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=18500),
        CausalEdge(source_id="WORLD_SUPERNATURAL_PROPHECY", target_id="EVT_MACBETH_KILLED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=19000),
        CausalEdge(source_id="WORLD_DIVINE_RIGHT", target_id="EVT_DUNCAN_MURDER",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=3.0, fabula_time=6000),
        CausalEdge(source_id="WORLD_DIVINE_RIGHT", target_id="EVT_LADY_MACBETH_SLEEPWALKING",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=16000),
    ],

    # ── SPATIAL TOPOLOGY ────────────────────────────────────────────────
    spatial_topology=[
        SpatialEdge(source_id="LOC_BATTLEFIELD", target_id="LOC_HEATH"),
        SpatialEdge(source_id="LOC_BATTLEFIELD", target_id="LOC_FORRES_COURT"),
        SpatialEdge(source_id="LOC_HEATH", target_id="LOC_FORRES_COURT"),
        SpatialEdge(source_id="LOC_HEATH", target_id="LOC_WITCHES_CAVERN"),
        SpatialEdge(source_id="LOC_FORRES_COURT", target_id="LOC_INVERNESS_CASTLE"),
        SpatialEdge(source_id="LOC_INVERNESS_CASTLE", target_id="LOC_DUNSINANE_CASTLE"),
        SpatialEdge(source_id="LOC_DUNSINANE_CASTLE", target_id="LOC_INVERNESS_CASTLE"),
        SpatialEdge(source_id="LOC_DUNSINANE_CASTLE", target_id="LOC_MACDUFF_CASTLE"),
        SpatialEdge(source_id="LOC_DUNSINANE_CASTLE", target_id="LOC_BIRNAM_WOOD"),
        SpatialEdge(source_id="LOC_BIRNAM_WOOD", target_id="LOC_DUNSINANE_CASTLE"),
        SpatialEdge(source_id="LOC_MACDUFF_CASTLE", target_id="LOC_ENGLAND"),
        SpatialEdge(source_id="LOC_ENGLAND", target_id="LOC_BIRNAM_WOOD"),
        SpatialEdge(source_id="LOC_DUNSINANE_CASTLE", target_id="LOC_WITCHES_CAVERN"),
    ],

    # ── INFORMATION TOPOLOGY ────────────────────────────────────────────
    # Only STANDING communication capabilities live here. One-shot speech-acts
    # (Duncan's proclamation, Macduff's alarm cry, Macbeth's pre-duel taunt,
    # Lady Macbeth's sleepwalking confession) are modelled solely as utterance
    # EventNodes with via_channel_id=None.
    channels={
        "CHN_PROPHETIC_LINK": Channel(
            id="CHN_PROPHETIC_LINK",
            name="Witches' Prophetic Link to Macbeth",
            medium="prophetic_link",
            participant_ids=["ENT_WITCHES", "ENT_MACBETH", "ENT_BANQUO"],
            directionality="broadcast",
            # Riddling utterance: Macbeth and Banquo decode only the literal
            # surface, missing the equivocations that ultimately doom them.
            intelligibility={"ENT_MACBETH": 0.6, "ENT_BANQUO": 0.6},
            established_at_fabula=2000,
            terminated_at_fabula=13000,
            evidence_strength="strong",
        ),
        "CHN_NOBLE_DISSENT": Channel(
            id="CHN_NOBLE_DISSENT",
            name="Whispered Dissent Among the Loyalist Thanes",
            medium="classified_pipeline",
            participant_ids=["ENT_LENNOX", "ENT_MACDUFF", "ENT_MALCOLM"],
            directionality="duplex",
            intelligibility={},
            established_at_fabula=11000,
            terminated_at_fabula=None,
            evidence_strength="moderate",
        ),
    },

    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_FEUDAL_HIERARCHY": GlobalTrait(
            id="WORLD_FEUDAL_HIERARCHY",
            name="Scottish Feudal Hierarchy",
            description="Scotland's feudal order in which thanes earn or forfeit royal favour through valour and bloodshed; succession is governed by the king's nominated heir. Drives ambition, loyalty oaths, and the legitimacy of seizure-by-violence.",
            category="governance",
            magnitude=TraitVector(value=0.8, inertia=0.7, evidence_strength="strong"),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=6000, triggered_by="EVT_DUNCAN_MURDER",
                    magnitude=TraitVector(value=0.5, inertia=0.4, evidence_strength="strong"),
                    description="Regicide shatters the feudal compact; kingship is now seized by treachery, not bestowed by lineage."),
                WorldTraitSnapshot(fabula_time=20000, triggered_by="EVT_MALCOLM_CROWNED",
                    magnitude=TraitVector(value=0.75, inertia=0.6, evidence_strength="strong"),
                    description="Malcolm's coronation at Scone restores legitimate succession, but the order is freshly re-installed and inertia is somewhat lower than the pre-murder baseline."),
            ],
        ),
        "WORLD_SUPERNATURAL_PROPHECY": GlobalTrait(
            id="WORLD_SUPERNATURAL_PROPHECY",
            name="Witches' Prophecy",
            description="A latent supernatural force operating through the witches' prophecies — never an event itself, but the named-latent common cause of every choice that the prophecy frames. Blurs the line between fate and agency.",
            category="cosmology",
            magnitude=TraitVector(value=0.55, inertia=0.9, evidence_strength="moderate"),
            affected_domains=["psychological", "epistemic"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=2000, triggered_by="EVT_WITCHES_PROPHECY_1",
                    magnitude=TraitVector(value=0.7, inertia=0.9, evidence_strength="strong"),
                    description="First prophecies overtly deliver the witches' design into Macbeth's psyche."),
                WorldTraitSnapshot(fabula_time=13000, triggered_by="EVT_WITCHES_PROPHECY_2",
                    magnitude=TraitVector(value=0.85, inertia=0.95, evidence_strength="strong"),
                    description="Second prophecies deepen Macbeth's false confidence with riddling assurances."),
                WorldTraitSnapshot(fabula_time=18500, triggered_by="EVT_BIRNAM_WOOD_MOVES",
                    magnitude=TraitVector(value=0.95, inertia=0.95, evidence_strength="strong"),
                    description="Prophecy fulfilled literally; supernatural fate is shown to be inescapable."),
            ],
        ),
        "WORLD_DIVINE_RIGHT": GlobalTrait(
            id="WORLD_DIVINE_RIGHT",
            name="Divine Right of Kings",
            description="The implicit Jacobean cosmological ordering in which the murder of an anointed king is a cosmic crime that returns as madness, sleeplessness and ill omens. Operates as a named-latent moral physics on the Macbeths.",
            category="cosmology",
            magnitude=TraitVector(value=0.5, inertia=0.85, evidence_strength="moderate"),
            affected_domains=["psychological", "social"],
        ),
    },

    # ── SOCIAL TOPOLOGY (per-axis RelationshipMetric — only observed axes) ──
    social_topology=[
        # The Macbeth marriage: strong affinity and clear power inversion (she leads).
        RelationshipEdge(
            source_entity_id="ENT_MACBETH", target_entity_id="ENT_LADY_MACBETH",
            metrics={
                "affinity":      RelationshipMetric(value=0.8, inertia=0.5, evidence_strength="strong", last_updated_fabula=4000),
                "power_dynamic": RelationshipMetric(value=-0.4, inertia=0.6, evidence_strength="strong", last_updated_fabula=5000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_LADY_MACBETH", target_entity_id="ENT_MACBETH",
            metrics={
                "affinity":      RelationshipMetric(value=0.85, inertia=0.5, evidence_strength="strong", last_updated_fabula=4000),
                "power_dynamic": RelationshipMetric(value=0.4, inertia=0.6, evidence_strength="strong", last_updated_fabula=5000),
            },
        ),
        # Macbeth → Duncan: pre-murder loyalty, then guilty avoidance (only affinity inverts; fear unobserved).
        RelationshipEdge(
            source_entity_id="ENT_MACBETH", target_entity_id="ENT_DUNCAN",
            metrics={
                "affinity":      RelationshipMetric(value=0.4, inertia=0.4, evidence_strength="moderate", last_updated_fabula=1000),
                "power_dynamic": RelationshipMetric(value=-0.7, inertia=0.7, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        # Macbeth ↔ Banquo: comradeship souring into murderous fear.
        RelationshipEdge(
            source_entity_id="ENT_MACBETH", target_entity_id="ENT_BANQUO",
            metrics={
                "affinity": RelationshipMetric(value=0.5, inertia=0.4, evidence_strength="strong", last_updated_fabula=1000),
                "fear":     RelationshipMetric(value=0.6, inertia=0.2, evidence_strength="strong", last_updated_fabula=6000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_BANQUO", target_entity_id="ENT_MACBETH",
            metrics={
                "affinity": RelationshipMetric(value=0.4, inertia=0.4, evidence_strength="strong", last_updated_fabula=10500),
                "fear":     RelationshipMetric(value=0.4, inertia=0.2, evidence_strength="moderate", last_updated_fabula=10500),
            },
        ),
        # Macbeth ↔ Macduff: enmity hardening into mortal opposition.
        RelationshipEdge(
            source_entity_id="ENT_MACBETH", target_entity_id="ENT_MACDUFF",
            metrics={
                "affinity": RelationshipMetric(value=-0.7, inertia=0.4, evidence_strength="strong", last_updated_fabula=13000),
                "fear":     RelationshipMetric(value=0.55, inertia=0.2, evidence_strength="strong", last_updated_fabula=13000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_MACDUFF", target_entity_id="ENT_MACBETH",
            metrics={
                "affinity": RelationshipMetric(value=-1.0, inertia=0.55, evidence_strength="strong", last_updated_fabula=14500),
                "fear":     RelationshipMetric(value=0.2, inertia=0.2, evidence_strength="weak", last_updated_fabula=14500),
                "power_dynamic": RelationshipMetric(value=0.4, inertia=0.6, evidence_strength="strong", last_updated_fabula=19000),
            },
        ),
        # Macduff ↔ Malcolm: alliance forged in shared loss.
        RelationshipEdge(
            source_entity_id="ENT_MACDUFF", target_entity_id="ENT_MALCOLM",
            metrics={
                "affinity":      RelationshipMetric(value=0.8, inertia=0.45, evidence_strength="strong", last_updated_fabula=15000),
                "power_dynamic": RelationshipMetric(value=-0.3, inertia=0.6, evidence_strength="moderate", last_updated_fabula=15000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_MALCOLM", target_entity_id="ENT_MACDUFF",
            metrics={
                "affinity":      RelationshipMetric(value=0.75, inertia=0.45, evidence_strength="strong", last_updated_fabula=15000),
                "power_dynamic": RelationshipMetric(value=0.3, inertia=0.6, evidence_strength="moderate", last_updated_fabula=15000),
            },
        ),
        # Malcolm → Macbeth: hatred and fear.
        RelationshipEdge(
            source_entity_id="ENT_MALCOLM", target_entity_id="ENT_MACBETH",
            metrics={
                "affinity": RelationshipMetric(value=-0.9, inertia=0.5, evidence_strength="strong", last_updated_fabula=11000),
                "fear":     RelationshipMetric(value=0.6, inertia=0.2, evidence_strength="strong", last_updated_fabula=9000),
            },
        ),
        # Lady Macbeth → Duncan: cold contempt during the planning.
        RelationshipEdge(
            source_entity_id="ENT_LADY_MACBETH", target_entity_id="ENT_DUNCAN",
            metrics={
                "affinity":      RelationshipMetric(value=-0.6, inertia=0.4, evidence_strength="strong", last_updated_fabula=5000),
                "power_dynamic": RelationshipMetric(value=-0.5, inertia=0.7, evidence_strength="moderate", last_updated_fabula=5000),
            },
        ),
        # Macbeth → Witches: drawn to them with mingled fear and need.
        RelationshipEdge(
            source_entity_id="ENT_MACBETH", target_entity_id="ENT_WITCHES",
            metrics={
                "affinity": RelationshipMetric(value=0.2, inertia=0.4, evidence_strength="moderate", last_updated_fabula=13000),
                "fear":     RelationshipMetric(value=0.5, inertia=0.25, evidence_strength="strong", last_updated_fabula=2000),
                "power_dynamic": RelationshipMetric(value=-0.6, inertia=0.7, evidence_strength="strong", last_updated_fabula=2000),
            },
        ),
        # Macbeth → Fleance: only fear is observed (a remaining heir of the prophecy).
        RelationshipEdge(
            source_entity_id="ENT_MACBETH", target_entity_id="ENT_FLEANCE",
            metrics={
                "fear": RelationshipMetric(value=0.65, inertia=0.2, evidence_strength="strong", last_updated_fabula=11000),
            },
        ),
    ],
)
