# SPDX-FileCopyrightText: 2026 David Rae Wilmot
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Nineteen Eighty-Four — high-fidelity WorldStateV1 test fixture.

Authored against the current ingestion prompts. Demonstrates all five
CausalEdge modalities, per-axis ``RelationshipMetric``, explicit
``evidence_strength``, and named-latent WORLD_ traits (Ingsoc / Party
totalitarianism, perpetual war, panoptic surveillance) wired as
common-cause parents over the events they jointly drive.
"""
from shadow_loom.models import (
    Channel,
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, RelationshipMetric, TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
    NarrativeStyle,
)

world_state = WorldStateV1(
    narrative_style=NarrativeStyle(
        format='synopsis',
        target_word_min=260,
        target_word_max=600,
        prose_density='sparse',
        voice='synoptic narration; no dialogue; condensed scene description; third-person POV; past tense',
        style_exemplar='As the narrative opens on "April 4th, 1984", a date whose validity is questioned by the protagonist, Winston Smith, the world has been ravaged for decades by global war, civil conflict and revolution. What was formerly known as the island of Great Britain is "Airstrip One", a province of Oceania, one of the three totalitarian super-states that rule the world. It is ruled by "The Party" under the ideology of "Ingsoc": a Newspeak shortening of "English Socialism". Also present is the mysterious leader Big Brother, who has an intense cult of personality.',
        source_word_count=781,
    ),
    # ── LOCATIONS ──────────────────────────────────────────────────────
    locations={
        "LOC_VICTORY_MANSIONS": Location(
            name="Victory Mansions, Flat 7",
            description="Winston's grimy Outer-Party flat with its inescapable telescreen.",
            ambient_state={
                "surveillance":   AmbientVector(value=0.9, volatility=0.1, evidence_strength="strong"),
                "drabness":       AmbientVector(value=0.85, volatility=0.1, evidence_strength="strong"),
            },
        ),
        "LOC_MINITRUE": Location(
            name="Ministry of Truth",
            description="The pyramid where Winston rewrites yesterday's newspapers and feeds originals to memory holes.",
            ambient_state={
                "ideological_pressure": AmbientVector(value=0.95, volatility=0.1, evidence_strength="strong"),
                "surveillance":         AmbientVector(value=0.9, volatility=0.1, evidence_strength="strong"),
            },
        ),
        "LOC_CHARRINGTON_ROOM": Location(
            name="Room above Mr Charrington's Shop",
            description="The seemingly telescreen-free room Winston rents for the affair — its concealed pickup is the trap that springs.",
            ambient_state={
                "false_intimacy": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
                "hidden_surveillance": AmbientVector(value=0.95, volatility=0.05, evidence_strength="strong"),
            },
        ),
        "LOC_PROLE_DISTRICT": Location(
            name="Prole District",
            description="The unsupervised, political-consciousness-free quarter beyond the Party's daily attention.",
            ambient_state={
                "depoliticisation": AmbientVector(value=0.9, volatility=0.1, evidence_strength="strong"),
                "low_surveillance": AmbientVector(value=0.3, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_GOLDEN_COUNTRY": Location(
            name="Open Country / 'The Golden Country'",
            description="Hawthorn-studded clearing outside London where Winston and Julia first sleep together.",
            ambient_state={
                "freedom":     AmbientVector(value=0.8, volatility=0.3, evidence_strength="strong"),
                "low_surveillance": AmbientVector(value=0.4, volatility=0.3, evidence_strength="moderate"),
            },
        ),
        "LOC_OBRIEN_FLAT": Location(
            name="O'Brien's Inner-Party Flat",
            description="Spacious, telescreen-mutable apartment where O'Brien stages his recruitment of Winston into the fictitious Brotherhood.",
            ambient_state={
                "luxury":     AmbientVector(value=0.85, volatility=0.1, evidence_strength="strong"),
                "performed_safety": AmbientVector(value=0.9, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_MINILOVE": Location(
            name="Ministry of Love",
            description="The windowless, white-tile interrogation complex where Party heretics are broken.",
            ambient_state={
                "white_glare": AmbientVector(value=0.95, volatility=0.05, evidence_strength="strong"),
                "terror":      AmbientVector(value=0.95, volatility=0.4, evidence_strength="strong"),
            },
        ),
        "LOC_ROOM_101": Location(
            name="Room 101",
            description="The final cell in the Ministry of Love that contains 'the worst thing in the world' — for each prisoner, a different one.",
            ambient_state={
                "worst_fear":     AmbientVector(value=1.0, volatility=0.3, evidence_strength="strong"),
                "personalised_terror": AmbientVector(value=1.0, volatility=0.3, evidence_strength="strong"),
            },
        ),
        "LOC_CHESTNUT_TREE": Location(
            name="Chestnut Tree Café",
            description="The unperson's café where re-educated thought-criminals drink Victory Gin while the telescreen plays.",
            ambient_state={
                "hollow_publicity": AmbientVector(value=0.85, volatility=0.1, evidence_strength="strong"),
            },
        ),
    },

    # ── OBJECTS ────────────────────────────────────────────────────────
    objects={
        "OBJ_DIARY": NarrativeObject(
            id="OBJ_DIARY", name="Winston's Diary",
            location_id="LOC_VICTORY_MANSIONS", owner_id="ENT_WINSTON",
            properties={"state": "kept_in_alcove", "first_entry": "DOWN_WITH_BIG_BROTHER"},
            affordances=[Affordance(action="record_thoughtcrime", target_type="Entity")],
        ),
        "OBJ_PAPERWEIGHT": NarrativeObject(
            id="OBJ_PAPERWEIGHT", name="Glass Coral Paperweight",
            location_id="LOC_CHARRINGTON_ROOM", owner_id="ENT_WINSTON",
            properties={"state": "fragile", "function": "symbol_of_past"},
            affordances=[Affordance(action="symbolise_lost_world", target_type="Entity")],
        ),
        "OBJ_HIDDEN_TELESCREEN": NarrativeObject(
            id="OBJ_HIDDEN_TELESCREEN", name="Hidden Telescreen behind the Engraving",
            location_id="LOC_CHARRINGTON_ROOM", owner_id="ENT_PARTY",
            properties={"state": "active", "concealed_behind": "engraving_of_st_clements"},
            affordances=[Affordance(action="record_dissidents", target_type="Entity")],
        ),
        "OBJ_GOLDSTEINS_BOOK": NarrativeObject(
            id="OBJ_GOLDSTEINS_BOOK", name="The Theory and Practice of Oligarchical Collectivism",
            location_id="LOC_OBRIEN_FLAT", owner_id="ENT_OBRIEN",
            properties={"state": "presented_as_genuine", "actually_authored_by": "INNER_PARTY"},
            affordances=[Affordance(action="entrap_dissident", target_type="Entity")],
        ),
        "OBJ_RAT_CAGE": NarrativeObject(
            id="OBJ_RAT_CAGE", name="Strapped Rat Cage",
            location_id="LOC_ROOM_101", owner_id="ENT_OBRIEN",
            properties={"state": "rats_starving", "intended_target_face": "ENT_WINSTON"},
            affordances=[Affordance(action="break_will", target_type="Entity")],
        ),
    },

    # ── ENTITIES ────────────────────────────────────────────────────────
    entities={
        "ENT_WINSTON": Entity(
            id="ENT_WINSTON", name="Winston Smith",
            location_id="LOC_VICTORY_MANSIONS", status="ill",
            traits={
                "memory_for_truth": TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
                "private_dissent":  TraitVector(value=0.85, inertia=0.8, evidence_strength="strong"),
                "physical_frailty": TraitVector(value=0.7, inertia=0.7, evidence_strength="strong"),
                "courage":          TraitVector(value=0.4, inertia=0.55, evidence_strength="moderate"),
                "love_for_julia":   TraitVector(value=0.0, inertia=0.4, evidence_strength="weak"),
                "loyalty_to_party": TraitVector(value=0.05, inertia=0.5, evidence_strength="weak"),
                "fear_of_rats":     TraitVector(value=0.95, inertia=0.95, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_BIG_BROTHER",
                       perceived_state="hateful symbol of an unbearable regime",
                       confidence=0.95, inertia=0.85, established_at_fabula=1000, evidence_strength="strong"),
                Belief(target_id="ENT_OBRIEN",
                       perceived_state="secretly sympathetic; perhaps a member of the Brotherhood",
                       confidence=0.6, inertia=0.4, established_at_fabula=1000, evidence_strength="moderate"),
                Belief(target_id="ENT_JULIA",
                       perceived_state="zealous Junior Anti-Sex League spy I cannot trust",
                       confidence=0.85, inertia=0.5, established_at_fabula=2000, evidence_strength="strong"),
            ],
            constants=["estranged_from_wife_katharine", "lost_family_in_50s_civil_war"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=3000, triggered_by="EVT_BUYS_DIARY",
                    traits={
                        "courage": TraitVector(value=0.55, inertia=0.6, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=3200, triggered_by="EVT_DOWN_WITH_BIG_BROTHER",
                    traits={
                        "private_dissent": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=5000, triggered_by="EVT_PROLE_DISILLUSION",
                    traits={
                        "private_dissent": TraitVector(value=0.97, inertia=0.85, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=6000, triggered_by="EVT_JULIA_NOTE",
                    beliefs_invalidated=["ENT_JULIA"],
                    beliefs_added=[
                        Belief(target_id="ENT_JULIA",
                               perceived_state="fellow rebel and lover",
                               confidence=0.95, inertia=0.6, established_at_fabula=6000, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=7000, triggered_by="EVT_GOLDEN_COUNTRY",
                    location_id="LOC_GOLDEN_COUNTRY",
                    traits={
                        "love_for_julia": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=10000, triggered_by="EVT_OBRIEN_INVITES",
                    location_id="LOC_OBRIEN_FLAT",
                    traits={
                        "courage": TraitVector(value=0.75, inertia=0.65, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=11000, triggered_by="EVT_HATE_WEEK_SWITCH",
                    traits={
                        "memory_for_truth": TraitVector(value=0.7, inertia=0.85, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=12000, triggered_by="EVT_READ_GOLDSTEIN",
                    traits={
                        "private_dissent": TraitVector(value=0.99, inertia=0.85, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=13000, triggered_by="EVT_ARREST",
                    location_id="LOC_MINILOVE", status="ill",
                    traits={
                        "courage": TraitVector(value=0.55, inertia=0.7, evidence_strength="strong"),
                    },
                    beliefs_invalidated=["ENT_OBRIEN"],
                    beliefs_added=[
                        Belief(target_id="ENT_OBRIEN",
                               perceived_state="Inner-Party Thought Police; my torturer; my interrogator-priest",
                               confidence=1.0, inertia=0.85, established_at_fabula=13000, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=14000, triggered_by="EVT_OBRIEN_TORTURE",
                    traits={
                        "memory_for_truth": TraitVector(value=0.4, inertia=0.85, evidence_strength="strong"),
                        "physical_frailty": TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=15000, triggered_by="EVT_OBRIEN_REVELATION",
                    traits={
                        "private_dissent": TraitVector(value=0.55, inertia=0.85, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=16000, triggered_by="EVT_ROOM_101",
                    location_id="LOC_ROOM_101",
                    traits={
                        "love_for_julia":   TraitVector(value=0.0, inertia=0.85, evidence_strength="strong"),
                        "private_dissent":  TraitVector(value=0.05, inertia=0.85, evidence_strength="strong"),
                        "memory_for_truth": TraitVector(value=0.05, inertia=0.85, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=18000, triggered_by="EVT_CAFE_LOVES_BIG_BROTHER",
                    location_id="LOC_CHESTNUT_TREE",
                    traits={
                        "loyalty_to_party": TraitVector(value=1.0, inertia=0.95, evidence_strength="strong"),
                    },
                    beliefs_invalidated=["ENT_BIG_BROTHER"],
                    beliefs_added=[
                        Belief(target_id="ENT_BIG_BROTHER",
                               perceived_state="he loves me; I love him",
                               confidence=1.0, inertia=0.95, established_at_fabula=18000, evidence_strength="strong"),
                    ]),
            ],
        ),
        "ENT_JULIA": Entity(
            id="ENT_JULIA", name="Julia",
            location_id="LOC_MINITRUE", status="healthy",
            traits={
                "private_hedonism": TraitVector(value=0.9, inertia=0.8, evidence_strength="strong"),
                "outward_orthodoxy": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "political_apathy": TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
                "vitality":         TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "love_for_winston": TraitVector(value=0.0, inertia=0.4, evidence_strength="weak"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=6000, triggered_by="EVT_JULIA_NOTE",
                    traits={
                        "love_for_winston": TraitVector(value=0.7, inertia=0.55, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=7000, triggered_by="EVT_GOLDEN_COUNTRY",
                    location_id="LOC_GOLDEN_COUNTRY",
                    traits={
                        "love_for_winston": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=13000, triggered_by="EVT_ARREST",
                    status="ill", location_id="LOC_MINILOVE"),
                EntityStateSnapshot(fabula_time=17000, triggered_by="EVT_FINAL_ENCOUNTER",
                    location_id="LOC_CHESTNUT_TREE",
                    traits={
                        "vitality":         TraitVector(value=0.3, inertia=0.75, evidence_strength="strong"),
                        "love_for_winston": TraitVector(value=0.0, inertia=0.7, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_OBRIEN": Entity(
            id="ENT_OBRIEN", name="O'Brien",
            location_id="LOC_OBRIEN_FLAT", status="healthy",
            traits={
                "intellect":           TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "doublethink_mastery": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "cruelty":             TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
                "ideological_certainty": TraitVector(value=0.95, inertia=0.9, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_PARTY",
                       perceived_state="power is the end, not the means",
                       confidence=1.0, inertia=0.95, established_at_fabula=1000, evidence_strength="strong"),
            ],
        ),
        "ENT_CHARRINGTON": Entity(
            id="ENT_CHARRINGTON", name="Mr Charrington",
            location_id="LOC_PROLE_DISTRICT", status="healthy",
            traits={
                "performed_kindliness": TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
                "covert_vigilance":     TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "deception":            TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=13000, triggered_by="EVT_ARREST",
                    traits={
                        "performed_kindliness": TraitVector(value=0.05, inertia=0.85, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_PARSONS": Entity(
            id="ENT_PARSONS", name="Parsons",
            location_id="LOC_VICTORY_MANSIONS", status="healthy",
            traits={
                "ideological_enthusiasm": TraitVector(value=0.95, inertia=0.9, evidence_strength="strong"),
                "stupidity":              TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
                "uncritical_loyalty":     TraitVector(value=0.95, inertia=0.9, evidence_strength="strong"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=13500, triggered_by="EVT_PARSONS_DENOUNCED",
                    location_id="LOC_MINILOVE", status="ill"),
            ],
        ),
        "ENT_KATHARINE": Entity(
            id="ENT_KATHARINE", name="Katharine",
            location_id="LOC_VICTORY_MANSIONS", status="healthy",
            traits={
                "ideological_frigidity": TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
                "duty_to_party":         TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
            },
            beliefs=[],
        ),
        "ENT_BIG_BROTHER": Entity(
            id="ENT_BIG_BROTHER", name="Big Brother",
            location_id="LOC_MINILOVE", status="healthy",
            traits={
                "iconic_presence":  TraitVector(value=1.0, inertia=0.95, evidence_strength="strong"),
                "ontological_status_uncertain": TraitVector(value=0.95, inertia=0.95, evidence_strength="moderate"),
            },
            beliefs=[],
            constants=["face_on_every_poster", "may_or_may_not_exist"],
            state_timeline=[
                EntityStateSnapshot(
                    fabula_time=3200, triggered_by="EVT_DOWN_WITH_BIG_BROTHER",
                    location_id="LOC_MINILOVE",
                    traits={
                        "iconic_presence": TraitVector(value=1.0, inertia=0.97, evidence_strength="strong"),
                        "object_of_thoughtcrime": TraitVector(value=0.6, inertia=0.5, evidence_strength="moderate"),
                    },
                ),
                EntityStateSnapshot(
                    fabula_time=18000, triggered_by="EVT_CAFE_LOVES_BIG_BROTHER",
                    location_id="LOC_MINILOVE",
                    traits={
                        "iconic_presence": TraitVector(value=1.0, inertia=0.99, evidence_strength="strong"),
                        "object_of_love": TraitVector(value=1.0, inertia=0.95, evidence_strength="strong"),
                    },
                ),
            ],
        ),
        "ENT_GOLDSTEIN": Entity(
            id="ENT_GOLDSTEIN", name="Emmanuel Goldstein",
            location_id="LOC_MINILOVE", status="healthy",
            traits={
                "iconic_villainy": TraitVector(value=1.0, inertia=0.95, evidence_strength="strong"),
                "ontological_status_uncertain": TraitVector(value=0.95, inertia=0.95, evidence_strength="moderate"),
            },
            beliefs=[],
            constants=["enemy_of_two_minutes_hate", "perhaps_invented_by_party"],
        ),
        "ENT_PARTY": Entity(
            id="ENT_PARTY", name="The Inner Party",
            location_id="LOC_MINILOVE", status="healthy",
            traits={
                "totalitarian_will":    TraitVector(value=1.0, inertia=0.95, evidence_strength="strong"),
                "doctrinal_flexibility": TraitVector(value=0.95, inertia=0.9, evidence_strength="strong"),
            },
            beliefs=[],
            constants=["seeks_power_for_its_own_sake", "rewrites_the_past_continually"],
            state_timeline=[
                EntityStateSnapshot(
                    fabula_time=13000, triggered_by="EVT_ARREST",
                    location_id="LOC_MINILOVE",
                    traits={
                        "totalitarian_will": TraitVector(value=1.0, inertia=0.97, evidence_strength="strong"),
                        "panoptic_grip": TraitVector(value=0.95, inertia=0.95, evidence_strength="strong"),
                    },
                ),
                EntityStateSnapshot(
                    fabula_time=16000, triggered_by="EVT_ROOM_101",
                    location_id="LOC_ROOM_101",
                    traits={
                        "totalitarian_will": TraitVector(value=1.0, inertia=0.99, evidence_strength="strong"),
                        "panoptic_grip": TraitVector(value=1.0, inertia=0.97, evidence_strength="strong"),
                        "interior_conquest": TraitVector(value=1.0, inertia=0.95, evidence_strength="strong"),
                    },
                ),
            ],
        ),
    },

    # ── EVENTS ──────────────────────────────────────────────────────────
    events=[
        EventNode(id="EVT_OPENING_DIARY_DATE", fabula_time=1000, syuzhet_index=1,
                  event_type="choice", actor_ids=["ENT_WINSTON"], target_ids=["ENT_WINSTON"],
                  description="On a date Winston believes to be 4 April 1984 he opens the new diary in the alcove out of the telescreen's sight."),
        EventNode(id="EVT_WORK_AT_MINITRUE", fabula_time=1500, syuzhet_index=2,
                  event_type="choice", actor_ids=["ENT_WINSTON"], target_ids=["ENT_PARTY"],
                  description="Winston rewrites yesterday's Times to bring history into line with the Party's current claims and drops the originals down a memory hole."),
        EventNode(id="EVT_BUYS_DIARY", fabula_time=3000, syuzhet_index=3,
                  event_type="choice", actor_ids=["ENT_WINSTON"], target_ids=["ENT_CHARRINGTON"],
                  description="In a prole district Winston buys a blank diary from Mr Charrington's antiques shop — a thoughtcrime in itself."),
        EventNode(id="EVT_DOWN_WITH_BIG_BROTHER", fabula_time=3200, syuzhet_index=4,
                  event_type="choice", actor_ids=["ENT_WINSTON"], target_ids=["ENT_BIG_BROTHER"],
                  description="In the diary Winston writes 'DOWN WITH BIG BROTHER' over and over, knowing he is now a thought-criminal."),
        EventNode(id="EVT_SUSPECTS_JULIA", fabula_time=4000, syuzhet_index=6,
                  event_type="outcome", actor_ids=["ENT_WINSTON"], target_ids=["ENT_JULIA"],
                  description="At the Ministry Winston watches the dark-haired Julia and develops an intense hatred, suspecting her of being a Thought Police informer."),
        EventNode(id="EVT_PROLE_DISILLUSION", fabula_time=5000, syuzhet_index=7,
                  event_type="outcome", actor_ids=["ENT_WINSTON"], target_ids=[],
                  description="Wandering the prole quarter Winston realises that the proles have no political consciousness whatsoever; revolution will not come from them in any foreseeable time."),
        EventNode(id="EVT_JULIA_NOTE", fabula_time=6000, syuzhet_index=9,
                  event_type="choice", actor_ids=["ENT_JULIA"], target_ids=["ENT_WINSTON"],
                  description="Julia engineers a fall in the corridor and slips Winston a note reading 'I love you'."),
        EventNode(id="EVT_GOLDEN_COUNTRY", fabula_time=7000, syuzhet_index=10,
                  event_type="choice", actor_ids=["ENT_WINSTON", "ENT_JULIA"], target_ids=[],
                  description="Winston and Julia escape to a clearing in the country and consummate the affair, with Julia recasting it as a deliberately political act."),
        EventNode(id="EVT_RENT_CHARRINGTON_ROOM", fabula_time=8000, syuzhet_index=12,
                  event_type="choice", actor_ids=["ENT_WINSTON"], target_ids=["ENT_CHARRINGTON"],
                  description="Winston rents the room above Charrington's shop, taking comfort in its apparent freedom from telescreens."),
        EventNode(id="EVT_OBRIEN_INVITES", fabula_time=10000, syuzhet_index=14,
                  event_type="choice", actor_ids=["ENT_OBRIEN"], target_ids=["ENT_WINSTON"],
                  description="O'Brien invites Winston to his Inner-Party flat under pretext of lending him a Newspeak dictionary; in person he 'admits' to membership of Goldstein's Brotherhood and undertakes to send the book."),
        EventNode(id="EVT_HATE_WEEK_SWITCH", fabula_time=11000, syuzhet_index=17,
                  event_type="outcome", actor_ids=["ENT_PARTY"], target_ids=["ENT_WINSTON"],
                  description="At the height of Hate Week the speaker mid-sentence switches the enemy from Eurasia to Eastasia; Winston is recalled to revise mountains of records."),
        EventNode(id="EVT_READ_GOLDSTEIN", fabula_time=12000, syuzhet_index=18,
                  event_type="outcome", actor_ids=["ENT_WINSTON", "ENT_JULIA"], target_ids=[],
                  description="In the rented room Winston reads aloud from Goldstein's book, which appears to confirm the analysis of the Party that Winston has been groping toward."),
        EventNode(id="EVT_ARREST", fabula_time=13000, syuzhet_index=21,
                  event_type="outcome", actor_ids=["ENT_CHARRINGTON", "ENT_PARTY"], target_ids=["ENT_WINSTON", "ENT_JULIA"],
                  description="The hidden telescreen behind the engraving speaks; Charrington reveals himself as Thought Police; Winston and Julia are taken to the Ministry of Love."),
        EventNode(id="EVT_PARSONS_DENOUNCED", fabula_time=13500, syuzhet_index=23,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_PARSONS"],
                  description="In the holding cells Winston meets Parsons, denounced by his own seven-year-old daughter for muttering 'Down with Big Brother' in his sleep."),
        EventNode(id="EVT_OBRIEN_TORTURE", fabula_time=14000, syuzhet_index=24,
                  event_type="outcome", actor_ids=["ENT_OBRIEN"], target_ids=["ENT_WINSTON"],
                  description="Across many sessions O'Brien tortures Winston with electricity and starvation, demanding he see four fingers when O'Brien holds up five."),
        EventNode(id="EVT_OBRIEN_REVELATION", fabula_time=15000, syuzhet_index=25,
                  event_type="outcome", actor_ids=["ENT_OBRIEN"], target_ids=["ENT_WINSTON"],
                  description="O'Brien tells Winston that Goldstein's book was written collaboratively by the Inner Party itself, that the Brotherhood may not exist, and that the Party seeks power purely for its own sake."),
        EventNode(id="EVT_ROOM_101", fabula_time=16000, syuzhet_index=26,
                  event_type="outcome", actor_ids=["ENT_OBRIEN"], target_ids=["ENT_WINSTON"],
                  description="In Room 101 the rat cage is strapped to Winston's face; he begs that it be done to Julia instead, and so betrays her."),
        EventNode(id="EVT_FINAL_ENCOUNTER", fabula_time=17000, syuzhet_index=27,
                  event_type="outcome", actor_ids=["ENT_WINSTON", "ENT_JULIA"], target_ids=[],
                  description="Released and indifferent, Winston meets Julia by chance in the park; they confess they betrayed each other and that nothing remains."),
        EventNode(id="EVT_CAFE_LOVES_BIG_BROTHER", fabula_time=18000, syuzhet_index=28,
                  event_type="outcome", actor_ids=["ENT_WINSTON"], target_ids=["ENT_BIG_BROTHER"],
                  description="At the Chestnut Tree Café a news bulletin announces a great victory in Africa; Winston, gazing at Big Brother's face, finally loves him."),

        # ── UTTERANCES (on-page speech-acts) ──
        EventNode(id='EVT_UTT_DIARY_DOWN_WITH_BB', event_type='utterance',
                  description="Winston commits the founding thoughtcrime by writing 'DOWN WITH BIG BROTHER' over and over in the diary.",
                  content="DOWN WITH BIG BROTHER. DOWN WITH BIG BROTHER. DOWN WITH BIG BROTHER.",
                  speaker_id='ENT_WINSTON', addressee_ids=['OBJ_DIARY'], actor_ids=['ENT_WINSTON'],
                  target_ids=['ENT_BIG_BROTHER', 'ENT_PARTY'],
                  via_channel_id='CHN_WINSTON_DIARY', truth_value='performative',
                  fabula_time=3200, syuzhet_index=5),
        EventNode(id='EVT_UTT_JULIA_LOVE_NOTE', event_type='utterance',
                  description="Julia stages a fall in the corridor and presses a folded note into Winston's hand.",
                  content="I love you.",
                  speaker_id='ENT_JULIA', addressee_ids=['ENT_WINSTON'], actor_ids=['ENT_JULIA'],
                  target_ids=['ENT_WINSTON'],
                  via_channel_id=None, truth_value='true',
                  fabula_time=6000, syuzhet_index=8),
        EventNode(id='EVT_UTT_OBRIEN_BROTHERHOOD_PITCH', event_type='utterance',
                  description="In his Inner-Party flat O'Brien declares himself a member of the Brotherhood and undertakes to deliver Goldstein's book — a false-flag recruitment.",
                  content="We are the dead. You will join the Brotherhood, and I shall send you the book — the book by Goldstein.",
                  speaker_id='ENT_OBRIEN', addressee_ids=['ENT_WINSTON'], actor_ids=['ENT_OBRIEN'],
                  target_ids=['ENT_GOLDSTEIN', 'OBJ_GOLDSTEINS_BOOK'],
                  via_channel_id=None, truth_value='false',
                  fabula_time=10100, syuzhet_index=11),
        EventNode(id='EVT_UTT_HATE_WEEK_ENEMY_SWITCH', event_type='utterance',
                  description="Mid-sentence in the Hate Week broadcast the Party speaker pivots Oceania's enemy from Eurasia to Eastasia.",
                  content="Oceania has always been at war with Eastasia.",
                  speaker_id='ENT_PARTY', addressee_ids=['ENT_WINSTON', 'ENT_JULIA', 'ENT_PARSONS'], actor_ids=['ENT_PARTY'],
                  target_ids=[],
                  via_channel_id='CHN_TELESCREEN_BROADCAST', truth_value='false',
                  fabula_time=11000, syuzhet_index=13),
        EventNode(id='EVT_UTT_GOLDSTEIN_READ_ALOUD', event_type='utterance',
                  description="In the Charrington room Winston reads chapters of Goldstein's book aloud to Julia.",
                  content="War is Peace. Freedom is Slavery. Ignorance is Strength. The Party can be overthrown only if the proles become conscious.",
                  speaker_id='ENT_WINSTON', addressee_ids=['ENT_JULIA'], actor_ids=['ENT_WINSTON'],
                  target_ids=['ENT_PARTY', 'ENT_GOLDSTEIN', 'OBJ_GOLDSTEINS_BOOK'],
                  via_channel_id='CHN_GOLDSTEIN_BOOK', truth_value='true',
                  fabula_time=12100, syuzhet_index=15),
        EventNode(id='EVT_UTT_HIDDEN_TELESCREEN_REVEALS', event_type='utterance',
                  description="The concealed telescreen behind the engraving suddenly speaks, signalling that the room has been bugged the entire time.",
                  content="You are the dead. Stand out in the middle of the room. Hands behind your heads.",
                  speaker_id='ENT_PARTY', addressee_ids=['ENT_WINSTON', 'ENT_JULIA'], actor_ids=['ENT_PARTY'],
                  target_ids=['EVT_ARREST'],
                  via_channel_id='CHN_HIDDEN_TELESCREEN_SURVEILLANCE', truth_value='performative',
                  fabula_time=13000, syuzhet_index=16),
        EventNode(id='EVT_UTT_OBRIEN_REVEALS_TRUTH', event_type='utterance',
                  description="In the Ministry of Love O'Brien tells Winston the Brotherhood may be a Party fiction, that he co-authored Goldstein's book, and that the Party seeks power purely for its own sake.",
                  content="The Party seeks power entirely for its own sake. You will never know whether the Brotherhood exists. The book — I helped to write it.",
                  speaker_id='ENT_OBRIEN', addressee_ids=['ENT_WINSTON'], actor_ids=['ENT_OBRIEN'],
                  target_ids=['ENT_PARTY', 'ENT_GOLDSTEIN', 'OBJ_GOLDSTEINS_BOOK'],
                  via_channel_id=None, truth_value='true',
                  fabula_time=15000, syuzhet_index=19),
        EventNode(id='EVT_UTT_WINSTON_BETRAYS_JULIA', event_type='utterance',
                  description="With the rat cage at his face Winston cracks and demands the torture be transferred to Julia.",
                  content="Do it to Julia! Not me! Julia! I don't care what you do to her. Tear her face off, strip her to the bones. Not me! Julia!",
                  speaker_id='ENT_WINSTON', addressee_ids=['ENT_OBRIEN'], actor_ids=['ENT_WINSTON'],
                  target_ids=['ENT_JULIA'],
                  via_channel_id=None, truth_value='performative',
                  fabula_time=16000, syuzhet_index=20),
        EventNode(id='EVT_UTT_CAFE_VICTORY_BULLETIN', event_type='utterance',
                  description="At the Chestnut Tree Café the telescreen news bulletin announces a great victory for Oceania in Africa.",
                  content="Glorious victory on the African front — the campaign has been brought to a swift and triumphant conclusion.",
                  speaker_id='ENT_PARTY', addressee_ids=['ENT_WINSTON'], actor_ids=['ENT_PARTY'],
                  target_ids=[],
                  via_channel_id='CHN_TELESCREEN_BROADCAST', truth_value='unknown',
                  fabula_time=18000, syuzhet_index=22),
    ],

    # ── CAUSAL TOPOLOGY ────────────────────────────────────────────────
    causal_topology=[
        # ── chain_reaction ──
        CausalEdge(source_id="EVT_OPENING_DIARY_DATE", target_id="EVT_BUYS_DIARY",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1000, propagation_delay=2000),
        CausalEdge(source_id="EVT_BUYS_DIARY", target_id="EVT_DOWN_WITH_BIG_BROTHER",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=3000, propagation_delay=200),
        CausalEdge(source_id="EVT_WORK_AT_MINITRUE", target_id="EVT_SUSPECTS_JULIA",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1500, propagation_delay=2500),
        CausalEdge(source_id="EVT_BUYS_DIARY", target_id="EVT_PROLE_DISILLUSION",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=3000, propagation_delay=2000),
        CausalEdge(source_id="EVT_SUSPECTS_JULIA", target_id="EVT_JULIA_NOTE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=4000, propagation_delay=2000),
        CausalEdge(source_id="EVT_JULIA_NOTE", target_id="EVT_GOLDEN_COUNTRY",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=6000, propagation_delay=1000),
        CausalEdge(source_id="EVT_GOLDEN_COUNTRY", target_id="EVT_RENT_CHARRINGTON_ROOM",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7000, propagation_delay=1000),
        CausalEdge(source_id="EVT_RENT_CHARRINGTON_ROOM", target_id="EVT_READ_GOLDSTEIN",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=8000, propagation_delay=4000),
        CausalEdge(source_id="EVT_DOWN_WITH_BIG_BROTHER", target_id="EVT_OBRIEN_INVITES",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=3200, propagation_delay=6800),
        CausalEdge(source_id="EVT_OBRIEN_INVITES", target_id="EVT_READ_GOLDSTEIN",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=8.0, fabula_time=10000, propagation_delay=2000),
        CausalEdge(source_id="EVT_WORK_AT_MINITRUE", target_id="EVT_HATE_WEEK_SWITCH",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=1500, propagation_delay=9500),
        CausalEdge(source_id="EVT_RENT_CHARRINGTON_ROOM", target_id="EVT_ARREST",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=10.0, fabula_time=8000, propagation_delay=5000),
        CausalEdge(source_id="EVT_OBRIEN_INVITES", target_id="EVT_ARREST",
                   causality_type="chain_reaction", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=10000, propagation_delay=3000),
        CausalEdge(source_id="EVT_ARREST", target_id="EVT_PARSONS_DENOUNCED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=13000, propagation_delay=500),
        CausalEdge(source_id="EVT_ARREST", target_id="EVT_OBRIEN_TORTURE",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=13000, propagation_delay=1000),
        CausalEdge(source_id="EVT_OBRIEN_TORTURE", target_id="EVT_OBRIEN_REVELATION",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=14000, propagation_delay=1000),
        CausalEdge(source_id="EVT_OBRIEN_REVELATION", target_id="EVT_ROOM_101",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=15000, propagation_delay=1000),
        CausalEdge(source_id="EVT_ROOM_101", target_id="EVT_FINAL_ENCOUNTER",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=16000, propagation_delay=1000),
        CausalEdge(source_id="EVT_FINAL_ENCOUNTER", target_id="EVT_CAFE_LOVES_BIG_BROTHER",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=17000, propagation_delay=1000),

        # ── mutation ──
        CausalEdge(source_id="EVT_BUYS_DIARY", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=3000,
                   trait_target="courage", trait_delta=0.15),
        CausalEdge(source_id="EVT_DOWN_WITH_BIG_BROTHER", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=3200,
                   trait_target="private_dissent", trait_delta=0.4),
        CausalEdge(source_id="EVT_GOLDEN_COUNTRY", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=7000,
                   trait_target="love_for_julia", trait_delta=0.85),
        CausalEdge(source_id="EVT_GOLDEN_COUNTRY", target_id="ENT_JULIA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=7000,
                   trait_target="love_for_winston", trait_delta=0.7),
        CausalEdge(source_id="EVT_OBRIEN_INVITES", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=10000,
                   trait_target="courage", trait_delta=0.2),
        CausalEdge(source_id="EVT_ARREST", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=13000,
                   trait_target="physical_frailty", trait_delta=0.2),
        CausalEdge(source_id="EVT_OBRIEN_TORTURE", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=14000,
                   trait_target="memory_for_truth", trait_delta=-0.5),
        CausalEdge(source_id="EVT_OBRIEN_REVELATION", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=15000,
                   trait_target="private_dissent", trait_delta=-0.4),
        CausalEdge(source_id="EVT_ROOM_101", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=16000,
                   trait_target="love_for_julia", trait_delta=-0.85),
        CausalEdge(source_id="EVT_ROOM_101", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=16000,
                   trait_target="private_dissent", trait_delta=-0.4),
        CausalEdge(source_id="EVT_CAFE_LOVES_BIG_BROTHER", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=18000,
                   trait_target="loyalty_to_party", trait_delta=0.95),
        CausalEdge(source_id="EVT_PARSONS_DENOUNCED", target_id="ENT_PARSONS",
                   causality_type="mutation", mechanism="social", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=13500,
                   trait_target="ideological_enthusiasm", trait_delta=0.05),
        CausalEdge(source_id="EVT_FINAL_ENCOUNTER", target_id="ENT_JULIA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=17000,
                   trait_target="vitality", trait_delta=-0.55),
        CausalEdge(source_id="EVT_ARREST", target_id="ENT_CHARRINGTON",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=13000,
                   trait_target="performed_kindliness", trait_delta=-0.8),
        CausalEdge(source_id="EVT_ARREST", target_id="ENT_PARTY",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=13000,
                   trait_target="panoptic_grip", trait_delta=0.1),
        CausalEdge(source_id="EVT_ROOM_101", target_id="ENT_PARTY",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=16000,
                   trait_target="interior_conquest", trait_delta=0.5),
        CausalEdge(source_id="EVT_PROLE_DISILLUSION", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=5000,
                   trait_target="private_dissent", trait_delta=0.2),
        CausalEdge(source_id="EVT_HATE_WEEK_SWITCH", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=11000,
                   trait_target="memory_for_truth", trait_delta=-0.2),
        CausalEdge(source_id="EVT_READ_GOLDSTEIN", target_id="ENT_WINSTON",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=6.0, fabula_time=12000,
                   trait_target="private_dissent", trait_delta=0.25),

        # ── mutation_social ──
        CausalEdge(source_id="EVT_JULIA_NOTE", target_id="ENT_WINSTON",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=6000,
                   trait_target="affinity", trait_delta=0.95, rel_counterpart_id="ENT_JULIA"),
        CausalEdge(source_id="EVT_JULIA_NOTE", target_id="ENT_JULIA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=6000,
                   trait_target="affinity", trait_delta=0.85, rel_counterpart_id="ENT_WINSTON"),
        CausalEdge(source_id="EVT_OBRIEN_INVITES", target_id="ENT_WINSTON",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=10000,
                   trait_target="affinity", trait_delta=0.7, rel_counterpart_id="ENT_OBRIEN"),
        CausalEdge(source_id="EVT_ARREST", target_id="ENT_WINSTON",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=10.0, fabula_time=13000,
                   trait_target="affinity", trait_delta=-1.0, rel_counterpart_id="ENT_CHARRINGTON"),
        CausalEdge(source_id="EVT_OBRIEN_TORTURE", target_id="ENT_WINSTON",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=14000,
                   trait_target="fear", trait_delta=0.95, rel_counterpart_id="ENT_OBRIEN"),
        CausalEdge(source_id="EVT_OBRIEN_TORTURE", target_id="ENT_WINSTON",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=14000,
                   trait_target="power_dynamic", trait_delta=-0.95, rel_counterpart_id="ENT_OBRIEN"),
        CausalEdge(source_id="EVT_ROOM_101", target_id="ENT_WINSTON",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=10.0, fabula_time=16000,
                   trait_target="affinity", trait_delta=-0.95, rel_counterpart_id="ENT_JULIA"),
        CausalEdge(source_id="EVT_ROOM_101", target_id="ENT_JULIA",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=10.0, fabula_time=16000,
                   trait_target="affinity", trait_delta=-0.95, rel_counterpart_id="ENT_WINSTON"),
        CausalEdge(source_id="EVT_CAFE_LOVES_BIG_BROTHER", target_id="ENT_WINSTON",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=18000,
                   trait_target="affinity", trait_delta=1.0, rel_counterpart_id="ENT_BIG_BROTHER"),

        # ── affordance_gate ──
        CausalEdge(source_id="OBJ_DIARY", target_id="EVT_DOWN_WITH_BIG_BROTHER",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=3200),
        CausalEdge(source_id="OBJ_HIDDEN_TELESCREEN", target_id="EVT_ARREST",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="strong",
                   causal_force=10.0, fabula_time=13000),
        CausalEdge(source_id="OBJ_GOLDSTEINS_BOOK", target_id="EVT_READ_GOLDSTEIN",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="strong",
                   causal_force=8.0, fabula_time=12000),
        CausalEdge(source_id="OBJ_RAT_CAGE", target_id="EVT_ROOM_101",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=16000),
        CausalEdge(source_id="OBJ_PAPERWEIGHT", target_id="EVT_ARREST",
                   causality_type="affordance_gate", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=13000),

        # ── ambient_propagation ──
        CausalEdge(source_id="LOC_MINITRUE", target_id="ENT_WINSTON",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="strong",
                   causal_force=5.0, fabula_time=1500),
        CausalEdge(source_id="LOC_VICTORY_MANSIONS", target_id="ENT_WINSTON",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="strong",
                   causal_force=5.0, fabula_time=1000),
        CausalEdge(source_id="LOC_MINILOVE", target_id="ENT_WINSTON",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=13000),
        CausalEdge(source_id="LOC_GOLDEN_COUNTRY", target_id="ENT_JULIA",
                   causality_type="ambient_propagation", mechanism="emotional", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=7000),

        # ── WORLD_ → Event ──
        CausalEdge(source_id="WORLD_INGSOC", target_id="EVT_WORK_AT_MINITRUE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500),
        CausalEdge(source_id="WORLD_INGSOC", target_id="EVT_OBRIEN_REVELATION",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=15000),
        CausalEdge(source_id="WORLD_INGSOC", target_id="EVT_OBRIEN_TORTURE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=14000),
        CausalEdge(source_id="WORLD_INGSOC", target_id="EVT_PARSONS_DENOUNCED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=13500),
        CausalEdge(source_id="WORLD_PERPETUAL_WAR", target_id="EVT_HATE_WEEK_SWITCH",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=11000),
        CausalEdge(source_id="WORLD_PERPETUAL_WAR", target_id="EVT_WORK_AT_MINITRUE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1500),
        CausalEdge(source_id="WORLD_PERPETUAL_WAR", target_id="EVT_CAFE_LOVES_BIG_BROTHER",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=18000),
        CausalEdge(source_id="WORLD_PANOPTICON", target_id="EVT_ARREST",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=10.0, fabula_time=13000),
        CausalEdge(source_id="WORLD_PANOPTICON", target_id="EVT_OPENING_DIARY_DATE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=5.0, fabula_time=1000),
        CausalEdge(source_id="WORLD_PANOPTICON", target_id="EVT_PROLE_DISILLUSION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=5000),

        # ── Utterance wiring (connect orphan EVT_UTT_ events to causal spine) ──
        CausalEdge(source_id="EVT_UTT_DIARY_DOWN_WITH_BB", target_id="EVT_OBRIEN_INVITES",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=3200, propagation_delay=6800),
        CausalEdge(source_id="EVT_UTT_JULIA_LOVE_NOTE", target_id="EVT_GOLDEN_COUNTRY",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=6000, propagation_delay=1000),
        CausalEdge(source_id="EVT_UTT_OBRIEN_BROTHERHOOD_PITCH", target_id="EVT_READ_GOLDSTEIN",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=7.0, fabula_time=10100, propagation_delay=1900),
        CausalEdge(source_id="EVT_UTT_HATE_WEEK_ENEMY_SWITCH", target_id="EVT_HATE_WEEK_SWITCH",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=11000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_GOLDSTEIN_READ_ALOUD", target_id="EVT_ARREST",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=6.0, fabula_time=12100, propagation_delay=900),
        CausalEdge(source_id="EVT_UTT_HIDDEN_TELESCREEN_REVEALS", target_id="EVT_ARREST",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=10.0, fabula_time=13000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_OBRIEN_REVEALS_TRUTH", target_id="EVT_ROOM_101",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=15000, propagation_delay=1000),
        CausalEdge(source_id="EVT_UTT_WINSTON_BETRAYS_JULIA", target_id="EVT_FINAL_ENCOUNTER",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=16000, propagation_delay=1000),
        CausalEdge(source_id="EVT_UTT_CAFE_VICTORY_BULLETIN", target_id="EVT_CAFE_LOVES_BIG_BROTHER",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=18000, propagation_delay=0),
    ],

    # ── SPATIAL TOPOLOGY ────────────────────────────────────────────────
    spatial_topology=[
        SpatialEdge(source_id="LOC_VICTORY_MANSIONS", target_id="LOC_MINITRUE"),
        SpatialEdge(source_id="LOC_MINITRUE", target_id="LOC_VICTORY_MANSIONS"),
        SpatialEdge(source_id="LOC_VICTORY_MANSIONS", target_id="LOC_PROLE_DISTRICT"),
        SpatialEdge(source_id="LOC_PROLE_DISTRICT", target_id="LOC_CHARRINGTON_ROOM"),
        SpatialEdge(source_id="LOC_PROLE_DISTRICT", target_id="LOC_GOLDEN_COUNTRY"),
        SpatialEdge(source_id="LOC_MINITRUE", target_id="LOC_OBRIEN_FLAT"),
        SpatialEdge(source_id="LOC_VICTORY_MANSIONS", target_id="LOC_MINILOVE"),
        SpatialEdge(source_id="LOC_MINILOVE", target_id="LOC_ROOM_101"),
        SpatialEdge(source_id="LOC_MINILOVE", target_id="LOC_CHESTNUT_TREE"),
    ],

    # ── INFORMATION TOPOLOGY ────────────────────────────────────────────
    # Only standing communication capabilities live here. One-shot speech-acts
    # (Julia's note, O'Brien's recruitment pitch, his final ideological
    # confession, Winston's Room-101 betrayal) are modelled as utterance events
    # with via_channel_id=None — see EVT_UTT_*.
    channels={
        # Winston's secret diary — a standing one-way thoughtcrime conduit between
        # his private mind and the page, used across many entries until arrest.
        'CHN_WINSTON_DIARY': Channel(
            id='CHN_WINSTON_DIARY',
            name="Winston's Secret Diary",
            medium='diary',
            participant_ids=['ENT_WINSTON', 'OBJ_DIARY'],
            directionality='simplex',
            intelligibility={},
            established_at_fabula=3200,
            terminated_at_fabula=13000,
            evidence_strength='strong',
        ),
        # Goldstein's book — an underground samizdat that broadcasts a forbidden
        # analysis of the Party to its readers across multiple reading sessions.
        'CHN_GOLDSTEIN_BOOK': Channel(
            id='CHN_GOLDSTEIN_BOOK',
            name="The Theory and Practice of Oligarchical Collectivism",
            medium='samizdat_text',
            participant_ids=['OBJ_GOLDSTEINS_BOOK', 'ENT_WINSTON', 'ENT_JULIA'],
            directionality='broadcast',
            intelligibility={},
            established_at_fabula=12000,
            terminated_at_fabula=13000,
            evidence_strength='strong',
        ),
        # The Party's telescreen broadcast network — the ubiquitous one-to-many
        # capability that carries Hate Week, news bulletins and Big Brother's face
        # throughout the novel.
        'CHN_TELESCREEN_BROADCAST': Channel(
            id='CHN_TELESCREEN_BROADCAST',
            name="Telescreen Broadcast Network",
            medium='telescreen_broadcast',
            participant_ids=['ENT_PARTY', 'ENT_WINSTON', 'ENT_JULIA', 'ENT_PARSONS', 'ENT_BIG_BROTHER'],
            directionality='broadcast',
            intelligibility={},
            established_at_fabula=1000,
            terminated_at_fabula=None,
            evidence_strength='strong',
        ),
        # The hidden telescreen behind the engraving in Charrington's room — a
        # covert one-way surveillance pipeline whose existence Winston and Julia
        # cannot perceive (intelligibility 0) until it springs the trap.
        'CHN_HIDDEN_TELESCREEN_SURVEILLANCE': Channel(
            id='CHN_HIDDEN_TELESCREEN_SURVEILLANCE',
            name="Charrington-Room Concealed Surveillance",
            medium='surveillance',
            participant_ids=['OBJ_HIDDEN_TELESCREEN', 'ENT_PARTY', 'ENT_WINSTON', 'ENT_JULIA'],
            directionality='simplex',
            intelligibility={'ENT_WINSTON': 0.0, 'ENT_JULIA': 0.0},
            established_at_fabula=8000,
            terminated_at_fabula=13000,
            evidence_strength='strong',
        ),
        # Charrington's standing Thought-Police reporting line — the classified
        # back-channel through which surveillance of the rented room is collated.
        'CHN_CHARRINGTON_REPORTS': Channel(
            id='CHN_CHARRINGTON_REPORTS',
            name="Charrington → Thought Police Reports",
            medium='classified_pipeline',
            participant_ids=['ENT_CHARRINGTON', 'ENT_PARTY'],
            directionality='simplex',
            intelligibility={},
            established_at_fabula=3000,
            terminated_at_fabula=13000,
            evidence_strength='strong',
        ),
    },

    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_INGSOC": GlobalTrait(
            id="WORLD_INGSOC",
            name="Ingsoc / Inner-Party Totalitarianism",
            description="The ideology and apparatus of Oceania's English Socialism: doublethink, the mutability of the past, the seizure of power as an end in itself. Operates as a maximally high-magnitude common-cause parent over every act of revision, denunciation, and torture in the story.",
            category="governance",
            magnitude=TraitVector(value=1.0, inertia=0.95, evidence_strength="strong"),
            affected_domains=["social", "psychological", "epistemic"],
        ),
        "WORLD_PERPETUAL_WAR": GlobalTrait(
            id="WORLD_PERPETUAL_WAR",
            name="Perpetual War Between the Three Super-States",
            description="The endless rotating war between Oceania, Eurasia and Eastasia that consumes the surplus product, justifies austerity, and licenses the mid-sentence revision of who is friend and who is enemy. The hidden engine of Hate Week and of Winston's revisionist labour.",
            category="economy",
            magnitude=TraitVector(value=0.95, inertia=0.9, evidence_strength="strong"),
            affected_domains=["social"],
        ),
        "WORLD_PANOPTICON": GlobalTrait(
            id="WORLD_PANOPTICON",
            name="Panoptic Surveillance State",
            description="Telescreens, hidden microphones, the children's spy clubs, and the planted Charringtons of the Thought Police. Operates as the ambient-but-targeted apparatus that both motivates Winston's careful concealment and makes its breakdown inevitable.",
            category="cosmology",
            magnitude=TraitVector(value=0.95, inertia=0.95, evidence_strength="strong"),
            affected_domains=["epistemic", "social"],
        ),
    },

    # ── SOCIAL TOPOLOGY ────────────────────────────────────────────────
    social_topology=[
        # Winston ↔ Julia — the doomed affair.
        RelationshipEdge(
            source_entity_id="ENT_WINSTON", target_entity_id="ENT_JULIA",
            metrics={
                "affinity": RelationshipMetric(value=-0.5, inertia=0.45, evidence_strength="strong", last_updated_fabula=4000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_JULIA", target_entity_id="ENT_WINSTON",
            metrics={
                "affinity": RelationshipMetric(value=0.7, inertia=0.5, evidence_strength="strong", last_updated_fabula=6000),
            },
        ),
        # Winston ↔ O'Brien — the false intimacy.
        RelationshipEdge(
            source_entity_id="ENT_WINSTON", target_entity_id="ENT_OBRIEN",
            metrics={
                "affinity":      RelationshipMetric(value=0.6, inertia=0.5, evidence_strength="strong", last_updated_fabula=10000),
                "fear":          RelationshipMetric(value=0.95, inertia=0.25, evidence_strength="strong", last_updated_fabula=14000),
                "power_dynamic": RelationshipMetric(value=-0.95, inertia=0.8, evidence_strength="strong", last_updated_fabula=14000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_OBRIEN", target_entity_id="ENT_WINSTON",
            metrics={
                "affinity":      RelationshipMetric(value=0.4, inertia=0.5, evidence_strength="moderate", last_updated_fabula=15000),
                "power_dynamic": RelationshipMetric(value=0.95, inertia=0.8, evidence_strength="strong", last_updated_fabula=14000),
            },
        ),
        # Winston ↔ Charrington — false trust → betrayal.
        RelationshipEdge(
            source_entity_id="ENT_WINSTON", target_entity_id="ENT_CHARRINGTON",
            metrics={
                "affinity": RelationshipMetric(value=0.55, inertia=0.45, evidence_strength="strong", last_updated_fabula=8000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_CHARRINGTON", target_entity_id="ENT_WINSTON",
            metrics={
                "affinity":      RelationshipMetric(value=-0.5, inertia=0.55, evidence_strength="strong", last_updated_fabula=13000),
                "power_dynamic": RelationshipMetric(value=0.85, inertia=0.75, evidence_strength="strong", last_updated_fabula=13000),
            },
        ),
        # Winston ↔ Big Brother — final loving submission.
        RelationshipEdge(
            source_entity_id="ENT_WINSTON", target_entity_id="ENT_BIG_BROTHER",
            metrics={
                "affinity":      RelationshipMetric(value=-0.95, inertia=0.45, evidence_strength="strong", last_updated_fabula=3000),
                "fear":          RelationshipMetric(value=0.95, inertia=0.25, evidence_strength="strong", last_updated_fabula=3000),
                "power_dynamic": RelationshipMetric(value=-0.95, inertia=0.85, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        # Winston ↔ Party.
        RelationshipEdge(
            source_entity_id="ENT_WINSTON", target_entity_id="ENT_PARTY",
            metrics={
                "affinity":      RelationshipMetric(value=-0.95, inertia=0.45, evidence_strength="strong", last_updated_fabula=3000),
                "fear":          RelationshipMetric(value=0.9, inertia=0.25, evidence_strength="strong", last_updated_fabula=3000),
                "power_dynamic": RelationshipMetric(value=-0.95, inertia=0.85, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        # Julia ↔ Party.
        RelationshipEdge(
            source_entity_id="ENT_JULIA", target_entity_id="ENT_PARTY",
            metrics={
                "affinity":      RelationshipMetric(value=-0.65, inertia=0.45, evidence_strength="strong", last_updated_fabula=6000),
                "power_dynamic": RelationshipMetric(value=-0.85, inertia=0.85, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        # Parsons ↔ Party.
        RelationshipEdge(
            source_entity_id="ENT_PARSONS", target_entity_id="ENT_PARTY",
            metrics={
                "affinity":      RelationshipMetric(value=0.95, inertia=0.85, evidence_strength="strong", last_updated_fabula=1000),
                "power_dynamic": RelationshipMetric(value=-0.85, inertia=0.85, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        # Winston ↔ Katharine — frozen marriage.
        RelationshipEdge(
            source_entity_id="ENT_WINSTON", target_entity_id="ENT_KATHARINE",
            metrics={
                "affinity": RelationshipMetric(value=-0.65, inertia=0.7, evidence_strength="moderate", last_updated_fabula=1000),
            },
        ),
        # O'Brien ↔ Party.
        RelationshipEdge(
            source_entity_id="ENT_OBRIEN", target_entity_id="ENT_PARTY",
            metrics={
                "affinity":      RelationshipMetric(value=1.0, inertia=0.95, evidence_strength="strong", last_updated_fabula=1000),
                "power_dynamic": RelationshipMetric(value=0.7, inertia=0.85, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
    ],
)
