"""Persuasion — high-fidelity WorldStateV1 test fixture.

Authored against the current ingestion prompts. Demonstrates all five
CausalEdge modalities, per-axis ``RelationshipMetric``, explicit
``evidence_strength``, and named-latent WORLD_ traits (Regency rank,
the Napoleonic Wars / naval prize economy, primogeniture and entail)
wired as common-cause parents over the events they jointly drive.
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, RelationshipMetric, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    # ── LOCATIONS ──────────────────────────────────────────────────────
    locations={
        "LOC_KELLYNCH_HALL": Location(
            name="Kellynch Hall",
            description="The Elliots' Somersetshire baronial seat; let to Admiral Croft when Sir Walter cannot afford to keep it.",
            ambient_state={
                "rank_consciousness": AmbientVector(value=0.95, volatility=0.1, evidence_strength="strong"),
                "fiscal_strain": AmbientVector(value=0.7, volatility=0.3, evidence_strength="strong"),
            },
        ),
        "LOC_UPPERCROSS": Location(
            name="Uppercross Hall",
            description="The Musgroves' easy country house where Anne stays with her sister Mary.",
            ambient_state={
                "warmth": AmbientVector(value=0.7, volatility=0.2, evidence_strength="strong"),
                "informality": AmbientVector(value=0.7, volatility=0.2, evidence_strength="moderate"),
            },
        ),
        "LOC_LYME_REGIS": Location(
            name="Lyme Regis (the Cobb)",
            description="Coastal town and seawall where the Musgrove party visit Wentworth's naval friends — and where Louisa falls.",
            ambient_state={
                "naval_camaraderie": AmbientVector(value=0.7, volatility=0.2, evidence_strength="strong"),
                "physical_danger": AmbientVector(value=0.5, volatility=0.4, evidence_strength="moderate"),
            },
        ),
        "LOC_BATH": Location(
            name="Bath",
            description="Fashionable spa city where Sir Walter and Elizabeth retrench, and where the courtship plots converge.",
            ambient_state={
                "social_display": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
                "marriage_market": AmbientVector(value=0.8, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_HARVILLE_LODGINGS": Location(
            name="The Harvilles' Lodgings",
            description="Modest seafront rooms in Lyme where Captain Harville's family receive the Musgrove party and where Louisa convalesces.",
            ambient_state={
                "domestic_warmth": AmbientVector(value=0.85, volatility=0.1, evidence_strength="strong"),
            },
        ),
        "LOC_MRS_SMITH_LODGINGS": Location(
            name="Mrs Smith's Lodgings, Westgate Buildings",
            description="The shabby Bath rooms where Anne's impoverished old school friend lives.",
            ambient_state={
                "poverty": AmbientVector(value=0.8, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_WHITE_HART": Location(
            name="The White Hart Inn",
            description="Bath inn where the Musgroves stay and where Anne and Harville's overheard conversation reaches Wentworth.",
            ambient_state={
                "bustle": AmbientVector(value=0.7, volatility=0.3, evidence_strength="strong"),
            },
        ),
    },

    # ── OBJECTS ────────────────────────────────────────────────────────
    objects={
        "OBJ_BARONETAGE": NarrativeObject(
            id="OBJ_BARONETAGE", name="Sir Walter's Baronetage",
            location_id="LOC_KELLYNCH_HALL", owner_id="ENT_SIR_WALTER",
            properties={"state": "well_thumbed", "page_marked": "ELLIOT_OF_KELLYNCH"},
            affordances=[Affordance(action="display_rank", target_type="Entity")],
        ),
        "OBJ_KELLYNCH_LEASE": NarrativeObject(
            id="OBJ_KELLYNCH_LEASE", name="Lease of Kellynch Hall to Admiral Croft",
            location_id="LOC_KELLYNCH_HALL", owner_id="ENT_SIR_WALTER",
            properties={"state": "executed", "tenant": "ENT_ADMIRAL_CROFT"},
            affordances=[Affordance(action="bring_navy_into_county", target_type="Entity")],
        ),
        "OBJ_PRIZE_MONEY": NarrativeObject(
            id="OBJ_PRIZE_MONEY", name="Wentworth's Prize Money",
            location_id=None, owner_id="ENT_WENTWORTH",
            properties={"state": "twenty_five_thousand_pounds", "source": "captured_french_ships"},
            affordances=[Affordance(action="qualify_as_suitor", target_type="Entity")],
        ),
        "OBJ_SMITH_PROPERTY": NarrativeObject(
            id="OBJ_SMITH_PROPERTY", name="Mr Smith's West Indies Property",
            location_id=None, owner_id="ENT_MRS_SMITH",
            properties={"state": "neglected", "executor": "ENT_WILLIAM_ELLIOT"},
            affordances=[Affordance(action="restore_income", target_type="Entity")],
        ),
        "OBJ_WENTWORTHS_LETTER": NarrativeObject(
            id="OBJ_WENTWORTHS_LETTER", name="Captain Wentworth's Letter to Anne",
            location_id="LOC_WHITE_HART", owner_id="ENT_ANNE",
            properties={"state": "freshly_written", "content": "you_pierce_my_soul"},
            affordances=[Affordance(action="declare_love", target_type="Entity")],
        ),
    },

    # ── ENTITIES ────────────────────────────────────────────────────────
    entities={
        "ENT_ANNE": Entity(
            id="ENT_ANNE", name="Anne Elliot",
            location_id="LOC_KELLYNCH_HALL", status="healthy",
            traits={
                "discernment":   TraitVector(value=0.9,  inertia=0.85, evidence_strength="strong"),
                "constancy":     TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "self_effacement": TraitVector(value=0.8, inertia=0.7,  evidence_strength="strong"),
                "regret":        TraitVector(value=0.75, inertia=0.6,  evidence_strength="strong"),
                "moral_courage": TraitVector(value=0.7,  inertia=0.65, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_WENTWORTH",
                       perceived_state="he can never forgive me for the broken engagement",
                       confidence=0.85, inertia=0.5, established_at_fabula=300, evidence_strength="strong"),
                Belief(target_id="ENT_LADY_RUSSELL",
                       perceived_state="she gave me bad counsel but she meant it as a mother would",
                       confidence=0.8,  inertia=0.7, established_at_fabula=200, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=400, triggered_by="EVT_ANNE_VISITS_UPPERCROSS",
                    location_id="LOC_UPPERCROSS"),
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_LYME_VISIT",
                    location_id="LOC_LYME_REGIS"),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_LOUISA_FALLS",
                    traits={
                        "moral_courage": TraitVector(value=0.9, inertia=0.75, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_ANNE_TO_BATH",
                    location_id="LOC_BATH"),
                EntityStateSnapshot(fabula_time=1050, triggered_by="EVT_MRS_SMITH_REVEALS_ELLIOT",
                    beliefs_added=[
                        Belief(target_id="ENT_WILLIAM_ELLIOT",
                               perceived_state="cold, calculating; courts me only to forestall Mrs Clay",
                               confidence=0.95, inertia=0.7, established_at_fabula=1050, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_RECONCILIATION",
                    traits={
                        "regret": TraitVector(value=0.1, inertia=0.6, evidence_strength="strong"),
                    },
                    beliefs_invalidated=["ENT_WENTWORTH"],
                    beliefs_added=[
                        Belief(target_id="ENT_WENTWORTH",
                               perceived_state="he loves me as constantly as ever",
                               confidence=1.0, inertia=0.85, established_at_fabula=1200, evidence_strength="strong"),
                    ]),
            ],
        ),
        "ENT_WENTWORTH": Entity(
            id="ENT_WENTWORTH", name="Captain Frederick Wentworth",
            location_id="LOC_KELLYNCH_HALL", status="healthy",
            traits={
                "ambition":      TraitVector(value=0.85, inertia=0.7,  evidence_strength="strong"),
                "professional_pride": TraitVector(value=0.9, inertia=0.8, evidence_strength="strong"),
                "resentment":    TraitVector(value=0.8,  inertia=0.55, evidence_strength="strong"),
                "constancy":     TraitVector(value=0.85, inertia=0.75, evidence_strength="moderate"),
                "self_knowledge": TraitVector(value=0.5, inertia=0.55, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_ANNE",
                       perceived_state="weak-charactered; could be persuaded out of love",
                       confidence=0.85, inertia=0.5, established_at_fabula=400, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=400, triggered_by="EVT_WENTWORTH_RETURNS",
                    location_id="LOC_UPPERCROSS"),
                EntityStateSnapshot(fabula_time=550, triggered_by="EVT_WENTWORTH_LEARNS_ANNE_REFUSED_CHARLES",
                    traits={
                        "self_knowledge": TraitVector(value=0.65, inertia=0.6, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=720, triggered_by="EVT_LOUISA_FALLS",
                    traits={
                        "self_knowledge": TraitVector(value=0.9, inertia=0.7, evidence_strength="strong"),
                        "resentment":     TraitVector(value=0.3, inertia=0.55, evidence_strength="strong"),
                    },
                    beliefs_invalidated=["ENT_ANNE"],
                    beliefs_added=[
                        Belief(target_id="ENT_ANNE",
                               perceived_state="composed and resolute under pressure; my error to encourage Louisa",
                               confidence=0.95, inertia=0.8, established_at_fabula=720, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_LOUISA_BENWICK_ENGAGED",
                    traits={
                        "constancy": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_WENTWORTH_TO_BATH",
                    location_id="LOC_BATH"),
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_RECONCILIATION",
                    traits={
                        "resentment": TraitVector(value=0.05, inertia=0.6, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_LADY_RUSSELL": Entity(
            id="ENT_LADY_RUSSELL", name="Lady Russell",
            location_id="LOC_KELLYNCH_HALL", status="healthy",
            traits={
                "prudence":      TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "rank_snobbery": TraitVector(value=0.7,  inertia=0.75, evidence_strength="strong"),
                "maternal_concern": TraitVector(value=0.85, inertia=0.8, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_WENTWORTH",
                       perceived_state="a young, undistinguished, rash sailor — quite unsuitable",
                       confidence=0.9, inertia=0.7, established_at_fabula=100, evidence_strength="strong"),
                Belief(target_id="ENT_WILLIAM_ELLIOT",
                       perceived_state="excellent match: rank, fortune, and renewed family connection",
                       confidence=0.85, inertia=0.5, established_at_fabula=900, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1250, triggered_by="EVT_RECONCILIATION",
                    beliefs_invalidated=["ENT_WENTWORTH", "ENT_WILLIAM_ELLIOT"],
                    beliefs_added=[
                        Belief(target_id="ENT_WENTWORTH",
                               perceived_state="my judgement of him was wrong; he is worthy of Anne",
                               confidence=0.9, inertia=0.7, established_at_fabula=1250, evidence_strength="strong"),
                    ]),
            ],
        ),
        "ENT_SIR_WALTER": Entity(
            id="ENT_SIR_WALTER", name="Sir Walter Elliot",
            location_id="LOC_KELLYNCH_HALL", status="healthy",
            traits={
                "vanity":        TraitVector(value=0.95, inertia=0.9,  evidence_strength="strong"),
                "rank_snobbery": TraitVector(value=0.95, inertia=0.9,  evidence_strength="strong"),
                "fiscal_imprudence": TraitVector(value=0.85, inertia=0.8, evidence_strength="strong"),
                "paternal_affection": TraitVector(value=0.2, inertia=0.6, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=300, triggered_by="EVT_KELLYNCH_LET",
                    location_id="LOC_BATH"),
            ],
        ),
        "ENT_ELIZABETH": Entity(
            id="ENT_ELIZABETH", name="Elizabeth Elliot",
            location_id="LOC_KELLYNCH_HALL", status="healthy",
            traits={
                "vanity":        TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
                "rank_snobbery": TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
                "self_regard":   TraitVector(value=0.9,  inertia=0.85, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_MRS_CLAY",
                       perceived_state="useful flatterer; no danger to my prospects",
                       confidence=0.85, inertia=0.65, established_at_fabula=300, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=300, triggered_by="EVT_KELLYNCH_LET",
                    location_id="LOC_BATH"),
            ],
        ),
        "ENT_MARY": Entity(
            id="ENT_MARY", name="Mary Musgrove",
            location_id="LOC_UPPERCROSS", status="ill",
            traits={
                "self_pity":     TraitVector(value=0.85, inertia=0.75, evidence_strength="strong"),
                "rank_snobbery": TraitVector(value=0.75, inertia=0.7,  evidence_strength="strong"),
                "querulousness": TraitVector(value=0.85, inertia=0.7,  evidence_strength="strong"),
            },
            beliefs=[],
        ),
        "ENT_CHARLES_MUSGROVE": Entity(
            id="ENT_CHARLES_MUSGROVE", name="Charles Musgrove",
            location_id="LOC_UPPERCROSS", status="healthy",
            traits={
                "good_humour":  TraitVector(value=0.8, inertia=0.7, evidence_strength="strong"),
                "sporting_distraction": TraitVector(value=0.75, inertia=0.65, evidence_strength="moderate"),
            },
            beliefs=[],
        ),
        "ENT_HENRIETTA": Entity(
            id="ENT_HENRIETTA", name="Henrietta Musgrove",
            location_id="LOC_UPPERCROSS", status="healthy",
            traits={
                "amiability":     TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
                "suggestibility": TraitVector(value=0.7, inertia=0.55, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_CHARLES_HAYTER",
                       perceived_state="my settled love",
                       confidence=0.85, inertia=0.6, established_at_fabula=450, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=520, triggered_by="EVT_HAYTER_WITHDRAWS",
                    traits={
                        "suggestibility": TraitVector(value=0.5, inertia=0.6, evidence_strength="moderate"),
                    }),
            ],
        ),
        "ENT_LOUISA": Entity(
            id="ENT_LOUISA", name="Louisa Musgrove",
            location_id="LOC_UPPERCROSS", status="healthy",
            traits={
                "high_spirits": TraitVector(value=0.9, inertia=0.65, evidence_strength="strong"),
                "wilfulness":   TraitVector(value=0.85, inertia=0.7,  evidence_strength="strong"),
                "infatuation":  TraitVector(value=0.4, inertia=0.4,  evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_WENTWORTH",
                       perceived_state="my decided suitor; I will be persuaded by no one",
                       confidence=0.85, inertia=0.5, established_at_fabula=550, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_LOUISA_FALLS",
                    status="ill", location_id="LOC_HARVILLE_LODGINGS",
                    traits={
                        "high_spirits": TraitVector(value=0.2, inertia=0.6, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_LOUISA_BENWICK_ENGAGED",
                    status="healthy",
                    traits={
                        "infatuation": TraitVector(value=0.85, inertia=0.55, evidence_strength="strong"),
                    },
                    beliefs_invalidated=["ENT_WENTWORTH"],
                    beliefs_added=[
                        Belief(target_id="ENT_BENWICK",
                               perceived_state="my poetic, grieving suitor",
                               confidence=0.85, inertia=0.55, established_at_fabula=900, evidence_strength="strong"),
                    ]),
            ],
        ),
        "ENT_BENWICK": Entity(
            id="ENT_BENWICK", name="Captain James Benwick",
            location_id="LOC_HARVILLE_LODGINGS", status="healthy",
            traits={
                "melancholy":    TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                "literary_taste": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "grief":         TraitVector(value=0.9,  inertia=0.7,  evidence_strength="strong"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_LOUISA_BENWICK_ENGAGED",
                    traits={
                        "grief":      TraitVector(value=0.3, inertia=0.65, evidence_strength="strong"),
                        "melancholy": TraitVector(value=0.4, inertia=0.6, evidence_strength="moderate"),
                    }),
            ],
        ),
        "ENT_HARVILLE": Entity(
            id="ENT_HARVILLE", name="Captain Harville",
            location_id="LOC_HARVILLE_LODGINGS", status="healthy",
            traits={
                "domestic_warmth": TraitVector(value=0.9, inertia=0.8, evidence_strength="strong"),
                "constancy":     TraitVector(value=0.85, inertia=0.75, evidence_strength="strong"),
            },
            beliefs=[],
        ),
        "ENT_ADMIRAL_CROFT": Entity(
            id="ENT_ADMIRAL_CROFT", name="Admiral Croft",
            location_id="LOC_KELLYNCH_HALL", status="healthy",
            traits={
                "bluff_decency": TraitVector(value=0.9, inertia=0.8, evidence_strength="strong"),
                "uxoriousness":  TraitVector(value=0.85, inertia=0.8, evidence_strength="strong"),
            },
            beliefs=[],
            constants=["royal_navy_admiral", "wentworths_brother_in_law"],
            state_timeline=[
                EntityStateSnapshot(
                    fabula_time=300, triggered_by="EVT_KELLYNCH_LET",
                    location_id="LOC_KELLYNCH_HALL",
                    traits={
                        "bluff_decency": TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_SOPHIA_CROFT": Entity(
            id="ENT_SOPHIA_CROFT", name="Mrs Sophia Croft",
            location_id="LOC_KELLYNCH_HALL", status="healthy",
            traits={
                "competence":   TraitVector(value=0.9, inertia=0.8, evidence_strength="strong"),
                "frankness":    TraitVector(value=0.85, inertia=0.75, evidence_strength="strong"),
            },
            beliefs=[],
        ),
        "ENT_WILLIAM_ELLIOT": Entity(
            id="ENT_WILLIAM_ELLIOT", name="Mr William Elliot",
            location_id="LOC_LYME_REGIS", status="healthy",
            traits={
                "polish":       TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "duplicity":    TraitVector(value=0.85, inertia=0.8,  evidence_strength="strong"),
                "calculation":  TraitVector(value=0.9,  inertia=0.85, evidence_strength="strong"),
                "self_interest": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="OBJ_BARONETAGE",
                       perceived_state="the Kellynch entail must come to me intact",
                       confidence=0.95, inertia=0.85, established_at_fabula=850, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_WILLIAM_RETURNS_TO_FAMILY",
                    location_id="LOC_BATH"),
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_WILLIAM_LEAVES_BATH",
                    location_id=None),
            ],
        ),
        "ENT_MRS_CLAY": Entity(
            id="ENT_MRS_CLAY", name="Mrs Penelope Clay",
            location_id="LOC_KELLYNCH_HALL", status="healthy",
            traits={
                "ingratiation": TraitVector(value=0.9, inertia=0.7, evidence_strength="strong"),
                "ambition":     TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=300, triggered_by="EVT_KELLYNCH_LET",
                    location_id="LOC_BATH"),
                EntityStateSnapshot(fabula_time=1320, triggered_by="EVT_MRS_CLAY_FOLLOWS_WILLIAM",
                    location_id=None),
            ],
        ),
        "ENT_MRS_SMITH": Entity(
            id="ENT_MRS_SMITH", name="Mrs Smith",
            location_id="LOC_MRS_SMITH_LODGINGS", status="ill",
            traits={
                "endurance":     TraitVector(value=0.85, inertia=0.75, evidence_strength="strong"),
                "discernment":   TraitVector(value=0.85, inertia=0.8, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_WILLIAM_ELLIOT",
                       perceived_state="cold opportunist who ruined my husband and refuses to act for me",
                       confidence=0.95, inertia=0.85, established_at_fabula=950, evidence_strength="strong"),
            ],
            constants=["widowed", "annes_old_school_friend"],
            state_timeline=[
                EntityStateSnapshot(
                    fabula_time=1000, triggered_by="EVT_ANNE_VISITS_MRS_SMITH",
                    location_id="LOC_MRS_SMITH_LODGINGS",
                    traits={
                        "endurance": TraitVector(value=0.88, inertia=0.78, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(
                    fabula_time=1410, triggered_by="EVT_WENTWORTH_HELPS_MRS_SMITH",
                    location_id="LOC_MRS_SMITH_LODGINGS", status="healthy",
                    traits={
                        "endurance": TraitVector(value=0.92, inertia=0.8, evidence_strength="strong"),
                        "gratitude": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_CHARLES_HAYTER": Entity(
            id="ENT_CHARLES_HAYTER", name="Charles Hayter",
            location_id="LOC_UPPERCROSS", status="healthy",
            traits={
                "diffidence":  TraitVector(value=0.7, inertia=0.6, evidence_strength="moderate"),
                "constancy":   TraitVector(value=0.8, inertia=0.7, evidence_strength="moderate"),
            },
            beliefs=[],
        ),
    },

    # ── EVENTS ──────────────────────────────────────────────────────────
    events=[
        EventNode(id="EVT_BROKEN_ENGAGEMENT", fabula_time=100, syuzhet_index=1,
                  event_type="choice", actor_ids=["ENT_ANNE", "ENT_LADY_RUSSELL"], target_ids=["ENT_WENTWORTH"],
                  description="Persuaded by Lady Russell that the match is imprudent for one so young, the nineteen-year-old Anne breaks her engagement to the unestablished Lieutenant Wentworth."),
        EventNode(id="EVT_WAR_AND_PRIZE_MONEY", fabula_time=200, syuzhet_index=2,
                  event_type="outcome", actor_ids=["ENT_WENTWORTH"], target_ids=[],
                  description="Through the late Napoleonic Wars Wentworth captures French ships and accumulates roughly £25,000 in prize money, becoming a captain of fortune."),
        EventNode(id="EVT_KELLYNCH_LET", fabula_time=300, syuzhet_index=3,
                  event_type="choice", actor_ids=["ENT_SIR_WALTER"], target_ids=["ENT_ADMIRAL_CROFT"],
                  description="Pressed by debts, Sir Walter is persuaded to let Kellynch Hall to Admiral and Mrs Croft and remove with Elizabeth and Mrs Clay to Bath."),
        EventNode(id="EVT_ANNE_VISITS_UPPERCROSS", fabula_time=400, syuzhet_index=4,
                  event_type="choice", actor_ids=["ENT_ANNE"], target_ids=[],
                  description="Anne goes to Uppercross to nurse Mary, putting her in the social orbit of the Crofts and the returning Wentworth."),
        EventNode(id="EVT_WENTWORTH_RETURNS", fabula_time=420, syuzhet_index=5,
                  event_type="outcome", actor_ids=["ENT_WENTWORTH"], target_ids=[],
                  description="Wentworth visits the Crofts at Kellynch and is drawn into the Musgrove circle, openly looking to marry."),
        EventNode(id="EVT_HAYTER_WITHDRAWS", fabula_time=500, syuzhet_index=6,
                  event_type="choice", actor_ids=["ENT_CHARLES_HAYTER"], target_ids=["ENT_HENRIETTA"],
                  description="Hurt by Henrietta's apparent interest in Wentworth, Charles Hayter stops visiting Uppercross."),
        EventNode(id="EVT_WENTWORTH_LEARNS_ANNE_REFUSED_CHARLES", fabula_time=550, syuzhet_index=7,
                  event_type="revelation", actor_ids=["ENT_LOUISA"], target_ids=["ENT_WENTWORTH"],
                  description="Anne overhears Louisa telling Wentworth that Anne refused Charles Musgrove's first proposal, revealing Anne's continued unmarried state and disturbing Wentworth's settled view of her."),
        EventNode(id="EVT_LYME_VISIT", fabula_time=600, syuzhet_index=8,
                  event_type="choice", actor_ids=["ENT_WENTWORTH", "ENT_ANNE"], target_ids=[],
                  description="The Uppercross party visits Captain Harville's family at Lyme Regis; Anne's looks attract the notice of a stranger who turns out to be William Elliot."),
        EventNode(id="EVT_WILLIAM_ADMIRES_ANNE_AT_LYME", fabula_time=650, syuzhet_index=9,
                  event_type="revelation", actor_ids=["ENT_WILLIAM_ELLIOT"], target_ids=["ENT_ANNE"],
                  description="At Lyme, William Elliot — heir presumptive to Kellynch — sees and silently admires Anne, planting his later courtship."),
        EventNode(id="EVT_LOUISA_FALLS", fabula_time=700, syuzhet_index=10,
                  event_type="outcome", actor_ids=["ENT_LOUISA"], target_ids=["ENT_LOUISA"],
                  description="On the Cobb Louisa insists on jumping a second time before Wentworth is ready to catch her, falls, and is concussed; Anne directs the response while the others panic."),
        EventNode(id="EVT_ANNE_TO_BATH", fabula_time=800, syuzhet_index=11,
                  event_type="choice", actor_ids=["ENT_ANNE"], target_ids=[],
                  description="Anne joins Sir Walter and Elizabeth in Bath, where Lady Russell is also resident."),
        EventNode(id="EVT_WILLIAM_RETURNS_TO_FAMILY", fabula_time=850, syuzhet_index=12,
                  event_type="choice", actor_ids=["ENT_WILLIAM_ELLIOT"], target_ids=["ENT_SIR_WALTER"],
                  description="William Elliot reconciles with Sir Walter and Elizabeth in Bath, courting Anne under the pretext of preserving the family line."),
        EventNode(id="EVT_LOUISA_BENWICK_ENGAGED", fabula_time=900, syuzhet_index=13,
                  event_type="outcome", actor_ids=["ENT_LOUISA", "ENT_BENWICK"], target_ids=[],
                  description="During Louisa's long convalescence at the Harvilles', she and Captain Benwick fall in love and become engaged, freeing Wentworth from the obligation he had felt to her."),
        EventNode(id="EVT_ANNE_VISITS_MRS_SMITH", fabula_time=1000, syuzhet_index=14,
                  event_type="choice", actor_ids=["ENT_ANNE"], target_ids=["ENT_MRS_SMITH"],
                  description="Against her father's snobbish disapproval, Anne calls on her impoverished old school friend Mrs Smith in Westgate Buildings."),
        EventNode(id="EVT_MRS_SMITH_REVEALS_ELLIOT", fabula_time=1050, syuzhet_index=15,
                  event_type="revelation", actor_ids=["ENT_MRS_SMITH"], target_ids=["ENT_ANNE"],
                  description="Mrs Smith reveals William Elliot's history of cold opportunism, his refusal to act as her husband's executor, and that his real motive in courting Anne is to forestall Mrs Clay marrying Sir Walter and bearing a displacing male heir."),
        EventNode(id="EVT_WENTWORTH_TO_BATH", fabula_time=1100, syuzhet_index=16,
                  event_type="choice", actor_ids=["ENT_WENTWORTH"], target_ids=[],
                  description="Wentworth, freed by Louisa's engagement to Benwick, travels to Bath and is alarmed to find William Elliot seemingly courting Anne."),
        EventNode(id="EVT_HARVILLE_ANNE_CONVERSATION", fabula_time=1180, syuzhet_index=17,
                  event_type="choice", actor_ids=["ENT_ANNE", "ENT_HARVILLE"], target_ids=["ENT_WENTWORTH"],
                  description="At the White Hart, Anne discusses with Harville the comparative constancy of men and women in love, arguing that women love longest when all hope is gone — within Wentworth's hearing."),
        EventNode(id="EVT_WENTWORTHS_LETTER", fabula_time=1190, syuzhet_index=18,
                  event_type="choice", actor_ids=["ENT_WENTWORTH"], target_ids=["ENT_ANNE"],
                  description="Pierced by Anne's words, Wentworth writes the letter declaring he is half agony, half hope, and slips it where Anne will find it."),
        EventNode(id="EVT_RECONCILIATION", fabula_time=1200, syuzhet_index=19,
                  event_type="outcome", actor_ids=["ENT_ANNE", "ENT_WENTWORTH"], target_ids=[],
                  description="In the streets of Bath, Anne and Wentworth meet, declare themselves, and renew their engagement."),
        EventNode(id="EVT_WILLIAM_LEAVES_BATH", fabula_time=1300, syuzhet_index=20,
                  event_type="choice", actor_ids=["ENT_WILLIAM_ELLIOT"], target_ids=[],
                  description="His scheme exposed and his hopes of Anne dashed, William Elliot quietly leaves Bath."),
        EventNode(id="EVT_MRS_CLAY_FOLLOWS_WILLIAM", fabula_time=1320, syuzhet_index=21,
                  event_type="choice", actor_ids=["ENT_MRS_CLAY"], target_ids=["ENT_WILLIAM_ELLIOT"],
                  description="Mrs Clay slips away to become William Elliot's mistress, ending the threat that she might marry Sir Walter."),
        EventNode(id="EVT_WENTWORTH_HELPS_MRS_SMITH", fabula_time=1400, syuzhet_index=22,
                  event_type="outcome", actor_ids=["ENT_WENTWORTH"], target_ids=["ENT_MRS_SMITH"],
                  description="After his marriage to Anne, Wentworth uses his interest to help Mrs Smith recover her West Indies property and her income."),
    ],

    # ── CAUSAL TOPOLOGY ────────────────────────────────────────────────
    causal_topology=[
        # ── chain_reaction ──
        CausalEdge(source_id="EVT_BROKEN_ENGAGEMENT", target_id="EVT_WAR_AND_PRIZE_MONEY",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=100, propagation_delay=100),
        CausalEdge(source_id="EVT_KELLYNCH_LET", target_id="EVT_WENTWORTH_RETURNS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300, propagation_delay=120),
        CausalEdge(source_id="EVT_KELLYNCH_LET", target_id="EVT_ANNE_VISITS_UPPERCROSS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=300, propagation_delay=100),
        CausalEdge(source_id="EVT_WENTWORTH_RETURNS", target_id="EVT_HAYTER_WITHDRAWS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=420, propagation_delay=80),
        CausalEdge(source_id="EVT_WENTWORTH_RETURNS", target_id="EVT_WENTWORTH_LEARNS_ANNE_REFUSED_CHARLES",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=6.0, fabula_time=420, propagation_delay=130),
        CausalEdge(source_id="EVT_WENTWORTH_RETURNS", target_id="EVT_LYME_VISIT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=420, propagation_delay=180),
        CausalEdge(source_id="EVT_LYME_VISIT", target_id="EVT_WILLIAM_ADMIRES_ANNE_AT_LYME",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=600, propagation_delay=50),
        CausalEdge(source_id="EVT_LYME_VISIT", target_id="EVT_LOUISA_FALLS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600, propagation_delay=100),
        CausalEdge(source_id="EVT_LOUISA_FALLS", target_id="EVT_LOUISA_BENWICK_ENGAGED",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700, propagation_delay=200),
        CausalEdge(source_id="EVT_ANNE_TO_BATH", target_id="EVT_WILLIAM_RETURNS_TO_FAMILY",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=800, propagation_delay=50),
        CausalEdge(source_id="EVT_WILLIAM_ADMIRES_ANNE_AT_LYME", target_id="EVT_WILLIAM_RETURNS_TO_FAMILY",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=650, propagation_delay=200),
        CausalEdge(source_id="EVT_ANNE_TO_BATH", target_id="EVT_ANNE_VISITS_MRS_SMITH",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=800, propagation_delay=200),
        CausalEdge(source_id="EVT_ANNE_VISITS_MRS_SMITH", target_id="EVT_MRS_SMITH_REVEALS_ELLIOT",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000, propagation_delay=50),
        CausalEdge(source_id="EVT_LOUISA_BENWICK_ENGAGED", target_id="EVT_WENTWORTH_TO_BATH",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900, propagation_delay=200),
        CausalEdge(source_id="EVT_WENTWORTH_TO_BATH", target_id="EVT_HARVILLE_ANNE_CONVERSATION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=1100, propagation_delay=80),
        CausalEdge(source_id="EVT_HARVILLE_ANNE_CONVERSATION", target_id="EVT_WENTWORTHS_LETTER",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1180, propagation_delay=10),
        CausalEdge(source_id="EVT_WENTWORTHS_LETTER", target_id="EVT_RECONCILIATION",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1190, propagation_delay=10),
        CausalEdge(source_id="EVT_MRS_SMITH_REVEALS_ELLIOT", target_id="EVT_WILLIAM_LEAVES_BATH",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1050, propagation_delay=250),
        CausalEdge(source_id="EVT_RECONCILIATION", target_id="EVT_WILLIAM_LEAVES_BATH",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1200, propagation_delay=100),
        CausalEdge(source_id="EVT_WILLIAM_LEAVES_BATH", target_id="EVT_MRS_CLAY_FOLLOWS_WILLIAM",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1300, propagation_delay=20),
        CausalEdge(source_id="EVT_RECONCILIATION", target_id="EVT_WENTWORTH_HELPS_MRS_SMITH",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=1200, propagation_delay=200),

        # ── mutation ──
        CausalEdge(source_id="EVT_BROKEN_ENGAGEMENT", target_id="ENT_ANNE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=100,
                   trait_target="regret", trait_delta=0.7),
        CausalEdge(source_id="EVT_BROKEN_ENGAGEMENT", target_id="ENT_ANNE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=100,
                   trait_target="self_effacement", trait_delta=0.3),
        CausalEdge(source_id="EVT_BROKEN_ENGAGEMENT", target_id="ENT_WENTWORTH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100,
                   trait_target="resentment", trait_delta=0.7),
        CausalEdge(source_id="EVT_BROKEN_ENGAGEMENT", target_id="ENT_WENTWORTH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=100,
                   trait_target="ambition", trait_delta=0.3),
        CausalEdge(source_id="EVT_WENTWORTH_LEARNS_ANNE_REFUSED_CHARLES", target_id="ENT_WENTWORTH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=550,
                   trait_target="self_knowledge", trait_delta=0.15),
        CausalEdge(source_id="EVT_LOUISA_FALLS", target_id="ENT_WENTWORTH",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=720,
                   trait_target="self_knowledge", trait_delta=0.4),
        CausalEdge(source_id="EVT_LOUISA_FALLS", target_id="ENT_WENTWORTH",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=720,
                   trait_target="resentment", trait_delta=-0.5),
        CausalEdge(source_id="EVT_LOUISA_FALLS", target_id="ENT_ANNE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=720,
                   trait_target="moral_courage", trait_delta=0.2),
        CausalEdge(source_id="EVT_LOUISA_FALLS", target_id="ENT_LOUISA",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=700,
                   trait_target="high_spirits", trait_delta=-0.7),
        CausalEdge(source_id="EVT_LOUISA_BENWICK_ENGAGED", target_id="ENT_BENWICK",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900,
                   trait_target="grief", trait_delta=-0.6),
        CausalEdge(source_id="EVT_LOUISA_BENWICK_ENGAGED", target_id="ENT_LOUISA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=900,
                   trait_target="infatuation", trait_delta=0.45),
        CausalEdge(source_id="EVT_RECONCILIATION", target_id="ENT_ANNE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1200,
                   trait_target="regret", trait_delta=-0.65),
        CausalEdge(source_id="EVT_RECONCILIATION", target_id="ENT_WENTWORTH",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1200,
                   trait_target="resentment", trait_delta=-0.25),

        # ── mutation: events newly covered ──
        CausalEdge(source_id="EVT_KELLYNCH_LET", target_id="ENT_SIR_WALTER",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=300,
                   trait_target="vanity", trait_delta=-0.05),
        CausalEdge(source_id="EVT_KELLYNCH_LET", target_id="ENT_SIR_WALTER",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300,
                   trait_target="humiliation", trait_delta=0.6),
        CausalEdge(source_id="EVT_KELLYNCH_LET", target_id="ENT_ANNE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=300,
                   trait_target="self_effacement", trait_delta=0.15),
        CausalEdge(source_id="EVT_HAYTER_WITHDRAWS", target_id="ENT_HENRIETTA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=520,
                   trait_target="suggestibility", trait_delta=-0.2),
        CausalEdge(source_id="EVT_HAYTER_WITHDRAWS", target_id="ENT_HENRIETTA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=520,
                   trait_target="self_knowledge", trait_delta=0.25),
        CausalEdge(source_id="EVT_WILLIAM_RETURNS_TO_FAMILY", target_id="ENT_ANNE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=5.0, fabula_time=860,
                   trait_target="suspicion", trait_delta=0.4),
        CausalEdge(source_id="EVT_WILLIAM_RETURNS_TO_FAMILY", target_id="ENT_ELIZABETH",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=860,
                   trait_target="vanity", trait_delta=0.05),
        CausalEdge(source_id="EVT_ANNE_VISITS_MRS_SMITH", target_id="ENT_ANNE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1010,
                   trait_target="moral_courage", trait_delta=0.15),
        CausalEdge(source_id="EVT_ANNE_VISITS_MRS_SMITH", target_id="ENT_ANNE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1010,
                   trait_target="loyalty", trait_delta=0.25),
        CausalEdge(source_id="EVT_HARVILLE_ANNE_CONVERSATION", target_id="ENT_WENTWORTH",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1185,
                   trait_target="hope", trait_delta=0.7),
        CausalEdge(source_id="EVT_HARVILLE_ANNE_CONVERSATION", target_id="ENT_WENTWORTH",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1185,
                   trait_target="resentment", trait_delta=-0.4),
        CausalEdge(source_id="EVT_WENTWORTHS_LETTER", target_id="ENT_ANNE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1192,
                   trait_target="hope", trait_delta=0.85),
        CausalEdge(source_id="EVT_MRS_CLAY_FOLLOWS_WILLIAM", target_id="ENT_WILLIAM_ELLIOT",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1325,
                   trait_target="duplicity", trait_delta=0.05),
        CausalEdge(source_id="EVT_WENTWORTH_HELPS_MRS_SMITH", target_id="ENT_MRS_SMITH",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1410,
                   trait_target="endurance", trait_delta=0.1),
        CausalEdge(source_id="EVT_WENTWORTH_HELPS_MRS_SMITH", target_id="ENT_MRS_SMITH",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1410,
                   trait_target="gratitude", trait_delta=0.7),

        # ── mutation_social ──
        CausalEdge(source_id="EVT_BROKEN_ENGAGEMENT", target_id="ENT_WENTWORTH",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=10.0, fabula_time=100,
                   trait_target="affinity", trait_delta=-0.95, rel_counterpart_id="ENT_ANNE"),
        CausalEdge(source_id="EVT_BROKEN_ENGAGEMENT", target_id="ENT_ANNE",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=4.0, fabula_time=100,
                   trait_target="affinity", trait_delta=-0.05, rel_counterpart_id="ENT_WENTWORTH"),
        CausalEdge(source_id="EVT_LOUISA_FALLS", target_id="ENT_WENTWORTH",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=720,
                   trait_target="affinity", trait_delta=0.65, rel_counterpart_id="ENT_ANNE"),
        CausalEdge(source_id="EVT_LOUISA_BENWICK_ENGAGED", target_id="ENT_LOUISA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900,
                   trait_target="affinity", trait_delta=0.85, rel_counterpart_id="ENT_BENWICK"),
        CausalEdge(source_id="EVT_LOUISA_BENWICK_ENGAGED", target_id="ENT_BENWICK",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900,
                   trait_target="affinity", trait_delta=0.85, rel_counterpart_id="ENT_LOUISA"),
        CausalEdge(source_id="EVT_MRS_SMITH_REVEALS_ELLIOT", target_id="ENT_ANNE",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1050,
                   trait_target="affinity", trait_delta=-0.85, rel_counterpart_id="ENT_WILLIAM_ELLIOT"),
        CausalEdge(source_id="EVT_RECONCILIATION", target_id="ENT_ANNE",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1200,
                   trait_target="affinity", trait_delta=1.0, rel_counterpart_id="ENT_WENTWORTH"),
        CausalEdge(source_id="EVT_RECONCILIATION", target_id="ENT_WENTWORTH",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1200,
                   trait_target="affinity", trait_delta=1.0, rel_counterpart_id="ENT_ANNE"),

        # ── affordance_gate ──
        CausalEdge(source_id="OBJ_KELLYNCH_LEASE", target_id="EVT_WENTWORTH_RETURNS",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=420),
        CausalEdge(source_id="OBJ_PRIZE_MONEY", target_id="EVT_RECONCILIATION",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1200),
        CausalEdge(source_id="OBJ_BARONETAGE", target_id="EVT_WILLIAM_RETURNS_TO_FAMILY",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=850),
        CausalEdge(source_id="OBJ_WENTWORTHS_LETTER", target_id="EVT_RECONCILIATION",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1200),
        CausalEdge(source_id="OBJ_SMITH_PROPERTY", target_id="EVT_WENTWORTH_HELPS_MRS_SMITH",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1400),

        # ── ambient_propagation ──
        CausalEdge(source_id="LOC_KELLYNCH_HALL", target_id="ENT_SIR_WALTER",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="strong",
                   causal_force=4.0, fabula_time=300),
        CausalEdge(source_id="LOC_BATH", target_id="ENT_ELIZABETH",
                   causality_type="ambient_propagation", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=850),
        CausalEdge(source_id="LOC_BATH", target_id="ENT_WILLIAM_ELLIOT",
                   causality_type="ambient_propagation", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=850),
        CausalEdge(source_id="LOC_LYME_REGIS", target_id="ENT_LOUISA",
                   causality_type="ambient_propagation", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=700),

        # ── WORLD_ → Event ──
        CausalEdge(source_id="WORLD_REGENCY_RANK", target_id="EVT_BROKEN_ENGAGEMENT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100),
        CausalEdge(source_id="WORLD_REGENCY_RANK", target_id="EVT_KELLYNCH_LET",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=300),
        CausalEdge(source_id="WORLD_REGENCY_RANK", target_id="EVT_WILLIAM_RETURNS_TO_FAMILY",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=850),
        CausalEdge(source_id="WORLD_REGENCY_RANK", target_id="EVT_ANNE_VISITS_MRS_SMITH",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1000),
        CausalEdge(source_id="WORLD_NAVAL_PRIZE_ECONOMY", target_id="EVT_WAR_AND_PRIZE_MONEY",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200),
        CausalEdge(source_id="WORLD_NAVAL_PRIZE_ECONOMY", target_id="EVT_WENTWORTH_RETURNS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=420),
        CausalEdge(source_id="WORLD_NAVAL_PRIZE_ECONOMY", target_id="EVT_KELLYNCH_LET",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=300),
        CausalEdge(source_id="WORLD_PRIMOGENITURE_ENTAIL", target_id="EVT_WILLIAM_RETURNS_TO_FAMILY",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=850),
        CausalEdge(source_id="WORLD_PRIMOGENITURE_ENTAIL", target_id="EVT_MRS_SMITH_REVEALS_ELLIOT",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1050),
        CausalEdge(source_id="WORLD_PRIMOGENITURE_ENTAIL", target_id="EVT_MRS_CLAY_FOLLOWS_WILLIAM",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1320),
    ],

    # ── SPATIAL TOPOLOGY ────────────────────────────────────────────────
    spatial_topology=[
        SpatialEdge(source_id="LOC_KELLYNCH_HALL", target_id="LOC_UPPERCROSS"),
        SpatialEdge(source_id="LOC_UPPERCROSS", target_id="LOC_KELLYNCH_HALL"),
        SpatialEdge(source_id="LOC_UPPERCROSS", target_id="LOC_LYME_REGIS"),
        SpatialEdge(source_id="LOC_LYME_REGIS", target_id="LOC_HARVILLE_LODGINGS"),
        SpatialEdge(source_id="LOC_HARVILLE_LODGINGS", target_id="LOC_LYME_REGIS"),
        SpatialEdge(source_id="LOC_KELLYNCH_HALL", target_id="LOC_BATH"),
        SpatialEdge(source_id="LOC_UPPERCROSS", target_id="LOC_BATH"),
        SpatialEdge(source_id="LOC_LYME_REGIS", target_id="LOC_BATH"),
        SpatialEdge(source_id="LOC_BATH", target_id="LOC_MRS_SMITH_LODGINGS"),
        SpatialEdge(source_id="LOC_BATH", target_id="LOC_WHITE_HART"),
    ],

    # ── INFORMATION TOPOLOGY ────────────────────────────────────────────
    information_topology=[
        InformationEdge(source_id="ENT_LOUISA", target_ids=["ENT_WENTWORTH", "ENT_ANNE"],
                        medium="overheard_conversation", is_encrypted=False,
                        established_at_fabula=550, terminated_at_fabula=550,
                        discovered_at_syuzhet=7, evidence_strength="strong"),
        InformationEdge(source_id="ENT_WILLIAM_ELLIOT", target_ids=["ENT_SIR_WALTER", "ENT_ELIZABETH"],
                        medium="reconciliatory_visit", is_encrypted=True,
                        established_at_fabula=850, terminated_at_fabula=1300,
                        discovered_at_syuzhet=12, evidence_strength="moderate"),
        InformationEdge(source_id="ENT_MRS_SMITH", target_ids=["ENT_ANNE"],
                        medium="confidential_disclosure", is_encrypted=False,
                        established_at_fabula=1050, terminated_at_fabula=1050,
                        discovered_at_syuzhet=15, evidence_strength="strong"),
        InformationEdge(source_id="ENT_ANNE", target_ids=["ENT_WENTWORTH"],
                        medium="overheard_conversation", is_encrypted=False,
                        established_at_fabula=1180, terminated_at_fabula=1180,
                        discovered_at_syuzhet=17, evidence_strength="strong"),
        InformationEdge(source_id="OBJ_WENTWORTHS_LETTER", target_ids=["ENT_ANNE"],
                        medium="written_letter", is_encrypted=False,
                        established_at_fabula=1190, terminated_at_fabula=1200,
                        discovered_at_syuzhet=18, evidence_strength="strong"),
        InformationEdge(source_id="ENT_ADMIRAL_CROFT", target_ids=["ENT_ANNE"],
                        medium="bath_gossip", is_encrypted=False,
                        established_at_fabula=1080, terminated_at_fabula=1080,
                        discovered_at_syuzhet=14, evidence_strength="moderate"),
        InformationEdge(source_id="ENT_HARVILLE", target_ids=["ENT_ANNE"],
                        medium="dialogue", is_encrypted=False,
                        established_at_fabula=1180, terminated_at_fabula=1180,
                        discovered_at_syuzhet=17, evidence_strength="strong"),
        InformationEdge(source_id="ENT_WILLIAM_ELLIOT", target_ids=["ENT_ANNE"],
                        medium="flattering_confidences", is_encrypted=True,
                        established_at_fabula=900, terminated_at_fabula=1050,
                        discovered_at_syuzhet=12, evidence_strength="moderate"),
    ],

    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_REGENCY_RANK": GlobalTrait(
            id="WORLD_REGENCY_RANK",
            name="Regency Rank Hierarchy",
            description="The fine-grained gradient of baronet, gentry, professional, naval officer, clergyman, and dependent that orders all introductions, marriages, and visiting practice in 1814 England. Operates as a common-cause parent over the original broken engagement, the Kellynch removal, and William Elliot's manoeuvres around the entail.",
            category="social_structure",
            magnitude=TraitVector(value=0.95, inertia=0.9, evidence_strength="strong"),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=1200, triggered_by="EVT_RECONCILIATION",
                    magnitude=TraitVector(value=0.7, inertia=0.85, evidence_strength="strong"),
                    description="Wentworth's marriage to Anne, sanctioned by Lady Russell, partially loosens the rank logic that originally divided them."),
            ],
        ),
        "WORLD_NAVAL_PRIZE_ECONOMY": GlobalTrait(
            id="WORLD_NAVAL_PRIZE_ECONOMY",
            name="Napoleonic Naval Prize Economy",
            description="The wartime British system under which captured enemy ships are sold and the proceeds shared among officers and crew. Wentworth's twenty-five thousand pounds — and the very fact of the Crofts' Kellynch tenancy — flow from this institution, which is the engine that returns Wentworth to Anne's social circle as an eligible match.",
            category="economy",
            magnitude=TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
            affected_domains=["social", "economic"],
        ),
        "WORLD_PRIMOGENITURE_ENTAIL": GlobalTrait(
            id="WORLD_PRIMOGENITURE_ENTAIL",
            name="Primogeniture and the Kellynch Entail",
            description="The English law of inheritance that channels Kellynch Hall through the male line, making William Elliot heir presumptive and giving him a calculable interest in preventing Sir Walter's remarriage. The hidden structural cause of William's courtship of Anne and Mrs Clay's manoeuvres.",
            category="governance",
            magnitude=TraitVector(value=0.9, inertia=0.9, evidence_strength="strong"),
            affected_domains=["social"],
        ),
    },

    # ── SOCIAL TOPOLOGY ────────────────────────────────────────────────
    social_topology=[
        # Anne ↔ Wentworth — buried love.
        RelationshipEdge(
            source_entity_id="ENT_ANNE", target_entity_id="ENT_WENTWORTH",
            metrics={
                "affinity": RelationshipMetric(value=0.9, inertia=0.55, evidence_strength="strong", last_updated_fabula=400),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_WENTWORTH", target_entity_id="ENT_ANNE",
            metrics={
                "affinity": RelationshipMetric(value=-0.4, inertia=0.5, evidence_strength="strong", last_updated_fabula=420),
            },
        ),
        # Anne ↔ Lady Russell — daughter substitute.
        RelationshipEdge(
            source_entity_id="ENT_ANNE", target_entity_id="ENT_LADY_RUSSELL",
            metrics={
                "affinity": RelationshipMetric(value=0.75, inertia=0.7, evidence_strength="strong", last_updated_fabula=400),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_LADY_RUSSELL", target_entity_id="ENT_ANNE",
            metrics={
                "affinity":      RelationshipMetric(value=0.85, inertia=0.7, evidence_strength="strong", last_updated_fabula=400),
                "power_dynamic": RelationshipMetric(value=0.6, inertia=0.75, evidence_strength="strong", last_updated_fabula=100),
            },
        ),
        # Sir Walter → Anne — neglect.
        RelationshipEdge(
            source_entity_id="ENT_SIR_WALTER", target_entity_id="ENT_ANNE",
            metrics={
                "affinity":      RelationshipMetric(value=-0.1, inertia=0.65, evidence_strength="strong", last_updated_fabula=400),
                "power_dynamic": RelationshipMetric(value=0.55, inertia=0.75, evidence_strength="moderate", last_updated_fabula=100),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_ANNE", target_entity_id="ENT_SIR_WALTER",
            metrics={
                "affinity": RelationshipMetric(value=0.15, inertia=0.6, evidence_strength="moderate", last_updated_fabula=400),
            },
        ),
        # Elizabeth → Anne — disdain.
        RelationshipEdge(
            source_entity_id="ENT_ELIZABETH", target_entity_id="ENT_ANNE",
            metrics={
                "affinity": RelationshipMetric(value=-0.3, inertia=0.65, evidence_strength="strong", last_updated_fabula=400),
            },
        ),
        # Mary → Anne — clinging.
        RelationshipEdge(
            source_entity_id="ENT_MARY", target_entity_id="ENT_ANNE",
            metrics={
                "affinity": RelationshipMetric(value=0.55, inertia=0.55, evidence_strength="moderate", last_updated_fabula=400),
            },
        ),
        # Henrietta ↔ Charles Hayter — settled love.
        RelationshipEdge(
            source_entity_id="ENT_HENRIETTA", target_entity_id="ENT_CHARLES_HAYTER",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.55, evidence_strength="strong", last_updated_fabula=520),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_CHARLES_HAYTER", target_entity_id="ENT_HENRIETTA",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.6, evidence_strength="strong", last_updated_fabula=500),
            },
        ),
        # Louisa ↔ Wentworth — flirtation.
        RelationshipEdge(
            source_entity_id="ENT_LOUISA", target_entity_id="ENT_WENTWORTH",
            metrics={
                "affinity": RelationshipMetric(value=0.7, inertia=0.5, evidence_strength="strong", last_updated_fabula=600),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_WENTWORTH", target_entity_id="ENT_LOUISA",
            metrics={
                "affinity": RelationshipMetric(value=0.45, inertia=0.45, evidence_strength="moderate", last_updated_fabula=600),
            },
        ),
        # Louisa ↔ Benwick — convalescent love.
        RelationshipEdge(
            source_entity_id="ENT_LOUISA", target_entity_id="ENT_BENWICK",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.55, evidence_strength="strong", last_updated_fabula=900),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_BENWICK", target_entity_id="ENT_LOUISA",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.55, evidence_strength="strong", last_updated_fabula=900),
            },
        ),
        # William → Anne — instrumental courtship.
        RelationshipEdge(
            source_entity_id="ENT_WILLIAM_ELLIOT", target_entity_id="ENT_ANNE",
            metrics={
                "affinity":      RelationshipMetric(value=0.5, inertia=0.45, evidence_strength="moderate", last_updated_fabula=900),
                "power_dynamic": RelationshipMetric(value=0.6, inertia=0.65, evidence_strength="moderate", last_updated_fabula=900),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_ANNE", target_entity_id="ENT_WILLIAM_ELLIOT",
            metrics={
                "affinity": RelationshipMetric(value=-0.6, inertia=0.5, evidence_strength="strong", last_updated_fabula=1050),
            },
        ),
        # Mrs Clay → Sir Walter — designs.
        RelationshipEdge(
            source_entity_id="ENT_MRS_CLAY", target_entity_id="ENT_SIR_WALTER",
            metrics={
                "affinity":      RelationshipMetric(value=0.7, inertia=0.55, evidence_strength="moderate", last_updated_fabula=300),
                "power_dynamic": RelationshipMetric(value=-0.5, inertia=0.7, evidence_strength="moderate", last_updated_fabula=300),
            },
        ),
        # Anne ↔ Mrs Smith — true friendship.
        RelationshipEdge(
            source_entity_id="ENT_ANNE", target_entity_id="ENT_MRS_SMITH",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.7, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_MRS_SMITH", target_entity_id="ENT_ANNE",
            metrics={
                "affinity": RelationshipMetric(value=0.9, inertia=0.7, evidence_strength="strong", last_updated_fabula=1050),
            },
        ),
        # Admiral & Sophia Croft → Wentworth — kin.
        RelationshipEdge(
            source_entity_id="ENT_ADMIRAL_CROFT", target_entity_id="ENT_WENTWORTH",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.75, evidence_strength="strong", last_updated_fabula=400),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_SOPHIA_CROFT", target_entity_id="ENT_WENTWORTH",
            metrics={
                "affinity": RelationshipMetric(value=0.95, inertia=0.8, evidence_strength="strong", last_updated_fabula=400),
            },
        ),
    ],
)
