"""Romeo and Juliet — high-fidelity WorldStateV1 test fixture.

Authored against the current ingestion prompts. Demonstrates all five
CausalEdge modalities, per-axis ``RelationshipMetric`` (only observed
axes populated), explicit ``evidence_strength`` everywhere, named-latent
WORLD_ traits (the family feud, fate, patriarchal authority) wired as
common-cause parents to co-driven events, ``state_timeline`` snapshots
whose inertia bumps up under shock, and initial entity locations that
match each character's first appearance.
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, RelationshipMetric, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    # ── LOCATIONS ──────────────────────────────────────────────────────
    locations={
        "LOC_VERONA_STREETS": Location(
            name="Streets of Verona",
            description="Public squares and lanes where the Montague–Capulet feud erupts in brawls and duels.",
            ambient_state={
                "tension": AmbientVector(value=0.8, volatility=0.5, evidence_strength="strong"),
                "danger": AmbientVector(value=0.6, volatility=0.5, evidence_strength="strong"),
            },
        ),
        "LOC_PRINCE_PALACE": Location(
            name="Prince Escalus' Palace",
            description="Civic seat where Prince Escalus enforces the peace and pronounces sentence.",
            ambient_state={
                "formality": AmbientVector(value=0.85, volatility=0.2, evidence_strength="moderate"),
            },
        ),
        "LOC_CAPULET_HOUSE": Location(
            name="Capulet House",
            description="The Capulet family estate; site of the masquerade ball where the lovers meet.",
            ambient_state={
                "festivity": AmbientVector(value=0.7, volatility=0.3, evidence_strength="strong"),
                "tension": AmbientVector(value=0.4, volatility=0.4, evidence_strength="moderate"),
            },
        ),
        "LOC_CAPULET_ORCHARD": Location(
            name="Capulet Orchard / Balcony",
            description="The garden beneath Juliet's window where the lovers exchange vows in secret.",
            ambient_state={
                "romance": AmbientVector(value=0.9, volatility=0.2, evidence_strength="strong"),
                "concealment": AmbientVector(value=0.7, volatility=0.3, evidence_strength="moderate"),
            },
        ),
        "LOC_JULIETS_CHAMBER": Location(
            name="Juliet's Chamber",
            description="Juliet's private bedroom; site of the consummated marriage and her sleeping-potion 'death'.",
            ambient_state={
                "secrecy": AmbientVector(value=0.8, volatility=0.3, evidence_strength="strong"),
            },
        ),
        "LOC_FRIAR_CELL": Location(
            name="Friar Laurence's Cell",
            description="Modest monastic chambers where the friar marries the lovers and brews the sleeping potion.",
            ambient_state={
                "safety": AmbientVector(value=0.7, volatility=0.3, evidence_strength="moderate"),
                "secrecy": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_MANTUA": Location(
            name="Mantua",
            description="Neighbouring city where Romeo lives in exile after killing Tybalt; cut off from Verona by plague-quarantine.",
            ambient_state={
                "isolation": AmbientVector(value=0.75, volatility=0.3, evidence_strength="strong"),
            },
        ),
        "LOC_APOTHECARY": Location(
            name="Mantuan Apothecary",
            description="Impoverished apothecary's shop in Mantua where Romeo buys the lethal poison.",
            ambient_state={
                "poverty": AmbientVector(value=0.8, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_CAPULET_CRYPT": Location(
            name="Capulet Crypt",
            description="Family tomb outside Verona where Juliet is laid out and where both lovers (and Paris) die.",
            ambient_state={
                "danger": AmbientVector(value=0.85, volatility=0.3, evidence_strength="strong"),
                "grief": AmbientVector(value=0.95, volatility=0.1, evidence_strength="strong"),
            },
        ),
    },

    # ── OBJECTS ─────────────────────────────────────────────────────────
    objects={
        "OBJ_INVITATION": NarrativeObject(
            id="OBJ_INVITATION", name="Capulet Ball Invitation",
            location_id=None, owner_id="ENT_ROMEO",
            properties={"event": "masquerade_ball", "state": "intercepted"},
            affordances=[Affordance(action="grant_entry", target_type="Entity")],
        ),
        "OBJ_ROPE_LADDER": NarrativeObject(
            id="OBJ_ROPE_LADDER", name="Rope Ladder",
            location_id="LOC_CAPULET_ORCHARD", owner_id="ENT_NURSE",
            properties={"state": "delivered"},
            affordances=[Affordance(action="climb", target_type="Location")],
        ),
        "OBJ_SLEEPING_POTION": NarrativeObject(
            id="OBJ_SLEEPING_POTION", name="Sleeping Potion",
            location_id="LOC_FRIAR_CELL", owner_id="ENT_FRIAR_LAURENCE",
            properties={"duration_hours": "42", "effect": "deathlike_coma"},
            affordances=[Affordance(action="fake_death", target_type="Entity")],
        ),
        "OBJ_FRIAR_LETTER": NarrativeObject(
            id="OBJ_FRIAR_LETTER", name="Friar Laurence's Letter to Romeo",
            location_id="LOC_FRIAR_CELL", owner_id="ENT_FRIAR_JOHN",
            properties={"content": "the_potion_plan", "state": "undelivered"},
            affordances=[Affordance(action="inform", target_type="Entity")],
        ),
        "OBJ_POISON": NarrativeObject(
            id="OBJ_POISON", name="Apothecary's Poison",
            location_id="LOC_APOTHECARY", owner_id="ENT_ROMEO",
            properties={"lethality": "instant"},
            affordances=[Affordance(action="kill", target_type="Entity")],
        ),
        "OBJ_DAGGER": NarrativeObject(
            id="OBJ_DAGGER", name="Romeo's Dagger",
            location_id=None, owner_id="ENT_ROMEO",
            properties={"state": "sheathed"},
            affordances=[Affordance(action="stab", target_type="Entity")],
        ),
    },

    # ── ENTITIES ────────────────────────────────────────────────────────
    entities={
        "ENT_ROMEO": Entity(
            id="ENT_ROMEO", name="Romeo Montague",
            location_id="LOC_VERONA_STREETS", status="healthy",
            traits={
                "passion": TraitVector(value=0.85, inertia=0.45, evidence_strength="strong"),
                "impulsiveness": TraitVector(value=0.75, inertia=0.55, evidence_strength="strong"),
                "devotion": TraitVector(value=0.5, inertia=0.4, evidence_strength="moderate"),
                "courage": TraitVector(value=0.6, inertia=0.5, evidence_strength="moderate"),
                "despair": TraitVector(value=0.3, inertia=0.3, evidence_strength="moderate"),
                "guilt": TraitVector(value=0.1, inertia=0.25, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_ROSALINE", perceived_state="Rosaline is the only girl I can ever love",
                       confidence=0.8, inertia=0.3, evidence_strength="strong"),
                Belief(target_id="ENT_TYBALT", perceived_state="Tybalt is my enemy by birthright",
                       confidence=0.85, inertia=0.45, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_ROMEO_MEETS_JULIET",
                    traits={
                        "devotion": TraitVector(value=0.95, inertia=0.55, evidence_strength="strong"),
                        "passion": TraitVector(value=0.95, inertia=0.55, evidence_strength="strong"),
                    },
                    beliefs_invalidated=["ENT_ROSALINE"],
                    beliefs_added=[
                        Belief(target_id="ENT_JULIET", perceived_state="Juliet is the only woman I have ever truly loved",
                               confidence=1.0, inertia=0.7, established_at_fabula=200, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=400, triggered_by="EVT_SECRET_MARRIAGE",
                    location_id="LOC_FRIAR_CELL"),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_ROMEO_KILLS_TYBALT",
                    traits={
                        "guilt": TraitVector(value=0.7, inertia=0.4, evidence_strength="strong"),
                        "despair": TraitVector(value=0.7, inertia=0.4, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_ROMEO_EXILED",
                    location_id="LOC_MANTUA"),
                EntityStateSnapshot(fabula_time=1450, triggered_by="EVT_BALTHASAR_REPORTS_DEATH",
                    traits={
                        "despair": TraitVector(value=1.0, inertia=0.55, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_JULIET", perceived_state="Juliet is dead",
                               confidence=0.95, inertia=0.85, established_at_fabula=1450, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_ROMEO_DRINKS_POISON",
                    status="dead",
                    location_id="LOC_CAPULET_CRYPT"),
            ],
        ),
        "ENT_JULIET": Entity(
            id="ENT_JULIET", name="Juliet Capulet",
            location_id="LOC_CAPULET_HOUSE", status="healthy",
            traits={
                "obedience": TraitVector(value=0.7, inertia=0.5, evidence_strength="strong"),
                "courage": TraitVector(value=0.5, inertia=0.4, evidence_strength="moderate"),
                "devotion": TraitVector(value=0.4, inertia=0.4, evidence_strength="moderate"),
                "maturity": TraitVector(value=0.4, inertia=0.4, evidence_strength="moderate"),
                "desperation": TraitVector(value=0.1, inertia=0.25, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_CAPULET", perceived_state="My father expects me to marry whomever he chooses",
                       confidence=0.9, inertia=0.6, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_ROMEO_MEETS_JULIET",
                    traits={
                        "devotion": TraitVector(value=0.95, inertia=0.55, evidence_strength="strong"),
                        "courage": TraitVector(value=0.7, inertia=0.5, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_ROMEO", perceived_state="Romeo is my true love despite our families' feud",
                               confidence=0.95, inertia=0.7, established_at_fabula=200, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=400, triggered_by="EVT_SECRET_MARRIAGE",
                    location_id="LOC_FRIAR_CELL"),
                EntityStateSnapshot(fabula_time=800, triggered_by="EVT_ROMEO_SPENDS_NIGHT",
                    location_id="LOC_JULIETS_CHAMBER"),
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_CAPULET_PROMISES_PARIS",
                    traits={
                        "desperation": TraitVector(value=0.85, inertia=0.4, evidence_strength="strong"),
                        "obedience": TraitVector(value=0.2, inertia=0.55, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_JULIET_TAKES_POTION",
                    status="unconscious",
                    traits={
                        "courage": TraitVector(value=0.85, inertia=0.55, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_JULIET_LAID_IN_CRYPT",
                    location_id="LOC_CAPULET_CRYPT"),
                EntityStateSnapshot(fabula_time=1650, triggered_by="EVT_JULIET_AWAKES",
                    status="healthy"),
                EntityStateSnapshot(fabula_time=1700, triggered_by="EVT_JULIET_STABS_SELF",
                    status="dead"),
            ],
        ),
        "ENT_TYBALT": Entity(
            id="ENT_TYBALT", name="Tybalt Capulet",
            location_id="LOC_VERONA_STREETS", status="healthy",
            traits={
                "aggression": TraitVector(value=0.9, inertia=0.65, evidence_strength="strong"),
                "family_honour": TraitVector(value=0.95, inertia=0.7, evidence_strength="strong"),
                "swordsmanship": TraitVector(value=0.9, inertia=0.75, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_ROMEO", perceived_state="Romeo's intrusion at our ball is an insult that demands blood",
                       confidence=0.95, inertia=0.7, established_at_fabula=300, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_TYBALT_KILLS_MERCUTIO",
                    traits={"aggression": TraitVector(value=1.0, inertia=0.7, evidence_strength="strong")}),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_ROMEO_KILLS_TYBALT",
                    status="dead"),
            ],
        ),
        "ENT_MERCUTIO": Entity(
            id="ENT_MERCUTIO", name="Mercutio",
            location_id="LOC_VERONA_STREETS", status="healthy",
            traits={
                "wit": TraitVector(value=0.9, inertia=0.65, evidence_strength="strong"),
                "volatility": TraitVector(value=0.8, inertia=0.5, evidence_strength="strong"),
                "loyalty": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
                "anger": TraitVector(value=0.4, inertia=0.3, evidence_strength="weak"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_TYBALT_KILLS_MERCUTIO",
                    traits={"anger": TraitVector(value=0.95, inertia=0.45, evidence_strength="strong")},
                    beliefs_added=[
                        Belief(target_id="ENT_ROMEO", perceived_state="Romeo's pacifism is vile submission",
                               confidence=0.7, inertia=0.5, established_at_fabula=600, evidence_strength="strong"),
                    ],
                    status="dead"),
            ],
        ),
        "ENT_BENVOLIO": Entity(
            id="ENT_BENVOLIO", name="Benvolio Montague",
            location_id="LOC_VERONA_STREETS", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
                "level_headedness": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
                "courage": TraitVector(value=0.6, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_ROMEO", perceived_state="Romeo's lovesickness for Rosaline can be cured by a new beauty",
                       confidence=0.7, inertia=0.4, evidence_strength="moderate"),
            ],
        ),
        "ENT_FRIAR_LAURENCE": Entity(
            id="ENT_FRIAR_LAURENCE", name="Friar Laurence",
            location_id="LOC_FRIAR_CELL", status="healthy",
            traits={
                "wisdom": TraitVector(value=0.7, inertia=0.65, evidence_strength="strong"),
                "benevolence": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                "caution": TraitVector(value=0.5, inertia=0.45, evidence_strength="moderate"),
                "guilt": TraitVector(value=0.05, inertia=0.2, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_ROMEO", perceived_state="This marriage may at last heal the Montague-Capulet feud",
                       confidence=0.6, inertia=0.5, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1700, triggered_by="EVT_JULIET_STABS_SELF",
                    traits={
                        "guilt": TraitVector(value=0.85, inertia=0.45, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_FRIAR_JOHN": Entity(
            id="ENT_FRIAR_JOHN", name="Friar John",
            location_id="LOC_FRIAR_CELL", status="healthy",
            traits={
                "obedience": TraitVector(value=0.7, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1400, triggered_by="EVT_PLAGUE_QUARANTINE_FRIAR_JOHN",
                    traits={"obedience": TraitVector(value=0.7, inertia=0.55, evidence_strength="moderate")}),
            ],
        ),
        "ENT_BALTHASAR": Entity(
            id="ENT_BALTHASAR", name="Balthasar (Romeo's Servant)",
            location_id="LOC_VERONA_STREETS", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_JULIET", perceived_state="Juliet is dead",
                       confidence=0.9, inertia=0.6, established_at_fabula=1350, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1450, triggered_by="EVT_BALTHASAR_REPORTS_DEATH",
                    location_id="LOC_MANTUA"),
            ],
        ),
        "ENT_CAPULET": Entity(
            id="ENT_CAPULET", name="Lord Capulet",
            location_id="LOC_CAPULET_HOUSE", status="healthy",
            traits={
                "authority": TraitVector(value=0.9, inertia=0.7, evidence_strength="strong"),
                "anger": TraitVector(value=0.4, inertia=0.35, evidence_strength="moderate"),
                "paternal_care": TraitVector(value=0.55, inertia=0.5, evidence_strength="moderate"),
                "family_honour": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_JULIET", perceived_state="Juliet's grief is for Tybalt and a Paris match will cheer her",
                       confidence=0.7, inertia=0.55, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_JULIET_REFUSES_PARIS",
                    traits={
                        "anger": TraitVector(value=0.9, inertia=0.5, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=1750, triggered_by="EVT_FAMILIES_RECONCILE",
                    traits={
                        "family_honour": TraitVector(value=0.5, inertia=0.55, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_LADY_CAPULET": Entity(
            id="ENT_LADY_CAPULET", name="Lady Capulet",
            location_id="LOC_CAPULET_HOUSE", status="healthy",
            traits={
                "coldness": TraitVector(value=0.6, inertia=0.55, evidence_strength="moderate"),
                "obedience": TraitVector(value=0.8, inertia=0.6, evidence_strength="moderate"),
            },
            beliefs=[],
        ),
        "ENT_NURSE": Entity(
            id="ENT_NURSE", name="The Nurse",
            location_id="LOC_CAPULET_HOUSE", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.7, inertia=0.55, evidence_strength="strong"),
                "pragmatism": TraitVector(value=0.7, inertia=0.5, evidence_strength="moderate"),
                "warmth": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_JULIET", perceived_state="Juliet should marry Paris now that Romeo is exiled",
                       confidence=0.6, inertia=0.4, established_at_fabula=950, evidence_strength="moderate"),
            ],
        ),
        "ENT_MONTAGUE": Entity(
            id="ENT_MONTAGUE", name="Lord Montague",
            location_id="LOC_VERONA_STREETS", status="healthy",
            traits={
                "family_honour": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "paternal_care": TraitVector(value=0.6, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1750, triggered_by="EVT_FAMILIES_RECONCILE",
                    traits={
                        "family_honour": TraitVector(value=0.5, inertia=0.55, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_PRINCE_ESCALUS": Entity(
            id="ENT_PRINCE_ESCALUS", name="Prince Escalus of Verona",
            location_id="LOC_PRINCE_PALACE", status="healthy",
            traits={
                "authority": TraitVector(value=0.95, inertia=0.75, evidence_strength="strong"),
                "justice": TraitVector(value=0.75, inertia=0.6, evidence_strength="strong"),
                "weariness": TraitVector(value=0.4, inertia=0.4, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_MONTAGUE", perceived_state="Both houses are equally guilty of disturbing the peace",
                       confidence=0.9, inertia=0.65, evidence_strength="strong"),
            ],
        ),
        "ENT_PARIS": Entity(
            id="ENT_PARIS", name="Count Paris",
            location_id="LOC_CAPULET_HOUSE", status="healthy",
            traits={
                "courtesy": TraitVector(value=0.7, inertia=0.55, evidence_strength="moderate"),
                "entitlement": TraitVector(value=0.6, inertia=0.5, evidence_strength="moderate"),
                "courage": TraitVector(value=0.5, inertia=0.45, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_JULIET", perceived_state="Juliet will come to love me once we marry",
                       confidence=0.6, inertia=0.45, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1500, triggered_by="EVT_ROMEO_KILLS_PARIS",
                    status="dead",
                    location_id="LOC_CAPULET_CRYPT"),
            ],
        ),
        "ENT_ROSALINE": Entity(
            id="ENT_ROSALINE", name="Rosaline",
            location_id="LOC_CAPULET_HOUSE", status="healthy",
            traits={
                "chastity": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[],
        ),
    },

    # ── EVENTS ──────────────────────────────────────────────────────────
    events=[
        EventNode(id="EVT_OPENING_BRAWL", fabula_time=50, syuzhet_index=1,
                  event_type="outcome", actor_ids=["ENT_TYBALT", "ENT_BENVOLIO"], target_ids=[],
                  description="Servants of the two houses brawl in the streets; Tybalt and Benvolio are drawn in."),
        EventNode(id="EVT_PRINCE_DECREE", fabula_time=80, syuzhet_index=2,
                  event_type="choice", actor_ids=["ENT_PRINCE_ESCALUS"],
                  target_ids=["ENT_MONTAGUE", "ENT_CAPULET"],
                  description="Prince Escalus decrees that any further breach of the peace shall be punishable by death."),
        EventNode(id="EVT_PARIS_PROPOSAL", fabula_time=100, syuzhet_index=3,
                  event_type="choice", actor_ids=["ENT_PARIS"], target_ids=["ENT_CAPULET"],
                  description="Paris asks Capulet for Juliet's hand; Capulet asks him to wait and invites him to the ball."),
        EventNode(id="EVT_BENVOLIO_PERSUADES_ROMEO", fabula_time=120, syuzhet_index=4,
                  event_type="choice", actor_ids=["ENT_BENVOLIO"], target_ids=["ENT_ROMEO"],
                  description="Benvolio and Mercutio persuade the lovesick Romeo to crash the Capulet ball to see Rosaline."),
        EventNode(id="EVT_CAPULET_BALL", fabula_time=180, syuzhet_index=5,
                  event_type="outcome", actor_ids=["ENT_CAPULET"], target_ids=[],
                  description="The Capulet masquerade ball begins."),
        EventNode(id="EVT_ROMEO_MEETS_JULIET", fabula_time=200, syuzhet_index=6,
                  event_type="outcome", actor_ids=["ENT_ROMEO", "ENT_JULIET"], target_ids=[],
                  description="At the ball Romeo and Juliet meet and instantly fall in love; Romeo's love for Rosaline is forgotten."),
        EventNode(id="EVT_TYBALT_RECOGNISES_ROMEO", fabula_time=220, syuzhet_index=7,
                  event_type="revelation", actor_ids=["ENT_TYBALT"], target_ids=["ENT_ROMEO"],
                  description="Tybalt recognises Romeo at the ball and is enraged; Capulet forbids bloodshed in his house."),
        EventNode(id="EVT_BALCONY_SCENE", fabula_time=300, syuzhet_index=8,
                  event_type="choice", actor_ids=["ENT_ROMEO", "ENT_JULIET"], target_ids=[],
                  description="In the orchard Romeo overhears Juliet vow her love; they exchange marriage promises."),
        EventNode(id="EVT_SECRET_MARRIAGE", fabula_time=400, syuzhet_index=9,
                  event_type="choice", actor_ids=["ENT_FRIAR_LAURENCE", "ENT_ROMEO", "ENT_JULIET"], target_ids=[],
                  description="Friar Laurence secretly marries Romeo and Juliet, hoping to reconcile the feuding houses."),
        EventNode(id="EVT_TYBALT_CHALLENGES_ROMEO", fabula_time=500, syuzhet_index=10,
                  event_type="choice", actor_ids=["ENT_TYBALT"], target_ids=["ENT_ROMEO"],
                  description="Tybalt finds Romeo in the street and challenges him to a duel; Romeo, now Tybalt's secret kinsman, refuses."),
        EventNode(id="EVT_TYBALT_KILLS_MERCUTIO", fabula_time=600, syuzhet_index=11,
                  event_type="outcome", actor_ids=["ENT_TYBALT"], target_ids=["ENT_MERCUTIO"],
                  description="Mercutio fights Tybalt in Romeo's stead and is fatally wounded; he curses both houses with his dying breath."),
        EventNode(id="EVT_ROMEO_KILLS_TYBALT", fabula_time=700, syuzhet_index=12,
                  event_type="choice", actor_ids=["ENT_ROMEO"], target_ids=["ENT_TYBALT"],
                  description="Grief-stricken and guilty, Romeo confronts and slays Tybalt."),
        EventNode(id="EVT_ROMEO_EXILED", fabula_time=900, syuzhet_index=13,
                  event_type="choice", actor_ids=["ENT_PRINCE_ESCALUS"], target_ids=["ENT_ROMEO"],
                  description="The Prince banishes Romeo from Verona on pain of death."),
        EventNode(id="EVT_ROMEO_SPENDS_NIGHT", fabula_time=800, syuzhet_index=14,
                  event_type="choice", actor_ids=["ENT_ROMEO", "ENT_JULIET"], target_ids=[],
                  description="Before fleeing to Mantua, Romeo secretly spends the wedding night with Juliet."),
        EventNode(id="EVT_CAPULET_PROMISES_PARIS", fabula_time=1000, syuzhet_index=15,
                  event_type="choice", actor_ids=["ENT_CAPULET"], target_ids=["ENT_JULIET", "ENT_PARIS"],
                  description="Misreading her grief, Capulet promises Juliet to Paris and accelerates the wedding."),
        EventNode(id="EVT_JULIET_REFUSES_PARIS", fabula_time=1100, syuzhet_index=16,
                  event_type="choice", actor_ids=["ENT_JULIET"], target_ids=["ENT_CAPULET"],
                  description="Juliet refuses; Capulet threatens to disown her, and Lady Capulet rejects her plea for delay."),
        EventNode(id="EVT_FRIAR_GIVES_POTION", fabula_time=1150, syuzhet_index=17,
                  event_type="choice", actor_ids=["ENT_FRIAR_LAURENCE"], target_ids=["ENT_JULIET"],
                  description="Friar Laurence gives Juliet a 42-hour death-mimicking potion and promises to send Friar John to inform Romeo."),
        EventNode(id="EVT_JULIET_TAKES_POTION", fabula_time=1200, syuzhet_index=18,
                  event_type="choice", actor_ids=["ENT_JULIET"], target_ids=[],
                  description="On the eve of the Paris wedding Juliet drinks the potion and falls into a deathlike coma."),
        EventNode(id="EVT_JULIET_LAID_IN_CRYPT", fabula_time=1300, syuzhet_index=19,
                  event_type="outcome", actor_ids=["ENT_CAPULET"], target_ids=["ENT_JULIET"],
                  description="Believing her dead, the Capulets lay Juliet in the family crypt."),
        EventNode(id="EVT_PLAGUE_QUARANTINE_FRIAR_JOHN", fabula_time=1400, syuzhet_index=20,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_FRIAR_JOHN"],
                  description="A plague-quarantine prevents Friar John from delivering the friar's letter to Romeo in Mantua."),
        EventNode(id="EVT_BALTHASAR_REPORTS_DEATH", fabula_time=1450, syuzhet_index=21,
                  event_type="revelation", actor_ids=["ENT_BALTHASAR"], target_ids=["ENT_ROMEO"],
                  description="Romeo's servant Balthasar arrives in Mantua and reports Juliet's apparent death."),
        EventNode(id="EVT_ROMEO_BUYS_POISON", fabula_time=1500, syuzhet_index=22,
                  event_type="choice", actor_ids=["ENT_ROMEO"], target_ids=[],
                  description="Romeo buys lethal poison from a destitute Mantuan apothecary."),
        EventNode(id="EVT_ROMEO_KILLS_PARIS", fabula_time=1550, syuzhet_index=23,
                  event_type="choice", actor_ids=["ENT_ROMEO"], target_ids=["ENT_PARIS"],
                  description="At the crypt Paris confronts Romeo as a vandal; Romeo kills him in the ensuing fight."),
        EventNode(id="EVT_ROMEO_DRINKS_POISON", fabula_time=1600, syuzhet_index=24,
                  event_type="choice", actor_ids=["ENT_ROMEO"], target_ids=[],
                  description="Believing Juliet truly dead, Romeo drinks the poison beside her body."),
        EventNode(id="EVT_JULIET_AWAKES", fabula_time=1650, syuzhet_index=25,
                  event_type="revelation", actor_ids=[], target_ids=["ENT_JULIET"],
                  description="Juliet awakens to find Romeo dead beside her."),
        EventNode(id="EVT_JULIET_STABS_SELF", fabula_time=1700, syuzhet_index=26,
                  event_type="choice", actor_ids=["ENT_JULIET"], target_ids=[],
                  description="Juliet stabs herself with Romeo's dagger and joins him in death."),
        EventNode(id="EVT_FAMILIES_RECONCILE", fabula_time=1750, syuzhet_index=27,
                  event_type="outcome", actor_ids=["ENT_MONTAGUE", "ENT_CAPULET"], target_ids=[],
                  description="At the tomb Friar Laurence recounts the lovers' story; the families reconcile and end the feud."),
    ],

    # ── CAUSAL TOPOLOGY ─────────────────────────────────────────────────
    causal_topology=[
        # ── chain_reaction ──
        CausalEdge(source_id="EVT_OPENING_BRAWL", target_id="EVT_PRINCE_DECREE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=50, propagation_delay=30),
        CausalEdge(source_id="EVT_PARIS_PROPOSAL", target_id="EVT_BENVOLIO_PERSUADES_ROMEO",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=100, propagation_delay=20),
        CausalEdge(source_id="EVT_BENVOLIO_PERSUADES_ROMEO", target_id="EVT_CAPULET_BALL",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=120, propagation_delay=60),
        CausalEdge(source_id="EVT_CAPULET_BALL", target_id="EVT_ROMEO_MEETS_JULIET",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=6.0, fabula_time=180, propagation_delay=20),
        CausalEdge(source_id="EVT_ROMEO_MEETS_JULIET", target_id="EVT_TYBALT_RECOGNISES_ROMEO",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=6.0, fabula_time=200, propagation_delay=20),
        CausalEdge(source_id="EVT_ROMEO_MEETS_JULIET", target_id="EVT_BALCONY_SCENE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200, propagation_delay=100),
        CausalEdge(source_id="EVT_BALCONY_SCENE", target_id="EVT_SECRET_MARRIAGE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300, propagation_delay=100),
        CausalEdge(source_id="EVT_TYBALT_RECOGNISES_ROMEO", target_id="EVT_TYBALT_CHALLENGES_ROMEO",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=220, propagation_delay=280),
        CausalEdge(source_id="EVT_TYBALT_CHALLENGES_ROMEO", target_id="EVT_TYBALT_KILLS_MERCUTIO",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500, propagation_delay=100),
        CausalEdge(source_id="EVT_TYBALT_KILLS_MERCUTIO", target_id="EVT_ROMEO_KILLS_TYBALT",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=600, propagation_delay=100),
        CausalEdge(source_id="EVT_ROMEO_KILLS_TYBALT", target_id="EVT_ROMEO_EXILED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700, propagation_delay=200),
        CausalEdge(source_id="EVT_PRINCE_DECREE", target_id="EVT_ROMEO_EXILED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=80, propagation_delay=820),
        CausalEdge(source_id="EVT_SECRET_MARRIAGE", target_id="EVT_ROMEO_SPENDS_NIGHT",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=400, propagation_delay=400),
        CausalEdge(source_id="EVT_ROMEO_EXILED", target_id="EVT_CAPULET_PROMISES_PARIS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=900, propagation_delay=100),
        CausalEdge(source_id="EVT_CAPULET_PROMISES_PARIS", target_id="EVT_JULIET_REFUSES_PARIS",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1000, propagation_delay=100),
        CausalEdge(source_id="EVT_JULIET_REFUSES_PARIS", target_id="EVT_FRIAR_GIVES_POTION",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1100, propagation_delay=50),
        CausalEdge(source_id="EVT_FRIAR_GIVES_POTION", target_id="EVT_JULIET_TAKES_POTION",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1150, propagation_delay=50),
        CausalEdge(source_id="EVT_JULIET_TAKES_POTION", target_id="EVT_JULIET_LAID_IN_CRYPT",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1200, propagation_delay=100),
        CausalEdge(source_id="EVT_PLAGUE_QUARANTINE_FRIAR_JOHN", target_id="EVT_BALTHASAR_REPORTS_DEATH",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1400, propagation_delay=50),
        CausalEdge(source_id="EVT_BALTHASAR_REPORTS_DEATH", target_id="EVT_ROMEO_BUYS_POISON",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1450, propagation_delay=50),
        CausalEdge(source_id="EVT_ROMEO_BUYS_POISON", target_id="EVT_ROMEO_KILLS_PARIS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1500, propagation_delay=50),
        CausalEdge(source_id="EVT_ROMEO_KILLS_PARIS", target_id="EVT_ROMEO_DRINKS_POISON",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1550, propagation_delay=50),
        CausalEdge(source_id="EVT_ROMEO_DRINKS_POISON", target_id="EVT_JULIET_AWAKES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=5.0, fabula_time=1600, propagation_delay=50),
        CausalEdge(source_id="EVT_JULIET_AWAKES", target_id="EVT_JULIET_STABS_SELF",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1650, propagation_delay=50),
        CausalEdge(source_id="EVT_JULIET_STABS_SELF", target_id="EVT_FAMILIES_RECONCILE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1700, propagation_delay=50),

        # ── mutation (Event → Entity trait) ──
        CausalEdge(source_id="EVT_ROMEO_MEETS_JULIET", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=200,
                   trait_target="passion", trait_delta=0.2),
        CausalEdge(source_id="EVT_ROMEO_MEETS_JULIET", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=200,
                   trait_target="devotion", trait_delta=0.6),
        CausalEdge(source_id="EVT_ROMEO_MEETS_JULIET", target_id="ENT_JULIET",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=200,
                   trait_target="devotion", trait_delta=0.7),
        CausalEdge(source_id="EVT_TYBALT_KILLS_MERCUTIO", target_id="ENT_MERCUTIO",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=600,
                   trait_target="anger", trait_delta=1.0),
        CausalEdge(source_id="EVT_ROMEO_KILLS_TYBALT", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=700,
                   trait_target="guilt", trait_delta=0.7),
        CausalEdge(source_id="EVT_ROMEO_KILLS_TYBALT", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700,
                   trait_target="despair", trait_delta=0.5),
        CausalEdge(source_id="EVT_CAPULET_PROMISES_PARIS", target_id="ENT_JULIET",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000,
                   trait_target="desperation", trait_delta=0.8),
        CausalEdge(source_id="EVT_JULIET_REFUSES_PARIS", target_id="ENT_CAPULET",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1100,
                   trait_target="anger", trait_delta=0.6),
        CausalEdge(source_id="EVT_JULIET_TAKES_POTION", target_id="ENT_JULIET",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1200,
                   trait_target="courage", trait_delta=0.5),
        CausalEdge(source_id="EVT_BALTHASAR_REPORTS_DEATH", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1450,
                   trait_target="despair", trait_delta=1.0),
        CausalEdge(source_id="EVT_ROMEO_DRINKS_POISON", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1600,
                   trait_target="courage", trait_delta=-1.0),
        CausalEdge(source_id="EVT_JULIET_STABS_SELF", target_id="ENT_FRIAR_LAURENCE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1700,
                   trait_target="guilt", trait_delta=0.9),
        CausalEdge(source_id="EVT_FAMILIES_RECONCILE", target_id="ENT_CAPULET",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1750,
                   trait_target="family_honour", trait_delta=-0.4),
        CausalEdge(source_id="EVT_FAMILIES_RECONCILE", target_id="ENT_MONTAGUE",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1750,
                   trait_target="family_honour", trait_delta=-0.4),
        # — Coverage mutations for previously un-mutated significant events —
        CausalEdge(source_id="EVT_PRINCE_DECREE", target_id="ENT_MONTAGUE",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=80,
                   trait_target="restraint", trait_delta=0.4),
        CausalEdge(source_id="EVT_PRINCE_DECREE", target_id="ENT_CAPULET",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=80,
                   trait_target="restraint", trait_delta=0.4),
        CausalEdge(source_id="EVT_PARIS_PROPOSAL", target_id="ENT_JULIET",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=100,
                   trait_target="dread", trait_delta=0.3),
        CausalEdge(source_id="EVT_PARIS_PROPOSAL", target_id="ENT_CAPULET",
                   causality_type="mutation", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=100,
                   trait_target="expectation", trait_delta=0.5),
        CausalEdge(source_id="EVT_BENVOLIO_PERSUADES_ROMEO", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="emotional", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=120,
                   trait_target="distraction", trait_delta=0.5),
        CausalEdge(source_id="EVT_BENVOLIO_PERSUADES_ROMEO", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="emotional", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=120,
                   trait_target="hope", trait_delta=0.4),
        CausalEdge(source_id="EVT_TYBALT_CHALLENGES_ROMEO", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=500,
                   trait_target="shame", trait_delta=0.6),
        CausalEdge(source_id="EVT_TYBALT_CHALLENGES_ROMEO", target_id="ENT_TYBALT",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=500,
                   trait_target="fury", trait_delta=0.5),
        CausalEdge(source_id="EVT_ROMEO_EXILED", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900,
                   trait_target="despair", trait_delta=0.5),
        CausalEdge(source_id="EVT_FRIAR_GIVES_POTION", target_id="ENT_JULIET",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1150,
                   trait_target="resolve", trait_delta=0.6),
        CausalEdge(source_id="EVT_JULIET_LAID_IN_CRYPT", target_id="ENT_CAPULET",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1300,
                   trait_target="grief", trait_delta=0.7),
        CausalEdge(source_id="EVT_PLAGUE_QUARANTINE_FRIAR_JOHN", target_id="ENT_FRIAR_JOHN",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1400,
                   trait_target="helplessness", trait_delta=0.7),
        CausalEdge(source_id="EVT_ROMEO_KILLS_PARIS", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1550,
                   trait_target="guilt", trait_delta=0.2),

        # ── mutation_social ──
        CausalEdge(source_id="EVT_ROMEO_MEETS_JULIET", target_id="ENT_ROMEO",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=200,
                   trait_target="affinity", trait_delta=0.95, rel_counterpart_id="ENT_JULIET"),
        CausalEdge(source_id="EVT_ROMEO_MEETS_JULIET", target_id="ENT_JULIET",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=200,
                   trait_target="affinity", trait_delta=0.95, rel_counterpart_id="ENT_ROMEO"),
        CausalEdge(source_id="EVT_ROMEO_KILLS_TYBALT", target_id="ENT_CAPULET",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=700,
                   trait_target="affinity", trait_delta=-0.7, rel_counterpart_id="ENT_ROMEO"),
        CausalEdge(source_id="EVT_JULIET_REFUSES_PARIS", target_id="ENT_CAPULET",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1100,
                   trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_JULIET"),
        CausalEdge(source_id="EVT_JULIET_REFUSES_PARIS", target_id="ENT_JULIET",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1100,
                   trait_target="fear", trait_delta=0.5, rel_counterpart_id="ENT_CAPULET"),
        CausalEdge(source_id="EVT_TYBALT_KILLS_MERCUTIO", target_id="ENT_ROMEO",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=600,
                   trait_target="affinity", trait_delta=-0.9, rel_counterpart_id="ENT_TYBALT"),
        CausalEdge(source_id="EVT_FAMILIES_RECONCILE", target_id="ENT_CAPULET",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1750,
                   trait_target="affinity", trait_delta=0.6, rel_counterpart_id="ENT_MONTAGUE"),
        CausalEdge(source_id="EVT_FAMILIES_RECONCILE", target_id="ENT_MONTAGUE",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1750,
                   trait_target="affinity", trait_delta=0.6, rel_counterpart_id="ENT_CAPULET"),

        # ── affordance_gate ──
        CausalEdge(source_id="OBJ_INVITATION", target_id="EVT_ROMEO_MEETS_JULIET",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=180),
        CausalEdge(source_id="OBJ_SLEEPING_POTION", target_id="EVT_JULIET_TAKES_POTION",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1200),
        CausalEdge(source_id="OBJ_POISON", target_id="EVT_ROMEO_DRINKS_POISON",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1600),
        CausalEdge(source_id="OBJ_DAGGER", target_id="EVT_JULIET_STABS_SELF",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1700),
        CausalEdge(source_id="ENT_PRINCE_ESCALUS", target_id="EVT_PRINCE_DECREE",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=80),
        CausalEdge(source_id="ENT_FRIAR_LAURENCE", target_id="EVT_SECRET_MARRIAGE",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=400),

        # ── ambient_propagation ──
        CausalEdge(source_id="LOC_VERONA_STREETS", target_id="ENT_TYBALT",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=500),
        CausalEdge(source_id="LOC_CAPULET_CRYPT", target_id="ENT_JULIET",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=1650),

        # ── WORLD_ → Event (named-latent common-cause wiring) ──
        CausalEdge(source_id="WORLD_FAMILY_FEUD", target_id="EVT_OPENING_BRAWL",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=50),
        CausalEdge(source_id="WORLD_FAMILY_FEUD", target_id="EVT_TYBALT_RECOGNISES_ROMEO",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=220),
        CausalEdge(source_id="WORLD_FAMILY_FEUD", target_id="EVT_TYBALT_KILLS_MERCUTIO",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=600),
        CausalEdge(source_id="WORLD_FAMILY_FEUD", target_id="EVT_SECRET_MARRIAGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=400),
        CausalEdge(source_id="WORLD_PATRIARCHAL_AUTHORITY", target_id="EVT_PARIS_PROPOSAL",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=100),
        CausalEdge(source_id="WORLD_PATRIARCHAL_AUTHORITY", target_id="EVT_CAPULET_PROMISES_PARIS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1000),
        CausalEdge(source_id="WORLD_PATRIARCHAL_AUTHORITY", target_id="EVT_JULIET_REFUSES_PARIS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=1100),
        CausalEdge(source_id="WORLD_FATE", target_id="EVT_PLAGUE_QUARANTINE_FRIAR_JOHN",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1400),
        CausalEdge(source_id="WORLD_FATE", target_id="EVT_BALTHASAR_REPORTS_DEATH",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1450),
        CausalEdge(source_id="WORLD_FATE", target_id="EVT_ROMEO_DRINKS_POISON",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1600),
        CausalEdge(source_id="WORLD_FATE", target_id="EVT_JULIET_AWAKES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1650),
    ],

    # ── SPATIAL TOPOLOGY ────────────────────────────────────────────────
    spatial_topology=[
        SpatialEdge(source_id="LOC_VERONA_STREETS", target_id="LOC_CAPULET_HOUSE"),
        SpatialEdge(source_id="LOC_VERONA_STREETS", target_id="LOC_PRINCE_PALACE"),
        SpatialEdge(source_id="LOC_VERONA_STREETS", target_id="LOC_FRIAR_CELL"),
        SpatialEdge(source_id="LOC_CAPULET_HOUSE", target_id="LOC_CAPULET_ORCHARD"),
        SpatialEdge(source_id="LOC_CAPULET_ORCHARD", target_id="LOC_JULIETS_CHAMBER"),
        SpatialEdge(source_id="LOC_CAPULET_HOUSE", target_id="LOC_JULIETS_CHAMBER"),
        SpatialEdge(source_id="LOC_CAPULET_HOUSE", target_id="LOC_CAPULET_CRYPT"),
        SpatialEdge(source_id="LOC_VERONA_STREETS", target_id="LOC_MANTUA"),
        SpatialEdge(source_id="LOC_MANTUA", target_id="LOC_APOTHECARY"),
        SpatialEdge(source_id="LOC_MANTUA", target_id="LOC_CAPULET_CRYPT"),
        SpatialEdge(source_id="LOC_FRIAR_CELL", target_id="LOC_MANTUA"),
        SpatialEdge(source_id="LOC_FRIAR_CELL", target_id="LOC_CAPULET_CRYPT"),
    ],

    # ── INFORMATION TOPOLOGY ────────────────────────────────────────────
    information_topology=[
        InformationEdge(source_id="ENT_PRINCE_ESCALUS", target_ids=["ENT_MONTAGUE", "ENT_CAPULET"],
                        medium="proclamation", is_encrypted=False,
                        established_at_fabula=80, terminated_at_fabula=80,
                        discovered_at_syuzhet=2, evidence_strength="strong"),
        InformationEdge(source_id="ENT_BENVOLIO", target_ids=["ENT_ROMEO"],
                        medium="speech", is_encrypted=False,
                        established_at_fabula=120, terminated_at_fabula=120,
                        discovered_at_syuzhet=4, evidence_strength="strong"),
        InformationEdge(source_id="ENT_JULIET", target_ids=["ENT_ROMEO"],
                        medium="overheard_vow", is_encrypted=False,
                        established_at_fabula=300, terminated_at_fabula=300,
                        discovered_at_syuzhet=8, evidence_strength="strong"),
        InformationEdge(source_id="ENT_NURSE", target_ids=["ENT_ROMEO", "ENT_JULIET"],
                        medium="messenger", is_encrypted=True,
                        established_at_fabula=350, terminated_at_fabula=400,
                        discovered_at_syuzhet=8, evidence_strength="moderate"),
        InformationEdge(source_id="ENT_FRIAR_LAURENCE", target_ids=["ENT_JULIET"],
                        medium="speech", is_encrypted=True,
                        established_at_fabula=1150, terminated_at_fabula=1150,
                        discovered_at_syuzhet=17, evidence_strength="strong"),
        InformationEdge(source_id="OBJ_FRIAR_LETTER", target_ids=["ENT_ROMEO"],
                        medium="letter", is_encrypted=True,
                        established_at_fabula=1200, terminated_at_fabula=1400,
                        discovered_at_syuzhet=17, evidence_strength="moderate"),
        InformationEdge(source_id="ENT_BALTHASAR", target_ids=["ENT_ROMEO"],
                        medium="speech", is_encrypted=False,
                        established_at_fabula=1450, terminated_at_fabula=1450,
                        discovered_at_syuzhet=21, evidence_strength="strong"),
        InformationEdge(source_id="ENT_FRIAR_LAURENCE", target_ids=["ENT_PRINCE_ESCALUS", "ENT_CAPULET", "ENT_MONTAGUE"],
                        medium="confession", is_encrypted=False,
                        established_at_fabula=1750, terminated_at_fabula=1750,
                        discovered_at_syuzhet=27, evidence_strength="strong"),
    ],

    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_FAMILY_FEUD": GlobalTrait(
            id="WORLD_FAMILY_FEUD",
            name="Montague–Capulet Feud",
            description="An 'ancient grudge' that long predates the play and conditions every character — servants, kinsmen, lovers — to read members of the other house as enemies first and people second.",
            category="social_structure",
            magnitude=TraitVector(value=0.85, inertia=0.75, evidence_strength="strong"),
            affected_domains=["social", "psychological", "betrayal"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=1750, triggered_by="EVT_FAMILIES_RECONCILE",
                    magnitude=TraitVector(value=0.15, inertia=0.45, evidence_strength="strong"),
                    description="The lovers' deaths shock the families into reconciliation; the feud collapses, though the wound is fresh and the new peace is unstable."),
            ],
        ),
        "WORLD_PATRIARCHAL_AUTHORITY": GlobalTrait(
            id="WORLD_PATRIARCHAL_AUTHORITY",
            name="Patriarchal Marriage Authority",
            description="The Veronese norm by which fathers dispose of their daughters in marriage. Drives Capulet's promise of Juliet to Paris and Juliet's catastrophic refusal.",
            category="social_structure",
            magnitude=TraitVector(value=0.8, inertia=0.8, evidence_strength="strong"),
            affected_domains=["social", "emotional"],
        ),
        "WORLD_FATE": GlobalTrait(
            id="WORLD_FATE",
            name="Star-Crossed Fate",
            description="The play's named-latent fatalism — 'star-crossed lovers', the prologue's promise of doom, the plague that delays the friar's letter. Operates as a common-cause parent over the cluster of events that would otherwise look like contrived bad luck.",
            category="cosmology",
            magnitude=TraitVector(value=0.55, inertia=0.9, evidence_strength="moderate"),
            affected_domains=["psychological", "epistemic"],
        ),
        "WORLD_HONOUR_CULTURE": GlobalTrait(
            id="WORLD_HONOUR_CULTURE",
            name="Italian Honour Culture",
            description="The duelling code that turns insults into death-matches; intensifies the feud and forces Mercutio to fight for Romeo's reputation.",
            category="social_structure",
            magnitude=TraitVector(value=0.7, inertia=0.7, evidence_strength="strong"),
            affected_domains=["social", "betrayal"],
        ),
    },

    # ── SOCIAL TOPOLOGY ─────────────────────────────────────────────────
    social_topology=[
        # Romeo ↔ Juliet — instant, total, mutual love.
        RelationshipEdge(
            source_entity_id="ENT_ROMEO", target_entity_id="ENT_JULIET",
            metrics={
                "affinity": RelationshipMetric(value=1.0, inertia=0.55, evidence_strength="strong", last_updated_fabula=200),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_JULIET", target_entity_id="ENT_ROMEO",
            metrics={
                "affinity": RelationshipMetric(value=1.0, inertia=0.55, evidence_strength="strong", last_updated_fabula=200),
            },
        ),
        # Romeo ↔ Tybalt — enmity then deadly opposition.
        RelationshipEdge(
            source_entity_id="ENT_TYBALT", target_entity_id="ENT_ROMEO",
            metrics={
                "affinity": RelationshipMetric(value=-0.95, inertia=0.5, evidence_strength="strong", last_updated_fabula=220),
                "fear":     RelationshipMetric(value=0.1, inertia=0.2, evidence_strength="weak", last_updated_fabula=220),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_ROMEO", target_entity_id="ENT_TYBALT",
            metrics={
                "affinity": RelationshipMetric(value=-0.6, inertia=0.45, evidence_strength="strong", last_updated_fabula=600),
                "fear":     RelationshipMetric(value=0.3, inertia=0.2, evidence_strength="moderate", last_updated_fabula=500),
            },
        ),
        # Mercutio ↔ Romeo — friendship strained by the duel.
        RelationshipEdge(
            source_entity_id="ENT_MERCUTIO", target_entity_id="ENT_ROMEO",
            metrics={
                "affinity": RelationshipMetric(value=0.6, inertia=0.4, evidence_strength="strong", last_updated_fabula=600),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_ROMEO", target_entity_id="ENT_MERCUTIO",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.5, evidence_strength="strong", last_updated_fabula=600),
            },
        ),
        # Benvolio → Romeo — older-brother concern.
        RelationshipEdge(
            source_entity_id="ENT_BENVOLIO", target_entity_id="ENT_ROMEO",
            metrics={
                "affinity":      RelationshipMetric(value=0.85, inertia=0.5, evidence_strength="strong", last_updated_fabula=120),
                "power_dynamic": RelationshipMetric(value=0.2, inertia=0.6, evidence_strength="moderate", last_updated_fabula=120),
            },
        ),
        # Capulet → Juliet — paternal love souring into authority and threat.
        RelationshipEdge(
            source_entity_id="ENT_CAPULET", target_entity_id="ENT_JULIET",
            metrics={
                "affinity":      RelationshipMetric(value=-0.2, inertia=0.45, evidence_strength="strong", last_updated_fabula=1100),
                "power_dynamic": RelationshipMetric(value=0.85, inertia=0.75, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_JULIET", target_entity_id="ENT_CAPULET",
            metrics={
                "affinity":      RelationshipMetric(value=0.0, inertia=0.4, evidence_strength="moderate", last_updated_fabula=1100),
                "fear":          RelationshipMetric(value=0.7, inertia=0.2, evidence_strength="strong", last_updated_fabula=1100),
                "power_dynamic": RelationshipMetric(value=-0.85, inertia=0.75, evidence_strength="strong", last_updated_fabula=1100),
            },
        ),
        # Juliet ↔ Nurse — quasi-maternal trust frayed by the Paris counsel.
        RelationshipEdge(
            source_entity_id="ENT_JULIET", target_entity_id="ENT_NURSE",
            metrics={
                "affinity":      RelationshipMetric(value=0.4, inertia=0.45, evidence_strength="strong", last_updated_fabula=950),
                "power_dynamic": RelationshipMetric(value=0.3, inertia=0.6, evidence_strength="moderate", last_updated_fabula=950),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_NURSE", target_entity_id="ENT_JULIET",
            metrics={
                "affinity":      RelationshipMetric(value=0.85, inertia=0.55, evidence_strength="strong", last_updated_fabula=400),
                "power_dynamic": RelationshipMetric(value=-0.3, inertia=0.6, evidence_strength="moderate", last_updated_fabula=400),
            },
        ),
        # Friar Laurence ↔ Romeo — pastoral mentorship.
        RelationshipEdge(
            source_entity_id="ENT_FRIAR_LAURENCE", target_entity_id="ENT_ROMEO",
            metrics={
                "affinity":      RelationshipMetric(value=0.7, inertia=0.55, evidence_strength="strong", last_updated_fabula=400),
                "power_dynamic": RelationshipMetric(value=0.5, inertia=0.65, evidence_strength="strong", last_updated_fabula=400),
            },
        ),
        # Capulet ↔ Montague — feud that collapses in the final scene.
        RelationshipEdge(
            source_entity_id="ENT_CAPULET", target_entity_id="ENT_MONTAGUE",
            metrics={
                "affinity": RelationshipMetric(value=-0.4, inertia=0.5, evidence_strength="strong", last_updated_fabula=1750),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_MONTAGUE", target_entity_id="ENT_CAPULET",
            metrics={
                "affinity": RelationshipMetric(value=-0.4, inertia=0.5, evidence_strength="strong", last_updated_fabula=1750),
            },
        ),
        # Paris → Juliet — courteous entitlement.
        RelationshipEdge(
            source_entity_id="ENT_PARIS", target_entity_id="ENT_JULIET",
            metrics={
                "affinity":      RelationshipMetric(value=0.5, inertia=0.4, evidence_strength="moderate", last_updated_fabula=100),
                "power_dynamic": RelationshipMetric(value=0.4, inertia=0.65, evidence_strength="moderate", last_updated_fabula=100),
            },
        ),
        # Prince → both houses — civic authority.
        RelationshipEdge(
            source_entity_id="ENT_PRINCE_ESCALUS", target_entity_id="ENT_CAPULET",
            metrics={
                "power_dynamic": RelationshipMetric(value=0.8, inertia=0.75, evidence_strength="strong", last_updated_fabula=80),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_PRINCE_ESCALUS", target_entity_id="ENT_MONTAGUE",
            metrics={
                "power_dynamic": RelationshipMetric(value=0.8, inertia=0.75, evidence_strength="strong", last_updated_fabula=80),
            },
        ),
    ],
)
