"""Romeo and Juliet — high-fidelity WorldStateV1 test fixture.

Quality checklist (all five causality modalities, varied force/evidence,
trait_target/trait_delta, state_timeline, rich beliefs, info edges).
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    # ── LOCATIONS ──────────────────────────────────────────────────────
    locations={
        "LOC_VERONA_STREETS": Location(
            name="Streets of Verona", description="Public space where the feud plays out in brawls and duels.",
            ambient_state={"tension": AmbientVector(value=0.8, volatility=0.5), "danger": AmbientVector(value=0.6, volatility=0.5)},
        ),
        "LOC_CAPULET_HOUSE": Location(
            name="Capulet House", description="The Capulet estate, site of the fateful ball.",
            ambient_state={"festivity": AmbientVector(value=0.7, volatility=0.3), "secrecy": AmbientVector(value=0.5, volatility=0.4)},
        ),
        "LOC_CAPULET_ORCHARD": Location(
            name="Capulet Orchard / Balcony", description="The garden beneath Juliet's window where the lovers declare their vows.",
            ambient_state={"romance": AmbientVector(value=0.9, volatility=0.2)},
        ),
        "LOC_FRIAR_CELL": Location(
            name="Friar Laurence's Cell", description="Modest quarters where the friar marries the lovers and concocts the sleeping potion.",
            ambient_state={"safety": AmbientVector(value=0.7, volatility=0.3), "secrecy": AmbientVector(value=0.8, volatility=0.2)},
        ),
        "LOC_CAPULET_CRYPT": Location(
            name="Capulet Crypt", description="Family tomb where both lovers die.",
            ambient_state={"danger": AmbientVector(value=0.9, volatility=0.2), "grief": AmbientVector(value=0.9, volatility=0.1)},
        ),
        "LOC_MANTUA": Location(
            name="Mantua", description="City of Romeo's exile.",
            ambient_state={"isolation": AmbientVector(value=0.7, volatility=0.3)},
        ),
        "LOC_JULIETS_CHAMBER": Location(
            name="Juliet's Chamber", description="Private room where the marriage is consummated and Juliet takes the potion.",
            ambient_state={"secrecy": AmbientVector(value=0.8, volatility=0.3)},
        ),
    },

    # ── OBJECTS ─────────────────────────────────────────────────────────
    objects={
        "OBJ_SLEEPING_POTION": NarrativeObject(
            id="OBJ_SLEEPING_POTION", name="Sleeping Potion",
            location_id="LOC_FRIAR_CELL", owner_id="ENT_FRIAR_LAURENCE",
            properties={"duration": "42 hours", "effect": "deathlike coma"},
            affordances=[Affordance(action="fake_death", target_type="Entity")],
        ),
        "OBJ_POISON": NarrativeObject(
            id="OBJ_POISON", name="Apothecary's Poison",
            location_id="LOC_MANTUA", owner_id="ENT_ROMEO",
            properties={"lethality": "instant"},
            affordances=[Affordance(action="kill_self", target_type="Entity")],
        ),
        "OBJ_DAGGER": NarrativeObject(
            id="OBJ_DAGGER", name="Romeo's Dagger",
            location_id=None, owner_id="ENT_ROMEO",
            properties={},
            affordances=[Affordance(action="stab", target_type="Entity")],
        ),
        "OBJ_INVITATION": NarrativeObject(
            id="OBJ_INVITATION", name="Capulet Ball Invitation",
            location_id=None, owner_id="ENT_ROMEO",
            properties={"event": "masquerade_ball"},
            affordances=[Affordance(action="grant_entry", target_type="Entity")],
        ),
    },

    # ── ENTITIES ────────────────────────────────────────────────────────
    entities={
        "ENT_ROMEO": Entity(
            id="ENT_ROMEO", name="Romeo Montague",
            location_id="LOC_VERONA_STREETS", status="healthy",
            traits={
                "passion": TraitVector(value=0.8, inertia=0.3),
                "impulsiveness": TraitVector(value=0.7, inertia=0.4),
                "devotion": TraitVector(value=0.5, inertia=0.3),
                "despair": TraitVector(value=0.3, inertia=0.2),
                "courage": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_JULIET", perceived_state="Juliet is the only woman I have ever truly loved", confidence=0.95, inertia=0.5, established_at_fabula=200),
                Belief(target_id="ENT_FRIAR_LAURENCE", perceived_state="The friar will help us be together", confidence=0.85, inertia=0.5),
                Belief(target_id="ENT_JULIET", perceived_state="Juliet is dead (FALSE — she is in a deathlike coma)", confidence=0.95, inertia=0.8, established_at_fabula=1500),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_ROMEO_MEETS_JULIET",
                    traits={"devotion": TraitVector(value=0.9, inertia=0.3), "passion": TraitVector(value=0.95, inertia=0.3)}),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_ROMEO_KILLS_TYBALT",
                    traits={"despair": TraitVector(value=0.8, inertia=0.2)},
                    location_id="LOC_MANTUA"),
                EntityStateSnapshot(fabula_time=1700, triggered_by="EVT_ROMEO_DRINKS_POISON",
                    status="dead"),
            ],
        ),
        "ENT_JULIET": Entity(
            id="ENT_JULIET", name="Juliet Capulet",
            location_id="LOC_CAPULET_HOUSE", status="healthy",
            traits={
                "devotion": TraitVector(value=0.4, inertia=0.3),
                "courage": TraitVector(value=0.5, inertia=0.3),
                "obedience": TraitVector(value=0.7, inertia=0.4),
                "desperation": TraitVector(value=0.1, inertia=0.2),
                "maturity": TraitVector(value=0.4, inertia=0.3),
            },
            beliefs=[
                Belief(target_id="ENT_ROMEO", perceived_state="Romeo is my true love despite the feud", confidence=0.95, inertia=0.6, established_at_fabula=200),
                Belief(target_id="ENT_FRIAR_LAURENCE", perceived_state="The friar's plan will reunite us", confidence=0.8, inertia=0.5, established_at_fabula=1200),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=200, triggered_by="EVT_ROMEO_MEETS_JULIET",
                    traits={"devotion": TraitVector(value=0.9, inertia=0.3), "obedience": TraitVector(value=0.4, inertia=0.4)}),
                EntityStateSnapshot(fabula_time=1300, triggered_by="EVT_JULIET_TAKES_POTION",
                    status="unconscious"),
                EntityStateSnapshot(fabula_time=1800, triggered_by="EVT_JULIET_STABS_SELF",
                    status="dead"),
            ],
        ),
        "ENT_TYBALT": Entity(
            id="ENT_TYBALT", name="Tybalt Capulet",
            location_id="LOC_CAPULET_HOUSE", status="healthy",
            traits={
                "aggression": TraitVector(value=0.9, inertia=0.5),
                "family_honour": TraitVector(value=0.95, inertia=0.6),
                "swordsmanship": TraitVector(value=0.9, inertia=0.7),
            },
            beliefs=[
                Belief(target_id="ENT_ROMEO", perceived_state="Romeo's presence at the ball is an insult that demands blood", confidence=0.95, inertia=0.6),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_TYBALT_KILLS_MERCUTIO",
                    traits={"aggression": TraitVector(value=1.0, inertia=0.5)}),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_ROMEO_KILLS_TYBALT",
                    status="dead"),
            ],
        ),
        "ENT_MERCUTIO": Entity(
            id="ENT_MERCUTIO", name="Mercutio",
            location_id="LOC_VERONA_STREETS", status="healthy",
            traits={
                "wit": TraitVector(value=0.9, inertia=0.6),
                "volatility": TraitVector(value=0.8, inertia=0.4),
                "loyalty": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_ROMEO", perceived_state="Romeo's pacifism is vile submission", confidence=0.7, inertia=0.4, established_at_fabula=600),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_TYBALT_KILLS_MERCUTIO",
                    status="dead"),
            ],
        ),
        "ENT_FRIAR_LAURENCE": Entity(
            id="ENT_FRIAR_LAURENCE", name="Friar Laurence",
            location_id="LOC_FRIAR_CELL", status="healthy",
            traits={
                "wisdom": TraitVector(value=0.7, inertia=0.6),
                "benevolence": TraitVector(value=0.8, inertia=0.5),
                "caution": TraitVector(value=0.5, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_ROMEO", perceived_state="This marriage may heal the Montague-Capulet rift", confidence=0.6, inertia=0.4),
            ],
        ),
        "ENT_CAPULET": Entity(
            id="ENT_CAPULET", name="Lord Capulet",
            location_id="LOC_CAPULET_HOUSE", status="healthy",
            traits={
                "authority": TraitVector(value=0.9, inertia=0.6),
                "anger": TraitVector(value=0.5, inertia=0.3),
                "paternal_care": TraitVector(value=0.5, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_JULIET", perceived_state="Juliet grieves for Tybalt and a marriage to Paris will cheer her", confidence=0.7, inertia=0.5),
            ],
        ),
        "ENT_PARIS": Entity(
            id="ENT_PARIS", name="Count Paris",
            location_id="LOC_CAPULET_HOUSE", status="healthy",
            traits={
                "courtesy": TraitVector(value=0.7, inertia=0.5),
                "entitlement": TraitVector(value=0.6, inertia=0.4),
            },
            beliefs=[
                Belief(target_id="ENT_JULIET", perceived_state="Juliet will come to love me once we marry", confidence=0.6, inertia=0.4),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_ROMEO_KILLS_PARIS",
                    status="dead"),
            ],
        ),
        "ENT_NURSE": Entity(
            id="ENT_NURSE", name="The Nurse",
            location_id="LOC_CAPULET_HOUSE", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.7, inertia=0.4),
                "pragmatism": TraitVector(value=0.6, inertia=0.5),
            },
            beliefs=[
                Belief(target_id="ENT_JULIET", perceived_state="Juliet should marry Paris now that Romeo is exiled", confidence=0.6, inertia=0.4, established_at_fabula=900),
            ],
        ),
        "ENT_PRINCE_ESCALUS": Entity(
            id="ENT_PRINCE_ESCALUS", name="Prince Escalus",
            location_id="LOC_VERONA_STREETS", status="healthy",
            traits={
                "authority": TraitVector(value=0.9, inertia=0.7),
                "justice": TraitVector(value=0.8, inertia=0.6),
            },
            beliefs=[],
        ),
        "ENT_BENVOLIO": Entity(
            id="ENT_BENVOLIO", name="Benvolio Montague",
            location_id="LOC_VERONA_STREETS", status="healthy",
            traits={
                "peacefulness": TraitVector(value=0.8, inertia=0.5),
                "loyalty": TraitVector(value=0.7, inertia=0.5),
            },
            beliefs=[],
        ),
    },

    # ── EVENTS ──────────────────────────────────────────────────────────
    events=[
        EventNode(id="EVT_STREET_BRAWL", fabula_time=100, syuzhet_index=1,
                  event_type="outcome", actor_ids=[], target_ids=[],
                  description="Servants of Montague and Capulet brawl in the streets; Prince Escalus threatens death for further violence."),
        EventNode(id="EVT_ROMEO_MEETS_JULIET", fabula_time=200, syuzhet_index=2,
                  event_type="revelation", actor_ids=["ENT_ROMEO"], target_ids=["ENT_JULIET"],
                  description="Romeo and Juliet meet at the Capulet ball and fall instantly in love."),
        EventNode(id="EVT_BALCONY_SCENE", fabula_time=300, syuzhet_index=3,
                  event_type="choice", actor_ids=["ENT_ROMEO", "ENT_JULIET"], target_ids=[],
                  description="Romeo and Juliet declare their love and agree to marry despite the feud."),
        EventNode(id="EVT_SECRET_MARRIAGE", fabula_time=400, syuzhet_index=4,
                  event_type="choice", actor_ids=["ENT_ROMEO", "ENT_JULIET", "ENT_FRIAR_LAURENCE"], target_ids=[],
                  description="Friar Laurence secretly marries Romeo and Juliet."),
        EventNode(id="EVT_TYBALT_CHALLENGES_ROMEO", fabula_time=500, syuzhet_index=5,
                  event_type="choice", actor_ids=["ENT_TYBALT"], target_ids=["ENT_ROMEO"],
                  description="Tybalt challenges Romeo to a duel; Romeo refuses, considering Tybalt his new kinsman."),
        EventNode(id="EVT_TYBALT_KILLS_MERCUTIO", fabula_time=600, syuzhet_index=6,
                  event_type="outcome", actor_ids=["ENT_TYBALT"], target_ids=["ENT_MERCUTIO"],
                  description="Mercutio fights Tybalt and is fatally wounded under Romeo's arm. He curses both houses."),
        EventNode(id="EVT_ROMEO_KILLS_TYBALT", fabula_time=700, syuzhet_index=7,
                  event_type="choice", actor_ids=["ENT_ROMEO"], target_ids=["ENT_TYBALT"],
                  description="Grief-stricken Romeo confronts and kills Tybalt in a rage."),
        EventNode(id="EVT_ROMEO_EXILED", fabula_time=800, syuzhet_index=8,
                  event_type="outcome", actor_ids=["ENT_PRINCE_ESCALUS"], target_ids=["ENT_ROMEO"],
                  description="Prince Escalus exiles Romeo from Verona under penalty of death."),
        EventNode(id="EVT_CAPULET_FORCES_MARRIAGE", fabula_time=900, syuzhet_index=9,
                  event_type="choice", actor_ids=["ENT_CAPULET"], target_ids=["ENT_JULIET", "ENT_PARIS"],
                  description="Lord Capulet insists Juliet marry Count Paris, threatening to disown her."),
        EventNode(id="EVT_JULIET_CONSUMMATION", fabula_time=850, syuzhet_index=10,
                  event_type="choice", actor_ids=["ENT_ROMEO", "ENT_JULIET"], target_ids=[],
                  description="Romeo and Juliet consummate their marriage before Romeo departs for Mantua."),
        EventNode(id="EVT_FRIAR_PLAN", fabula_time=1100, syuzhet_index=11,
                  event_type="choice", actor_ids=["ENT_FRIAR_LAURENCE"], target_ids=["ENT_JULIET"],
                  description="Friar Laurence gives Juliet the sleeping potion and promises to send word to Romeo."),
        EventNode(id="EVT_JULIET_TAKES_POTION", fabula_time=1300, syuzhet_index=12,
                  event_type="choice", actor_ids=["ENT_JULIET"], target_ids=[],
                  description="Juliet drinks the potion and falls into a deathlike coma."),
        EventNode(id="EVT_MESSAGE_FAILS", fabula_time=1400, syuzhet_index=13,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_ROMEO"],
                  description="Friar John's message cannot reach Romeo due to plague quarantine."),
        EventNode(id="EVT_ROMEO_LEARNS_JULIET_DEAD", fabula_time=1500, syuzhet_index=14,
                  event_type="revelation", actor_ids=[], target_ids=["ENT_ROMEO"],
                  description="Romeo learns from Balthasar that Juliet is dead (false information)."),
        EventNode(id="EVT_ROMEO_KILLS_PARIS", fabula_time=1600, syuzhet_index=15,
                  event_type="outcome", actor_ids=["ENT_ROMEO"], target_ids=["ENT_PARIS"],
                  description="Romeo encounters Paris at the crypt and kills him in a fight."),
        EventNode(id="EVT_ROMEO_DRINKS_POISON", fabula_time=1700, syuzhet_index=16,
                  event_type="choice", actor_ids=["ENT_ROMEO"], target_ids=[],
                  description="Believing Juliet dead, Romeo drinks poison and dies beside her."),
        EventNode(id="EVT_JULIET_STABS_SELF", fabula_time=1800, syuzhet_index=17,
                  event_type="choice", actor_ids=["ENT_JULIET"], target_ids=[],
                  description="Juliet awakens, finds Romeo dead, and stabs herself with his dagger."),
        EventNode(id="EVT_FAMILIES_RECONCILE", fabula_time=1900, syuzhet_index=18,
                  event_type="outcome", actor_ids=["ENT_CAPULET"], target_ids=[],
                  description="The Montagues and Capulets discover the bodies and agree to end their feud."),
    ],

    # ── CAUSAL TOPOLOGY ─────────────────────────────────────────────────
    causal_topology=[
        # ── chain_reaction (Event → Event) ──
        CausalEdge(source_id="EVT_STREET_BRAWL", target_id="EVT_ROMEO_EXILED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=100, propagation_delay=700),
        CausalEdge(source_id="EVT_ROMEO_MEETS_JULIET", target_id="EVT_BALCONY_SCENE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200),
        CausalEdge(source_id="EVT_BALCONY_SCENE", target_id="EVT_SECRET_MARRIAGE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=300),
        CausalEdge(source_id="EVT_SECRET_MARRIAGE", target_id="EVT_TYBALT_CHALLENGES_ROMEO",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=400),
        CausalEdge(source_id="EVT_TYBALT_CHALLENGES_ROMEO", target_id="EVT_TYBALT_KILLS_MERCUTIO",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=500),
        CausalEdge(source_id="EVT_TYBALT_KILLS_MERCUTIO", target_id="EVT_ROMEO_KILLS_TYBALT",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=600),
        CausalEdge(source_id="EVT_ROMEO_KILLS_TYBALT", target_id="EVT_ROMEO_EXILED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=700),
        CausalEdge(source_id="EVT_ROMEO_EXILED", target_id="EVT_CAPULET_FORCES_MARRIAGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=800),
        CausalEdge(source_id="EVT_CAPULET_FORCES_MARRIAGE", target_id="EVT_FRIAR_PLAN",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900),
        CausalEdge(source_id="EVT_FRIAR_PLAN", target_id="EVT_JULIET_TAKES_POTION",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1100),
        CausalEdge(source_id="EVT_MESSAGE_FAILS", target_id="EVT_ROMEO_LEARNS_JULIET_DEAD",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1400),
        CausalEdge(source_id="EVT_ROMEO_LEARNS_JULIET_DEAD", target_id="EVT_ROMEO_DRINKS_POISON",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1500),
        CausalEdge(source_id="EVT_ROMEO_DRINKS_POISON", target_id="EVT_JULIET_STABS_SELF",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1700),
        CausalEdge(source_id="EVT_JULIET_STABS_SELF", target_id="EVT_FAMILIES_RECONCILE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1800),
        CausalEdge(source_id="EVT_ROMEO_EXILED", target_id="EVT_JULIET_CONSUMMATION",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=800),
        CausalEdge(source_id="EVT_ROMEO_LEARNS_JULIET_DEAD", target_id="EVT_ROMEO_KILLS_PARIS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1500),

        # ── mutation (Event → Entity trait/status) ──
        CausalEdge(source_id="EVT_ROMEO_MEETS_JULIET", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200,
                   trait_target="devotion", trait_delta=0.5),
        CausalEdge(source_id="EVT_ROMEO_MEETS_JULIET", target_id="ENT_JULIET",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=200,
                   trait_target="devotion", trait_delta=0.5),
        CausalEdge(source_id="EVT_TYBALT_KILLS_MERCUTIO", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600,
                   trait_target="despair", trait_delta=0.5),
        CausalEdge(source_id="EVT_ROMEO_KILLS_TYBALT", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=700,
                   trait_target="impulsiveness", trait_delta=0.2),
        CausalEdge(source_id="EVT_CAPULET_FORCES_MARRIAGE", target_id="ENT_JULIET",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900,
                   trait_target="desperation", trait_delta=0.6),
        CausalEdge(source_id="EVT_CAPULET_FORCES_MARRIAGE", target_id="ENT_JULIET",
                   causality_type="mutation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=900,
                   trait_target="obedience", trait_delta=-0.4),
        CausalEdge(source_id="EVT_ROMEO_LEARNS_JULIET_DEAD", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1500,
                   trait_target="despair", trait_delta=0.7),
        CausalEdge(source_id="EVT_ROMEO_EXILED", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=800,
                   trait_target="despair", trait_delta=0.3),
        CausalEdge(source_id="EVT_FRIAR_PLAN", target_id="ENT_JULIET",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1100,
                   trait_target="courage", trait_delta=0.2),
        CausalEdge(source_id="EVT_TYBALT_CHALLENGES_ROMEO", target_id="ENT_ROMEO",
                   causality_type="mutation", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=500,
                   trait_target="courage", trait_delta=0.1),

        # ── mutation_social (Event → Relationship) ──
        CausalEdge(source_id="EVT_ROMEO_MEETS_JULIET", target_id="ENT_ROMEO",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=200,
                   trait_target="affinity", trait_delta=0.8, rel_counterpart_id="ENT_JULIET"),
        CausalEdge(source_id="EVT_ROMEO_KILLS_TYBALT", target_id="ENT_JULIET",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=700,
                   trait_target="affinity", trait_delta=-0.2, rel_counterpart_id="ENT_ROMEO"),
        CausalEdge(source_id="EVT_TYBALT_KILLS_MERCUTIO", target_id="ENT_ROMEO",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600,
                   trait_target="affinity", trait_delta=-0.7, rel_counterpart_id="ENT_TYBALT"),
        CausalEdge(source_id="EVT_CAPULET_FORCES_MARRIAGE", target_id="ENT_JULIET",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900,
                   trait_target="affinity", trait_delta=-0.5, rel_counterpart_id="ENT_CAPULET"),

        # ── affordance_gate (State → Event) ──
        CausalEdge(source_id="OBJ_SLEEPING_POTION", target_id="EVT_JULIET_TAKES_POTION",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1300),
        CausalEdge(source_id="OBJ_POISON", target_id="EVT_ROMEO_DRINKS_POISON",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1700),
        CausalEdge(source_id="OBJ_DAGGER", target_id="EVT_JULIET_STABS_SELF",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1800),

        # ── ambient_propagation (State → State) ──
        CausalEdge(source_id="LOC_VERONA_STREETS", target_id="ENT_TYBALT",
                   causality_type="ambient_propagation", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=100),
        CausalEdge(source_id="ENT_ROMEO", target_id="ENT_JULIET",
                   causality_type="ambient_propagation", mechanism="emotional", evidence_strength="weak",
                   causal_force=3.0, fabula_time=1500),
    ],

    # ── SPATIAL TOPOLOGY ────────────────────────────────────────────────
    spatial_topology=[
        SpatialEdge(source_id="LOC_VERONA_STREETS", target_id="LOC_CAPULET_HOUSE"),
        SpatialEdge(source_id="LOC_CAPULET_HOUSE", target_id="LOC_CAPULET_ORCHARD"),
        SpatialEdge(source_id="LOC_CAPULET_HOUSE", target_id="LOC_JULIETS_CHAMBER"),
        SpatialEdge(source_id="LOC_CAPULET_HOUSE", target_id="LOC_CAPULET_CRYPT"),
        SpatialEdge(source_id="LOC_VERONA_STREETS", target_id="LOC_FRIAR_CELL"),
        SpatialEdge(source_id="LOC_VERONA_STREETS", target_id="LOC_MANTUA"),
        SpatialEdge(source_id="LOC_MANTUA", target_id="LOC_CAPULET_CRYPT"),
    ],

    # ── INFORMATION TOPOLOGY ────────────────────────────────────────────
    information_topology=[
        InformationEdge(source_id="ENT_ROMEO", target_ids=["ENT_JULIET"],
                        medium="overheard_confession", established_at_fabula=300),
        InformationEdge(source_id="ENT_FRIAR_LAURENCE", target_ids=["ENT_ROMEO", "ENT_JULIET"],
                        medium="confession", is_encrypted=True, established_at_fabula=400),
        InformationEdge(source_id="ENT_MERCUTIO", target_ids=["ENT_ROMEO", "ENT_TYBALT"],
                        medium="dying_curse", established_at_fabula=600),
        InformationEdge(source_id="ENT_FRIAR_LAURENCE", target_ids=["ENT_JULIET"],
                        medium="private_counsel", is_encrypted=True, established_at_fabula=1100),
        InformationEdge(source_id="ENT_FRIAR_LAURENCE", target_ids=["ENT_ROMEO"],
                        medium="letter", is_encrypted=True,
                        established_at_fabula=1100, terminated_at_fabula=1400),
        InformationEdge(source_id="ENT_FRIAR_LAURENCE", target_ids=["ENT_PRINCE_ESCALUS", "ENT_CAPULET"],
                        medium="public_confession", established_at_fabula=1900),
    ],

    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_BLOOD_FEUD": GlobalTrait(
            id="WORLD_BLOOD_FEUD",
            name="Montague-Capulet Blood Feud",
            description="Generations-old vendetta between the Montagues and Capulets that poisons all of Verona with violence and hatred.",
            category="social_structure",
            magnitude=TraitVector(value=0.9, inertia=0.7),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=100, triggered_by="EVT_STREET_BRAWL",
                    magnitude=TraitVector(value=0.95, inertia=0.7),
                    description="Renewed street violence intensifies the feud."),
                WorldTraitSnapshot(fabula_time=700, triggered_by="EVT_ROMEO_KILLS_TYBALT",
                    magnitude=TraitVector(value=1.0, inertia=0.8),
                    description="Tybalt's death at Romeo's hand escalates the feud to a lethal peak."),
                WorldTraitSnapshot(fabula_time=1900, triggered_by="EVT_FAMILIES_RECONCILE",
                    magnitude=TraitVector(value=0.2, inertia=0.3),
                    description="The lovers' deaths shock both families into reconciliation."),
            ],
        ),
        "WORLD_FATE_AND_STARS": GlobalTrait(
            id="WORLD_FATE_AND_STARS",
            name="Star-Crossed Fate",
            description="An inescapable current of tragic destiny that dooms the lovers from the start, driven by coincidence, poor timing, and cosmic irony.",
            category="cosmology",
            magnitude=TraitVector(value=0.6, inertia=0.8),
            affected_domains=["psychological", "epistemic"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=1400, triggered_by="EVT_MESSAGE_FAILS",
                    magnitude=TraitVector(value=0.9, inertia=0.9),
                    description="The plague quarantine prevents the friar's message — fate closes the last escape route."),
                WorldTraitSnapshot(fabula_time=1700, triggered_by="EVT_ROMEO_DRINKS_POISON",
                    magnitude=TraitVector(value=1.0, inertia=1.0),
                    description="Romeo dies moments before Juliet wakes — tragic timing fulfils the star-crossed prophecy."),
            ],
        ),
    },

    # ── SOCIAL TOPOLOGY ─────────────────────────────────────────────────
    social_topology=[
        RelationshipEdge(source_entity_id="ENT_ROMEO", target_entity_id="ENT_JULIET",
                         affinity=0.95, fear=0.2, power_dynamic=0.0, inertia=0.5, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_JULIET", target_entity_id="ENT_ROMEO",
                         affinity=0.95, fear=0.15, power_dynamic=0.0, inertia=0.5, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_ROMEO", target_entity_id="ENT_TYBALT",
                         affinity=-0.4, fear=0.3, power_dynamic=-0.1, inertia=0.3, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_TYBALT", target_entity_id="ENT_ROMEO",
                         affinity=-0.9, fear=0.1, power_dynamic=0.2, inertia=0.4, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_ROMEO", target_entity_id="ENT_MERCUTIO",
                         affinity=0.8, fear=0.05, power_dynamic=0.0, inertia=0.5, evidence_strength="strong"),
        RelationshipEdge(source_entity_id="ENT_MERCUTIO", target_entity_id="ENT_ROMEO",
                         affinity=0.7, fear=0.05, power_dynamic=0.1, inertia=0.5, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_JULIET", target_entity_id="ENT_CAPULET",
                         affinity=0.4, fear=0.5, power_dynamic=-0.6, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_CAPULET", target_entity_id="ENT_JULIET",
                         affinity=0.5, fear=0.0, power_dynamic=0.6, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_JULIET", target_entity_id="ENT_NURSE",
                         affinity=0.7, fear=0.0, power_dynamic=0.1, inertia=0.5, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_NURSE", target_entity_id="ENT_JULIET",
                         affinity=0.9, fear=0.1, power_dynamic=0.3, inertia=0.4),
        RelationshipEdge(source_entity_id="ENT_JULIET", target_entity_id="ENT_FRIAR_LAURENCE",
                         affinity=0.6, fear=0.1, power_dynamic=-0.3, inertia=0.4, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_ROMEO", target_entity_id="ENT_FRIAR_LAURENCE",
                         affinity=0.7, fear=0.1, power_dynamic=-0.3, inertia=0.5, evidence_strength="moderate"),
        RelationshipEdge(source_entity_id="ENT_PARIS", target_entity_id="ENT_JULIET",
                         affinity=0.6, fear=0.0, power_dynamic=0.2, inertia=0.3, evidence_strength="weak"),
    ],
)