# SPDX-FileCopyrightText: 2026 David Rae Wilmot
# SPDX-License-Identifier: AGPL-3.0-or-later

"""The Devil Wears Prada — high-fidelity WorldStateV1 fixture.

Lauren Weisberger / film 2006. Authored against the current ingestion
prompts. Demonstrates the five CausalEdge modalities, per-axis
``RelationshipMetric``, named-latent WORLD_ traits (the
fashion-industry status economy, the aspirational career-vs-personal-life
machine, the always-on assistant phone), standing ``Channel``s for
Miranda's chain of command, the Runway internal network, and Andrea's
fraying personal pipeline.
"""
from shadow_loom.models import (
    Channel,
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, RelationshipMetric,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait,
    NarrativeStyle,
)

world_state = WorldStateV1(
    narrative_style=NarrativeStyle(
        format='synopsis',
        target_word_min=200,
        target_word_max=560,
        prose_density='moderate',
        voice='contemporary urban synopsis; brisk indirect discourse; third-person past tense',
        style_exemplar="Andrea Sachs, a recent graduate of Brown University with a degree in English, moves to New York City with her best friend, Lily, a graduate student at Columbia. Andrea hopes to find a career in publishing and blankets the city with her résumé. She gets a surprise interview at the Elias-Clarke Group and is hired as junior assistant for Miranda Priestly, editor-in-chief of the fashion magazine Runway.",
        source_word_count=460,
    ),

    # ── LOCATIONS ──────────────────────────────────────────────────────
    locations={
        "LOC_ANDREA_APT": Location(
            name="Andrea & Lily's NYC Apartment",
            description="The shared apartment in Manhattan where Andrea and Lily start out, increasingly empty as Andrea's hours stretch.",
            ambient_state={
                "domestic_warmth":  AmbientVector(value=0.7, volatility=0.4, evidence_strength="strong"),
                "abandonment":      AmbientVector(value=0.3, volatility=0.5, evidence_strength="moderate"),
            },
        ),
        "LOC_RUNWAY_OFFICES": Location(
            name="Runway / Elias-Clarke Offices",
            description="The glass-and-steel headquarters where Miranda's chilled silences set the tempo for an entire industry.",
            ambient_state={
                "status_pressure":     AmbientVector(value=0.95, volatility=0.2, evidence_strength="strong"),
                "fashion_capital":     AmbientVector(value=0.95, volatility=0.1, evidence_strength="strong"),
                "constant_observation": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_CELEBRITY_PARTY": Location(
            name="Manhattan Celebrity Party",
            description="The crowded loft party where Andrea, in borrowed Chanel, meets Christian Collinsworth.",
            ambient_state={
                "glamour":   AmbientVector(value=0.9, volatility=0.3, evidence_strength="strong"),
                "temptation": AmbientVector(value=0.7, volatility=0.4, evidence_strength="strong"),
            },
        ),
        "LOC_PARIS_HOTEL": Location(
            name="Paris Fashion Week Hotel Suite",
            description="Miranda's suite during the Paris collections, where the curtain finally drops between editor and assistant.",
            ambient_state={
                "intimacy_under_pressure": AmbientVector(value=0.7, volatility=0.4, evidence_strength="strong"),
                "professional_apex":       AmbientVector(value=0.95, volatility=0.1, evidence_strength="strong"),
            },
        ),
        "LOC_DIOR_SHOW": Location(
            name="Dior Show, Paris",
            description="The runway tent where Andrea, mid-show, refuses Miranda's latest impossible demand.",
            ambient_state={
                "spectacle":   AmbientVector(value=0.95, volatility=0.2, evidence_strength="strong"),
                "public_break": AmbientVector(value=0.85, volatility=0.4, evidence_strength="strong"),
            },
        ),
        "LOC_ANDREA_PARENTS_HOME": Location(
            name="Andrea's Parents' Home",
            description="The Midwestern household where Andrea retreats after Paris — the moral baseline she had to leave to recognise.",
            ambient_state={
                "family_steadiness": AmbientVector(value=0.95, volatility=0.05, evidence_strength="strong"),
            },
        ),
        "LOC_HOSPITAL": Location(
            name="Manhattan Hospital",
            description="The room where Lily lies comatose after wrecking a car drunk.",
            ambient_state={
                "medical_anxiety":  AmbientVector(value=0.85, volatility=0.3, evidence_strength="strong"),
                "moral_inventory":  AmbientVector(value=0.85, volatility=0.3, evidence_strength="strong"),
            },
        ),
    },

    # ── OBJECTS ────────────────────────────────────────────────────────
    objects={
        "OBJ_ANDREA_RESUME": NarrativeObject(
            id="OBJ_ANDREA_RESUME", name="Andrea's Résumé",
            location_id="LOC_ANDREA_APT", owner_id="ENT_ANDREA",
            properties={"state": "blanketed_across_city", "credentials": "Brown English"},
            affordances=[Affordance(action="open_doors", target_type="Entity")],
        ),
        "OBJ_ASSISTANT_PHONE": NarrativeObject(
            id="OBJ_ASSISTANT_PHONE", name="Junior Assistant's Mobile Phone",
            location_id="LOC_RUNWAY_OFFICES", owner_id="ENT_ANDREA",
            properties={"state": "always_ringing", "function": "tether_to_miranda"},
            affordances=[
                Affordance(action="summon_andrea", target_type="Entity"),
                Affordance(action="rupture_personal_time", target_type="Entity"),
            ],
        ),
        "OBJ_BORROWED_WARDROBE": NarrativeObject(
            id="OBJ_BORROWED_WARDROBE", name="Runway's Borrowed Couture",
            location_id="LOC_RUNWAY_OFFICES", owner_id=None,
            properties={"state": "circulating", "function": "transform_andrea"},
            affordances=[Affordance(action="confer_status", target_type="Entity")],
        ),
        "OBJ_LILYS_CAR": NarrativeObject(
            id="OBJ_LILYS_CAR", name="The Car Lily Wrecks",
            location_id=None, owner_id="ENT_LILY",
            properties={"state": "wrecked", "function": "consequence_carrier"},
            affordances=[Affordance(action="cause_coma", target_type="Entity")],
        ),
        "OBJ_MIRANDA_PHONE": NarrativeObject(
            id="OBJ_MIRANDA_PHONE", name="Miranda's Personal Phone",
            location_id="LOC_DIOR_SHOW", owner_id="ENT_MIRANDA",
            properties={"state": "active", "function": "issue_demand"},
            affordances=[Affordance(action="issue_impossible_demand", target_type="Entity")],
        ),
    },

    # ── ENTITIES ────────────────────────────────────────────────────────
    entities={
        "ENT_ANDREA": Entity(
            id="ENT_ANDREA", name="Andrea Sachs",
            location_id="LOC_ANDREA_APT", status="healthy",
            traits={
                "literary_ambition":      TraitVector(value=0.85, inertia=0.7,  evidence_strength="strong"),
                "earnestness":            TraitVector(value=0.9,  inertia=0.85, evidence_strength="strong"),
                "moral_seriousness":      TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
                "self_doubt":             TraitVector(value=0.5,  inertia=0.5,  evidence_strength="moderate"),
                "fashion_assimilation":   TraitVector(value=0.0,  inertia=0.4,  evidence_strength="weak"),
                "loyalty_to_friends":     TraitVector(value=0.9,  inertia=0.8,  evidence_strength="strong"),
                "loyalty_to_alex":        TraitVector(value=0.85, inertia=0.7,  evidence_strength="strong"),
                "longing_for_new_yorker": TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_MIRANDA",
                       perceived_state="terrifying boss; key to the New Yorker if I survive a year",
                       confidence=0.7, inertia=0.6,
                       established_at_fabula=2500, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=2500, triggered_by="EVT_HIRED_AS_JR_ASSISTANT",
                    location_id="LOC_RUNWAY_OFFICES",
                    traits={
                        "self_doubt": TraitVector(value=0.7, inertia=0.5, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=4500, triggered_by="EVT_ALEX_FRUSTRATED",
                    traits={
                        "fashion_assimilation": TraitVector(value=0.55, inertia=0.5, evidence_strength="strong"),
                        "loyalty_to_alex":      TraitVector(value=0.6, inertia=0.6, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=7000, triggered_by="EVT_MIRANDA_OPENS_UP",
                    location_id="LOC_PARIS_HOTEL",
                    beliefs_added=[
                        Belief(target_id="ENT_MIRANDA",
                               perceived_state="not a monster; a lonely professional who actually values me",
                               confidence=0.8, inertia=0.5,
                               established_at_fabula=7000, evidence_strength="strong",
                               acquired_via_event_id="EVT_UTT_MIRANDA_PROMISES_NEW_YORKER",
                               acquired_via_channel_id="CHN_MIRANDA_CHAIN_OF_COMMAND"),
                    ]),
                EntityStateSnapshot(fabula_time=7500, triggered_by="EVT_LILY_DUI_COMA",
                    traits={
                        "moral_seriousness": TraitVector(value=0.95, inertia=0.9, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_LILY",
                               perceived_state="seriously harmed while I was abroad chasing a job",
                               confidence=0.95, inertia=0.85,
                               established_at_fabula=7500, evidence_strength="strong",
                               acquired_via_event_id="EVT_LILY_DUI_COMA",
                               acquired_via_channel_id="CHN_PERSONAL_LIFELINE"),
                    ]),
                EntityStateSnapshot(fabula_time=8200, triggered_by="EVT_ANDREA_REFUSES",
                    location_id="LOC_DIOR_SHOW",
                    traits={
                        "fashion_assimilation": TraitVector(value=0.0, inertia=0.4, evidence_strength="strong"),
                        "moral_seriousness":    TraitVector(value=0.95, inertia=0.95, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=9000, triggered_by="EVT_RETURN_HOME",
                    location_id="LOC_ANDREA_PARENTS_HOME",
                    traits={
                        "loyalty_to_friends": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_MIRANDA": Entity(
            id="ENT_MIRANDA", name="Miranda Priestly",
            location_id="LOC_RUNWAY_OFFICES", status="healthy",
            traits={
                "editorial_authority":    TraitVector(value=0.99, inertia=0.95, evidence_strength="strong"),
                "exacting_standards":     TraitVector(value=0.95, inertia=0.95, evidence_strength="strong"),
                "private_loneliness":     TraitVector(value=0.6,  inertia=0.6,  evidence_strength="moderate"),
                "willingness_to_mentor":  TraitVector(value=0.0,  inertia=0.6,  evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_ANDREA",
                       perceived_state="another assistant, until she proves otherwise",
                       confidence=0.7, inertia=0.6,
                       established_at_fabula=2500, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=7000, triggered_by="EVT_MIRANDA_OPENS_UP",
                    location_id="LOC_PARIS_HOTEL",
                    traits={
                        "willingness_to_mentor": TraitVector(value=0.6, inertia=0.5, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_ANDREA",
                               perceived_state="capable of writing for the New Yorker; worth a phone call",
                               confidence=0.8, inertia=0.5,
                               established_at_fabula=7000, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=8200, triggered_by="EVT_ANDREA_REFUSES",
                    location_id="LOC_DIOR_SHOW",
                    traits={
                        "willingness_to_mentor": TraitVector(value=0.0, inertia=0.7, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_LILY": Entity(
            id="ENT_LILY", name="Lily",
            location_id="LOC_ANDREA_APT", status="healthy",
            traits={
                "academic_ambition": TraitVector(value=0.7,  inertia=0.7,  evidence_strength="strong"),
                "loyalty_to_andrea": TraitVector(value=0.85, inertia=0.8,  evidence_strength="strong"),
                "self_destructiveness": TraitVector(value=0.3, inertia=0.4, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_ANDREA",
                       perceived_state="my best friend, increasingly absent",
                       confidence=0.85, inertia=0.7,
                       established_at_fabula=2500, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=4000, triggered_by="EVT_LILY_DRINKS",
                    traits={
                        "self_destructiveness": TraitVector(value=0.7, inertia=0.5, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=7500, triggered_by="EVT_LILY_DUI_COMA",
                    location_id="LOC_HOSPITAL", status="unconscious"),
                EntityStateSnapshot(fabula_time=10000, triggered_by="EVT_LILY_RECOVERS",
                    location_id="LOC_ANDREA_APT", status="injured",
                    traits={
                        "self_destructiveness": TraitVector(value=0.25, inertia=0.5, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_ALEX": Entity(
            id="ENT_ALEX", name="Alex (Andrea's Boyfriend)",
            location_id="LOC_ANDREA_APT", status="healthy",
            traits={
                "vocational_idealism":   TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
                "patience":              TraitVector(value=0.7,  inertia=0.6,  evidence_strength="moderate"),
                "frustration":           TraitVector(value=0.2,  inertia=0.4,  evidence_strength="weak"),
                "loyalty_to_andrea":     TraitVector(value=0.9,  inertia=0.8,  evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_ANDREA",
                       perceived_state="my serious girlfriend, swallowed by a job that isn't her",
                       confidence=0.8, inertia=0.7,
                       established_at_fabula=4500, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=4500, triggered_by="EVT_ALEX_FRUSTRATED",
                    traits={
                        "frustration": TraitVector(value=0.7, inertia=0.5, evidence_strength="strong"),
                        "patience":    TraitVector(value=0.4, inertia=0.5, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=9500, triggered_by="EVT_BREAKUP_WITH_ALEX",
                    traits={
                        "loyalty_to_andrea": TraitVector(value=0.6, inertia=0.6, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_CHRISTIAN": Entity(
            id="ENT_CHRISTIAN", name="Christian Collinsworth",
            location_id="LOC_CELEBRITY_PARTY", status="healthy",
            traits={
                "literary_glamour":   TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
                "social_charm":       TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
                "predatory_interest": TraitVector(value=0.6, inertia=0.5,  evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_ANDREA",
                       perceived_state="bright provincial girl in over her head — opportunity",
                       confidence=0.8, inertia=0.6,
                       established_at_fabula=3500, evidence_strength="strong"),
            ],
        ),
        "ENT_EMILY": Entity(
            id="ENT_EMILY", name="Emily (Senior Assistant)",
            location_id="LOC_RUNWAY_OFFICES", status="healthy",
            traits={
                "fashion_devotion":   TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "competitive_anxiety": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "physical_fragility": TraitVector(value=0.5,  inertia=0.4,  evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_ANDREA",
                       perceived_state="hopeless interloper who somehow hasn't been fired",
                       confidence=0.85, inertia=0.7,
                       established_at_fabula=2500, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=5500, triggered_by="EVT_EMILY_MONONUCLEOSIS",
                    status="ill",
                    traits={
                        "physical_fragility": TraitVector(value=0.95, inertia=0.5, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_HR_INTERVIEWER": Entity(
            id="ENT_HR_INTERVIEWER", name="Elias-Clarke HR Interviewer",
            location_id="LOC_RUNWAY_OFFICES", status="healthy",
            traits={
                "industry_jadedness": TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
            },
            beliefs=[],
        ),
        "ENT_ANDREAS_PARENTS": Entity(
            id="ENT_ANDREAS_PARENTS", name="Andrea's Parents",
            location_id="LOC_ANDREA_PARENTS_HOME", status="healthy",
            traits={
                "parental_concern": TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
                "moral_baseline":   TraitVector(value=0.9, inertia=0.9,  evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_ANDREA",
                       perceived_state="our daughter, working impossible hours at a job we don't recognise",
                       confidence=0.9, inertia=0.85,
                       established_at_fabula=5000, evidence_strength="strong"),
            ],
        ),
    },

    # ── EVENTS ──────────────────────────────────────────────────────────
    events=[
        EventNode(id="EVT_MOVE_TO_NYC", fabula_time=1000, syuzhet_index=1,
                  event_type="choice", actor_ids=["ENT_ANDREA", "ENT_LILY"], target_ids=[],
                  description="Andrea, freshly graduated from Brown in English, moves to New York with her best friend Lily, a Columbia graduate student."),
        EventNode(id="EVT_RESUME_BLANKET", fabula_time=1500, syuzhet_index=2,
                  event_type="choice", actor_ids=["ENT_ANDREA"], target_ids=["OBJ_ANDREA_RESUME"],
                  description="Andrea blankets the city with her résumé, hoping to break into the magazine industry on the road to The New Yorker."),
        EventNode(id="EVT_INTERVIEW_ELIAS_CLARKE", fabula_time=2000, syuzhet_index=3,
                  event_type="outcome", actor_ids=["ENT_ANDREA", "ENT_HR_INTERVIEWER"], target_ids=[],
                  description="A surprise interview at the Elias-Clarke Group leads, against Andrea's expectations, to an offer."),
        EventNode(id="EVT_HIRED_AS_JR_ASSISTANT", fabula_time=2500, syuzhet_index=4,
                  event_type="outcome", actor_ids=["ENT_MIRANDA", "ENT_ANDREA"], target_ids=["ENT_ANDREA"],
                  description="Andrea is hired as junior assistant to Miranda Priestly, editor-in-chief of Runway; she is told a million girls would die for the job."),
        EventNode(id="EVT_CELEBRITY_PARTY", fabula_time=3500, syuzhet_index=5,
                  event_type="choice", actor_ids=["ENT_ANDREA", "ENT_CHRISTIAN"], target_ids=[],
                  description="At a celebrity party Andrea meets the charismatic Yale-graduate writer Christian Collinsworth; the attraction is instant and complicating."),
        EventNode(id="EVT_LILY_DRINKS", fabula_time=4000, syuzhet_index=6,
                  event_type="choice", actor_ids=["ENT_LILY"], target_ids=["ENT_LILY"],
                  description="Under graduate-school pressure Lily increasingly turns to alcohol and bad company."),
        EventNode(id="EVT_ALEX_FRUSTRATED", fabula_time=4500, syuzhet_index=7,
                  event_type="choice", actor_ids=["ENT_ALEX"], target_ids=["ENT_ANDREA"],
                  description="Alex, an inner-city schoolteacher with his own demanding job, grows frustrated with Andrea's long hours and constant stress."),
        EventNode(id="EVT_FAMILY_SUFFERS", fabula_time=5000, syuzhet_index=8,
                  event_type="outcome", actor_ids=["ENT_ANDREAS_PARENTS"], target_ids=["ENT_ANDREA"],
                  description="Andrea's relationship with her parents thins — missed calls, cancelled visits, holiday-shaped silences."),
        EventNode(id="EVT_EMILY_MONONUCLEOSIS", fabula_time=5500, syuzhet_index=9,
                  event_type="outcome", actor_ids=["ENT_EMILY"], target_ids=["ENT_ANDREA"],
                  description="Emily, the senior assistant, contracts mononucleosis; Andrea is required to travel to Paris with Miranda in her stead."),
        EventNode(id="EVT_PARIS_TRIP", fabula_time=6000, syuzhet_index=10,
                  event_type="choice", actor_ids=["ENT_ANDREA", "ENT_MIRANDA"], target_ids=[],
                  description="Andrea flies to Paris Fashion Week with Miranda — the apex and the test of her year at Runway."),
        EventNode(id="EVT_PARIS_CHRISTIAN_ENCOUNTER", fabula_time=6500, syuzhet_index=11,
                  event_type="outcome", actor_ids=["ENT_ANDREA", "ENT_CHRISTIAN"], target_ids=[],
                  description="Andrea has a surprise encounter with Christian in Paris; the temptation she has been managing all season catches up with her."),
        EventNode(id="EVT_MIRANDA_OPENS_UP", fabula_time=7000, syuzhet_index=12,
                  event_type="choice", actor_ids=["ENT_MIRANDA"], target_ids=["ENT_ANDREA"],
                  description="Late at night in the Paris hotel, Miranda finally lowers her guard — she asks Andrea what she has learned and where she wants to work, and offers to make calls to the New Yorker once the year is up."),
        EventNode(id="EVT_LILY_DUI_COMA", fabula_time=7500, syuzhet_index=13,
                  event_type="outcome", actor_ids=["ENT_LILY"], target_ids=["ENT_LILY"],
                  description="Back at the hotel Andrea takes urgent calls from home: Lily is comatose after driving drunk and wrecking a car."),
        EventNode(id="EVT_ANDREA_HONORS_COMMITMENT", fabula_time=7600, syuzhet_index=14,
                  event_type="choice", actor_ids=["ENT_ANDREA"], target_ids=["ENT_MIRANDA"],
                  description="Pressured by her family and Alex to fly home, Andrea instead tells Miranda she will honour her commitment to Runway and stay in Paris."),
        EventNode(id="EVT_DIOR_DEMAND", fabula_time=8000, syuzhet_index=15,
                  event_type="choice", actor_ids=["ENT_MIRANDA"], target_ids=["ENT_ANDREA"],
                  description="At the Dior show Miranda phones Andrea with another impossible demand; the pattern Andrea had hoped to escape reasserts itself."),
        EventNode(id="EVT_ANDREA_REFUSES", fabula_time=8200, syuzhet_index=16,
                  event_type="choice", actor_ids=["ENT_ANDREA"], target_ids=["ENT_MIRANDA"],
                  description="Recognising she is becoming Miranda, Andrea refuses the request — the public, decisive break."),
        EventNode(id="EVT_FIRED", fabula_time=8300, syuzhet_index=17,
                  event_type="outcome", actor_ids=["ENT_MIRANDA"], target_ids=["ENT_ANDREA"],
                  description="Miranda fires Andrea on the spot at the Dior tent."),
        EventNode(id="EVT_RETURN_HOME", fabula_time=9000, syuzhet_index=18,
                  event_type="choice", actor_ids=["ENT_ANDREA"], target_ids=["ENT_ANDREAS_PARENTS"],
                  description="Andrea returns home to reconnect with her family and friends, the year of fashion behind her."),
        EventNode(id="EVT_BREAKUP_WITH_ALEX", fabula_time=9500, syuzhet_index=19,
                  event_type="choice", actor_ids=["ENT_ANDREA", "ENT_ALEX"], target_ids=[],
                  description="Andrea and Alex agree to break up but to remain friends — the cost the year has actually levied."),
        EventNode(id="EVT_LILY_RECOVERS", fabula_time=10000, syuzhet_index=20,
                  event_type="outcome", actor_ids=["ENT_LILY"], target_ids=["ENT_LILY"],
                  description="Lily recovers and is fortunate to receive only community service for her DUI charge; the friendship survives."),

        # ── UTTERANCES ──
        EventNode(id="EVT_UTT_HR_TELLS_ANDREA", event_type="utterance",
                  description="The HR interviewer drops the line every Runway assistant hears.",
                  content="A million girls would die for this job. If you survive a year with Miranda, you can have your pick of jobs in publishing.",
                  speaker_id="ENT_HR_INTERVIEWER", addressee_ids=["ENT_ANDREA"], actor_ids=["ENT_HR_INTERVIEWER"],
                  target_ids=["ENT_MIRANDA", "EVT_HIRED_AS_JR_ASSISTANT"],
                  via_channel_id=None, truth_value="true",
                  fabula_time=2500, syuzhet_index=21),
        EventNode(id="EVT_UTT_MIRANDA_PROMISES_NEW_YORKER", event_type="utterance",
                  description="Miranda, in the Paris hotel, makes the promise that almost holds Andrea inside the machine.",
                  content="I'll place a few calls for you. The New Yorker has people who owe me favours. Take some small writing assignments at Runway in the meantime.",
                  speaker_id="ENT_MIRANDA", addressee_ids=["ENT_ANDREA"], actor_ids=["ENT_MIRANDA"],
                  target_ids=["ENT_ANDREA", "EVT_MIRANDA_OPENS_UP"],
                  via_channel_id="CHN_MIRANDA_CHAIN_OF_COMMAND", truth_value="true",
                  fabula_time=7000, syuzhet_index=22),
        EventNode(id="EVT_UTT_FAMILY_PRESSURES_ANDREA", event_type="utterance",
                  description="From a hotel phone, Andrea's family insists she come home.",
                  content="Lily is comatose. You need to be on the next flight back. The job is not worth this.",
                  speaker_id="ENT_ANDREAS_PARENTS", addressee_ids=["ENT_ANDREA"], actor_ids=["ENT_ANDREAS_PARENTS"],
                  target_ids=["ENT_LILY", "EVT_LILY_DUI_COMA"],
                  via_channel_id="CHN_PERSONAL_LIFELINE", truth_value="true",
                  fabula_time=7500, syuzhet_index=23),
        EventNode(id="EVT_UTT_MIRANDA_DIOR_DEMAND", event_type="utterance",
                  description="Mid-show, Miranda phones with another demand impossible to satisfy and impossible to refuse.",
                  content="Get me the unpublished Harry Potter manuscript. By tonight. The twins want to read it on the plane.",
                  speaker_id="ENT_MIRANDA", addressee_ids=["ENT_ANDREA"], actor_ids=["ENT_MIRANDA"],
                  target_ids=["ENT_ANDREA", "EVT_DIOR_DEMAND"],
                  via_channel_id="CHN_MIRANDA_CHAIN_OF_COMMAND", truth_value="performative",
                  fabula_time=8000, syuzhet_index=24),
        EventNode(id="EVT_UTT_ANDREA_FUCK_YOU", event_type="utterance",
                  description="At the Dior show, Andrea finally answers Miranda the only way she can.",
                  content="Fuck you, Miranda. Fuck you.",
                  speaker_id="ENT_ANDREA", addressee_ids=["ENT_MIRANDA"], actor_ids=["ENT_ANDREA"],
                  target_ids=["ENT_MIRANDA", "EVT_ANDREA_REFUSES"],
                  via_channel_id="CHN_MIRANDA_CHAIN_OF_COMMAND", truth_value="performative",
                  fabula_time=8200, syuzhet_index=25),
        EventNode(id="EVT_UTT_MIRANDA_FIRES_ANDREA", event_type="utterance",
                  description="Miranda's response is two short, clinical sentences — the channel is severed.",
                  content="You're fired. Get out.",
                  speaker_id="ENT_MIRANDA", addressee_ids=["ENT_ANDREA"], actor_ids=["ENT_MIRANDA"],
                  target_ids=["ENT_ANDREA", "EVT_FIRED"],
                  via_channel_id="CHN_MIRANDA_CHAIN_OF_COMMAND", truth_value="performative",
                  fabula_time=8300, syuzhet_index=26),
        EventNode(id="EVT_UTT_ALEX_PARTING_LINE", event_type="utterance",
                  description="In the breakup conversation Alex says what they have both known for months.",
                  content="You're not the same person who moved here with me. I think we should be friends instead.",
                  speaker_id="ENT_ALEX", addressee_ids=["ENT_ANDREA"], actor_ids=["ENT_ALEX"],
                  target_ids=["ENT_ANDREA", "EVT_BREAKUP_WITH_ALEX"],
                  via_channel_id=None, truth_value="true",
                  fabula_time=9500, syuzhet_index=27),
    ],

    # ── CAUSAL TOPOLOGY ────────────────────────────────────────────────
    causal_topology=[
        # ── chain_reaction (the spine) ──
        CausalEdge(source_id="EVT_MOVE_TO_NYC", target_id="EVT_RESUME_BLANKET",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=1000, propagation_delay=500),
        CausalEdge(source_id="EVT_RESUME_BLANKET", target_id="EVT_INTERVIEW_ELIAS_CLARKE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=1500, propagation_delay=500),
        CausalEdge(source_id="EVT_INTERVIEW_ELIAS_CLARKE", target_id="EVT_HIRED_AS_JR_ASSISTANT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=2000, propagation_delay=500),
        CausalEdge(source_id="EVT_HIRED_AS_JR_ASSISTANT", target_id="EVT_CELEBRITY_PARTY",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=2500, propagation_delay=1000),
        CausalEdge(source_id="EVT_HIRED_AS_JR_ASSISTANT", target_id="EVT_ALEX_FRUSTRATED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=2500, propagation_delay=2000),
        CausalEdge(source_id="EVT_HIRED_AS_JR_ASSISTANT", target_id="EVT_FAMILY_SUFFERS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=2500, propagation_delay=2500),
        CausalEdge(source_id="EVT_HIRED_AS_JR_ASSISTANT", target_id="EVT_LILY_DRINKS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=2500, propagation_delay=1500),
        CausalEdge(source_id="EVT_EMILY_MONONUCLEOSIS", target_id="EVT_PARIS_TRIP",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=5500, propagation_delay=500),
        CausalEdge(source_id="EVT_PARIS_TRIP", target_id="EVT_PARIS_CHRISTIAN_ENCOUNTER",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=6000, propagation_delay=500),
        CausalEdge(source_id="EVT_PARIS_TRIP", target_id="EVT_MIRANDA_OPENS_UP",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=6000, propagation_delay=1000),
        CausalEdge(source_id="EVT_LILY_DRINKS", target_id="EVT_LILY_DUI_COMA",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=4000, propagation_delay=3500),
        CausalEdge(source_id="EVT_LILY_DUI_COMA", target_id="EVT_ANDREA_HONORS_COMMITMENT",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=7500, propagation_delay=100),
        CausalEdge(source_id="EVT_ANDREA_HONORS_COMMITMENT", target_id="EVT_DIOR_DEMAND",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7600, propagation_delay=400),
        CausalEdge(source_id="EVT_DIOR_DEMAND", target_id="EVT_ANDREA_REFUSES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=8000, propagation_delay=200),
        CausalEdge(source_id="EVT_ANDREA_REFUSES", target_id="EVT_FIRED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=10.0, fabula_time=8200, propagation_delay=100),
        CausalEdge(source_id="EVT_FIRED", target_id="EVT_RETURN_HOME",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=8300, propagation_delay=700),
        CausalEdge(source_id="EVT_RETURN_HOME", target_id="EVT_BREAKUP_WITH_ALEX",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=9000, propagation_delay=500),
        CausalEdge(source_id="EVT_LILY_DUI_COMA", target_id="EVT_LILY_RECOVERS",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7500, propagation_delay=2500),

        # ── mutation ──
        CausalEdge(source_id="EVT_HIRED_AS_JR_ASSISTANT", target_id="ENT_ANDREA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=2500,
                   trait_target="self_doubt", trait_delta=0.2),
        CausalEdge(source_id="EVT_ALEX_FRUSTRATED", target_id="ENT_ANDREA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=4500,
                   trait_target="fashion_assimilation", trait_delta=0.55),
        CausalEdge(source_id="EVT_LILY_DRINKS", target_id="ENT_LILY",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=4000,
                   trait_target="self_destructiveness", trait_delta=0.4),
        CausalEdge(source_id="EVT_MIRANDA_OPENS_UP", target_id="ENT_MIRANDA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7000,
                   trait_target="willingness_to_mentor", trait_delta=0.6),
        CausalEdge(source_id="EVT_LILY_DUI_COMA", target_id="ENT_ANDREA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=7500,
                   trait_target="moral_seriousness", trait_delta=0.1),
        CausalEdge(source_id="EVT_ANDREA_REFUSES", target_id="ENT_ANDREA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=8200,
                   trait_target="fashion_assimilation", trait_delta=-0.55),
        CausalEdge(source_id="EVT_ANDREA_REFUSES", target_id="ENT_MIRANDA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8200,
                   trait_target="willingness_to_mentor", trait_delta=-0.6),

        # ── mutation_social ──
        CausalEdge(source_id="EVT_HIRED_AS_JR_ASSISTANT", target_id="ENT_ANDREA",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=2500,
                   trait_target="power_dynamic", trait_delta=-0.7, rel_counterpart_id="ENT_MIRANDA"),
        CausalEdge(source_id="EVT_HIRED_AS_JR_ASSISTANT", target_id="ENT_MIRANDA",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=2500,
                   trait_target="power_dynamic", trait_delta=0.7, rel_counterpart_id="ENT_ANDREA"),
        CausalEdge(source_id="EVT_ALEX_FRUSTRATED", target_id="ENT_ANDREA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=4500,
                   trait_target="affinity", trait_delta=-0.3, rel_counterpart_id="ENT_ALEX"),
        CausalEdge(source_id="EVT_FAMILY_SUFFERS", target_id="ENT_ANDREA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=5.0, fabula_time=5000,
                   trait_target="affinity", trait_delta=-0.25, rel_counterpart_id="ENT_ANDREAS_PARENTS"),
        CausalEdge(source_id="EVT_LILY_DRINKS", target_id="ENT_LILY",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=4000,
                   trait_target="affinity", trait_delta=-0.25, rel_counterpart_id="ENT_ANDREA"),
        CausalEdge(source_id="EVT_MIRANDA_OPENS_UP", target_id="ENT_ANDREA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7000,
                   trait_target="affinity", trait_delta=0.5, rel_counterpart_id="ENT_MIRANDA"),
        CausalEdge(source_id="EVT_MIRANDA_OPENS_UP", target_id="ENT_MIRANDA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7000,
                   trait_target="affinity", trait_delta=0.5, rel_counterpart_id="ENT_ANDREA"),
        CausalEdge(source_id="EVT_ANDREA_REFUSES", target_id="ENT_ANDREA",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=8200,
                   trait_target="affinity", trait_delta=-0.7, rel_counterpart_id="ENT_MIRANDA"),
        CausalEdge(source_id="EVT_FIRED", target_id="ENT_MIRANDA",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8300,
                   trait_target="affinity", trait_delta=-0.7, rel_counterpart_id="ENT_ANDREA"),
        CausalEdge(source_id="EVT_RETURN_HOME", target_id="ENT_ANDREA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=9000,
                   trait_target="affinity", trait_delta=0.45, rel_counterpart_id="ENT_ANDREAS_PARENTS"),
        CausalEdge(source_id="EVT_BREAKUP_WITH_ALEX", target_id="ENT_ANDREA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=9500,
                   trait_target="affinity", trait_delta=-0.3, rel_counterpart_id="ENT_ALEX"),
        CausalEdge(source_id="EVT_LILY_RECOVERS", target_id="ENT_ANDREA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=5.0, fabula_time=10000,
                   trait_target="affinity", trait_delta=0.4, rel_counterpart_id="ENT_LILY"),

        # ── mutation_social: fear arc (Andrea → Miranda) ──
        # Fear rises sharply when Andrea steps into Miranda's orbit, peaks at the
        # impossible Dior ultimatum, softens briefly during the Paris confidence,
        # and crystallises at the final refusal. Terminal value tracks the
        # ENT_ANDREA → ENT_MIRANDA fear baseline (0.7) on the social topology.
        CausalEdge(source_id="EVT_HIRED_AS_JR_ASSISTANT", target_id="ENT_ANDREA",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2500,
                   trait_target="fear", trait_delta=0.5, rel_counterpart_id="ENT_MIRANDA"),
        CausalEdge(source_id="EVT_DIOR_DEMAND", target_id="ENT_ANDREA",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8000,
                   trait_target="fear", trait_delta=0.3, rel_counterpart_id="ENT_MIRANDA"),
        CausalEdge(source_id="EVT_MIRANDA_OPENS_UP", target_id="ENT_ANDREA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=7000,
                   trait_target="fear", trait_delta=-0.2, rel_counterpart_id="ENT_MIRANDA"),
        CausalEdge(source_id="EVT_ANDREA_REFUSES", target_id="ENT_ANDREA",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=8200,
                   trait_target="fear", trait_delta=0.1, rel_counterpart_id="ENT_MIRANDA"),

        # ── affordance_gate ──
        CausalEdge(source_id="OBJ_ANDREA_RESUME", target_id="EVT_INTERVIEW_ELIAS_CLARKE",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=2000),
        CausalEdge(source_id="OBJ_ASSISTANT_PHONE", target_id="EVT_DIOR_DEMAND",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8000),
        CausalEdge(source_id="OBJ_BORROWED_WARDROBE", target_id="EVT_CELEBRITY_PARTY",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=3500),
        CausalEdge(source_id="OBJ_LILYS_CAR", target_id="EVT_LILY_DUI_COMA",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=7500),
        CausalEdge(source_id="OBJ_MIRANDA_PHONE", target_id="EVT_DIOR_DEMAND",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=8000),

        # ── ambient_propagation ──
        CausalEdge(source_id="LOC_RUNWAY_OFFICES", target_id="ENT_ANDREA",
                   causality_type="ambient_propagation", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2500),
        CausalEdge(source_id="LOC_PARIS_HOTEL", target_id="ENT_ANDREA",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7000),
        CausalEdge(source_id="LOC_DIOR_SHOW", target_id="ENT_ANDREA",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=8200),
        CausalEdge(source_id="LOC_HOSPITAL", target_id="ENT_ANDREA",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="strong",
                   causal_force=5.0, fabula_time=7500),
        CausalEdge(source_id="LOC_ANDREA_PARENTS_HOME", target_id="ENT_ANDREA",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="strong",
                   causal_force=5.0, fabula_time=9000),

        # ── WORLD_ → Event ──
        CausalEdge(source_id="WORLD_FASHION_STATUS_ECONOMY", target_id="EVT_HIRED_AS_JR_ASSISTANT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=2500),
        CausalEdge(source_id="WORLD_FASHION_STATUS_ECONOMY", target_id="EVT_DIOR_DEMAND",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8000),
        CausalEdge(source_id="WORLD_CAREER_VS_LIFE", target_id="EVT_ALEX_FRUSTRATED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=4500),
        CausalEdge(source_id="WORLD_CAREER_VS_LIFE", target_id="EVT_FAMILY_SUFFERS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=5000),
        CausalEdge(source_id="WORLD_CAREER_VS_LIFE", target_id="EVT_ANDREA_REFUSES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8200),
        CausalEdge(source_id="WORLD_ALWAYS_ON_PHONE", target_id="EVT_HIRED_AS_JR_ASSISTANT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=2500),
        CausalEdge(source_id="WORLD_ALWAYS_ON_PHONE", target_id="EVT_DIOR_DEMAND",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8000),

        # ── orphan utterance wirings ──
        CausalEdge(source_id="EVT_HIRED_AS_JR_ASSISTANT", target_id="EVT_UTT_HR_TELLS_ANDREA",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=4.0, fabula_time=2500, propagation_delay=0),
        CausalEdge(source_id="EVT_MIRANDA_OPENS_UP", target_id="EVT_UTT_MIRANDA_PROMISES_NEW_YORKER",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=5.0, fabula_time=7000, propagation_delay=0),
        CausalEdge(source_id="EVT_LILY_DUI_COMA", target_id="EVT_UTT_FAMILY_PRESSURES_ANDREA",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=7500, propagation_delay=0),
        CausalEdge(source_id="EVT_DIOR_DEMAND", target_id="EVT_UTT_MIRANDA_DIOR_DEMAND",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=8000, propagation_delay=0),
        CausalEdge(source_id="EVT_ANDREA_REFUSES", target_id="EVT_UTT_ANDREA_FUCK_YOU",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=8200, propagation_delay=0),
        CausalEdge(source_id="EVT_FIRED", target_id="EVT_UTT_MIRANDA_FIRES_ANDREA",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=8300, propagation_delay=0),
        CausalEdge(source_id="EVT_BREAKUP_WITH_ALEX", target_id="EVT_UTT_ALEX_PARTING_LINE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=5.0, fabula_time=9500, propagation_delay=0),
    ],

    # ── SPATIAL TOPOLOGY ────────────────────────────────────────────────
    spatial_topology=[
        SpatialEdge(source_id="LOC_ANDREA_APT", target_id="LOC_RUNWAY_OFFICES"),
        SpatialEdge(source_id="LOC_RUNWAY_OFFICES", target_id="LOC_ANDREA_APT"),
        SpatialEdge(source_id="LOC_ANDREA_APT", target_id="LOC_CELEBRITY_PARTY"),
        SpatialEdge(source_id="LOC_RUNWAY_OFFICES", target_id="LOC_PARIS_HOTEL"),
        SpatialEdge(source_id="LOC_PARIS_HOTEL", target_id="LOC_DIOR_SHOW"),
        SpatialEdge(source_id="LOC_DIOR_SHOW", target_id="LOC_PARIS_HOTEL"),
        SpatialEdge(source_id="LOC_PARIS_HOTEL", target_id="LOC_ANDREA_PARENTS_HOME"),
        SpatialEdge(source_id="LOC_ANDREA_APT", target_id="LOC_HOSPITAL"),
        SpatialEdge(source_id="LOC_ANDREA_APT", target_id="LOC_ANDREA_PARENTS_HOME"),
    ],

    # ── INFORMATION TOPOLOGY ────────────────────────────────────────────
    channels={
        "CHN_MIRANDA_CHAIN_OF_COMMAND": Channel(
            id="CHN_MIRANDA_CHAIN_OF_COMMAND",
            name="Miranda's Chain of Command",
            medium="hierarchical_directive",
            participant_ids=["ENT_MIRANDA", "ENT_EMILY", "ENT_ANDREA"],
            directionality="duplex",
            intelligibility={"ENT_ANDREA": 0.5, "ENT_EMILY": 0.95},
            established_at_fabula=2500, terminated_at_fabula=8300,
            evidence_strength="strong",
        ),
        "CHN_RUNWAY_INTERNAL": Channel(
            id="CHN_RUNWAY_INTERNAL",
            name="Runway Editorial Floor Network",
            medium="office_grapevine",
            participant_ids=["ENT_MIRANDA", "ENT_EMILY", "ENT_ANDREA"],
            directionality="broadcast",
            intelligibility={"ENT_ANDREA": 0.4, "ENT_EMILY": 0.95},
            established_at_fabula=2500, terminated_at_fabula=8300,
            evidence_strength="strong",
        ),
        "CHN_PERSONAL_LIFELINE": Channel(
            id="CHN_PERSONAL_LIFELINE",
            name="Andrea's Personal Lifeline (family / Lily / Alex)",
            medium="phone_and_voicemail",
            participant_ids=["ENT_ANDREA", "ENT_LILY", "ENT_ALEX", "ENT_ANDREAS_PARENTS"],
            directionality="duplex",
            intelligibility={"ENT_ANDREA": 0.4, "ENT_LILY": 0.95, "ENT_ALEX": 0.95, "ENT_ANDREAS_PARENTS": 0.95},
            established_at_fabula=1000, terminated_at_fabula=None,
            evidence_strength="strong",
        ),
    },

    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_FASHION_STATUS_ECONOMY": GlobalTrait(
            id="WORLD_FASHION_STATUS_ECONOMY",
            name="The Fashion-Industry Status Economy",
            description="The cosmology of Runway: a hierarchy of taste, surveillance, and proximity-to-Miranda in which a million girls would die for the bottom rung. Operates as common-cause parent over every demand, every sneer, and the public break at Dior.",
            category="social_structure",
            magnitude=TraitVector(value=0.95, inertia=0.95, evidence_strength="strong"),
            affected_domains=["social", "economic"],
        ),
        "WORLD_CAREER_VS_LIFE": GlobalTrait(
            id="WORLD_CAREER_VS_LIFE",
            name="The Career-vs-Personal-Life Machine",
            description="The contemporary professional structure that demands the assistant be available for every late-night call and weekend errand at the cost of romantic, familial, and friendship bandwidth. The film's quiet maximal latent.",
            category="social_structure",
            magnitude=TraitVector(value=0.9, inertia=0.9, evidence_strength="strong"),
            affected_domains=["social", "psychological"],
        ),
        "WORLD_ALWAYS_ON_PHONE": GlobalTrait(
            id="WORLD_ALWAYS_ON_PHONE",
            name="The Always-On Assistant Phone",
            description="The standing infrastructural fact of a mobile that may ring at any moment and must be answered. A material substrate beneath WORLD_CAREER_VS_LIFE; in the film, Andrea's tether and Miranda's leash.",
            category="cosmology",
            magnitude=TraitVector(value=0.9, inertia=0.9, evidence_strength="strong"),
            affected_domains=["social"],
        ),
    },

    # ── SOCIAL TOPOLOGY ────────────────────────────────────────────────
    social_topology=[
        # Andrea ↔ Miranda — the asymmetric centre.
        RelationshipEdge(
            source_entity_id="ENT_ANDREA", target_entity_id="ENT_MIRANDA",
            metrics={
                "affinity":      RelationshipMetric(value=-0.2, inertia=0.4, evidence_strength="strong", last_updated_fabula=8200),
                "fear":          RelationshipMetric(value=0.7,  inertia=0.5, evidence_strength="strong", last_updated_fabula=8200),
                "power_dynamic": RelationshipMetric(value=-0.85, inertia=0.7, evidence_strength="strong", last_updated_fabula=8300),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_MIRANDA", target_entity_id="ENT_ANDREA",
            metrics={
                "affinity":      RelationshipMetric(value=-0.2, inertia=0.5, evidence_strength="strong", last_updated_fabula=8300),
                "power_dynamic": RelationshipMetric(value=0.85, inertia=0.7, evidence_strength="strong", last_updated_fabula=8300),
            },
        ),
        # Andrea ↔ Lily — best-friendship under strain.
        RelationshipEdge(
            source_entity_id="ENT_ANDREA", target_entity_id="ENT_LILY",
            metrics={
                "affinity": RelationshipMetric(value=0.65, inertia=0.65, evidence_strength="strong", last_updated_fabula=10000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_LILY", target_entity_id="ENT_ANDREA",
            metrics={
                "affinity": RelationshipMetric(value=0.6, inertia=0.65, evidence_strength="strong", last_updated_fabula=10000),
            },
        ),
        # Andrea ↔ Alex — relationship.
        RelationshipEdge(
            source_entity_id="ENT_ANDREA", target_entity_id="ENT_ALEX",
            metrics={
                "affinity": RelationshipMetric(value=0.55, inertia=0.55, evidence_strength="strong", last_updated_fabula=9500),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_ALEX", target_entity_id="ENT_ANDREA",
            metrics={
                "affinity": RelationshipMetric(value=0.55, inertia=0.55, evidence_strength="strong", last_updated_fabula=9500),
            },
        ),
        # Andrea ↔ Christian — temptation.
        RelationshipEdge(
            source_entity_id="ENT_ANDREA", target_entity_id="ENT_CHRISTIAN",
            metrics={
                "affinity": RelationshipMetric(value=0.5, inertia=0.45, evidence_strength="moderate", last_updated_fabula=6500),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_CHRISTIAN", target_entity_id="ENT_ANDREA",
            metrics={
                "affinity":      RelationshipMetric(value=0.5, inertia=0.4, evidence_strength="moderate", last_updated_fabula=6500),
                "power_dynamic": RelationshipMetric(value=0.4, inertia=0.5, evidence_strength="moderate", last_updated_fabula=6500),
            },
        ),
        # Andrea ↔ Emily — office rivalry.
        RelationshipEdge(
            source_entity_id="ENT_EMILY", target_entity_id="ENT_ANDREA",
            metrics={
                "affinity":      RelationshipMetric(value=-0.55, inertia=0.55, evidence_strength="strong", last_updated_fabula=5500),
                "power_dynamic": RelationshipMetric(value=0.4, inertia=0.6, evidence_strength="moderate", last_updated_fabula=2500),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_ANDREA", target_entity_id="ENT_EMILY",
            metrics={
                "affinity": RelationshipMetric(value=0.2, inertia=0.5, evidence_strength="moderate", last_updated_fabula=5500),
            },
        ),
        # Andrea ↔ parents — the moral baseline.
        RelationshipEdge(
            source_entity_id="ENT_ANDREA", target_entity_id="ENT_ANDREAS_PARENTS",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.85, evidence_strength="strong", last_updated_fabula=9000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_ANDREAS_PARENTS", target_entity_id="ENT_ANDREA",
            metrics={
                "affinity": RelationshipMetric(value=0.95, inertia=0.9, evidence_strength="strong", last_updated_fabula=9000),
            },
        ),
    ],
)
