# SPDX-FileCopyrightText: 2026 David Rae Wilmot
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Tinker Tailor Soldier Spy — high-fidelity WorldStateV1 test fixture.

Authored against the current ingestion prompts (ontology_locations,
ontology_objects, ontology_entities, ontology_world_traits,
physics_extraction, social_extraction, consequences_extraction,
world_trait_timeline). Demonstrates:

* All five CausalEdge modalities (chain_reaction, mutation,
  mutation_social, affordance_gate, ambient_propagation).
* Per-axis RelationshipMetric (only observed axes populated, with
  per-axis inertia bands: fear ~0.1–0.3, affinity ~0.3–0.6,
  power_dynamic ~0.5–0.8).
* Explicit evidence_strength everywhere it is supported
  (TraitVector, AmbientVector, Belief, CausalEdge,
  RelationshipMetric, GlobalTrait magnitude).
* state_timeline snapshots whose inertia *bumps up* (not down) when
  a trait is shocked away from baseline.
* WORLD_ named-latent traits wired as common-cause parents to the
  events they jointly drive.
* Channel-rich espionage modeling — the mole hunt IS an information-flow problem.
"""
from shadow_loom.models import (
    Channel,
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, RelationshipMetric, TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
    NarrativeStyle,
)

world_state = WorldStateV1(
    narrative_style=NarrativeStyle(
        format='synopsis',
        target_word_min=339,
        target_word_max=1270,
        prose_density='rich',
        voice='synoptic narration; minimal dialogue; condensed scene description; third-person POV; past tense; espionage register',
        style_exemplar='In October 1973, Control (John Hurt), the head of British Intelligence ("the Circus"), sends agent Jim Prideaux (Mark Strong) to Communist Hungary to meet a Hungarian general who had promised to sell information. However, Prideaux is shot and captured by Soviet agents. Amid the international incident that follows, Control and his right-hand man George Smiley (Gary Oldman) are forced into retirement. Control, already ill, dies soon afterwards.',
        source_word_count=847,
    ),
    # ── LOCATIONS ──────────────────────────────────────────────────────
    locations={
        "LOC_THE_CIRCUS": Location(
            name="The Circus (MI6 HQ, London)",
            description="British Intelligence headquarters in Cambridge Circus, London. Atmosphere of institutional paranoia and bureaucratic secrecy.",
            ambient_state={
                "surveillance": AmbientVector(value=0.85, volatility=0.3, evidence_strength="strong"),
                "tension": AmbientVector(value=0.7, volatility=0.4, evidence_strength="strong"),
                "secrecy": AmbientVector(value=0.9, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_HUNGARY": Location(
            name="Hungary (Budapest meeting site)",
            description="Communist Hungary, site of Prideaux's disastrous mission. Cold War frontier zone.",
            ambient_state={
                "danger": AmbientVector(value=0.9, volatility=0.3, evidence_strength="strong"),
                "surveillance": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_LACON_HOUSE": Location(
            name="Lacon's House",
            description="Oliver Lacon's residence, where sensitive off-the-books meetings occur.",
            ambient_state={
                "secrecy": AmbientVector(value=0.7, volatility=0.3, evidence_strength="moderate"),
            },
        ),
        "LOC_SMILEY_HOUSE": Location(
            name="Smiley's House (Bywater Street)",
            description="George Smiley's modest London home. Site of quiet domestic betrayal.",
            ambient_state={
                "isolation": AmbientVector(value=0.6, volatility=0.4, evidence_strength="moderate"),
            },
        ),
        "LOC_SAFE_HOUSE": Location(
            name="Safe House (Lock Gardens)",
            description="Secret MI6 safe house where senior officers meet Polyakov for Witchcraft material.",
            ambient_state={
                "secrecy": AmbientVector(value=0.95, volatility=0.2, evidence_strength="strong"),
                "surveillance": AmbientVector(value=0.8, volatility=0.3, evidence_strength="strong"),
            },
        ),
        "LOC_SARRATT": Location(
            name="Sarratt Interrogation Centre",
            description="MI6 training and interrogation facility. Site of Haydon's confession.",
            ambient_state={
                "tension": AmbientVector(value=0.8, volatility=0.3, evidence_strength="strong"),
                "isolation": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_PARIS_OFFICE": Location(
            name="Paris MI6 Office",
            description="British Intelligence Paris station. Where Tarr announces he knows the mole.",
            ambient_state={
                "tension": AmbientVector(value=0.5, volatility=0.5, evidence_strength="moderate"),
            },
        ),
        "LOC_ISTANBUL": Location(
            name="Istanbul",
            description="Turkish city where Tarr met Boris and Irina. Crossroads of Cold War espionage.",
            ambient_state={
                "surveillance": AmbientVector(value=0.75, volatility=0.4, evidence_strength="moderate"),
                "danger": AmbientVector(value=0.65, volatility=0.5, evidence_strength="moderate"),
            },
        ),
        "LOC_ENGLAND_EXILE": Location(
            name="England (Retirement)",
            description="Where Control and Smiley live in forced retirement after the Hungary disaster.",
            ambient_state={
                "isolation": AmbientVector(value=0.7, volatility=0.3, evidence_strength="moderate"),
            },
        ),
        "LOC_MOSCOW_CENTRE": Location(
            name="Moscow Centre (offstage)",
            description="The Soviet intelligence headquarters from which Karla runs the mole; never depicted, only inferred.",
            ambient_state={
                "secrecy": AmbientVector(value=0.95, volatility=0.1, evidence_strength="weak"),
            },
        ),
    },

    # ── OBJECTS ─────────────────────────────────────────────────────────
    objects={
        "OBJ_WITCHCRAFT_MATERIAL": NarrativeObject(
            id="OBJ_WITCHCRAFT_MATERIAL", name="Witchcraft Material (Soviet chicken-feed dossiers)",
            location_id="LOC_SAFE_HOUSE", owner_id="ENT_POLYAKOV",
            properties={"content": "high_grade_soviet_intelligence", "state": "chicken_feed_with_glitter"},
            affordances=[
                Affordance(action="be_read", target_type="Entity"),
                Affordance(action="be_traded", target_type="Entity"),
                Affordance(action="deceive", target_type="Entity"),
            ],
        ),
        "OBJ_DUTY_LOGBOOK": NarrativeObject(
            id="OBJ_DUTY_LOGBOOK", name="Circus Duty Logbook",
            location_id="LOC_THE_CIRCUS", owner_id=None,
            properties={"state": "tampered", "pages_cut": "Tarr_call_night"},
            affordances=[
                Affordance(action="be_read", target_type="Entity"),
                Affordance(action="be_stolen", target_type="Entity"),
                Affordance(action="reveal_evidence", target_type="Entity"),
            ],
        ),
        "OBJ_SAFE_HOUSE_LEDGER": NarrativeObject(
            id="OBJ_SAFE_HOUSE_LEDGER", name="Safe House Ledger",
            location_id="LOC_SAFE_HOUSE", owner_id=None,
            properties={"content": "meeting_records"},
            affordances=[
                Affordance(action="be_read", target_type="Entity"),
                Affordance(action="reveal_evidence", target_type="Entity"),
            ],
        ),
        "OBJ_TARR_FILE": NarrativeObject(
            id="OBJ_TARR_FILE", name="Tarr's Defection File",
            location_id="LOC_THE_CIRCUS", owner_id=None,
            properties={"state": "fabricated", "content": "false_defection_accusation"},
            affordances=[
                Affordance(action="be_read", target_type="Entity"),
                Affordance(action="frame", target_type="Entity"),
            ],
        ),
        "OBJ_HAYDON_REVOLVER": NarrativeObject(
            id="OBJ_HAYDON_REVOLVER", name="Haydon's Service Revolver",
            location_id="LOC_SARRATT", owner_id="ENT_BILL_HAYDON",
            properties={"state": "loaded"},
            affordances=[
                Affordance(action="kill", target_type="Entity"),
            ],
        ),
    },

    # ── ENTITIES ────────────────────────────────────────────────────────
    entities={
        "ENT_GEORGE_SMILEY": Entity(
            id="ENT_GEORGE_SMILEY", name="George Smiley",
            location_id="LOC_THE_CIRCUS", status="healthy",
            traits={
                "intelligence": TraitVector(value=0.95, inertia=0.8, evidence_strength="strong"),
                "suspicion": TraitVector(value=0.4, inertia=0.45, evidence_strength="moderate"),
                "loyalty": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "professionalism": TraitVector(value=0.9, inertia=0.75, evidence_strength="strong"),
                "grief": TraitVector(value=0.3, inertia=0.35, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_CONTROL", perceived_state="Control is my mentor and the rightful Chief",
                       confidence=0.95, inertia=0.7, evidence_strength="strong"),
                Belief(target_id="ENT_BILL_HAYDON", perceived_state="Haydon is a trusted colleague and friend",
                       confidence=0.75, inertia=0.55, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=4000, triggered_by="EVT_CONTROL_DIES",
                    traits={
                        "grief": TraitVector(value=0.7, inertia=0.45, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=5000, triggered_by="EVT_LACON_RECRUITS_SMILEY",
                    traits={
                        "suspicion": TraitVector(value=0.6, inertia=0.5, evidence_strength="strong"),
                    },
                    location_id="LOC_LACON_HOUSE"),
                EntityStateSnapshot(fabula_time=13000, triggered_by="EVT_WESTERBY_REVEALS_AFFAIR",
                    traits={
                        "suspicion": TraitVector(value=0.8, inertia=0.55, evidence_strength="strong"),
                        "grief": TraitVector(value=0.85, inertia=0.5, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=22000, triggered_by="EVT_HAYDON_UNMASKED",
                    traits={
                        "suspicion": TraitVector(value=0.95, inertia=0.65, evidence_strength="strong"),
                    },
                    location_id="LOC_SAFE_HOUSE"),
            ],
        ),
        "ENT_CONTROL": Entity(
            id="ENT_CONTROL", name="Control (former Chief)",
            location_id="LOC_THE_CIRCUS", status="ill",
            traits={
                "intelligence": TraitVector(value=0.9, inertia=0.75, evidence_strength="strong"),
                "paranoia": TraitVector(value=0.75, inertia=0.6, evidence_strength="strong"),
                "loyalty": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="WORLD_SOVIET_MOLE", perceived_state="There is a mole in the Circus at senior level",
                       confidence=0.85, inertia=0.8, evidence_strength="strong"),
                Belief(target_id="OBJ_WITCHCRAFT_MATERIAL", perceived_state="Witchcraft is a Soviet deception operation",
                       confidence=0.8, inertia=0.75, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=2500, triggered_by="EVT_CONTROL_FORCED_RETIREMENT",
                    location_id="LOC_ENGLAND_EXILE",
                    traits={
                        "paranoia": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=4000, triggered_by="EVT_CONTROL_DIES",
                    status="dead"),
            ],
        ),
        "ENT_BILL_HAYDON": Entity(
            id="ENT_BILL_HAYDON", name="Bill Haydon",
            location_id="LOC_THE_CIRCUS", status="healthy",
            traits={
                "intelligence": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "betrayal": TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
                "loyalty": TraitVector(value=0.2, inertia=0.8, evidence_strength="strong"),
                "composure": TraitVector(value=0.9, inertia=0.6, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_KARLA", perceived_state="Karla is my true master and I serve the Soviet cause",
                       confidence=0.95, inertia=0.9, evidence_strength="strong"),
                Belief(target_id="ENT_GEORGE_SMILEY", perceived_state="Smiley suspects nothing — the Ann affair keeps him distracted",
                       confidence=0.8, inertia=0.6, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=3000, triggered_by="EVT_ALLELINE_BECOMES_CHIEF",
                    location_id="LOC_THE_CIRCUS"),
                EntityStateSnapshot(fabula_time=22000, triggered_by="EVT_HAYDON_UNMASKED",
                    traits={
                        "composure": TraitVector(value=0.2, inertia=0.65, evidence_strength="strong"),
                    },
                    location_id="LOC_SAFE_HOUSE"),
                EntityStateSnapshot(fabula_time=23000, triggered_by="EVT_HAYDON_CONFESSION",
                    location_id="LOC_SARRATT"),
                EntityStateSnapshot(fabula_time=24000, triggered_by="EVT_PRIDEAUX_KILLS_HAYDON",
                    status="dead"),
            ],
        ),
        "ENT_PERCY_ALLELINE": Entity(
            id="ENT_PERCY_ALLELINE", name="Percy Alleline",
            location_id="LOC_THE_CIRCUS", status="healthy",
            traits={
                "ambition": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                "loyalty": TraitVector(value=0.6, inertia=0.5, evidence_strength="moderate"),
                "professionalism": TraitVector(value=0.65, inertia=0.55, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="OBJ_WITCHCRAFT_MATERIAL", perceived_state="Witchcraft is my triumph — genuine high-grade Soviet intelligence",
                       confidence=0.9, inertia=0.7, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=3000, triggered_by="EVT_ALLELINE_BECOMES_CHIEF",
                    location_id="LOC_THE_CIRCUS"),
            ],
        ),
        "ENT_ROY_BLAND": Entity(
            id="ENT_ROY_BLAND", name="Roy Bland",
            location_id="LOC_THE_CIRCUS", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.7, inertia=0.6, evidence_strength="moderate"),
                "professionalism": TraitVector(value=0.75, inertia=0.65, evidence_strength="moderate"),
            },
            beliefs=[],
        ),
        "ENT_TOBY_ESTERHASE": Entity(
            id="ENT_TOBY_ESTERHASE", name="Toby Esterhase",
            location_id="LOC_THE_CIRCUS", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.65, inertia=0.55, evidence_strength="moderate"),
                "fear": TraitVector(value=0.5, inertia=0.3, evidence_strength="moderate"),
                "professionalism": TraitVector(value=0.7, inertia=0.6, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=19000, triggered_by="EVT_ESTERHASE_PRESSED",
                    traits={
                        "fear": TraitVector(value=0.85, inertia=0.4, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_JIM_PRIDEAUX": Entity(
            id="ENT_JIM_PRIDEAUX", name="Jim Prideaux",
            location_id="LOC_HUNGARY", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.9, inertia=0.75, evidence_strength="strong"),
                "courage": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "paranoia": TraitVector(value=0.2, inertia=0.3, evidence_strength="weak"),
                "grief": TraitVector(value=0.1, inertia=0.25, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_BILL_HAYDON", perceived_state="Haydon is my close friend and trusted comrade",
                       confidence=0.9, inertia=0.75, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_PRIDEAUX_SHOT",
                    status="injured",
                    traits={
                        "paranoia": TraitVector(value=0.7, inertia=0.45, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=1500, triggered_by="EVT_PRIDEAUX_CAPTURED",
                    traits={
                        "loyalty": TraitVector(value=0.65, inertia=0.75, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=16000, triggered_by="EVT_SMILEY_FINDS_PRIDEAUX",
                    location_id="LOC_ENGLAND_EXILE"),
                EntityStateSnapshot(fabula_time=23000, triggered_by="EVT_HAYDON_CONFESSION",
                    traits={
                        "grief": TraitVector(value=0.95, inertia=0.55, evidence_strength="strong"),
                    },
                    beliefs_invalidated=["ENT_BILL_HAYDON"]),
                EntityStateSnapshot(fabula_time=24000, triggered_by="EVT_PRIDEAUX_KILLS_HAYDON",
                    location_id="LOC_SARRATT"),
            ],
        ),
        "ENT_PETER_GUILLAM": Entity(
            id="ENT_PETER_GUILLAM", name="Peter Guillam",
            location_id="LOC_THE_CIRCUS", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                "professionalism": TraitVector(value=0.8, inertia=0.65, evidence_strength="strong"),
                "courage": TraitVector(value=0.75, inertia=0.6, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_GEORGE_SMILEY", perceived_state="Smiley is the only one I can trust",
                       confidence=0.9, inertia=0.75, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=14000, triggered_by="EVT_GUILLAM_STEALS_LOGBOOK",
                    location_id="LOC_THE_CIRCUS"),
            ],
        ),
        "ENT_RICKI_TARR": Entity(
            id="ENT_RICKI_TARR", name="Ricki Tarr",
            location_id="LOC_ISTANBUL", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.7, inertia=0.6, evidence_strength="moderate"),
                "romanticism": TraitVector(value=0.75, inertia=0.5, evidence_strength="moderate"),
                "suspicion": TraitVector(value=0.6, inertia=0.45, evidence_strength="moderate"),
                "fear": TraitVector(value=0.4, inertia=0.3, evidence_strength="weak"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=8000, triggered_by="EVT_IRINA_DEFECTION_REQUEST",
                    traits={
                        "romanticism": TraitVector(value=0.9, inertia=0.55, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=10000, triggered_by="EVT_IRINA_CAPTURED",
                    traits={
                        "fear": TraitVector(value=0.8, inertia=0.4, evidence_strength="strong"),
                        "grief": TraitVector(value=0.85, inertia=0.5, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=11000, triggered_by="EVT_TARR_FLEES",
                    location_id="LOC_SMILEY_HOUSE"),
                EntityStateSnapshot(fabula_time=20000, triggered_by="EVT_TARR_TRAP_PARIS",
                    location_id="LOC_PARIS_OFFICE"),
            ],
        ),
        "ENT_CONNIE_SACHS": Entity(
            id="ENT_CONNIE_SACHS", name="Connie Sachs",
            location_id="LOC_THE_CIRCUS", status="healthy",
            traits={
                "intelligence": TraitVector(value=0.85, inertia=0.75, evidence_strength="strong"),
                "suspicion": TraitVector(value=0.8, inertia=0.65, evidence_strength="strong"),
                "loyalty": TraitVector(value=0.8, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_POLYAKOV", perceived_state="Polyakov is a Soviet mole handler operating in London",
                       confidence=0.85, inertia=0.8, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=3500, triggered_by="EVT_SACHS_SACKED",
                    location_id="LOC_ENGLAND_EXILE"),
            ],
        ),
        "ENT_JERRY_WESTERBY": Entity(
            id="ENT_JERRY_WESTERBY", name="Jerry Westerby",
            location_id="LOC_THE_CIRCUS", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.75, inertia=0.65, evidence_strength="moderate"),
                "professionalism": TraitVector(value=0.7, inertia=0.6, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=13000, triggered_by="EVT_WESTERBY_REVEALS_AFFAIR",
                    location_id="LOC_ENGLAND_EXILE"),
            ],
        ),
        "ENT_OLIVER_LACON": Entity(
            id="ENT_OLIVER_LACON", name="Oliver Lacon",
            location_id="LOC_LACON_HOUSE", status="healthy",
            traits={
                "professionalism": TraitVector(value=0.8, inertia=0.7, evidence_strength="moderate"),
                "loyalty": TraitVector(value=0.75, inertia=0.65, evidence_strength="moderate"),
            },
            beliefs=[],
        ),
        "ENT_KARLA": Entity(
            id="ENT_KARLA", name="Karla (Soviet spymaster)",
            location_id="LOC_MOSCOW_CENTRE", status="healthy",
            traits={
                "intelligence": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "ruthlessness": TraitVector(value=0.9, inertia=0.8, evidence_strength="strong"),
            },
            beliefs=[],
            constants=["offstage"],
        ),
        "ENT_POLYAKOV": Entity(
            id="ENT_POLYAKOV", name="Alexei Polyakov",
            location_id="LOC_SAFE_HOUSE", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.85, inertia=0.75, evidence_strength="strong"),
                "professionalism": TraitVector(value=0.8, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[],
        ),
        "ENT_BORIS": Entity(
            id="ENT_BORIS", name="Boris (Soviet agent, Istanbul)",
            location_id="LOC_ISTANBUL", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.7, inertia=0.6, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=9000, triggered_by="EVT_BORIS_MURDERED",
                    status="dead"),
            ],
        ),
        "ENT_IRINA": Entity(
            id="ENT_IRINA", name="Irina (Boris's wife, defector)",
            location_id="LOC_ISTANBUL", status="healthy",
            traits={
                "courage": TraitVector(value=0.75, inertia=0.6, evidence_strength="moderate"),
                "romanticism": TraitVector(value=0.8, inertia=0.55, evidence_strength="moderate"),
                "fear": TraitVector(value=0.5, inertia=0.3, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=10000, triggered_by="EVT_IRINA_CAPTURED",
                    traits={
                        "fear": TraitVector(value=0.95, inertia=0.45, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=17000, triggered_by="EVT_PRIDEAUX_SEES_IRINA_SHOT",
                    status="dead"),
            ],
        ),
        "ENT_ANN_SMILEY": Entity(
            id="ENT_ANN_SMILEY", name="Ann Smiley (George's wife)",
            location_id="LOC_SMILEY_HOUSE", status="healthy",
            traits={
                "romanticism": TraitVector(value=0.7, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[],
        ),
    },

    # ── EVENTS ──────────────────────────────────────────────────────────
    events=[
        EventNode(id="EVT_PRIDEAUX_HUNGARY_MISSION", fabula_time=500, syuzhet_index=1,
                  event_type="choice", actor_ids=["ENT_CONTROL"], target_ids=["ENT_JIM_PRIDEAUX"],
                  description="Control sends Prideaux to Hungary to meet a Hungarian general who promised to sell the mole's identity."),
        EventNode(id="EVT_PRIDEAUX_SHOT", fabula_time=1000, syuzhet_index=2,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_JIM_PRIDEAUX"],
                  description="Prideaux is shot by Soviet agents in Budapest."),
        EventNode(id="EVT_PRIDEAUX_CAPTURED", fabula_time=1500, syuzhet_index=4,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_JIM_PRIDEAUX"],
                  description="Soviet agents capture the wounded Prideaux."),
        EventNode(id="EVT_PRIDEAUX_KILLED_FALSE", fabula_time=2000, syuzhet_index=5,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_JIM_PRIDEAUX"],
                  description="The Circus receives reports that Prideaux was killed in Hungary. (Later revealed to be false.)"),
        EventNode(id="EVT_CONTROL_FORCED_RETIREMENT", fabula_time=2500, syuzhet_index=6,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_CONTROL", "ENT_GEORGE_SMILEY"],
                  description="Control and Smiley are forced into retirement after the Hungary disaster."),
        EventNode(id="EVT_ALLELINE_BECOMES_CHIEF", fabula_time=3000, syuzhet_index=7,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_PERCY_ALLELINE"],
                  description="Percy Alleline becomes the new Chief of the Circus, with Haydon as his deputy."),
        EventNode(id="EVT_WITCHCRAFT_PROJECT_STARTS", fabula_time=3200, syuzhet_index=8,
                  event_type="choice", actor_ids=["ENT_PERCY_ALLELINE", "ENT_BILL_HAYDON"], target_ids=[],
                  description="The Witchcraft project begins producing high-grade Soviet intelligence shared with the Americans."),
        EventNode(id="EVT_SACHS_SACKED", fabula_time=3500, syuzhet_index=9,
                  event_type="outcome", actor_ids=["ENT_PERCY_ALLELINE"], target_ids=["ENT_CONNIE_SACHS"],
                  description="Connie Sachs is sacked by Alleline after claiming Polyakov is a Soviet mole handler."),
        EventNode(id="EVT_CONTROL_DIES", fabula_time=4000, syuzhet_index=10,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_CONTROL"],
                  description="Control dies, already ill from the forced retirement."),
        EventNode(id="EVT_LACON_RECRUITS_SMILEY", fabula_time=5000, syuzhet_index=11,
                  event_type="choice", actor_ids=["ENT_OLIVER_LACON"], target_ids=["ENT_GEORGE_SMILEY"],
                  description="Lacon brings Smiley out of retirement to investigate Tarr's claim of a mole."),
        EventNode(id="EVT_TARR_ISTANBUL_MISSION", fabula_time=7000, syuzhet_index=12,
                  event_type="choice", actor_ids=["ENT_RICKI_TARR"], target_ids=[],
                  description="Tarr is sent to Istanbul to investigate Soviet agent Boris."),
        EventNode(id="EVT_TARR_MEETS_IRINA", fabula_time=7500, syuzhet_index=13,
                  event_type="outcome", actor_ids=["ENT_RICKI_TARR"], target_ids=["ENT_IRINA"],
                  description="Tarr meets Boris's wife Irina and begins an affair with her."),
        EventNode(id="EVT_IRINA_DEFECTION_REQUEST", fabula_time=8000, syuzhet_index=14,
                  event_type="choice", actor_ids=["ENT_IRINA"], target_ids=["ENT_RICKI_TARR"],
                  description="Irina tells Tarr she wants to defect and reveals there is a mole at the Circus sent by Karla."),
        EventNode(id="EVT_TARR_SENDS_REQUEST", fabula_time=8500, syuzhet_index=16,
                  event_type="choice", actor_ids=["ENT_RICKI_TARR"], target_ids=[],
                  description="Tarr sends Irina's defection request back to London."),
        EventNode(id="EVT_BORIS_MURDERED", fabula_time=9000, syuzhet_index=17,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_BORIS"],
                  description="Boris is suddenly killed in Istanbul."),
        EventNode(id="EVT_IRINA_CAPTURED", fabula_time=10000, syuzhet_index=18,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_IRINA"],
                  description="Irina is captured by Soviet agents and taken back to Russia."),
        EventNode(id="EVT_TARR_FLEES", fabula_time=11000, syuzhet_index=19,
                  event_type="choice", actor_ids=["ENT_RICKI_TARR"], target_ids=[],
                  description="Tarr goes on the run after being accused of defecting and murdering the British station chief."),
        EventNode(id="EVT_SMILEY_INTERVIEWS_SACHS", fabula_time=12000, syuzhet_index=20,
                  event_type="choice", actor_ids=["ENT_GEORGE_SMILEY"], target_ids=["ENT_CONNIE_SACHS"],
                  description="Smiley interviews Connie Sachs, who tells him about Polyakov being a mole handler."),
        EventNode(id="EVT_SMILEY_INTERVIEWS_WESTERBY", fabula_time=13000, syuzhet_index=22,
                  event_type="choice", actor_ids=["ENT_GEORGE_SMILEY"], target_ids=["ENT_JERRY_WESTERBY"],
                  description="Smiley interviews Jerry Westerby, the duty clerk on the night Prideaux was shot."),
        EventNode(id="EVT_WESTERBY_REVEALS_AFFAIR", fabula_time=13000, syuzhet_index=23,
                  event_type="revelation", actor_ids=["ENT_JERRY_WESTERBY"], target_ids=["ENT_GEORGE_SMILEY"],
                  description="Westerby reveals that Ann answered when he called Smiley's house that night, and Haydon arrived shortly after — implying Haydon was with Ann."),
        EventNode(id="EVT_TARR_VISITS_SMILEY", fabula_time=13500, syuzhet_index=24,
                  event_type="choice", actor_ids=["ENT_RICKI_TARR"], target_ids=["ENT_GEORGE_SMILEY"],
                  description="Tarr visits Smiley at his home and tells him the full Istanbul story."),
        EventNode(id="EVT_GUILLAM_STEALS_LOGBOOK", fabula_time=14000, syuzhet_index=25,
                  event_type="choice", actor_ids=["ENT_PETER_GUILLAM"], target_ids=[],
                  description="Guillam steals the Circus duty logbook for the night Tarr called."),
        EventNode(id="EVT_LOGBOOK_PAGES_CUT", fabula_time=14500, syuzhet_index=26,
                  event_type="revelation", actor_ids=["ENT_GEORGE_SMILEY"], target_ids=[],
                  description="Smiley discovers the logbook pages for that night have been cut out — confirming Tarr's story."),
        EventNode(id="EVT_SMILEY_FINDS_PRIDEAUX", fabula_time=16000, syuzhet_index=27,
                  event_type="revelation", actor_ids=["ENT_GEORGE_SMILEY"], target_ids=["ENT_JIM_PRIDEAUX"],
                  description="Smiley locates Prideaux alive in England — the 'killed in Hungary' report was false."),
        EventNode(id="EVT_PRIDEAUX_INTERVIEWED", fabula_time=16500, syuzhet_index=28,
                  event_type="choice", actor_ids=["ENT_GEORGE_SMILEY"], target_ids=["ENT_JIM_PRIDEAUX"],
                  description="Smiley interviews Prideaux, who reveals Control's Tinker/Tailor/Soldier/Poorman/Beggarman codenames for the suspects."),
        EventNode(id="EVT_PRIDEAUX_SEES_IRINA_SHOT", fabula_time=17000, syuzhet_index=30,
                  event_type="revelation", actor_ids=["ENT_JIM_PRIDEAUX"], target_ids=["ENT_GEORGE_SMILEY"],
                  description="Prideaux tells Smiley he saw a blonde female prisoner (Irina) shot during his interrogation."),
        EventNode(id="EVT_TINKER_TAILOR_REVEALED", fabula_time=17500, syuzhet_index=31,
                  event_type="revelation", actor_ids=["ENT_JIM_PRIDEAUX"], target_ids=["ENT_GEORGE_SMILEY"],
                  description="The codenames are revealed: Tinker (Alleline), Tailor (Haydon), Soldier (Bland), Poorman (Esterhase), Beggarman (Smiley)."),
        EventNode(id="EVT_SAFE_HOUSE_MEETINGS_DISCOVERED", fabula_time=18000, syuzhet_index=32,
                  event_type="revelation", actor_ids=["ENT_GEORGE_SMILEY"], target_ids=[],
                  description="Smiley learns that Alleline, Haydon, Bland, and Esterhase meet Polyakov regularly at a safe house."),
        EventNode(id="EVT_ESTERHASE_PRESSED", fabula_time=19000, syuzhet_index=33,
                  event_type="choice", actor_ids=["ENT_GEORGE_SMILEY"], target_ids=["ENT_TOBY_ESTERHASE"],
                  description="Smiley threatens to deport Esterhase (a wanted criminal in Hungary) to get the safe house location."),
        EventNode(id="EVT_SAFE_HOUSE_LOCATION_REVEALED", fabula_time=19500, syuzhet_index=34,
                  event_type="revelation", actor_ids=["ENT_TOBY_ESTERHASE"], target_ids=["ENT_GEORGE_SMILEY"],
                  description="Esterhase reveals the safe house is in Lock Gardens."),
        EventNode(id="EVT_TARR_TRAP_PARIS", fabula_time=20000, syuzhet_index=35,
                  event_type="choice", actor_ids=["ENT_RICKI_TARR"], target_ids=[],
                  description="Tarr appears at the Paris office announcing he knows who the mole is and is ready to give the name."),
        EventNode(id="EVT_MOLE_PANICS", fabula_time=21000, syuzhet_index=37,
                  event_type="outcome", actor_ids=["ENT_BILL_HAYDON"], target_ids=[],
                  description="The mole (Haydon) hears about Tarr and arranges an emergency meeting with Polyakov at the safe house."),
        EventNode(id="EVT_SAFE_HOUSE_AMBUSH", fabula_time=21500, syuzhet_index=38,
                  event_type="choice", actor_ids=["ENT_GEORGE_SMILEY"], target_ids=[],
                  description="Smiley waits at the safe house to catch the mole."),
        EventNode(id="EVT_HAYDON_UNMASKED", fabula_time=22000, syuzhet_index=39,
                  event_type="revelation", actor_ids=["ENT_GEORGE_SMILEY"], target_ids=[],
                  description="Haydon arrives at the safe house and is captured by Smiley — the mole is unmasked."),
        EventNode(id="EVT_HAYDON_CONFESSION", fabula_time=23000, syuzhet_index=40,
                  event_type="revelation", actor_ids=["ENT_BILL_HAYDON"], target_ids=["ENT_GEORGE_SMILEY"],
                  description="At Sarratt, Haydon confesses he seduced Ann on Karla's orders and that Prideaux confided in him before the Hungary mission."),
        EventNode(id="EVT_PRIDEAUX_KILLS_HAYDON", fabula_time=24000, syuzhet_index=42,
                  event_type="choice", actor_ids=["ENT_JIM_PRIDEAUX"], target_ids=["ENT_BILL_HAYDON"],
                  description="Prideaux, learning of Haydon's betrayal, kills Haydon at Sarratt."),
        EventNode(id="EVT_SMILEY_RESTORED_CHIEF", fabula_time=25000, syuzhet_index=43,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_GEORGE_SMILEY"],
                  description="Smiley is restored as Chief of the Circus."),

        # ── UTTERANCES ──────────────────────────────────────────────────
        EventNode(id="EVT_UTT_IRINA_MOLE_CLAIM", event_type="utterance",
                  description="Irina tells Tarr there is a Soviet mole sent by Karla at the top of British Intelligence.",
                  speaker_id="ENT_IRINA", addressee_ids=["ENT_RICKI_TARR"],
                  actor_ids=["ENT_IRINA"], target_ids=["WORLD_SOVIET_MOLE"],
                  content="There is a mole inside the Circus, sent by Moscow Centre, by Karla himself. At the top.",
                  via_channel_id=None, truth_value="true",
                  fabula_time=8000, syuzhet_index=15),
        EventNode(id="EVT_UTT_WESTERBY_DUTY_CALL", event_type="utterance",
                  description="Westerby called Smiley's house the night Prideaux was shot, and Ann answered.",
                  speaker_id="ENT_JERRY_WESTERBY", addressee_ids=["ENT_ANN_SMILEY"],
                  actor_ids=["ENT_JERRY_WESTERBY"], target_ids=["EVT_PRIDEAUX_SHOT"],
                  content="Prideaux has been shot in Hungary — I need instructions.",
                  via_channel_id="CHN_DUTY_PHONE", truth_value="true",
                  fabula_time=1000, syuzhet_index=3),
        EventNode(id="EVT_UTT_SACHS_POLYAKOV_WARNING", event_type="utterance",
                  description="Sachs tells Smiley that Polyakov is a Soviet mole handler and there is a mole within the Circus.",
                  speaker_id="ENT_CONNIE_SACHS", addressee_ids=["ENT_GEORGE_SMILEY"],
                  actor_ids=["ENT_CONNIE_SACHS"], target_ids=["ENT_POLYAKOV"],
                  content="Polyakov is a mole handler, George. The Witchcraft material is coming from our own people, not from Moscow.",
                  via_channel_id=None, truth_value="true",
                  fabula_time=12000, syuzhet_index=21),
        EventNode(id="EVT_UTT_PRIDEAUX_CONFESSION", event_type="utterance",
                  description="Prideaux tells Smiley about the Hungary mission, the Tinker/Tailor codenames, and his brutal interrogation.",
                  speaker_id="ENT_JIM_PRIDEAUX", addressee_ids=["ENT_GEORGE_SMILEY"],
                  actor_ids=["ENT_JIM_PRIDEAUX"], target_ids=["EVT_PRIDEAUX_HUNGARY_MISSION", "EVT_PRIDEAUX_CAPTURED"],
                  content="Control sent me to get the mole's name. He had suspects — Tinker, Tailor, Soldier, Poorman, Beggarman. They tortured me. They already knew about Control's investigation.",
                  via_channel_id=None, truth_value="true",
                  fabula_time=16500, syuzhet_index=29),
        EventNode(id="EVT_UTT_HAYDON_CONFESSION_ANN", event_type="utterance",
                  description="Haydon confesses that he seduced Ann on Karla's orders to distract Smiley.",
                  speaker_id="ENT_BILL_HAYDON", addressee_ids=["ENT_GEORGE_SMILEY"],
                  actor_ids=["ENT_BILL_HAYDON"], target_ids=["ENT_ANN_SMILEY"],
                  content="Karla told me to seduce Ann. To keep you off balance. To make you doubt yourself.",
                  via_channel_id="CHN_SARRATT_INTERROGATION", truth_value="true",
                  fabula_time=23000, syuzhet_index=41),
        EventNode(id="EVT_UTT_TARR_PARIS_ANNOUNCEMENT", event_type="utterance",
                  description="Tarr announces at the Paris office that he knows the mole's identity.",
                  speaker_id="ENT_RICKI_TARR", addressee_ids=["ENT_BILL_HAYDON"],
                  actor_ids=["ENT_RICKI_TARR"], target_ids=["WORLD_SOVIET_MOLE"],
                  content="I know who the mole is and I'm ready to give the name.",
                  via_channel_id="CHN_PARIS_BAIT", truth_value="performative",
                  fabula_time=20000, syuzhet_index=36),
    ],

    # ── CAUSAL TOPOLOGY ─────────────────────────────────────────────────
    causal_topology=[
        # ── chain_reaction (Event → Event) ──
        CausalEdge(source_id="EVT_PRIDEAUX_HUNGARY_MISSION", target_id="EVT_PRIDEAUX_SHOT",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=500, propagation_delay=500),
        CausalEdge(source_id="EVT_PRIDEAUX_SHOT", target_id="EVT_PRIDEAUX_CAPTURED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1000, propagation_delay=500),
        CausalEdge(source_id="EVT_PRIDEAUX_CAPTURED", target_id="EVT_PRIDEAUX_KILLED_FALSE",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=1500, propagation_delay=500),
        CausalEdge(source_id="EVT_PRIDEAUX_KILLED_FALSE", target_id="EVT_CONTROL_FORCED_RETIREMENT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=2000, propagation_delay=500),
        CausalEdge(source_id="EVT_CONTROL_FORCED_RETIREMENT", target_id="EVT_ALLELINE_BECOMES_CHIEF",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2500, propagation_delay=500),
        CausalEdge(source_id="EVT_ALLELINE_BECOMES_CHIEF", target_id="EVT_WITCHCRAFT_PROJECT_STARTS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=3000, propagation_delay=200),
        CausalEdge(source_id="EVT_WITCHCRAFT_PROJECT_STARTS", target_id="EVT_SACHS_SACKED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=3200, propagation_delay=300),
        CausalEdge(source_id="EVT_CONTROL_FORCED_RETIREMENT", target_id="EVT_CONTROL_DIES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2500, propagation_delay=1500),
        CausalEdge(source_id="EVT_TARR_ISTANBUL_MISSION", target_id="EVT_TARR_MEETS_IRINA",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7000, propagation_delay=500),
        CausalEdge(source_id="EVT_TARR_MEETS_IRINA", target_id="EVT_IRINA_DEFECTION_REQUEST",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=7500, propagation_delay=500),
        CausalEdge(source_id="EVT_IRINA_DEFECTION_REQUEST", target_id="EVT_TARR_SENDS_REQUEST",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8000, propagation_delay=500),
        CausalEdge(source_id="EVT_TARR_SENDS_REQUEST", target_id="EVT_BORIS_MURDERED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8500, propagation_delay=500),
        CausalEdge(source_id="EVT_TARR_SENDS_REQUEST", target_id="EVT_IRINA_CAPTURED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=9.0, fabula_time=8500, propagation_delay=1500),
        CausalEdge(source_id="EVT_IRINA_CAPTURED", target_id="EVT_TARR_FLEES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=10000, propagation_delay=1000),
        CausalEdge(source_id="EVT_LACON_RECRUITS_SMILEY", target_id="EVT_SMILEY_INTERVIEWS_SACHS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=5000, propagation_delay=7000),
        CausalEdge(source_id="EVT_SMILEY_INTERVIEWS_SACHS", target_id="EVT_SMILEY_INTERVIEWS_WESTERBY",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=6.0, fabula_time=12000, propagation_delay=1000),
        CausalEdge(source_id="EVT_WESTERBY_REVEALS_AFFAIR", target_id="EVT_GUILLAM_STEALS_LOGBOOK",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=13000, propagation_delay=1000),
        CausalEdge(source_id="EVT_GUILLAM_STEALS_LOGBOOK", target_id="EVT_LOGBOOK_PAGES_CUT",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=8.0, fabula_time=14000, propagation_delay=500),
        CausalEdge(source_id="EVT_LOGBOOK_PAGES_CUT", target_id="EVT_SMILEY_FINDS_PRIDEAUX",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=14500, propagation_delay=1500),
        CausalEdge(source_id="EVT_SMILEY_FINDS_PRIDEAUX", target_id="EVT_PRIDEAUX_INTERVIEWED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=16000, propagation_delay=500),
        CausalEdge(source_id="EVT_PRIDEAUX_INTERVIEWED", target_id="EVT_TINKER_TAILOR_REVEALED",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=9.0, fabula_time=16500, propagation_delay=1000),
        CausalEdge(source_id="EVT_TINKER_TAILOR_REVEALED", target_id="EVT_SAFE_HOUSE_MEETINGS_DISCOVERED",
                   causality_type="chain_reaction", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=17500, propagation_delay=500),
        CausalEdge(source_id="EVT_SAFE_HOUSE_MEETINGS_DISCOVERED", target_id="EVT_ESTERHASE_PRESSED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=18000, propagation_delay=1000),
        CausalEdge(source_id="EVT_ESTERHASE_PRESSED", target_id="EVT_SAFE_HOUSE_LOCATION_REVEALED",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=19000, propagation_delay=500),
        CausalEdge(source_id="EVT_SAFE_HOUSE_LOCATION_REVEALED", target_id="EVT_TARR_TRAP_PARIS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=19500, propagation_delay=500),
        CausalEdge(source_id="EVT_TARR_TRAP_PARIS", target_id="EVT_MOLE_PANICS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=20000, propagation_delay=1000),
        CausalEdge(source_id="EVT_MOLE_PANICS", target_id="EVT_SAFE_HOUSE_AMBUSH",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=21000, propagation_delay=500),
        CausalEdge(source_id="EVT_SAFE_HOUSE_AMBUSH", target_id="EVT_HAYDON_UNMASKED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=21500, propagation_delay=500),
        CausalEdge(source_id="EVT_HAYDON_UNMASKED", target_id="EVT_HAYDON_CONFESSION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=22000, propagation_delay=1000),
        CausalEdge(source_id="EVT_HAYDON_CONFESSION", target_id="EVT_PRIDEAUX_KILLS_HAYDON",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=23000, propagation_delay=1000),
        CausalEdge(source_id="EVT_HAYDON_UNMASKED", target_id="EVT_SMILEY_RESTORED_CHIEF",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=22000, propagation_delay=3000),

        # ── mutation (Event → Entity trait/status) ──
        CausalEdge(source_id="EVT_PRIDEAUX_SHOT", target_id="ENT_JIM_PRIDEAUX",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1000,
                   trait_target="paranoia", trait_delta=0.5),
        CausalEdge(source_id="EVT_PRIDEAUX_CAPTURED", target_id="ENT_JIM_PRIDEAUX",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500,
                   trait_target="loyalty", trait_delta=-0.25),
        CausalEdge(source_id="EVT_CONTROL_FORCED_RETIREMENT", target_id="ENT_CONTROL",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=2500,
                   trait_target="paranoia", trait_delta=0.1),
        CausalEdge(source_id="EVT_CONTROL_DIES", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=4000,
                   trait_target="grief", trait_delta=0.4),
        CausalEdge(source_id="EVT_LACON_RECRUITS_SMILEY", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=6.0, fabula_time=5000,
                   trait_target="suspicion", trait_delta=0.2),
        CausalEdge(source_id="EVT_IRINA_DEFECTION_REQUEST", target_id="ENT_RICKI_TARR",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=8000,
                   trait_target="romanticism", trait_delta=0.15),
        CausalEdge(source_id="EVT_IRINA_CAPTURED", target_id="ENT_RICKI_TARR",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=10000,
                   trait_target="fear", trait_delta=0.4),
        CausalEdge(source_id="EVT_IRINA_CAPTURED", target_id="ENT_IRINA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=10000,
                   trait_target="fear", trait_delta=0.45),
        CausalEdge(source_id="EVT_WESTERBY_REVEALS_AFFAIR", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=9.0, fabula_time=13000,
                   trait_target="suspicion", trait_delta=0.2),
        CausalEdge(source_id="EVT_WESTERBY_REVEALS_AFFAIR", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=13000,
                   trait_target="grief", trait_delta=0.55),
        CausalEdge(source_id="EVT_ESTERHASE_PRESSED", target_id="ENT_TOBY_ESTERHASE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=19000,
                   trait_target="fear", trait_delta=0.35),
        CausalEdge(source_id="EVT_HAYDON_UNMASKED", target_id="ENT_BILL_HAYDON",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=22000,
                   trait_target="composure", trait_delta=-0.7),
        CausalEdge(source_id="EVT_HAYDON_UNMASKED", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=22000,
                   trait_target="suspicion", trait_delta=0.15),
        CausalEdge(source_id="EVT_HAYDON_CONFESSION", target_id="ENT_JIM_PRIDEAUX",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=23000,
                   trait_target="grief", trait_delta=0.85),
        CausalEdge(source_id="EVT_PRIDEAUX_KILLS_HAYDON", target_id="ENT_BILL_HAYDON",
                   causality_type="mutation", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=24000,
                   trait_target="loyalty", trait_delta=-1.0),

        # ── mutation_social (Event → Relationship metric) ──
        # affinity mutations
        CausalEdge(source_id="EVT_CONTROL_FORCED_RETIREMENT", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=2500,
                   trait_target="affinity", trait_delta=0.1, rel_counterpart_id="ENT_CONTROL"),
        CausalEdge(source_id="EVT_WESTERBY_REVEALS_AFFAIR", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=13000,
                   trait_target="affinity", trait_delta=-0.6, rel_counterpart_id="ENT_BILL_HAYDON"),
        CausalEdge(source_id="EVT_WESTERBY_REVEALS_AFFAIR", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=8.0, fabula_time=13000,
                   trait_target="affinity", trait_delta=-0.4, rel_counterpart_id="ENT_ANN_SMILEY"),
        CausalEdge(source_id="EVT_HAYDON_CONFESSION", target_id="ENT_JIM_PRIDEAUX",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=10.0, fabula_time=23000,
                   trait_target="affinity", trait_delta=-0.9, rel_counterpart_id="ENT_BILL_HAYDON"),
        CausalEdge(source_id="EVT_IRINA_DEFECTION_REQUEST", target_id="ENT_RICKI_TARR",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8000,
                   trait_target="affinity", trait_delta=0.7, rel_counterpart_id="ENT_IRINA"),
        CausalEdge(source_id="EVT_IRINA_CAPTURED", target_id="ENT_RICKI_TARR",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=10000,
                   trait_target="affinity", trait_delta=-0.2, rel_counterpart_id="ENT_IRINA"),
        CausalEdge(source_id="EVT_LACON_RECRUITS_SMILEY", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=5000,
                   trait_target="affinity", trait_delta=0.3, rel_counterpart_id="ENT_OLIVER_LACON"),
        CausalEdge(source_id="EVT_ALLELINE_BECOMES_CHIEF", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=3000,
                   trait_target="affinity", trait_delta=-0.4, rel_counterpart_id="ENT_PERCY_ALLELINE"),

        # fear mutations
        CausalEdge(source_id="EVT_PRIDEAUX_CAPTURED", target_id="ENT_JIM_PRIDEAUX",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500,
                   trait_target="fear", trait_delta=0.6, rel_counterpart_id="ENT_KARLA"),
        CausalEdge(source_id="EVT_IRINA_CAPTURED", target_id="ENT_RICKI_TARR",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=10000,
                   trait_target="fear", trait_delta=0.5, rel_counterpart_id="ENT_BILL_HAYDON"),
        CausalEdge(source_id="EVT_ESTERHASE_PRESSED", target_id="ENT_TOBY_ESTERHASE",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=19000,
                   trait_target="fear", trait_delta=0.7, rel_counterpart_id="ENT_GEORGE_SMILEY"),
        CausalEdge(source_id="EVT_TARR_TRAP_PARIS", target_id="ENT_BILL_HAYDON",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=20000,
                   trait_target="fear", trait_delta=0.6, rel_counterpart_id="ENT_RICKI_TARR"),
        CausalEdge(source_id="EVT_HAYDON_UNMASKED", target_id="ENT_BILL_HAYDON",
                   causality_type="mutation_social", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=22000,
                   trait_target="fear", trait_delta=0.7, rel_counterpart_id="ENT_GEORGE_SMILEY"),
        CausalEdge(source_id="EVT_PRIDEAUX_KILLS_HAYDON", target_id="ENT_BILL_HAYDON",
                   causality_type="mutation_social", mechanism="physical", evidence_strength="strong",
                   causal_force=10.0, fabula_time=24000,
                   trait_target="fear", trait_delta=-0.7, rel_counterpart_id="ENT_JIM_PRIDEAUX"),

        # power_dynamic mutations
        CausalEdge(source_id="EVT_ALLELINE_BECOMES_CHIEF", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=3000,
                   trait_target="power_dynamic", trait_delta=-0.6, rel_counterpart_id="ENT_PERCY_ALLELINE"),
        CausalEdge(source_id="EVT_SACHS_SACKED", target_id="ENT_CONNIE_SACHS",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=3500,
                   trait_target="power_dynamic", trait_delta=-0.7, rel_counterpart_id="ENT_PERCY_ALLELINE"),
        CausalEdge(source_id="EVT_LACON_RECRUITS_SMILEY", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation_social", mechanism="social", evidence_strength="moderate",
                   causal_force=6.0, fabula_time=5000,
                   trait_target="power_dynamic", trait_delta=-0.3, rel_counterpart_id="ENT_OLIVER_LACON"),
        CausalEdge(source_id="EVT_ESTERHASE_PRESSED", target_id="ENT_TOBY_ESTERHASE",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=19000,
                   trait_target="power_dynamic", trait_delta=-0.6, rel_counterpart_id="ENT_GEORGE_SMILEY"),
        CausalEdge(source_id="EVT_HAYDON_UNMASKED", target_id="ENT_BILL_HAYDON",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=9.0, fabula_time=22000,
                   trait_target="power_dynamic", trait_delta=-0.8, rel_counterpart_id="ENT_GEORGE_SMILEY"),
        CausalEdge(source_id="EVT_SMILEY_RESTORED_CHIEF", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation_social", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=25000,
                   trait_target="power_dynamic", trait_delta=0.7, rel_counterpart_id="ENT_PERCY_ALLELINE"),
        CausalEdge(source_id="EVT_WESTERBY_REVEALS_AFFAIR", target_id="ENT_GEORGE_SMILEY",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=13000,
                   trait_target="power_dynamic", trait_delta=-0.3, rel_counterpart_id="ENT_ANN_SMILEY"),
        CausalEdge(source_id="EVT_HAYDON_CONFESSION", target_id="ENT_BILL_HAYDON",
                   causality_type="mutation_social", mechanism="epistemic", evidence_strength="strong",
                   causal_force=7.0, fabula_time=23000,
                   trait_target="power_dynamic", trait_delta=-0.5, rel_counterpart_id="ENT_KARLA"),

        # ── affordance_gate (State → Event) ──
        CausalEdge(source_id="OBJ_WITCHCRAFT_MATERIAL", target_id="EVT_WITCHCRAFT_PROJECT_STARTS",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="strong",
                   causal_force=8.0, fabula_time=3200),
        CausalEdge(source_id="OBJ_DUTY_LOGBOOK", target_id="EVT_GUILLAM_STEALS_LOGBOOK",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="strong",
                   causal_force=7.0, fabula_time=14000),
        CausalEdge(source_id="OBJ_DUTY_LOGBOOK", target_id="EVT_LOGBOOK_PAGES_CUT",
                   causality_type="affordance_gate", mechanism="epistemic", evidence_strength="strong",
                   causal_force=9.0, fabula_time=14500),
        CausalEdge(source_id="ENT_TOBY_ESTERHASE", target_id="EVT_SAFE_HOUSE_LOCATION_REVEALED",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="strong",
                   causal_force=8.0, fabula_time=19500),
        CausalEdge(source_id="ENT_RICKI_TARR", target_id="EVT_TARR_TRAP_PARIS",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=20000),

        # ── ambient_propagation (State → State) ──
        CausalEdge(source_id="LOC_THE_CIRCUS", target_id="ENT_GEORGE_SMILEY",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=5000),
        CausalEdge(source_id="LOC_SAFE_HOUSE", target_id="ENT_BILL_HAYDON",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.0, fabula_time=22000),
        CausalEdge(source_id="LOC_SARRATT", target_id="ENT_BILL_HAYDON",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="weak",
                   causal_force=3.5, fabula_time=23000),

        # ── WORLD_ → Event (named-latent common-cause wiring) ──
        CausalEdge(source_id="WORLD_COLD_WAR_TRADECRAFT", target_id="EVT_PRIDEAUX_HUNGARY_MISSION",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=500),
        CausalEdge(source_id="WORLD_COLD_WAR_TRADECRAFT", target_id="EVT_WITCHCRAFT_PROJECT_STARTS",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=6.0, fabula_time=3200),
        CausalEdge(source_id="WORLD_INSTITUTIONAL_PARANOIA", target_id="EVT_CONTROL_FORCED_RETIREMENT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=2500),
        CausalEdge(source_id="WORLD_INSTITUTIONAL_PARANOIA", target_id="EVT_SACHS_SACKED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=3500),
        CausalEdge(source_id="WORLD_SOVIET_MOLE", target_id="EVT_PRIDEAUX_SHOT",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1000),
        CausalEdge(source_id="WORLD_SOVIET_MOLE", target_id="EVT_IRINA_CAPTURED",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=10000),
        CausalEdge(source_id="WORLD_SOVIET_MOLE", target_id="EVT_BORIS_MURDERED",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=9000),
        CausalEdge(source_id="WORLD_KARLA_ASYMMETRY", target_id="EVT_HAYDON_CONFESSION",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=23000),

        # ── orphan utterance wirings ──
        CausalEdge(source_id="EVT_IRINA_DEFECTION_REQUEST", target_id="EVT_UTT_IRINA_MOLE_CLAIM",
                   causality_type="chain_reaction", mechanism="performative", evidence_strength="strong",
                   causal_force=8.0, fabula_time=8000, propagation_delay=0),
        CausalEdge(source_id="EVT_PRIDEAUX_SHOT", target_id="EVT_UTT_WESTERBY_DUTY_CALL",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1000, propagation_delay=0),
        CausalEdge(source_id="EVT_SMILEY_INTERVIEWS_SACHS", target_id="EVT_UTT_SACHS_POLYAKOV_WARNING",
                   causality_type="chain_reaction", mechanism="performative", evidence_strength="strong",
                   causal_force=7.0, fabula_time=12000, propagation_delay=0),
        CausalEdge(source_id="EVT_PRIDEAUX_INTERVIEWED", target_id="EVT_UTT_PRIDEAUX_CONFESSION",
                   causality_type="chain_reaction", mechanism="performative", evidence_strength="strong",
                   causal_force=8.0, fabula_time=16500, propagation_delay=0),
        CausalEdge(source_id="EVT_HAYDON_CONFESSION", target_id="EVT_UTT_HAYDON_CONFESSION_ANN",
                   causality_type="chain_reaction", mechanism="performative", evidence_strength="strong",
                   causal_force=8.0, fabula_time=23000, propagation_delay=0),
        CausalEdge(source_id="EVT_TARR_TRAP_PARIS", target_id="EVT_UTT_TARR_PARIS_ANNOUNCEMENT",
                   causality_type="chain_reaction", mechanism="performative", evidence_strength="strong",
                   causal_force=8.0, fabula_time=20000, propagation_delay=0),

        # ─── auto-patched mutation_social edges (per-axis coverage) ───
        CausalEdge(source_id="EVT_ALLELINE_BECOMES_CHIEF", target_id="ENT_PERCY_ALLELINE", rel_counterpart_id="ENT_GEORGE_SMILEY", causality_type="mutation_social", trait_target="affinity", trait_delta=-0.3, mechanism="social", evidence_strength="moderate", causal_force=6.0, fabula_time=3000, propagation_delay=0),
        CausalEdge(source_id="EVT_TARR_MEETS_IRINA", target_id="ENT_IRINA", rel_counterpart_id="ENT_RICKI_TARR", causality_type="mutation_social", trait_target="affinity", trait_delta=0.75, mechanism="emotional", evidence_strength="strong", causal_force=8.0, fabula_time=7500, propagation_delay=0),
        CausalEdge(source_id="EVT_HAYDON_CONFESSION", target_id="ENT_BILL_HAYDON", rel_counterpart_id="ENT_KARLA", causality_type="mutation_social", trait_target="affinity", trait_delta=0.9, mechanism="betrayal", evidence_strength="strong", causal_force=9.0, fabula_time=23000, propagation_delay=0),
        CausalEdge(source_id="EVT_SACHS_SACKED", target_id="ENT_CONNIE_SACHS", rel_counterpart_id="ENT_PERCY_ALLELINE", causality_type="mutation_social", trait_target="affinity", trait_delta=-0.6, mechanism="social", evidence_strength="strong", causal_force=7.0, fabula_time=3500, propagation_delay=0),
        CausalEdge(source_id="EVT_WESTERBY_REVEALS_AFFAIR", target_id="ENT_GEORGE_SMILEY", rel_counterpart_id="ENT_BILL_HAYDON", causality_type="mutation_social", trait_target="fear", trait_delta=0.3, mechanism="psychological", evidence_strength="moderate", causal_force=6.0, fabula_time=13000, propagation_delay=0),
        CausalEdge(source_id="EVT_TARR_MEETS_IRINA", target_id="ENT_RICKI_TARR", rel_counterpart_id="ENT_IRINA", causality_type="mutation_social", trait_target="fear", trait_delta=0.2, mechanism="epistemic", evidence_strength="weak", causal_force=4.0, fabula_time=7500, propagation_delay=0),
        CausalEdge(source_id="EVT_ALLELINE_BECOMES_CHIEF", target_id="ENT_PERCY_ALLELINE", rel_counterpart_id="ENT_GEORGE_SMILEY", causality_type="mutation_social", trait_target="power_dynamic", trait_delta=0.6, mechanism="social", evidence_strength="strong", causal_force=7.0, fabula_time=3000, propagation_delay=0),
        CausalEdge(source_id="EVT_CONTROL_FORCED_RETIREMENT", target_id="ENT_GEORGE_SMILEY", rel_counterpart_id="ENT_CONTROL", causality_type="mutation_social", trait_target="power_dynamic", trait_delta=-0.5, mechanism="social", evidence_strength="strong", causal_force=7.0, fabula_time=2500, propagation_delay=0),
        CausalEdge(source_id="EVT_GUILLAM_STEALS_LOGBOOK", target_id="ENT_PETER_GUILLAM", rel_counterpart_id="ENT_GEORGE_SMILEY", causality_type="mutation_social", trait_target="affinity", trait_delta=0.4, mechanism="social", evidence_strength="strong", causal_force=7.0, fabula_time=14000, propagation_delay=0),
    ],

    # ── SPATIAL TOPOLOGY ────────────────────────────────────────────────
    spatial_topology=[
        SpatialEdge(source_id="LOC_THE_CIRCUS", target_id="LOC_SMILEY_HOUSE"),
        SpatialEdge(source_id="LOC_THE_CIRCUS", target_id="LOC_SAFE_HOUSE"),
        SpatialEdge(source_id="LOC_THE_CIRCUS", target_id="LOC_LACON_HOUSE"),
        SpatialEdge(source_id="LOC_SMILEY_HOUSE", target_id="LOC_ENGLAND_EXILE"),
        SpatialEdge(source_id="LOC_SAFE_HOUSE", target_id="LOC_SARRATT"),
        SpatialEdge(source_id="LOC_THE_CIRCUS", target_id="LOC_PARIS_OFFICE"),
        SpatialEdge(source_id="LOC_THE_CIRCUS", target_id="LOC_ISTANBUL"),
        SpatialEdge(source_id="LOC_HUNGARY", target_id="LOC_ENGLAND_EXILE"),
    ],

    # ── INFORMATION TOPOLOGY ────────────────────────────────────────────
    channels={
        "CHN_WITCHCRAFT_DROP": Channel(
            id="CHN_WITCHCRAFT_DROP",
            name="Witchcraft Dead-Drop (Polyakov ↔ Mole)",
            medium="dead_drop",
            participant_ids=["ENT_POLYAKOV", "ENT_BILL_HAYDON"],
            directionality="duplex",
            intelligibility={"ENT_POLYAKOV": 1.0, "ENT_BILL_HAYDON": 1.0},
            established_at_fabula=3200,
            terminated_at_fabula=22000,
            evidence_strength="strong",
        ),
        "CHN_DUTY_PHONE": Channel(
            id="CHN_DUTY_PHONE",
            name="Circus Duty Officer Phone Line",
            medium="telephone",
            participant_ids=["ENT_JERRY_WESTERBY", "ENT_ANN_SMILEY"],
            directionality="duplex",
            established_at_fabula=1000,
            terminated_at_fabula=1000,
            evidence_strength="strong",
        ),
        "CHN_SARRATT_INTERROGATION": Channel(
            id="CHN_SARRATT_INTERROGATION",
            name="Sarratt Interrogation (Haydon → Smiley)",
            medium="interrogation",
            participant_ids=["ENT_BILL_HAYDON", "ENT_GEORGE_SMILEY"],
            directionality="simplex",
            established_at_fabula=23000,
            terminated_at_fabula=23000,
            evidence_strength="strong",
        ),
        "CHN_PARIS_BAIT": Channel(
            id="CHN_PARIS_BAIT",
            name="Tarr's Paris Broadcast (Trap)",
            medium="broadcast",
            participant_ids=["ENT_RICKI_TARR", "ENT_BILL_HAYDON"],
            directionality="broadcast",
            intelligibility={"ENT_BILL_HAYDON": 1.0},
            established_at_fabula=20000,
            terminated_at_fabula=20000,
            evidence_strength="strong",
        ),
        "CHN_KARLA_HANDLER": Channel(
            id="CHN_KARLA_HANDLER",
            name="Karla's Handler Channel (Polyakov ↔ Karla, offstage)",
            medium="classified_pipeline",
            participant_ids=["ENT_POLYAKOV", "ENT_KARLA"],
            directionality="duplex",
            established_at_fabula=0,
            terminated_at_fabula=None,
            evidence_strength="moderate",
        ),
    },

    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_COLD_WAR_TRADECRAFT": GlobalTrait(
            id="WORLD_COLD_WAR_TRADECRAFT",
            name="Cold War Tradecraft",
            description="The espionage methods and institutional practices of the British and Soviet intelligence services during the Cold War. Shapes every operational decision.",
            category="governance",
            magnitude=TraitVector(value=0.85, inertia=0.8, evidence_strength="strong"),
            affected_domains=["social", "psychological", "informational"],
        ),
        "WORLD_INSTITUTIONAL_PARANOIA": GlobalTrait(
            id="WORLD_INSTITUTIONAL_PARANOIA",
            name="Institutional Paranoia",
            description="The pervasive distrust and suspicion within British Intelligence — colleagues suspect colleagues, loyalty is questioned, and bureaucratic infighting is rife.",
            category="social_structure",
            magnitude=TraitVector(value=0.7, inertia=0.65, evidence_strength="strong"),
            affected_domains=["psychological", "social", "epistemic"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=2500, triggered_by="EVT_CONTROL_FORCED_RETIREMENT",
                    magnitude=TraitVector(value=0.8, inertia=0.7, evidence_strength="strong"),
                    description="Control's forced retirement deepens institutional paranoia — the mole hunt begins in earnest."),
                WorldTraitSnapshot(fabula_time=22000, triggered_by="EVT_HAYDON_UNMASKED",
                    magnitude=TraitVector(value=0.95, inertia=0.75, evidence_strength="strong"),
                    description="Haydon's unmasking shatters trust — institutional paranoia reaches its peak."),
            ],
        ),
        "WORLD_SOVIET_MOLE": GlobalTrait(
            id="WORLD_SOVIET_MOLE",
            name="Soviet Mole (Karla's Agent)",
            description="The presence of a high-level Soviet mole (Haydon) inside British Intelligence, sent by Karla. This is a named-latent common cause — not a single event but the shared driver of the Prideaux disaster, Irina's capture, Boris's murder, and the Witchcraft deception.",
            category="cosmology",
            magnitude=TraitVector(value=0.75, inertia=0.9, evidence_strength="strong"),
            affected_domains=["psychological", "social", "informational"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=22000, triggered_by="EVT_HAYDON_UNMASKED",
                    magnitude=TraitVector(value=0.0, inertia=0.9, evidence_strength="strong"),
                    description="The mole is unmasked and captured — the threat is neutralized."),
            ],
        ),
        "WORLD_KARLA_ASYMMETRY": GlobalTrait(
            id="WORLD_KARLA_ASYMMETRY",
            name="Karla's Offstage Pressure",
            description="Karla, the Soviet spymaster, operates entirely offstage yet exerts constant strategic pressure on the Circus through his mole (Haydon) and handler (Polyakov). A named-latent adversarial force.",
            category="cosmology",
            magnitude=TraitVector(value=0.65, inertia=0.85, evidence_strength="moderate"),
            affected_domains=["psychological", "epistemic"],
        ),
        "WORLD_BRITISH_DECLINE": GlobalTrait(
            id="WORLD_BRITISH_DECLINE",
            name="Post-Imperial British Decline",
            description="The fading power of British Intelligence in the Cold War — dependent on American intelligence sharing, compromised by Soviet infiltration, and plagued by internal decay.",
            category="social_structure",
            magnitude=TraitVector(value=0.6, inertia=0.75, evidence_strength="moderate"),
            affected_domains=["social", "psychological"],
        ),
    },

    # ── SOCIAL TOPOLOGY (per-axis RelationshipMetric) ──────────────────
    social_topology=[
        # Smiley ↔ Control
        RelationshipEdge(
            source_entity_id="ENT_GEORGE_SMILEY", target_entity_id="ENT_CONTROL",
            metrics={
                "affinity":      RelationshipMetric(value=0.85, inertia=0.6, evidence_strength="strong", last_updated_fabula=2500),
                "power_dynamic": RelationshipMetric(value=-0.5, inertia=0.7, evidence_strength="strong", last_updated_fabula=0),
            },
        ),
        # Smiley ↔ Haydon
        RelationshipEdge(
            source_entity_id="ENT_GEORGE_SMILEY", target_entity_id="ENT_BILL_HAYDON",
            metrics={
                "affinity":      RelationshipMetric(value=0.15, inertia=0.55, evidence_strength="strong", last_updated_fabula=13000),
                "fear":          RelationshipMetric(value=0.3, inertia=0.25, evidence_strength="moderate", last_updated_fabula=22000),
            },
        ),
        # Smiley ↔ Ann
        RelationshipEdge(
            source_entity_id="ENT_GEORGE_SMILEY", target_entity_id="ENT_ANN_SMILEY",
            metrics={
                "affinity":      RelationshipMetric(value=0.4, inertia=0.5, evidence_strength="strong", last_updated_fabula=13000),
                "power_dynamic": RelationshipMetric(value=-0.3, inertia=0.6, evidence_strength="moderate", last_updated_fabula=13000),
            },
        ),
        # Smiley ↔ Alleline
        RelationshipEdge(
            source_entity_id="ENT_GEORGE_SMILEY", target_entity_id="ENT_PERCY_ALLELINE",
            metrics={
                "affinity":      RelationshipMetric(value=-0.4, inertia=0.5, evidence_strength="moderate", last_updated_fabula=3000),
                "power_dynamic": RelationshipMetric(value=-0.6, inertia=0.65, evidence_strength="strong", last_updated_fabula=3000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_PERCY_ALLELINE", target_entity_id="ENT_GEORGE_SMILEY",
            metrics={
                "affinity":      RelationshipMetric(value=-0.3, inertia=0.45, evidence_strength="moderate", last_updated_fabula=3000),
                "power_dynamic": RelationshipMetric(value=0.6, inertia=0.65, evidence_strength="strong", last_updated_fabula=25000),
            },
        ),
        # Smiley ↔ Lacon
        RelationshipEdge(
            source_entity_id="ENT_GEORGE_SMILEY", target_entity_id="ENT_OLIVER_LACON",
            metrics={
                "affinity":      RelationshipMetric(value=0.6, inertia=0.5, evidence_strength="moderate", last_updated_fabula=5000),
                "power_dynamic": RelationshipMetric(value=-0.3, inertia=0.6, evidence_strength="moderate", last_updated_fabula=5000),
            },
        ),
        # Prideaux ↔ Haydon
        RelationshipEdge(
            source_entity_id="ENT_JIM_PRIDEAUX", target_entity_id="ENT_BILL_HAYDON",
            metrics={
                "affinity":      RelationshipMetric(value=-0.9, inertia=0.75, evidence_strength="strong", last_updated_fabula=23000),
                "fear":          RelationshipMetric(value=0.0, inertia=0.2, evidence_strength="weak", last_updated_fabula=24000, observed=False),
            },
        ),
        # Tarr ↔ Irina
        RelationshipEdge(
            source_entity_id="ENT_RICKI_TARR", target_entity_id="ENT_IRINA",
            metrics={
                "affinity":      RelationshipMetric(value=0.7, inertia=0.55, evidence_strength="strong", last_updated_fabula=10000),
                "fear":          RelationshipMetric(value=0.2, inertia=0.25, evidence_strength="weak", last_updated_fabula=10000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_IRINA", target_entity_id="ENT_RICKI_TARR",
            metrics={
                "affinity":      RelationshipMetric(value=0.75, inertia=0.55, evidence_strength="strong", last_updated_fabula=8000),
            },
        ),
        # Tarr ↔ Haydon (fear only)
        RelationshipEdge(
            source_entity_id="ENT_RICKI_TARR", target_entity_id="ENT_BILL_HAYDON",
            metrics={
                "fear":          RelationshipMetric(value=0.5, inertia=0.3, evidence_strength="moderate", last_updated_fabula=10000),
            },
        ),
        # Esterhase ↔ Smiley
        RelationshipEdge(
            source_entity_id="ENT_TOBY_ESTERHASE", target_entity_id="ENT_GEORGE_SMILEY",
            metrics={
                "fear":          RelationshipMetric(value=0.7, inertia=0.35, evidence_strength="strong", last_updated_fabula=19000),
                "power_dynamic": RelationshipMetric(value=-0.6, inertia=0.6, evidence_strength="strong", last_updated_fabula=19000),
            },
        ),
        # Haydon ↔ Smiley
        RelationshipEdge(
            source_entity_id="ENT_BILL_HAYDON", target_entity_id="ENT_GEORGE_SMILEY",
            metrics={
                "fear":          RelationshipMetric(value=0.7, inertia=0.35, evidence_strength="strong", last_updated_fabula=22000),
                "power_dynamic": RelationshipMetric(value=-0.8, inertia=0.65, evidence_strength="strong", last_updated_fabula=22000),
            },
        ),
        # Haydon ↔ Karla
        RelationshipEdge(
            source_entity_id="ENT_BILL_HAYDON", target_entity_id="ENT_KARLA",
            metrics={
                "affinity":      RelationshipMetric(value=0.9, inertia=0.85, evidence_strength="strong", last_updated_fabula=0),
                "power_dynamic": RelationshipMetric(value=-0.5, inertia=0.75, evidence_strength="strong", last_updated_fabula=23000),
            },
        ),
        # Prideaux ↔ Karla
        RelationshipEdge(
            source_entity_id="ENT_JIM_PRIDEAUX", target_entity_id="ENT_KARLA",
            metrics={
                "fear":          RelationshipMetric(value=0.6, inertia=0.4, evidence_strength="strong", last_updated_fabula=1500),
            },
        ),
        # Haydon ↔ Tarr
        RelationshipEdge(
            source_entity_id="ENT_BILL_HAYDON", target_entity_id="ENT_RICKI_TARR",
            metrics={
                "fear":          RelationshipMetric(value=0.6, inertia=0.3, evidence_strength="strong", last_updated_fabula=20000),
            },
        ),
        # Sachs ↔ Alleline
        RelationshipEdge(
            source_entity_id="ENT_CONNIE_SACHS", target_entity_id="ENT_PERCY_ALLELINE",
            metrics={
                "affinity":      RelationshipMetric(value=-0.6, inertia=0.6, evidence_strength="strong", last_updated_fabula=3500),
                "power_dynamic": RelationshipMetric(value=-0.7, inertia=0.7, evidence_strength="strong", last_updated_fabula=3500),
            },
        ),
        # Guillam ↔ Smiley
        RelationshipEdge(
            source_entity_id="ENT_PETER_GUILLAM", target_entity_id="ENT_GEORGE_SMILEY",
            metrics={
                "affinity":      RelationshipMetric(value=0.85, inertia=0.7, evidence_strength="strong", last_updated_fabula=0),
            },
        ),
    ],
)