# SPDX-FileCopyrightText: 2026 David Rae Wilmot
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Wuthering Heights — high-fidelity WorldStateV1 test fixture.

Authored against the current ingestion prompts. Demonstrates all five
CausalEdge modalities, per-axis ``RelationshipMetric`` (only observed
axes populated), explicit ``evidence_strength`` everywhere, and named-
latent WORLD_ traits (Yorkshire class hierarchy, the moors as
intrusive cosmology, primogeniture and entail) wired as common-cause
parents over the events they jointly drive.
"""
from shadow_loom.models import (
    Channel,
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, RelationshipMetric, TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
    NarrativeStyle,
)

world_state = WorldStateV1(
    narrative_style=NarrativeStyle(
        format='synopsis',
        target_word_min=271,
        target_word_max=600,
        prose_density='sparse',
        voice='synoptic narration; no dialogue; condensed scene description; third-person POV; past tense',
        style_exemplar='Opening\n\nIn 1801, Mr Lockwood, the new tenant at Thrushcross Grange in Yorkshire, visits his landlord, Heathcliff, at his remote moorland farmhouse, Wuthering Heights. There he meets a reserved young woman (later identified as Cathy Linton), Joseph, an ill-tempered servant, and Hareton, an uneducated young man who speaks like a servant. Everyone is sullen and inhospitable. Snowed in for the night, Lockwood reads diary entries of the former inhabitant of his room, Catherine Earnshaw, and has a nightmare in which a ghostly Catherine begs to enter through the window.',
        source_word_count=814,
    ),
    # ── LOCATIONS ──────────────────────────────────────────────────────
    locations={
        "LOC_WUTHERING_HEIGHTS": Location(
            name="Wuthering Heights",
            description="The Earnshaws' wind-battered hilltop farmhouse on the Yorkshire moors; site of every act of cruelty and most acts of love in the saga.",
            ambient_state={
                "harshness": AmbientVector(value=0.9, volatility=0.2, evidence_strength="strong"),
                "isolation": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
                "violence": AmbientVector(value=0.8, volatility=0.4, evidence_strength="strong"),
            },
        ),
        "LOC_THRUSHCROSS_GRANGE": Location(
            name="Thrushcross Grange",
            description="The Lintons' refined valley estate; symbol of civilised gentility against the Heights' wildness.",
            ambient_state={
                "refinement": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
                "comfort": AmbientVector(value=0.8, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_MOORS": Location(
            name="The Yorkshire Moors",
            description="The wild heath between the two houses where Catherine and Heathcliff run free as children and where their ghosts are later reported.",
            ambient_state={
                "wildness": AmbientVector(value=0.95, volatility=0.3, evidence_strength="strong"),
                "supernatural": AmbientVector(value=0.6, volatility=0.4, evidence_strength="moderate"),
            },
        ),
        "LOC_LIVERPOOL": Location(
            name="Liverpool Streets",
            description="Dock city where Mr Earnshaw finds the orphan Heathcliff and brings him home.",
            ambient_state={
                "destitution": AmbientVector(value=0.85, volatility=0.3, evidence_strength="strong"),
            },
        ),
        "LOC_GIMMERTON_KIRK": Location(
            name="Gimmerton Kirkyard",
            description="Hillside graveyard where Catherine, Edgar, and finally Heathcliff are buried side by side.",
            ambient_state={
                "stillness": AmbientVector(value=0.9, volatility=0.1, evidence_strength="strong"),
            },
        ),
    },

    # ── OBJECTS ────────────────────────────────────────────────────────
    objects={
        "OBJ_CATHERINES_DIARY": NarrativeObject(
            id="OBJ_CATHERINES_DIARY", name="Catherine's Childhood Diary",
            location_id="LOC_WUTHERING_HEIGHTS", owner_id=None,
            properties={"state": "preserved", "content": "earnshaw_grievances"},
            affordances=[Affordance(action="reveal_past", target_type="Entity")],
        ),
        "OBJ_HEIGHTS_MORTGAGE": NarrativeObject(
            id="OBJ_HEIGHTS_MORTGAGE", name="Mortgage on Wuthering Heights",
            location_id=None, owner_id="ENT_HEATHCLIFF",
            properties={"state": "held_against_hindley", "originated": "gambling_debt"},
            affordances=[Affordance(action="dispossess", target_type="Entity")],
        ),
        "OBJ_GRANGE_DEED": NarrativeObject(
            id="OBJ_GRANGE_DEED", name="Thrushcross Grange Entail",
            location_id="LOC_THRUSHCROSS_GRANGE", owner_id="ENT_EDGAR",
            properties={"state": "entailed", "successor_clause": "edgar_heir_or_isabellas_heir"},
            affordances=[Affordance(action="transfer_estate", target_type="Entity")],
        ),
        "OBJ_CATHERINES_GRAVE": NarrativeObject(
            id="OBJ_CATHERINES_GRAVE", name="Catherine's Grave",
            location_id="LOC_GIMMERTON_KIRK", owner_id=None,
            properties={"state": "twice_disinterred"},
            affordances=[Affordance(action="haunt", target_type="Entity")],
        ),
    },

    # ── ENTITIES ────────────────────────────────────────────────────────
    entities={
        "ENT_HEATHCLIFF": Entity(
            id="ENT_HEATHCLIFF", name="Heathcliff",
            location_id="LOC_LIVERPOOL", status="healthy",
            traits={
                "intensity": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "vengefulness": TraitVector(value=0.3, inertia=0.45, evidence_strength="moderate"),
                "devotion": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "cruelty": TraitVector(value=0.2, inertia=0.4, evidence_strength="weak"),
                "endurance": TraitVector(value=0.9, inertia=0.75, evidence_strength="strong"),
                "despair": TraitVector(value=0.1, inertia=0.3, evidence_strength="weak"),
                "grief": TraitVector(value=0.1, inertia=0.3, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_CATHERINE",
                       perceived_state="Catherine and I are the same soul",
                       confidence=1.0, inertia=0.95, established_at_fabula=2000, evidence_strength="strong"),
            ],
            constants=["foundling_origin", "racial_other"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_EARNSHAW_BRINGS_HEATHCLIFF",
                    location_id="LOC_WUTHERING_HEIGHTS"),
                EntityStateSnapshot(fabula_time=3500, triggered_by="EVT_OLD_EARNSHAW_DIES",
                    traits={
                        "vulnerability": TraitVector(value=0.50, inertia=0.50, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=4000, triggered_by="EVT_HINDLEY_DEMOTES_HEATHCLIFF",
                    traits={
                        "vengefulness": TraitVector(value=0.7, inertia=0.6, evidence_strength="strong"),
                        "endurance": TraitVector(value=0.95, inertia=0.8, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_HINDLEY",
                               perceived_state="I will live to ruin Hindley and his line",
                               confidence=0.85, inertia=0.7, established_at_fabula=4000, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=7000, triggered_by="EVT_HEATHCLIFF_OVERHEARS",
                    traits={
                        "despair": TraitVector(value=0.85, inertia=0.5, evidence_strength="strong"),
                        "vengefulness": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=7500, triggered_by="EVT_HEATHCLIFF_FLEES",
                    location_id=None),
                EntityStateSnapshot(fabula_time=9700, triggered_by="EVT_HEATHCLIFF_RETURNS",
                    location_id="LOC_THRUSHCROSS_GRANGE",
                    traits={
                        "cruelty": TraitVector(value=0.7, inertia=0.55, evidence_strength="strong"),
                        "vengefulness": TraitVector(value=0.95, inertia=0.7, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=11000, triggered_by="EVT_CATHERINE_DIES",
                    location_id="LOC_WUTHERING_HEIGHTS",
                    traits={
                        "grief": TraitVector(value=1.0, inertia=0.85, evidence_strength="strong"),
                        "despair": TraitVector(value=0.95, inertia=0.7, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_CATHERINE",
                               perceived_state="Be with me always — take any form — drive me mad!",
                               confidence=1.0, inertia=0.9, established_at_fabula=11000, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=18500, triggered_by="EVT_HEATHCLIFF_OPENS_GRAVE_AGAIN",
                    traits={
                        "vengefulness": TraitVector(value=0.00, inertia=0.45, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=19000, triggered_by="EVT_HEATHCLIFF_STOPS_EATING",
                    status="ill",
                    traits={
                        "vengefulness": TraitVector(value=0.2, inertia=0.7, evidence_strength="strong"),
                        "despair": TraitVector(value=1.0, inertia=0.75, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=19500, triggered_by="EVT_HEATHCLIFF_DIES",
                    status="dead", location_id="LOC_WUTHERING_HEIGHTS"),
                
            ],
        ),
        "ENT_CATHERINE": Entity(
            id="ENT_CATHERINE", name="Catherine Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "wildness": TraitVector(value=0.9, inertia=0.7, evidence_strength="strong"),
                "passion": TraitVector(value=0.95, inertia=0.7, evidence_strength="strong"),
                "vanity": TraitVector(value=0.7, inertia=0.55, evidence_strength="strong"),
                "self_division": TraitVector(value=0.4, inertia=0.4, evidence_strength="moderate"),
                "wilfulness": TraitVector(value=0.9, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF",
                       perceived_state="I am Heathcliff — he is more myself than I am",
                       confidence=1.0, inertia=0.85, established_at_fabula=2000, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_EARNSHAW_BRINGS_HEATHCLIFF",
                    traits={
                        "bond": TraitVector(value=0.50, inertia=0.50, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=6000, triggered_by="EVT_CATHERINE_AT_LINTONS",
                    traits={
                        "vanity": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                        "self_division": TraitVector(value=0.8, inertia=0.55, evidence_strength="strong"),
                    },
                    location_id="LOC_THRUSHCROSS_GRANGE"),
                EntityStateSnapshot(fabula_time=7500, triggered_by="EVT_HEATHCLIFF_FLEES",
                    status="ill",
                    traits={
                        "passion": TraitVector(value=1.0, inertia=0.75, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=9500, triggered_by="EVT_CATHERINE_MARRIES_EDGAR",
                    location_id="LOC_THRUSHCROSS_GRANGE"),
                EntityStateSnapshot(fabula_time=10500, triggered_by="EVT_CATHERINE_LOCKS_HERSELF",
                    status="ill",
                    traits={
                        "self_division": TraitVector(value=1.0, inertia=0.7, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=10900, triggered_by="EVT_HEATHCLIFF_VISITS_DYING_CATHERINE",
                    traits={
                        "anguish": TraitVector(value=0.80, inertia=0.50, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=11000, triggered_by="EVT_CATHERINE_DIES",
                    status="dead", location_id="LOC_GIMMERTON_KIRK"),
                
            ],
        ),
        "ENT_HINDLEY": Entity(
            id="ENT_HINDLEY", name="Hindley Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "jealousy": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
                "brutality": TraitVector(value=0.6, inertia=0.55, evidence_strength="moderate"),
                "addiction_to_drink": TraitVector(value=0.2, inertia=0.4, evidence_strength="weak"),
                "self_pity": TraitVector(value=0.5, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF",
                       perceived_state="The gipsy brat has stolen my father's love",
                       confidence=0.95, inertia=0.75, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_EARNSHAW_BRINGS_HEATHCLIFF",
                    traits={
                        "jealousy": TraitVector(value=1.00, inertia=0.60, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=3500, triggered_by="EVT_OLD_EARNSHAW_DIES",
                    traits={
                        "brutality": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=3500, triggered_by="EVT_OLD_EARNSHAW_DIES",
                    traits={
                        "tyranny": TraitVector(value=0.60, inertia=0.50, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=5500, triggered_by="EVT_FRANCES_DIES",
                    traits={
                        "addiction_to_drink": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                        "self_pity": TraitVector(value=0.9, inertia=0.65, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=9900, triggered_by="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE",
                    traits={
                        "despair": TraitVector(value=0.60, inertia=0.50, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=12000, triggered_by="EVT_HINDLEY_DIES",
                    status="dead"),
                
            ],
        ),
        "ENT_EDGAR": Entity(
            id="ENT_EDGAR", name="Edgar Linton",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "gentility": TraitVector(value=0.9, inertia=0.75, evidence_strength="strong"),
                "tenderness": TraitVector(value=0.8, inertia=0.65, evidence_strength="strong"),
                "weakness": TraitVector(value=0.55, inertia=0.5, evidence_strength="moderate"),
                "devotion": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=8000, triggered_by="EVT_LINTON_PARENTS_DIE",
                    traits={
                        "grief": TraitVector(value=0.60, inertia=0.50, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=11000, triggered_by="EVT_CATHERINE_DIES",
                    traits={
                        "devotion": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=15000, triggered_by="EVT_EDGAR_DIES",
                    status="dead"),
                
            ],
        ),
        "ENT_ISABELLA": Entity(
            id="ENT_ISABELLA", name="Isabella Linton",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "naivety": TraitVector(value=0.85, inertia=0.55, evidence_strength="strong"),
                "infatuation": TraitVector(value=0.4, inertia=0.4, evidence_strength="moderate"),
                "endurance": TraitVector(value=0.4, inertia=0.45, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF",
                       perceived_state="Heathcliff is a darkly romantic hero",
                       confidence=0.7, inertia=0.4, established_at_fabula=9000, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=8000, triggered_by="EVT_LINTON_PARENTS_DIE",
                    traits={
                        "grief": TraitVector(value=0.60, inertia=0.50, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=10000, triggered_by="EVT_ISABELLA_ELOPES",
                    location_id="LOC_WUTHERING_HEIGHTS",
                    traits={
                        "infatuation": TraitVector(value=0.9, inertia=0.5, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=11500, triggered_by="EVT_ISABELLA_FLEES_SOUTH",
                    location_id=None,
                    beliefs_invalidated=["ENT_HEATHCLIFF"],
                    beliefs_added=[
                        Belief(target_id="ENT_HEATHCLIFF",
                               perceived_state="Heathcliff is a fiend who can never love anything but Catherine",
                               confidence=0.95, inertia=0.7, established_at_fabula=11500, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=14000, triggered_by="EVT_ISABELLA_DIES",
                    status="dead"),
                
            ],
        ),
        "ENT_NELLY": Entity(
            id="ENT_NELLY", name="Ellen 'Nelly' Dean",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.7, inertia=0.6, evidence_strength="strong"),
                "judgement": TraitVector(value=0.7, inertia=0.6, evidence_strength="strong"),
                "interventionism": TraitVector(value=0.6, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=9500, triggered_by="EVT_CATHERINE_MARRIES_EDGAR",
                    location_id="LOC_THRUSHCROSS_GRANGE"),
                EntityStateSnapshot(fabula_time=19000, triggered_by="EVT_HEATHCLIFF_STOPS_EATING",
                    location_id="LOC_WUTHERING_HEIGHTS"),
            ],
        ),
        "ENT_OLD_EARNSHAW": Entity(
            id="ENT_OLD_EARNSHAW", name="Mr Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "stubbornness": TraitVector(value=0.7, inertia=0.7, evidence_strength="moderate"),
                "favouritism": TraitVector(value=0.7, inertia=0.65, evidence_strength="strong"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=3500, triggered_by="EVT_OLD_EARNSHAW_DIES",
                    status="dead"),
            ],
        ),
        "ENT_FRANCES": Entity(
            id="ENT_FRANCES", name="Frances Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "cheerfulness": TraitVector(value=0.7, inertia=0.5, evidence_strength="moderate"),
                "frailty": TraitVector(value=0.5, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=5500, triggered_by="EVT_FRANCES_DIES",
                    status="dead"),
            ],
        ),
        "ENT_HARETON": Entity(
            id="ENT_HARETON", name="Hareton Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "neglected_dignity": TraitVector(value=0.7, inertia=0.55, evidence_strength="strong"),
                "loyalty": TraitVector(value=0.7, inertia=0.55, evidence_strength="moderate"),
                "shame": TraitVector(value=0.6, inertia=0.45, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF",
                       perceived_state="Heathcliff is the only father I have known",
                       confidence=0.7, inertia=0.55, established_at_fabula=13000, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=12000, triggered_by="EVT_HINDLEY_DIES",
                    traits={
                        "loyalty": TraitVector(value=0.90, inertia=0.55, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=18500, triggered_by="EVT_CATHY_TEACHES_HARETON",
                    traits={
                        "shame": TraitVector(value=0.15, inertia=0.55, evidence_strength="strong"),
                        "neglected_dignity": TraitVector(value=0.3, inertia=0.65, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=19500, triggered_by="EVT_HEATHCLIFF_DIES",
                    traits={
                        "loyalty": TraitVector(value=0.90, inertia=0.55, evidence_strength="moderate"),
                    }),
            ],
        ),
        "ENT_LINTON": Entity(
            id="ENT_LINTON", name="Linton Heathcliff",
            location_id="LOC_THRUSHCROSS_GRANGE", status="ill",
            traits={
                "frailty": TraitVector(value=0.95, inertia=0.65, evidence_strength="strong"),
                "petulance": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                "fear": TraitVector(value=0.7, inertia=0.4, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF",
                       perceived_state="My father will harm me if I disobey",
                       confidence=0.95, inertia=0.55, established_at_fabula=15000, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=14000, triggered_by="EVT_ISABELLA_DIES",
                    traits={
                        "fear": TraitVector(value=1.00, inertia=0.40, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=15000, triggered_by="EVT_LINTON_TAKEN_BY_FATHER",
                    location_id="LOC_WUTHERING_HEIGHTS"),
                EntityStateSnapshot(fabula_time=17000, triggered_by="EVT_LINTON_DIES",
                    status="dead"),
                
            ],
        ),
        "ENT_CATHY": Entity(
            id="ENT_CATHY", name="Cathy Linton",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "courage": TraitVector(value=0.75, inertia=0.55, evidence_strength="strong"),
                "warmth": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                "stubbornness": TraitVector(value=0.7, inertia=0.55, evidence_strength="strong"),
                "resilience": TraitVector(value=0.7, inertia=0.55, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=15000, triggered_by="EVT_EDGAR_DIES",
                    traits={
                        "resilience": TraitVector(value=0.90, inertia=0.55, evidence_strength="moderate"),
                    }),
                EntityStateSnapshot(fabula_time=16000, triggered_by="EVT_CATHY_FORCED_MARRIAGE",
                    location_id="LOC_WUTHERING_HEIGHTS",
                    traits={
                        "courage": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=17000, triggered_by="EVT_LINTON_DIES",
                    traits={
                        "warmth": TraitVector(value=0.65, inertia=0.60, evidence_strength="moderate"),
                    }),EntityStateSnapshot(fabula_time=18500, triggered_by="EVT_CATHY_TEACHES_HARETON",
                    traits={
                        "warmth": TraitVector(value=0.95, inertia=0.65, evidence_strength="strong"),
                    }),
                
            ],
        ),
        "ENT_LOCKWOOD": Entity(
            id="ENT_LOCKWOOD", name="Mr Lockwood",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "curiosity": TraitVector(value=0.8, inertia=0.5, evidence_strength="strong"),
                "obtuseness": TraitVector(value=0.6, inertia=0.55, evidence_strength="moderate"),
            },
            beliefs=[],
        ),
    },

    # ── EVENTS ──────────────────────────────────────────────────────────
    events=[
        EventNode(id="EVT_EARNSHAW_BRINGS_HEATHCLIFF", fabula_time=1000, syuzhet_index=2,
                  event_type="choice", actor_ids=["ENT_OLD_EARNSHAW"], target_ids=["ENT_HEATHCLIFF"],
                  description="Mr Earnshaw returns from a Liverpool trip with the orphan Heathcliff and brings him to live at Wuthering Heights as a favoured ward."),
        EventNode(id="EVT_HEATHCLIFF_AND_CATHERINE_BOND", fabula_time=2000, syuzhet_index=3,
                  event_type="outcome", actor_ids=["ENT_HEATHCLIFF", "ENT_CATHERINE"], target_ids=[],
                  description="Heathcliff and Catherine become inseparable companions, roaming the moors together."),
        EventNode(id="EVT_OLD_EARNSHAW_DIES", fabula_time=3500, syuzhet_index=4,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_OLD_EARNSHAW"],
                  description="Mr Earnshaw dies; Hindley returns from university with his wife Frances to take over Wuthering Heights."),
        EventNode(id="EVT_HINDLEY_DEMOTES_HEATHCLIFF", fabula_time=4000, syuzhet_index=5,
                  event_type="choice", actor_ids=["ENT_HINDLEY"], target_ids=["ENT_HEATHCLIFF"],
                  description="Hindley reduces Heathcliff to the status of a farm servant, beats him, and forbids his lessons."),
        EventNode(id="EVT_FRANCES_DIES", fabula_time=5500, syuzhet_index=6,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_FRANCES"],
                  description="Frances dies after giving birth to Hareton; Hindley descends into alcoholism."),
        EventNode(id="EVT_CATHERINE_AT_LINTONS", fabula_time=6000, syuzhet_index=7,
                  event_type="outcome", actor_ids=["ENT_CATHERINE"], target_ids=[],
                  description="Catherine, attacked by the Lintons' dog while spying with Heathcliff, stays five weeks at Thrushcross Grange and returns transformed into a young lady."),
        EventNode(id="EVT_HEATHCLIFF_OVERHEARS", fabula_time=7000, syuzhet_index=8,
                  event_type="revelation", actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Heathcliff overhears Catherine tell Nelly it would degrade her to marry him, but leaves before hearing her declaration that she IS Heathcliff."),
        EventNode(id="EVT_HEATHCLIFF_FLEES", fabula_time=7500, syuzhet_index=9,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Heathcliff disappears from Wuthering Heights; Catherine falls dangerously ill."),
        EventNode(id="EVT_LINTON_PARENTS_DIE", fabula_time=8000, syuzhet_index=10,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_EDGAR"],
                  description="Mr and Mrs Linton die of the fever they caught nursing Catherine; Edgar inherits Thrushcross Grange under an entail favouring his male heir or Isabella's heir."),
        EventNode(id="EVT_CATHERINE_MARRIES_EDGAR", fabula_time=9500, syuzhet_index=11,
                  event_type="choice", actor_ids=["ENT_CATHERINE", "ENT_EDGAR"], target_ids=[],
                  description="Catherine marries Edgar Linton and becomes mistress of Thrushcross Grange."),
        EventNode(id="EVT_HEATHCLIFF_RETURNS", fabula_time=9700, syuzhet_index=12,
                  event_type="outcome", actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Three years after fleeing, Heathcliff returns mysteriously wealthy and re-enters the lives of the Earnshaws and Lintons."),
        EventNode(id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE", fabula_time=9900, syuzhet_index=13,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=["ENT_HINDLEY"],
                  description="Heathcliff exploits Hindley's gambling addiction to become mortgagee of Wuthering Heights."),
        EventNode(id="EVT_ISABELLA_ELOPES", fabula_time=10000, syuzhet_index=14,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF", "ENT_ISABELLA"], target_ids=[],
                  description="Heathcliff cynically elopes with the infatuated Isabella to spite Edgar."),
        EventNode(id="EVT_CATHERINE_LOCKS_HERSELF", fabula_time=10500, syuzhet_index=15,
                  event_type="choice", actor_ids=["ENT_CATHERINE"], target_ids=[],
                  description="Caught between Edgar and Heathcliff, Catherine locks herself in her room and refuses food for three days."),
        EventNode(id="EVT_HEATHCLIFF_VISITS_DYING_CATHERINE", fabula_time=10900, syuzhet_index=16,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=["ENT_CATHERINE"],
                  description="Heathcliff steals to Catherine's bedside; they accuse and embrace each other in a final scene."),
        EventNode(id="EVT_CATHERINE_DIES", fabula_time=11000, syuzhet_index=17,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_CATHERINE"],
                  description="Catherine dies after giving birth to a daughter, Cathy."),
        EventNode(id="EVT_ISABELLA_FLEES_SOUTH", fabula_time=11500, syuzhet_index=18,
                  event_type="choice", actor_ids=["ENT_ISABELLA"], target_ids=[],
                  description="Isabella, abused and disillusioned, flees Heathcliff's house and goes south to bear his sickly son Linton."),
        EventNode(id="EVT_HINDLEY_DIES", fabula_time=12000, syuzhet_index=19,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_HINDLEY"],
                  description="Hindley dies of alcoholism six months after Catherine; Heathcliff takes possession of Wuthering Heights and Hareton with it."),
        EventNode(id="EVT_HEATHCLIFF_OPENS_GRAVE", fabula_time=13000, syuzhet_index=20,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Heathcliff bribes the sexton to open Catherine's grave for the first time."),
        EventNode(id="EVT_ISABELLA_DIES", fabula_time=14000, syuzhet_index=21,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_ISABELLA"],
                  description="Isabella dies in the south; her son Linton is brought north."),
        EventNode(id="EVT_LINTON_TAKEN_BY_FATHER", fabula_time=15000, syuzhet_index=22,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=["ENT_LINTON"],
                  description="Heathcliff insists his son Linton be brought to Wuthering Heights, despite Edgar's claim and the boy's frailty."),
        EventNode(id="EVT_EDGAR_DIES", fabula_time=15000, syuzhet_index=23,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_EDGAR"],
                  description="Edgar Linton dies; under the entail Thrushcross Grange will pass through his son-in-law Linton."),
        EventNode(id="EVT_CATHY_FORCED_MARRIAGE", fabula_time=16000, syuzhet_index=24,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=["ENT_CATHY", "ENT_LINTON"],
                  description="Heathcliff manoeuvres Cathy into marrying his dying son Linton, securing the Grange."),
        EventNode(id="EVT_LINTON_DIES", fabula_time=17000, syuzhet_index=25,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_LINTON"],
                  description="Linton dies, leaving Cathy a teenage widow trapped at Wuthering Heights with the now-master Heathcliff."),
        EventNode(id="EVT_LOCKWOOD_DREAMS", fabula_time=18000, syuzhet_index=1,
                  event_type="revelation", actor_ids=["ENT_LOCKWOOD"], target_ids=["ENT_HEATHCLIFF"],
                  description="Snowbound at Wuthering Heights, Lockwood dreams of Catherine's ghost begging entry; his cries shatter Heathcliff."),
        EventNode(id="EVT_HEATHCLIFF_OPENS_GRAVE_AGAIN", fabula_time=18500, syuzhet_index=26,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Heathcliff opens Catherine's grave a second time and arranges for his own coffin to lie touching hers."),
        EventNode(id="EVT_CATHY_TEACHES_HARETON", fabula_time=18500, syuzhet_index=27,
                  event_type="choice", actor_ids=["ENT_CATHY"], target_ids=["ENT_HARETON"],
                  description="Cathy reconciles with Hareton and begins teaching him to read; the two fall in love."),
        EventNode(id="EVT_HEATHCLIFF_STOPS_EATING", fabula_time=19000, syuzhet_index=28,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Increasingly haunted by visions of Catherine, Heathcliff stops eating and avoids the young couple."),
        EventNode(id="EVT_HEATHCLIFF_DIES", fabula_time=19500, syuzhet_index=29,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_HEATHCLIFF"],
                  description="Heathcliff is found dead in Catherine's old room with his eyes open; Hareton mourns him."),
        EventNode(id="EVT_CATHY_HARETON_INHERIT", fabula_time=20000, syuzhet_index=30,
                  event_type="outcome", actor_ids=["ENT_CATHY", "ENT_HARETON"], target_ids=[],
                  description="Hareton reclaims Wuthering Heights and Cathy regains the Grange; they plan to marry on New Year's Day."),

        # ── UTTERANCES (discrete on-page speech-acts) ──────────────────
        EventNode(
            id="EVT_UTT_CATHERINE_CONFESSES_TO_NELLY",
            event_type="utterance", fabula_time=7000, syuzhet_index=31,
            speaker_id="ENT_CATHERINE", addressee_ids=["ENT_NELLY"],
            actor_ids=["ENT_CATHERINE"], target_ids=["ENT_HEATHCLIFF", "ENT_EDGAR"],
            description="Catherine confesses to Nelly that marrying Heathcliff would degrade her, but that she IS Heathcliff in her soul; Heathcliff overhears only the first half.",
            content="It would degrade me to marry Heathcliff now... but he's more myself than I am — whatever our souls are made of, his and mine are the same.",
            via_channel_id=None, truth_value="true",
        ),
        EventNode(
            id="EVT_UTT_ISABELLA_LETTER_TO_NELLY",
            event_type="utterance", fabula_time=11500, syuzhet_index=32,
            speaker_id="ENT_ISABELLA", addressee_ids=["ENT_NELLY"],
            actor_ids=["ENT_ISABELLA"], target_ids=["ENT_HEATHCLIFF"],
            description="Isabella writes to Nelly from the south describing Heathcliff's cruelty and asking whether he is even human.",
            content="Is Mr Heathcliff a man? If so, is he mad? And if not, is he a devil? I cannot live with him as a wife.",
            via_channel_id="CHN_ISABELLA_NELLY_LETTERS", truth_value="true",
        ),
        EventNode(
            id="EVT_UTT_HEATHCLIFF_COERCES_LINTON",
            event_type="utterance", fabula_time=15000, syuzhet_index=33,
            speaker_id="ENT_HEATHCLIFF", addressee_ids=["ENT_LINTON"],
            actor_ids=["ENT_HEATHCLIFF"], target_ids=["ENT_LINTON", "ENT_CATHY"],
            description="Heathcliff orders the sickly Linton to court Cathy and lure her to the Heights, threatening violence if he refuses.",
            content="Win her — or I will make your life a torment until your last breath.",
            via_channel_id=None, truth_value="performative",
        ),
        EventNode(
            id="EVT_UTT_LINTON_COERCED_LETTERS_TO_CATHY",
            event_type="utterance", fabula_time=15800, syuzhet_index=34,
            speaker_id="ENT_LINTON", addressee_ids=["ENT_CATHY"],
            actor_ids=["ENT_LINTON", "ENT_HEATHCLIFF"], target_ids=["ENT_CATHY"],
            description="Linton, dictated to and supervised by Heathcliff, sends Cathy a stream of love letters feigning ardour to draw her into the marriage scheme.",
            content="My dearest Catherine, I am wasting for want of you — come to me at the Heights and save my life.",
            via_channel_id="CHN_LINTON_CATHY_COERCED_LETTERS", truth_value="false",
        ),
        EventNode(
            id="EVT_UTT_LOCKWOOD_READS_DIARY",
            event_type="utterance", fabula_time=18000, syuzhet_index=35,
            speaker_id="OBJ_CATHERINES_DIARY", addressee_ids=["ENT_LOCKWOOD"],
            actor_ids=["ENT_LOCKWOOD", "OBJ_CATHERINES_DIARY"], target_ids=["ENT_CATHERINE", "ENT_HINDLEY", "ENT_HEATHCLIFF"],
            description="Snowed in at the Heights, Lockwood reads Catherine's childhood diary entries chronicling Hindley's tyranny and her bond with Heathcliff.",
            content="H. and I are going to rebel — we took our initiatory step this evening... an awful Sunday!",
            via_channel_id="CHN_CATHERINES_DIARY", truth_value="true",
        ),
        EventNode(
            id="EVT_UTT_NELLY_NARRATES_TO_LOCKWOOD",
            event_type="utterance", fabula_time=18100, syuzhet_index=36,
            speaker_id="ENT_NELLY", addressee_ids=["ENT_LOCKWOOD"],
            actor_ids=["ENT_NELLY"],
            target_ids=[
                "EVT_EARNSHAW_BRINGS_HEATHCLIFF", "EVT_HINDLEY_DEMOTES_HEATHCLIFF",
                "EVT_HEATHCLIFF_OVERHEARS", "EVT_HEATHCLIFF_FLEES",
                "EVT_CATHERINE_MARRIES_EDGAR", "EVT_HEATHCLIFF_RETURNS",
                "EVT_CATHERINE_DIES", "EVT_CATHY_FORCED_MARRIAGE",
            ],
            description="Convalescing Lockwood begs Nelly for the household's history; over many evenings she narrates the entire Earnshaw–Linton–Heathcliff saga.",
            content="Before I came to live here, she commenced — waiting no farther invitation to her story...",
            via_channel_id="CHN_NELLY_ORAL_HISTORY", truth_value="true",
        ),
    ],

    # ── CAUSAL TOPOLOGY ────────────────────────────────────────────────
    causal_topology=[
        # ── chain_reaction ──
        CausalEdge(source_id="EVT_EARNSHAW_BRINGS_HEATHCLIFF", target_id="EVT_HEATHCLIFF_AND_CATHERINE_BOND",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1000, propagation_delay=1000),
        CausalEdge(source_id="EVT_OLD_EARNSHAW_DIES", target_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=3500, propagation_delay=500),
        CausalEdge(source_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF", target_id="EVT_HEATHCLIFF_OVERHEARS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=4000, propagation_delay=3000),
        CausalEdge(source_id="EVT_CATHERINE_AT_LINTONS", target_id="EVT_HEATHCLIFF_OVERHEARS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=6000, propagation_delay=1000),
        CausalEdge(source_id="EVT_FRANCES_DIES", target_id="EVT_HINDLEY_DIES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=5500, propagation_delay=6500),
        CausalEdge(source_id="EVT_HEATHCLIFF_OVERHEARS", target_id="EVT_HEATHCLIFF_FLEES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=7000, propagation_delay=500),
        CausalEdge(source_id="EVT_HEATHCLIFF_FLEES", target_id="EVT_CATHERINE_MARRIES_EDGAR",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7500, propagation_delay=2000),
        CausalEdge(source_id="EVT_LINTON_PARENTS_DIE", target_id="EVT_CATHERINE_MARRIES_EDGAR",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=8000, propagation_delay=1500),
        CausalEdge(source_id="EVT_HEATHCLIFF_RETURNS", target_id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=9700, propagation_delay=200),
        CausalEdge(source_id="EVT_HEATHCLIFF_RETURNS", target_id="EVT_ISABELLA_ELOPES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=9700, propagation_delay=300),
        CausalEdge(source_id="EVT_HEATHCLIFF_RETURNS", target_id="EVT_CATHERINE_LOCKS_HERSELF",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=9700, propagation_delay=800),
        CausalEdge(source_id="EVT_CATHERINE_LOCKS_HERSELF", target_id="EVT_HEATHCLIFF_VISITS_DYING_CATHERINE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=10500, propagation_delay=400),
        CausalEdge(source_id="EVT_HEATHCLIFF_VISITS_DYING_CATHERINE", target_id="EVT_CATHERINE_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=10900, propagation_delay=100),
        CausalEdge(source_id="EVT_ISABELLA_ELOPES", target_id="EVT_ISABELLA_FLEES_SOUTH",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=10000, propagation_delay=1500),
        CausalEdge(source_id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE", target_id="EVT_HINDLEY_DIES",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=9900, propagation_delay=2100),
        CausalEdge(source_id="EVT_CATHERINE_DIES", target_id="EVT_HEATHCLIFF_OPENS_GRAVE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=11000, propagation_delay=2000),
        CausalEdge(source_id="EVT_ISABELLA_FLEES_SOUTH", target_id="EVT_ISABELLA_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=11500, propagation_delay=2500),
        CausalEdge(source_id="EVT_ISABELLA_DIES", target_id="EVT_LINTON_TAKEN_BY_FATHER",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=14000, propagation_delay=1000),
        CausalEdge(source_id="EVT_LINTON_TAKEN_BY_FATHER", target_id="EVT_CATHY_FORCED_MARRIAGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=15000, propagation_delay=1000),
        CausalEdge(source_id="EVT_EDGAR_DIES", target_id="EVT_CATHY_FORCED_MARRIAGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=15000, propagation_delay=1000),
        CausalEdge(source_id="EVT_CATHY_FORCED_MARRIAGE", target_id="EVT_LINTON_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=16000, propagation_delay=1000),
        CausalEdge(source_id="EVT_LOCKWOOD_DREAMS", target_id="EVT_HEATHCLIFF_OPENS_GRAVE_AGAIN",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=18000, propagation_delay=500),
        CausalEdge(source_id="EVT_HEATHCLIFF_OPENS_GRAVE_AGAIN", target_id="EVT_HEATHCLIFF_STOPS_EATING",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=18500, propagation_delay=500),
        CausalEdge(source_id="EVT_LINTON_DIES", target_id="EVT_CATHY_TEACHES_HARETON",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=17000, propagation_delay=1500),
        CausalEdge(source_id="EVT_CATHY_TEACHES_HARETON", target_id="EVT_HEATHCLIFF_STOPS_EATING",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=18500, propagation_delay=500),
        CausalEdge(source_id="EVT_HEATHCLIFF_STOPS_EATING", target_id="EVT_HEATHCLIFF_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=19000, propagation_delay=500),
        CausalEdge(source_id="EVT_HEATHCLIFF_DIES", target_id="EVT_CATHY_HARETON_INHERIT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=19500, propagation_delay=500),

        # ── mutation ──
        CausalEdge(source_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=4000,
                   trait_target="vengefulness", trait_delta=0.4),
        CausalEdge(source_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=4000,
                   trait_target="endurance", trait_delta=0.05),
        CausalEdge(source_id="EVT_CATHERINE_AT_LINTONS", target_id="ENT_CATHERINE",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=6000,
                   trait_target="vanity", trait_delta=0.15),
        CausalEdge(source_id="EVT_CATHERINE_AT_LINTONS", target_id="ENT_CATHERINE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=6000,
                   trait_target="self_division", trait_delta=0.4),
        CausalEdge(source_id="EVT_HEATHCLIFF_OVERHEARS", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=7000,
                   trait_target="despair", trait_delta=0.75),
        CausalEdge(source_id="EVT_HEATHCLIFF_OVERHEARS", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=7000,
                   trait_target="vengefulness", trait_delta=0.55),
        CausalEdge(source_id="EVT_HEATHCLIFF_RETURNS", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=9700,
                   trait_target="cruelty", trait_delta=0.5),
        CausalEdge(source_id="EVT_FRANCES_DIES", target_id="ENT_HINDLEY",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=5500,
                   trait_target="addiction_to_drink", trait_delta=0.65),
        CausalEdge(source_id="EVT_CATHERINE_DIES", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=11000,
                   trait_target="grief", trait_delta=0.9),
        CausalEdge(source_id="EVT_CATHERINE_DIES", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=11000,
                   trait_target="despair", trait_delta=0.85),
        CausalEdge(source_id="EVT_ISABELLA_ELOPES", target_id="ENT_ISABELLA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=10000,
                   trait_target="infatuation", trait_delta=0.5),
        CausalEdge(source_id="EVT_ISABELLA_FLEES_SOUTH", target_id="ENT_ISABELLA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=11500,
                   trait_target="endurance", trait_delta=0.3),
        CausalEdge(source_id="EVT_HEATHCLIFF_OPENS_GRAVE_AGAIN", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=18500,
                   trait_target="vengefulness", trait_delta=-0.6),
        CausalEdge(source_id="EVT_CATHY_TEACHES_HARETON", target_id="ENT_HARETON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=18500,
                   trait_target="shame", trait_delta=-0.45),
        CausalEdge(source_id="EVT_CATHY_TEACHES_HARETON", target_id="ENT_HARETON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=18500,
                   trait_target="neglected_dignity", trait_delta=-0.4),
        # — Coverage mutations for previously un-mutated significant events —
        CausalEdge(source_id="EVT_EARNSHAW_BRINGS_HEATHCLIFF", target_id="ENT_HINDLEY",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1000,
                   trait_target="jealousy", trait_delta=0.3),
        CausalEdge(source_id="EVT_EARNSHAW_BRINGS_HEATHCLIFF", target_id="ENT_CATHERINE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1000,
                   trait_target="bond", trait_delta=0.5),
        CausalEdge(source_id="EVT_OLD_EARNSHAW_DIES", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=3500,
                   trait_target="vulnerability", trait_delta=0.5),
        CausalEdge(source_id="EVT_OLD_EARNSHAW_DIES", target_id="ENT_HINDLEY",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=3500,
                   trait_target="tyranny", trait_delta=0.6),
        CausalEdge(source_id="EVT_LINTON_PARENTS_DIE", target_id="ENT_EDGAR",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=8000,
                   trait_target="grief", trait_delta=0.6),
        CausalEdge(source_id="EVT_LINTON_PARENTS_DIE", target_id="ENT_ISABELLA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=8000,
                   trait_target="grief", trait_delta=0.6),
        CausalEdge(source_id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE", target_id="ENT_HINDLEY",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=9900,
                   trait_target="despair", trait_delta=0.6),
        CausalEdge(source_id="EVT_HEATHCLIFF_VISITS_DYING_CATHERINE", target_id="ENT_CATHERINE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=10900,
                   trait_target="anguish", trait_delta=0.8),
        CausalEdge(source_id="EVT_HINDLEY_DIES", target_id="ENT_HARETON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=12000,
                   trait_target="loyalty", trait_delta=0.2),
        CausalEdge(source_id="EVT_ISABELLA_DIES", target_id="ENT_LINTON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=14000,
                   trait_target="fear", trait_delta=0.3),
        CausalEdge(source_id="EVT_LINTON_TAKEN_BY_FATHER", target_id="ENT_LINTON",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=15000,
                   trait_target="fear", trait_delta=0.5),
        CausalEdge(source_id="EVT_EDGAR_DIES", target_id="ENT_CATHY",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=15000,
                   trait_target="resilience", trait_delta=0.2),
        CausalEdge(source_id="EVT_LINTON_DIES", target_id="ENT_CATHY",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=17000,
                   trait_target="warmth", trait_delta=-0.2),
        CausalEdge(source_id="EVT_HEATHCLIFF_DIES", target_id="ENT_HARETON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=19500,
                   trait_target="loyalty", trait_delta=0.2),

        # ── mutation_social ──
        CausalEdge(source_id="EVT_HEATHCLIFF_AND_CATHERINE_BOND", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=2000,
                   trait_target="affinity", trait_delta=1.0, rel_counterpart_id="ENT_CATHERINE"),
        CausalEdge(source_id="EVT_HEATHCLIFF_AND_CATHERINE_BOND", target_id="ENT_CATHERINE",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=2000,
                   trait_target="affinity", trait_delta=1.0, rel_counterpart_id="ENT_HEATHCLIFF"),
        CausalEdge(source_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=8.0, fabula_time=4000,
                   trait_target="affinity", trait_delta=-0.95, rel_counterpart_id="ENT_HINDLEY"),
        CausalEdge(source_id="EVT_CATHERINE_MARRIES_EDGAR", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=9500,
                   trait_target="affinity", trait_delta=-0.4, rel_counterpart_id="ENT_EDGAR"),
        CausalEdge(source_id="EVT_ISABELLA_ELOPES", target_id="ENT_ISABELLA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=10000,
                   trait_target="affinity", trait_delta=0.6, rel_counterpart_id="ENT_HEATHCLIFF"),
        CausalEdge(source_id="EVT_ISABELLA_FLEES_SOUTH", target_id="ENT_ISABELLA",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=10.0, fabula_time=11500,
                   trait_target="affinity", trait_delta=-1.0, rel_counterpart_id="ENT_HEATHCLIFF"),
        CausalEdge(source_id="EVT_CATHY_FORCED_MARRIAGE", target_id="ENT_CATHY",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=16000,
                   trait_target="fear", trait_delta=0.7, rel_counterpart_id="ENT_HEATHCLIFF"),
        CausalEdge(source_id="EVT_CATHY_TEACHES_HARETON", target_id="ENT_CATHY",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=18500,
                   trait_target="affinity", trait_delta=0.85, rel_counterpart_id="ENT_HARETON"),
        CausalEdge(source_id="EVT_CATHY_TEACHES_HARETON", target_id="ENT_HARETON",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=18500,
                   trait_target="affinity", trait_delta=0.85, rel_counterpart_id="ENT_CATHY"),

        # ── affordance_gate ──
        CausalEdge(source_id="OBJ_CATHERINES_DIARY", target_id="EVT_LOCKWOOD_DREAMS",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="strong",
                   causal_force=7.0, fabula_time=18000),
        CausalEdge(source_id="OBJ_HEIGHTS_MORTGAGE", target_id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=9900),
        CausalEdge(source_id="OBJ_GRANGE_DEED", target_id="EVT_CATHY_FORCED_MARRIAGE",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=16000),
        CausalEdge(source_id="OBJ_CATHERINES_GRAVE", target_id="EVT_HEATHCLIFF_OPENS_GRAVE",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=13000),
        CausalEdge(source_id="ENT_NELLY", target_id="EVT_HEATHCLIFF_OVERHEARS",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=7000),

        # ── ambient_propagation ──
        CausalEdge(source_id="LOC_WUTHERING_HEIGHTS", target_id="ENT_HEATHCLIFF",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=4000),
        CausalEdge(source_id="LOC_THRUSHCROSS_GRANGE", target_id="ENT_CATHERINE",
                   causality_type="ambient_propagation", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=6000),
        CausalEdge(source_id="LOC_MOORS", target_id="ENT_HEATHCLIFF",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=2000),

        # ── WORLD_ → Event ──
        CausalEdge(source_id="WORLD_CLASS_HIERARCHY", target_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=4000),
        CausalEdge(source_id="WORLD_CLASS_HIERARCHY", target_id="EVT_HEATHCLIFF_OVERHEARS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=7000),
        CausalEdge(source_id="WORLD_CLASS_HIERARCHY", target_id="EVT_CATHERINE_MARRIES_EDGAR",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=9500),
        CausalEdge(source_id="WORLD_CLASS_HIERARCHY", target_id="EVT_CATHERINE_AT_LINTONS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=6000),
        CausalEdge(source_id="WORLD_PRIMOGENITURE_ENTAIL", target_id="EVT_LINTON_TAKEN_BY_FATHER",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=15000),
        CausalEdge(source_id="WORLD_PRIMOGENITURE_ENTAIL", target_id="EVT_CATHY_FORCED_MARRIAGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=16000),
        CausalEdge(source_id="WORLD_PRIMOGENITURE_ENTAIL", target_id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=9900),
        CausalEdge(source_id="WORLD_PRIMOGENITURE_ENTAIL", target_id="EVT_CATHY_HARETON_INHERIT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=20000),
        CausalEdge(source_id="WORLD_HAUNTED_MOORS", target_id="EVT_LOCKWOOD_DREAMS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=18000),
        CausalEdge(source_id="WORLD_HAUNTED_MOORS", target_id="EVT_HEATHCLIFF_OPENS_GRAVE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=13000),
        CausalEdge(source_id="WORLD_HAUNTED_MOORS", target_id="EVT_HEATHCLIFF_STOPS_EATING",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=5.0, fabula_time=19000),

        # ── orphan utterance wirings ──
        CausalEdge(source_id="EVT_UTT_CATHERINE_CONFESSES_TO_NELLY", target_id="EVT_HEATHCLIFF_OVERHEARS",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=10.0, fabula_time=7000, propagation_delay=0),
        CausalEdge(source_id="EVT_ISABELLA_FLEES_SOUTH", target_id="EVT_UTT_ISABELLA_LETTER_TO_NELLY",
                   causality_type="chain_reaction", mechanism="informational", evidence_strength="strong",
                   causal_force=4.0, fabula_time=11500, propagation_delay=0),
        CausalEdge(source_id="EVT_LINTON_TAKEN_BY_FATHER", target_id="EVT_UTT_HEATHCLIFF_COERCES_LINTON",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=15000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_HEATHCLIFF_COERCES_LINTON", target_id="EVT_UTT_LINTON_COERCED_LETTERS_TO_CATHY",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=15000, propagation_delay=800),
        CausalEdge(source_id="EVT_UTT_LINTON_COERCED_LETTERS_TO_CATHY", target_id="EVT_CATHY_FORCED_MARRIAGE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=15800, propagation_delay=200),
        CausalEdge(source_id="EVT_UTT_LOCKWOOD_READS_DIARY", target_id="EVT_LOCKWOOD_DREAMS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=5.0, fabula_time=18000, propagation_delay=0),
        CausalEdge(source_id="EVT_LOCKWOOD_DREAMS", target_id="EVT_UTT_NELLY_NARRATES_TO_LOCKWOOD",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=4.0, fabula_time=18000, propagation_delay=100),

        # ─── auto-patched mutation_social edges (per-axis coverage) ───
        CausalEdge(source_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF", target_id="ENT_HINDLEY", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="affinity", trait_delta=-0.95, mechanism="betrayal", evidence_strength="strong", causal_force=8.0, fabula_time=4000, propagation_delay=0),
        CausalEdge(source_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF", target_id="ENT_HINDLEY", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="power_dynamic", trait_delta=0.7, mechanism="social", evidence_strength="strong", causal_force=8.0, fabula_time=4000, propagation_delay=0),
        CausalEdge(source_id="EVT_CATHERINE_MARRIES_EDGAR", target_id="ENT_CATHERINE", rel_counterpart_id="ENT_EDGAR", causality_type="mutation_social", trait_target="affinity", trait_delta=0.6, mechanism="emotional", evidence_strength="strong", causal_force=7.0, fabula_time=9500, propagation_delay=0),
        CausalEdge(source_id="EVT_CATHERINE_MARRIES_EDGAR", target_id="ENT_EDGAR", rel_counterpart_id="ENT_CATHERINE", causality_type="mutation_social", trait_target="affinity", trait_delta=0.8, mechanism="emotional", evidence_strength="strong", causal_force=7.0, fabula_time=9500, propagation_delay=0),
        CausalEdge(source_id="EVT_CATHERINE_DIES", target_id="ENT_EDGAR", rel_counterpart_id="ENT_CATHERINE", causality_type="mutation_social", trait_target="affinity", trait_delta=0.15, mechanism="emotional", evidence_strength="strong", causal_force=9.0, fabula_time=11000, propagation_delay=0),
        CausalEdge(source_id="EVT_HEATHCLIFF_RETURNS", target_id="ENT_EDGAR", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="affinity", trait_delta=-0.7, mechanism="social", evidence_strength="strong", causal_force=7.0, fabula_time=9700, propagation_delay=0),
        CausalEdge(source_id="EVT_CATHERINE_LOCKS_HERSELF", target_id="ENT_EDGAR", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="affinity", trait_delta=-0.25, mechanism="emotional", evidence_strength="strong", causal_force=6.0, fabula_time=10500, propagation_delay=0),
        CausalEdge(source_id="EVT_HEATHCLIFF_RETURNS", target_id="ENT_EDGAR", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="fear", trait_delta=0.5, mechanism="psychological", evidence_strength="moderate", causal_force=6.0, fabula_time=9700, propagation_delay=0),
        CausalEdge(source_id="EVT_ISABELLA_ELOPES", target_id="ENT_HEATHCLIFF", rel_counterpart_id="ENT_ISABELLA", causality_type="mutation_social", trait_target="affinity", trait_delta=-0.4, mechanism="social", evidence_strength="strong", causal_force=6.0, fabula_time=10000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_ISABELLA_LETTER_TO_NELLY", target_id="ENT_HEATHCLIFF", rel_counterpart_id="ENT_ISABELLA", causality_type="mutation_social", trait_target="affinity", trait_delta=-0.45, mechanism="emotional", evidence_strength="strong", causal_force=7.0, fabula_time=11500, propagation_delay=0),
        CausalEdge(source_id="EVT_ISABELLA_ELOPES", target_id="ENT_HEATHCLIFF", rel_counterpart_id="ENT_ISABELLA", causality_type="mutation_social", trait_target="power_dynamic", trait_delta=0.85, mechanism="social", evidence_strength="strong", causal_force=7.0, fabula_time=10000, propagation_delay=0),
        CausalEdge(source_id="EVT_ISABELLA_ELOPES", target_id="ENT_ISABELLA", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="power_dynamic", trait_delta=-0.85, mechanism="social", evidence_strength="strong", causal_force=7.0, fabula_time=10000, propagation_delay=0),
        CausalEdge(source_id="EVT_ISABELLA_FLEES_SOUTH", target_id="ENT_ISABELLA", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="fear", trait_delta=0.95, mechanism="emotional", evidence_strength="strong", causal_force=9.0, fabula_time=11500, propagation_delay=0),
        CausalEdge(source_id="EVT_LINTON_TAKEN_BY_FATHER", target_id="ENT_HEATHCLIFF", rel_counterpart_id="ENT_LINTON", causality_type="mutation_social", trait_target="affinity", trait_delta=-0.3, mechanism="social", evidence_strength="strong", causal_force=6.0, fabula_time=15000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_HEATHCLIFF_COERCES_LINTON", target_id="ENT_HEATHCLIFF", rel_counterpart_id="ENT_LINTON", causality_type="mutation_social", trait_target="affinity", trait_delta=-0.2, mechanism="betrayal", evidence_strength="strong", causal_force=7.0, fabula_time=15000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_HEATHCLIFF_COERCES_LINTON", target_id="ENT_HEATHCLIFF", rel_counterpart_id="ENT_LINTON", causality_type="mutation_social", trait_target="power_dynamic", trait_delta=0.95, mechanism="social", evidence_strength="strong", causal_force=9.0, fabula_time=15000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_HEATHCLIFF_COERCES_LINTON", target_id="ENT_LINTON", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="fear", trait_delta=0.7, mechanism="psychological", evidence_strength="strong", causal_force=8.0, fabula_time=15000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_LINTON_COERCED_LETTERS_TO_CATHY", target_id="ENT_LINTON", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="fear", trait_delta=0.25, mechanism="psychological", evidence_strength="strong", causal_force=6.0, fabula_time=15800, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_HEATHCLIFF_COERCES_LINTON", target_id="ENT_LINTON", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="power_dynamic", trait_delta=-0.95, mechanism="social", evidence_strength="strong", causal_force=9.0, fabula_time=15000, propagation_delay=0),
        CausalEdge(source_id="EVT_CATHY_FORCED_MARRIAGE", target_id="ENT_CATHY", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="affinity", trait_delta=-0.85, mechanism="betrayal", evidence_strength="strong", causal_force=9.0, fabula_time=16000, propagation_delay=0),
        CausalEdge(source_id="EVT_LINTON_DIES", target_id="ENT_CATHY", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="fear", trait_delta=0.5, mechanism="psychological", evidence_strength="strong", causal_force=7.0, fabula_time=17000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_CATHERINE_CONFESSES_TO_NELLY", target_id="ENT_NELLY", rel_counterpart_id="ENT_CATHERINE", causality_type="mutation_social", trait_target="affinity", trait_delta=0.55, mechanism="emotional", evidence_strength="strong", causal_force=6.0, fabula_time=7000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_CATHERINE_CONFESSES_TO_NELLY", target_id="ENT_NELLY", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="affinity", trait_delta=-0.1, mechanism="psychological", evidence_strength="moderate", causal_force=4.0, fabula_time=7000, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_ISABELLA_LETTER_TO_NELLY", target_id="ENT_NELLY", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="affinity", trait_delta=-0.1, mechanism="informational", evidence_strength="moderate", causal_force=5.0, fabula_time=11500, propagation_delay=0),
        CausalEdge(source_id="EVT_HEATHCLIFF_RETURNS", target_id="ENT_NELLY", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="fear", trait_delta=0.35, mechanism="psychological", evidence_strength="moderate", causal_force=5.0, fabula_time=9700, propagation_delay=0),
        CausalEdge(source_id="EVT_UTT_ISABELLA_LETTER_TO_NELLY", target_id="ENT_NELLY", rel_counterpart_id="ENT_HEATHCLIFF", causality_type="mutation_social", trait_target="fear", trait_delta=0.1, mechanism="informational", evidence_strength="moderate", causal_force=4.0, fabula_time=11500, propagation_delay=0),
        CausalEdge(source_id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE", target_id="ENT_HEATHCLIFF", rel_counterpart_id="ENT_HINDLEY", causality_type="mutation_social", trait_target="power_dynamic", trait_delta=0.7, mechanism="social", evidence_strength="strong", causal_force=8.0, fabula_time=9900, propagation_delay=0),
    ],

    # ── SPATIAL TOPOLOGY ────────────────────────────────────────────────
    spatial_topology=[
        SpatialEdge(source_id="LOC_WUTHERING_HEIGHTS", target_id="LOC_MOORS"),
        SpatialEdge(source_id="LOC_THRUSHCROSS_GRANGE", target_id="LOC_MOORS"),
        SpatialEdge(source_id="LOC_MOORS", target_id="LOC_WUTHERING_HEIGHTS"),
        SpatialEdge(source_id="LOC_MOORS", target_id="LOC_THRUSHCROSS_GRANGE"),
        SpatialEdge(source_id="LOC_WUTHERING_HEIGHTS", target_id="LOC_THRUSHCROSS_GRANGE"),
        SpatialEdge(source_id="LOC_WUTHERING_HEIGHTS", target_id="LOC_GIMMERTON_KIRK"),
        SpatialEdge(source_id="LOC_THRUSHCROSS_GRANGE", target_id="LOC_GIMMERTON_KIRK"),
        SpatialEdge(source_id="LOC_LIVERPOOL", target_id="LOC_WUTHERING_HEIGHTS"),
    ],

    # ── INFORMATION TOPOLOGY ────────────────────────────────────────────
    channels={
        # Nelly's framed oral history to Lockwood — standing capability
        # spanning many evenings of narration during his convalescence.
        "CHN_NELLY_ORAL_HISTORY": Channel(
            id="CHN_NELLY_ORAL_HISTORY",
            name="Nelly Dean's framed narration to Lockwood",
            medium="oral_history",
            participant_ids=["ENT_NELLY", "ENT_LOCKWOOD"],
            directionality="simplex",
            established_at_fabula=18000,
            terminated_at_fabula=None,
            evidence_strength="strong",
        ),
        # Catherine's childhood diary as a standing artefact-channel:
        # many entries authored over years, read by Lockwood in one snowed-in night.
        "CHN_CATHERINES_DIARY": Channel(
            id="CHN_CATHERINES_DIARY",
            name="Catherine Earnshaw's childhood diary",
            medium="diary",
            participant_ids=["OBJ_CATHERINES_DIARY", "ENT_LOCKWOOD"],
            directionality="simplex",
            established_at_fabula=3000,
            terminated_at_fabula=None,
            evidence_strength="strong",
        ),
        # Isabella's letters from the south to Nelly — ongoing correspondence
        # after she flees Heathcliff.
        "CHN_ISABELLA_NELLY_LETTERS": Channel(
            id="CHN_ISABELLA_NELLY_LETTERS",
            name="Isabella ↔ Nelly correspondence",
            medium="correspondence",
            participant_ids=["ENT_ISABELLA", "ENT_NELLY"],
            directionality="duplex",
            established_at_fabula=11500,
            terminated_at_fabula=14000,
            evidence_strength="strong",
        ),
        # Coerced Linton↔Cathy letters — Heathcliff dictates / supervises every
        # message Linton sends, so Cathy's effective intelligibility of the
        # true sender is low.
        "CHN_LINTON_CATHY_COERCED_LETTERS": Channel(
            id="CHN_LINTON_CATHY_COERCED_LETTERS",
            name="Linton ↔ Cathy coerced correspondence",
            medium="coerced_correspondence",
            participant_ids=["ENT_LINTON", "ENT_CATHY", "ENT_HEATHCLIFF"],
            directionality="duplex",
            intelligibility={"ENT_CATHY": 0.3},
            established_at_fabula=15500,
            terminated_at_fabula=17000,
            evidence_strength="moderate",
        ),
        # Cathy's recurring reading lessons with Hareton — a standing teaching
        # channel that re-domesticates Hareton out of servitude.
        "CHN_HARETON_CATHY_LESSONS": Channel(
            id="CHN_HARETON_CATHY_LESSONS",
            name="Cathy's reading lessons for Hareton",
            medium="oral_tutoring",
            participant_ids=["ENT_CATHY", "ENT_HARETON"],
            directionality="duplex",
            established_at_fabula=18500,
            terminated_at_fabula=None,
            evidence_strength="strong",
        ),
    },

    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_CLASS_HIERARCHY": GlobalTrait(
            id="WORLD_CLASS_HIERARCHY",
            name="Yorkshire Gentry / Yeoman / Servant Hierarchy",
            description="The rigid Regency-Yorkshire ordering of gentry (Lintons), yeoman farmers (Earnshaws) and unfree servants (the demoted Heathcliff and the unlettered Hareton). Drives Catherine's calculation that marrying Heathcliff would degrade her, Hindley's racialised contempt, and the marriage strategies that lock the next generation into Heathcliff's hands.",
            category="social_structure",
            magnitude=TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=20000, triggered_by="EVT_CATHY_HARETON_INHERIT",
                    magnitude=TraitVector(value=0.55, inertia=0.7, evidence_strength="strong"),
                    description="Cathy literacy-tutoring Hareton up out of servant status partially dissolves the local hierarchy."),
            ],
        ),
        "WORLD_PRIMOGENITURE_ENTAIL": GlobalTrait(
            id="WORLD_PRIMOGENITURE_ENTAIL",
            name="Primogeniture and Entail",
            description="The English law of inheritance under which estates pass to male heirs along defined entail clauses. Operates as common-cause parent over Hindley's mastery, Heathcliff's mortgage acquisition of the Heights, and the engineered marriage that delivers the Grange to Heathcliff via Linton.",
            category="governance",
            magnitude=TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
            affected_domains=["social"],
        ),
        "WORLD_HAUNTED_MOORS": GlobalTrait(
            id="WORLD_HAUNTED_MOORS",
            name="The Haunted Moors",
            description="The named-latent metaphysics of the moor: a porous boundary between living and dead in which the same wind that batters the Heights also carries Catherine's ghost. Operates as a low-magnitude but high-inertia cosmological substrate, intensifying around Catherine's grave.",
            category="cosmology",
            magnitude=TraitVector(value=0.55, inertia=0.9, evidence_strength="moderate"),
            affected_domains=["psychological", "epistemic"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=11000, triggered_by="EVT_CATHERINE_DIES",
                    magnitude=TraitVector(value=0.8, inertia=0.95, evidence_strength="strong"),
                    description="Catherine's death seals the supernatural channel that will draw Heathcliff back to her."),
            ],
        ),
    },

    # ── SOCIAL TOPOLOGY ────────────────────────────────────────────────
    social_topology=[
        # Heathcliff ↔ Catherine — the absolute bond.
        RelationshipEdge(
            source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_CATHERINE",
            metrics={
                "affinity": RelationshipMetric(value=1.0, inertia=0.6, evidence_strength="strong", last_updated_fabula=11000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_CATHERINE", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity": RelationshipMetric(value=1.0, inertia=0.6, evidence_strength="strong", last_updated_fabula=11000),
            },
        ),
        # Hindley ↔ Heathcliff — class-rage and counter-vengeance.
        RelationshipEdge(
            source_entity_id="ENT_HINDLEY", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity":      RelationshipMetric(value=-0.95, inertia=0.55, evidence_strength="strong", last_updated_fabula=4000),
                "power_dynamic": RelationshipMetric(value=0.7, inertia=0.7, evidence_strength="strong", last_updated_fabula=4000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_HINDLEY",
            metrics={
                "affinity":      RelationshipMetric(value=-0.95, inertia=0.55, evidence_strength="strong", last_updated_fabula=4000),
                "power_dynamic": RelationshipMetric(value=-0.5, inertia=0.7, evidence_strength="strong", last_updated_fabula=4000),
            },
        ),
        # Catherine ↔ Edgar — settled affection.
        RelationshipEdge(
            source_entity_id="ENT_CATHERINE", target_entity_id="ENT_EDGAR",
            metrics={
                "affinity": RelationshipMetric(value=0.6, inertia=0.5, evidence_strength="strong", last_updated_fabula=9500),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_EDGAR", target_entity_id="ENT_CATHERINE",
            metrics={
                "affinity": RelationshipMetric(value=0.95, inertia=0.6, evidence_strength="strong", last_updated_fabula=11000),
            },
        ),
        # Heathcliff ↔ Edgar — formal hatred.
        RelationshipEdge(
            source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_EDGAR",
            metrics={
                "affinity": RelationshipMetric(value=-0.95, inertia=0.55, evidence_strength="strong", last_updated_fabula=10000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_EDGAR", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity": RelationshipMetric(value=-0.95, inertia=0.55, evidence_strength="strong", last_updated_fabula=10000),
                "fear":     RelationshipMetric(value=0.5, inertia=0.25, evidence_strength="moderate", last_updated_fabula=10000),
            },
        ),
        # Heathcliff → Isabella — instrumental cruelty.
        RelationshipEdge(
            source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_ISABELLA",
            metrics={
                "affinity":      RelationshipMetric(value=-0.85, inertia=0.5, evidence_strength="strong", last_updated_fabula=10000),
                "power_dynamic": RelationshipMetric(value=0.85, inertia=0.7, evidence_strength="strong", last_updated_fabula=10000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_ISABELLA", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity":      RelationshipMetric(value=-0.95, inertia=0.55, evidence_strength="strong", last_updated_fabula=11500),
                "fear":          RelationshipMetric(value=0.95, inertia=0.25, evidence_strength="strong", last_updated_fabula=11500),
                "power_dynamic": RelationshipMetric(value=-0.85, inertia=0.7, evidence_strength="strong", last_updated_fabula=10000),
            },
        ),
        # Heathcliff → Hareton — surrogate son raised in deliberate ignorance.
        RelationshipEdge(
            source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_HARETON",
            metrics={
                "affinity": RelationshipMetric(value=0.0, inertia=0.5, evidence_strength="moderate", last_updated_fabula=12000, observed=False),
                "power_dynamic": RelationshipMetric(value=0.0, inertia=0.75, evidence_strength="strong", last_updated_fabula=12000, observed=False),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_HARETON", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity": RelationshipMetric(value=0.0, inertia=0.5, evidence_strength="strong", last_updated_fabula=19000, observed=False),
                "power_dynamic": RelationshipMetric(value=0.0, inertia=0.7, evidence_strength="strong", last_updated_fabula=12000, observed=False),
            },
        ),
        # Heathcliff ↔ Linton — owned son.
        RelationshipEdge(
            source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_LINTON",
            metrics={
                "affinity":      RelationshipMetric(value=-0.5, inertia=0.5, evidence_strength="strong", last_updated_fabula=15000),
                "power_dynamic": RelationshipMetric(value=0.95, inertia=0.75, evidence_strength="strong", last_updated_fabula=15000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_LINTON", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "fear":          RelationshipMetric(value=0.95, inertia=0.25, evidence_strength="strong", last_updated_fabula=15000),
                "power_dynamic": RelationshipMetric(value=-0.95, inertia=0.75, evidence_strength="strong", last_updated_fabula=15000),
            },
        ),
        # Cathy ↔ Hareton — resentment to love.
        RelationshipEdge(
            source_entity_id="ENT_CATHY", target_entity_id="ENT_HARETON",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.55, evidence_strength="strong", last_updated_fabula=19000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_HARETON", target_entity_id="ENT_CATHY",
            metrics={
                "affinity": RelationshipMetric(value=0.9, inertia=0.55, evidence_strength="strong", last_updated_fabula=19000),
            },
        ),
        # Cathy → Heathcliff — defiance.
        RelationshipEdge(
            source_entity_id="ENT_CATHY", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity": RelationshipMetric(value=-0.85, inertia=0.5, evidence_strength="strong", last_updated_fabula=19000),
                "fear":     RelationshipMetric(value=0.5, inertia=0.25, evidence_strength="strong", last_updated_fabula=17000),
            },
        ),
        # Nelly → narrative subjects — observer's affection.
        RelationshipEdge(
            source_entity_id="ENT_NELLY", target_entity_id="ENT_CATHERINE",
            metrics={
                "affinity": RelationshipMetric(value=0.55, inertia=0.5, evidence_strength="strong", last_updated_fabula=11000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_NELLY", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity": RelationshipMetric(value=-0.2, inertia=0.45, evidence_strength="moderate", last_updated_fabula=19000),
                "fear":     RelationshipMetric(value=0.45, inertia=0.25, evidence_strength="moderate", last_updated_fabula=9000),
            },
        ),
    ],
)
