"""Wuthering Heights — high-fidelity WorldStateV1 test fixture.

Authored against the current ingestion prompts. Demonstrates all five
CausalEdge modalities, per-axis ``RelationshipMetric`` (only observed
axes populated), explicit ``evidence_strength`` everywhere, and named-
latent WORLD_ traits (Yorkshire class hierarchy, the moors as
intrusive cosmology, primogeniture and entail) wired as common-cause
parents over the events they jointly drive.
"""
from shadow_loom.models import (
    WorldStateV1, Location, Entity, EventNode, NarrativeObject,
    CausalEdge, SpatialEdge, RelationshipEdge, RelationshipMetric, InformationEdge,
    TraitVector, AmbientVector, Affordance, Belief, EntityStateSnapshot,
    GlobalTrait, WorldTraitSnapshot,
)

world_state = WorldStateV1(
    # ── LOCATIONS ──────────────────────────────────────────────────────
    locations={
        "LOC_WUTHERING_HEIGHTS": Location(
            name="Wuthering Heights",
            description="The Earnshaws' wind-battered hilltop farmhouse on the Yorkshire moors; site of every act of cruelty and most acts of love in the saga.",
            ambient_state={
                "harshness": AmbientVector(value=0.9, volatility=0.2, evidence_strength="strong"),
                "isolation": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
                "violence": AmbientVector(value=0.8, volatility=0.4, evidence_strength="strong"),
            },
        ),
        "LOC_THRUSHCROSS_GRANGE": Location(
            name="Thrushcross Grange",
            description="The Lintons' refined valley estate; symbol of civilised gentility against the Heights' wildness.",
            ambient_state={
                "refinement": AmbientVector(value=0.85, volatility=0.2, evidence_strength="strong"),
                "comfort": AmbientVector(value=0.8, volatility=0.2, evidence_strength="strong"),
            },
        ),
        "LOC_MOORS": Location(
            name="The Yorkshire Moors",
            description="The wild heath between the two houses where Catherine and Heathcliff run free as children and where their ghosts are later reported.",
            ambient_state={
                "wildness": AmbientVector(value=0.95, volatility=0.3, evidence_strength="strong"),
                "supernatural": AmbientVector(value=0.6, volatility=0.4, evidence_strength="moderate"),
            },
        ),
        "LOC_LIVERPOOL": Location(
            name="Liverpool Streets",
            description="Dock city where Mr Earnshaw finds the orphan Heathcliff and brings him home.",
            ambient_state={
                "destitution": AmbientVector(value=0.85, volatility=0.3, evidence_strength="strong"),
            },
        ),
        "LOC_GIMMERTON_KIRK": Location(
            name="Gimmerton Kirkyard",
            description="Hillside graveyard where Catherine, Edgar, and finally Heathcliff are buried side by side.",
            ambient_state={
                "stillness": AmbientVector(value=0.9, volatility=0.1, evidence_strength="strong"),
            },
        ),
    },

    # ── OBJECTS ────────────────────────────────────────────────────────
    objects={
        "OBJ_CATHERINES_DIARY": NarrativeObject(
            id="OBJ_CATHERINES_DIARY", name="Catherine's Childhood Diary",
            location_id="LOC_WUTHERING_HEIGHTS", owner_id=None,
            properties={"state": "preserved", "content": "earnshaw_grievances"},
            affordances=[Affordance(action="reveal_past", target_type="Entity")],
        ),
        "OBJ_HEIGHTS_MORTGAGE": NarrativeObject(
            id="OBJ_HEIGHTS_MORTGAGE", name="Mortgage on Wuthering Heights",
            location_id=None, owner_id="ENT_HEATHCLIFF",
            properties={"state": "held_against_hindley", "originated": "gambling_debt"},
            affordances=[Affordance(action="dispossess", target_type="Entity")],
        ),
        "OBJ_GRANGE_DEED": NarrativeObject(
            id="OBJ_GRANGE_DEED", name="Thrushcross Grange Entail",
            location_id="LOC_THRUSHCROSS_GRANGE", owner_id="ENT_EDGAR",
            properties={"state": "entailed", "successor_clause": "edgar_heir_or_isabellas_heir"},
            affordances=[Affordance(action="transfer_estate", target_type="Entity")],
        ),
        "OBJ_CATHERINES_GRAVE": NarrativeObject(
            id="OBJ_CATHERINES_GRAVE", name="Catherine's Grave",
            location_id="LOC_GIMMERTON_KIRK", owner_id=None,
            properties={"state": "twice_disinterred"},
            affordances=[Affordance(action="haunt", target_type="Entity")],
        ),
    },

    # ── ENTITIES ────────────────────────────────────────────────────────
    entities={
        "ENT_HEATHCLIFF": Entity(
            id="ENT_HEATHCLIFF", name="Heathcliff",
            location_id="LOC_LIVERPOOL", status="healthy",
            traits={
                "intensity": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "vengefulness": TraitVector(value=0.3, inertia=0.45, evidence_strength="moderate"),
                "devotion": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                "cruelty": TraitVector(value=0.2, inertia=0.4, evidence_strength="weak"),
                "endurance": TraitVector(value=0.9, inertia=0.75, evidence_strength="strong"),
                "despair": TraitVector(value=0.1, inertia=0.3, evidence_strength="weak"),
                "grief": TraitVector(value=0.1, inertia=0.3, evidence_strength="weak"),
            },
            beliefs=[
                Belief(target_id="ENT_CATHERINE",
                       perceived_state="Catherine and I are the same soul",
                       confidence=1.0, inertia=0.95, established_at_fabula=200, evidence_strength="strong"),
            ],
            constants=["foundling_origin", "racial_other"],
            state_timeline=[
                EntityStateSnapshot(fabula_time=100, triggered_by="EVT_EARNSHAW_BRINGS_HEATHCLIFF",
                    location_id="LOC_WUTHERING_HEIGHTS"),
                EntityStateSnapshot(fabula_time=400, triggered_by="EVT_HINDLEY_DEMOTES_HEATHCLIFF",
                    traits={
                        "vengefulness": TraitVector(value=0.7, inertia=0.6, evidence_strength="strong"),
                        "endurance": TraitVector(value=0.95, inertia=0.8, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_HINDLEY",
                               perceived_state="I will live to ruin Hindley and his line",
                               confidence=0.85, inertia=0.7, established_at_fabula=400, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=700, triggered_by="EVT_HEATHCLIFF_OVERHEARS",
                    traits={
                        "despair": TraitVector(value=0.85, inertia=0.5, evidence_strength="strong"),
                        "vengefulness": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=750, triggered_by="EVT_HEATHCLIFF_FLEES",
                    location_id=None),
                EntityStateSnapshot(fabula_time=900, triggered_by="EVT_HEATHCLIFF_RETURNS",
                    location_id="LOC_THRUSHCROSS_GRANGE",
                    traits={
                        "cruelty": TraitVector(value=0.7, inertia=0.55, evidence_strength="strong"),
                        "vengefulness": TraitVector(value=0.95, inertia=0.7, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_CATHERINE_DIES",
                    location_id="LOC_WUTHERING_HEIGHTS",
                    traits={
                        "grief": TraitVector(value=1.0, inertia=0.85, evidence_strength="strong"),
                        "despair": TraitVector(value=0.95, inertia=0.7, evidence_strength="strong"),
                    },
                    beliefs_added=[
                        Belief(target_id="ENT_CATHERINE",
                               perceived_state="Be with me always — take any form — drive me mad!",
                               confidence=1.0, inertia=0.9, established_at_fabula=1100, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=1900, triggered_by="EVT_HEATHCLIFF_STOPS_EATING",
                    status="ill",
                    traits={
                        "vengefulness": TraitVector(value=0.2, inertia=0.7, evidence_strength="strong"),
                        "despair": TraitVector(value=1.0, inertia=0.75, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=1950, triggered_by="EVT_HEATHCLIFF_DIES",
                    status="dead", location_id="LOC_WUTHERING_HEIGHTS"),
            ],
        ),
        "ENT_CATHERINE": Entity(
            id="ENT_CATHERINE", name="Catherine Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "wildness": TraitVector(value=0.9, inertia=0.7, evidence_strength="strong"),
                "passion": TraitVector(value=0.95, inertia=0.7, evidence_strength="strong"),
                "vanity": TraitVector(value=0.7, inertia=0.55, evidence_strength="strong"),
                "self_division": TraitVector(value=0.4, inertia=0.4, evidence_strength="moderate"),
                "wilfulness": TraitVector(value=0.9, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF",
                       perceived_state="I am Heathcliff — he is more myself than I am",
                       confidence=1.0, inertia=0.85, established_at_fabula=200, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=600, triggered_by="EVT_CATHERINE_AT_LINTONS",
                    traits={
                        "vanity": TraitVector(value=0.85, inertia=0.65, evidence_strength="strong"),
                        "self_division": TraitVector(value=0.8, inertia=0.55, evidence_strength="strong"),
                    },
                    location_id="LOC_THRUSHCROSS_GRANGE"),
                EntityStateSnapshot(fabula_time=750, triggered_by="EVT_HEATHCLIFF_FLEES",
                    status="ill",
                    traits={
                        "passion": TraitVector(value=1.0, inertia=0.75, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=950, triggered_by="EVT_CATHERINE_MARRIES_EDGAR",
                    location_id="LOC_THRUSHCROSS_GRANGE"),
                EntityStateSnapshot(fabula_time=1050, triggered_by="EVT_CATHERINE_LOCKS_HERSELF",
                    status="ill",
                    traits={
                        "self_division": TraitVector(value=1.0, inertia=0.7, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_CATHERINE_DIES",
                    status="dead", location_id="LOC_GIMMERTON_KIRK"),
            ],
        ),
        "ENT_HINDLEY": Entity(
            id="ENT_HINDLEY", name="Hindley Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "jealousy": TraitVector(value=0.8, inertia=0.6, evidence_strength="strong"),
                "brutality": TraitVector(value=0.6, inertia=0.55, evidence_strength="moderate"),
                "addiction_to_drink": TraitVector(value=0.2, inertia=0.4, evidence_strength="weak"),
                "self_pity": TraitVector(value=0.5, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF",
                       perceived_state="The gipsy brat has stolen my father's love",
                       confidence=0.95, inertia=0.75, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=350, triggered_by="EVT_OLD_EARNSHAW_DIES",
                    traits={
                        "brutality": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=550, triggered_by="EVT_FRANCES_DIES",
                    traits={
                        "addiction_to_drink": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                        "self_pity": TraitVector(value=0.9, inertia=0.65, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=1200, triggered_by="EVT_HINDLEY_DIES",
                    status="dead"),
            ],
        ),
        "ENT_EDGAR": Entity(
            id="ENT_EDGAR", name="Edgar Linton",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "gentility": TraitVector(value=0.9, inertia=0.75, evidence_strength="strong"),
                "tenderness": TraitVector(value=0.8, inertia=0.65, evidence_strength="strong"),
                "weakness": TraitVector(value=0.55, inertia=0.5, evidence_strength="moderate"),
                "devotion": TraitVector(value=0.85, inertia=0.7, evidence_strength="strong"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1100, triggered_by="EVT_CATHERINE_DIES",
                    traits={
                        "devotion": TraitVector(value=0.95, inertia=0.85, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=1500, triggered_by="EVT_EDGAR_DIES",
                    status="dead"),
            ],
        ),
        "ENT_ISABELLA": Entity(
            id="ENT_ISABELLA", name="Isabella Linton",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "naivety": TraitVector(value=0.85, inertia=0.55, evidence_strength="strong"),
                "infatuation": TraitVector(value=0.4, inertia=0.4, evidence_strength="moderate"),
                "endurance": TraitVector(value=0.4, inertia=0.45, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF",
                       perceived_state="Heathcliff is a darkly romantic hero",
                       confidence=0.7, inertia=0.4, established_at_fabula=900, evidence_strength="moderate"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1000, triggered_by="EVT_ISABELLA_ELOPES",
                    location_id="LOC_WUTHERING_HEIGHTS",
                    traits={
                        "infatuation": TraitVector(value=0.9, inertia=0.5, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=1150, triggered_by="EVT_ISABELLA_FLEES_SOUTH",
                    location_id=None,
                    beliefs_invalidated=["ENT_HEATHCLIFF"],
                    beliefs_added=[
                        Belief(target_id="ENT_HEATHCLIFF",
                               perceived_state="Heathcliff is a fiend who can never love anything but Catherine",
                               confidence=0.95, inertia=0.7, established_at_fabula=1150, evidence_strength="strong"),
                    ]),
                EntityStateSnapshot(fabula_time=1400, triggered_by="EVT_ISABELLA_DIES",
                    status="dead"),
            ],
        ),
        "ENT_NELLY": Entity(
            id="ENT_NELLY", name="Ellen 'Nelly' Dean",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "loyalty": TraitVector(value=0.7, inertia=0.6, evidence_strength="strong"),
                "judgement": TraitVector(value=0.7, inertia=0.6, evidence_strength="strong"),
                "interventionism": TraitVector(value=0.6, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=950, triggered_by="EVT_CATHERINE_MARRIES_EDGAR",
                    location_id="LOC_THRUSHCROSS_GRANGE"),
                EntityStateSnapshot(fabula_time=1900, triggered_by="EVT_HEATHCLIFF_STOPS_EATING",
                    location_id="LOC_WUTHERING_HEIGHTS"),
            ],
        ),
        "ENT_OLD_EARNSHAW": Entity(
            id="ENT_OLD_EARNSHAW", name="Mr Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "stubbornness": TraitVector(value=0.7, inertia=0.7, evidence_strength="moderate"),
                "favouritism": TraitVector(value=0.7, inertia=0.65, evidence_strength="strong"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=350, triggered_by="EVT_OLD_EARNSHAW_DIES",
                    status="dead"),
            ],
        ),
        "ENT_FRANCES": Entity(
            id="ENT_FRANCES", name="Frances Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "cheerfulness": TraitVector(value=0.7, inertia=0.5, evidence_strength="moderate"),
                "frailty": TraitVector(value=0.5, inertia=0.5, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=550, triggered_by="EVT_FRANCES_DIES",
                    status="dead"),
            ],
        ),
        "ENT_HARETON": Entity(
            id="ENT_HARETON", name="Hareton Earnshaw",
            location_id="LOC_WUTHERING_HEIGHTS", status="healthy",
            traits={
                "neglected_dignity": TraitVector(value=0.7, inertia=0.55, evidence_strength="strong"),
                "loyalty": TraitVector(value=0.7, inertia=0.55, evidence_strength="moderate"),
                "shame": TraitVector(value=0.6, inertia=0.45, evidence_strength="moderate"),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF",
                       perceived_state="Heathcliff is the only father I have known",
                       confidence=0.7, inertia=0.55, established_at_fabula=1300, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1850, triggered_by="EVT_CATHY_TEACHES_HARETON",
                    traits={
                        "shame": TraitVector(value=0.15, inertia=0.55, evidence_strength="strong"),
                        "neglected_dignity": TraitVector(value=0.3, inertia=0.65, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_LINTON": Entity(
            id="ENT_LINTON", name="Linton Heathcliff",
            location_id="LOC_THRUSHCROSS_GRANGE", status="ill",
            traits={
                "frailty": TraitVector(value=0.95, inertia=0.65, evidence_strength="strong"),
                "petulance": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                "fear": TraitVector(value=0.7, inertia=0.4, evidence_strength="strong"),
            },
            beliefs=[
                Belief(target_id="ENT_HEATHCLIFF",
                       perceived_state="My father will harm me if I disobey",
                       confidence=0.95, inertia=0.55, established_at_fabula=1500, evidence_strength="strong"),
            ],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1500, triggered_by="EVT_LINTON_TAKEN_BY_FATHER",
                    location_id="LOC_WUTHERING_HEIGHTS"),
                EntityStateSnapshot(fabula_time=1700, triggered_by="EVT_LINTON_DIES",
                    status="dead"),
            ],
        ),
        "ENT_CATHY": Entity(
            id="ENT_CATHY", name="Cathy Linton",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "courage": TraitVector(value=0.75, inertia=0.55, evidence_strength="strong"),
                "warmth": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                "stubbornness": TraitVector(value=0.7, inertia=0.55, evidence_strength="strong"),
                "resilience": TraitVector(value=0.7, inertia=0.55, evidence_strength="moderate"),
            },
            beliefs=[],
            state_timeline=[
                EntityStateSnapshot(fabula_time=1600, triggered_by="EVT_CATHY_FORCED_MARRIAGE",
                    location_id="LOC_WUTHERING_HEIGHTS",
                    traits={
                        "courage": TraitVector(value=0.85, inertia=0.6, evidence_strength="strong"),
                    }),
                EntityStateSnapshot(fabula_time=1850, triggered_by="EVT_CATHY_TEACHES_HARETON",
                    traits={
                        "warmth": TraitVector(value=0.95, inertia=0.65, evidence_strength="strong"),
                    }),
            ],
        ),
        "ENT_LOCKWOOD": Entity(
            id="ENT_LOCKWOOD", name="Mr Lockwood",
            location_id="LOC_THRUSHCROSS_GRANGE", status="healthy",
            traits={
                "curiosity": TraitVector(value=0.8, inertia=0.5, evidence_strength="strong"),
                "obtuseness": TraitVector(value=0.6, inertia=0.55, evidence_strength="moderate"),
            },
            beliefs=[],
        ),
    },

    # ── EVENTS ──────────────────────────────────────────────────────────
    events=[
        EventNode(id="EVT_EARNSHAW_BRINGS_HEATHCLIFF", fabula_time=100, syuzhet_index=2,
                  event_type="choice", actor_ids=["ENT_OLD_EARNSHAW"], target_ids=["ENT_HEATHCLIFF"],
                  description="Mr Earnshaw returns from a Liverpool trip with the orphan Heathcliff and brings him to live at Wuthering Heights as a favoured ward."),
        EventNode(id="EVT_HEATHCLIFF_AND_CATHERINE_BOND", fabula_time=200, syuzhet_index=3,
                  event_type="outcome", actor_ids=["ENT_HEATHCLIFF", "ENT_CATHERINE"], target_ids=[],
                  description="Heathcliff and Catherine become inseparable companions, roaming the moors together."),
        EventNode(id="EVT_OLD_EARNSHAW_DIES", fabula_time=350, syuzhet_index=4,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_OLD_EARNSHAW"],
                  description="Mr Earnshaw dies; Hindley returns from university with his wife Frances to take over Wuthering Heights."),
        EventNode(id="EVT_HINDLEY_DEMOTES_HEATHCLIFF", fabula_time=400, syuzhet_index=5,
                  event_type="choice", actor_ids=["ENT_HINDLEY"], target_ids=["ENT_HEATHCLIFF"],
                  description="Hindley reduces Heathcliff to the status of a farm servant, beats him, and forbids his lessons."),
        EventNode(id="EVT_FRANCES_DIES", fabula_time=550, syuzhet_index=6,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_FRANCES"],
                  description="Frances dies after giving birth to Hareton; Hindley descends into alcoholism."),
        EventNode(id="EVT_CATHERINE_AT_LINTONS", fabula_time=600, syuzhet_index=7,
                  event_type="outcome", actor_ids=["ENT_CATHERINE"], target_ids=[],
                  description="Catherine, attacked by the Lintons' dog while spying with Heathcliff, stays five weeks at Thrushcross Grange and returns transformed into a young lady."),
        EventNode(id="EVT_HEATHCLIFF_OVERHEARS", fabula_time=700, syuzhet_index=8,
                  event_type="revelation", actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Heathcliff overhears Catherine tell Nelly it would degrade her to marry him, but leaves before hearing her declaration that she IS Heathcliff."),
        EventNode(id="EVT_HEATHCLIFF_FLEES", fabula_time=750, syuzhet_index=9,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Heathcliff disappears from Wuthering Heights; Catherine falls dangerously ill."),
        EventNode(id="EVT_LINTON_PARENTS_DIE", fabula_time=800, syuzhet_index=10,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_EDGAR"],
                  description="Mr and Mrs Linton die of the fever they caught nursing Catherine; Edgar inherits Thrushcross Grange under an entail favouring his male heir or Isabella's heir."),
        EventNode(id="EVT_CATHERINE_MARRIES_EDGAR", fabula_time=950, syuzhet_index=11,
                  event_type="choice", actor_ids=["ENT_CATHERINE", "ENT_EDGAR"], target_ids=[],
                  description="Catherine marries Edgar Linton and becomes mistress of Thrushcross Grange."),
        EventNode(id="EVT_HEATHCLIFF_RETURNS", fabula_time=900, syuzhet_index=12,
                  event_type="outcome", actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Three years after fleeing, Heathcliff returns mysteriously wealthy and re-enters the lives of the Earnshaws and Lintons."),
        EventNode(id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE", fabula_time=980, syuzhet_index=13,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=["ENT_HINDLEY"],
                  description="Heathcliff exploits Hindley's gambling addiction to become mortgagee of Wuthering Heights."),
        EventNode(id="EVT_ISABELLA_ELOPES", fabula_time=1000, syuzhet_index=14,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF", "ENT_ISABELLA"], target_ids=[],
                  description="Heathcliff cynically elopes with the infatuated Isabella to spite Edgar."),
        EventNode(id="EVT_CATHERINE_LOCKS_HERSELF", fabula_time=1050, syuzhet_index=15,
                  event_type="choice", actor_ids=["ENT_CATHERINE"], target_ids=[],
                  description="Caught between Edgar and Heathcliff, Catherine locks herself in her room and refuses food for three days."),
        EventNode(id="EVT_HEATHCLIFF_VISITS_DYING_CATHERINE", fabula_time=1090, syuzhet_index=16,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=["ENT_CATHERINE"],
                  description="Heathcliff steals to Catherine's bedside; they accuse and embrace each other in a final scene."),
        EventNode(id="EVT_CATHERINE_DIES", fabula_time=1100, syuzhet_index=17,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_CATHERINE"],
                  description="Catherine dies after giving birth to a daughter, Cathy."),
        EventNode(id="EVT_ISABELLA_FLEES_SOUTH", fabula_time=1150, syuzhet_index=18,
                  event_type="choice", actor_ids=["ENT_ISABELLA"], target_ids=[],
                  description="Isabella, abused and disillusioned, flees Heathcliff's house and goes south to bear his sickly son Linton."),
        EventNode(id="EVT_HINDLEY_DIES", fabula_time=1200, syuzhet_index=19,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_HINDLEY"],
                  description="Hindley dies of alcoholism six months after Catherine; Heathcliff takes possession of Wuthering Heights and Hareton with it."),
        EventNode(id="EVT_HEATHCLIFF_OPENS_GRAVE", fabula_time=1300, syuzhet_index=20,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Heathcliff bribes the sexton to open Catherine's grave for the first time."),
        EventNode(id="EVT_ISABELLA_DIES", fabula_time=1400, syuzhet_index=21,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_ISABELLA"],
                  description="Isabella dies in the south; her son Linton is brought north."),
        EventNode(id="EVT_LINTON_TAKEN_BY_FATHER", fabula_time=1500, syuzhet_index=22,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=["ENT_LINTON"],
                  description="Heathcliff insists his son Linton be brought to Wuthering Heights, despite Edgar's claim and the boy's frailty."),
        EventNode(id="EVT_EDGAR_DIES", fabula_time=1500, syuzhet_index=23,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_EDGAR"],
                  description="Edgar Linton dies; under the entail Thrushcross Grange will pass through his son-in-law Linton."),
        EventNode(id="EVT_CATHY_FORCED_MARRIAGE", fabula_time=1600, syuzhet_index=24,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=["ENT_CATHY", "ENT_LINTON"],
                  description="Heathcliff manoeuvres Cathy into marrying his dying son Linton, securing the Grange."),
        EventNode(id="EVT_LINTON_DIES", fabula_time=1700, syuzhet_index=25,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_LINTON"],
                  description="Linton dies, leaving Cathy a teenage widow trapped at Wuthering Heights with the now-master Heathcliff."),
        EventNode(id="EVT_LOCKWOOD_DREAMS", fabula_time=1800, syuzhet_index=1,
                  event_type="revelation", actor_ids=["ENT_LOCKWOOD"], target_ids=["ENT_HEATHCLIFF"],
                  description="Snowbound at Wuthering Heights, Lockwood dreams of Catherine's ghost begging entry; his cries shatter Heathcliff."),
        EventNode(id="EVT_HEATHCLIFF_OPENS_GRAVE_AGAIN", fabula_time=1850, syuzhet_index=26,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Heathcliff opens Catherine's grave a second time and arranges for his own coffin to lie touching hers."),
        EventNode(id="EVT_CATHY_TEACHES_HARETON", fabula_time=1850, syuzhet_index=27,
                  event_type="choice", actor_ids=["ENT_CATHY"], target_ids=["ENT_HARETON"],
                  description="Cathy reconciles with Hareton and begins teaching him to read; the two fall in love."),
        EventNode(id="EVT_HEATHCLIFF_STOPS_EATING", fabula_time=1900, syuzhet_index=28,
                  event_type="choice", actor_ids=["ENT_HEATHCLIFF"], target_ids=[],
                  description="Increasingly haunted by visions of Catherine, Heathcliff stops eating and avoids the young couple."),
        EventNode(id="EVT_HEATHCLIFF_DIES", fabula_time=1950, syuzhet_index=29,
                  event_type="outcome", actor_ids=[], target_ids=["ENT_HEATHCLIFF"],
                  description="Heathcliff is found dead in Catherine's old room with his eyes open; Hareton mourns him."),
        EventNode(id="EVT_CATHY_HARETON_INHERIT", fabula_time=2000, syuzhet_index=30,
                  event_type="outcome", actor_ids=["ENT_CATHY", "ENT_HARETON"], target_ids=[],
                  description="Hareton reclaims Wuthering Heights and Cathy regains the Grange; they plan to marry on New Year's Day."),
    ],

    # ── CAUSAL TOPOLOGY ────────────────────────────────────────────────
    causal_topology=[
        # ── chain_reaction ──
        CausalEdge(source_id="EVT_EARNSHAW_BRINGS_HEATHCLIFF", target_id="EVT_HEATHCLIFF_AND_CATHERINE_BOND",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=100, propagation_delay=100),
        CausalEdge(source_id="EVT_OLD_EARNSHAW_DIES", target_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=350, propagation_delay=50),
        CausalEdge(source_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF", target_id="EVT_HEATHCLIFF_OVERHEARS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=400, propagation_delay=300),
        CausalEdge(source_id="EVT_CATHERINE_AT_LINTONS", target_id="EVT_HEATHCLIFF_OVERHEARS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=600, propagation_delay=100),
        CausalEdge(source_id="EVT_FRANCES_DIES", target_id="EVT_HINDLEY_DIES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=550, propagation_delay=650),
        CausalEdge(source_id="EVT_HEATHCLIFF_OVERHEARS", target_id="EVT_HEATHCLIFF_FLEES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=9.0, fabula_time=700, propagation_delay=50),
        CausalEdge(source_id="EVT_HEATHCLIFF_FLEES", target_id="EVT_CATHERINE_MARRIES_EDGAR",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=750, propagation_delay=200),
        CausalEdge(source_id="EVT_LINTON_PARENTS_DIE", target_id="EVT_CATHERINE_MARRIES_EDGAR",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=800, propagation_delay=150),
        CausalEdge(source_id="EVT_HEATHCLIFF_RETURNS", target_id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900, propagation_delay=80),
        CausalEdge(source_id="EVT_HEATHCLIFF_RETURNS", target_id="EVT_ISABELLA_ELOPES",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900, propagation_delay=100),
        CausalEdge(source_id="EVT_HEATHCLIFF_RETURNS", target_id="EVT_CATHERINE_LOCKS_HERSELF",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=900, propagation_delay=150),
        CausalEdge(source_id="EVT_CATHERINE_LOCKS_HERSELF", target_id="EVT_HEATHCLIFF_VISITS_DYING_CATHERINE",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1050, propagation_delay=40),
        CausalEdge(source_id="EVT_HEATHCLIFF_VISITS_DYING_CATHERINE", target_id="EVT_CATHERINE_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1090, propagation_delay=10),
        CausalEdge(source_id="EVT_ISABELLA_ELOPES", target_id="EVT_ISABELLA_FLEES_SOUTH",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1000, propagation_delay=150),
        CausalEdge(source_id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE", target_id="EVT_HINDLEY_DIES",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=980, propagation_delay=220),
        CausalEdge(source_id="EVT_CATHERINE_DIES", target_id="EVT_HEATHCLIFF_OPENS_GRAVE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1100, propagation_delay=200),
        CausalEdge(source_id="EVT_ISABELLA_FLEES_SOUTH", target_id="EVT_ISABELLA_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1150, propagation_delay=250),
        CausalEdge(source_id="EVT_ISABELLA_DIES", target_id="EVT_LINTON_TAKEN_BY_FATHER",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1400, propagation_delay=100),
        CausalEdge(source_id="EVT_LINTON_TAKEN_BY_FATHER", target_id="EVT_CATHY_FORCED_MARRIAGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1500, propagation_delay=100),
        CausalEdge(source_id="EVT_EDGAR_DIES", target_id="EVT_CATHY_FORCED_MARRIAGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1500, propagation_delay=100),
        CausalEdge(source_id="EVT_CATHY_FORCED_MARRIAGE", target_id="EVT_LINTON_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1600, propagation_delay=100),
        CausalEdge(source_id="EVT_LOCKWOOD_DREAMS", target_id="EVT_HEATHCLIFF_OPENS_GRAVE_AGAIN",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1800, propagation_delay=50),
        CausalEdge(source_id="EVT_HEATHCLIFF_OPENS_GRAVE_AGAIN", target_id="EVT_HEATHCLIFF_STOPS_EATING",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1850, propagation_delay=50),
        CausalEdge(source_id="EVT_LINTON_DIES", target_id="EVT_CATHY_TEACHES_HARETON",
                   causality_type="chain_reaction", mechanism="emotional", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1700, propagation_delay=150),
        CausalEdge(source_id="EVT_CATHY_TEACHES_HARETON", target_id="EVT_HEATHCLIFF_STOPS_EATING",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1850, propagation_delay=50),
        CausalEdge(source_id="EVT_HEATHCLIFF_STOPS_EATING", target_id="EVT_HEATHCLIFF_DIES",
                   causality_type="chain_reaction", mechanism="physical", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1900, propagation_delay=50),
        CausalEdge(source_id="EVT_HEATHCLIFF_DIES", target_id="EVT_CATHY_HARETON_INHERIT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1950, propagation_delay=50),

        # ── mutation ──
        CausalEdge(source_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=400,
                   trait_target="vengefulness", trait_delta=0.4),
        CausalEdge(source_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=400,
                   trait_target="endurance", trait_delta=0.05),
        CausalEdge(source_id="EVT_CATHERINE_AT_LINTONS", target_id="ENT_CATHERINE",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=600,
                   trait_target="vanity", trait_delta=0.15),
        CausalEdge(source_id="EVT_CATHERINE_AT_LINTONS", target_id="ENT_CATHERINE",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=600,
                   trait_target="self_division", trait_delta=0.4),
        CausalEdge(source_id="EVT_HEATHCLIFF_OVERHEARS", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=700,
                   trait_target="despair", trait_delta=0.75),
        CausalEdge(source_id="EVT_HEATHCLIFF_OVERHEARS", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=10.0, fabula_time=700,
                   trait_target="vengefulness", trait_delta=0.55),
        CausalEdge(source_id="EVT_HEATHCLIFF_RETURNS", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=900,
                   trait_target="cruelty", trait_delta=0.5),
        CausalEdge(source_id="EVT_FRANCES_DIES", target_id="ENT_HINDLEY",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=550,
                   trait_target="addiction_to_drink", trait_delta=0.65),
        CausalEdge(source_id="EVT_CATHERINE_DIES", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1100,
                   trait_target="grief", trait_delta=0.9),
        CausalEdge(source_id="EVT_CATHERINE_DIES", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1100,
                   trait_target="despair", trait_delta=0.85),
        CausalEdge(source_id="EVT_ISABELLA_ELOPES", target_id="ENT_ISABELLA",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1000,
                   trait_target="infatuation", trait_delta=0.5),
        CausalEdge(source_id="EVT_ISABELLA_FLEES_SOUTH", target_id="ENT_ISABELLA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1150,
                   trait_target="endurance", trait_delta=0.3),
        CausalEdge(source_id="EVT_HEATHCLIFF_OPENS_GRAVE_AGAIN", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1850,
                   trait_target="vengefulness", trait_delta=-0.6),
        CausalEdge(source_id="EVT_CATHY_TEACHES_HARETON", target_id="ENT_HARETON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1850,
                   trait_target="shame", trait_delta=-0.45),
        CausalEdge(source_id="EVT_CATHY_TEACHES_HARETON", target_id="ENT_HARETON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1850,
                   trait_target="neglected_dignity", trait_delta=-0.4),
        # — Coverage mutations for previously un-mutated significant events —
        CausalEdge(source_id="EVT_EARNSHAW_BRINGS_HEATHCLIFF", target_id="ENT_HINDLEY",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=100,
                   trait_target="jealousy", trait_delta=0.3),
        CausalEdge(source_id="EVT_EARNSHAW_BRINGS_HEATHCLIFF", target_id="ENT_CATHERINE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=100,
                   trait_target="bond", trait_delta=0.5),
        CausalEdge(source_id="EVT_OLD_EARNSHAW_DIES", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=7.0, fabula_time=350,
                   trait_target="vulnerability", trait_delta=0.5),
        CausalEdge(source_id="EVT_OLD_EARNSHAW_DIES", target_id="ENT_HINDLEY",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=350,
                   trait_target="tyranny", trait_delta=0.6),
        CausalEdge(source_id="EVT_LINTON_PARENTS_DIE", target_id="ENT_EDGAR",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=800,
                   trait_target="grief", trait_delta=0.6),
        CausalEdge(source_id="EVT_LINTON_PARENTS_DIE", target_id="ENT_ISABELLA",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=800,
                   trait_target="grief", trait_delta=0.6),
        CausalEdge(source_id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE", target_id="ENT_HINDLEY",
                   causality_type="mutation", mechanism="psychological", evidence_strength="strong",
                   causal_force=8.0, fabula_time=980,
                   trait_target="despair", trait_delta=0.6),
        CausalEdge(source_id="EVT_HEATHCLIFF_VISITS_DYING_CATHERINE", target_id="ENT_CATHERINE",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1090,
                   trait_target="anguish", trait_delta=0.8),
        CausalEdge(source_id="EVT_HINDLEY_DIES", target_id="ENT_HARETON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1200,
                   trait_target="loyalty", trait_delta=0.2),
        CausalEdge(source_id="EVT_ISABELLA_DIES", target_id="ENT_LINTON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1400,
                   trait_target="fear", trait_delta=0.3),
        CausalEdge(source_id="EVT_LINTON_TAKEN_BY_FATHER", target_id="ENT_LINTON",
                   causality_type="mutation", mechanism="social", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1500,
                   trait_target="fear", trait_delta=0.5),
        CausalEdge(source_id="EVT_EDGAR_DIES", target_id="ENT_CATHY",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1500,
                   trait_target="resilience", trait_delta=0.2),
        CausalEdge(source_id="EVT_LINTON_DIES", target_id="ENT_CATHY",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1700,
                   trait_target="warmth", trait_delta=-0.2),
        CausalEdge(source_id="EVT_HEATHCLIFF_DIES", target_id="ENT_HARETON",
                   causality_type="mutation", mechanism="emotional", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1950,
                   trait_target="loyalty", trait_delta=0.2),

        # ── mutation_social ──
        CausalEdge(source_id="EVT_HEATHCLIFF_AND_CATHERINE_BOND", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=200,
                   trait_target="affinity", trait_delta=1.0, rel_counterpart_id="ENT_CATHERINE"),
        CausalEdge(source_id="EVT_HEATHCLIFF_AND_CATHERINE_BOND", target_id="ENT_CATHERINE",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=10.0, fabula_time=200,
                   trait_target="affinity", trait_delta=1.0, rel_counterpart_id="ENT_HEATHCLIFF"),
        CausalEdge(source_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=8.0, fabula_time=400,
                   trait_target="affinity", trait_delta=-0.95, rel_counterpart_id="ENT_HINDLEY"),
        CausalEdge(source_id="EVT_CATHERINE_MARRIES_EDGAR", target_id="ENT_HEATHCLIFF",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=950,
                   trait_target="affinity", trait_delta=-0.4, rel_counterpart_id="ENT_EDGAR"),
        CausalEdge(source_id="EVT_ISABELLA_ELOPES", target_id="ENT_ISABELLA",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=1000,
                   trait_target="affinity", trait_delta=0.6, rel_counterpart_id="ENT_HEATHCLIFF"),
        CausalEdge(source_id="EVT_ISABELLA_FLEES_SOUTH", target_id="ENT_ISABELLA",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=10.0, fabula_time=1150,
                   trait_target="affinity", trait_delta=-1.0, rel_counterpart_id="ENT_HEATHCLIFF"),
        CausalEdge(source_id="EVT_CATHY_FORCED_MARRIAGE", target_id="ENT_CATHY",
                   causality_type="mutation_social", mechanism="betrayal", evidence_strength="strong",
                   causal_force=9.0, fabula_time=1600,
                   trait_target="fear", trait_delta=0.7, rel_counterpart_id="ENT_HEATHCLIFF"),
        CausalEdge(source_id="EVT_CATHY_TEACHES_HARETON", target_id="ENT_CATHY",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1850,
                   trait_target="affinity", trait_delta=0.85, rel_counterpart_id="ENT_HARETON"),
        CausalEdge(source_id="EVT_CATHY_TEACHES_HARETON", target_id="ENT_HARETON",
                   causality_type="mutation_social", mechanism="emotional", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1850,
                   trait_target="affinity", trait_delta=0.85, rel_counterpart_id="ENT_CATHY"),

        # ── affordance_gate ──
        CausalEdge(source_id="OBJ_CATHERINES_DIARY", target_id="EVT_LOCKWOOD_DREAMS",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1800),
        CausalEdge(source_id="OBJ_HEIGHTS_MORTGAGE", target_id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=980),
        CausalEdge(source_id="OBJ_GRANGE_DEED", target_id="EVT_CATHY_FORCED_MARRIAGE",
                   causality_type="affordance_gate", mechanism="social", evidence_strength="strong",
                   causal_force=8.0, fabula_time=1600),
        CausalEdge(source_id="OBJ_CATHERINES_GRAVE", target_id="EVT_HEATHCLIFF_OPENS_GRAVE",
                   causality_type="affordance_gate", mechanism="physical", evidence_strength="strong",
                   causal_force=7.0, fabula_time=1300),
        CausalEdge(source_id="ENT_NELLY", target_id="EVT_HEATHCLIFF_OVERHEARS",
                   causality_type="affordance_gate", mechanism="informational", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=700),

        # ── ambient_propagation ──
        CausalEdge(source_id="LOC_WUTHERING_HEIGHTS", target_id="ENT_HEATHCLIFF",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=400),
        CausalEdge(source_id="LOC_THRUSHCROSS_GRANGE", target_id="ENT_CATHERINE",
                   causality_type="ambient_propagation", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=600),
        CausalEdge(source_id="LOC_MOORS", target_id="ENT_HEATHCLIFF",
                   causality_type="ambient_propagation", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=200),

        # ── WORLD_ → Event ──
        CausalEdge(source_id="WORLD_CLASS_HIERARCHY", target_id="EVT_HINDLEY_DEMOTES_HEATHCLIFF",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=400),
        CausalEdge(source_id="WORLD_CLASS_HIERARCHY", target_id="EVT_HEATHCLIFF_OVERHEARS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=700),
        CausalEdge(source_id="WORLD_CLASS_HIERARCHY", target_id="EVT_CATHERINE_MARRIES_EDGAR",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=950),
        CausalEdge(source_id="WORLD_CLASS_HIERARCHY", target_id="EVT_CATHERINE_AT_LINTONS",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=600),
        CausalEdge(source_id="WORLD_PRIMOGENITURE_ENTAIL", target_id="EVT_LINTON_TAKEN_BY_FATHER",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=1500),
        CausalEdge(source_id="WORLD_PRIMOGENITURE_ENTAIL", target_id="EVT_CATHY_FORCED_MARRIAGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=6.0, fabula_time=1600),
        CausalEdge(source_id="WORLD_PRIMOGENITURE_ENTAIL", target_id="EVT_HEATHCLIFF_TAKES_HEIGHTS_MORTGAGE",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="moderate",
                   causal_force=5.0, fabula_time=980),
        CausalEdge(source_id="WORLD_PRIMOGENITURE_ENTAIL", target_id="EVT_CATHY_HARETON_INHERIT",
                   causality_type="chain_reaction", mechanism="social", evidence_strength="strong",
                   causal_force=5.0, fabula_time=2000),
        CausalEdge(source_id="WORLD_HAUNTED_MOORS", target_id="EVT_LOCKWOOD_DREAMS",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1800),
        CausalEdge(source_id="WORLD_HAUNTED_MOORS", target_id="EVT_HEATHCLIFF_OPENS_GRAVE",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="moderate",
                   causal_force=4.0, fabula_time=1300),
        CausalEdge(source_id="WORLD_HAUNTED_MOORS", target_id="EVT_HEATHCLIFF_STOPS_EATING",
                   causality_type="chain_reaction", mechanism="psychological", evidence_strength="strong",
                   causal_force=5.0, fabula_time=1900),
    ],

    # ── SPATIAL TOPOLOGY ────────────────────────────────────────────────
    spatial_topology=[
        SpatialEdge(source_id="LOC_WUTHERING_HEIGHTS", target_id="LOC_MOORS"),
        SpatialEdge(source_id="LOC_THRUSHCROSS_GRANGE", target_id="LOC_MOORS"),
        SpatialEdge(source_id="LOC_MOORS", target_id="LOC_WUTHERING_HEIGHTS"),
        SpatialEdge(source_id="LOC_MOORS", target_id="LOC_THRUSHCROSS_GRANGE"),
        SpatialEdge(source_id="LOC_WUTHERING_HEIGHTS", target_id="LOC_THRUSHCROSS_GRANGE"),
        SpatialEdge(source_id="LOC_WUTHERING_HEIGHTS", target_id="LOC_GIMMERTON_KIRK"),
        SpatialEdge(source_id="LOC_THRUSHCROSS_GRANGE", target_id="LOC_GIMMERTON_KIRK"),
        SpatialEdge(source_id="LOC_LIVERPOOL", target_id="LOC_WUTHERING_HEIGHTS"),
    ],

    # ── INFORMATION TOPOLOGY ────────────────────────────────────────────
    information_topology=[
        InformationEdge(source_id="ENT_CATHERINE", target_ids=["ENT_NELLY"],
                        medium="confession", is_encrypted=True,
                        established_at_fabula=700, terminated_at_fabula=700,
                        discovered_at_syuzhet=8, evidence_strength="strong"),
        InformationEdge(source_id="OBJ_CATHERINES_DIARY", target_ids=["ENT_LOCKWOOD"],
                        medium="diary", is_encrypted=False,
                        established_at_fabula=1800, terminated_at_fabula=1800,
                        discovered_at_syuzhet=1, evidence_strength="strong"),
        InformationEdge(source_id="ENT_NELLY", target_ids=["ENT_LOCKWOOD"],
                        medium="oral_history", is_encrypted=False,
                        established_at_fabula=1800, terminated_at_fabula=1800,
                        discovered_at_syuzhet=1, evidence_strength="strong"),
        InformationEdge(source_id="ENT_HEATHCLIFF", target_ids=["ENT_ISABELLA"],
                        medium="seductive_conduct", is_encrypted=True,
                        established_at_fabula=950, terminated_at_fabula=1000,
                        discovered_at_syuzhet=13, evidence_strength="moderate"),
        InformationEdge(source_id="ENT_ISABELLA", target_ids=["ENT_NELLY"],
                        medium="letter", is_encrypted=False,
                        established_at_fabula=1150, terminated_at_fabula=1150,
                        discovered_at_syuzhet=18, evidence_strength="strong"),
        InformationEdge(source_id="ENT_HEATHCLIFF", target_ids=["ENT_LINTON"],
                        medium="threat", is_encrypted=False,
                        established_at_fabula=1500, terminated_at_fabula=1500,
                        discovered_at_syuzhet=22, evidence_strength="strong"),
        InformationEdge(source_id="ENT_LINTON", target_ids=["ENT_CATHY"],
                        medium="coerced_letter", is_encrypted=True,
                        established_at_fabula=1580, terminated_at_fabula=1600,
                        discovered_at_syuzhet=24, evidence_strength="moderate"),
        InformationEdge(source_id="ENT_HARETON", target_ids=["ENT_CATHY"],
                        medium="recited_lessons", is_encrypted=False,
                        established_at_fabula=1850, terminated_at_fabula=1900,
                        discovered_at_syuzhet=27, evidence_strength="strong"),
    ],

    # ── WORLD TRAITS ────────────────────────────────────────────────────
    world_traits={
        "WORLD_CLASS_HIERARCHY": GlobalTrait(
            id="WORLD_CLASS_HIERARCHY",
            name="Yorkshire Gentry / Yeoman / Servant Hierarchy",
            description="The rigid Regency-Yorkshire ordering of gentry (Lintons), yeoman farmers (Earnshaws) and unfree servants (the demoted Heathcliff and the unlettered Hareton). Drives Catherine's calculation that marrying Heathcliff would degrade her, Hindley's racialised contempt, and the marriage strategies that lock the next generation into Heathcliff's hands.",
            category="social_structure",
            magnitude=TraitVector(value=0.9, inertia=0.85, evidence_strength="strong"),
            affected_domains=["social", "psychological"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=2000, triggered_by="EVT_CATHY_HARETON_INHERIT",
                    magnitude=TraitVector(value=0.55, inertia=0.7, evidence_strength="strong"),
                    description="Cathy literacy-tutoring Hareton up out of servant status partially dissolves the local hierarchy."),
            ],
        ),
        "WORLD_PRIMOGENITURE_ENTAIL": GlobalTrait(
            id="WORLD_PRIMOGENITURE_ENTAIL",
            name="Primogeniture and Entail",
            description="The English law of inheritance under which estates pass to male heirs along defined entail clauses. Operates as common-cause parent over Hindley's mastery, Heathcliff's mortgage acquisition of the Heights, and the engineered marriage that delivers the Grange to Heathcliff via Linton.",
            category="governance",
            magnitude=TraitVector(value=0.85, inertia=0.85, evidence_strength="strong"),
            affected_domains=["social"],
        ),
        "WORLD_HAUNTED_MOORS": GlobalTrait(
            id="WORLD_HAUNTED_MOORS",
            name="The Haunted Moors",
            description="The named-latent metaphysics of the moor: a porous boundary between living and dead in which the same wind that batters the Heights also carries Catherine's ghost. Operates as a low-magnitude but high-inertia cosmological substrate, intensifying around Catherine's grave.",
            category="cosmology",
            magnitude=TraitVector(value=0.55, inertia=0.9, evidence_strength="moderate"),
            affected_domains=["psychological", "epistemic"],
            state_timeline=[
                WorldTraitSnapshot(fabula_time=1100, triggered_by="EVT_CATHERINE_DIES",
                    magnitude=TraitVector(value=0.8, inertia=0.95, evidence_strength="strong"),
                    description="Catherine's death seals the supernatural channel that will draw Heathcliff back to her."),
            ],
        ),
    },

    # ── SOCIAL TOPOLOGY ────────────────────────────────────────────────
    social_topology=[
        # Heathcliff ↔ Catherine — the absolute bond.
        RelationshipEdge(
            source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_CATHERINE",
            metrics={
                "affinity": RelationshipMetric(value=1.0, inertia=0.6, evidence_strength="strong", last_updated_fabula=1100),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_CATHERINE", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity": RelationshipMetric(value=1.0, inertia=0.6, evidence_strength="strong", last_updated_fabula=1100),
            },
        ),
        # Hindley ↔ Heathcliff — class-rage and counter-vengeance.
        RelationshipEdge(
            source_entity_id="ENT_HINDLEY", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity":      RelationshipMetric(value=-0.95, inertia=0.55, evidence_strength="strong", last_updated_fabula=400),
                "power_dynamic": RelationshipMetric(value=0.7, inertia=0.7, evidence_strength="strong", last_updated_fabula=400),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_HINDLEY",
            metrics={
                "affinity":      RelationshipMetric(value=-0.95, inertia=0.55, evidence_strength="strong", last_updated_fabula=400),
                "power_dynamic": RelationshipMetric(value=-0.5, inertia=0.7, evidence_strength="strong", last_updated_fabula=400),
            },
        ),
        # Catherine ↔ Edgar — settled affection.
        RelationshipEdge(
            source_entity_id="ENT_CATHERINE", target_entity_id="ENT_EDGAR",
            metrics={
                "affinity": RelationshipMetric(value=0.6, inertia=0.5, evidence_strength="strong", last_updated_fabula=950),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_EDGAR", target_entity_id="ENT_CATHERINE",
            metrics={
                "affinity": RelationshipMetric(value=0.95, inertia=0.6, evidence_strength="strong", last_updated_fabula=1100),
            },
        ),
        # Heathcliff ↔ Edgar — formal hatred.
        RelationshipEdge(
            source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_EDGAR",
            metrics={
                "affinity": RelationshipMetric(value=-0.95, inertia=0.55, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_EDGAR", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity": RelationshipMetric(value=-0.95, inertia=0.55, evidence_strength="strong", last_updated_fabula=1000),
                "fear":     RelationshipMetric(value=0.5, inertia=0.25, evidence_strength="moderate", last_updated_fabula=1000),
            },
        ),
        # Heathcliff → Isabella — instrumental cruelty.
        RelationshipEdge(
            source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_ISABELLA",
            metrics={
                "affinity":      RelationshipMetric(value=-0.85, inertia=0.5, evidence_strength="strong", last_updated_fabula=1000),
                "power_dynamic": RelationshipMetric(value=0.85, inertia=0.7, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_ISABELLA", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity":      RelationshipMetric(value=-0.95, inertia=0.55, evidence_strength="strong", last_updated_fabula=1150),
                "fear":          RelationshipMetric(value=0.95, inertia=0.25, evidence_strength="strong", last_updated_fabula=1150),
                "power_dynamic": RelationshipMetric(value=-0.85, inertia=0.7, evidence_strength="strong", last_updated_fabula=1000),
            },
        ),
        # Heathcliff → Hareton — surrogate son raised in deliberate ignorance.
        RelationshipEdge(
            source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_HARETON",
            metrics={
                "affinity":      RelationshipMetric(value=0.4, inertia=0.5, evidence_strength="moderate", last_updated_fabula=1200),
                "power_dynamic": RelationshipMetric(value=0.85, inertia=0.75, evidence_strength="strong", last_updated_fabula=1200),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_HARETON", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity":      RelationshipMetric(value=0.7, inertia=0.5, evidence_strength="strong", last_updated_fabula=1900),
                "power_dynamic": RelationshipMetric(value=-0.7, inertia=0.7, evidence_strength="strong", last_updated_fabula=1200),
            },
        ),
        # Heathcliff ↔ Linton — owned son.
        RelationshipEdge(
            source_entity_id="ENT_HEATHCLIFF", target_entity_id="ENT_LINTON",
            metrics={
                "affinity":      RelationshipMetric(value=-0.5, inertia=0.5, evidence_strength="strong", last_updated_fabula=1500),
                "power_dynamic": RelationshipMetric(value=0.95, inertia=0.75, evidence_strength="strong", last_updated_fabula=1500),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_LINTON", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "fear":          RelationshipMetric(value=0.95, inertia=0.25, evidence_strength="strong", last_updated_fabula=1500),
                "power_dynamic": RelationshipMetric(value=-0.95, inertia=0.75, evidence_strength="strong", last_updated_fabula=1500),
            },
        ),
        # Cathy ↔ Hareton — resentment to love.
        RelationshipEdge(
            source_entity_id="ENT_CATHY", target_entity_id="ENT_HARETON",
            metrics={
                "affinity": RelationshipMetric(value=0.85, inertia=0.55, evidence_strength="strong", last_updated_fabula=1900),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_HARETON", target_entity_id="ENT_CATHY",
            metrics={
                "affinity": RelationshipMetric(value=0.9, inertia=0.55, evidence_strength="strong", last_updated_fabula=1900),
            },
        ),
        # Cathy → Heathcliff — defiance.
        RelationshipEdge(
            source_entity_id="ENT_CATHY", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity": RelationshipMetric(value=-0.85, inertia=0.5, evidence_strength="strong", last_updated_fabula=1900),
                "fear":     RelationshipMetric(value=0.5, inertia=0.25, evidence_strength="strong", last_updated_fabula=1700),
            },
        ),
        # Nelly → narrative subjects — observer's affection.
        RelationshipEdge(
            source_entity_id="ENT_NELLY", target_entity_id="ENT_CATHERINE",
            metrics={
                "affinity": RelationshipMetric(value=0.55, inertia=0.5, evidence_strength="strong", last_updated_fabula=1100),
            },
        ),
        RelationshipEdge(
            source_entity_id="ENT_NELLY", target_entity_id="ENT_HEATHCLIFF",
            metrics={
                "affinity": RelationshipMetric(value=-0.2, inertia=0.45, evidence_strength="moderate", last_updated_fabula=1900),
                "fear":     RelationshipMetric(value=0.45, inertia=0.25, evidence_strength="moderate", last_updated_fabula=900),
            },
        ),
    ],
)
